### ISSUE TITLE
Grabber refactoring/features

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#1]
Grabber refactoring overview as notice

- [ ] Sync feature level of all grabbers
- [ ] Add a monitor selection mode (at .json) (x11) on multi monitor setups to start the grabber always from another source, fallback to monitor 0 if the requested monitor not found
- [X] connect to kodi check via proto for all grabbers (follow hyperion x11)
- [X] Add to hyperiond a grabber starter which selects automatically the platform depending grabber 
- [X] Add enable option to all grabbers - in case of false don´t start the grabber
- [ ] PixelFormat option is available just for v4l2, x11 and framebuffer - sync it.
- [x] v4l2 is a half exception here, cause it is often used at the same .json. But could also be externalized with a opt-in option for kodi check, if people use kodi just via v4l2.

@Paulchen-Panther @redPanther @penfold42  

new pattern example - feel free to add more
```
	"framegrabber" : 
	{
		"enable" : true,		
		"width" : 64,
		"height" : 64,
		"frequency_Hz" : 10.0,
		"priority" : 890,
		"display" : 0,
		"cropleft" : 0,
		"cropright" : 0,
		"croptop" : 0,
		"cropbottom" : 0
	},
```

**Comment by redPanther** [comment]
-> externalize all grabbers this is already done!

**Comment by brindosch** [comment]
of couse, i forgot i rename it to "remove grabbers from hyperiond" ;)

**Comment by redPanther** [comment]
Would be nice if grabbers had a parent class like the led devices. We need a general grabber app too - to reduce code dups

**Comment by brindosch** [comment]
hm, yes makes sense. Could be also used for KodiCheck to disable or enable the grabber completely? (but would be a little bit a log mess, if you start and stop the grabber more frequent)

**Comment by redPanther** [comment]
.. I updated your issue, to be up to date with latest development.

**Comment by brindosch** [comment]
Thanks

**Comment by penfold42** [comment]
More good work!

I guess the next big 'grep' style cleanup we need to do is find all the exit() and throw() calls.

We don't really want any subcomponent stopping hyperiond

**Comment by redPanther** [comment]
exits should be resolved. The throws are ok as long as there catched. We should remove those throws who are in slots, because that is forbidden by QT.
But only removing throws isn't the whole story, we have to adapt the code logic in those areas. If you want to start - v4l would be fine.

problem: I start hyperion, v4l and stuff all is fine. My pc goes to standby, usb grabber is powerd down and bang v4l throws exception because device is not ready/open .... We can do that better!

**Comment by redPanther** [comment]
display selection make not sense on every grabber. e.g. on raspi there is no dual screen posibility. framebuffer has one device per screen, so display selection is selection the correct device.
I suggest, leave the state as it is ....

**Comment by brindosch** [comment]
yes, afterwards i also thought about some of them. Not everything here makes sene, rather work on the effectengine :D

**Comment by redPanther** [comment]
PixelFormat is only available in v4l. Other grabbers didn't support this.

I think we are done here. Of ourse there is always something to do, but we reached a good state in the grabber section ...

@brindosch If you think the same, then close the issue, or drop a comment
