### ISSUE TITLE
adjustable image to led mapping

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#10]
Hyperion calculates  average color of rectangular screen area to a led. Every led has his area.
Currently calculating average color of whole screen and set this single color to to all leds is not possible. (ok there is a trick, but this waste to much cpu time)
This is one thing ... the other is, not everybody likes average color. There are other algorithms like weighted average, mean vaule, [dominant color](https://hyperion-project.org/threads/output-color-determination-algorithm.117) 

Hyperion needs some transform mechanisms for image to led mapping. We already have "color transform", but this make the transformation after the image processing.

**Comment by redPanther** [comment]
this issue is more or less related to this
https://github.com/hyperion-project/hyperion/issues/72

**Comment by brindosch** [comment]
You are bored? :)

**Comment by redPanther** [comment]
just looked around for v4l things and found that by accident ...

found that: https://github.com/b2un0/kodi-script-hyperion/issues/3
It's not a big problem to add multiple color adjust/transform with only one config. (just a bit monkey work)
We can have a default "color" section and "color" sections per prio-channel. When e.g. v4l is on 901 then make a "color" section with "prio channel assignment" "901" and if this channel is active, then this config is selected and if any other channel is active, take the default ...

**Comment by brindosch** [comment]
possible :)
sounds nice - optional :)

**Comment by tpmodding** [comment]
so we can have for different sources different color adjustments?

**Comment by brindosch** [comment]
the unicolor mode maps from the entire picture one color to all leds, multicolor is the old behaviour.
a per priority mapping of color adjustments (which are not part of the headline for this issue) are not available (yet)

**Comment by redPanther** [comment]
Not exactly, we can limit transform and/or adjustment to v4l source
