### ISSUE TITLE
USB Webcams no longer working

### ISSUE THREAD

**Issue by moe7863** [hyperion-project/hyperion.ng#1000]
- [x] I confirm that this is an issue rather than a question.

## Bug report
USB Webcams are no longer working. I updated from the Alpha 1 build to Alpha 7 and my hyperion environment is no longer functional. Upon enabling debugging I get the two following error messages:

V4L2:/DEV/VI : <ERROR> Throws error nr: VIDIOC_STREAMON error code 5, Input/output error
V4L2:/DEV/VI : <ERROR> Throws error nr: VIDIOC_STREAMON error code 28, No space left on device

#### Steps to reproduce
Upgrade to the Alpha 7 build from the Alpha 1 build 

#### What is expected?
USB webcams should work 

#### What is actually happening?
The USB webcam is detected but not functional in version Alpha 7

#### System
 Hyperion 2.0.0-alpha.7

**Comment by direk** [comment]
It's more like RPi kernel issue. I had the same problem. Upgrading from 5.4.51 to 5.4.65-v7l+ seemed to fix it... just testing.

**Comment by moe7863** [comment]
@direk thank you for your response and advice. It seemed like the RPi4 could not deliver enough power after updating to Alpha 7 but I thought that it would be unlikely. How did you apply extra power to your USB device?

**Comment by moe7863** [comment]
Updated the kernal to 5.4.65-v8+ today and installed a clean build of Alpha 8 with no success. I enabled debugging and got the following error:

2020-09-24T14:18:42.134 hyperiond V4L2:AUTO    : <INFO> found usable v4l2 device: /dev/video0 (Philips SPZ2000: Philips SPZ200)
**_2020-09-24T14:18:42.147 hyperiond V4L2:AUTO    : <ERROR> Throws error nr: VIDIOC_STREAMON error code 28, No space left on device_**

**Comment by direk** [comment]
I have hdmi grabber with two USB ports - one for signal and power (but rpi power is not enough) and second usb port for powering only. So now I am using both and all works fine.

And my kernel is now 5.4.65-v7l+.

**Comment by moe7863** [comment]
Okay so thanks to @direk that my issue is resolved. The old kernel 5.4.51 did not allow for sufficient power/bandwidth for a USB webcam to work. Updating my RSPi4 kernel to 5.4.65-v8+ seems to have done the trick. After you run **rpi-update** to update the kernel, reboot and run **apt full-upgrade** to finish the kernel and software updates. My USB webcam is now working like a charm on the 2.0.0-alpha.8 build. This issue is now being closed.
