### ISSUE TITLE
Alpha 8 - Startup error while loading libcec

### ISSUE THREAD

**Issue by flexage** [hyperion-project/hyperion.ng#1006]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Updated from Alpha 6 to Alpha 8 (reverted from Alpha 7 previously due to bug with APA102 LEDs being unusable)

Hyperion failed to start after install.

Ran `hyperiond` from the terminal to get more information

#### What is expected?

I expected hyperion to start up successfully

#### What is actually happening?

Hyperion failed to start with an error to do with loading the shared libcec library.

`hyperiond: error while loading shared libraries: libcec.so.4: cannot open shared object file: No such file or directory`

#### System

Sorry, couldn't grab the hyperion system info for Alpha 8 as it woudn't start, so I reverted to Alpha 6 and grabbed the system info from there:

**Raspberry Pi 3**

```
Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:11:33
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: en-GB)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 
```

**Comment by flexage** [comment]
I should add that I'd really like to be able to try out Alpha 8, if this is just a missing libcec dependency can I just provide it manually somewhere?

**Comment by jes1417** [comment]
Same issue here on a pi3

**Comment by flexage** [comment]
Sorry, I must be having a bad day - I know how to install dependencies on Linux.

A simple `sudo apt-get install libcec4` solved the missing library for me.

I didn't need to manually install this dependency with the previous releases, I took a look at the dependency make files in the repo, and it looks like it's detecting whether libcec is present at build time... Has something changed on the hyperion.ng build environment for arm? Maybe it has libcec pre-installed by default now and doesn't build it in?

**Comment by jes1417** [comment]
> Sorry, I must be having a bad day - I know how to install dependencies on Linux.
> 
> A simple `sudo apt-get install libcec4` solved the missing library for me.
> 
> I didn't need to manually install this dependency with the previous releases, I took a look at the dependency make files in the repo, and it looks like it's detecting whether libcec is present at build time... Has something changed on the hyperion.ng build environment for arm? Maybe it has libcec pre-installed by default now and doesn't build it in?

same here fixed it with 

```
sudo apt install libcec-dev
```

**Comment by Paulchen-Panther** [comment]
@flexage Did you use the .deb file to install?

**Comment by jes1417** [comment]
I used the .deb to install

**Comment by Paulchen-Panther** [comment]
OK, thanks for the information.
I have fixed this.
https://github.com/hyperion-project/hyperion.ng/commit/510af27e764f0044090627cb86f24bb4610f7206

**Comment by flexage** [comment]
@Paulchen-Panther Great work! Just for reference, yes I also was using the .deb to install

**Comment by nAFutro** [comment]
Ubuntu 20.10 doesn't have the libcec4 package anymore, it's been deleted on 2020-08-18. Can the .deb installer check for libcec6 or just libcec?

**Comment by Paulchen-Panther** [comment]
@nAFutro 
Thanks for the hint.
I have fixed it so I will close this issue for the time being.
Should problems arise again, simply open the issue again.
https://github.com/hyperion-project/hyperion.ng/commit/19c850b4794225b9c0bc8fac6f3c038fd94c93e8

**Comment by MatthewJK** [comment]
Same problem 11/27/2020

Raspberry PI 2 V1.1
used Hyperion-2.0.0-alpha.8-Linux-armv7l.deb
Needed to use apt-get install libcec4  <= project is missing dependencies 

Now Hyperion loads on port on http//::xxx.xxx.xxx.xxx:8090.  

Without libcec4 installed, no services outside of SSH port 22 were running.

**Comment by Lord-Grey** [comment]
@MatthewJK Please retest with the latest release which is alpha 9 ( and not 8). The problem was fixed there. See releasenotes too.

**Comment by MatthewJK** [comment]
I had the same problem with 9, which is why I downloaded and tested with 8.    When 8 had the same issues, I went looking for answers.

**Comment by Lord-Grey** [comment]
Suggest you open a new issue for alpha9 including your platform details, way how you installed and a debug log output.
