### ISSUE TITLE
Raspberry Pi 4 Kodi OSD HDMI Signal Drop

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [hyperion-project/hyperion.ng#1009]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When I open any OSD / Menu in Kodi while playing a video with Hyperion active the hdmi signal will drop and flicker.
I've read that unlimiting the refresh rate of the ui will fix this problem, but this option is not available in kodi 18 (for the raspi4).

#### Steps to reproduce
Install lastest Raspberry Pi OS.
Install Hyperion.NG.
Install Kodi.
Play a video and open the osd.

#### What is expected?
No HDMI signal drops.

#### What is actually happening?
HDMI Signal drops.

#### System

Hyperion Server: 
- Build:       master (GitHub-d663a48c/d4b4158c-1595872836)
- Build time:  Jul 28 2020 14:44:43
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.134 Safari/537.36

**Comment by m-seker** [comment]
Duplicate #954 954
