### ISSUE TITLE
Add invert option to SPI device

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#101]
SPI device needs an option to invert the data and clock pins to support inverting level shifters

**Comment by redPanther** [comment]
any hints how to do that? Is it enough to bitwise invert "data" (line 69)? But what about the clock?

**Comment by penfold42** [comment]
Yep - the hardware might be capable of it but I don't think the kernel driver exposes it.

The SPI mode (0..3) defines the clock polarity and phase so should be easy.

I Have an oscilloscope near my pi right now so I'll try today.

**Comment by redPanther** [comment]
https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md

Supported Mode bits?

**Comment by redPanther** [comment]
http://www.airspayce.com/mikem/bcm2835/group__constants.html#ga8dd7bb496565324800130100e6bf6d86

**Comment by penfold42** [comment]
That's them

I'll modify the low level LedSPIDebice to parse some options from the device section so ALL SPI derived devices magically get the feature without having to modify them all.

**Comment by penfold42** [comment]
https://commons.m.wikimedia.org/wiki/File:SPI_timing_diagram2.svg#mw-jump-to-license
