### ISSUE TITLE
Alpha 8 - WebUI does not work on mobile (iPhone)

### ISSUE THREAD

**Issue by Hukuma1** [hyperion-project/hyperion.ng#1010]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Unable to login to webui at `ip:8090` on mobile device. Works on desktop just fine.

#### Steps to reproduce
`ip:8090`

#### What is expected?
WebUI login

#### What is actually happening?
Error message:
![Hyperion](https://user-images.githubusercontent.com/54511555/93281906-fdda3780-f781-11ea-88fd-daa007784186.PNG)

#### System

Hyperion Server: 
- Build:       (HEAD detached at 08909b8a) (Paulchen-Panther-75963ca9/08909b8a-1600115237)
- Build time:  Sep 14 2020 21:04:51
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.8
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Debian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by tpmodding** [comment]
i cannot confirm it...could you provide some logs in debug mode please

**Comment by Lord-Grey** [comment]
@Hukuma1 I suggest, you delete the cookies and try again.

**Comment by FrostyMisa** [comment]
I update from alpha 6 to 8 and web interface working for me (iOS 14) iPhone and raspberry 4. Alpha 7 I don't know, because here was bug with grabber and led doesn't work, so I skip this version.

**Comment by Hukuma1** [comment]
Works now. I guess @Lord-Grey was right in saying it was a cookie issue. Thanks!
