### ISSUE TITLE
High CPU load (RPI3B+)

### ISSUE THREAD

**Issue by eloo** [hyperion-project/hyperion.ng#1013]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hi,
i'm using the ng project since a while (alpha6) on my RPI3B+ and also after this update i still see a high CPU load caused by hyperiond.

When the system is idling (just in the kodi menu) i see a CPU load of around 20% -  30% for hyperiond.
This seems to be quite a lot to me.

I've also checked the CPU load for the "old" hyperion setup (the kodi plugin) on the same hardware and its only creating a CPU load of around 2% - 5%.

My first thougths was that maybe the internal grabber is producing the load. But also when i disabled everything in the hyperion-UI the CPU load is still around 20%

#### Steps to reproduce
Install and configure hyperion-ng on libreelec on a RPI3B+

#### What is expected?
The new hyperion generation is consumed as less CPU as the previous version has.

#### What is actually happening?
CPU load of hyperiond is quite high

#### System
System: RPI3B+
OS: LibreElec 9.2.4
Platform:	Raspberry Pi
Controller type:	adalight
Instance:	First LED Hardware instance
Ports (flat|proto):	19400 | 19445
Your Hyperion version:	2.0.0-alpha.8
Watched version branch:	Stable
Latest Hyperion version:	2.0.0-alpha.8

I hope i have provided all necessary information you need to investigate this topic. If not please let me know.

Thanks a lot. And by the, i really like the new hyperion!

Best regards
eloo

**Comment by Paulchen-Panther** [comment]
Thanks for your report. But you are aware that Hyperion.ng is not officially supported under LibreELEC?

**Comment by eloo** [comment]
@Paulchen-Panther ah okay.. no i was not aware.. but at least this is also mentioned in the forum where i come from.

but did you think its highly related to libreelec especially? 
If so i can also test a raspbian or hyperbian image.

**Comment by Paulchen-Panther** [comment]
I cannot say whether it is explicitly up to LibreELEC. I haven't paid attention to the CPU usage yet.
You are welcome to test it on Raspbian or HyperBian. No problem.

**Comment by Paulchen-Panther** [comment]
Tested on Raspberry Pi OS. Here the load in idle without internal grabber:
![Raspi_OS](https://user-images.githubusercontent.com/16664240/94176763-daf20680-fe98-11ea-91ed-9650b737ba71.jpg)

And here the CPU loada with internal grabber:
![Raspi_OS](https://user-images.githubusercontent.com/16664240/94177029-3d4b0700-fe99-11ea-8713-fbe84946fb74.jpg)

**Comment by jueank** [comment]
i can report the same issue on a RPi3+ with Retropie 4.6 using Alpha 8. ~20% CPU load.

**Comment by OBrown92** [comment]
I can report the same issue with alpha8 on LibreElec. I'm not able to watch prime video without glitches when running hyperionng.

**Comment by eloo** [comment]
So i've just checked the Haspbian.
With a complete fresh installation i still see a high amount of cpu usage.

![image](https://user-images.githubusercontent.com/2631895/99903048-23c01300-2cc2-11eb-8f7f-464738fca957.png)

Please mind that i have NOT configured any grabbing or LED hardware yet.
This seems pretty high to me for "doing nothing".

I've also tested to disable everything (blackbar detection, internal grabber and so on) but this didn't change the CPU load.

**Comment by Paulchen-Panther** [comment]
Please deactivate the boot and background effect. I think it's because of the effect engine.
Thanks for testing.

**Comment by eloo** [comment]
@Paulchen-Panther 
Okay that was a good hint.
I've just deactivated the boot and background effects.
Result:
Boot effect doesn't have an impact on the CPU Load
But the background effect has dropped the CPU load to around 6%

So its still a bit more than with the "legacy" hyperion but it feels better.
While watching the CPU load increases to 7-9% now .
I guess thats pretty fine.

Maybe it would make sense to have a hint in the web ui that the background effect will increase the CPU load .

Thanks

**Comment by mkrsn** [comment]
Same problem here. hyperiond eats ~20% from one core while idling. After disabling the boot effects and restarting hyperion the usage drops to ~2% while idling.

When enabling the boot effects and restarting hyperion the load goes to ~20% again. After disabling the boot effects and restarting again the load drops to ~2%. So it is reproducible, each time i enable boot effects the load steps up to ~20% idle usage.

Thanks for the hint
