### ISSUE TITLE
failed to switch instance by json command

### ISSUE THREAD

**Issue by Arthur-Koo** [hyperion-project/hyperion.ng#1018]
- [x] I confirm that this is an issue rather than a question.

## Bug report

failed to switch instance by json command on ALPHA 8

#### Steps to reproduce

1) Open SSH
2) type & execute:  echo '{ "command" : "instance",  "subcommand" : "switchTo",  "instance" : 1}' | nc  127.0.0.1 19444
3) get response:  {"command":"instance-switchTo","info":{"instance":1},"success":true,"tan":0}
4) But LED output is still the legacy one, and there's no instance change on Hyperion Web UI.

#### What is expected?

fix or provide a guide

**Comment by dermotduffy** [comment]
Can you clarify what you expect to happen?

Switching the instance via the API just tells the API server that subsequent commands will apply to that instance. It is not expected that the instance switch command would have any impact on the LED output or the Hyperion UI.

**Comment by Arthur-Koo** [comment]
OK.

1) How to set value by your API
2) How to switch instance sucessfully
3) How to re config LED layout by script if there's solution

Thanks!


gu_arthur@hotmail.com
 
From: Dermot Duffy
Date: 2020-09-25 10:56
To: hyperion-project/hyperion.ng
CC: Arthur-Koo; Author
Subject: Re: [hyperion-project/hyperion.ng] failed to switch instance by json command (#1018)
Can you clarify what you expect to happen?
Switching the instance via the API just tells the API server that subsequent commands will apply to that instance. It is not expected that the instance switch command would have any impact on the LED output or the Hyperion UI.

**Comment by Arthur-Koo** [comment]
So you mean it's the same to Hyperion-remote -I, right? I hope it can result on the web UI, all the thing switch to the new assigned instance.  Thanks!

**Comment by dermotduffy** [comment]
Note: I am not a Hyperion developer.

`hyperion-remote -l` just prints out the server info for the selected (default?) instance. I don't know if hyperion-remote has a way to interact with multiple instances.

I don't quite understand that last sentence. What are you trying to achieve?

**Comment by Lord-Grey** [comment]
@Arthur-Koo Do I get you right that you expect issuing an Instance-Switch command via API and then expect that the UI-Screen updates?

In that case, please bear in mind that API is an alternative way to control hyperion itself, e.g. enable/disable an LED-Device.
It is similar what you achieve when using the "Remote control" capabilities manually using the WebUI.

Regardless how you triggered, e.g. disabling an LED-Device you will view the outcome on the web-UI, as hyperion in itself changed its status. i.e. the API to to provide an alternative path controlling hyperon! and it is not to control/update the UI.

The instance switch in the current API is provided to switch the context of the commands, i.e. "against" which instance the subsequent commends are going to be issued. It is similar as you would switch instance via the UI and then use the remote control.

Note: This does not properly work, if you are using individual sessions for each command (as with echo and nc).
Plus it is counter intuitive that you currently cannot run one command against one or all instances.
This is a know issue and planned to be improved.

Hope that clarifies what APIs are used for.

**Comment by Arthur-Koo** [comment]
Thanks @Lord-Grey & @dermotduffy ! I'll try to check and report later.
