### ISSUE TITLE
Delay between start instance and ability to switch to that instance

### ISSUE THREAD

**Issue by dermotduffy** [hyperion-project/hyperion.ng#1019]
- [x] I confirm that this is an issue rather than a question.

## Bug report

If I start an instance via the API and it returns successfully, there is a delay in _actually_ starting that instance. If I quickly attempt to switch to that started instance, it will fail. If I wait a few seconds, it will succeed.

#### Steps to reproduce

   * Stop an instance in the UI.
   * Via the API: Start it, and attempt to switch to it upon receipt of the successful response

Example: Send this in rapid succession:

```
'{"instance": 1, "tan": 2, "command": "instance", "subcommand": "startInstance"}'
'{"instance": 1, "tan": 3, "command": "instance", "subcommand": "switchTo"}'
```

Using my [Hyperion-PY client library](https://github.com/dermotduffy/hyperion-py), here's some output that does this:

```
DEBUG:hyperion.client:Send to server (hyperion:19444-0): {'instance': 1, 'tan': 2, 'command': 'instance', 'subcommand': 'startInstance'}
DEBUG:hyperion.client:Read from server (hyperion:19444-0): b'{"command":"instance-startInstance","success":true,"tan":2}\n'
DEBUG:hyperion.client:Send to server (hyperion:19444-0): {'instance': 1, 'tan': 3, 'command': 'instance', 'subcommand': 'switchTo'}
DEBUG:hyperion.client:Read from server (hyperion:19444-0): b'{"command":"instance-switchTo","error":"Selected Hyperion instance isn\'t running","success":false,"tan":3}\n'
```

There is a way around this, to wait for an instance-update callback before the switch-to -- but I think this is still surprising behavior. I wouldn't expect the call to return success, until it is possible to switch to it.

[Here's some code of my workaround](https://github.com/dermotduffy/hyperion-py/blob/master/README.md#example-starting-and-switching-instances).

#### What is expected?

If the start call returns successful, it feels reasonable that a client should be able to switch to it., 

#### What is actually happening?

The `switchto` is not possible, and returns a failure:
```
WARNING:hyperion.client:Failed Hyperion (hyperion:19444-0) command: {'command': 'instance-switchTo', 'error': "Selected Hyperion instance isn't running", 'success': False, 'tan': 3}
```

**Comment by Paulchen-Panther** [comment]
Can you test PR #1036 please?

**Comment by dermotduffy** [comment]
@Paulchen-Panther Working -- thank you!
