### ISSUE TITLE
The second instance does not start after stopping

### ISSUE THREAD

**Issue by sergoo-lbt** [hyperion-project/hyperion.ng#1021]
The second instance does not start after stopping. I have a raspberry pi 3 b with a hyperbian alpha 8 image. 
There are 2 instances. The first main 107 LEDs and the second wled 14 LEDs. Everything works fine, synchronously, until I disable the main instance. Both of them are turned off, but when the main instance is turned on, wled freezes on any color. It only helps to stop the wled instance in the web ui through the stop button, then after clicking the play button, everything continues to work. Is there any way to fix this? Thank you for your work dear developers! Low bow to you!

**Comment by tpmodding** [comment]
Closed due to ignoring issue template.
Pleas use our issue template.
