### ISSUE TITLE
authorize-requestToken does not respect tan

### ISSUE THREAD

**Issue by dermotduffy** [hyperion-project/hyperion.ng#1022]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Sending an `authorize-requestToken` request should respect the tan parameter. It does not (success and failure show different behaviors -- both incorrect).

#### Steps to reproduce

Send this to the JSON API:

```
{"id": "Sh729", "comment": "whatever", "tan": 27, "command": "authorize", "subcommand": "requestToken"}
```

#### What is expected?

The tan parameter of the response matches the request regardless of success (user approves on UI), or failure (timeout or user deny).

#### What is actually happening?

For success:
   * A tan of 0 is returned:

```json
{"command":"authorize-requestToken","info":{"comment":"whatever","id":"Sh729","token":"<TOKEN>"},"success":true,"tan":0}
```

For failure:
   * A tan of 5 (???) is returned:

```json
{"command":"authorize-requestToken","error":"Token request timeout or denied","success":false,"tan":5}
```

#### System

```
Hyperion Server: 
- Build:       (HEAD detached at 08909b8a) (Paulchen-Panther-75963ca9/08909b8a-1600115237)
- Build time:  Sep 14 2020 21:04:51
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.8
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 
```

**Comment by dermotduffy** [comment]
Note that this is particularly problematic because this particular API call is expected to take a long-time, as it blocks on the user --  thus matching response/request is ~essential.

**Comment by Paulchen-Panther** [comment]
@dermotduffy 
Could you please test the PR #1036 ?

**Comment by dermotduffy** [comment]
@Paulchen-Panther Verified working with that PR (thank you, this was the most important bug fix for me!)
