### ISSUE TITLE
Support 10-step RGB gamma

### ISSUE THREAD

**Issue by MichaelAnders** [hyperion-project/hyperion.ng#1023]
Request: Allow user to specify RGB gamma similar to HDTV's in multiple steps (amount of steps can be defined by the user, e.g. 1 like now or 2, 5, 10, ...) and use the (closest) gamma level that matches the pixel's/regions brightness for calculation of the RGB values for the LED strip.

Why?

Correct color reproduction on a HDTV requires the following, else the resulting picture will not be as expected (I am restricting the list to what is important for my request):

1. Calibrating the RGB values on the HDTV so that they "match" specific color ( WRGBCMY / white, red, green, blue, cyan, magenta, yellow)

2. White balance using RGB gamma calibration (how do colors "mix")

I've done the calibration on my HDTV with calibration hardware & software and the result is astonishing and was well worth the costs and effort for me. However, hyperion is not matching the colors of what I see on the screen and that is very irritating.

Hyperion allows calibrating RGB values for the required colors, resulting in a newly **calculated** RGB color - this is done by displaying an WRGBCMY image.
Hyperion also takes a gamma value to adjust the final RGB values displayed on the LED strip - this is done by displaying a white image.

The problem: gamma is restricted to one value for each R, G and B. This means that no matter how bright a **calculated** RGB color is (value 0-255), the same gamma value will be used for the calculation.

As a result, displaying an image which shows a single RGBCMY color in different brightness next to each other results in hyperion creating incorrect colors: At some brightness level the LED strip just shows one color as the RGB values cannot go any higher.

Additionally, the RGBCMY (no W) may be way off from what it should be as gamma calibration happened only on W.

HDTV televisions on the other hand allow defining multiple RGB gamma values, e.g. in 10 brightness steps (close to black till maximum). This allows defining the RGB gamma in 10 ranges, splitting up a single R/G/B color from a single range 0-255 to 10 ranges (0-24, 25-49, ... -255). This allows perfect RGB calibration for every WRGBCMY color at every brightness level. This is what any calibration hardware & software target. Without this, the colors cannot match.

Every LED strip I've used in the last years was never able to show the correct colors at a given brightness. I can change the gamma when I see red so that red has a nice brightness increase visible in an image with 10 ranges - perfect! But then blue is wrong, or green. A yellow suddenly becomes brownish. Changing gamma for yellow results in perfect yellow matching the TV in the middle of the range, but is still brownish in the higher brightness.

**Comment by Paulchen-Panther** [comment]
Closed due to ignoring request template.
Pleas use our request template.
