### ISSUE TITLE
Support for Shelly RGBW2

### ISSUE THREAD

**Issue by zeschko** [hyperion-project/hyperion.ng#1024]
## Feature request

Add new LED Controller.
Controller Type "shellyrgbw2" in category "Network".

#### What problem does this feature solve?

Can control LED Stripes that are connected to the Shelly RGBW2.

#### What does the proposed API look like?

To update the color of the Shelly RGBW2 following HTTP GET has to be send:
http://{IP}/color/0?turn=on&red={red:0-255}&green={green:0-255}&blue={blue:0-255}&white={white:0-255}&gain={gain:0-100}

#### How should this be implemented in your opinion?

See question before.

#### Are you willing to work on this yourself?

Maybe. If I would implement it, I will need some time to understand the code. I would appreciate if someone who is familiar in this project can implement it.

**Comment by jimwanker** [comment]
The Shelly RGBW does **_not_** work with individually addressable LED strips.  Thus, I don't think it makes sense to add "support" for strips connected to a Shelly RGBW.  Lights connected to a Shelly RGBW would have no way to be reactive to the monitor/TV screen.  I'm not seeing how this makes sense.

**Comment by zeschko** [comment]
That's true, individually addressable strips are not supported with Shelly rgbw2. 
I do not want to use them directly around the TV.
I created an an additional configuration instance with only one single led on the right side of the TV and want to control that Shelly rgbw2 led strip on the right side of my room.

Something similar is possible with the philips hue snyc box. Here you can place single bulbs somewhere in the room.

**Comment by tpmodding** [comment]
i would not add shelly rgb as own device to hyperion....shelly supports mqtt afaik, better to wait till we implement mqtt

if anyone could help us with implementing mqtt would be very cool...

https://github.com/hyperion-project/hyperion.ng/issues/483

**Comment by jimwanker** [comment]
yeah mqtt would be cool.  nice.

**Comment by zeschko** [comment]
Oh nice. Mqtt is much better. Yes, we can close this ticket and focus on mqtt feature instead.
