### ISSUE TITLE
Unable to Compile in Windows WSL instance

### ISSUE THREAD

**Issue by JeffResc** [hyperion-project/hyperion.ng#1026]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Attemp to compile Hyperion using Docker inside of a Windows Ubuntu WSL instance using the provided script at `bin/scripts/docker-compile.sh`.

#### What is expected?
For Hyperion to be compiled.

#### What is actually happening?
```
jeff@DESKTOP-SHC2B57:/mnt/c/Users/jeffr/Documents/GitHub/hyperion.ng/bin/scripts$ bash docker-compile.sh
docker-compile.sh: line 2: $'\r': command not found
docker-compile.sh: line 18: $'\r': command not found
: Permission deniedline 20: /dev/null
docker-compile.sh: line 45: syntax error near unexpected token `$'{\r''
'ocker-compile.sh: line 45: `function printHelp {
jeff@DESKTOP-SHC2B57:/mnt/c/Users/jeffr/Documents/GitHub/hyperion.ng/bin/scripts$ sh docker-compile.sh
: not foundile.sh: 2:
: not foundile.sh: 18:
: Permission denied20: cannot create /dev/null
docker-compile.sh: 20: pushd: not found
docker-compile.sh: 21: Bad substitution
jeff@DESKTOP-SHC2B57:/mnt/c/Users/jeffr/Documents/GitHub/hyperion.ng/bin/scripts$ ./docker-compile.sh
: invalid option
```

#### System

Host System: Windows 10 Version 2004 (OS Build 19041.508)

Docker Desktop: Latest (Unable to find this)

Docker Engine: v19.03.13

Docker Command Line: v19.03.13

Docker WSL Integration: Enabled

WSL Container:
Linux DESKTOP-SHC2B57 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by Paulchen-Panther** [comment]
Could you please run the script in the Ubuntu file system? Not in the mounted Windows file system.
https://prnt.sc/utgb8q

**Comment by JeffResc** [comment]
That's all it was, thank you for the help!
