### ISSUE TITLE
No black borders on AMLogic platform input

### ISSUE THREAD

**Issue by V10lator** [hyperion-project/hyperion.ng#1030]
- [x] I confirm that this is an issue rather than a question.

## Bug report
It seems the image is grabbed before black borders (or Kodi UI elements but that's probably a different issue) are added, then resized to whatever size is setted in the config. So one can't disable black border detection and if they are there the LEDs are off cause stretched on one axis.

#### Steps to reproduce
1) Disable black border detection
2) play a 4:3 video on a 16:9 screen or vice-versa

#### What is expected?
LEDs at the black borders stay off.

#### What is actually happening?
Hyperion is ignoring the black border.

#### System

Hyperion Server: 
- Build:       
- Build time:  Aug  1 2020 02:16:44
- Git Remote:  
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   expert
- Avail Capt:  v4l2,framebuffer,amlogic,qt

Hyperion Server OS: 
- Distribution: CoreELEC (official): 9.2.4.2
- Arch:         arm64
- Kernel:       linux (4.9.113 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**Comment by jasimancas** [comment]
Same error here with Hyperion 2.0.0-alpha.9

**Comment by Portisch** [comment]
A bit late but I tested it now. On CoreELEC 19.2_Matrix-rc2 and alpha.9

I think it's a issue of the grabber as it get stretched in the Webinterface:
<a href="https://ibb.co/ZGdyBJ8"><img src="https://i.ibb.co/ZGdyBJ8/Screenshot-2021-06-15-22-11-38-736-com-android-chrome.jpg" alt="Screenshot-2021-06-15-22-11-38-736-com-android-chrome" border="0"></a>

<a href="https://ibb.co/19F9fZm"><img src="https://i.ibb.co/19F9fZm/IMG-20210615-221305.jpg" alt="IMG-20210615-221305" border="0"></a>

**Comment by Lord-Grey** [comment]
@V10lator Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by V10lator** [comment]
It's still the same with alpha10.

**Comment by V10lator** [comment]
Made a photo showing the issue. This is with black border detection disabled:
![IMG_20210807_213739](https://user-images.githubusercontent.com/1312422/128612070-ece892f1-47b7-45f8-9456-3bfa8f92fa10.jpg)

**Comment by Paulchen-Panther** [comment]
Actually, this issue belongs in the feature request corner.
Since the AMLogic grabber captures the video source material and not the screen, no black borders can be detected because there are none. If the video source material is encoded with black borders, everything should work as intended.
I see that the next thing is that black border detection does not work with AML grabber and 4:3 videos on 16:9 output devices.
I will close here. Please make a feature request. Thanks

Translated with www.DeepL.com/Translator (free version)
