### ISSUE TITLE
CoreElec - S912 arm box - Red and Blue color is switched in the menu, good during playback

### ISSUE THREAD

**Issue by Merwenus** [hyperion-project/hyperion.ng#1041]
- [x] I confirm that this is an issue rather than a question.

## Bug report
In the menu with platform capture, the blue and red color is switched.
When playing a video, the color is in good order and blue is blue red is red, green is green.

#### Steps to reproduce
Install CoreElec 9.2.4.2 and Hyperion.NG 9.2.104 (based on 2.0.0-alpha7) on an S912 android box.
It is a bug since ages with a few armboxes, some people made a fix once in a while, but always different person, and can't reach out them anymore.
More information here: [https://www.hyperion-project.org/threads/coreelec-hyperion-ng.3286/](https://www.hyperion-project.org/threads/coreelec-hyperion-ng.3286/)

#### What is expected?
Red should be red and blue should be blue during playback, and in the menu too.

#### What is actually happening?
In the menu the red and blue color is switched.

**Menu** Red and Blue color is switched
[https://i.imgur.com/CcjBZA1.jpg](https://i.imgur.com/CcjBZA1.jpg)

**During playback** Red is red, playback is good.
[https://i.imgur.com/CcjBZA1.jpg](https://i.imgur.com/5A8N5CM.jpg)

#### System

Hyperion Server: 
- Build:       
- Build time:  Aug  1 2020 02:16:44
- Git Remote:  
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: hu-HU)
- UI Access:   expert
- Avail Capt:  v4l2,framebuffer,amlogic,qt

Hyperion Server OS: 
- Distribution: CoreELEC (official): 9.2.4.2
- Arch:         arm64
- Kernel:       linux (3.14.29 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by Paulchen-Panther** [comment]
ASK HERE: https://discourse.coreelec.org/

**Comment by Merwenus** [comment]
Started with that, they pointed me to come here....

**Comment by tpmodding** [comment]
sorry but we dont provide support for coreelec
