### ISSUE TITLE
USB Capture Color Threshold no Effectz

### ISSUE THREAD

**Issue by z3ky** [hyperion-project/hyperion.ng#1050]
I enabled the Signal Detection option in the USB Capture settings to set color thresholds. Red, green and blue thresholds seems to have no effects. The output to the LEDs doesn't change.
Even with 100% thresholds the grabber forwards the detected colors to hyperion. No matter if it gets a black or colored picture.

Same HW setup  (utv007 grabber chipset) worked with the old Hyperion.

**Comment by Paulchen-Panther** [comment]
Closed due to ignoring issue template.
Please use our issue template.
