### ISSUE TITLE
Idea: dynamic backlight with image main color

### ISSUE THREAD

**Issue by 0rsa** [hyperion-project/hyperion.ng#1064]
Hello,
I currently use a fixed white backlight at 10%.
Can we imagine a dynamic backlight which is colored with the single dominant color of the current image ?
See example:
![hyperion](https://user-images.githubusercontent.com/769750/96947723-3210e880-14e4-11eb-9d1d-a514aef25595.png)

Thank you.

**Comment by Paulchen-Panther** [comment]
Closed due to ignoring feature request template.
Please use our feature request template.
