### ISSUE TITLE
componentstate update missing for LEDDEVICE

### ISSUE THREAD

**Issue by dermotduffy** [hyperion-project/hyperion.ng#1066]
- [x] I confirm that this is an issue rather than a question.

## Bug report

A componentstate update should be generated when LEDDEVICE changes state.

#### Steps to reproduce

In one terminal:

```
echo '{"tan": 1, "command": "serverinfo", "subscribe": ["adjustment-update", "components-update", "effects-update", "leds-update", "imageToLedMapping-update", "instance-update", "priorities-update", "sessions-update", "videomode-update"]}' | nc hyperion 19444
```

In another terminal:

```
echo '{"componentstate": {"component": "LEDDEVICE", "state": false}, "command": "componentstate"}' | nc hyperion 19444
```

This appears to work fine when turning SMOOTHING,  BLACKBORDER. But not for LEDDEVICE at least.

#### What is expected?

A `components-update` should be generated.

#### What is actually happening?

No update is generated.

#### System

```
Hyperion Server: 
- Build:       master (GitHub-ea05c1a2/669b108a-1603380738)
- Build time:  Oct 25 2020 15:15:45
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.8
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Architecture: arm
- CPU Model:    ARMv7 Processor rev 3 (v7l)
- CPU Type:     Raspberry Pi 4 Model B Rev 1.2
- CPU Revision: b03112
- CPU Hardware: BCM2711
- Kernel:       linux (5.4.51-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 
```

**Comment by dermotduffy** [comment]
Hmm. Something really weird going on. This is using a build for @Paulchen-Panther to test https://github.com/hyperion-project/hyperion.ng/pull/1062 -- for some reason LEDDEVICE cannot be toggled even directly on the UI (it toggles, but then it's lost on a reload).

![leddevice](https://user-images.githubusercontent.com/1136829/97113494-02124280-16a8-11eb-9542-a3b3b7058841.gif)

@Paulchen-Panther Is this just me, can you reproduce this?

**Comment by Paulchen-Panther** [comment]
Tested with led device "file":

![device](https://user-images.githubusercontent.com/16664240/97113733-9605fd80-16ec-11eb-8b18-a34626e59e70.gif)

**Comment by dermotduffy** [comment]
On the fresh build I did for #993 , I also **cannot** reproduce this. I'm doing another new build with your latest fix, if I still cannot reproduce this then, I'll close it out (no idea how it happened).

**Comment by dermotduffy** [comment]
I still cannot reproduce this. I will re-open if it happens again reliably.
