### ISSUE TITLE
Move blackborder config to hyperiond.cpp 

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#107]
I searched the reason why the enable option for v4l2 won't work, and now i found this
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/blackborder/BlackBorderProcessor.cpp

should be moved to

https://github.com/hyperion-project/hyperion.ng/blob/master/src/hyperiond/hyperiond.cpp

**Comment by redPanther** [comment]
For my taste the bb'way to hande it is the best. I'm currently updating my fadecandy driver with some things and I do the same.
Another rule for clean code is to avoid very long parameter lists ...

The advantage is: if developer of e.g. bb wants a new config param he_she had to modify only his - bb - files and not the hyperiond.cpp. And he_she had to add less code. Only the class member in the .h file and the line in initializer list.
the "enable" should be implemented inside bb. As addition bb should have a setconfig(const Json::Value &blackborderConfig) function to update class mebers and reinitialize the bbdetector. Then we can create a new config json object in json server and set the new config during runtime.

**Comment by brindosch** [comment]
So kodi should be also removed from hyperion.cpp? The problem is we should consider to implement all (additional?) options the same way. It really doesn't matter how, i am not a devleoper so this is your decision about pro/cons and future functions

**Comment by redPanther** [comment]
let use exercise with leddevices first. look at my fadecandy pr - the setconfig thing and changes in factory.

**Comment by redPanther** [comment]
... should be solved now. enable should work as expected
