### ISSUE TITLE
Fix "QNetworkConfiguration: was declared deprecated"

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#1071]
- [x] I confirm that this is an issue rather than a question.

## Bug report

QNetworkConfigurationManager is deprecated since Qt 5.15 and will be removed in Qt 6.

#### Steps to reproduce

Build hyperion.ng

#### What is expected?

Check for alternative solution and retire code based on QNetworkConfigurationManager.

**Comment by Paulchen-Panther** [comment]
Same aus #869 ?

**Comment by Lord-Grey** [comment]
Duplicate to #869
