### ISSUE TITLE
Wrong direction in LED´s

### ISSUE THREAD

**Issue by guergen1** [hyperion-project/hyperion.ng#1077]
I think the LED´s show wrong direction. 
In the front of the screen my LED are going up, then left, down and at the bottom right way; but in the hyperion LED Layout preview i have them to configure in the reverse direction to show the right video

Hyperion 2.0.0-alpha.8
Hyperion Server OS: 
- Distribution: Ubuntu 20.04.1 LTS
- Arch:         x86_64
- Kernel:       linux (5.4.0-52-generic (WS: 64))

**Comment by tpmodding** [comment]
thanks for ignoring our issue template.
there is nothing wrong, you can choose the direction
