### ISSUE TITLE
Update from old Hyperion

### ISSUE THREAD

**Issue by wuast94** [hyperion-project/hyperion.ng#1080]
How can i update from an old Hyperion installation to the Hyperion.ng? 

I only have the config file and cant import that. Dont want to count all leds again and find out all the configs to set

and how do i remove the old hyperion instance?

**Comment by wuast94** [comment]
Ok closed without any info.. Not even a hint.. 
 Thanks...

**Comment by Paulchen-Panther** [comment]
thanks for ignoring our issue template.

**Comment by wuast94** [comment]
It's not a bug and it's not a feature request.. It's a simple question that I can't find in docs or already opened and closed issues. Why should I discripe bug and API questions when the issue I have is of a complete different topic? 

I have no problems to provide more infos and I don't have any problems to fill out a template.. But the templates doesn't fit my question and I can't fit my question to it

**Comment by Paulchen-Panther** [comment]
https://hyperion-project.org

**Comment by tpmodding** [comment]
there is no update from old to new... the changes are to big...it is not possible, im sorry but you have to count the leds...

if you need support, then visit our forum please. thanks

**Comment by Lord-Grey** [comment]
Maybe stating the obvious...

In the old json config you have the LEDs numbered by the index element.

```
		{
			"index" : 45,
			"hscan" : { "minimum" : 0.5625, "maximum" : 0.6250 },
			"vscan" : { "minimum" : 0.9200, "maximum" : 1.0000 }
		}
```

As the numbering is zero based, the highest index number+1 is your number of LEDs.
I do not understand why you make that big fuss about counting LEDs.
Just read your config file....
