### ISSUE TITLE
AutoMoc error

### ISSUE THREAD

**Issue by ffzwadd** [hyperion-project/hyperion.ng#1085]
- [x] I confirm that this is an issue rather than a question.

## Bug report

AutoMoc error
-------------
"SRC:/libsrc/utils/hyperion-utils_autogen/mocs_compilation.cpp"
includes the moc file "YC2X3M4VYJ/moc_GlobalSignals.cpp",
but a header "YC2X3M4VYJ/GlobalSignals.{h,hh,h++,hm,hpp,hxx,in,txx}"
could not be found in the following directories
  "SRC:/libsrc/utils/hyperion-utils_autogen/YC2X3M4VYJ"
  "SRC:/YC2X3M4VYJ"
  "SRC:/dependencies/include/YC2X3M4VYJ"
  "SRC:/include/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/QtCore/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/mkspecs/linux-openwrt-g++/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/QtGui/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/QtNetwork/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/QtSerialPort/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/QtSql/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/target-mipsel_24kc_musl/usr/include/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/mipsel-openwrt-linux-musl/include/c++/8.4.0/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/mipsel-openwrt-linux-musl/include/c++/8.4.0/mipsel-openwrt-linux-musl/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/mipsel-openwrt-linux-musl/include/c++/8.4.0/backward/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/mipsel-openwrt-linux-musl/sys-include/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/mipsel-openwrt-linux-musl/include/YC2X3M4VYJ"
  "/disk0/CharlesHe/linux/openwrt_new/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/include/YC2X3M4VYJ"

#### Steps to reproduce

build the hyperion.ng in the openwrt

**Comment by Paulchen-Panther** [comment]
We do not support OpenWRT. Closed
