### ISSUE TITLE
Forwarder not working

### ISSUE THREAD

**Issue by blindlight86** [hyperion-project/hyperion.ng#1086]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
source hyperion1 x86_64 forward to hyperion2 raspberry pi.
Got the forwarder working once, but I can't get it done since I reinstall the the system where source hyperion1 is running and hyperion.

**hyperion1**
- ip: 10.0.0.110
- X86_64
- 2.0.0-alpha.8
- USB Capture activated
- Forwarder activated:
    Json target 1: 10.0.0.166:_19444_
    flatbuffer target 1: 10.0.0.166:_19400_
![image](https://user-images.githubusercontent.com/25404088/98674148-56e5d680-2393-11eb-8f6a-973a7158e88f.png)

**hyperion2**
- ip: 10.0.0.166
- raspberrypi 3b
- 2.0.0-alpha.8
- LED device activated (ws2812 flawless)
- JSON Server: _19444_
- Flatbuffers Server: _19400_
![image](https://user-images.githubusercontent.com/25404088/98674487-d83d6900-2393-11eb-88d2-c8d2952d7219.png)

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/25404088/98674568-f5723780-2393-11eb-950d-c26579be3d9f.png)
There supposes to be a flatbuffer from 10.0.0.110 in the origin section. But I don't know it does not.

hyperion1 logs:
 2020-11-10T12:13:28.542Z [hyperiond FLATBUFCONN] (INFO) Connecting to Hyperion: 10.0.0.166:19400
 2020-11-10T12:13:28.542Z [hyperiond NETFORWARDER] (INFO) Forward now to json targets '10.0.0.166:19444'
 2020-11-10T12:13:28.542Z [hyperiond NETFORWARDER] (INFO) Forward now to flatbuffer targets '10.0.0.166:19400'

hyperion2 logs:
 2020-11-10T12:13:36.574Z [hyperiond JSONSERVER] (INFO) Started on port 19444
 2020-11-10T12:13:40.120Z [hyperiond FLATBUFSERVER] (INFO) Stopped
 2020-11-10T12:13:40.122Z [hyperiond FLATBUFSERVER] (INFO) Started on port 19400
 **2020-11-10T12:13:43.156Z [hyperiond FLATBUFSERVER] (DEBUG) (FlatBufferServer.cpp:68:newConnection()) New connection from ::ffff:10.0.0.110**

#### What is expected?
Not sure what else that I misconfig. I want to know how to test the connection between these two hyperion services

**Comment by panec** [comment]
@blindlight86 I have the same issue running 2.0.0-alpha.8 on RPi3B and RPi4. Why had you closed the issue? Have you solved it?

**Comment by raphaabreu** [comment]
Hello @blindlight86  / @panec, I am facing the same issue. Is there a workaround?
