### ISSUE TITLE
Error while running in Docker container

### ISSUE THREAD

**Issue by JeffResc** [hyperion-project/hyperion.ng#1089]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hello,
I've created a custom Dockerfile and image in order to run Hyperion inside of a Docker container. When running the `hyperiond` binary, I received the following error:
```
hyperiond: /hyperion/libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp:26: DispmanxFrameGrabber::DispmanxFrameGrabber(unsigned int, unsigned int): Assertion `_vc_display > 0' failed.

Hyperion caught signal :SIGABRT

Hyperion caught signal :SIGILL
2020-11-11T00:45:48.751 hyperiond CORE         : <ERROR>        /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xf64ef130]
```
I don't plan on using the display grabber, only a USB capture card, so I could remove the feature if supported.

#### Steps to reproduce
Create a Docker image using the following Dockerfile and run the image.
```dockerfile
FROM ghcr.io/hyperion-project/rpi-raspbian:buster as builder

ARG GIT_URL=https://github.com/hyperion-project/hyperion.ng
ARG GIT_TAG=2.0.0-alpha.8
ARG PLATFORM=rpi

RUN mkdir /hyperion && \
    git clone --recursive --branch ${GIT_TAG} ${GIT_URL} /hyperion && \
    cd /hyperion && mkdir build && cd build && \
    cmake -DPLATFORM=${PLATFORM} -DCMAKE_BUILD_TYPE=${PLATFORM} ../ && \
    make -j $(nproc)

FROM balenalib/rpi-raspbian:buster

WORKDIR /root
RUN apt-get update && apt-get install -y libqt5widgets5 libpython3.7 libqt5sql5 libavahi-compat-libdnssd-dev libavahi-core-dev libqt5serialport5-dev libusb-1.0.0 libcec-dev libqt5sql5-sqlite && rm -rf /var/lib/apt/lists/*
COPY --from=builder /hyperion/build/bin/ ./bin/

CMD ["/root/bin/hyperiond"]
```

It seems to work fine when Ubuntu is the host OS, but not when Raspberry Pi OS is the host OS. Since it is running on Docker, this shouldn't have any effect, but it does for some reason. I cannot run Ubuntu on this Pi due to a hardware limitation.

#### What is expected?
For `hyperiond` to run properly.

#### What is actually happening?
The error message given above.

#### System
Running on Raspberry Pi 3a+ running 64-bit Raspberry Pi OS inside of Docker. aarch64/arm64 architecture is running on the host OS as well as in both Docker containers.

**Comment by Paulchen-Panther** [comment]
@JeffResc 
First of all, I would recommend you to set the build type (DCMAKE_BUILD_TYPE) to "Debug" or "Release". 😄 
Then you could, if you don't need it anyway, exclude the DispmanX Grabber (-DENABLE_DISPMANX=OFF).
After that, your container should also run under rpi.

**Comment by JeffResc** [comment]
@Paulchen-Panther Awesome — Looks like that solved the problem, thank you!
