### ISSUE TITLE
Color correction for grabbed picture

### ISSUE THREAD

**Issue by todely** [hyperion-project/hyperion.ng#1091]
Hello
Is it possible to add a feature to correct color of grabber ? (My grabber do not support any custom v4l2 parameters...
Captured picture give me a green dominant coloration.. so when it’s blue on tv led go to a blue/green color...

Thanks !

**Comment by todely** [comment]
Why closed ?

**Comment by Paulchen-Panther** [comment]
Please use our Feature Request Templates.

**Comment by todely** [comment]
> Please use our Feature Request Templates.

Ok i will
Sorry
