### ISSUE TITLE
Color correction for grabbed picture

### ISSUE THREAD

**Issue by todely** [hyperion-project/hyperion.ng#1092]
## Feature request
Add colors RGB, gamma, brightness and saturation correction to applied on capturing hardware flow to avoid bad / not exact color transcription from hyperion to led device

#### What problem does this feature solve?

Solve issue for grabber with bad / incorrect transcode signal and perhaps HDR signal.

#### What does the proposed API look like?

Adding parameters in capture hardware section or in picture processing section

#### How should this be implemented in your opinion?

By adding filter on flow coming from usb capture device or when hyperion analyse picture ?

#### Are you willing to work on this yourself?

Don’t have programming capabilities sorry

**Comment by Lord-Grey** [comment]
Addressed by #1477
