### ISSUE TITLE
Cannot post with a registered and verified e-mail on https://hyperion-project.org/

### ISSUE THREAD

**Issue by SetupCoding** [hyperion-project/hyperion.ng#1093]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After registering with an e-mail and verifying said e-mail on every subsection of the Forum I see the following thing:
(You have insufficient privileges to post here.)

#### Steps to reproduce
Register with an e-mail and verify it. Log in with said e-mail.  You will see `(You have insufficient privileges to post here.)` at the bottom right of the page and will not be able to create a thread.

#### What is expected?
A verified e-mail should be able to post a question.

#### What is actually happening?
The logged in user is not able to create a thread.

#### System

Hyperion Server: 
- Build:       (HEAD detached at 08909b8a) (Paulchen-Panther-75963ca9/08909b8a-1600115237)
- Build time:  Sep 14 2020 20:39:25
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.8
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   expert
- Avail Capt:  qt

Hyperion Server OS: 
- Distribution: Windows 10 Version 1903
- Arch:         x86_64
- Kernel:       winnt (10.0.18362 (WS: 64))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36

**Comment by Paulchen-Panther** [comment]
@tpmodding!

**Comment by tpmodding** [comment]
Spam Filter hat zugeschlagen...sollte nun gehen :-)
