### ISSUE TITLE
WLED device should not turn automatically off after hyperion shutdown

### ISSUE THREAD

**Issue by ProtoxiDe22** [hyperion-project/hyperion.ng#1095]
## Feature request
First of all, i don't really know if this should have been a feature request or bug report, it's is kinda in the middle.
It seems like that when WLED was implemented in Hyperion as a controller type, a new feature was added, that automatically  shuts down the WLED device when Hyperion is closed, this is not always a desidered behaviour, as the user might want to use WLED's lighting when Hyperion is not active.
This has been discussed in Aircoookie/WLED#1308 and it seems like the past behaviour was different (as in, WLED would stay on after Hyperion shut down)

#### What problem does this feature solve?
This would allow to seamlessly interchange between the use of Hyperion and WLED, for those users who only want to use Hyperion for ambient lighting when using certain aplications

#### What does the proposed API look like?
N/A (at least i think so)

#### How should this be implemented in your opinion?
I think the best approach to this would be to have this behaviour configurable in the controller settings, there should be a flag, or something similar, that specifies if WLED should be turned off or not after Hyperion's shutdown

#### Are you willing to work on this yourself?
I'm not knowledgeable enough on this feature

**Comment by Aircoookie** [comment]
@HyperionNG devs: First of all, thank you very much for adding an integration for my software to Hyperion.NG :) That's awesome!

[Here is my proposal](https://github.com/Aircoookie/WLED/issues/1308#issuecomment-727854764) for the in my opinion ideal behavior. Maybe there are better options though, like a user config option.

**Comment by Lord-Grey** [comment]
I will have a look at the topic...
