### ISSUE TITLE
Uses WLED brightness settings instead of full range set in Hyperion settings

### ISSUE THREAD

**Issue by CalvinSchwartz** [hyperion-project/hyperion.ng#1101]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
- Set brightness at boot in WLED the WLED LED settings to a low value (10) or enable “turn off at boot”, then reboot.
- Start Hyperion, connect it to WLED.
- Or set brightness in WLED UI

#### What is expected?
Hyperion uses the maximum brightness setting which is defined in its config (100%) and takes full control of the LEDs independent of the WLED brightness settings.

#### What is actually happening?
Hyperion uses only 10/255 of the maximum brightness (basically the WLED boot brightness) or in case WLED is turned of after boot it stays completely dark.
The WLED UI confirms that Hyperion has control.

#### System

WLED: version 0.10.2 on Wemos D1 mini with WS2812b LEDs

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-gb)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605

**Comment by Lord-Grey** [comment]
@CalvinSchwartz Thanks for sharing this requirement with us. It is not a bug, but might be considered as a feature enhancement going forward.

In the interim, I would suggest you make use of the WLED configuration, where you can already configure this behaviour for streaming input.

Go to the WLED configuration -> Sync. Settings and enable "Force max brightness"

![image](https://user-images.githubusercontent.com/48840279/100197035-0c6b6a80-2efa-11eb-9329-c8b7563da34b.png)

**Comment by CalvinSchwartz** [comment]
Thank you very much, I missed this setting.
It seems to work and turns up the brightness to max. if WLED is set to a brightness greater than 0 at boot.

However if WLED is configured to be turned of or brightness 0 at boot there seems to be a bug.
In this case Hyperion takes control of WLED some seconds after boot, sets the colors according to the current picture captured but stays at this color even when the movie continues. There’s no further change in LED color.

I reproduced this a couple of times but I’m not sure if this is a WLED or Hyperion bug.
Should I add a second issue or is this comment enough @Lord-Grey ?

**Comment by Lord-Grey** [comment]
@CalvinSchwartz You might need to describe your test scenario in more detail....

I was running the following on hyperion alpha and it worked.

1. I disabled power on and brightness on WLED

![image](https://user-images.githubusercontent.com/48840279/100473102-e2729d80-30dd-11eb-903a-37c161aa13d1.png)

2. I started hyperion and started a color feed

3. I restarted WLED

4. WLED catches up with the hyperion color

5. I staredt an effect in hyperion and WLED displays it.

**Comment by CalvinSchwartz** [comment]
Basically I was performing the same steps but used the USB-Grabber as a source instead and watched a movie.
If WLED was turned off at boot WLED catches up with the color (step 4.) but stays there even when the colors of the movie/grabber continue to change.

But I’ll try it again for a week or so and report if the bug continues or if it was just an odd one-time behavior.

**Comment by CalvinSchwartz** [comment]
The "Force max brightness"setting in WLED solved the problem, therefore I would recommend to close this issue and may add a short text to the wiki.\
See #1162
