### ISSUE TITLE
Package dependency errors when installing on RPi 0

### ISSUE THREAD

**Issue by ratbgt77** [hyperion-project/hyperion.ng#1103]
When installing Alpha 9 release on a RPi 0 I get the following package dependency error.

#### Steps to reproduce
 sudo dpkg -i Hyperion-2.0.0-alpha.9-Linux-armv6l.deb

#### What is expected?
Hyperion installation is successful.

#### What is actually happening?
Unpacking hyperion (2.0.0) ...
dpkg: dependency problems prevent configuration of hyperion:
 hyperion depends on libcec4; however:
  Package libcec4 is not installed.

dpkg: error processing package hyperion (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hyperion

**Comment by Paulchen-Panther** [comment]
https://unix.stackexchange.com/a/159114
