### ISSUE TITLE
Color state not updating

### ISSUE THREAD

**Issue by Dewi02** [hyperion-project/hyperion.ng#1105]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Disabling and reenableing the LED Device won't set the previous color again

#### Steps to reproduce
- Set a color
- Switch "LED device" Off
- Switch "LED device" On

#### What is expected?
The LED's should output the previous color again

#### What is actually happening?
The LED's remain disabled until you set a color again

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:34:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         en (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Which LED device is affected?

**Comment by Dewi02** [comment]
APA102

**Comment by Lord-Grey** [comment]
@Dewi02 Could you share a screenshot on the LED-Device configured?
I assume you have "Rewrite Time = 0"?

**Comment by Dewi02** [comment]
Where can I find that?

**Comment by Lord-Grey** [comment]
In the Hyperion UI:
Configuration->LED-Hardware-> Tab LED Controller

**Comment by Dewi02** [comment]
![image](https://user-images.githubusercontent.com/23001695/103921014-41322a80-5112-11eb-9571-1f2767d0360e.png)

There is no "Rewrite Time = 0" tho.

**Comment by Lord-Grey** [comment]
Sorry, please enable Expert settings level

![image](https://user-images.githubusercontent.com/48840279/103922348-e6013780-5113-11eb-8ad2-d74052bc6a31.png)

**Comment by Dewi02** [comment]
![image](https://user-images.githubusercontent.com/23001695/103923054-ed751080-5114-11eb-88c0-e5ad2b2e2a62.png)

**Comment by Lord-Grey** [comment]
Could you check, if the problem persists when you set a Latchtime? e.g. 30

**Comment by Lord-Grey** [comment]
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Dewi02** [comment]
Just updated to alpha 10 and tried it again. 
And the issue is fixed, it works just as expected now :).
