### ISSUE TITLE
Python ModuleNotFoundError: No module named 'math'

### ISSUE THREAD

**Issue by thosoo** [hyperion-project/hyperion.ng#1109]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I have compiled hyperion from sources on a fresh fedora server image in a VM to fix a libcec bug. On start of hyperion I receive the following error log:
```
[thaison@localhost build]$ hyperiond
2020-12-06T19:02:51.517 hyperiond QTGRABBER    : <ERROR> No displays found to capture from!
2020-12-06T19:02:51.645 hyperiond EFFECTENGINE : <ERROR> ###### PYTHON EXCEPTION ######
2020-12-06T19:02:51.647 hyperiond EFFECTENGINE : <ERROR> ## In effect 'Rainbow swirl fast'
2020-12-06T19:02:51.650 hyperiond EFFECTENGINE : <ERROR> ## ModuleNotFoundError: No module named 'math'
2020-12-06T19:02:51.740 hyperiond EFFECTENGINE : <ERROR> ## Traceback (most recent call last):
2020-12-06T19:02:51.743 hyperiond EFFECTENGINE : <ERROR> ## File "<string>", line 1, in <module>
2020-12-06T19:02:51.745 hyperiond EFFECTENGINE : <ERROR> ## File "/usr/local/share/hyperion/lib/python/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
2020-12-06T19:02:51.746 hyperiond EFFECTENGINE : <ERROR> ## ModuleNotFoundError: No module named 'math'
2020-12-06T19:02:51.747 hyperiond EFFECTENGINE : <ERROR> ###### EXCEPTION END ######
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/share/hyperion/lib/python/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
```

#### Steps to reproduce

Compile and install on fedora server.

#### What is expected?

No error messages

#### What is actually happening?

Error messages

#### System

- Fedora 33 server
- Virtual Box VM

Hyperion Server: 
- Build:           master (root-d65453ba/2b34b793-1607260462)
- Build time:      Dec  6 2020 18:54:16
- Git Remote:      https://github.com/thosoo/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: de)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,x11,xcb,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Fedora 33 (Server Edition)
- Architecture:   x86_64
- CPU Model:      Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
- CPU Type:       69
- Kernel:         linux (5.9.11-200.fc33.x86_64 (WS: 64))
- Qt Version:     5.15.2
- Python Version: 3.9.0
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0

**Comment by Paulchen-Panther** [comment]
Was it compiled via Docker or native?

**Comment by thosoo** [comment]
> Was it compiled via Docker or native?

It was compiled native

**Comment by Paulchen-Panther** [comment]
What dependencies do you have installed?

**Comment by thosoo** [comment]
> What dependencies do you have installed?

I tried to copy in here all the relevant commands I have done to compile it. I can also paste a list of all installed packages if needed..
```
[root@localhost ~]# dnf install git
[root@localhost ~]# git clone https://github.com/thosoo/hyperion.ng
[root@localhost ~]# git submodule init
[root@localhost ~]# git submodule update

[root@localhost ~]# dnf -y groupinstall "Development Tools"
[root@localhost ~]# dnf install python3
[root@localhost ~]# dnf install python3-devel
[root@localhost ~]# dnf install qt-devel
[root@localhost ~]# dnf install qt5-qtbase-devel
[root@localhost ~]# dnf install qt5-qtserialport-devel
[root@localhost ~]# dnf install libjpeg-devel
[root@localhost ~]# dnf install xrandr
[root@localhost ~]# dnf install xcb-util-image-devel
[root@localhost ~]# dnf install qt5-qtx11extras-devel
[root@localhost ~]# dnf install turbojpeg-devel
[root@localhost ~]# dnf install libusb-devel
[root@localhost ~]# dnf install avahi-libs
[root@localhost ~]# dnf install avahi-compat-libdns_sd-devel
[root@localhost ~]# dnf install xcb-util-devel
[root@localhost ~]# dnf install dbus-devel
[root@localhost ~]# dnf install openssl-devel
[root@localhost ~]# dnf install fedora-packager rpmdevtools gcc
[root@localhost ~]# mkdir build
[root@localhost ~]# cd build
[root@localhost ~]# cmake -DCMAKE_BUILD_TYPE=Release ..
[root@localhost ~]# make
[root@localhost ~]# make install/strip
```

**Comment by Paulchen-Panther** [comment]
There seems to be a problem with the python modules on Fedora. Since you have compiled on this system anyway, you can solve the problem by deleting the python folder in the hyperion directory.

`sudo rm -R /usr/local/share/hyperion/lib/python`

**Comment by thosoo** [comment]
This workaround worked. Wunderbar, danke!

**Comment by Paulchen-Panther** [comment]
Du kannst auch gerne noch ein PR erstellen, das den Usern hilft Hyperion unter Fedora zu kompilieren (CompileHowto.md).
Vielen dank.

**Comment by thosoo** [comment]
> Du kannst auch gerne noch ein PR erstellen, das den Usern hilft Hyperion unter Fedora zu kompilieren (CompileHowto.md).
> Vielen dank.

Will do

**Comment by Paulchen-Panther** [comment]
Reopened because problem still exists.
