### ISSUE TITLE
Smoothing improvement (small)

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#111]
@redPanther 
If you may have some time later, there is a small issue now. If you use the backlight option it is much more noticebale.
The smoothing should stop the output not immediately after "no change" -> stop output trigger.
It would be better to keep the output flow -until- the configured smoothing time is reached.

If you have a fast color change: the leds "hang" in a smoothed state between for example blue and black. (If you go from a blue to a black picture)

Thank you

**Comment by redPanther** [comment]
The output is not stopped imidiatly, but perhaps we have to double the time ....

I'm thinking about a qtimer trigger for about 10 seconds + 2* smooth time. 

I'm not satisfied with the modification I've made in the past. For my taste it is better always send in a defined frequency, regardless if there is new data or not. If the leds receives noise from somewhere, the leds would be refreshed and set to its last state. The current implemention wouldn't do that.
Perhaps an option to enable continous led refresh would be the best. I'll have a look ....

**Comment by redPanther** [comment]
whats your smoothing settings? problems occured when updateDelay>0. Hopefully this is resolved now

**Comment by brindosch** [comment]
update delay is 0.
That you delay the output explains why it is more a very light blue, instead something in between (a brighter blue - hald black half blue)

**Comment by redPanther** [comment]
when delay=0 then my latest fix won't work. I disable writing to leds, when smoothing gets no new input.

problem for delay>0 was that the buffer wasn't flushed. e.g. if delay=10, then output stopped 10 frames before input stops. This should work now.

**Comment by brindosch** [comment]
just a small report, i could easy recreate the issue when using kodicheck. If the state switches from background-effect to "grabbing" but the player is in pause mode. You see very good the effect mood blobs. We should enable continous as default.

**Comment by brindosch** [comment]
This is done
