### ISSUE TITLE
Idle mode effects do not work properly when more than 1 instance is active

### ISSUE THREAD

**Issue by mathman** [hyperion-project/hyperion.ng#1113]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Create three instances
Use hyperion android grabber or other remote control
Stop remote control.

#### What is expected?
When remote control is stopped the leds use effect or color who was chosen for idle mode.

#### What is actually happening?
If i stop hyperion android grabber the leds stay with the last color.
They do not use the chosen effect for idle mode.
When i re apply black color for idle mode it come back to atomic swirl and i need to re apply a second time black color effect.

#### System

Hyperion Server: 
- Build:           master (GitHub-08edd880/a42aae44-1606253282)
- Build time:      Dec  1 2020 11:45:07
- Git Remote:      https://github.com/hyperion-project/hyperion.ng.git
- Version:         2.0.0-alpha.9
- UI Lang:         en (BrowserLang: fr-FR)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Which LED types for the 3 instances?

**Comment by mathman** [comment]
Leds types : Sk9822

Instance 1 : sk9822 from gpio
Instance 2 : udp raw with esp8266
Instance 3 : udp raw with esp8266

**Comment by mathman** [comment]
This bug work only with color effect.

If i choose "standard" effect the leds work with it.
