### ISSUE TITLE
Alpha 9 .Deb libcec4 dependency?

### ISSUE THREAD

**Issue by testbughub** [hyperion-project/hyperion.ng#1123]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I installed the alpha 9 x86_64.deb, and it complains about not finding libcec4. 
Seem to be similar to https://github.com/hyperion-project/hyperion.ng/issues/1006, but it was mentioned that a new issue should be posted for alpha 9.

#### Steps to reproduce
```
sudo dpkg -i Hyperion-2.0.0-alpha.9-Linux-x86_64.deb
```

#### What is expected?
I'm assuming it should need libcec6 instead. 

#### What is actually happening?

```
The following packages have unmet dependencies:
    hyperion : Depends: libcec4 but it is not installable
```
It still works though, but because of the apt error, I have to keep it held.
EDIT: I'm not getting this error after building from source.

#### System

```
Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:01:42
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,x11,xcb,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Ubuntu 20.10
- Architecture:   x86_64
- CPU Model:      Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
- CPU Type:       94
- Kernel:         linux (5.8.0-33-generic (WS: 64))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Linux; Android 9; SM-T585) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101
```

**Comment by i7i5** [comment]
Same after docker-compile.sh installation, when u try to run hyperiond :)
`./hyperiond: error while loading shared libraries: libcec.so.4: cannot open shared object file: No such file or directory`

**Comment by Paulchen-Panther** [comment]
It is fixed. The following two commands are required to install the Hyperion deb file:
sudo dpkg -i /path/to/hyperion_file.deb
sudo apt-get install -f

Why the second command is necessary is described here:
https://unix.stackexchange.com/a/159103

**Comment by testbughub** [comment]
I did try that, but when I did, it wanted to remove hyperion altogether.

**Comment by unfaceit** [comment]
I have experienced the same issue. 
Raspberry Pi 4b 8Gb + Ubuntu Desktop 20.10. 
`libcec6` and `libcec-dev` was installed. 
Running `sudo dpkg -i Hyperion-2.0.0-alpha.9-Linux-aarch64.deb` errors out due to missing libcec4: 
```
Selecting previously unselected package hyperion.
(Reading database ... 182396 files and directories currently installed.)
Preparing to unpack Hyperion-2.0.0-alpha.9-Linux-aarch64.deb ...
---Hyperion ambient light preinst ---
Unpacking hyperion (2.0.0) ...
dpkg: dependency problems prevent configuration of hyperion:
 hyperion depends on libcec4; however:
  Package libcec4 is not installed.

dpkg: error processing package hyperion (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hyperion
```
Following `sudo apt-get install -f` prompts/ removes Hyperion: 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  cryptsetup-bin dctrl-tools dmeventd dmraid dpkg-repack efibootmgr
  gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 grub-common grub-efi-arm64
  grub-efi-arm64-bin grub-efi-arm64-signed grub2-common kpartx kpartx-boot
  libdebian-installer4 libdevmapper-event1.02.1 libdmraid1.0.0.rc16
  liblvm2cmd2.03 libreadline5 libtimezonemap-data libtimezonemap1 lvm2
  os-prober python3-icu python3-pam rdate thin-provisioning-tools
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  hyperion
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 208 MB disk space will be freed.
Do you want to continue? [Y/n] 
```
I ran into the same problem trying to install Hyperion on Raspberry Pi OS 64bit yesterday. 
Can we reopen the issue?

**Comment by geovannimp** [comment]
I installed with this commands:

```
sudo apt install libcec6
sudo dpkg -i --force-depends ./Hyperion-2.0.0-alpha.9-Linux-x86_64.deb
```

**Comment by barthand** [comment]
I believe this still requires a fix.

Ubuntu 20.10 comes with `libcec6`, while hyperion.ng-alpha-9 seems to still require `libcec4`:

```
$ sudo dpkg -i Hyperion-2.0.0-alpha.9-Linux-x86_64.deb
Selecting previously unselected package hyperion.
(Reading database ... 252659 files and directories currently installed.)
Preparing to unpack Hyperion-2.0.0-alpha.9-Linux-x86_64.deb ...
---Hyperion ambient light preinst ---
Unpacking hyperion (2.0.0) ...
dpkg: dependency problems prevent configuration of hyperion:
 hyperion depends on libcec4; however:
  Package libcec4 is not installed.

dpkg: error processing package hyperion (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hyperion
```

Yes, installing with `--force-depends` forces it to install properly, but then one is not able to use apt anymore:

```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 hyperion : Depends: libcec4 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

I haven't found any other way than to uninstall Hyperion in order to use `apt` again.

@Paulchen-Panther Can we reopen this issue and solve this by e.g. making deb package require either `libcec4` or `libcec6` (which for Hyperion purpose seem to be compatible, because despite these dependencies problem, software works just fine)?

And by the way, big THANK YOU for this great piece of software. :pray:

**Comment by Paulchen-Panther** [comment]
The bug fix has been in the master since [December 27, 2020](https://github.com/hyperion-project/hyperion.ng/issues/1123#issuecomment-751519429).
Proof: https://prnt.sc/zgp74o
