### ISSUE TITLE
V4L Errors while using DroidCam remotely

### ISSUE THREAD

**Issue by psychowood** [hyperion-project/hyperion.ng#1126]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I'm trying to use droidcam (Android application + v4l2loopback device) as an input device for Hyperion NG, but I get some errors.

#### Steps to reproduce
- Install [droidcam for linux](https://www.dev47apps.com/droidcam/linux/)
- Install [droidcam app](https://www.dev47apps.com/)
- Run Android/iOS app, get current IP:PORT
- Run cli application (droidcam-cli IP PORT) in the hyperion server 

#### What is expected?

The video grabber is working

#### What is actually happening?

Hyperion does not load the video device, throwing an error:

> **2020-12-29T01:24:34.680Z** [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:87:uninit()) uninit grabber: /dev/video1
 **2020-12-29T01:24:34.680Z** [hyperiond V4L2:/DEV/VIDEO0] (INFO) Stopped
 **2020-12-29T01:24:34.680Z** [hyperiond V4L2:/DEV/VIDEO0] (INFO) configured v4l device: /dev/video0
 **2020-12-29T01:24:34.680Z** [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:582:init_device()) Set device input to: loopback
 **2020-12-29T01:24:34.680Z** [hyperiond V4L2:/DEV/VIDEO0] (ERROR) Throws error nr: VIDIOC_S_FMT error code 22, Invalid argument
 **2020-12-29T01:24:34.680Z** [hyperiond V4L2:/DEV/VIDEO0] (INFO) Started
 **2020-12-29T01:24:34.681Z** [hyperiond V4L2:/DEV/VIDEO0] (ERROR) Throws error nr: VIDIOC_DQBUF error code 22, Invalid argument
 **2020-12-29T01:24:34.681Z** [hyperiond V4L2:/DEV/VIDEO0] (INFO) Stopped

#### Additional infos

V4L is correctly configured locally, another USB camera (PS3 Eye) works flawlessly.

v4l2-ctl --all output of both cameras, just in case this could be useful. Diff also saved [here](https://www.diffchecker.com/II02jzkh) for 1 month.

**DroidCam**

````
Driver Info:
	Driver name      : v4l2 loopback
	Card type        : Dummy video device (0x0000)
	Bus info         : platform:v4l2loopback-000
	Driver version   : 4.19.160
	Capabilities     : 0x85208003
		Video Capture
		Video Output
		Video Memory-to-Memory
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x85208003
		Video Capture
		Video Output
		Video Memory-to-Memory
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
Priority: 0
Video input : 0 (loopback: ok)
Video output: 0 (loopback in)
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : 'YU12' (Planar YUV 4:2:0)
	Field             : None
	Bytes per Line    : 640
	Size Image        : 460800
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Limited Range)
	Flags             :
Format Video Output:
	Width/Height      : 640/480
	Pixel Format      : 'YU12' (Planar YUV 4:2:0)
	Field             : None
	Bytes per Line    : 640
	Size Image        : 460800
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Limited Range)
	Flags             :
Streaming Parameters Video Capture:
	Frames per second: 30.000 (30/1)
	Read buffers     : 8
Streaming Parameters Video Output:
	Frames per second: 30.000 (30/1)
	Write buffers    : 8

User Controls

                    keep_format 0x0098f900 (bool)   : default=0 value=0
              sustain_framerate 0x0098f901 (bool)   : default=0 value=0
                        timeout 0x0098f902 (int)    : min=0 max=100000 step=1 default=0 value=0
               timeout_image_io 0x0098f903 (bool)   : default=0 value=0`
````

**PS3 Eye**

````
Driver Info:
	Driver name      : ov534
	Card type        : USB Camera-B4.09.24.1
	Bus info         : usb-0000:02:01.0-1
	Driver version   : 4.19.160
	Capabilities     : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x05200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (ov534: ok)
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : 'YUYV' (YUYV 4:2:2)
	Field             : None
	Bytes per Line    : 1280
	Size Image        : 614400
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Limited Range)
	Flags             :
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 15.000 (15/1)
	Read buffers     : 2

User Controls

                     brightness 0x00980900 (int)    : min=0 max=255 step=1 default=0 value=0 flags=slider
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=32 value=32 flags=slider
                     saturation 0x00980902 (int)    : min=0 max=255 step=1 default=64 value=64 flags=slider
                            hue 0x00980903 (int)    : min=-90 max=90 step=1 default=0 value=0 flags=slider
        white_balance_automatic 0x0098090c (bool)   : default=1 value=1
                       exposure 0x00980911 (int)    : min=0 max=255 step=1 default=120 value=120 flags=inactive, volatile
                 gain_automatic 0x00980912 (bool)   : default=1 value=1 flags=update
                           gain 0x00980913 (int)    : min=0 max=63 step=1 default=20 value=20 flags=inactive, volatile
                horizontal_flip 0x00980914 (bool)   : default=0 value=0
                  vertical_flip 0x00980915 (bool)   : default=0 value=0
           power_line_frequency 0x00980918 (menu)   : min=0 max=1 default=0 value=0
                      sharpness 0x0098091b (int)    : min=0 max=63 step=1 default=0 value=0 flags=slider

Camera Controls

                  auto_exposure 0x009a0901 (menu)   : min=0 max=1 default=0 value=0 flags=update
````

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:01:42
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: it)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,x11,xcb,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Debian GNU/Linux 10 (buster)
- Architecture:   x86_64
- CPU Model:      Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
- CPU Type:       58
- Kernel:         linux (4.19.0-13-amd64 (WS: 64))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by Paulchen-Panther** [comment]
Please open a feature request. The V4L2 format YU12 is currently not supported. Many Thanks
