### ISSUE TITLE
Cannot use custom settings for USB capture when using multiple LED Instances

### ISSUE THREAD

**Issue by billroemhild** [hyperion-project/hyperion.ng#1131]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Configure two LED Instances

#### What is expected?
Use the custom settings for USB capture for each LED instance.

#### What is actually happening?
When I had a single LED instance running I was able to choose which capture device along with the ability to change all settings.  I can still do this, but only one of the two LED instances will work.  If I change both instances back to "Automatic"  everything works as expected except I can't make custom changes.  I've been dropping the resolution down to 320x240 to speed things up along with limiting flickering (Not using smoothing as it's not what I want to do).  I even noticed that when I added the second LED instance, my custom changes from the first instance were changed to automatic for the USB capture. 

Running two "WLED devices over IP" with a "UVC Camera (534d:2109): FY HD v"  camera.

Is this by design?  If so, please close this out with a note.

#### System
Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 400 Rev 1.0
- CPU Revision:   c03130
- CPU Hardware:   BCM2711
- Kernel:         linux (5.4.72-v7l+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by Paulchen-Panther** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16664240/103403643-2fb8b380-4b51-11eb-9917-71c5d59716cb.png)

**Comment by Paulchen-Panther** [comment]
That still seems to be a problem in the database / WebUI. Thank you for your feedback

**Comment by billroemhild** [comment]
Kept hacking on it for a bit.  Found that if I set the capture device to custom and set the device manually to "/dev/video0" for both LED instances, everything works as expected.  So only seeing the issue when selecting the video capture device directly.
