### ISSUE TITLE
LedLayout: allow dragging led corners and/or single leds

### ISSUE THREAD

**Issue by psychowood** [hyperion-project/hyperion.ng#1137]
#### What problem does this feature solve?

Handling non-standard Camera grabbers, possibily non linear(fisheye) lenses too.
Partially connected to #1136

#### What does the proposed API look like?

It's a frontend-only change.

#### How should this be implemented in your opinion?

- When dragging a corner led, the whole layout should move. This would simply change the already available values in the Led Layout -> Advanced section (Point Top Left, Top Right, Bottom Left, Bottom Right)

- When dragging non-corner leds, reposition that specific led alone, editing directly the generated/current led Configuration.

- Bonus point, draw the whole contour with the mouse and redistribute the leds

#### Are you willing to work on this yourself?

I've got some ideas but I'm not sure my free time would allow me to :)

**Comment by wube1** [comment]
Iam so waiting for this feature to be implemented. You have no idea how much that would change the usability of the Hyperion. So much potential!! USB CAM as a capture right now is great but man when this is finally out. Not sure why this has not been a part of alpha10 release. I'm no coder but is it that hard to implement?

**Comment by wube1** [comment]
Hi again, I know it takes time and effort which i really appreciate cause without it we (community) wouldn't be able to use Hyperion. May I ask when this feature could be possible implemented?

**Comment by Paulchen-Panther** [comment]
@wube1 
It is comming soon:
![trapezoid](https://user-images.githubusercontent.com/16664240/132893651-12282114-a0ab-4318-9f17-c0b83612290a.gif)

**Comment by wube1** [comment]
@Paulchen-Panther 
That is fantastic news :) , thank you!!

**Comment by wube1** [comment]
Hi @Paulchen-Panther,
Would it be possible to add more dragging points in next release? I mean not only the corners but also mid way along the leds on each side?

**Comment by W2APS** [comment]
Is there any possibility this can be applied to the Matrix Layout (LED Wall) also?  I'm looking to use Hyperion with WLED to create low res peripheral expansion displays off to the side walls and ceiling of a large main display.  Without having an easy adjust like this I'm going to have to locate 1800 LEDs per panel. (72x25 pixels, 500x1000mm, 75% transparent).

**Comment by Lord-Grey** [comment]
@W2APS would you mid sharing a sketch how the LEDs should be arranged and addressed?
It is hard to visualize from the description and would be helpful to advise on options to make it happen.

**Comment by W2APS** [comment]
I'll do a couple of drawings tomorrow and put them on here. I think I'll need to do a physical LED layout, a virtual LED layout and the virtual layout overlaid on the video capture source. 👍
