### ISSUE TITLE
WS281B PWM not functional unless hyperiond starts as root

### ISSUE THREAD

**Issue by jeffh0821** [hyperion-project/hyperion.ng#1138]
- [x] I confirm that this is an issue rather than a question.

## Bug report

WS281B PWM not functional unless hyperiond starts as root

#### Steps to reproduce

1. Fresh Raspberry Pi OS (Debian Buster) install
2. RPi DEB install automatically enables/starts service hyperiond@Pi. (awful practice)
3. Configure Hyperion with USB capture and RPi WS2812B PWM LED Hardware
4. WS281B PWM will not initialize as user Pi
5. Stop/disable hyperiond@pi service and enable/start hyperiond@root service
6. Re-configure Hyperion capture and RPi WS2812B PWM.
7. Everything works.

#### What is expected?

- Hyperion RPi DEB installs SHOULD NOT automatically enable/start services
-- Additionally, RPi DEB packages SHOULD NOT enable SPI (you don't disable audio which is required for PWM) 
- WS2812B libraries should function as non-root user

#### What is actually happening?

Hyperion RPi DEB install are automatically enabling/starting services under a user that is not functional for some LED Hardware services.

#### System
Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:34:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.79-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by penfold42** [comment]
Suggest not fixing this and just documenting the limitations.
The current behaviour will suit the majority of users.

**Comment by jeffh0821** [comment]
I agree, the issue of the rpi_ws281x library not being able to leverage PWM as a non-root user is unlikely to be fixed.

However, I would argue RPi/WS2812b/PWM is used by far more users than you are acknowledging. A compromise should be to DOCUMENT the post-installation steps (service for root if using PWM, service for user if not, disabling audio for RPi users using PWM, enabling SPI for SPI users, etc..) and NOT just set them arbitrarily in the DEB package. Having an install package "do stuff" that might need to be undone to make it work for a sizable user population is VERY bad form. Particularly with RPi and the config.txt entries which should NEVER be programmatically set and systemd services which should be left to the user to decide how to implement.

**Comment by Lord-Grey** [comment]
@jeffh0821 As you seem to be familiar with packages, why do you not create a PR, which includes the questions to allow a user to disable the defaults and drive the configuration?

**Comment by jeffh0821** [comment]
@Lord-Grey I would be happy to look at the cmake scripts and rip out the post-install logic. But as a maintainer, shouldn't you take a position on if this should be done and why?

**Comment by Lord-Grey** [comment]
@jeffh0821 As @penfold42 outlined, many hyperion user are not even able to spell Linux.
For them the current way of installation is the most convenient one to be successful.

I appreciate that there are other users which have different setup.
As the current hyperion team has only two developers any support is welcome (hence my suggestion or a PR) ....

Nevertheless, my ask would be not just to "rip-out" stuff, but make installation scrips more user friendly while supporting one (or more) default installation scenarios (given the rationale above) and more customized ones.

**Comment by jeffh0821** [comment]
@Lord-Grey Any PR I submit would be to bring the Hyperion.ng packages back into compliance with widely-accepted packaging guidelines. This would mean removing the postinst service enablements and RPi config.txt configurations as the current scripts render the application broken under certain typical configurations (RPi and PWM) and enable unnecessary modules (dtparam=spi=on) for those same typical configurations.

I would be happy to replace them with system dialogs explaining post-installation options, but it should be noted that many package managers will not expose these instructions. They will need to be placed in the documentation (wiki) which I would also be happy to write.

I think the recommended approach for users who are not even able to spell Linux should be HyperBian. Within HyperBian you could proactively enable whatever services would be most beneficial for the majority of users.

Question: What is the position on just running the Hyperion.ng service as root by default? Many applications run as a service under the root user and it would work for ALL configurations. This would almost completely eliminate this debate (I still think having a package make config.txt changes is REALLY bad).

**Comment by Paulchen-Panther** [comment]
> Question: What is the position on just running the Hyperion.ng service as root by default? Many applications run as a service under the root user and it would work for ALL configurations. This would almost completely eliminate this debate (I still think having a package make config.txt changes is REALLY bad).

We already had this discussion here:
https://github.com/hyperion-project/hyperion.ng/issues/5

If you can think of something better (except root user), please do a PR.

**Comment by jeffh0821** [comment]
@Paulchen-Panther I'm glad there was debate here. Unfortunately root is a real requirement for the rpi_ws281x library when utilizing PWM. @penfold42 acknowledged this in the rpi_ws281x git repo.

Current package DOES NOT and CANNOT WORK for RPi/PWM without reconfiguration of the systemd/Init services.

I think this has been beat to death now. I will not submit a PR that goes against standard practices (non-functioning application for standard use cases) but which seems to be acceptable to the maintainers.

I will offer to create additional documentation to the wiki if that is acceptable.

**Comment by jabberwock** [comment]
So how do we remove the @pi service and replace it with @root ?

**Comment by jabberwock** [comment]
sudo systemctl disable --now hyperion@pi
sudo systemctl enable --now hyperion@root


Other docs mention 'hyperiond' (notice the d) but that won't work for me. The above does.

**Comment by Paulchen-Panther** [comment]
`sudo systemctl disable --quiet hyperion@pi.service --now`
`systemctl enable --quiet hyperion@root.service --now`
