### ISSUE TITLE
Add option to skip first LEDs when setting Layout

### ISSUE THREAD

**Issue by c-thiel** [hyperion-project/hyperion.ng#1141]
#### What problem does this feature solve?
Currently, there is no option to skip the first LEDs in the Classic Layout. While the Input position can be defined perfectly, the first LED is always 0. However, in my setup the first LED is number ~35, the strip then goes around the TV and closes with LED 265 of 300.

#### What does the proposed API look like?
Not sure what needs to be changed.

#### How should this be implemented in your opinion?
Add option "First LED Number" to Classic Layout.

#### Are you willing to work on this yourself?
Currently not, maybe in the future.

**Comment by Lord-Grey** [comment]
@c-thiel Not sure, if I get the problem space...

If you do a standard config LED 0 is at top left

![image](https://user-images.githubusercontent.com/48840279/104107391-0966e680-52bc-11eb-9f4f-c6840da2cf7b.png)

If for argument sake the LED strip starts at position 5
You configure the "Input Position accordingly"

![image](https://user-images.githubusercontent.com/48840279/104107404-2ef3f000-52bc-11eb-9349-b45f33235eb7.png)

If you the have the need to define a gap, you can set a gap length and position:

![image](https://user-images.githubusercontent.com/48840279/104107439-6fec0480-52bc-11eb-8e88-7d812b336bcb.png)

If the above does not address your needs, a visual representation of your problem might be helpful.

**Comment by penfold42** [comment]
I think the OP is wants to skip the first 34 LEDs and have Hyperion set them to black.

**Comment by Lord-Grey** [comment]
In summary, the need is to blacklist a certain amount of LEDs which are ignored (being black) while watching TV. For other scenarios all LEDs are used.

@c-thiel In the interim, you can already achieve this via manual configuration 

see https://hyperion-project.org/threads/effects-help-sk6812.11102/#post-31411

**Comment by Paulchen-Panther** [comment]
Wie wäre es einfach die Startposition auf 5 zu setzten und die HW Led Anzahl auf 265.

**Comment by kolyshkin** [comment]
@c-thiel it would be beneficial if you can show us your particular setup.

To rephrase it, do you just use the first 34 LEDs from the strip instead of wire?

**Comment by c-thiel** [comment]
@Lord-Grey thank you very much for the link, I will check it out at the weekend. It seems to solve my problem perfectly.

@Paulchen-Panther If I set the start-position to 5 the first 4 LEDs will still be lighted. The layout is just rotated. The first LEDs are always assumed to be part of the setup. Using a gap doesn't work either, as I don't want an actual gap to appear in the layout.

@kolyshkin Yes, I use the first 34 and last 34 LEDs as wire basically.

I am aware that I can already achieve a working setup if I would have started the circle with the first LED of the strip. At the time building, I chose  to implement the simplest hardware setup, which is plugging both left-over parts of my strip directly into the 5V power supply at the center of my TV. The alternative would be to solder an extension wire to the start and have 68 LEDs left over at the End.

I was suprised that I could skip the last LEDs but not the first ones in hyperion. It feels like a very simple thing to implement - hence this feature request.

**Comment by Chaphasilor** [comment]
Just chiming in to say that I would also like to see this implemented.  
To summarize the problem again:

Allow us to have hyperion completely ignore not only LEDs at the end of the light strip, but also at the start.  
And *ignore* in this case doesn't mean *gap*, but instead "treat them as if they wouldn't exist on the strip".

To clarify another example:  
the first ~17 LEDs of my light strip are dangling down from my TV because the strip is too long. I don't need all LEDs, so I use the first couple LEDs as an extension cable to my Raspberry Pi. There's no gap, the TV is surrounded by LEDs. It just happens that I have too many of them, at the start and not the end :)

So a simple `LED Offset` option in the LED Controller settings would totally do the trick!

**Comment by Paulchen-Panther** [comment]
@c-thiel 
In the meantime, to use your setup you can use the following workaround:

An example:
Enter the number of LEDs around your TV in the WebUI.
![70_leds](https://user-images.githubusercontent.com/16664240/104815450-f05aba00-5814-11eb-9b86-a2177ac3842c.png)

Export your config. (Configuration -> General-> Import / Export Configuration)
![export](https://user-images.githubusercontent.com/16664240/104815470-0f594c00-5815-11eb-841a-abb4d4788321.png)

Open your config with a text editor and add the number of unused LEDs to the beginning of the LED strip.
Insert the empty LEDs in front of the LED array.

Before:
![75_leds_config](https://user-images.githubusercontent.com/16664240/104815482-2435df80-5815-11eb-8cbb-0ffecf558078.png)
After:
![75_leds_config_modified](https://user-images.githubusercontent.com/16664240/104815483-26983980-5815-11eb-9427-1fa936c852d0.png)

Save and import the config in the WebUI (Configuration -> General-> Import / Export Configuration).

Proof:
![preview](https://user-images.githubusercontent.com/16664240/104815550-81319580-5815-11eb-92cc-abc9bebcd6c4.png)
![layout](https://user-images.githubusercontent.com/16664240/104815553-842c8600-5815-11eb-9749-48d25ad11635.png)

**Comment by Lord-Grey** [comment]
PR #1164 Allows to blacklist LEDs in layout via UI

**Comment by Chaphasilor** [comment]
Thanks a ton! Much appreciated 😇

**Comment by Chaphasilor** [comment]
@Lord-Grey I have a question about the blacklist feature, what exactly is it supposed to do? I've played around with it and in the LED layout preview it looks like it's simply creating a gap, but when I run an effect the blacklisted LEDs still light up like before...

I've upgraded to 2.0.12, currently rebuilding my setup and struggling with skipping the first LEDs again...

**Comment by lsaadeh** [comment]
+1 for this FR.. having an offset in the ui would be really useful.. seems like its technically possible should be an easy implementation and ui change.

**Comment by Lord-Grey** [comment]
@isaadeh Have you tried the „Blacklist“ Festure? Or you define a Gap?

**Comment by lsaadeh** [comment]
> @isaadeh Have you tried the „Blacklist“ Festure? Or you define a Gap?

Yes, I tried all combinations.. but only the above workaround achieved the desired effect
