### ISSUE TITLE
Value & saturation gain and threshold

### ISSUE THREAD

**Issue by starkillerOG** [hyperion-project/hyperion.ng#1142]
## Feature request
The old hyperion had a hsv, saturationGain and valueGain
And it also had a threshold that could be set.
The configuration of the old hyperion looked like this:
```
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain"	: 1.2000,
					"valueGain"		: 1.1000
				},
				"red" :
				{
					"threshold" 	: 0.0200,
					"gamma"     	: 1.6000
				},
				"green" :
				{
					"threshold" 	: 0.0200,
					"gamma"     	: 1.6000
				},
				"blue" :
				{
					"threshold" 	: 0.0200,
					"gamma"     	: 1.6000
				}
			}
		],
```
The new hyperion ng seems to be missing the valuegain, saturationgain and threshold.
I would like to also see those options in the new hyperion ng.
I noticed that the philips hue Led device does have a valuegain setting under configuration --> LED hardware --> LED controller.
I basically want that option available for all platforms under configuration --> Image Processing.

#### What problem does this feature solve?
Specifically for my secondary lights throught the room (so not the LEDs behind the TV but other lights controlled through UDP raw) I would like to have a desent valuegain to have them most of the time turned on at full brightness and only change color but not brightness to still have some light in the room. Only at verry very dark scenes in a movie they schould start to dim. This was possible with the ValueGain in the old hyperion.

Besides these lights use a pretty big area of the TV to derive the color from, that is good to get a better average of the screen color, but it also makes them tend to white values a lot instead of nice saturated colors. Therefore the SaturationGain is also very handy for such lights.

At last the LEDs behind my TV tend to flicker a bit when at very low brightness, I previously used the threshold option of the old hyperion to turn LEDs off when the brightness was below 2% brightness.
I would very much like to have this option back under configuration --> Image Processing in the new hyperion NG.

#### How should this be implemented in your opinion?
The same way it was done in the old hyperion.

#### Are you willing to work on this yourself?
I actually am working on quite some other github projects, mainly HomeAssisistant related and written in python.
I am not fimiliar with the Hyperion code and it is written in c which I am less proficiant in.
Therefore I would love it if someone else could implement this that is already fimiliar with Hyperion.
I could then help other people with there issues on other pyhon github projects.

**Comment by ORippler** [comment]
I would also love to see something like this !

**Comment by d4kine** [comment]
Me too :)

**Comment by Erik9519** [comment]
This would be extremely useful. I've noticed on my setup that it tends to be white all the time especially when compared to the setup I had on Prismatik where I had the saturation cranked.

**Comment by denimjeans** [comment]
no progress since 1 year. any news ? I am also interessted in to see how we can adjust the colors. 
for me - after tweaking arround with the color setting, the colors are too dark and if I increase the background light, it get more white. With boblight before, everything was perfect. I need hyperion to get it working with my LG TV. Otherwise if boblight would work with hyperion protocol, this would be the best solution. Hyperion is really nice, but the most important settings are missing: 
Adjusting saturation, contrast, etc is really missing.... hope I am doing something wrong or someone can give me some hints where to adjust better color output

**Comment by MichaelJahn2** [comment]
Yeah, color transform was unfortunately removed in hyperion ng. Really hoping this can be brought back. Also related / possible duplicate(?) #658.
