### ISSUE TITLE
Alpha9 prebuilt binary is broken on Windows 7

### ISSUE THREAD

**Issue by LMBernardo** [hyperion-project/hyperion.ng#1143]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Attempting to launch Hyperion Alpha9 on Windows 7 fails with both the installer and zip versions. All binaries fail to run with the message "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer."

My understanding is that this library is an internal library that is not meant to be linked against directly and is not present in Windows 7. Alpha8 runs properly and does not have this problem.

#### Steps to reproduce
Install or download Hyperion Alpha9 on Windows 7 and attempt to run any of the binaries.

#### What is expected?
The binaries will run properly.

#### What is actually happening?
The binaries fail to execute due to a missing shared lib.

#### System

Unable to run Hyperion in order to get this information.

**Comment by Paulchen-Panther** [comment]
Since Hyperion is still in alpha status, the developers have decided to no longer support Windows 7 (EOL). The notes in the CompileHowto have been adapted.
Thank you for your understanding.
