### ISSUE TITLE
Color calibration wizard: LEDs do not light up.

### ISSUE THREAD

**Issue by gerion0** [hyperion-project/hyperion.ng#1148]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When opening the color calibration wizard, Kodi is detected and shows a nice color frame in the next steps. I also get a color chooser in the web interface. but the LEDs do not light up, so the entire setup is kind of useless.

#### Steps to reproduce
1. Go to webinterface
2. Open the color calibration wizard.

#### What is expected?
Kodi shows a color, and the LEDs light up (with more less the same color).

#### What is actually happening?
Kodi shows a color.

#### System

```
Hyperion Server: 
- Build:           (HEAD losgelöst bei refs/git-r3/HEAD) (GitHub-4b0b84ec/8a028328-1608763626)
- Build time:      Jan 14 2021 16:39:57
- Git Remote:      
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      v4l2,framebuffer,x11,xcb,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Gentoo/Linux
- Architecture:   x86_64
- CPU Model:      AMD E-450 APU with Radeon(tm) HD Graphics
- CPU Type:       2
- Kernel:         linux (5.4.52 (WS: 64))
- Qt Version:     5.15.2
- Python Version: 3.8.4
- Browser:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/83.0.4103.122 Safari/537.36
```

#### Additional information
The LEDs can be controlled with the webinterface. I can activate effects and single colors. Only the wizard seems to fail.
If I activate the color white before starting the wizard and then starting the wizard _while_ the color is active, the first color chooser in the wizard works partially. I can modify brightness and saturation but not hue. The following color chooser are all white, too.

I searched in the javascript code but did not find any place, where the LEDs are activated or changed to the specific color. Is the wizard meant that way? Especially this code seems to be one step of the wizard:
```
  if (step == 2) {
    updateWEditor(["white"]);
    h = $.i18n('wiz_cc_adjustit', $.i18n('edt_conf_color_white_title'));
    if (withKodi) {
      h += '<br/>' + $.i18n('wiz_cc_kodishould', $.i18n('edt_conf_color_white_title'));
      sendToKodi('playP', "white");
    }
    else
      h += '<br/>' + $.i18n('wiz_cc_lettvshow', $.i18n('edt_conf_color_white_title'));
    $('#wiz_cc_desc').html(h);
  }
```
This seems to be a lot html test replacement, the sendToKodi action (which works) and then a updateWEditor function, which seems to choose the correct color palette web UI. Where is the actual command for the LED color change?

**Comment by corus87** [comment]
@gerion0 I had the same problem, turned out it was because I had Hyperion-Control installed and configured to only activate Hyperion if a video or music is played. 
After activating all components in Hyperion-Control, the wizard was working.

**Comment by Lord-Grey** [comment]
@gerion0 Did you validate that your LEDs are working in general and your LED-Layout is accurate?
Before you start calibrating, you must have a working setup.

**Comment by gerion0** [comment]
> @gerion0 Did you validate that your LEDs are working in general and your LED-Layout is accurate?

Yes, my LED-Layout is working.

I have digged in the code a little bit more and within the JS code the LEDs aren't activated. I assume that the LEDs should be activated by the normal screen grabbing mechanism, when the picture is shown by Kodi. However, that does not work with the standard Kodi addon.

What works:
1. Light up the LEDs in whatever way (e.g. by activating color red in the webinterface)
2. Start the wizard, skip to the specific color that should be calibrated.
3. Calibrate with the input field (the JS code sends the correct commands to _change_ the color but not _activates_ it).
4. Skip to the end to store this specific color.
5. Iterate...

**Comment by Lord-Grey** [comment]
@gerion0 Sorry for coming back late.....

As calibration is to align the screen grabbed via the screen grabber of your choice and the LED output, it is key that
a. LEDs work in general and are enabled
b. the screen grabber that you would like to use is enabled and working.

That is your starting point with the Calibration Wizard.
If you then present a color in Kodi it is captured by the screen grabber and displayed via the LEDs configured.
You can then adjust to have them matched.

As the screen grabber differ from platform to platform, as well as for some platforms there are multiple variants, hyperion cannot just preselect one for you.
If the LEDs are off, then there is a problem and you should fix this first, as it is a prerequisite.

Could you please retest with alpha10 and outline, if there are still problems/concerns.

**Comment by Lord-Grey** [comment]
Closing as not feedback since August 2021.
