### ISSUE TITLE
Missing dependencies (ubuntu 20.04 RPi 3B)

### ISSUE THREAD

**Issue by fastlorenzo** [hyperion-project/hyperion.ng#1161]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Install latest deb release file on clean Ubuntu 20.04.1 (Raspberry Pi 3B)
Start the service.

#### What is expected?

That the service is started.

#### What is actually happening?

Missing the following files: 
- libfreetype.so.6:
- libGL.so.1

Can be fixed by installing the following packages: `libfreetype6 libgl1-mesa-glx`

**Comment by Paulchen-Panther** [comment]
Server or Desktop image?

**Comment by fastlorenzo** [comment]
server image

**Comment by micw** [comment]
Same for debian buster on RPi 2. The deb file provided misses the dependency

**Comment by Paulchen-Panther** [comment]
@micw What dependence?

**Comment by micw** [comment]
libfreetype6 was missing, I had to install it manally.

**Comment by micw** [comment]
On Rasperian (Buster), the lib seems to be present by default. Nevertheless, it should be a dependency of the hyperion deb file when it's needed.

**Comment by MrSpoocy** [comment]
On Raspbian Buster **light**, the libgl1-mesa-glx is missing.

**Comment by Paulchen-Panther** [comment]
@fastlorenzo @micw @MrSpoocy 
Could you try installing Hyperion again using [our APT server](https://apt.hyperion-project.org/). Thank you very much.

**Comment by maleadt** [comment]
Running into the same issue using alpha10 from Github releases. With the deb from the apt repo, it's only missing libpython3.7m.so.1.0, which installing libpython3.7 resolves.

**Comment by Paulchen-Panther** [comment]
@maleadt 
Are you running the server version of Ubuntu 20.04? You would help us a lot to complete the dependencies list for the used ubuntu version.

**Comment by maleadt** [comment]
I'm running Debian 10.10 (buster) on an x86 system; headless, with only the SSH server installed through tasksel.

**Comment by chatainsim** [comment]
Same fo me, missing libgl1-mesa-glx on Debian 10 headless running on Proxmox.
