### ISSUE TITLE
Philips Hue lamps not moving with the image / communication error?

### ISSUE THREAD

**Issue by NL-Splinter** [hyperion-project/hyperion.ng#1166]
[x] I confirm that this is an issue rather than a question.

## Bug report

```
 2021-01-24T20:15:05.975Z [hyperiond LEDDEVICE] (DEBUG) (ProviderRestApi.cpp:150:put()) PUT: [http://192.168.0.67:80/api/xxx-xxxx/lights/2/state] [{"on":true,}]
 2021-01-24T20:15:06.023Z [hyperiond LEDDEVICE] (DEBUG) (ProviderRestApi.cpp:179:getResponse()) Reply.httpStatusCode [200]
 2021-01-24T20:15:06.024Z [hyperiond LEDDEVICE] (DEBUG) (LedDevicePhilipsHue.cpp:392:log()) Error Type                    : 2
 2021-01-24T20:15:06.025Z [hyperiond LEDDEVICE] (DEBUG) (LedDevicePhilipsHue.cpp:392:log()) Error Address                 : /lights/2/state
 2021-01-24T20:15:06.025Z [hyperiond LEDDEVICE] (DEBUG) (LedDevicePhilipsHue.cpp:392:log()) Error Address Description     : body contains invalid json
 2021-01-24T20:15:06.025Z [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'philipshue' signals error: '(2) body contains invalid json, Resource:/lights/2/state'
```

#### Steps to reproduce
Fully install the philipshue bridge.

#### What is expected?
I expect the same behaviour from the Hue lamp next to the tv as the diy LED strips behind the TV.

#### What is actually happening?
Everything is working fine, except the external Hue lamp doesn't change. It does respond to selecting the lamp and to color calibration, etc. But it just doesn't keep on going. From the error log above I conclude Hyperion isn't sending valid comms to the the Hue Bridge. But no clue how I can fix this.....

#### System

```
Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: nl)
- UI Access:       advanced
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.83-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0 
```

**Comment by Lord-Grey** [comment]
1. Do you make use of an official Hue Bride or do you use an alternative eg DIYHue?
2. Would you mind sharing the logs where the Hue Bride details are shown?
You might need to disable and the enable the device via the „Remote Control“ UI Page.
Then the info should be at the end of the log.
3. In General, I would suggest to you use the Entertainment API mode rather then the classical one. It is far more performance.

**Comment by NL-Splinter** [comment]
1. Yes, brand new original Philips.
2. Pffff, will look at this more... I can't find more info then the lines in my initial post. But will keep looking...
3. No, not yet. When I try color calibration, it works. I see my lamps, I can use effects on them also. But I can't figure out why the live image is only getting through to the LEDstrip and not to the Hue lamp.
4. From what I say I need to make 'scenarios' in the Hue app, but didn't get there quite yet. Will try too...

Maybe tomorrow I'll do a full clean Hyperbian re-install and see where I get from there.

Thanks sofar!

**Comment by NL-Splinter** [comment]
I've tried different powersupplies but that wasn't it. Reinstalled Hyperion, and added the Hue bridge step by step. All works as expected! Very nice.
