### ISSUE TITLE
Signal detection of a grabbed frame

### ISSUE THREAD

**Issue by TechVic-1** [hyperion-project/hyperion.ng#1169]
## Feature request
Add a feature that works like "Signal detection" but can detect a specific static image ("like a vertically rainbow")

#### What problem does this feature solve?
Fix the issue with some hdmi grabber outputs a static rainbow image when no input is present (TV off).
you can not use Signal detection because of this.

#### What does the proposed API look like?
Maybe an option under Signal detection to take a frame that the signal detection is looking after.

#### How should this be implemented in your opinion?
Code wise, no ide.

#### Are you willing to work on this yourself?
Not in my scope of expertise.

**Comment by Paulchen-Panther** [comment]
I am closing this feature request because, the signal detection is working exactly as it should. It searches for a specific color value in a specific area. If this value is persistent for x frames, the respective source (in this case the USB grabber) is switched off.
Searching for an image makes no sense at all. Because a match can not be given 100% (size decimation, image noise etc). I don't even want to start with the computing time.

**Comment by TechVic-1** [comment]
So please explain how you setup "signal detection" for this image? 
![Screenshot_20210201-174606_Chrome](https://user-images.githubusercontent.com/21226587/106489934-9533f300-64b5-11eb-8334-d7eb564eaba9.jpg)

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/pull/339

**Comment by Lord-Grey** [comment]
https://hyperion-project.org/threads/best-way-to-configure-signal-detection-area.10847/#post-28981

**Comment by bloomberg21** [comment]
This link is posted many times in many different threads throughout this project but results in 404 and 500 errors.

Any way to correct the link so it produces the intended result?

**Comment by Paulchen-Panther** [comment]
> This link is posted many times in many different threads throughout this project but results in 404 and 500 errors.
> 
> Any way to correct the link so it produces the intended result? @Lord-Grey

Yes. https://hyperion-project.org/forum/index.php?thread/10847-best-way-to-configure-signal-detection-area/

**Comment by bloomberg21** [comment]
Thanks @Paulchen-Panther .... appreciated
