### ISSUE TITLE
Update Delay way too big if set to something other than 0

### ISSUE THREAD

**Issue by maeries** [hyperion-project/hyperion.ng#1179]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Actual update delay is a couple of seconds when set to something reasonable like 70ms

#### Steps to reproduce

1. Open the web UI -> Configuration -> Image Processing
2. Under Smoothing click activate
3. Set Update Delay to something other than 0 (e.g. 1)

#### What is expected?

Delay the update of the LEDs by set amount

#### What is actually happening?

The update of the LEDs gets delayed by 5-10s even when set to 1ms

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:34:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         en (BrowserLang: de)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   LibreELEC (official): 9.2.6
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.4
- CPU Revision:   b03114
- CPU Hardware:   BCM2835
- Kernel:         linux (4.19.127 (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0

**Comment by SimoneBnc** [comment]
Are there any news about this? I also have the need to delay a little the LEDs since they change before the actual image on the screen and it is pretty annoying.

**Comment by Lord-Grey** [comment]
Please note the update delay is in frames not in ms.
I think this was wrongly presented in the UI before and was corrected.
I suggest you retest with the latest version.

Depending on your update frequency configured, you would need to define the number of frames to be delayed.

**Comment by SimoneBnc** [comment]
> Please note the update delay is in frames not in ms. I think this was wrongly presented in the UI before and was corrected. I suggest you retest with the latest version.
> 
> Depending on your update frequency configured, you would need to define the number of frames to be delayed.

After some tinkering I figured that for my case i solved the problem by setting duration to 25ms, frequency 25hz and delay 5 frames.

**Comment by Lord-Grey** [comment]
Thanks for the feedback.
