### ISSUE TITLE
spidev device is often changed after reboot: LED device is disabled

### ISSUE THREAD

**Issue by rolandbreedveld** [hyperion-project/hyperion.ng#1184]
- [x] I confirm that this is an issue rather than a question.

## Bug report
a lot of times, after a reboot the LED-Strip is disabled 
in these cases I have to change /dev/spidev0.0 to /dev/spidev0.1 or the opposite way.
I have a WS2801 LED-strip.

#### What is expected?
Is there a way to make the spidev device persistent? Like with a udev rule or something like that, other option is a AUTO detect in Hyperion between spidev0.0 and spidev0.1

**Comment by Paulchen-Panther** [comment]
https://www.google.com/amp/s/blog.stabel.family/raspberry-pi-4-multiple-spis-and-the-device-tree/amp/
