### ISSUE TITLE
Android Grabber > Yeelight non-responsive

### ISSUE THREAD

**Issue by boardwarp** [hyperion-project/hyperion.ng#1185]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Begin with a clean installation of Hyperion
Configure Yeelight hardware
- Rainbow effect shows on bulb
Configure Android grabber on Google TV w/ Chromecast
- Screen video is visible in Hyperion UI
Play video on Google TV

#### What is expected?
The Yeelight colour changes to reflect the screen

#### What is actually happening?
The Yeelight does not respond

I realise that as a first-time user with an issue, the forum is probably a better choice, however after verifying my account it still seems to lack permissions to make a new thread or post in an existing one.

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       advanced
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by Lord-Grey** [comment]
@boardwarp would you mind sharing the log output, please? In the UI
System->Log

**Comment by Lord-Grey** [comment]
@boardwarp Any updates? Otherwise I assume the issue does not exist any longer?

**Comment by Lord-Grey** [comment]
Closing, as no further input provided.
