### ISSUE TITLE
SPI failed to write. errno: 110, Connection timed out

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [hyperion-project/hyperion.ng#1192]
- [x] I confirm that this is an issue rather than a question.

## Bug report
My hyperion.ng setup was working fine for month. From one day to the next the hyperion suddenly stops working.
The LEDs light up, but stay static. When I disable and enable hyperion via the webinterface, the LEDs get updated once and stay static.
Updating to the latest version or compiling from source did not change a thing.
Deleting my .hyperion directory did not change a thing either.

#### What is expected?
Color changing LEDs

#### What is actually happening?
Static LEDs

hyperion says:
```
LEDDEVICE    : <ERROR> SPI failed to write. errno: 110, Connection timed out
SPI failed to write. errno: 110, Connection timed out
```

#### System
Hyperion Server: 
- Build:           master (GitHub-36441554/9e281b23-1613561393)
- Build time:      Feb 20 2021 11:06:42
- Git Remote:      https://github.com/hyperion-project/hyperion.ng.git
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   b03111
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.11-v7l+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 6.3; WOW64; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by Lord-Grey** [comment]
@Unkn0wn-MDCLXIV I would suggest that you follow up on the error that is given to you. There seems to be a problem with SPI.
This is not a bug, but something on your system.
