### ISSUE TITLE
"Reverse Direction" not respected in Kodi menu/pictures.

### ISSUE THREAD

**Issue by newkind** [hyperion-project/hyperion.ng#1196]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I noticed that when "Reverse direction" is enabled in the LED Layout settings the colors in the Kodi menu and Kodi pictures are not respecting this setting. Playing any video from any source is fine and colors are proper, just not in the menu and pictures.

**When playing video:**

![Hyperion Video](https://discourse.coreelec.org/uploads/default/original/2X/9/97417c940599ab9c445d8e94036297d00340e1ad.jpeg)

![Hyperion Video](https://discourse.coreelec.org/uploads/default/original/2X/2/2ceccec34ed0655a106eb097efe9296bb127d73b.jpeg)

**When displaying sample rgb picture:**

![Hyperion Picture](https://discourse.coreelec.org/uploads/default/original/2X/6/644b00c883a338338e3dc5ea7845ff79c57363b4.jpeg)

#### Steps to reproduce
Enable "Reverse direction" in Hyperion LED Layout settings and display sample rgb picture via Kodi "Picture" menu.
Sample image: https://cln.sh/lo3Y7f

#### What is expected?
The "Reverse direction" is respected outside of the video playing and colors are proper for not only videos but also pictures and Kodi menu.

#### What is actually happening?
Hyperion is ignoring "Reverse direction" and thus displaying wrong colors.

#### System
Hyperion Server: 
- Build:           coreelec-9.2 (Portisch-de94399e92/d7336cbe8c-1611911223)
- Build time:      Jan 31 2021 10:29:42
- Git Remote:      https://github.com/CoreELEC/CoreELEC.git
- Version:         2.0.0-alpha.9
- UI Lang:         en (BrowserLang: pl)
- UI Access:       expert
- Avail Capt:      v4l2,framebuffer,amlogic,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   CoreELEC (official): 9.2.6
- Architecture:   arm64
- CPU Model:      Amlogic S912 rev a
- CPU Hardware:   Amlogic
- Kernel:         linux (3.14.29 (WS: 32))
- Qt Version:     5.13.0
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0

**Comment by Lord-Grey** [comment]
@newkind Would you mind sharing a screenshot of the LED-Visualisation preview with 
LED-Numbers, Live-Video and Show LED on, please?

So similar to:

![image](https://user-images.githubusercontent.com/48840279/109862787-2509c000-7c61-11eb-9861-0b00e8a4ebc5.png)

**Comment by newkind** [comment]
@Lord-Grey Sure! Some interesting findings there:

Kodi menu (I'm using default skin with default color scheme) - the colors are inverted. Netflix logo is blue, Twitch logo is red.

![Kodi Menu](https://i.imgur.com/iDbOyPC.png)

RGB picture - appears proper in web view but when viewed on TV - it's mirrored. Just like on the photo in my initial report.

![Kodi Picture](https://i.imgur.com/ZbygHud.png)

Video - local file, network file, YouTube, Twitch etc. - everythings fine in here, well besides Netflix when from time to time I can't help but have feeling that the colors should be different.

![Kodi Video](https://i.imgur.com/UwLXaIU.png)

**Comment by Lord-Grey** [comment]
@newkind I would suggest you check/fix on the Kodi/Netflix color issues first and then revisit hyperion.

**Comment by newkind** [comment]
@Lord-Grey By colors in Netflix - I meant LED colors, not the picture itself ;)

To be honest i think that the cause of this is most likely the Netflix addon and the fact that it uses software decoding which often lags videos enough that I barely use Netflix on this Kodi box. It doesn't bother me at all. Besides all colors on all other videos are proper so I'd say that's the most important thing.

I just thought about reporting this issue as I've seen other people having the same issue like in this topic: https://discourse.coreelec.org/t/hyperion-ng-amlogic-improvements/5476/202?u=newkind

On my setup I'm enabling Hyperion only when video is playing so all of that above really doesn't affect me directly. If you want to, I can close this issue.

**Comment by Lord-Grey** [comment]
@newkind Could you retest with hyperion alpha10 and report back?

**Comment by newkind** [comment]
@Lord-Grey Sure, but I need to wait for the @Portisch from CE forums to compile it, as I don't have needed files to build it myself.

**Comment by Lord-Grey** [comment]
> @Lord-Grey Sure, but I need to wait for the @Portisch from CE forums to compile it, as I don't have needed files to build it myself.

Great. Alpha10 is available now; I just updated the plug-in on CoreElec.

**Comment by newkind** [comment]
@Lord-Grey hmmm I still don't see that update in the CE repo. Maybe it has been only pushed for the CE Matrix (Kodi 19+) users? I'm using S912 devices so I have to stick to CE 9.2.7 for now.

**Comment by Lord-Grey** [comment]
@Portisch Is the updated Hyperion only available for CE 19?

**Comment by Portisch** [comment]
Yes, only CE-19. Don't know if it will work as CE-19 is python 3.

**Comment by newkind** [comment]
@Portisch If you want to, I can test it on 9.2.7 if you'll upload me the compiled files :)

**Comment by Portisch** [comment]
No, as I said Kodi Matrix have switched to python 3 and dropped python 2 support.
You can stay with 9.2.7 on S912. The S912 implementation was a hack and is not supported anymore in current used 4.9 kernel as we are not able to port it to the newer kernel. GXBB and GXM support is dropped on Amlogic-NG as they are based on 3.14 kernel. For Matrix you will need to try hardware with Amlogic-NG (Kernel 4.9) support.

**Comment by newkind** [comment]
Yah, I'm well aware of that and I know that Kodi Matrix is python3 only, I just thought that maybe you could install python3 on S912 devices using package manager so that only addons that need it could use it. I guess that's not an option without kernel support. Thanks for clarification.

@Lord-Grey Sorry, I'm stuck on Alpha 9 for now. I'm not sure when I'll be upgrading the devices as both that I have are working fine as of now. I guess we can close this issue so it wouldn't be holding you back.

Thank you both for your support!

**Comment by Lord-Grey** [comment]
@newkind Thanks for your support and input.
