### ISSUE TITLE
WebOS for lg screen capture? 

### ISSUE THREAD

**Issue by Suspect-byte** [hyperion-project/hyperion.ng#1200]
#### What problem does this feature solve?
Screen capture for smart tv of LG. Extract screen capture from tv's for hyperion. No need for external device but just plain use of smart tv. 
#### How should this be implemented in your opinion?
I dont know if it is hard to get in the LG content store but maybe an app right there or hack the tv OS. Here I found something on the forum: https://hyperion-project.org/threads/web-os-andriod-app-and-usb-camera-support.10531/#post-25490
#### Are you willing to work on this yourself?
Sure i'm not a real programmer but I have the equipment so I can do whatever the instructions are

**Comment by tpmodding** [comment]
This is not possible, i'm sorry. I will close this "issue"
