### ISSUE TITLE
Not all MKV files work

### ISSUE THREAD

**Issue by otmpp** [hyperion-project/hyperion.ng#1201]
- [x] I confirm that this is an issue rather than a question.

## Bug report
No h.625 files work with hyperion, completely no control of the led, even manual

#### Steps to reproduce
Play files through Plex Kodi connect through osmc

#### What is expected?
For everything to synchronise

#### What is actually happening?
LEDs completely unresponsive

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Open Source Media Center
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (4.19.122-2-osmc (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0

**Comment by Lord-Grey** [comment]
Hyperion just presents what is executed via Kodi,; it is independent of video formats (like MKV).
Please have a look how you configured Kodi and ensure that everything works there first.
