### ISSUE TITLE
Ubuntu Mate raspberrypi 4. libcec4

### ISSUE THREAD

**Issue by xxxjasonj2xxx** [hyperion-project/hyperion.ng#1202]
- [x] I confirm that this is an issue rather than a question.

## Bug report
At install of Hyperion on Ubuntu Mate 20.10
(
#### Steps to reproduce
Fresh Ubuntu mate installation and try install Hyperion  2.0. 0 apha9 linux-x86_64.deb

#### What is actually happening?
The terminal says it needs libcec4 but can't install

I already tryed to install ist with sudo apt install - y libcec4
But only an error that he can't find the paket

**Comment by Lord-Grey** [comment]
Duplicate issue

The bug fix has been in the master/main since December 27, 2020.
Fix will be available with the next release.
