### ISSUE TITLE
Colour calibration wizard doesn't light up LEDs

### ISSUE THREAD

**Issue by GenuineJakob** [hyperion-project/hyperion.ng#1207]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The colour configuration wizard does not light up any LEDs.

#### What is actually happening?
LEDs do not light up and in the log, I found following message:
`[hyperiond WEBSOCKET] (WARNING) Incorrect adjustment identifier: Test1`
`[hyperiond WEBSOCKET] (WARNING) Incorrect adjustment identifier: default1`

#### System
Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36 Edg/89.0.774

**Comment by Lord-Grey** [comment]
@GenuineJakob The warnings in the log are just an indication that the profile name currently is not matching the corresponding entry for Color channel adjustments in the "Image Processing" screen. 
That the LEDs do not light up must have a different reason.
I suggest you test with alpha10 again. For the time being, I will close the issue.
