### ISSUE TITLE
Alpha 9 .Deb libcec4 dependency on Ubuntu 20.10 Server

### ISSUE THREAD

**Issue by nrpetonr** [hyperion-project/hyperion.ng#1209]
I installed the alpha 9 aarch64.deb, and it complains about not finding libcec4.
Seem to be similar to #1123 , which was already closed, but i reproduce the problem again.

Commands that are supposed fix it, do not work in my case.
sudo dpkg -i /path/to/hyperion_file.deb      installs hyperion claimiming missing dependencies.
sudo apt-get install -f        actually uninstalls hyperion

- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
sudo dpkg -i Hyperion-2.0.0-alpha.9-Linux-aarch64.deb

#### What is expected?
hyperion installation

#### What is actually happening?
dpkg: dependency problems prevent configuration of hyperion:
hyperion depends on libcec4; however:
Package libcec4 is not installed.

#### System
 5.11.0-odroid-arm64 #1 SMP PREEMPT Ubuntu 5.11.2-202103041610~groovy (2021-03-04) aarch64 aarch64 aarch64 GNU/Linux

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/issues/1123#issuecomment-778756142
