### ISSUE TITLE
Update json schema

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#121]
We need to update json schema file. This will be important for travis check and automatic building of web config ui.

**Comment by brindosch** [comment]
Already done from @Paulchen-Panther

**Comment by redPanther** [comment]
Cool, thats nice.

**Comment by brindosch** [comment]
He wanted to open a PR yesterday, not sure what is in between now :)

**Comment by Paulchen-Panther** [comment]
Mach ich sofort wenn ich zu Hause bin. Hab gestern noch den Kodichecker umgeschrieben. Dabei hab ich es wohl vergessen. Sorry

**Comment by brindosch** [comment]
Wow, fleißig :)

**Comment by redPanther** [comment]
Big thx! So langsam wirds doch ..

**Comment by Paulchen-Panther** [comment]
PR vom Kodichecker ist erstellt. Erstelle gleich noch das PR von den Schematas
