### ISSUE TITLE
Hyperion-project.org website and wiki missing

### ISSUE THREAD

**Issue by dilruacs** [hyperion-project/hyperion.ng#1213]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The contents of the hyperion-project.org website, the wiki and the forum seems to be missing.

#### Steps to reproduce
Open https://wiki.hyperion-project.org/ in a browser

#### What is expected?
The project wiki

#### What is actually happening?
It displays a "Plesk" default web site

**Comment by Paulchen-Panther** [comment]
https://hyperion-project.org
https://docs.hyperion-project.org/

**Comment by dilruacs** [comment]
Thanks! Good news that a new website is available. I appreciate the work.

The problem is that quite a lot of google search results and posts within the forum itself find links in the "old" format:
e.g.: https://hyperion-project.org/threads/mein-4k-setup-rp4-und-hyperion-ng.11142/page-8#post-34107
Whereas the "new" format looks like:
https://hyperion-project.org/forum/index.php?thread/11142-mein-4k-setup-rp4-und-hyperion-ng/&postID=34107

It would be great if a URL rewrite from the old format to the new could be implemented, so the old references still work because they redirect to the existing content in the new format.

I'd offer help in writing a block of nginx configuration according to http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite if needed, but I'd need a bit of input.

**Comment by Paulchen-Panther** [comment]
Our webmaster @tpmodding  can give you more information about this.

**Comment by tpmodding** [comment]
added the wiki cname, thanks

will have a look for rewrite, @Paulchen-Panther did mentioned allready the problem with the old urls, it is on my list :-)
