### ISSUE TITLE
Can't SSH or Web UI while in use

### ISSUE THREAD

**Issue by robertalexa** [hyperion-project/hyperion.ng#1215]
- [x] I confirm that this is an issue rather than a question.

I would appreciate any feedback. There is nothing else running on the Rpi.

## Bug report
While Hyperion is in use, e.g. LEDs are working, in my case from a HDMI USB Grabber, I am unable to SSH into the RPI zero nor access the Web UI. If i turn the TV off, and LEDs go off, i can do both without issues.

#### Steps to reproduce
I have tried this using the arm6 deb on a fresh install of raspbian, with sudo apt update && sudo apt ugrade all done.
I have also tried this using the Hyperbian Image. Things seemed fine at first. Did update && upgrade and things continued to work fine, even after power cycling the whole setup. The next day, getting the same behaviour.

Hyperion version is most recent, alpha 9, with everything updated on the host RPI zero.

#### What is expected?
To be able to SSH and use the Web UI while the hyperion is interpreting video and outputing lights.

#### What is actually happening?
Explained in Steps to reproduce

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

**Comment by phipro92** [comment]
I had the same issue with HyperBian #8d161b7 on my RPi zero (armv6l) and fixed it with an adjustment to the network interface configuration to disable the power saving mode of the WLAN adapter. 

You can check it with:
`pi@HyperBian:~ $ iw wlan0 get power_save
Power save: on`

To fix this, open the interfaces file:
`sudo nano /etc/network/interfaces`
Enter the following lines or complete missing lines:
```
allow-hotplug wlan0
iface wlan0 inet manual
wireless-power of
```
After saving, you just have to restart:
`sudo reboot`

**Comment by robertalexa** [comment]
Thanks for pointing me in this direction, i was under the impression that wifi power saving was disabled by default, thus not looking into it.

For the sake of anyone else reading this, there is your type in your last command, missing an "f"

`wireless-power off`

**Comment by robertalexa** [comment]
I will close this issue in order to keep this project clean. I will see how wifi power saving goes. I will leave some more feedback once I have tested.

**Comment by tpmodding** [comment]
@robertalexa i'm waiting for your feedback. if this helps you, i would like to add this point to the docu.

**Comment by robertalexa** [comment]
Note: I have chosen not to make changes to `/etc/network/interfaces`

Instead I have added one line to `/etc/rc.local` above the `exit 0` command
`iwconfig wlan0 power off`

I am currently rebuilding my setup so I will let you guys know as soon as I have something to report
