### ISSUE TITLE
V4l2 Grabber delay in combination with AMLogic platform grabber

### ISSUE THREAD

**Issue by xonestonex** [hyperion-project/hyperion.ng#1218]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When using a V4L2 Grabber (stk1160 driver) in combination with the AMLogic platform grabber (Odroid-C4), there is a 1-2 sec delay in image processing of the V4L2 Grabber. There is no delay when only the Framebuffer platform grabber is enabled. But this also disables effects for movies played with the amlogic video acceleration.

#### Steps to reproduce
Enable the AMLogic platform grabber and the V4L2 grabber.

#### What is expected?
No delay in video processing of the V4L2 grabber.

#### What is actually happening?
1. 1-2 sec delay of the V4L2 grabber Frames if there is no video playback on the AMLogic video accelerator an the AMLogic grabber is in its framebuffer fallback mode.
2. 1-2 sec delay (maybe less than above) of the V4L2 grabber Frames if there is an accelerated video playing in Kodi in the background.
3. No V4L2 processing at all, if a accelerated video has been paused in Kodi.

#### System

Hyperion Server: 
- Build:           coreelec-19 (Portisch-992a222772/81fbc79061-1614623929)
- Build time:      Mar  1 2021 21:06:38
- Git Remote:      https://github.com/CoreELEC/CoreELEC.git
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: de)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,amlogic,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   CoreELEC (official): 19.0-Matrix
- Architecture:   arm64
- CPU Model:      Amlogic S905X3 rev c
- CPU Revision:   0400
- CPU Hardware:   Hardkernel ODROID-C4
- Kernel:         linux (4.9.113 (WS: 32))
- Qt Version:     5.13.0
- Python Version: 3.8.7
- Browser:        Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by Lord-Grey** [comment]
@xonestonex Could you retest with hyperion alpha10 and report back?

**Comment by xonestonex** [comment]
Works now with alpha10. Thx.
