### ISSUE TITLE
Dynamic link against bcm_host and x11

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#122]
Bind (dlopen) against bcm and x11 libs only when dispmanx/x11 is used. 

This enables us to e.g. to launch raspi build on other arm linux, where bcm libs not available.
Or compile with x11, but hyperion is runable on system without x11 ..

Then we don't have to remove integrated grabbers and use only proto grabbers.

**Comment by brindosch** [comment]
Hm, can't follow
> Or compile with x11, but hyperion is runable on system without x11 ..

eg Pi, but you can't enable dispmanx without Pi sources so it remains the same (-> Proto)?
Under the hood you could use a hyperion-x11 enabled internal build with a dispmanx proto implementation?

if platform grabber not inside the build - call the external one?

**Comment by redPanther** [comment]
ok try to make a simpel example.
compile hyperiond on raspi with x11 and dispmanx and amlogic.
compilation has more or less 3 stages. configure, compile and link.
during link phase do not link against bcm (dispmanx) and x11 libs (currently we do).

If linked against e.g. x11 then it is neccessary that x11 libs are in place when start hyperiond. If libs not there hyperiond will not start and throw error "missing x11 libs"

now the new part: if not linked on binary creation, those libs arn't needed to run hyperiond, as long as the code part for x11 grabber is not executed. when config says enable x11, then we load x11 libs during  runtime. if loading fails, throw error: x11 not usable .. same for dispmanx.

we can use dispmanx enable binary on systems where dispmanx is not available.

**Comment by brindosch** [comment]
Ah now i understand :)
Thank you. 

OT: For sure a "plugin system" is a nice thing. Like HDMI-CEC stream reading and assign actions, or IR signals.

**Comment by redPanther** [comment]
After investigating a bit I had some additions:

currently all grabbers are made as static libs. This is generally good, because we need the grabbers as lib for "load on demand".
Todo: the graber libs have to build as shared lib. Then we can load the grabber (and indirectly x11 and bcm libs), if we need it - if loading of grabber fails, then x11/dispmanx is not available and those grabbers are deactivated.

**Comment by tpmodding** [comment]
@Paulchen-Panther ist der durch?

**Comment by Paulchen-Panther** [comment]
Ich glaube schon
