### ISSUE TITLE
No signal detection if size decimation parameter is used in external V4L2 grabber

### ISSUE THREAD

**Issue by xonestonex** [hyperion-project/hyperion.ng#1220]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When the -s or --size-decimator argument is used for the hyperion-v4l2 external grabber, then the signal detection is not working.
The --size-decimator and the --signal-detection-disabled share the same short option name -s. I assume that if the -s or --size-decimator argument is passed to the binary, that also --signal-detection-disabled is set by the argument processing function.

#### Steps to reproduce
Start: hyperion-v4l2 --size-decimator 8 -t 0.5

#### What is expected?
If there is no or a dark signal on the V4L2 grabber source, then the source gets deactivated.

#### What is actually happening?
Source stays active, because signal detection is disabled. 

#### System

Hyperion Server: 
- Build:           coreelec-19 (Portisch-992a222772/81fbc79061-1614623929)
- Build time:      Mar  1 2021 21:06:38
- Git Remote:      https://github.com/CoreELEC/CoreELEC.git
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: de)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,amlogic,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   CoreELEC (official): 19.0-Matrix
- Architecture:   arm64
- CPU Model:      Amlogic S905X3 rev c
- CPU Revision:   0400
- CPU Hardware:   Hardkernel ODROID-C4
- Kernel:         linux (4.9.113 (WS: 32))
- Qt Version:     5.13.0
- Python Version: 3.8.7
- Browser:        Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by Lord-Grey** [comment]
Fixed in alpha10
