### ISSUE TITLE
allow custom SPI-path

### ISSUE THREAD

**Issue by xtools-at** [hyperion-project/hyperion.ng#1224]
#### What problem does this feature solve?
Controlling leds which are not connected to spidev0.0 or spidev0.1. I've fried the SPI0 pin on my RPi0 and need to use _/dev/spidev1.0_ , but can't - just recently updated from old Hyperion, and this is biting me in the ass now :(

#### What does the proposed API look like?
add a "Custom" option to Configuration > Led-Hardware > Led-Controller > SPI-Path, so you can type in a custom SPI path yourself. Alternatively, add more options (spidev1.0/spidev1.1/spidev1.2).

#### How should this be implemented in your opinion?
Option in the UI

#### Are you willing to work on this yourself?
yes

**Comment by Paulchen-Panther** [comment]
[Comming soon](https://github.com/hyperion-project/hyperion.ng/pull/1112) in next release (no ETA).

**Comment by xtools-at** [comment]
danke :)

**Comment by Paulchen-Panther** [comment]
Kein Problem. 😀

**Comment by xtools-at** [comment]
any idea if i can edit some config file somewhere to set my SPI-path manually in the meantime?

**Comment by Paulchen-Panther** [comment]
What operating system do you use for hyperion?

**Comment by xtools-at** [comment]
latest raspbian lite (headless) on a Raspberry Pi 0 W

**Comment by Paulchen-Panther** [comment]
The easiest way is to load a current PR artifact (e.g. #1223 ) and overwrite the Hyperion files.
Proof:
![Screenshot_1](https://user-images.githubusercontent.com/16664240/113344210-0f0b2000-9331-11eb-8cba-b1f2ea378d63.png)

**Comment by xtools-at** [comment]
thx, i'll give it a shot 🤟

**Comment by Lord-Grey** [comment]
You can even test this PR
https://github.com/hyperion-project/hyperion.ng/pull/1164

Here all spidev Devices are resolved dynamically...

**Comment by Felix313** [comment]
Could you explain in more detail where to overwrite the Hyperion files? I have the master-branch and armv6l downloaded but since the files in the folders dont match up I'm unsure where to copy them to / overwrite the master-branch files.
