### ISSUE TITLE
"LED Test" effect description is in wrong order

### ISSUE THREAD

**Issue by TheGroundZero** [hyperion-project/hyperion.ng#1229]
- [x] I confirm that this is an issue rather than a question.

## Bug report

The description of the _LED Test_ effect states the following:

> Led Test
> Rotating output: Red, Blue, Green, White, Black

![image](https://user-images.githubusercontent.com/2406013/114686347-37682680-9d02-11eb-9f7a-0409dc7356be.png)

However, the output actually rotates in the following order: `Red, Green, Blue, White, Black`

This order is defined in the code here: https://github.com/hyperion-project/hyperion.ng/blob/6f0ccdbe25a7532f766b613430ef13838d9719c0/effects/ledtest.py#L30

~I couldn't find the file that contains this description text, so didn't create a PR to fix this.~
EDIT: The test description can be found in this file: https://github.com/hyperion-project/hyperion.ng/blob/6f0ccdbe25a7532f766b613430ef13838d9719c0/assets/webconfig/i18n/en.json#L583
Other translations may be impacted by this if the translation was based on the English version

#### Steps to reproduce

1. Open 'Effects Configurator' 
2. Choose the 'Led Test' template.
3. Note the description that is shown.
4. Run the actual test and notice that (if the strip is correctly configured) the order is R>G>B>W>Bl

#### What is expected?

The description should state

```
Led Test
Rotating output: Red, Green, Blue, White, Black
```

#### What is actually happening?

The description states

```
Led Test
Rotating output: Red, Blue, Green, White, Black
```

#### System

```
Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 
```

**Comment by Lord-Grey** [comment]
@TheGroundZero Thank you very much for the finding, as well as the fix via PR1229!
