### ISSUE TITLE
Installation Failed - 'hyperion.postinst: root: not found'

### ISSUE THREAD

**Issue by mitch7391** [hyperion-project/hyperion.ng#1245]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Installing on a Raspberry Pi 4 that has the official Homebridge image seems to fail when installing through the terminal.

#### Steps to reproduce
```
wget https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.9/Hyperion-2.0.0-alpha.9-Linux-armv7l.deb
sudo apt install ./Hyperion-2.0.0-alpha.9-Linux-armv7l.deb
```
Response:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'hyperion' instead of './Hyperion-2.0.0-alpha.9-Linux-armv7l.deb'
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  hyperion
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/80.5 MB of archives.
After this operation, 215 MB of additional disk space will be used.
Get:1 /home/pi/Hyperion-2.0.0-alpha.9-Linux-armv7l.deb hyperion armhf 2.0.0 [80.5 MB]
Selecting previously unselected package hyperion.
(Reading database ... 46431 files and directories currently installed.)
Preparing to unpack .../Hyperion-2.0.0-alpha.9-Linux-armv7l.deb ...
---Hyperion ambient light preinst ---
/var/lib/dpkg/tmp.ci/preinst: 6: /var/lib/dpkg/tmp.ci/preinst: root: not found
Unpacking hyperion (2.0.0) ...
Setting up hyperion (2.0.0) ...
---Hyperion ambient light postinstall ---
/var/lib/dpkg/info/hyperion.postinst: 32: /var/lib/dpkg/info/hyperion.postinst: root: not found
---> init deamon: systemd
Failed to start hyperiond@.service: Unit name hyperiond@.service is missing the instance name.
See system logs and 'systemctl status hyperiond@.service' for details.
---> Install Hyperion desktop icons
--> systemctl start hyperiond for user
-----------------------------------------------------------------------------
---> Hyperion has been installed/updated!
---> 
---> Hyperion has been installed as service, it will start on each system startup
---> For configuration, visit with your browser: 192.168.0.175:8090
---> or if already used by another service try: 192.168.0.175:8091
-----------------------------------------------------------------------------
Webpage: www.hyperion-project.org
Wiki: wiki.hyperion-project.org
Forum: forum.hyperion-project.org
-----------------------------------------------------------------------------
```
Refer to previous issue raised (#1242).

#### What is expected?
Successful installation of Hyperion.NG.

#### What is actually happening?
Pre-installation seems to be failing to located a file, installation seems to not be complete and the service is not created; but the finishing messages seem to think it has still installed.

#### System

Raspberry Pi 4 using official Homebridge image.

**Comment by tpmodding** [comment]
i dont know how the "official homebridge image" works...

but if you read the log you can find some hints which you can look up for at the "offical homebridge" community maybe first

/var/lib/dpkg/tmp.ci/preinst: 6: /var/lib/dpkg/tmp.ci/preinst: root: not found

/var/lib/dpkg/info/hyperion.postinst: 32: /var/lib/dpkg/info/hyperion.postinst: root: not found

Failed to start hyperiond@.service: Unit name hyperiond@.service is missing the instance name.
See system logs and 'systemctl status hyperiond@.service' for details.

**Comment by mitch7391** [comment]
Oh that is a good point @tpmodding, I hadn’t thought that maybe it could be due to how their image is set up. I will create an issue there and reference this one to see if they are able to answer my questions.

If root is removed from their system does that mean that Hyperion would be able to be installed on it?

**Comment by mitch7391** [comment]
@tpmodding I received a response from one of the Homebridge developers and they say the following:

> The image is just Raspberry Pi OS Lite with Homebridge pre-installed. Nothing fancy :)
The issue is with their installer:
Failed to start hyperiond@.service: Unit name hyperiond@.service is missing the instance name.

Is there anything else I can check or provide for you to be able to figure this one out? I would be very keen to get this installed on the same RPi to avoid having multiple running.

**Comment by tpmodding** [comment]
can you try to run it manually? just try "hyperiond --debug"

**Comment by mitch7391** [comment]
Awesome, will try this after work and get back to you :)

**Comment by tpmodding** [comment]
i think this should work, if yes then there is only a problem with the systemctl service file

**Comment by Lord-Grey** [comment]
@mitch7391 Would you mind executing the following command and report back, if there has been an error....

`echo `who | grep -o -m1 '^\w*\b'` || "root"`


It looks the script fails to resolve the user in the preinst and postinst scripts:

# search for users in system, returns first entry
FOUND_USR=`who | grep -o -m1 '^\w*\b'` || "root"

**Comment by Paulchen-Panther** [comment]
@Lord-Grey 
The first command is taken 1:1 from the shell script file.
After removing the ` characters, the correct username is displayed. But this seems to be valid in shell as a command substitution. (https://www.cs.ait.ac.th/~on/O/oreilly/unix/upt/ch09_16.htm)

![image](https://user-images.githubusercontent.com/16664240/119262519-dcb4cb00-bbdb-11eb-85e0-7ef57b9b5822.png)

After downloading the deb file and installing it using sudo apt-get install, I see no problems with the installation on my system. However, since this was done with an RPi3, I will repeat the same procedure with an RPi4. You can find the complete log here:
https://pastebin.com/H77JfiQ7

**Comment by Lord-Grey** [comment]
@Paulchen-Panther 

The log indicates that on the Homebrige OS the command fails (the command in script line 6 is failing)

`/var/lib/dpkg/tmp.ci/preinst: 6: /var/lib/dpkg/tmp.ci/preinst: root: not found`

That is why I asked the Homebridge user to test the command...


The "´" is requried to executed the command...
If I execute the same command on Coreelec, I get the error that who is not found

```
echo `who | grep -o -m1 '^\w*\b'` || "root"
-sh: who: not found

Therefore my question, if it is the same for teh Homebridge image
```

**Comment by Paulchen-Panther** [comment]
No Problems on RPi4.
Log: https://pastebin.com/SDU1mb64

**Comment by tpmodding** [comment]
@mitch7391 could you try to uninstall and reinstall please?

https://docs.hyperion-project.org/en/user/Installation.html#uninstall-hyperion

**Comment by mitch7391** [comment]
I will get back to you all with these tests after work :)

@Paulchen-Panther are you using the official image for Homebridge or have you installed it on Raspbian or using some other method?

@tpmodding I have tried to uninstall and reinstall several times and still get the same result sadly.

**Comment by Paulchen-Panther** [comment]
> @Paulchen-Panther are you using the official image for Homebridge or have you installed it on Raspbian or using some other method?

Yes official image.

**Comment by mitch7391** [comment]
Yep, it looked like it but just wanted to confirm. It looks like you are ssh’ing into your RPi. I have been trying to do this from the terminal on the Homebridge web UI; perhaps this could make things different (I doubt it but figured I’d ask)?

**Comment by tpmodding** [comment]
try it with ssh, yes.

**Comment by Paulchen-Panther** [comment]
> Yep, it looked like it but just wanted to confirm. It looks like you are ssh’ing into your RPi. I have been trying to do this from the terminal on the Homebridge web UI; perhaps this could make things different (I doubt it but figured I’d ask)?

WTF. And you're just coming up with this information now? Are you serious?

**Comment by mitch7391** [comment]
> WTF. And you're just coming up with this information now? Are you serious?

I’m sorry but since I have been on that OS I have done any installations from that terminal and was not aware there was a difference; not all of us are experts or have a lot of experience. I tried to follow the instructions on the web page and it does not specify this…

**Comment by mitch7391** [comment]
Might I suggest the addition of the terminal commands provided to me and the noting of using ssh in the installation instructions so that some else does not make this mistake in the future?

I will update you all on how this goes when I am home and thank you for you help so far.

**Comment by Paulchen-Panther** [comment]
![image](https://user-images.githubusercontent.com/16664240/119264975-63ba7100-bbe5-11eb-8b21-d93a31770df2.png)

**Comment by mitch7391** [comment]
Ok so that looks like it worked for you @Paulchen-Panther… I honestly have no idea why it will not work for me then. I will see how doing it through ssh goes for me and report back.

**Comment by mitch7391** [comment]
@Paulchen-Panther, @tpmodding and @Lord-Grey  it appears that the terminal installation method worked when done through ssh; I am sorry for the time wasted and very grateful for the guidance. 

Are you able to explain to me why it would not successfully install through the Homebridge web UI terminal vs the terminal using ssh? I was not aware the two would be different, as I have successfully installed other programs through the Homebridge web UI terminal.

**Comment by tpmodding** [comment]
we dont know how th webUI terminal works...maybe it has some "limited" access or so.... dont know, but also dont want to invest time in it...sorry, great that it worked in the end.

**Comment by mitch7391** [comment]
Nah that’s all good @tpmodding was just wondering if you had an answer off the top of you head. I will ask over at homebridge, thanks again!
