### ISSUE TITLE
 <ERROR> V4l2 init failed ('/dev/video0' does not support streaming i/o)

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#126]
Is there any way to get this to work?

If not should we write an error and then stop re-trying?

 lsusb
Bus 001 Device 004: ID 2040:4903 Hauppauge HS PVR

This provides an mpeg4 stream from /dev/video0 so is different from the standard grabbers.

v4l2-ctl -L
User Controls
                     brightness (int)    : min=0 max=255 step=1 default=128 value=128 flags=slider
                       contrast (int)    : min=0 max=255 step=1 default=64 value=64 flags=slider
                     saturation (int)    : min=0 max=255 step=1 default=64 value=64 flags=slider
                            hue (int)    : min=0 max=30 step=1 default=15 value=15 flags=slider
                      sharpness (int)    : min=0 max=255 step=1 default=128 value=128 flags=slider

Codec Controls
                    stream_type (menu)   : min=0 max=1 default=1 value=1 flags=update
                                1: MPEG-2 Transport Stream
                 audio_encoding (menu)   : min=0 max=4 default=3 value=3 flags=update
                                3: MPEG-2/4 AAC
                                4: AC-3
                 video_encoding (menu)   : min=0 max=2 default=2 value=2
                                2: MPEG-4 AVC
             video_bitrate_mode (menu)   : min=0 max=1 default=1 value=0 flags=update
                                0: Variable Bitrate
                                1: Constant Bitrate
                  video_bitrate (int)    : min=1000000 max=13500000 step=100000 default=6500000 value=13500000
             video_peak_bitrate (int)    : min=1100000 max=20200000 step=100000 default=9000000 value=20200000
                     brightness (int)    : min=0 max=255 step=1 default=128 value=128 flags=slider
                       contrast (int)    : min=0 max=255 step=1 default=64 value=64 flags=slider
                     saturation (int)    : min=0 max=255 step=1 default=64 value=64 flags=slider
                            hue (int)    : min=0 max=30 step=1 default=15 value=15 flags=slider
                      sharpness (int)    : min=0 max=255 step=1 default=128 value=128 flags=slider

**Comment by penfold42** [comment]
I've just noticed we get this error even when the v4l grabber is "disabled"
We never actually start it, but we do create it and that seems enough to trigger this error message

**Comment by redPanther** [comment]
There are some more isues. there are exceptions in slits wich is not allowed by qt.

Did you try the auto device?

**Comment by penfold42** [comment]
i haven't - where isn't it documented ?

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion.ng/pull/118

**Comment by penfold42** [comment]
Nope - it automatically finds /dev/video0 and gives the same error

**Comment by redPanther** [comment]
can you retry your test with latest version?

**Comment by redPanther** [comment]
ok I close the issue, because it is solved ...
