### ISSUE TITLE
Docker cross compilation for Raspberry Pi 2/3/4 (Debian Buster) fails

### ISSUE THREAD

**Issue by 0x6470** [hyperion-project/hyperion.ng#1260]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I tried cross compiling Hyperion for armv7l with three different machines (2x Ubuntu and  1x Debian) with docker, but every time, the exact same error appeared.

#### Steps to reproduce
Install Docker freshly according to those instructions: https://docs.docker.com/engine/install/ubuntu/ or https://docs.docker.com/engine/install/debian/
Add the current user to the docker group `sudo usermod -aG docker $USER`
Restart the machine
`wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -i armv7l -t buster`

#### What is expected?
Successful compilation/compiled binaries

#### What is actually happening?
```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeCompilerIdDetection.cmake:26 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:211 (compiler_id_detection)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:230 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCXXCompiler.cmake:111 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:5 (PROJECT)
```
(it actually appears 20 times until it finally stops)

Strangely, `wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -i x86_64 -t buster` works just fine.

#### System
```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
and
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by Paulchen-Panther** [comment]
I can confirm the error. I will take care of the problem this week. Thank you for your issue report.

**Comment by Paulchen-Panther** [comment]
The problem has been fixed. Thanks again. 👍🏻
