### ISSUE TITLE
[FR] Support for password managers

### ISSUE THREAD

**Issue by Xanderr** [hyperion-project/hyperion.ng#1263]
## Feature request

The ability to use password managers for signing in. Currently, the password input field has no "name" attribute, causing it to be not detected by password managers.

#### What problem does this feature solve?

Easier login. Especially handy since Hyperion currently doesn't keep your session. (Also suggested as FR at #858)

#### What does the proposed API look like?

N/A

#### How should this be implemented in your opinion?

The only required change would to add the following attribute to the password input element:

name="password"

#### Are you willing to work on this yourself?

I wouldn't mind creating a PR, since it's very easy to fix.

**Comment by Lord-Grey** [comment]
@Xanderr Hi, I fixed to have the password handled by Password-Manager. 
You can check it out via the linked PR.

**Comment by Xanderr** [comment]
Thanks man :) very nice
