### ISSUE TITLE
Web UI messed up until language selected

### ISSUE THREAD

**Issue by washcroft** [hyperion-project/hyperion.ng#1267]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Another @Lord-Grey inflicted bug, assuming it was broken in PR #812.

If loading the Web UI for the first time, or without a language selected and stored in local storage - there is no fallback to English if an appropriate language cannot be found. This causes the UI to look a mess until a language selection is forced (I have to change to another language and then back to English).

My browser language is en-GB, it tries to load translations from /i18n/en-GB.json.

#### Steps to reproduce

Visit the Web UI for the first time (incognito) using a language that has no direct translation file (i.e. en-GB).

#### What is expected?

In this case, fallback to the closest match (en) - but if the browser language cannot be matched to anything, default to en.

#### What is actually happening?

![image](https://user-images.githubusercontent.com/1866176/123552574-ad5f2400-d76e-11eb-83e2-42f6cf1c972e.png)

#### System

```
Hyperion Server: 
- Build:           master (GitHub-2b135194/6d004240-1623696528)
- Build time:      Jun 24 2021 18:15:48
- Git Remote:      https://github.com/hyperion-project/hyperion.ng.git
- Version:         2.0.0-alpha.9
- UI Lang:         en (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
```

**Comment by Paulchen-Panther** [comment]
The bug is known and will be fixed with PR #1119
