### ISSUE TITLE
Hyperion app/remote control no longer working

### ISSUE THREAD

**Issue by nicksears** [hyperion-project/hyperion.ng#1270]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Every since switching to this new version with the web ui (which I love) I haven't been able to use the Hyperion mobile app. It says server synchronized when using 19444, but does not reflect any changes.

#### Steps to reproduce

Install hyper Ian, configure (add to wifi) install (Android) app, try to change color, effect, etc

#### What is expected?

Color/effect change

#### What is actually happening?

Nothing

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Linux; Android 11; SM-G973U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36

**Comment by Lord-Grey** [comment]
@nicksears I would suggest you validate, if the IP-Address of HyperBian is still the same as the one configured in the app.
I tested the app with alpha 10 and there is no issue... (besides that color transformation is not supported, as the app was build for hyperion classic).

**Comment by nicksears** [comment]
I'd like to have this reopened, I made a new install of the latest Hyperion (V12) and it still doesn't work.

The IP address was never the issue, and to make sure my issue is clear - I have completely configured Hyperion and everything works great, it's just the mobile app (https://play.google.com/store/apps/details?id=nl.hyperion.hyperionfree) that does not work.

Again, I use the same ip address as I use to connect to the web server 192.168.1.92, but port 19444 instead of 8090.

I get "server synchronized" as if it's going to be able to remote control, but nothing works and no effects show up when I click that tab.

**Comment by nicksears** [comment]
![Screenshot_20211215-215757_Hyperion Free](https://user-images.githubusercontent.com/6611900/146305723-ad4ca3de-a8bf-44f4-8981-356a0a232e99.jpg)
![Screenshot_20211215-215752_Hyperion Free](https://user-images.githubusercontent.com/6611900/146305724-b7482f01-0e2b-4aae-ae8a-4bac55a61753.jpg)
![Screenshot_20211215-215746_Hyperion Free](https://user-images.githubusercontent.com/6611900/146305725-b402100c-5aeb-442c-869e-9f54537695cc.jpg)

**Comment by Lord-Grey** [comment]
@nicksears Could you check your Network Configuration in Hyperion?
 
 With the following setup, it works for me with 2.012.
 Note: Restart the Android App, if you did any changes.
  
![image](https://user-images.githubusercontent.com/48840279/146374093-7c17437a-d0dc-4688-a45e-bafb06f36f30.png)

**Comment by nicksears** [comment]
That did the trick! I previously had all four of those buttons enabled.

Thank you so much, this was the one final missing piece to this amazing
setup!

Thanks
Nick
