### ISSUE TITLE
Failed to get record: 'WHERE type =?

### ISSUE THREAD

**Issue by TMTYD** [hyperion-project/hyperion.ng#1273]
- [ x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
When I call up the status using systemctl from hyperiond@xx.service there is the following error message:
```
hyperiond DB: <ERROR> Failed to get record: 'WHERE type =?' in table: 'settings' Error:
Jul 18 07:26:02 pi [667]: Failed to get record: 'WHERE type =?' in table: 'settings' Error: 
```

#### System

> Hyperion Server: 
> - Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
> - Build time:      Nov 18 2020 21:34:12
> - Git Remote:      https://github.com/hyperion-project/hyperion.ng
> - Version:         2.0.0-alpha.9
> - UI Lang:         auto (BrowserLang: de)
> - UI Access:       default
> - Avail Capt:      dispmanx,v4l2,framebuffer,qt
> - Database:        read/write
> 
> Hyperion Server OS: 
> - Distribution:   Raspbian GNU/Linux 10 (buster)
> - Architecture:   arm
> - CPU Model:      ARMv7 Processor rev 3 (v7l)
> - CPU Type:       Raspberry Pi 4 Model B Rev 1.1
> - CPU Revision:   c03111
> - CPU Hardware:   BCM2711
> - Kernel:         linux (5.10.17-v7l+ (WS: 32))
> - Qt Version:     5.7.1
> - Python Version: 3.5.3
> - Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0

**Comment by Lord-Grey** [comment]
@TMTYD Hi, seems that you database includes invalid records or does not match the Hyperion version you are running.
I suggest you try with the new alpha10 release and if that not work, start with a fresh database.

**Comment by TMTYD** [comment]
Ok, thanks, then I'll try version 10, but in the web interface under System -> Update, you can't do an update, it says it

``
No updates available for selected channel.
``
