### ISSUE TITLE
Missing option PAL/NTSC

### ISSUE THREAD

**Issue by HITMIK** [hyperion-project/hyperion.ng#1275]
Hi,

aplha10 not incluted in usb capture option PAL or NTSC. Can you add it? I have white-black screen because I havent option change to PAL.

Thanks

- [x] I confirm that this is an issue rather than a question.

**Comment by Lord-Grey** [comment]
You you enabled the "Expert" settings level?
Can you see it then?

**Comment by HITMIK** [comment]
Wow, super man!

Sorry, for me stupidity O:-)

Thanks, solved :-)

**Comment by Lord-Grey** [comment]
@HITMIK You are welcome. 
I will close the issue.
