### ISSUE TITLE
Philips hue wizard not working - alpha10

### ISSUE THREAD

**Issue by N1c093** [hyperion-project/hyperion.ng#1276]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The philips hue wizard is not working in alpha 10. 

#### Steps to reproduce

1. Add a new led output "philipshue"
2. Start hue wizard
2. Click on "continue"
3. Nothing happens :(

#### What is expected?
Hue wizard should run normally

#### What is actually happening?
Nothing

#### System

Hyperion Server: 
- Build:           (HEAD detached at b1a4e95c) (Paulchen-Panther-975f969a/b1a4e95c-1626550299)
- Build time:      Jul 17 2021 20:59:56
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         en (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a22082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

#### Additional information:
I noticed some errors in the development tools of chrome, when I click the button "continue".

![image](https://user-images.githubusercontent.com/59510296/126160272-271cf04c-9612-4f5f-84cf-4f63c68a6867.png)

**Comment by Lord-Grey** [comment]
@N1c093 Thanks for reporting! I confim it is a bug in the wizard. I will look for it.
Nevertheless, you should be able to configure and run Hue without the wizard.

**Comment by peterbaumert** [comment]
> @N1c093 Thanks for reporting! I confim it is a bug in the wizard. I will look for it.
> Nevertheless, you should be able to configure and run Hue without the wizard.

root.specificOptions.output doesnt seem to be defined but it looks for it.
