### ISSUE TITLE
Not work in hyperian

### ISSUE THREAD

**Issue by Ninoh-FOX** [hyperion-project/hyperion.ng#1277]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Qt lib not compatible

#### Steps to reproduce

Update from 2.0.9 alpha to 2.0.10 alpha via apt

#### What is expected?

@HyperBian:~ $ hyperiond
Cannot mix incompatible Qt library (version 0x50701) with this library (version 0x50b03)

Hyperion caught signal :SIGABRT
2021-07-19T20:14:07.539 hyperiond CORE         : <ERROR>        /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb547d130]
Abortado

#### What is actually happening?

Not work

#### System

Hyperian rpi 4

**Comment by mutlucan96** [comment]
Same is happening on rpi 3b+

**Comment by Lord-Grey** [comment]
Did you uninstall alpha9 before installing alpha10 via apt?
Given that alpha9 was not installed via apt, you need to uninstall it first...

**Comment by Ninoh-FOX** [comment]
Ok, I go back to a9, I go try this, another question. How can I autostart the service in hyperian? I am edit the autostart file of desktop add @hyperiand line, but I prefer another way.

**Comment by Lord-Grey** [comment]
If you install Hyperion via a package on a rpi, the installation is that way that Hyperion starts when booting. It runs as a background service.

**Comment by Ninoh-FOX** [comment]
Yes. Now works with uninstall a9 first, thanks.
