### ISSUE TITLE
Blackbar detection not working properly

### ISSUE THREAD

**Issue by mcl22** [hyperion-project/hyperion.ng#1278]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hello, I use a camera to grab the picture information from an oled tv. I've been doing this for several month now and it's working pretty well with one exception: everytime there is content with letterboxes the upper and lower leds only light up sporadically for perhaps 5 to 15 seconds. 

Since I use a camera I had to adjust the corners to get the picture information right. I wonder if the technique to detect the black bars respects those adjustments? As you can see on the screenshot there of course is a part of my wall which is led up when the leds are on. Can this cause this strange behaviour?

Hallo, ich habe das Problem, dass die Blackbar Detection nur sporadisch funktioniert. Dies war in der alpha 9 bereits ebenso. Da es sich nach dem Update auf die alpha 10 nicht geändert hat, melde ich den Bug jetzt. Ich habe bereits mit sämtlichen Einstellungen (unbekannte Bilder, Randbilder, inkonsistente Bilder und unscharfe Pixel) sowie Modi herumgespielt. Ebenso mit der Schwelle. Ich muss an dieser Stelle aber 2 wichtige Dinge hinzufügen:
1. ich besitze einen OLED, sprich schwarz ist wirklich schwarz
2. das spielt eine Rolle, weil ich seit einigen Monaten weg vom Grabber auf eine Cam umgestiegen bin

Bei Vollbild habe ich absolut keine Probleme. Bei Letterboxen hingegen werden die oberen und unteren LEDs mal kurzzeitig angesteuert, dann wieder nicht mehr. Bei unterschiedlich dicken Letterboxen tritt dieser Effekt stärker bzw. schwächer auf.

Auf Grund der Tatsache, dass ich eine Cam nutze, verwende ich im LED Layout auch die Optionen, um die Ecken anzugleichen und beschneide natürlich das Bild entsprechend (seit der alpha 10 kann ich hier nur noch 1024x768 als Auflösung wählen).

Wenn ich mir ansehe, welche Methoden die Modi zum Erkennen nutzen, frage ich mich, ob diese Anpassungen evtl. das Problem darstellen? 
Wie man an meinem Layout sehen kann gibt es natürlich unten und oben je einen schmalen Bereich der quasi meine Wand abfilmt und somit bei aktivierten LEDs entsprechende Farbinformationen liefert.
![LED Layout](https://user-images.githubusercontent.com/22153409/126213981-1e1b8c0c-e79f-4756-a82b-4e112774ef66.png)

Here are some live examples:
Hier das ganze nochmal in Action:
![2021-07-19 20_39_02-Hyperion - Web Konfiguration - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/22153409/126214287-415ae2c9-a12a-45ba-8a3e-aaffdc0e5332.png)
![2021-07-19 20_40_51-Hyperion - Web Konfiguration und 1 weitere Seite - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/22153409/126214301-96ff2d8d-09aa-44df-9c7d-9cc2000a9b58.png)

#### Steps to reproduce
Play content containing letterboxes.
Inhalt mit Letterboxen abspielen.

#### What is expected?
All leds including those on the top and the bottom should light up.
Die oberen und unteren LEDs sollten den Inhalt des oberen und unteren Randes abbilden.

#### What is actually happening?
The expected behaviour only occurs sporadically for a pretty short time and leds turn off right after.
Das erwartete Verhalten tritt nur sporadisch und abhängig von der Balkenstärke nur für ca. 5 bis 15 Sekunden ein.

#### System

Hyperion Server: 
- Build:           (HEAD detached at b1a4e95c) (Paulchen-Panther-975f969a/b1a4e95c-1626550299)
- Build time:      Jul 17 2021 20:59:56
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         de (BrowserLang: de)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.79-v7+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.70

**Comment by Lord-Grey** [comment]
@mcl22 Letterbox detection is independent from how you map the LEDs to the Screen to assign a screen area to an LED.
Border detection works on the input image provided.
Given that you have light borders outside the screen, which are part of your image, the current algorithm does not detect black below the given threshold

![image](https://user-images.githubusercontent.com/48840279/127902535-88d660c6-6478-49c3-b876-8c0bd58b63e6.png)

The current algorithm are currently not designed for Cam-Capture overlapping outside the TV screen therefore I close the issue.
