### ISSUE TITLE
Device disabled, device 'ws281x' signals error

### ISSUE THREAD

**Issue by mutlucan96** [hyperion-project/hyperion.ng#1280]
- [x] I confirm that this is an issue rather than a question.

## Bug report
ws281x won't work on fresh install Hyperbian alpha 10. Was working fine on alpha 9.

#### Steps to reproduce
-Start a fresh image of Hyperbian.
-Choose ws281x

#### What is expected?
- LEDs should work. It was working out of the box on alpha9

#### What is actually happening?
-LEDs won't turn on
- `[hyperiond LEDDEVICE] (ERROR) Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: mmap() failed'` appears on the log.

What I tried:
- Disabling audio on config.txt and blacklisting snd_bcm2835
- `sudo systemctl disable --now hyperion@pi` without d
- `sudo systemctl enable --now hyperion@root` without d

after doing these LEDs still won't work but also USB capture disappeared.

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.10) (Paulchen-Panther-975f969/b1a4e95-1626550299)
- Build time:      Jul 17 2021 21:50:25
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17-v7+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (X11; CrOS x86_64 13904.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by Lord-Grey** [comment]
The error  'Failed to open. Error message: mmap() failed' means that Hyperion is missing the access rights to write to the ws281x. Only for this type of LED, you need to run under root.
See the forum, for what is required….

**Comment by mutlucan96** [comment]
As I stated in my description, I tried what is required by reading forums.

**Comment by Lord-Grey** [comment]
Have you e.g. looked here

https://hyperion-project.org/forum/index.php?thread/11895-help-please-leds-not-working/&postID=39134&highlight=mmap%2528%2529%2Bfailed#post39134

**Comment by Guyohms** [comment]
I think that the Alpha 9 release of **Hyperbian** was already setup to run as root.
I don't think I had to run these commands to get 'ws281x' running.

**Comment by tpmodding** [comment]
can you start hyperiond and show me the output from "top | grep hyperiond"

**Comment by Guyohms** [comment]
> can you start hyperiond and show me the output from "top | grep hyperiond"

```
pi@HyperBian:~ $ top | grep hyperiond
  458 pi        20   0  274788  36424  28524 S   5.0   8.3   0:17.06 hyperiond
```

**Comment by Guyohms** [comment]
Also...
```
pi@HyperBian:~ $ sudo systemctl disable --now hyperiond@pi
Failed to disable unit: Unit file hyperiond@pi.service does not exist.

pi@HyperBian:~ $ sudo systemctl enable --now hyperiond@root
Failed to enable unit: Unit file hyperiond@root.service does not exist.
```

**Comment by tpmodding** [comment]
i have flashed a new hyperbian image, entered the same commands, and it worked

sudo systemctl disable --now hyperion@pi
sudo systemctl enable --now hyperion@root

<img width="766" alt="Bildschirmfoto 2021-07-21 um 01 38 13" src="https://user-images.githubusercontent.com/17259976/126408413-7babd04d-770b-4642-8962-b4b0306cbd63.png">

so can not reproduce it... it would kindly ask you to flash the image new and try it again

**Comment by Guyohms** [comment]
You are right!
I reflashed the image and now the commands works!

But I don't remember having to do this on alpha 9 though.

Thanks

**Comment by televisi** [comment]
Sorry for a noob question.

When you said that you fixed the issue by re-flashing the image, does it mean you re-flashed it with the same version of hyperbian from https://docs.hyperion-project.org/en/user/HyperBian.html 2.0.0-alpha.10?

**Comment by Guyohms** [comment]
> Sorry for a noob question.
> 
> When you said that you fixed the issue by re-flashing the image, does it mean you re-flashed it with the same version of hyperbian from https://docs.hyperion-project.org/en/user/HyperBian.html 2.0.0-alpha.10?

Yes that's what I did.
