### ISSUE TITLE
Signal detection does not switch off all instances

### ISSUE THREAD

**Issue by NeeeeB** [hyperion-project/hyperion.ng#1281]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Signal detection does not switch off all instances

#### Steps to reproduce
create 2 or more instances and set signal detection to switch off ambilight if no signal

#### What is expected?
all instances switch off

#### What is actually happening?
only the last (or 2 last) instances switch off

#### System

Hyperion.NG Alpha 10

**Comment by Burnsys2** [comment]
Same issue here with two instances

**Comment by Lord-Grey** [comment]
Fixed via #1421
