### ISSUE TITLE
Connection to WLED not working on Alpha 10

### ISSUE THREAD

**Issue by kafisc1** [hyperion-project/hyperion.ng#1287]
![WLED_Alpha_10](https://user-images.githubusercontent.com/56489749/126910186-b3fb3cc2-a8cc-4c9f-a9f8-3c78a5cfcf77.JPG)
![WLED_Alpha_9](https://user-images.githubusercontent.com/56489749/126910212-8c62522a-9a4e-4c1d-8d83-fc280f8d8f08.JPG)

- [x] I confirm that this is an issue rather than a question.

## Bug report
Since updating from Alpha 9 (with a working connection to WLED device) to the latest Alpha 10 on my X86 NUC with Libreelec, I'm unable to connect to WLED device (0.12.0).

#### Steps to reproduce
- Try to connect to WLED device on ALPHA 10
- Not connecting
- No device is found when searching for a (new) WLED device
- WLED is also not working if I enter all the needed information manually
- Downgrade to Alpha 9 and WLED is working instantly

#### What is expected?
- Connecting to WLED

#### What is actually happening?
- Not recognizing and connecting to WLED and also not connecting to WLED when I enter the informations manually.

#### System
Hyperion Server: 
- Build:           (HEAD detached at b1a4e95c) (Paulchen-Panther-975f969a/b1a4e95c-1626550299)
- Build time:      Jul 17 2021 20:46:40
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         de (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      v4l2,framebuffer,x11,xcb,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   LibreELEC (community): nightly-20210716-4b15caf
- Architecture:   x86_64
- CPU Model:      Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
- CPU Type:       92
- Kernel:         linux (5.10.47 (WS: 64))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36

**Comment by Lord-Grey** [comment]
@kafisc1 Thanks for reporting.

> No device is found when searching for a (new) WLED device

That behaviour is correct. The discovery of WLED is not yet supported. It will be most likely available in some upcoming release.

> WLED is also not working if I enter all the needed information manually

It is an indication that your WLED device cannot be reached by the system hyperion is running on.
If you enter the IP address or name and then press Tab to move to the next element, WLED properties should be resolved automatically. Them the "Identify" and "Save" buttons get enabled.

Could you do me a favour and run hyperion alpha10 with debug logging on.
Capture the WLED address and press Tab.
Share the log output here.

Many thanks in advance!

**Comment by kafisc1** [comment]
Thank you very much for your help.
The "Identify" and "Save" buttons are both enabled.
I was able to resolve the issue by entering the IP from the WLED device manually and then by clicking on "Identify" and afterwards on the "Save" button.
When I tried first to connect to WLED I only pressed the "Save" button on not the "Identify" button.

Please find the logs attached for: "Capture the WLED address and press Tab"
[logs.txt](https://github.com/hyperion-project/hyperion.ng/files/6891709/logs.txt)

**Comment by Lord-Grey** [comment]
@kafisc1 Great that it is working now.
