### ISSUE TITLE
[Feature request] Allowing to manually set the serial path.

### ISSUE THREAD

**Issue by philibertc** [hyperion-project/hyperion.ng#1293]
#### What problem does this feature solve?
When a serial device changes from /dev/ttyUSB0 to /dev/ttyUSB1 for example, and you have to open the configuration to change the path.

#### How should this be implemented in your opinion?
Just by letting users manually write the path to the serial device.

#### Are you willing to work on this yourself?
I would like to but do not understand Hyperion enough to do so.

**Comment by Lord-Grey** [comment]
@philibertc I assume you are reposting this in context of alpha10.
What is not clear for me is the difference of manually updating a path versus selecting it from a top down?
If the path would have changed, the drop-down reflects this, given that hyperion looks for feasible configurations in the background. This helps to avoid "wrong" manual configurations.

What I guess is you are looking for is a "stable" path which does not change over time.
Here the answer is not manual configuration, but to use a udev configuration under unix.
That is already supported out-of the box by alpha10.

see https://github.com/hyperion-project/hyperion.ng/pull/1246

In case I missed you point, maybe you outline your problem and not a potential solution...

**Comment by philibertc** [comment]
Hello,
The problem is when you connect the adalight device and the port /dev/ttyUSB0 is already in use, you have to open the configuration to change the port to /dev/ttyUSB1, and it is annoying.

**Comment by philibertc** [comment]
I created a link /dev/ttyUSB-Adalight which works. But I can't select it via the hyperion web interface.
