### ISSUE TITLE
spidev not found

### ISSUE THREAD

**Issue by TMTYD** [hyperion-project/hyperion.ng#1296]
Hello

I have the following error message:

pi hyperiond [1397]: Device disabled, device 'ws2801' signals error: 'Failed to open device (/dev/spidev0.0). Error message: No such file or directory '

spi is activated under raspi-config, as well as in /boot/config.txt via dtparam = spi = on

I still get this message, why is that?

**Comment by TMTYD** [comment]
Why closed?

**Comment by tpmodding** [comment]
because you ignored our issue template

**Comment by TMTYD** [comment]
Oh ok, sorry I Try again

**Comment by Lord-Grey** [comment]
@TMTYD You might want bringing up your question in the Hyperion forum (https://hyperion-project.org/forum/),
as it is very likely that it is a configuration issue, rather than a bug....

**Comment by TMTYD** [comment]
Ok

**Comment by TMTYD** [comment]
this is my thread

[spidev not found](https://hyperion-project.org/forum/index.php?thread/12036-spidev-not-found-info/)
