### ISSUE TITLE
USB Signal detection missing on alpha10

### ISSUE THREAD

**Issue by V10lator** [hyperion-project/hyperion.ng#1300]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The USB signal detection is missing from the web interface. It was there with alpha9 through.

#### Steps to reproduce
Open the web interface and search for signal detection.

#### What is expected?
Finding it.

#### What is actually happening?
Going crazy cause it's nowhere.

#### System

Hyperion Server: 
- Build:           coreelec-19 (Portisch-1333b74d4d/c908f00eaa-1628142929)
- Build time:      Aug  5 2021 09:16:28
- Git Remote:      git@github.com:CoreELEC/CoreELEC.git
- Version:         2.0.0-alpha.10
- UI Lang:         de (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,amlogic,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   CoreELEC (official): 19.2-Matrix_rc3
- Architecture:   arm64
- CPU Model:      Amlogic S905X rev b
- CPU Revision:   0400
- CPU Hardware:   Le Potato
- Kernel:         linux (4.9.113 (WS: 32))
- Qt Version:     5.13.0
- Python Version: 3.8.9
- Browser:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by V10lator** [comment]
Never mind, the update just resetted the config level from expert back to default.

**Comment by Paulchen-Panther** [comment]
@V10lator Please open a new issue for this.
Thanks a lot

**Comment by V10lator** [comment]
@Paulchen-Panther I'll do tomorrow but just to clearify: You want me to open a new report for the issue that the config setting resetted with the update, right? I also found another setting (Capturing Hardware) to reset which was way more annoying as I had to reconfigure all subsettings from scratch. So do you want me to open two new bug reports or just one?

**Comment by Lord-Grey** [comment]
@V10lator No need to spend effort capturing issues on your end.
a) The Settings Level is only captured locally in your Browser. In case you deleted Cookies or used a different browser. You need to switch settings level. Nothing dependent on the Hyperion server part.
b) As outlined in the Release Notes,
https://github.com/hyperion-project/hyperion.ng/releases
the grabber is disabled and you need to enable it. 
@portisch Might be worth to add this to the CoreElec Plug-in Release notes too.
