### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by Paulchen-Panther** [hyperion-project/hyperion.ng#131]
@redPanther 

Der Fehler "*** stack smashing detected ***" tritt auf sobald ich ein Youtube Video abspielen möchte. Es ist die Zeile 126 im [kodivideochecker.cpp](https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/kodivideochecker/KODIVideoChecker.cpp#L128)
Kommentiere ich diese aus, tritt der Fehler nicht auf. 

Hier die Ausgabe:
`Starting program: /home/paulchen/Schreibtisch/KodiVideoChecker/build/bin/hyperiond hyperion.config.json --debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[HYPERIOND MAIN] <INFO> Selected configuration file: hyperion.config.json
[HYPERIOND Core] <INFO> ColorTransform 'default' => [0; 45]
[HYPERIOND Core] <INFO> ColorTemperature 'default' => [0; 45]
[HYPERIOND Core] <INFO> ColorAdjustment 'default' => [0; 45]
[HYPERIOND LedDevice] <INFO> configuration: 
{
	"colorOrder" : "rgb",
	"name" : "DefaultHyperionConfig",
	"output" : "/dev/null",
	"rate" : 1000000,
	"type" : "file"
}
 
[HYPERIOND Core] <INFO> Smoothing disabled
[HYPERIOND EFFECTENGINE] <INFO> 27 effects loaded from directory /home/paulchen/Schreibtisch/hyperion/effects
[HYPERIOND EFFECTENGINE] <DEBUG> <EffectEngine.cpp:63:EffectEngine()> Initializing Python interpreter
[HYPERIOND Core] <DEBUG> <Hyperion.cpp:589:Hyperion()> configured leds: 46 hw leds: 46
[HYPERIOND LOGGER] <WARNING> Logger settings overriden by command line argument
[HYPERIOND MAIN] <INFO> Hyperion started and initialised
[HYPERIOND EFFECTENGINE] <INFO> run effect Rainbow swirl fast on channel 0
[HYPERIOND BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.000000 (0)
[HYPERIOND BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[HYPERIOND Core] <INFO> Register new input source named 'EFFECT: /home/paulchen/Schreibtisch/hyperion/effects/rainbow-swirl.py' for priority channel '0'
[HYPERIOND MAIN] <INFO> Inital foreground effect 'Rainbow swirl fast' started
[HYPERIOND EFFECTENGINE] <INFO> run effect Full color mood blobs on channel 2147483646
[HYPERIOND BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.000000 (0)
[HYPERIOND BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[HYPERIOND Core] <INFO> Register new input source named 'EFFECT: /home/paulchen/Schreibtisch/hyperion/effects/mood-blobs.py' for priority channel '2147483646'
[HYPERIOND MAIN] <INFO> Inital background effect 'Full color mood blobs' started
[HYPERIOND MAIN] <DEBUG> <hyperiond.cpp:212:createKODIVideoChecker()> KODI checker created 
[HYPERIOND KODI] <INFO> started
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:306:reconnect()> try reconnect
[HYPERIOND MAIN] <INFO> Json server created and started on port 19444
[HYPERIOND MAIN] <INFO> Proto server created and started on port 19445
[HYPERIOND MAIN] <DEBUG> <hyperiond.cpp:261:startNetworkServices()> Boblight server created
[New Thread 0x7fffee455700 (LWP 9322)]
[New Thread 0x7fffeee9b700 (LWP 9321)]
[New Thread 0x7fffef69c700 (LWP 9320)]
[New Thread 0x7fffefe9d700 (LWP 9319)]
[HYPERIOND MAIN] <DEBUG> <hyperiond.cpp:311:startNetworkServices()> Json mDNS responder started
[HYPERIOND MAIN] <DEBUG> <hyperiond.cpp:319:startNetworkServices()> Proto mDNS responder started
[HYPERIOND WEBSERVER] <INFO> started on port 8099 name "Hyperion WebConfig"
[HYPERIOND KODI] <INFO> Connected
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[]}
[HYPERIOND KODI] <INFO> switching to MENU mode
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[]}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":16,"minor":0,"revision":"2015-10-11-9272297","tag":"alpha","tagversion":"4"}}}
[HYPERIOND EFFECTENGINE] <INFO> effect finished
[HYPERIOND Core] <INFO> Unregister input source named 'EFFECT: /home/paulchen/Schreibtisch/hyperion/effects/rainbow-swirl.py' from priority register
[Thread 0x7fffefe9d700 (LWP 9319) exited]
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnClear","params":{"data":{"playlistid":1},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"More Newly Discovered Pokémon Have Arrived for Pokémon Sun and Pokémon Moon!","type":"movie","year":2016},"playlistid":1,"position":0},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Only Jon Stewart Can Make Sense of the Trump Candidacy","type":"movie","year":2016},"playlistid":1,"position":1},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Coming Wednesday: Carpool Karaoke with The First Lady","type":"movie","year":2016},"playlistid":1,"position":2},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Comparing Melania Trump and Michelle Obama's speeches","type":"movie","year":2016},"playlistid":1,"position":3},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Jeffree Star: It's so much easier to do the right thing.","type":"movie","year":2016},"playlistid":1,"position":4},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"SUICIDE SQUAD - Official Final Trailer (2016) DC Superhero Movie HD","type":"movie","year":2016},"playlistid":1,"position":5},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Honest Trailers - Batman v Superman: Dawn of Justice","type":"movie","year":2016},"playlistid":1,"position":6},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Ridiculous Rhett Reactions","type":"movie","year":2016},"playlistid":1,"position":7},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Water Bottle Flip Edition | Dude Perfect","type":"movie","year":2016},"playlistid":1,"position":8},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"The Not- Ready-For-Primetime Party | Full Frontal with Samantha Bee | TBS","type":"movie","year":2016},"playlistid":1,"position":9},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Donald Trump Entrance at GOP Convention (C-SPAN)","type":"movie","year":2016},"playlistid":1,"position":10},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Melania Trump's full speech at the 2016 Republican National Convention","type":"movie","year":2016},"playlistid":1,"position":11},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"WHY TAYLOR SWIFT'S LEAKED EXPOSE VIDEO IS A HUGE DEAL! I know...even I'm surprised.","type":"movie","year":2016},"playlistid":1,"position":12},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Rep. Steve King says white people have contributed more to civilization than other 'sub-groups'","type":"movie","year":2016},"playlistid":1,"position":13},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"ضب\" ماتحمل الحر وراح يدور للظل | اللهم ارحمنا","type":"movie","year":2016},"playlistid":1,"position":14},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"This plane could cross the Atlantic in 3.5 hours. Why did it fail?","type":"movie","year":2016},"playlistid":1,"position":15},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Steve King Asks: What Have Minorities Contributed To Civilization?","type":"movie","year":2016},"playlistid":1,"position":16},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Stephen Colbert Hijacks Mic at RNC","type":"movie","year":2016},"playlistid":1,"position":17},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Bailey - Who's Got It Better Than Us?","type":"movie","year":2016},"playlistid":1,"position":18},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"We asked Trump voters about Melania's plagiarism scandal. Here's what they said.","type":"movie","year":2016},"playlistid":1,"position":19},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Sheriff David Clarke Crushes Don Lemon Over Hateful Black Lives Matter","type":"movie","year":2016},"playlistid":1,"position":20},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"UNDERTALE SPIDER DONUTS ft Dan & Phil! - NERDY NUMMIES","type":"movie","year":2016},"playlistid":1,"position":21},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Futurama - The Science of Comedy","type":"movie","year":2016},"playlistid":1,"position":22},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Hitting the Sun is HARD","type":"movie","year":2016},"playlistid":1,"position":23},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Republican National Convention Live Stream Monday [Official]","type":"movie","year":2016},"playlistid":1,"position":24},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"FULL REPLAY: Day 2 of Republican National Convention in Cleveland - July 19, 2016","type":"movie","year":2016},"playlistid":1,"position":25},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Miranda Lambert - Vice (Audio)","type":"movie","year":2016},"playlistid":1,"position":26},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Chris Pine Learned Never to Mix Goldschläger, Beer and Chinese Food","type":"movie","year":2016},"playlistid":1,"position":27},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Who Is Mike Pence? A Closer Look","type":"movie","year":2016},"playlistid":1,"position":28},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Melania Trump Speech - RNC","type":"movie","year":2016},"playlistid":1,"position":29},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"The YouTube Factory feat. Dwayne \"The Rock\" Johnson, Lilly Singh, and More!","type":"movie","year":2016},"playlistid":1,"position":30},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Kim Kardashian exposes Taylor Swift on Snapchat [Part 1]","type":"movie","year":2016},"playlistid":1,"position":31},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Melania Trump's RNC speech vs. Michelle Obama's 2008 DNC speech","type":"movie","year":2016},"playlistid":1,"position":32},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Johnny B. Goode (Live in NY w/ Michael J. Fox)","type":"movie","year":2016},"playlistid":1,"position":33},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"The Girl on the Train - Official Trailer - In Theaters October 7 (HD)","type":"movie","year":2016},"playlistid":1,"position":34},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Casually Explained: The Spectrum of Intelligence","type":"movie","year":2016},"playlistid":1,"position":35},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"How To Be a YouTube Star (ft. The Rock)","type":"movie","year":2016},"playlistid":1,"position":36},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Last Week Tonight with John Oliver: Endorsements (Web Exclusive)","type":"movie","year":2016},"playlistid":1,"position":37},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"POWERFUL! ♥ FULL SPEECH: Patricia Smith, mother of Benghazi victim - Republican National Convention","type":"movie","year":2016},"playlistid":1,"position":38},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Melania Trump and Michelle Obama speeches side by side","type":"movie","year":2016},"playlistid":1,"position":39},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Karwia - dzik wyszedł z morza i zaatakował ludzi","type":"movie","year":2016},"playlistid":1,"position":40},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Bitmoji on Snapchat!","type":"movie","year":2016},"playlistid":1,"position":41},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"EARTH ANGEL/ JOHNNY B. GOODE -MICHAEL J. FOX & COLDPLAY: HEAD FULL OF DREAMS TOUR 7.17.16 NYC/NJ","type":"movie","year":2016},"playlistid":1,"position":42},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"FAN-O-RAMA - A Futurama Fan Film","type":"movie","year":2016},"playlistid":1,"position":43},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"DIY Hydro Dipping - Pinterest Test - Man Vs Pin #95","type":"movie","year":2016},"playlistid":1,"position":44},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"THE MAGNIFICENT SEVEN - Official Trailer (HD)","type":"movie","year":2016},"playlistid":1,"position":45},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Ivanka Trump On GOP Leaders Not Attending Republican National Convention","type":"movie","year":2016},"playlistid":1,"position":46},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Confessions of a Republican | Hillary Clinton","type":"movie","year":2016},"playlistid":1,"position":47},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"xXx: Return of Xander Cage - Teaser Trailer (2017) - Paramount Pictures","type":"movie","year":2016},"playlistid":1,"position":48},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"YouTube Music – Afsa’s Theme","type":"movie","year":2016},"playlistid":1,"position":49},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"title":"Ridiculous Rhett Reactions","type":"movie","year":2016},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
[HYPERIOND KODI] <INFO> switching to VIDEO mode
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:126:receiveReply()> message: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"https://r8---sn-uxax4vopj5qx-cxge.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&key=yt6&itag=22&lmt=1468995474342434&signature=34EA3987AED2DE4BA30051D7356766EC4600BAE8.88B6DEDC90B92869E21F72F705768E77FF5B5850&expire=1469031687&cnr=14&pcm2cms=yes&pl=23&sver=3&requiressl=yes&upn=Q9yJZfrgrO4&ei=p1CPV6aBHYj_cZf8qLgN&ip=78.53.194.219&initcwndbps=1253750&id=o-AM2jTPCBq55uGpOjHVDNHJbSvKSrE5q6S_5i8GSE7YXm&sparams=cnr%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ratebypass=yes&mm=31&source=youtube&mn=sn-uxax4vopj5qx-cxge&mt=1469009568&mv=m&ms=au&fexp=9416891%2C9422596%2C9428398%2C9431012%2C9432367%2C9433096%2C9433223%2C9433946%2C9435526%2C9435876%2C9437552%2C9438663%2C9439652%2C9440880%2C9442424&dur=90.999","label":"Ridiculous Rhett Reactions","type":"unknown"}}}
*** stack smashing detected ***: /home/paulchen/Schreibtisch/KodiVideoChecker/build/bin/hyperiond terminated
[New Thread 0x7fffeda07700 (LWP 9323)]

Program received signal SIGABRT, Aborted.
0x00007ffff4eee267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) 
`

**Comment by redPanther** [comment]
Ich bin mir nicht sicher, aber ich glaube die sache mit dem "constData" is nich so gut ... jedenfalls nich so wie wir das da verwenden.  

versuch mal:
Debug(_log, "message: %s", std::string(doc.toJson(QJsonDocument::Compact).constData(),  doc.toJson(QJsonDocument::Compact).size()).c_str()  );

geht aber sicher noch eleganter ... scheint als wenn constData eben nich zwangsweise nullterminiert sein muss und dann gibts ärger ...

**Comment by Paulchen-Panther** [comment]
Ok. Vielen Dank für deine Erklärung.  Ich werd es mal probieren

**Comment by Paulchen-Panther** [comment]
@redPanther:
Leider immer noch der selbe fehler

**Comment by redPanther** [comment]
bin schon dran. was bei mir geht:
was geht:
```
QString qmsg(doc.toJson(QJsonDocument::Compact));                                                                                                            
const char* msg = qmsg.toStdString().c_str();                                                                                                                
Debug(_log, "message: %s", msg);
```
... aber gefällt ir noch nich ...

**Comment by Paulchen-Panther** [comment]
Funktionieren tut es aber es gibt keine Ausgabe mehr von der Reply ID 667.

`[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:128:receiveReply()> message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"title":"Jayna Brown: See How This Smiley Teen Singer Earns the Golden Buzzer - America's Got Talent 2016","type":"movie","year":2016},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:128:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
[HYPERIOND KODI] <INFO> switching to VIDEO mode
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:128:receiveReply()> message: 
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:128:receiveReply()> message: {"id":669,"jsonrpc":"2.0","result":{"stereoscopicmode":{"label":"Deaktiviert","mode":"off"}}}`

**Comment by Paulchen-Panther** [comment]
Ab und zu gibt es auch noch dieses Zeichen zu sehen. 

**Comment by redPanther** [comment]
ok ich habs.
schau mal hier: https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/utils/Logger.cpp#L126

das definiert die message mit max 512 zeichen. Die tollen youtube urls sind aber etwas üppiger.

Wenn man das so schreibt:
`Debug(_log, doc.toJson(QJsonDocument::Compact).constData());`
geht das, da der erste parameter der format parameter ist und der hat keine beschränkung. Das Wäre dann erstmal nen schneller fix. Ich muss mal schauen wie ich das im logger sicherer hinbekomme ... Eine grenze muss es aber geben. Ich würde dann den string abschneiden - auf jedenfall darf es nich crashen

**Comment by redPanther** [comment]
... ok hab jetzt nen fix im logger. lange nachrichgten sollten jetzt nich mehr zum crash führen

**Comment by Paulchen-Panther** [comment]
Hab gerade auch das const char auf 1024 erhöht und es schmiert bei sehr langen url's von youtube ab. erst ab 2048 habe ich keine Abstürze mehr.

**Comment by redPanther** [comment]
aber mit meinem fix, sollte es auch mit 1024 gehen (natürlich nur mit abgeschnitter url)
der (dumme) fehler war vsprintf anstelle von vsnprintf zu verwenden. zweiteres passt schön auf das man nich irgendwi im speicher rumschreib wo man nix zu suchen hat ...

**Comment by Paulchen-Panther** [comment]
Habs gerade getestet. Funktioniert super. Er schneidet zwar die URL ab und den rest von JSON Object aber das kann man verkraften.
Vielen Dank für deine schnelle Hilfe.
Ich mach dann mal hier zu.
