### ISSUE TITLE
Hyperion.NG on OSMC (on Pi3b) screen grab seems to be looking at console?

### ISSUE THREAD

**Issue by harvybob** [hyperion-project/hyperion.ng#1310]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I have a new install of OSMC running on Pi3. On top of that i did the following:

wget -qO- https://apt.hyperion-project.org/hyperion.pub.key | sudo apt-key add -
echo "deb https://apt.hyperion-project.org/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hyperion.list
sudo apt-get update && sudo apt-get install hyperion

Set up the LED's w2801 and these are controlable by remote and functioning correctly if setting a colour via remote.

Kodi/Hyperion.NG both running on the same PI, and TV is plugged in via HDMI 

The issue i have is that having enabled the screen grabber, the LED's do not light with the image, using the LED Layout Preview if I enable Live Video, I think i am looking at a blury image of the console rather then the KODI landing page? But I see no way of modifying that?

#### Steps to reproduce
Clean new install of OSMC 20210808 build (19.1)
Installed Hyperion.NG via apt-get
Configured LED's via web interface
Configured screen grabbing - 
Capture Hardware set to Activate, 
Device Discovered = Frame Buffer
Frequency =25
decimation = 8
crop left/right/top/bottom = 0

Play any Video on Kodi and get no capture.
Starting and stopping a colour via Hyperion remote shows a few LED's lit on top left - where you would normally see the console on linux.

Looking at the LED OUTPUT -> LED Layout and enabling live video shows a blury image with white boxes on the top left - possibly console prompt?

#### What is expected?
screen grabbing of the Kodi image rather then console

#### What is actually happening?
Appears that the default grabber is set to console grabbing

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.10) (Paulchen-Panther-975f969/b1a4e95-1626550299)
- Build time:      Jul 17 2021 21:50:25
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         en (BrowserLang: en-GB)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Open Source Media Center
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.32-2-osmc (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Comment by Lord-Grey** [comment]
@harvybob Closing, as this is a duplicate to #983 

see also https://hyperion-project.org/forum/index.php?thread/12079-kodi-ambilight-not-working-but-hyperion-remote-ok/&postID=40986#post40986
