### ISSUE TITLE
UI bug : Pannel Led Output/Led Layout parameter Load/Edit/Save

### ISSUE THREAD

**Issue by spiderjn** [hyperion-project/hyperion.ng#1314]
- [x] I confirm that this is an issue rather than a question.

## Bug report

When i try to configure my led layout, UI Crash but parameter are stored,
when i reopen this pannel, "LED Layout Preview" is correct,  but when when click on "Classic Layout (LED Frame)" only basic information are correctly displayed (top, bottom,left,right) and pannel "LED Layout Preview" is resetted.

i must re-enter all time, values : "Gap length", "Gap position", "Input position" and "reverse direction"

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/35093306/130569698-71f2be37-8f05-4894-8487-9af215059901.png)

click on "Classic Layou"

![image](https://user-images.githubusercontent.com/35093306/130569838-48c2af9d-d233-4d53-b04f-d23541ba8d42.png)

#### What is expected?

to store and edit parameters.

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.10) (Paulchen-Panther-975f969/b1a4e95-1626550299)
- Build time:      Jul 17 2021 21:50:25
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         en (BrowserLang: fr-FR)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.52+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

**Comment by Lord-Grey** [comment]
@spiderjn Did this happend only once, or can you reproduce it?
In case the later, could you do a screenshot before you save the configuration and share it please?

Does a removal of cookies help?

**Comment by spiderjn** [comment]
it's reproductible, with 2 diff browser.

this is my configuration before click on SAVE

![image](https://user-images.githubusercontent.com/35093306/130686172-83a2bd3a-fa3a-4160-a318-f9018e6f6f68.png)

when i click on "save layout", UI restart on Hyperion splash screen and i'm back on this screen

![image](https://user-images.githubusercontent.com/35093306/130686336-6d7a2055-9084-4967-bf65-30885c155f4a.png)

but configuration is correctly generated.

**Comment by Lord-Grey** [comment]
@spiderjn Thanks for providing the additional details, with that I was able to reproduce the issue too.
We will have a look into it.

**Comment by Lord-Grey** [comment]
@spiderjn You can test the fix. it is part or #1312 .
Just download an artifact from a ready made build.

https://github.com/hyperion-project/hyperion.ng/pull/1312/checks?check_run_id=3423569871
