### ISSUE TITLE
Philips Hue Entertainment Wizard - Unable to click Continue

### ISSUE THREAD

**Issue by sofakng** [hyperion-project/hyperion.ng#1316]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I am unable to click continue in the Philips Hue Entertainment Wizard after a fresh install of Hyperbian.  I've tried Chrome and Edge browses.

#### Steps to reproduce
Navigate to LED Instances -> LED Output.  
Change Controller type from [file] to philips hue.  Wizard button appears.
Click Philips Hue Wizard.  Wizard opens with Continue and Cancel buttons.
Clicking Continue has no effect.

#### What is expected?
Wizard should continue.

#### What is actually happening?
Nothing happens.

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.10) (Paulchen-Panther-975f969/b1a4e95-1626550299)
- Build time:      Jul 17 2021 21:50:25
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.4
- CPU Revision:   b03114
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.17-v7l+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

**Comment by Lord-Grey** [comment]
Duplicate to #1276
