### ISSUE TITLE
Hyperion blocks VLC UPnP on Windows 10

### ISSUE THREAD

**Issue by mikosoft83** [hyperion-project/hyperion.ng#1324]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When Hyperion is running VLC will not discover any UPnP device. Tested on two different Windows 10 machines.

#### Steps to reproduce
Run Hyperion
Run VLC
Click "Universal Plug n Play" in VLC
Devices should pop up yet they don't
Close Hyperion
Close and run VLC again
Repeat UPnP discovery in VLC 
Devices show in the list

#### What is expected?
What it says above

#### What is actually happening?
Ditto

**Comment by Paulchen-Panther** [comment]
Thank you for the bug report. 👍🏼 
It has just been corrected (8fb3d76).

**Comment by mikosoft83** [comment]
@Paulchen-Panther just for information, is there a plan for next release? I'm not sure I'm up to the task of compiling the software myself.
