### ISSUE TITLE
Hyperion NG not starting on Libreelec 11 Nightly Builds

### ISSUE THREAD

**Issue by kafisc1** [hyperion-project/hyperion.ng#1338]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion Next Generation not starting on the latest Libreelec Builds with the error "error while loading shared libraries: libX11.so.6: cannot open shared object file"
Kodi Build tested: nightly-20210921-7455a76

#### Steps to reproduce
Install  LibreELEC (Matrix) 10.0.0, install Hyperion 2.0.0-alpha.10 check if it work.
--> Works
Update Libreelec to the latest Nightly 20210921-7455a76

--> "error while loading shared libraries: libX11.so.6: cannot open shared object file" appears and hyperion is not starting

If I downgrade again to Libreleec 10 Hyperion NG works again.

#### What is expected?
Hyperion NG should start

#### What is actually happening?
Hyperion NG is not starting and the following error-message appears in the journal:
Sep 22 08:45:40 LibreELEC hyperiond[1283]: /storage/hyperion/bin/hyperiond: error while loading shared libraries: libX11.so.6: cannot open shared object file
Sep 22 08:45:40 LibreELEC systemd[1]: hyperion.service: Main process exited, code=exited, status=127/n/a
Sep 22 08:45:40 LibreELEC systemd[1]: hyperion.service: Failed with result 'exit-code'.
Sep 22 08:45:50 LibreELEC systemd[1]: hyperion.service: Scheduled restart job, restart counter is at 4.
Sep 22 08:45:50 LibreELEC systemd[1]: Stopped Hyperion ambient light systemd service.
Sep 22 08:45:50 LibreELEC systemd[1]: Started Hyperion ambient light systemd service.
Sep 22 08:45:50 LibreELEC hyperiond[1290]: /storage/hyperion/bin/hyperiond: error while loading shared libraries: libX11.so.6: cannot open shared object file
Sep 22 08:45:50 LibreELEC systemd[1]: hyperion.service: Main process exited, code=exited, status=127/n/a
Sep 22 08:45:50 LibreELEC systemd[1]: hyperion.service: Failed with result 'exit-code'.
Sep 22 08:46:01 LibreELEC systemd[1]: hyperion.service: Scheduled restart job, restart counter is at 5.

#### System
 Not possible here, because Hyperion NG service is not running

Version: 2.0.0-alpha.10
Platform: x86

**Comment by FlyingPersian** [comment]
Probably something to do with:

`Hyperion Add-on no longer works
No solution for now, Hyperion doesn’t support the new graphics driver stack yet`? 

Source: https://libreelec.tv/2021/11/03/libreelec-matrix-10-0-1/ under Known Issues for RP4

**Comment by Fietspomp86** [comment]
This is unfortunately still relevant.

I've had a GPU upgrade so I had to switch from LE 10 to LE 11.


It gives me the same error (with latest Hyperion.ng 2.0.13 and also with one I build myself today):

`/storage/hyperion/bin/hyperiond: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`

I hope there is a workaround for this!

**Comment by Wickueler** [comment]
> It gives me the same error (with latest Hyperion.ng 2.0.13 and also with one I build myself today)

How did you build it?

**Comment by Fietspomp86** [comment]
> > It gives me the same error (with latest Hyperion.ng 2.0.13 and also with one I build myself today)
> 
> How did you build it?
> 
> Have you ever tried this method? https://hyperion-project.org/forum/index.php?thread/10753-compile-hyperion-ng-on-libreelec/

Yes I did. However it's nothing to do with how it's build. Newer LE (11) versions don't have X11.
Anyway, LE11 generic-legacy can maybe be used, I have not tried this though,

**Comment by Wickueler** [comment]
> > > It gives me the same error (with latest Hyperion.ng 2.0.13 and also with one I build myself today)
> > 
> > 
> > How did you build it?
> > Have you ever tried this method? https://hyperion-project.org/forum/index.php?thread/10753-compile-hyperion-ng-on-libreelec/
> 
> Yes I did. However it's nothing to do with how it's build. Newer LE (11) versions don't have X11. Anyway, just found there is also a legacy version of LE11 which has X11, with this version Hyperion works!

Someone knows a lot about building hyperion. Of course, it has to do with the build method. X11 can very well be turned off when building Hyperion. But you can do it better.

**Comment by Fietspomp86** [comment]
> > > > It gives me the same error (with latest Hyperion.ng 2.0.13 and also with one I build myself today)
> > > 
> > > 
> > > How did you build it?
> > > Have you ever tried this method? https://hyperion-project.org/forum/index.php?thread/10753-compile-hyperion-ng-on-libreelec/
> > 
> > 
> > Yes I did. However it's nothing to do with how it's build. Newer LE (11) versions don't have X11. Anyway, just found there is also a legacy version of LE11 which has X11, with this version Hyperion works!
> 
> Someone knows a lot about building hyperion. Of course, it has to do with the build method. X11 can very well be turned off when building Hyperion. But you can do it better.

The reason I said it has nothing to do with how I build it, is because I also built it without X11 ( ./docker-compile.sh -i x86_64 -- -DENABLE_X11=OFF ), but it still didn't work.

Anyway latest LE10 nightly works with my new GPU so I can use that.
And the LE11 generic-legacy builds work with Hyperion out of the box :-)
