### ISSUE TITLE
Error on Startup (Hyperion 2.0 Alpha 10.1 + LibreELEC 9.2 on RPi3)

### ISSUE THREAD

**Issue by koelle25** [hyperion-project/hyperion.ng#1344]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I just tried updating to Alpha 10.1 (which was released a few days ago). But when starting Hyperion using the systemd service, nothing happens and no error is shown.

When manually trying to start it the following error occurs:
```
Current thread 0x7333a040 (most recent call first):

Hyperion caught signal :SIGABRT
2021-10-05T13:00:36.815 hyperiond CORE         : <ERROR> 	/opt/vc/lib/libc.so.6(__default_rt_sa_restorer+0) [0x75656210]
Aborted
```

Using Alpha 10 everything works as expected.

#### Steps to reproduce
Install/Update Hyperion 2.0 Alpha 10.1 using [Paulchen-Panther's Script](https://gist.github.com/Paulchen-Panther/f0baf820343bbf800a041b102dd9cadd): `./libreelec.sh 2.0.0-alpha.10.1`.  => OK
`systemctl status hyperion` => NOT OK ("Main PID: 1604 (code=killed, signal=ABRT)")
`/storage/hyperion/bin/hyperiond --userdata /storage/hyperion/` => NOT OK (see error message above)

#### What is expected?
Downgrade Hyperion 2.0 using [Paulchen-Panther's Script](https://gist.github.com/Paulchen-Panther/f0baf820343bbf800a041b102dd9cadd) to Alpha 10: `./libreelec.sh 2.0.0-alpha.10` => OK
`systemctl status hyperion` => OK
`/storage/hyperion/bin/hyperiond --userdata /storage/hyperion/` => _OK_ ("The Hyperion Daemon is already running [...]"

#### What is actually happening?
see error message above

#### System

_/proc/cpuinfo_:
```
Hardware	: BCM2835
Revision	: a020d3
Serial		: 0000000081f01853
Model		: Raspberry Pi 3 Model B Plus Rev 1.3
```
_/etc/os-release_:
```
NAME="LibreELEC"
VERSION="9.2.8"
ID="libreelec"
VERSION_ID="9.2"
PRETTY_NAME="LibreELEC (official): 9.2.8"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="2282c381ee597a3ca6a6cf3836b5681049f7b81b"
OPENELEC_ARCH="RPi2.arm"
LIBREELEC_ARCH="RPi2.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="RPi"
LIBREELEC_DEVICE="RPi2"
```

**Comment by Paulchen-Panther** [comment]
HotFix is on the way.

**Comment by koelle25** [comment]
With Alpha 11 it is working again, thanks for the quick fix!
