### ISSUE TITLE
Home Assistant integration fault

### ISSUE THREAD

**Issue by karimidze** [hyperion-project/hyperion.ng#1351]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After upgrading to alpha.10.1, HA integration doesnt get right hyperion status, e.g.: 
 - LED instance state (on/off)
 - Current capture platform/effect
 - LED device state (on/off)

After first time of turning on hyperion switch in HA system actually works, but awterwards the switch becomes useless and hyperion integration card does not not provide right info about instance.

Also i have noticed that double click on hyperion integration entity (for example, switch.hyperion_component_all) works, but also not giving feedback.

Manual integration reload fixes everything until next time switch(es) use.

#### Steps to reproduce
1. From HA side turn on light.hyperion entity
2. Turn it off or change anything, like brightness or effect

#### What is expected?
hyperion will turn on and off

#### What is actually happening?
hyperion turn on and not turn off. switch will stay in previous state (on)

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.10.1) (Paulchen-Panther-d43e7e1/17e8c6b-1633253402)
- Build time:      Oct  3 2021 09:34:46
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10.1
- UI Lang:         en (BrowserLang: ru-RU)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/pi/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.4
- CPU Revision:   b03114
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.63-v7l+ (WS: 32))
- Root/Admin:     false
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

Home Assistant:
version | core-2021.9.5
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.8.7
os_name | Linux
os_version | 5.10.60-v7+
arch | armv7l
timezone | UTC

**Comment by karimidze** [comment]
Thanks for feedback! Upgraded to alpha.11, the problem remains

**Comment by mrdarrengriffin** [comment]
> Here is logs from HA side: ![chrome_DqIa5pRcN0](https://user-images.githubusercontent.com/9719210/136251400-b9932f15-3d04-4211-bb50-41efee1f3dbe.png)

Remove the integration and readd it. This happened to me and readding the integration fixed it

**Comment by karimidze** [comment]
> > Here is logs from HA side: ![chrome_DqIa5pRcN0](https://user-images.githubusercontent.com/9719210/136251400-b9932f15-3d04-4211-bb50-41efee1f3dbe.png)
> 
> Remove the integration and readd it. This happened to me and readding the integration fixed it

Yeah, already tried it, but with no success I'm afraid

**Comment by FirstS0ul** [comment]
I have the same problem. For me is it not fixed :-( Even no Log entrys. i updated everthing to the latest version...

**Comment by jimmyeao** [comment]
Installed the new pi image for hyperion today, and could not connect. Had to add the apt sources,` apt purge hyperion` then `apt install hyperion` before it would connect

**Comment by Pro-Control** [comment]
Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest


Hyperion.NG
Current version: 2.0.12 


After Restart 



Logger: hyperion.client
Source: runner.py:120
First occurred: 2:28:47 pm (1 occurrences)
Last logged: 2:28:47 pm

Failed Hyperion (192.168.5.15:19444) command: {'command': 'sysinfo', 'error': 'No Authorization', 'success': False, 'tan': 1}
