### ISSUE TITLE
Hyperion does not start automatically without a user login

### ISSUE THREAD

**Issue by aasimenator** [hyperion-project/hyperion.ng#1355]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I am running the latest version of Hyperion.NG on my Home Assistant server on Debian 10. When the computer is started or restarted Hyperion.NG does not start automatically until I log in on the PC (using RDP or physically). 

#### Steps to reproduce
I don't know i followed the installation guide

#### What is expected?
Auto start Hyperion.NG service so once the PC is restarted we can directly browse the url 

#### What is actually happening?
When the computer is started or restarted Hyperion.NG does not start automatically until I log in on the PC (using RDP or physically).

#### System

Hyperion Server: 
- Build:           (HEAD detached at b1a4e95c) (Paulchen-Panther-975f969a/b1a4e95c-1626550299)
- Build time:      Jul 17 2021 20:46:40
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      v4l2,framebuffer,x11,xcb,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Debian GNU/Linux 10 (buster)
- Architecture:   x86_64
- CPU Model:      Intel(R) Celeron(R) CPU G3900T @ 2.60GHz
- CPU Type:       94
- Kernel:         linux (4.19.0-17-amd64 (WS: 64))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38

**Comment by N1c093** [comment]
I think it's the same issue as #1350 
It sounds like, that you are not using a headless ubuntu installation. The service/autostart is only installed, when you run your system headless.

**Comment by aasimenator** [comment]
@N1c093  Is there any documentation on doing so? as there is only one command I found on how to install it.

Is there any way to upgrade the current installation into the headless mode or do I need to start fresh with it?

**Comment by Lord-Grey** [comment]
see #1478
