### ISSUE TITLE
Selected Hyperion instance isn't running

### ISSUE THREAD

**Issue by hode22** [hyperion-project/hyperion.ng#1357]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Alpha 11 fresh install , when i go on the web ui it says 'ERROR Selected Hyperion instance isn't running' and i can't press anything or do anything.

i was using this file to install it on a rpi3
Hyperion-2.0.0-alpha.11-Linux-armv7l.deb

#### Steps to reproduce
i reinstalled it 4 times with the exact same result . 

now i deleted this element '<div id="loading_overlay" class="overlay"></div>' from the page and i can navigate the menus but everything is empty .

#### What is actually happening?
![Screenshot (38)](https://user-images.githubusercontent.com/84182720/137401495-b776ed9b-955a-4046-bf1f-fd283f7e67ea.png)
![Screenshot (39)](https://user-images.githubusercontent.com/84182720/137401499-5d505a16-e6b3-4750-a903-9461bc06849a.png)
![Screenshot (40)](https://user-images.githubusercontent.com/84182720/137401500-3bd3be60-714b-4b52-b24c-921d74678add.png)
![Screenshot (41)](https://user-images.githubusercontent.com/84182720/137401504-2ff01afa-fbd9-4dec-b527-c47a38ed49c2.png)
![Screenshot (42)](https://user-images.githubusercontent.com/84182720/137401506-3b98a5df-845a-4379-8a7c-2f1f6bfc8ed2.png)

**Comment by Lord-Grey** [comment]
@hode22 Do not remove the element, but remove the cookies.
