### ISSUE TITLE
Hyperion 2.0.0.0-alpha11 not starting on Fedora35

### ISSUE THREAD

**Issue by evfool** [hyperion-project/hyperion.ng#1359]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Hyperion does not start on Fedora35.

#### Steps to reproduce

* Install Hyperion 2.0.0.0 alpha 11 release on Fedora 35.
* try to start service with systemctl start hyperion

#### What is expected?

Hyperion daemon starts

#### What is actually happening?

Service errors out.
Trying to start manually reveals a missing symbol error (
`sudo /usr/bin/hyperiond /etc/hyperion/hyperion.config.json`
                                  
`/usr/bin/hyperiond: symbol lookup error: /lib64/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language`)

Checking the net reveals that steam had a similar issue (https://github.com/ValveSoftware/steam-for-linux/issues/7935), which was reported with freetype-2.11 (installed on fedora35) but working correctly with freetype 2.10.4 (installed on fedora 34). Unfortunately a downgrade of freetype is not possible, as it is a system package, and would break gnome shell.

#### System
As Hyperion doesn't start, couldn't get to system info tab. Hyperion version is 2.0 alpha 11, Fedora version is 35.

**Comment by Paulchen-Panther** [comment]
Hey @evfool.
In the near future we will introduce a YUM repository. Until then you could do us a favor and test an actual [Hyperion RPM file](https://yum.hyperion-project.org/hyperion-2.0.12.x86_64.rpm) for us. Feedback is welcome.

Thank you very much.

**Comment by evfool** [comment]
@Paulchen-Panther downloaded the rpm, seems like it has a dependency on flatbuffers missing, after installing flatbuffers package I could install the rpm, and it does start correctly, so the alpha12 build you provided does fix this issue. 

Great to hear that a RPM repository is in the works.

**Comment by Paulchen-Panther** [comment]
Thank you for your test. What makes me a bit puzzled is that actually Flatbuffers should be installed with it. It is at least included in the dependency list.

https://github.com/Paulchen-Panther/hyperion.ng/blob/fedora/.github/workflows/yum.json#L9

**Comment by Paulchen-Panther** [comment]
May I ask how you installed the rpm file?

**Comment by evfool** [comment]
If it has a dep on flatbuffers, then probably it was my fault. I did use rpm -i DOWNLOADED.RPM to install.

**Comment by darksaboteur** [comment]
I'm having the same issue on Fedora 35. The above [link](https://yum.hyperion-project.org/hyperion-2.0.12.x86_64.rpm) isn't working. Would it be possible to get a copy of it please?

**Comment by Paulchen-Panther** [comment]
@darksaboteur 
The YUM repository will come with the next release. I ask you to be patient. Unfortunately we are understaffed (the number of devs). Or you compile the Hyperion yourself for Fedora. You can find the instructions here:
https://github.com/hyperion-project/hyperion.ng/blob/master/doc/development/CompileHowto.md

**Comment by Lord-Grey** [comment]
Would you mind checking with the new releases 2.0.16?
For Fedora, we now provide dedicated dnf installation files see [here](https://releases.hyperion-project.org/)
