### ISSUE TITLE
Need to manually start if importing backup

### ISSUE THREAD

**Issue by Xitee1** [hyperion-project/hyperion.ng#1368]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
After importing my backup (from version aplha.9), Hyperion won't restart automatically. If i go into SSH and type `service hyperion@root start`, it starts up and is working fine.

```
● hyperion@root.service - Hyperion ambient light systemd service  for user root
     Loaded: loaded (/etc/systemd/system/hyperion@.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2021-11-12 18:22:20 CET; 54s ago
       Docs: https://docs.hyperion-project.org
    Process: 1366 ExecStart=/usr/bin/hyperiond (code=exited, status=0/SUCCESS)
   Main PID: 1366 (code=exited, status=0/SUCCESS)
        CPU: 13.407s

Nov 12 18:22:20 ledband-bad r[1366]: Config Fix: [root].instCapture.systemGrabberDevice: Create property: systemGrabberDevice with value: NONE
Nov 12 18:22:20 ledband-bad r[1366]: Config Fix: [root].instCapture.v4lGrabberDevice: Create property: v4lGrabberDevice with value: NONE
Nov 12 18:22:20 ledband-bad hyperiond[1366]:       *******************************************
Nov 12 18:22:20 ledband-bad hyperiond[1366]:       *      hyperion will restart now          *
Nov 12 18:22:20 ledband-bad hyperiond[1366]:       *******************************************
Nov 12 18:22:20 ledband-bad systemd[1]: hyperion@root.service: Killing process 1490 (hyperiond) with signal SIGKILL.
Nov 12 18:22:20 ledband-bad systemd[1]: hyperion@root.service: Killing process 1490 (hyperiond) with signal SIGKILL.
Nov 12 18:22:20 ledband-bad systemd[1]: hyperion@root.service: Succeeded.
Nov 12 18:22:20 ledband-bad systemd[1]: hyperion@root.service: Unit process 1490 (hyperiond) remains running after unit stopped.
Nov 12 18:22:20 ledband-bad systemd[1]: hyperion@root.service: Consumed 13.407s CPU time.
```

#### What is expected?
Hyperion should automatically restart.

#### What is actually happening?
It stops but won't start up again.

#### System
Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.11) (GitHub-f42d5a7/2c79656-1633468939)
- Build time:      Oct  5 2021 21:26:27
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.11
- UI Lang:         auto (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /root/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63+ (WS: 32))
- Root/Admin:     true
- Qt Version:     5.15.2
- Python Version: 3.9.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

**Comment by Lord-Grey** [comment]
@Xitee1 Would you mind sharing the file that you tried to import, please?

**Comment by Xitee1** [comment]
> @Xitee1 Would you mind sharing the file that you tried to import, please?
Of course.
I had to put it in a ZIP because the filetype isn't supported by GitHub.
[Hyperion-2.0.0-alpha.9-Backup (LED Band Bad) 2021.11.05.zip](https://github.com/hyperion-project/hyperion.ng/files/7531748/Hyperion-2.0.0-alpha.9-Backup.LED.Band.Bad.2021.11.05.zip)
.

**Comment by fightforlife** [comment]
I have the same happening.   Backup from 14 beta reimport into 14 beta.
