### ISSUE TITLE
No Language Button.

### ISSUE THREAD

**Issue by DJ-Haegi** [hyperion-project/hyperion.ng#1370]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hello Guys, the Language Button on the following Site "https://docs.hyperion-project.org" is unusable on Smartphone when the phone is in Portrait Orientation.
In Landscape i can See the Language Button.

Tested on following device:
iPhone 11 Pro
iOS 15.1

Two Screenshots from me:
Portrait Orientation:
![image](https://user-images.githubusercontent.com/33071103/141678107-e9265961-bf92-49df-ba56-d0a0539114cb.png)

Landscape Orientation:
![image](https://user-images.githubusercontent.com/33071103/141678130-1651833b-d5f8-42fb-9e22-af3dcfcc0336.jpeg)

#### Steps to reproduce
Go on https://docs.hyperion-project.org with an Smartphone, then you can see it.

**Comment by Paulchen-Panther** [comment]
Hi @DJ-Haegi 

I would ask you to open an issue at https://github.com/hyperion-project/hyperion.docs in the future if you have problems with the doc.

About your issue. Have you ever clicked on the menu, there should be the language button.
Thank you very much.

**Comment by DJ-Haegi** [comment]
> Hi @DJ-Haegi 
> 
> 
> 
> I would ask you to open an issue at https://github.com/hyperion-project/hyperion.docs in the future if you have problems with the doc.
> 
> 
> 
> About your issue. Have you ever clicked on the menu, there should be the language button.
> 
> Thank you very much.

I'm so sorry, before i have not seen the Language Button in the Menu. Thx for the fast answer.

**Comment by Paulchen-Panther** [comment]
![Screenshot_2021-11-14-12-41-54-575_com android chrome](https://user-images.githubusercontent.com/16664240/141679344-63370a9b-08d2-46c7-9832-8edd023e30ba.jpg)
