### ISSUE TITLE
hyperion JSON server

### ISSUE THREAD

**Issue by vlascoff** [hyperion-project/hyperion.ng#1371]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion-remote commands do not work if the active instance isn't the first one in the "LED Hardware instance management" section
Note: the "First LED Hardware instance" cannot be disabled for some reason.

#### Steps to reproduce
create another hardware instance below the "First LED Hardware instance" and configure to use it 

#### What is expected?
a higher priority  request should be accepted. (ie. when it comes from the hyperion app with a priority of 50 compared to the screengrabber priority of 150)

#### What is actually happening?
the log shows the commands being successfully received but the actions are not performed.

#### System

Hyperion Server: 
- Build:           master (GitHub-69e325c0/3b1ca20b-1636305077)
- Build time:      Nov 14 2021 09:14:58
- Git Remote:      https://github.com/hyperion-project/hyperion.ng.git
- Version:         2.0.12
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/osmc/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Open Source Media Center
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (4.19.122-2-osmc (WS: 32))
- Root/Admin:     false
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

**Comment by Lord-Grey** [comment]
@vlascoff Currently hyperion-remote only works against the first instance.
To have it work against multiple instances requires enhancements.

Therefore, I tagged the item as a Feature Request.

**Comment by Lord-Grey** [comment]
@vlascoff Sorry, I rechecked again....

If you want to run hyperion-remote against an specific instance, make use of the "-I" option.

Sample:

`hyperion-remote -I "2nd Instance" -c blue`

**Comment by vlascoff** [comment]
thanks for the feedback, can this feature be extended to the hyperion app eventually? there is no way of editing how the command is sent

**Comment by Lord-Grey** [comment]
Now I get it. 
You are referring to the mobile app and not the command line utility hyperion-remote.
You might have mentioned it in the description, as well as the title is misleading....

The issue you are raising is related to the apps capabilities; hyperion can handle multiple instances via API.
As we do not maintain the app, please reach out to the app's provider.
