### ISSUE TITLE
Nvidia Jetson Nano support

### ISSUE THREAD

**Issue by quejoo** [hyperion-project/hyperion.ng#1373]
## Feature request

Please add support for nvidia jetson nano so we can use it with hyperion

#### What problem does this feature solve?

This will add support for armv8 devices including nvidia jetson nano

#### What does the proposed API look like?

no api changes is needed

#### How should this be implemented in your opinion?

kernel level

#### Are you willing to work on this yourself?

no, i dont.

**Comment by Paulchen-Panther** [comment]
You could try to install Ubuntu 18.04 and install Hyperion (nightly) via our [APT server](https://apt.hyperion-project.org/).
