### ISSUE TITLE
Hyperion 2.0.12 does not toggle LED state for Hyperion HomeAssistant integration

### ISSUE THREAD

**Issue by forkless** [hyperion-project/hyperion.ng#1380]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Using the appropriate toggle for my

#### Steps to reproduce
Install H2.0.12, click toggle on HomeAssistant UI (rolling back to Hyperion 2.0.0-alpha.9 functions as expected)

#### What is expected?
The LED instance should toggle between on/off depending on the state

#### What is actually happening?
[Errno 110] is thrown on the HA UI 
(Full error) https://gist.github.com/forkless/08d791ac43426b9fd952577e4f83dd62

#### System

Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 16:50:38
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      v4l2,qt,dx
- Config path:     C:/Users/forkless/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.19044 (WS: 64))
- Root/Admin:     true
- Qt Version:     5.15.0
- Python Version: 3.10.0
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

**Comment by forkless** [comment]
I may have experienced some caching issue, the communication between HA and Hyperion seems to function at the moment. Will do some more testing and close the issue if needed.

**Comment by Lord-Grey** [comment]
Suggest we close for now and you reopen when the issue still persist :)

**Comment by forkless** [comment]
Some more testing revealed that the LED instance does not always switch on (I haven't found the right condition yet)

What I have observed is that if the LED instance is enabled via the Hyperion front-end (with both the Screen and USB capture enabled the LED instance will switch off via HA, however when I toggle the HA button again, the LED instance will toggle the switch back to the ON state on the HA Hyperion front-end but the LED array remains dark. In addition to that at that point it also disables the Screen capture leaving only the USB capture enabled.
