### ISSUE TITLE
libcec4 Bullseye

### ISSUE THREAD

**Issue by patrickpflug** [hyperion-project/hyperion.ng#1387]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hello i use Raspberry Pi OS Bullseye.
In the Bullseye Repo is libcec4 not found. I can´t install hyperion. 

#### Steps to reproduce
Clean install the newest Raspberry Pi OS and hyperion.deb 

#### What is expected?
start hyperion. 
Is libcec4 necessary?

#### What is actually happening?

I found a dirty issue and is working for me. 
I added the Raspberry Pi Buster Repo in /etc/apt/sources.list 
(uncommend for activation)
> #deb http://archive.raspbian.org/raspbian buster main contrib non-free
#deb-src http://archive.raspbian.org/raspbian buster main contrib non-free

apt update and apt install libcec4 is working.

#### System

Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 17:01:59
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         de (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /root/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   2a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63-v7+ (WS: 32))
- Root/Admin:     true
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Please use our APT server to install Hyperion. Thanks a lot.

-> [apt.hyperion-project.org](https://apt.hyperion-project.org/)

**Comment by Sakashi92** [comment]
Ah thanks, this is new? Sorry for this Issue.

**Comment by Paulchen-Panther** [comment]
Not entirely new. Had already the fear that this information is too hidden. I fix that. Thanks again for the tip.

**Comment by Sakashi92** [comment]
No Problem. Thanks for your hard work!
