### ISSUE TITLE
Do not turn off WLED when closing the Hyperion Server OS

### ISSUE THREAD

**Issue by DivanX10** [hyperion-project/hyperion.ng#1389]
#### What problem does this feature solve?
Is it possible to add a function that will allow you not to turn off WLED when closing Hyperion Server OS on Windows? If there is such an option, how can I enable it? I use the WLED backlight on the back of the monitor. When I turn on WLED on the monitor, and then I start Hyperion Server OS, then image capture starts and the backlight starts to shimmer, everything is super here. And when I close Hyperion Server OS on Windows, the backlight turns off. I am currently using automation in Home Assistant, which monitors the sensor and as soon as Hyperion Server OS is unavailable, WLED will be enabled on the monitor.

#### What does the proposed API look like?
don't know

#### How should this be implemented in your opinion?
don't know

#### Are you willing to work on this yourself?
no

**Comment by Lord-Grey** [comment]
@DivanX10 You can configure Hyperion's WLED device that it restores the state before it took over the device.
Just enable "Restore lights' state"

![image](https://user-images.githubusercontent.com/48840279/144715607-5f5545d1-7a76-4b17-aa73-df8545f052dc.png)

Having it enabled
1. Hyperion saves the WLED state
2. Hyperion streams to the WLED device
3. Hyperion is stopped and it restores the state as saved in 1.

**Comment by DivanX10** [comment]
Thank you very much. Works 🥳
