### ISSUE TITLE
Lagg during gameplay

### ISSUE THREAD

**Issue by Nikpesu** [hyperion-project/hyperion.ng#1391]
- [x] I confirm that this is an issue rather than a question.

## Bug report
So when I'm playing League of Legends and Hyperion is active, my game stutters when moving a mouse. Didn't have that problem on windows 10, but when i switched to windows 11 it started doing that. 

#### Steps to reproduce
Have Hyperion active, have windows 11, open League and move mouse. 

#### What is expected?
The game running smoothly. Like it runs without Hyperion running. 

#### What is actually happening?
Game stutters when moving mouse.

#### System

Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 16:50:38
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      v4l2,qt,dx
- Config path:     C:/Users/nikpe/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.22509 (WS: 64))
- Root/Admin:     false
- Qt Version:     5.15.0
- Python Version: 3.10.0
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

**Comment by GhostgamesDHG** [comment]
I have this too, but I have only 20 less frames on my games(The impact is not too strong for me with a RTX 2060S). On my side the application has a high cpu usage.

I hope this will be fixed

**Comment by Lord-Grey** [comment]
The project currently do not have Windows 11 Developers nor hardware.
Happy, if someone picks this up.

**Comment by PS-O5** [comment]
I would love to help, if its ok with you.

**Comment by Lord-Grey** [comment]
> I would love to help, if its ok with you.

Of course, help is very much appreciated!

**Comment by PS-O5** [comment]
Thank you @Lord-Grey . @Nikpesu can you share some hardware specs like the mouse you are using, your pc specs Viz. USB port and driver details etc., if feasible?

**Comment by Chloe-ko** [comment]
This became inactive, but I'm actually having the same issue and would love to help to fix it. I also have another issue where the lights color changes are actually somewhat delayed, but I'm not sure if that's related.

Either way, I didn't check in detail yet, what kind of info can I bring forward to help debug this?
One thing I noticed is that rather than affecting my FPS, having hyperion running affects my minimum FPS/Frametime a lot, so while my FPS themselves don't drop, games feel notably laggy
