### ISSUE TITLE
Webserver returns wrong ContentType `application/x-extension-html` header

### ISSUE THREAD

**Issue by Jakeler** [hyperion-project/hyperion.ng#1395]
- [x] I confirm that this is an issue rather than a question.

## Bug report
On one system I could not open the Hyperion web UI, the browsers just show a download prompt for the html, instead of rendering it.
After digging a while I found out that it is related to the MIME type setup in the home dir, that changes what header the server returns.

A solution is in the next paragraph, main reason for this report is that others hopefully don't have to debug this as long. 
Still it might be better to hardcode the content type headers, so it does not depend on users MIME type configs.

#### Steps to reproduce
Create the file `~/.local/share/mime/packages/user-extension-html.xml` with:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
 <mime-type type="application/x-extension-html">
  <comment>html document</comment>
  <glob pattern="*.html"/>
 </mime-type>
</mime-info>
```
Then run `update-mime-database ~/.local/share/mime`, now after a `hyperiond` restart it shows the unexpected behavior.

To fix it again just delete the file and update/generate the mime db again. 
I don't know which app created this config file initially (in my case from 2019), but it is apparently not needed (and causing issues). There is not much on the internet, I found only [this report on a mail plugin](https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=3644), that was also solved by deleting the file. Nobody seems to actually know why it actually exists though.

#### What is expected?
Hyperion webserver returning proper `Content-Type: text/html`:
```console
$ http http://localhost:8090/ -h
HTTP/1.1 200 OK.
Access-Control-Allow-Origin: *
Content-Length: 15989
Content-Type: text/html
Date: Sa., 11 Dez. 2021 21:16:21 UTC
Server: Hyperion Webserver
```

#### What is actually happening?
Wrong `application/x-extension-html`:
```console
$ http http://localhost:8090/ -h
HTTP/1.1 200 OK.
Access-Control-Allow-Origin: *
Content-Length: 15989
Content-Type: application/x-extension-html
Date: Sa., 11 Dez. 2021 21:16:07 UTC
Server: Hyperion Webserver
```

#### System
Hyperion Server: 
- Build:           makepkg (GitHub-f8d78bb5/17582ac3-1638637220)
- Version:         2.0.12

Hyperion Server OS: 
- Distribution:   Arch Linux
- Architecture:   x86_64
- Root/Admin:     false
- Qt Version:     5.15.2
- Python Version: 3.9.9
- Browser:        Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by nighi** [comment]
I can confirm this issue and the solution (to simply delete the file) on manjaro (arch based).
```
Hyperion Server:
- Build:             master (GitHub-85a83872/2efc03b6-1642870083)
- Build time:        Jan 26 2022 16:39:44
- Git Remote:        /home/nighi/sData/.cache/yay/hyperion.ng-git/hyperion.ng
- Version:           2.0.13-beta.1
- UI Lang:           auto (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,forwarder,flatbuffer,protobuffer,borderdetection
- Config path:       /home/nighi/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Manjaro Linux
- Architecture:      x86_64
- CPU Model:       Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
- CPU Type:        94
- Kernel:            linux (5.10.93-1-MANJARO (WS: 64))
- Root/Admin:        false
- Qt Version:        6.2.2
- Python Version:    3.10.1
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
```

**Comment by Lord-Grey** [comment]
@Jakeler Hyperion only returns the mime.type from the request in the response. 
Given that different mime-types are exchanged while rendering the page, one cannot just hard-code as you suggested.
As this is a general OS and library problem, I suggest you stay with the workaround and I will close the issue for now.
