### ISSUE TITLE
hyperiond and crash status

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#14]
If we want to move forward to a webinterface and configuration in general we need to ensure that you are able to fix issue with the webinterface as much as possible.

If hyperion leads to a crash the websever is also gone and you just get a blank page (?)
Parts that could lead to this
- a corrupted .json or a not compatible one
- wrong configured led device (output f.e.)
- a enabled component that is not found at the system (v4l2)

we should find ways to prevent here a crash of hyperion that you are able to fix it. (As long that could done) and create better logoutput that describes better what happend now.

**Comment by redPanther** [comment]
when loading json fails, hyperion shouldn't abort, just don't start the whole hyperion stack - only webserver is started. This can be achieved with the new hyperiond structure ...

No component should hardly exit hyperion - just throw an exception that we can catch in main.cpp and react.

**Comment by brindosch** [comment]
Hm, a corrupted .json. It is for sure possible to fall back into a emergency state but this means the json checker needs to fix the confguration itself (which may be hard to code)? We could also add a ".json corrupt - copy and replace with json.default and restart"

**Comment by redPanther** [comment]
when checker fails, do not load given config, use default values instead. (or our default json file).
Then we can modify the config via web ui.

**Comment by brindosch** [comment]
yes, i think restore the .json.default is a easier solution. As we don't need no additional code to maintain or extend, just the checker.
But there is also one point i still not thought about:
What happend if you push later a new release and of course, the old configs don't contain the new array? So than we need to write this array.

**Comment by redPanther** [comment]
I will look which options still have no default and leads to abort. Giving all json  param a default, means we can start without a configfile

**Comment by brindosch** [comment]
//config migrator missing
