### ISSUE TITLE
Simple color temperature slider

### ISSUE THREAD

**Issue by kopidoo** [hyperion-project/hyperion.ng#1410]
## Feature request
I am having difficulties to tune the white balance and colors with the hyperion. Tweaking the white and other basic colors is time consuming. It is not impossible, but had many hours to find the acceptable results. 
In comparison the Prismatik 5.11.2.30 has simple sliders to tune, but works like magic, took only 10-15 minutes to find a good outcome. I have an adalight compatible device (Insanelight) with 2812B LED strip.
With Prismatik not only the pure white, but also other colours get the proper tuning even the darker shades.

#### What problem does this feature solve?
Simple global white balance and color gamma setup as an option in image processing section to make the initial tuning easier.
#### What does the proposed API look like?
Since I do not know how it works, I wwould like to leave it for a professional.
#### How should this be implemented in your opinion?
Making a simple white balance and color temperature slider from 1000K to 10000K same as in Prismatik 5.11.2.30
Also a joint gamma slider for the color channels beside the current ones.
#### Are you willing to work on this yourself?
I would like to, but I am newbie in programming. :(

**Comment by Lord-Grey** [comment]
You might want to test: https://github.com/Lord-Grey/hyperion.ng/tree/temperture
