### ISSUE TITLE
Pi cam works with Hyperion alpha 11 but not 2.0.12 version on rpi zero W

### ISSUE THREAD

**Issue by fightingforyou46** [hyperion-project/hyperion.ng#1413]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Pi cam works perfectly with Hyperion.ng alpha 11 version but not working with 2.0.12 version on rpi zero W

#### Steps to reproduce

I connected pi cam and test 2 version above, then alpha 11 work, but 2.0.12 not work, cannot choose resolution and fps of usb capture method.

<a href="https://ibb.co/T4LQXrw"><img src="https://i.ibb.co/R3yXn7g/Capture.jpg" alt="Capture" border="0"></a>

#### What is expected?
Hyperion.ng with newest verion can capture with pi cam on rpi zero W
#### What is actually happening?

see log please:

```
< ----- Current Log --------------------------- >
2022-01-11T16:48:03.532Z [ V4L2] (ERROR) Throws error: Only pixel formats RGB32, BGR24, YUYV, UYVY, NV12, I420 and MJPEG are supported
2022-01-11T16:48:03.538Z [ V4L2] (ERROR) Throws error nr: VIDIOC_STREAMON error code 22, Invalid argument
2022-01-11T16:48:03.705Z [ V4L2] (ERROR) Throws error nr: VIDIOC_DQBUF error code 16, Device or resource busy
2022-01-11T16:48:03.712Z [ V4L2] (ERROR) VIDIOC_STREAMOFF  error code  16, Device or resource busy
2022-01-11T16:48:26.560Z [ V4L2] (ERROR) Throws error: Only pixel formats RGB32, BGR24, YUYV, UYVY, NV12, I420 and MJPEG are supported
2022-01-11T16:48:26.566Z [ V4L2] (ERROR) Throws error nr: VIDIOC_STREAMON error code 22, Invalid argument
2022-01-11T16:48:26.703Z [ V4L2] (ERROR) Throws error nr: VIDIOC_DQBUF error code 16, Device or resource busy
2022-01-11T16:48:26.708Z [ V4L2] (ERROR) VIDIOC_STREAMOFF  error code  16, Device or resource busy
2022-01-11T16:54:29.212Z [ WEBSOCKET] (DEBUG) (WebSocketClient.cpp:215:sendClose()) Send close to ::ffff:192.168.31.234: 1000 
2022-01-11T16:54:35.918Z [ WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.31.234
2022-01-11T16:54:36.290Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:122:handleInstanceSwitch()) Client '::ffff:192.168.31.234' switch to Hyperion instance 0
2022-01-11T16:54:36.816Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1090:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.31.234
```

#### System

```
< ----- System information -------------------- >
Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: vi-VN)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/pi/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   19000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63+ (WS: 32))
- Root/Admin:     false
- Qt Version:     5.15.2
- Python Version: 3.9.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

< ----- Configured Instances ------------------ >
0: First LED Hardware instance Running: true

< ----- This instance's priorities ------------ >
240:           (V4L) Owner: undefined
priorities_autoselect: true

< ----- This instance components' status ------->
ALL - true
SMOOTHING - true
BLACKBORDER - true
FORWARDER - false
BOBLIGHTSERVER - false
GRABBER - false
V4L - true
LEDDEVICE - true

< ----- This instance's configuration --------- >
{"backgroundEffect":{"color":[255,138,0],"effect":"Warm mood blobs","enable":false,"type":"effect"},"blackborderdetector":{"blurRemoveCnt":1,"borderFrameCnt":50,"enable":true,"maxInconsistentCnt":10,"mode":"default","threshold":5,"unknownFrameCnt":600},"boblightServer":{"enable":false,"port":19333,"priority":128},"color":{"channelAdjustment":[{"backlightColored":false,"backlightThreshold":0,"blue":[0,0,255],"brightness":100,"brightnessCompensation":100,"cyan":[0,255,255],"gammaBlue":2.2,"gammaGreen":2.2,"gammaRed":2.2,"green":[0,255,0],"id":"default","leds":"*","magenta":[255,0,255],"red":[255,0,0],"white":[255,255,255],"yellow":[255,255,0]}],"imageToLedMappingType":"multicolor_mean"},"device":{"colorOrder":"rgb","hardwareLedCount":1,"latchTime":0,"output":"/dev/null","rewriteTime":0,"type":"file"},"effects":{"disable":[""],"paths":["$ROOT/custom-effects"]},"flatbufServer":{"enable":true,"port":19400,"timeout":5},"foregroundEffect":{"color":[0,0,255],"duration_ms":3000,"effect":"Rainbow swirl fast","enable":true,"type":"effect"},"forwarder":{"enable":false,"flat":[],"json":[]},"framegrabber":{"cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"device":"auto","enable":false,"fps":10,"height":45,"input":0,"pixelDecimation":8,"width":80},"general":{"configVersion":"2.0.12","name":"My Hyperion Config","previousVersion":"2.0.12","showOptHelp":true,"watchedVersionBranch":"Stable"},"grabberV4L2":{"available_devices":"unicam-image","blueSignalThreshold":0,"cecDetection":false,"cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"device":"/dev/video0","device_inputs":"0","enable":true,"encoding":"NO_CHANGE","flip":"NO_CHANGE","fps":0,"fpsSoftwareDecimation":0,"framerates":"","greenSignalThreshold":100,"hardware_brightness":0,"hardware_contrast":0,"hardware_hue":0,"hardware_saturation":0,"height":0,"input":0,"noSignalCounterThreshold":200,"redSignalThreshold":0,"resolutions":"","sDHOffsetMax":0.46,"sDHOffsetMin":0.4,"sDVOffsetMax":0.9,"sDVOffsetMin":0.1,"signalDetection":false,"sizeDecimation":8,"standard":"NONE","width":0},"instCapture":{"systemEnable":false,"systemGrabberDevice":"NONE","systemPriority":250,"v4lEnable":true,"v4lGrabberDevice":"NONE","v4lPriority":240},"jsonServer":{"port":19444},"ledConfig":{"classic":{"bottom":0,"edgegap":0,"glength":0,"gpos":0,"hdepth":8,"left":0,"overlap":0,"pblh":0,"pblv":100,"pbrh":100,"pbrv":100,"position":0,"ptlh":0,"ptlv":0,"ptrh":100,"ptrv":0,"reverse":false,"right":0,"top":1,"vdepth":5},"matrix":{"cabling":"snake","ledshoriz":1,"ledsvert":1,"start":"top-left"}},"leds":[{"hmax":1,"hmin":0,"vmax":0.08,"vmin":0}],"logger":{"level":"debug"},"network":{"apiAuth":true,"internetAccessAPI":false,"ipWhitelist":[],"localAdminAuth":true,"localApiAuth":false,"restirctedInternetAccessAPI":false},"protoServer":{"enable":true,"port":19445,"timeout":5},"smoothing":{"decay":1,"dithering":false,"enable":true,"interpolationRate":25,"outputRate":25,"time_ms":200,"type":"linear","updateDelay":0,"updateFrequency":25},"webConfig":{"crtPath":"","document_root":"","keyPassPhrase":"","keyPath":"","port":8090,"sslPort":8092}}
```

**Comment by Paulchen-Panther** [comment]
Switch to advanced Mode in the WebUi.

**Comment by fightingforyou46** [comment]
@Paulchen-Panther nothing change and the issue is still not solved
<a href="https://ibb.co/48qMC4T"><img src="https://i.ibb.co/gS2wQtT/Capture.jpg" alt="Capture" border="0"></a>

**Comment by Paulchen-Panther** [comment]
Device or resource busy.
What other software is running on the Pi that denies access?
Please post the output of the following commands:
dmesg
v4l2-ctl --list-devices
v4l2-ctl --all

**Comment by tihoangyeudau** [comment]
here you are

```
pi@HyperBian:~ $ v4l2-ctl --list-devices
v4l2-ctl --all
unicam (platform:20801000.csi):
        /dev/video0
        /dev/video1
        /dev/media2

bcm2835-codec-decode (platform:bcm2835-codec):
        /dev/video10
        /dev/video11
        /dev/video12
        /dev/video18
        /dev/media1

bcm2835-isp (platform:bcm2835-isp):
        /dev/video13
        /dev/video14
        /dev/video15
        /dev/video16
        /dev/media0

Driver Info:
        Driver name      : unicam
        Card type        : unicam
        Bus info         : platform:20801000.csi
        Driver version   : 5.10.63
        Capabilities     : 0x85a00001
                Video Capture
                Metadata Capture
                Read/Write
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x05200001
                Video Capture
                Read/Write
                Streaming
                Extended Pix Format
Media Driver Info:
        Driver name      : unicam
        Model            : unicam
        Serial           :
        Bus info         : platform:20801000.csi
        Media version    : 5.10.63
        Hardware revision: 0x00000000 (0)
        Driver version   : 5.10.63
Interface Info:
        ID               : 0x03000005
        Type             : V4L Video
Entity Info:
        ID               : 0x00000003 (3)
        Name             : unicam-image
        Function         : V4L2 I/O
        Flags         : default
        Pad 0x01000004   : 0: Sink
          Link 0x02000007: from remote pad 0x1000002 of entity 'ov5647 10-0036':                                                                                                              Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 0: ok)
Format Video Capture:
        Width/Height      : 1296/972
        Pixel Format      : 'pBAA' (10-bit Bayer BGBG/GRGR Packed)
        Field             : None
        Bytes per Line    : 1632
        Size Image        : 1586304
        Colorspace        : sRGB
        Transfer Function : Default (maps to sRGB)
        YCbCr/HSV Encoding: Default (maps to ITU-R 601)
        Quantization      : Default (maps to Full Range)
        Flags             :
Crop Capability Video Capture:
        Bounds      : Left 16, Top 6, Width 2592, Height 1944
        Default     : Left 16, Top 6, Width 2592, Height 1944
        Pixel Aspect: 1/1
Selection Video Capture: crop, Left 16, Top 6, Width 2592, Height 1944, Flags:
Selection Video Capture: crop_default, Left 16, Top 6, Width 2592, Height 1944,                                                                                                              Flags:
Selection Video Capture: crop_bounds, Left 16, Top 6, Width 2592, Height 1944, F                                                                                                             lags:
Selection Video Capture: native_size, Left 0, Top 0, Width 2624, Height 1956, Fl                                                                                                             ags:

User Controls

        white_balance_automatic 0x0098090c (bool)   : default=0 value=0
                       exposure 0x00980911 (int)    : min=4 max=1431 step=1 defa                                                                                                             ult=1000 value=1000
                 gain_automatic 0x00980912 (bool)   : default=0 value=0

Camera Controls

                  auto_exposure 0x009a0901 (menu)   : min=0 max=1 default=1 valu                                                                                                             e=1
                                0: Auto Mode
                                1: Manual Mode
             camera_orientation 0x009a0922 (menu)   : min=0 max=2 default=2 valu                                                                                                             e=2 flags=read-only
                                0: Front
                                1: Back
                                2: External
         camera_sensor_rotation 0x009a0923 (int)    : min=0 max=0 step=1 default                                                                                                             =0 value=0 flags=read-only

Image Source Controls

              vertical_blanking 0x009e0901 (int)    : min=24 max=31795 step=1 de                                                                                                             fault=463 value=463
            horizontal_blanking 0x009e0902 (int)    : min=600 max=600 step=1 def                                                                                                             ault=600 value=600 flags=read-only
                  analogue_gain 0x009e0903 (int)    : min=16 max=1023 step=1 def                                                                                                             ault=32 value=32

Image Processing Controls

                     pixel_rate 0x009f0902 (int64)  : min=81666700 max=81666700                                                                                                              step=1 default=81666700 value=81666700 flags=read-only
```

**Comment by fightingforyou46** [comment]
ok you can see it

```
v4l2-ctl --list-devices
unicam (platform:20801000.csi):
        /dev/video0
        /dev/video1
        /dev/media2

bcm2835-codec-decode (platform:bcm2835-codec):
        /dev/video10
        /dev/video11
        /dev/video12
        /dev/video18
        /dev/media1

bcm2835-isp (platform:bcm2835-isp):
        /dev/video13
        /dev/video14
        /dev/video15
        /dev/video16
        /dev/media0
```
```
v4l2-ctl --all
Driver Info:
        Driver name      : unicam
        Card type        : unicam
        Bus info         : platform:20801000.csi
        Driver version   : 5.10.63
        Capabilities     : 0x85a00001
                Video Capture
                Metadata Capture
                Read/Write
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x05200001
                Video Capture
                Read/Write
                Streaming
                Extended Pix Format
Media Driver Info:
        Driver name      : unicam
        Model            : unicam
        Serial           :
        Bus info         : platform:20801000.csi
        Media version    : 5.10.63
        Hardware revision: 0x00000000 (0)
        Driver version   : 5.10.63
Interface Info:
        ID               : 0x03000005
        Type             : V4L Video
Entity Info:
        ID               : 0x00000003 (3)
        Name             : unicam-image
        Function         : V4L2 I/O
        Flags         : default
        Pad 0x01000004   : 0: Sink
          Link 0x02000007: from remote pad 0x1000002 of entity 'ov5647 10-0036': Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 0: ok)
Format Video Capture:
        Width/Height      : 1296/972
        Pixel Format      : 'pBAA' (10-bit Bayer BGBG/GRGR Packed)
        Field             : None
        Bytes per Line    : 1632
        Size Image        : 1586304
        Colorspace        : sRGB
        Transfer Function : Default (maps to sRGB)
        YCbCr/HSV Encoding: Default (maps to ITU-R 601)
        Quantization      : Default (maps to Full Range)
        Flags             :
Crop Capability Video Capture:
        Bounds      : Left 16, Top 6, Width 2592, Height 1944
        Default     : Left 16, Top 6, Width 2592, Height 1944
        Pixel Aspect: 1/1
Selection Video Capture: crop, Left 16, Top 6, Width 2592, Height 1944, Flags:
Selection Video Capture: crop_default, Left 16, Top 6, Width 2592, Height 1944, Flags:
Selection Video Capture: crop_bounds, Left 16, Top 6, Width 2592, Height 1944, Flags:
Selection Video Capture: native_size, Left 0, Top 0, Width 2624, Height 1956, Flags:

User Controls

        white_balance_automatic 0x0098090c (bool)   : default=0 value=0
                       exposure 0x00980911 (int)    : min=4 max=1431 step=1 default=1000 value=1000
                 gain_automatic 0x00980912 (bool)   : default=0 value=0

Camera Controls

                  auto_exposure 0x009a0901 (menu)   : min=0 max=1 default=1 value=1
                                0: Auto Mode
                                1: Manual Mode
             camera_orientation 0x009a0922 (menu)   : min=0 max=2 default=2 value=2 flags=read-only
                                0: Front
                                1: Back
                                2: External
         camera_sensor_rotation 0x009a0923 (int)    : min=0 max=0 step=1 default=0 value=0 flags=read-only

Image Source Controls

              vertical_blanking 0x009e0901 (int)    : min=24 max=31795 step=1 default=463 value=463
            horizontal_blanking 0x009e0902 (int)    : min=600 max=600 step=1 default=600 value=600 flags=read-only
                  analogue_gain 0x009e0903 (int)    : min=16 max=1023 step=1 default=32 value=32

Image Processing Controls

                     pixel_rate 0x009f0902 (int64)  : min=81666700 max=81666700 step=1 default=81666700 value=81666700 flags=read-only
```

**Comment by Paulchen-Panther** [comment]
Thank you very much. Would you still be so kind as to output:
`v4l2-ctl -d /dev/video0 --list-formats-ext`
to post.

**Comment by fightingforyou46** [comment]
```
v4l2-ctl -d /dev/video0 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'BA81' (8-bit Bayer BGBG/GRGR)
                Size: Discrete 640x480
        [1]: 'pBAA' (10-bit Bayer BGBG/GRGR Packed)
                Size: Discrete 2592x1944
                Size: Discrete 1920x1080
                Size: Discrete 1296x972
                Size: Discrete 640x480
        [2]: 'BG10' (10-bit Bayer BGBG/GRGR)
                Size: Discrete 2592x1944
                Size: Discrete 1920x1080
                Size: Discrete 1296x972
                Size: Discrete 640x480
```

**Comment by Paulchen-Panther** [comment]
Which camera are we actually talking about?
Unfortunately, none of the devs owns a CSI Camera. Therefore it would be good to know which one it is.

**Comment by fightingforyou46** [comment]
i just use rpi pi camera rev 1.3. If I use hyperion.ng ver alpha11, it works well. But up to 2.0.12, I got this issue!

**Comment by Lord-Grey** [comment]
@fightingforyou46 It would be helpful, if you could share the details what Hyperion discovered as grabber-details:

Go to the "Capturing hardware" page
In your Brower you can right click and then select "Inspect".
Then move to the "Network" tab and select WS
Now refresh the page and select localhost
At the bottom of the list you should find a message "command: "inputsource-discover","
Right click and do a "copy object" and paste the result.

To help navigating the items, please find the following screenshot below:

![image](https://user-images.githubusercontent.com/48840279/149671729-f7385207-7b58-4747-8576-25ae07b3d922.png)

**Comment by fightingforyou46** [comment]
here you are

```
{command: "inputsource-discover", info: {sourceType: "video",…}, success: true, tan: 10}
command: "inputsource-discover"
info: {sourceType: "video",…}
sourceType: "video"
video_sources: [{default: {properties: {},…}, device: "/dev/video0", device_name: "unicam-image", properties: {},…}]
0: {default: {properties: {},…}, device: "/dev/video0", device_name: "unicam-image", properties: {},…}
default: {properties: {},…}
properties: {}
video_input: {formats: {format: "yuyv", resolution: {fps: 25, height: 480, width: 640}}, inputIdx: 0,…}
formats: {format: "yuyv", resolution: {fps: 25, height: 480, width: 640}}
format: "yuyv"
resolution: {fps: 25, height: 480, width: 640}
fps: 25
height: 480
width: 640
inputIdx: 0
standards: "PAL"
device: "/dev/video0"
device_name: "unicam-image"
properties: {}
type: "v4l2"
video_inputs: [{formats: [], inputIdx: 0, name: "Camera 0"}]
0: {formats: [], inputIdx: 0, name: "Camera 0"}
formats: []
inputIdx: 0
name: "Camera 0"
success: true
tan: 10
```

**Comment by Lord-Grey** [comment]
@fightingforyou46 Thank you. nevertheless it is hard to read, as you have not copied as asked for.

Maybe easier... Right click on the "{command: "inputsource-discover", info:" response Message and do a "Copy message"

![image](https://user-images.githubusercontent.com/48840279/149764634-55d04247-dd78-4264-9dab-202b683efcbe.png)

The output should look like this one

`{"command":"inputsource-discover","info":{"sourceType":"video","video_sources":[{"default":{"properties":{"brightness":128,"contrast":32,"saturation":28},"video_input":{"formats":{"format":"bgr24","resolution":{"fps":25,"height":480,"width":640}},"inputIdx":0,"standards":"PAL"}},"device":"Logitech Webcam Pro 9000","device_name":"Logitech Webcam Pro 9000","properties":{"brightness":{"current":100,"maxValue":255,"minValue":0,"step":1},"contrast":{"current":32,"maxValue":255,"minValue":0,"step":1},"saturation":{"current":28,"maxValue":255,"minValue":0,"step":1}},"type":"v4l2","video_inputs":[{"formats":[{"format":"bgr24","resolutions":[{"fps":[15,5,10,20,25,30],"height":120,"width":160},{"fps":[15,5,10,20,25,30],"height":100,"width":160},{"fps":[15,5,10,20,25,30],"height":90,"width":160},{"fps":[15,5,10,20,25,30],"height":144,"width":176},{"fps":[15,5,10,20,25,30],"height":240,"width":320},{"fps":[15,5,10,20,25,30],"height":200,"width":320},{"fps":[15,5,10,20,25,30],"height":180,"width":320},{"fps":[15,5,10,20,25,30],"height":288,"width":352},{"fps":[15,5,10,20,25,30],"height":400,"width":640},{"fps":[15,5,10,20,25,30],"height":360,"width":640},{"fps":[30,5,10,15,20,25],"height":480,"width":640},{"fps":[15,5,10,20,25,30],"height":480,"width":768},{"fps":[15,5,10,20,25,30],"height":600,"width":800},{"fps":[15,5,10,20,25,30],"height":500,"width":800},{"fps":[15,5,10,20,25,30],"height":450,"width":800},{"fps":[15,5,10],"height":480,"width":864},{"fps":[15,5,10,20,25,30],"height":720,"width":960},{"fps":[5,10],"height":1024,"width":1280},{"fps":[5,10,15,20,25],"height":800,"width":1280},{"fps":[5,10,15],"height":720,"width":1280},{"fps":[5],"height":1200,"width":1600},{"fps":[5,10],"height":1000,"width":1600},{"fps":[5,10],"height":900,"width":1600}]},{"format":"i420","resolutions":[{"fps":[15,5,10,20,25,30],"height":120,"width":160},{"fps":[15,5,10,20,25,30],"height":100,"width":160},{"fps":[15,5,10,20,25,30],"height":90,"width":160},{"fps":[15,5,10,20,25,30],"height":144,"width":176},{"fps":[15,5,10,20,25,30],"height":240,"width":320},{"fps":[15,5,10,20,25,30],"height":200,"width":320},{"fps":[15,5,10,20,25,30],"height":180,"width":320},{"fps":[15,5,10,20,25,30],"height":288,"width":352},{"fps":[15,5,10,20,25,30],"height":400,"width":640},{"fps":[15,5,10,20,25,30],"height":360,"width":640},{"fps":[30,5,10,15,20,25],"height":480,"width":640},{"fps":[15,5,10,20,25,30],"height":480,"width":768},{"fps":[15,5,10,20,25,30],"height":600,"width":800},{"fps":[15,5,10,20,25,30],"height":500,"width":800},{"fps":[15,5,10,20,25,30],"height":450,"width":800},{"fps":[15,5,10],"height":480,"width":864},{"fps":[15,5,10,20,25,30],"height":720,"width":960},{"fps":[5,10],"height":1024,"width":1280},{"fps":[5,10,15,20,25],"height":800,"width":1280},{"fps":[5,10,15],"height":720,"width":1280},{"fps":[5],"height":1200,"width":1600},{"fps":[5,10],"height":1000,"width":1600},{"fps":[5,10],"height":900,"width":1600}]}],"inputIdx":0,"name":""}]},{"default":{"properties":{"brightness":-11,"contrast":148,"hue":0,"saturation":180},"video_input":{"formats":{"format":"bgr24","resolution":{"fps":25,"height":480,"width":640}},"inputIdx":0,"standards":"PAL"}},"device":"USB Video","device_name":"USB Video","properties":{"brightness":{"current":-11,"maxValue":127,"minValue":-128,"step":1},"contrast":{"current":148,"maxValue":255,"minValue":0,"step":1},"hue":{"current":0,"maxValue":127,"minValue":-128,"step":1},"saturation":{"current":180,"maxValue":255,"minValue":0,"step":1}},"type":"v4l2","video_inputs":[{"formats":[{"format":"nv12","resolutions":[{"fps":[60,50,30,20,10],"height":480,"width":640},{"fps":[60,50,30,20,10],"height":480,"width":720},{"fps":[60,50,30,20,10],"height":576,"width":720},{"fps":[60,50,30,20,10],"height":600,"width":800},{"fps":[60,50,30,20,10],"height":768,"width":1024},{"fps":[60,50,30,20,10],"height":720,"width":1280},{"fps":[60,30,25,20,10],"height":960,"width":1280},{"fps":[60,30,25,20,10],"height":1024,"width":1280},{"fps":[60,30,25,20,10],"height":768,"width":1360},{"fps":[60,30,25,20,10],"height":1200,"width":1600},{"fps":[60,30,25,20,10],"height":1080,"width":1920}]},{"format":"mjpeg","resolutions":[{"fps":[60,50,30,20,10],"height":480,"width":640},{"fps":[60,50,30,20,10],"height":480,"width":720},{"fps":[60,50,30,20,10],"height":576,"width":720},{"fps":[60,50,30,20,10],"height":600,"width":800},{"fps":[60,50,30,20,10],"height":768,"width":1024},{"fps":[60,50,30,20,10],"height":720,"width":1280},{"fps":[60,30,25,20,10],"height":960,"width":1280},{"fps":[60,30,25,20,10],"height":1024,"width":1280},{"fps":[60,30,25,20,10],"height":768,"width":1360},{"fps":[60,30,25,20,10],"height":1200,"width":1600},{"fps":[60,30,25,20,10],"height":1080,"width":1920}]},{"format":"yuyv","resolutions":[{"fps":[30,20,10,5],"height":480,"width":640},{"fps":[30,20,10,5],"height":480,"width":720},{"fps":[25,20,10,5],"height":576,"width":720},{"fps":[20,10,5],"height":600,"width":800},{"fps":[10],"height":768,"width":1024},{"fps":[8],"height":960,"width":1280},{"fps":[8],"height":1024,"width":1280},{"fps":[10],"height":720,"width":1280},{"fps":[8],"height":768,"width":1360},{"fps":[5],"height":1200,"width":1600},{"fps":[5],"height":1080,"width":1920}]}],"inputIdx":0,"name":""}]},{"default":{"properties":{},"video_input":{"formats":{"format":"bgr24","resolution":{"fps":25,"height":480,"width":640}},"inputIdx":0,"standards":"PAL"}},"device":"XSplit VCam","device_name":"XSplit VCam","properties":{},"type":"v4l2","video_inputs":[{"formats":[{"format":"bgr24","resolutions":[{"fps":[30],"height":480,"width":640},{"fps":[30],"height":360,"width":640},{"fps":[30],"height":720,"width":1280}]}],"inputIdx":0,"name":""}]}]},"success":true,"tan":953}`

Thank you!

**Comment by fightingforyou46** [comment]
here you are

`{"command":"inputsource-discover","info":{"sourceType":"video","video_sources":[{"default":{"properties":{},"video_input":{"formats":{"format":"yuyv","resolution":{"fps":25,"height":480,"width":640}},"inputIdx":0,"standards":"PAL"}},"device":"/dev/video0","device_name":"unicam-image","properties":{},"type":"v4l2","video_inputs":[{"formats":[],"inputIdx":0,"name":"Camera 0"}]}]},"success":true,"tan":409}`

**Comment by Lord-Grey** [comment]
@fightingforyou46 Thank you!

**Comment by Paulchen-Panther** [comment]
Since we were able to buy a rev1.4 camera using donations, I can understand the problem.
The reason for this is not Hyperion and can be found since Raspberry Pi OS Bullseye on.
As per the[ blog post for the release of Raspberry Pi OS Bullseye](https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/), the default camera stack is now libcamera.

But there is a possibility to load the previous V4L2 driver:
- Edit /boot/config.txt, remove or comment the line "camera_auto_detect=1", and add "start_x=1" and "gpu_mem=128". Rebooting at this stage will reload the old V4L2 driver.

Now that we have the possibility to access the new Bayer formats, we do not exclude to support them in a future Hyperion version.

P.S.: For completeness, the default resolution of the V4L2 driver is 1024x768. If a different resolution is desired, this is possible via v4l2-ctl command.
Example: `v4l2-ctl -v width=640,height=480`
P.P.S: The resolution entry 0x0 is a known bug of Hyperion. 
P.P.P.S: I'll close here for now, if there are still any questions, just write in here.

**Comment by fightingforyou46** [comment]
@Paulchen-Panther Thank you so much! I will test it again

**Comment by fightingforyou46** [comment]
> * Edit /boot/config.txt, remove or comment the line "camera_auto_detect=1", and add "start_x=1" and "gpu_mem=128". Rebooting at this stage will reload the old V4L2 driver.

It works perfectly! Thank you so much again @Paulchen-Panther @Lord-Grey
