### ISSUE TITLE
Can't upgrade to 2.0.12 due to unmet dependencies in Hyperbian

### ISSUE THREAD

**Issue by TheGroundZero** [hyperion-project/hyperion.ng#1414]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I cannot upgrade to the latest version of Hyperion because the Raspbian image used by Hyperbian is missing some packages.

#### Steps to reproduce

```bash
pi@HyperBian:~ $ sudo apt install hyperion
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hyperion : Depends: libpython3.9 but it is not installable
            Depends: libcec6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

#### What is expected?

Update Hyperion to the latest version

#### What is actually happening?

Update fails due to unmet dependencies
- libpython3.9
- libcec6

#### System

```
Hyperion Server: 
- Build:           (HEAD detached at 2.0.0-alpha.10) (Paulchen-Panther-975f969/b1a4e95-1626550299)
- Build time:      Jul 17 2021 21:50:25
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.10
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63-v7+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
```

**Comment by Paulchen-Panther** [comment]
How did you install Hyperion?

**Comment by TheGroundZero** [comment]
> How did you install Hyperion?

It's been a while since I set this system up, but IIRC I used the Hyperbian image.

Today I decided to have a look at the web portal again an noticed there's an update available.
SSH'ed into the box and then noticed Raspbian doesn't have Python3.9 yet.

**Comment by Paulchen-Panther** [comment]
If all this doesn't work, you can always backup the config via sftp/ssh and then download the latest Hyperbian version. Restoring the config should not be a problem.

**Comment by TheGroundZero** [comment]
Updating to bullseye, will see if that suffices

**Comment by TheGroundZero** [comment]
Hyperion was upgraded, but there's an other issue appearing

> Jan 12 18:43:27 HyperBian hyperiond[834]: /usr/bin/hyperiond: error while loading shared libraries: libbcm_host.so.0: cannot open shared object file: No such file or directory
> Jan 12 18:43:27 HyperBian systemd[1]: hyperion@root.service: Main process exited, code=exited, status=127/n/a

**Comment by Paulchen-Panther** [comment]
sudo apt-get install libraspberrypi-bin

**Comment by TheGroundZero** [comment]
```bash
pi@HyperBian:~ $ sudo apt install libraspberrypi-bin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libraspberrypi-bin is already the newest version (1:1.20211201~buster-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Also tried `sudo apt install --reinstall libraspberrypi0 libraspberrypi-dev libraspberrypi-doc libraspberrypi-bin`
as per https://raspberrypi.stackexchange.com/questions/78719/missing-libbcm-host-so-when-running-chromium-browser

**Comment by TheGroundZero** [comment]
```bash
pi@HyperBian:~ $ sudo ldconfig -v
ldconfig: Can't stat /usr/local/lib/arm-linux-gnueabihf: No such file or directory
ldconfig: Path `/usr/lib/arm-linux-gnueabihf' given more than once
ldconfig: Path `/lib/arm-linux-gnueabihf' given more than once
ldconfig: Path `/usr/lib/arm-linux-gnueabihf' given more than once
ldconfig: Path `/usr/lib' given more than once
/opt/vc/lib:
        # ...
        libbcm_host.so -> libbcm_host.so
        # ...
```

**Comment by Paulchen-Panther** [comment]
Since something seems to have gone wrong with your OS upgrade, I suggest the easier way.
The best way is to save your config from the .hyperion directory (located in the HOME directory) and download the latest HyperBian. After the first start of HyperBian stop the service (sudo systemctl stop hyperion@pi). Restore the config and if needed run the updateHyperionUser script to run Hyperion as root service. After that everything should work.

**Comment by TheGroundZero** [comment]
hyperion.db ?

```
$ ls -R .hyperion
.hyperion:
custom-effects  db

.hyperion/custom-effects:

.hyperion/db:
hyperion.db
```

**Comment by Paulchen-Panther** [comment]
yes, hyperion.db

**Comment by TheGroundZero** [comment]
1. Unplugged SD-card from RPi and copied `/root/.hyperion/db/hyperion.db` and `wpa_supplicant.conf`
2. Flashed Hyperbian to the SD card
2. Restored `wpa_supplicant.conf` after flashing and put `ssh` in the boot partition.
3. Plugged SD-card in RPi and powered RPi
4. Stopped `hyperion@pi` service, restored `hyperion.db` to `~/.hyperion/db/hyperion.db`, restarted service.
5. Ran `sudo updateHyperionUser -u root`
6. Stopped `hyperion@root` service, copied `~/.hyperion/db/hyperion.db` to `/root/.hyperion/db/hyperion.db` and restarted service

Everything seems to work now :)
