### ISSUE TITLE
USB grabber wont grab anything after being idle

### ISSUE THREAD

**Issue by arifroni** [hyperion-project/hyperion.ng#1417]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After being idle for some time, when I start my TV, I see the default LED light color of WLED. when I try the see the live video from webgui, I see black screen with hyperion written on it. I need to restart hyperion to get it fixed.

This started after I updated to the newest version last week.

#### System

Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 17:01:51
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/pi/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.2
- CPU Revision:   c03112
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.17-v7l+ (WS: 32))
- Root/Admin:     false
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

**Comment by provalinf** [comment]
I also have this problem, but to make it work again, I uncheck and recheck no signal detection option.

**Comment by arifroni** [comment]
> I also have this problem, but to make it work again, I uncheck and recheck no signal detection option.

ok, where is this option?

**Comment by arifroni** [comment]
![16423438632611364679699342297946](https://user-images.githubusercontent.com/59896374/149664550-c1947537-1beb-4651-8552-c4992e916eeb.jpg)
while searching you 'no signal detection', i noticed i had 2 sources listed here, home assistant and system. i deleted home assistant and it seems to solve the problem 🤔. can you try and confirm?

**Comment by jjlink** [comment]
I also have this problem, but to make it work again, I uncheck and recheck no signal detection option.

**Comment by Lord-Grey** [comment]
Would you mind rechecking with the latest version, please?
If the problem persists, please share a Hyperion debug log from before and after the idle time.

**Comment by Lord-Grey** [comment]
Closing as no feedback provided so far.
