### ISSUE TITLE
Can't install on Orange Pi Zero

### ISSUE THREAD

**Issue by Vladimirov71** [hyperion-project/hyperion.ng#1418]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I try install Hyperion on Orange Pi Zero(Armbian) https://apt.hyperion-project.org/. hyperiond not start
hyperiond: error while loading shared libraries: libbcm_host.so.0: cannot open shared object file: No such file or directory

#### What is expected?
Not work

**Comment by Paulchen-Panther** [comment]
I am aware of the problem. I will hopefully have this fixed in the next release. Thanks again for the reminder.

**Comment by Paulchen-Panther** [comment]
@Vladimirov71 
As of tomorrow, the [Nightly builds](https://apt.hyperion-project.org#nightly) should be created and you are welcome to give feedback here again if it now runs under Armbian.
