### ISSUE TITLE
SPI failed to write. errno: 90, Message too long

### ISSUE THREAD

**Issue by jwieland** [hyperion-project/hyperion.ng#1426]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I have a using raspberry pi bullseye with the newest Hyperion release.    I have installed an LED SK6812 strip on the TV and have everything setup as instructed in the tutorial.  However the LED strip does not light up and I see this error repeating rapidly in the logs

SPI failed to write. errno: 90, Message too long

Full log -> https://pastebin.com/9vr2Gc3E

I searched google for a while and can't seem to figure out how to address.  Thank you for looking.

**Comment by Lord-Grey** [comment]
It seems that the default SPI Buffer needs to be increased for your set-up.
You need to update the rpi CONFIG.TXT file.

I suggest you ask in the [Hyperion forum](https://hyperion-project.org/forum/); I am sure the SMEs for such a set-up will put you on track.

**Comment by jwieland** [comment]
Solution here -> https://hyperion-project.org/forum/index.php?thread/12657-issues-with-hyperion-setup-spi-failed-to-write-errno-90-message-too-long/&postID=45090#post45090

Thank you
