### ISSUE TITLE
Drive 756 LEDs Apa102 via usb?

### ISSUE THREAD

**Issue by KrX3D** [hyperion-project/hyperion.ng#1432]
- [ ] I confirm that this is an issue rather than a question.

#### What is expected?
Hello,

i got 756 LEDs which i want to use on my TV. i got LibreElec installed on an VM on my Unraid Nas.

I tried it with an Mega2560 and adalight but i got an huge lag, probably because the baudrate is to slow? increasing it to 1000000 didnt work sind the leds where flickering.
i also tried an ESP32 with WLED, but in hyperion i can only select 490 LEDs and not sure how to change that, i tried Prismatik where i could select UDP with 1500 Leds which kinda works but not on my libreelec.

forwaring it to an raspberry zero seems also kida laggy, and i would like to not use an Pi is possible.

is there an other way to use my 756 LEDs via USB and not an network? or any other way i could try?

**Comment by Paulchen-Panther** [comment]
This section is for issues and not for questions that actually belong in the forum. Therefore I close here now and refer you to the forum.

--> [Hyperion Project Forum](https://hyperion-project.org/forum/) <--
