### ISSUE TITLE
Hyperion not starting

### ISSUE THREAD

**Issue by unformatted** [hyperion-project/hyperion.ng#1433]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After upgrading my RPi4 running arch ARM with kodi and hyperion.ng, hyperion does not start anymore. The previous upgrade was on 2021-12-26 and working. I start hyperion manually from kodi script mapped to my remote. From [https://aur.archlinux.org/cgit/aur.git/log/?h=hyperion.ng-git](url) it should have been rebuild for python 3.10 but hyperion-remote expects libpython3.9.so.1.0 library.

#### Steps to reproduce
systemctl --user start hyperion.service

#### What is expected?
Starting hyperion service

#### What is actually happening?
[user@PC19 ~]$ systemctl --user status hyperion.service
× hyperion.service - Hyperion ambient light systemd service
     Loaded: loaded (/home/user/.config/systemd/user/hyperion.service; bad; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-02-15 13:21:05 CET; 2s ago
       Docs: https://docs.hyperion-project.org
    Process: 492 ExecStart=/usr/bin/hyperiond (code=exited, status=127)
   Main PID: 492 (code=exited, status=127)
        CPU: 4ms
		
Feb 15 13:21:05 PC19 systemd[378]: hyperion.service: Scheduled restart job, restart counter is at 3.
Feb 15 13:21:05 PC19 systemd[378]: Stopped Hyperion ambient light systemd service.
Feb 15 13:21:05 PC19 systemd[378]: hyperion.service: Start request repeated too quickly.
Feb 15 13:21:05 PC19 systemd[378]: hyperion.service: Failed with result 'exit-code'.
Feb 15 13:21:05 PC19 systemd[378]: Failed to start Hyperion ambient light systemd service.

[user@PC19 ~]$ hyperion-remote -h
hyperion-remote: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

#### System

Web interface obviously not working, here's my system setup:
RPi4
Linux 5.15.21-3-rpi-ARCH #1 SMP PREEMPT Fri Feb 11 13:59:13 UTC 2022 aarch64 GNU/Linux
kodi-rpi 19.3-3
python 3.10.2-1
hyperion.ng-git 2.0.12.r8.c38ec602-1

**Comment by Lord-Grey** [comment]
@unformatted It looks like you make use of an Arch Linux package similar or equal to this one https://aur.archlinux.org/packages/hyperion.ng-git

I suggest you get in contact with the package maintainer, as we do not provide those packages nor have details on them.
