### ISSUE TITLE
Hdmi 2.1 (4k/VRR/120hz/hdr/Dolby Vision)

### ISSUE THREAD

**Issue by Ramalama2** [hyperion-project/hyperion.ng#1451]
Hey guys, im sorry, this is probably a bit offtopic 🤦
But im searching a way, to get ambilight  on my LG C1 with Xbox Series X.

The problem is, the connection between the tv and the Xbox uses the full 40gb bandwidth of hdmi 2.1. Means (4k 120fps in the 4:4:4 colorspace)

The only problem that i have is, that i can't find any hardware or even capture cards, that will work with the 40gbs bandwidth... Everything thats available caps out at 18gbs (4k 60fps)....

I mean, i know that if i can get something that converts the input signal down even to 640x480 would be enough, but it has still to understand the 40gbs input signal...

Does anyone know any solution at all how i can get in my scenario ambilight, aside from the stupid camera systems that have an incredible amount of delay?

I would be even okay with a camera, but one that doesn't introduce feeling wise a 2 second delay 🙈

Sorry for the offtopic.
Feel free to close the issue if it's wrong here 🙈

**Comment by Lord-Grey** [comment]
@Ramalama2 Suggest  you ask your question in the forum to get feedback by the Hyperion community.

https://hyperion-project.org/

**Comment by RaymondMouthaan** [comment]
@Ramalama2 https://www.hdfury.com, especially the DIVA works perfectly.
