### ISSUE TITLE
Unable to register for Hyperion / Hyperbian forums using my "disposable" email address

### ISSUE THREAD

**Issue by SteveDinn** [hyperion-project/hyperion.ng#1455]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hey. This isn't really a bug with Hyperion itself, but with the [Hyperion / Hyperbian forms registration page](https://hyperion-project.org/index.php?register/). It won't let me use my email address to sign up, giving me the error message "The usage of disposable email addresses is not allowed." It's really not disposable -- It's my email address! The one I'm trying to use is "steve (at) dinn (dot) ca". It's my name. It's not disposable :)

#### Steps to reproduce
I don't know the criteria that the forums use to determine what constitutes a "disposable" email address, but I haven't had this problem using my email anywhere else.

#### What is expected?
I expect to be able to sign up for the forums.

#### What is actually happening?
I get rejected on the registration page. https://hyperion-project.org/index.php?register/

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /root/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   HyperBian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63+ (WS: 32))
- Root/Admin:     true
- Qt Version:     5.15.2
- Python Version: 3.9.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36

**Comment by tpmodding** [comment]
Hey Steve,
can you try again? I whitelisted your domain, should hopefully work now.

**Comment by SteveDinn** [comment]
Worked like a charm! Thanks!
