### ISSUE TITLE
Bar in camera preview

### ISSUE THREAD

**Issue by phenix1990** [hyperion-project/hyperion.ng#1459]
- [x] I confirm that this is an issue rather than a question.

## Bug report
In my video preview I have a strange bar which also changes the color.

#### Steps to reproduce
The bar is always visible under the live video even if the camera is not connected or activated (then the bar is black)
I have this issue on buster as well on bullseye, both times i use v4L2 because i cant get libcamera work.
With older Version i didnt had this issue.
When i take a picture with raspistill i dont have such a bar in the picture.

#### What is expected?
No color changing bar in the live video.

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         de (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/pi/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model A Plus Rev 1.0
- CPU Revision:   9020e0
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.103-v7+ (WS: 32))
- Root/Admin:     false
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127

<img width="784" alt="2022-04-29_06h03_16" src="https://user-images.githubusercontent.com/43311321/165884435-b4428313-cdc2-4558-b6c8-08fd5b96ce24.png">

**Comment by Lord-Grey** [comment]
The Gray bar is the LED preview.
Currently 1 LED is configured in the LED layout handling the top area of the screen.
Disable "Zeige LEDs" and the bar will disappear...
