### ISSUE TITLE
Missing systemd service file

### ISSUE THREAD

**Issue by ghost** [hyperion-project/hyperion.ng#1478]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Installed release Hyperion-2.0.13-Linux-x86_64.deb via _dpkg -i_

#### What is expected?
want to start the service with issuing: _systemctl restart hyperion_

#### What is actually happening?
 /etc/systemd/system/hyperion.service wasn't created. So i had to create it manually 

#### System

Hyperion Server:
- Build:             (HEAD detached at 5dc696b8) (GitHub-dfd94381/5dc696b8-1653218333)
- Build time:        May 22 2022 11:40:56
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Ubuntu 22.04 LTS
- Architecture:      x86_64
- CPU Model:         Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
- CPU Type:          94
- Kernel:            linux (5.15.0-37-generic (WS: 64))
- Root/Admin:        true
- Qt Version:        5.7.1
- Python Version:    3.5.3
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0

**Comment by Lord-Grey** [comment]
You installed Hyperion on a system with user interface.
For UI systems a service is not installed by default, but desktop /menu entries are created.
A service is normally used for headless systems.

This is also outlined in the output during installation:
„You can start Hyperion from your menu now“

Nevertheless, you can install the service manually (on a systemd based system):

1. Copy Hyperion's service file
`sudo cp /usr/share/hyperion/service/hyperion.systemd /etc/systemd/system/hyperion@.service`

2. Establish the service for the current user (if it should be a different user, use the -u option)
`sudo /usr/share/hyperion/scripts/updateHyperionUser.sh`

3. Check that the service is running for your current user (or replace ${USER} with the username given with the -u option before)
`systemctl status hyperion@${USER}`
