### ISSUE TITLE
HyperBian SSH not working

### ISSUE THREAD

**Issue by LeLunZ** [hyperion-project/hyperion.ng#1479]
- [x] I confirm that this is an issue rather than a question.

## Bug report

SSH doesn't work after a clean install of HyperBian.

#### Steps to reproduce

- install HyperBian
- Add ssh file to boot
- ssh pi@host
- enter password 'raspberry'

#### What is expected?

Login should work

#### What is actually happening?

```
Please note that SSH may not work until a valid user has been set up.

See http://rptl.io/newuser for details.
pi@192.168.0.53's password:
```

after entering password:
```
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
```

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.13) (GitHub-dfd9438/5dc696b-1653218333)
- Build time:        May 22 2022 12:55:01
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         expert
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/pi/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      HyperBian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 3 (v7l)
- CPU Type:          Raspberry Pi 4 Model B Rev 1.5
- CPU Revision:      c03115
- CPU Hardware:      BCM2711
- Kernel:            linux (5.15.32-v7l+ (WS: 32))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15

**Comment by Lord-Grey** [comment]
Did you consider that the keyboard layout is English by default?
That often creates problems that the password is invalid as the ‚y‘ character is at a different Position (e.g. on a German keyboard, you would need to type ‚z‘)

**Comment by LeLunZ** [comment]
Yes sure. I also tried with copying the password.

the ssh file is removed after looking at the SD card again. Normal?

**Comment by tpmodding** [comment]
Just create a "userconf"-file on the boot partition with containing this line:
"pi:$6$ZGEEFHP4I1jNqzvS$2pKzPMEVvX85M3gq2q6P5sLroqDu1cfpBCObiRmC.rzQuT.KZ.llYh3/ZBii98DUHLGpYC9bU7cCwZQe7bCiD1"

and the "ssh"-file too

then it should work

**Comment by LeLunZ** [comment]
Yesss that worked :) thx

**Comment by Wickueler** [comment]
https://github.com/hyperion-project/HyperBian/pull/8

**Comment by daviddoji** [comment]
It didn't work for me.
Adding a "userconf" file with the content @LeLunZ said above and an empty "ssh" file, when I try to ssh using the "pi" user and "raspberry" as password, I got permission denied.

**Comment by tpmodding** [comment]
did you try the method from my last post?

**Comment by daviddoji** [comment]
Yes, exactly what you posted and still can't ssh :(

**Comment by tpmodding** [comment]
which error do you get?

**Comment by daviddoji** [comment]
After three attempts to log in, I get the "Permission denied" error and I was kicked out of the ssh session :shrug:

**Comment by beardedfool** [comment]
can confirm tp modding's fix works on a new install.

For the next guy, would it be possible to link to this issue from https://docs.hyperion-project.org/en/user/HyperBian.html#hyperbian-ssh please

**Comment by Lord-Grey** [comment]
A new HyperBian image was just released with [default user and password](https://docs.hyperion-project.org/en/user/HyperBian.html#ssh-login) changed to align with Raspberry Pi OS security measures.
Furthermore, the respective [HyperBian installation documentation](https://docs.hyperion-project.org/en/user/HyperBian.html#hyperbian) was updated, too.
