### ISSUE TITLE
Runtime error if color number is out of range (JSONConnection)

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#148]
Log:
```
[HYPERIOND JSONSERVER] <DEBUG> <JsonServer.cpp:64:closedConnection()> Connection closed
terminate called after throwing an instance of 'std::runtime_error'
  what():  unsigned integer out of signed int range
Aborted
```

Command:
`{"command":"color","priority":1,"color":[142333333333333,331,1],"duration":3}`

**Comment by redPanther** [comment]
.. then put no big numbers in it ;-) 
we are in process to change our json parser. We will fix this issue in that process.

**Comment by b1rdhous3** [comment]
But I am always curious what happens if I do ;)
Okay, sounds good.

**Comment by brindosch** [comment]
Looks like no one before tried to feed Hyperion with "out of scope" values :)
No problem, it is good to catch and note everything. In best case now :)

**Comment by redPanther** [comment]
I'm not happy with those plenty uncaught exceptions - thats another todo. But it can be more worse - we have exceptions in code parts where exceptions not allowed, e.g. in v4l grabber. I'm happy that we rework so much, but it feels everyday we find new stuff that can be made better ....

**Comment by redPanther** [comment]
... for exactly that tests we need automated unittests, that check all corner cases of the code ...

>  , but it feels everyday we find new stuff that can be made better ....
