### ISSUE TITLE
no manual settings for forwarding since Hyperion-2.0.13/mDNS integration

### ISSUE THREAD

**Issue by 000MDK** [hyperion-project/hyperion.ng#1483]
- [x] I confirm that this is an issue rather than a question.

## Bug report

forwarding settings for mDNS replace manual IP entries

#### Steps to reproduce

install Hyperion-2.0.13
goto settings/network
enable forwarding
try to setup IPs manually without finding anything with mDNS first

#### What is expected?

that users can still do manual IP setup - auto-discovery should just be a new addition to the old settings from .12

#### What is actually happening?

the new auto-discovery for mDNS replaced the old settings completely, so users cannot setup targets manually - at least not without finding one with mDNS first.

#### System
Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 16:50:38
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         de (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      v4l2,qt,dx
- Config path:     C:/Users/user/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.22000 (WS: 64))
- Root/Admin:     true
- Qt Version:     5.15.0
- Python Version: 3.10.0
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
The mDNS discovery way ensures that the configuration with the remote configuration is correct and working.
On top , in case the port of the remote Hyperion is changed, the forwarding Hyperion will adapt to the new port as the handshake is via the exposed service capabilities.

Would you mind elaborating why a manual configuration is required with the risk of inconsistent configurations?

Note: as a workaround, you could export the configuration and replace the remote Hyperion's mDNS service name via an IP.

**Comment by Lord-Grey** [comment]
Closing as no feedback was provided
