### ISSUE TITLE
LEDs stopped changing colors to Picture LED output not showing picture of HDMI input

### ISSUE THREAD

**Issue by bsmith76s** [hyperion-project/hyperion.ng#1487]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
I have been using Hyperion for 2 years now without issue. Came home today and LEDs are not changing. I checked the Live View on LED output and picture is not showing just vertical bars. TV is displaying picture so I know signal is good. I have reinstalled Hyperion with no success. USB Grabber is displayed when running command
 v4l2-ctl --list-devices
USB Video: USB Video (usb-0000:01:00.0-1.4):
	/dev/video0
	/dev/video1
	/dev/media3

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.13) (GitHub-dfd9438/5dc696b-1653218333)
- Build time:        May 22 2022 12:56:16
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         expert
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/pi/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Debian GNU/Linux 11 (bullseye)
- Architecture:      arm64
- CPU Type:          Raspberry Pi 4 Model B Rev 1.2
- CPU Revision:      c03112
- CPU Hardware:      BCM2835
- Kernel:            linux (5.15.32-v8+ (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0

**Comment by Lord-Grey** [comment]
@bsmith76s It looks like that it is a problem with your grabber.
I would suggest you check with the Hyperion community via the forum (https://hyperion-project.org/forum).
It might be worth adding a screenshot showing the "just vertical bars" picure.
