### ISSUE TITLE
Hyperion output to wrong WLED controller

### ISSUE THREAD

**Issue by theTobster500** [hyperion-project/hyperion.ng#1497]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
unsure, happened once when starting hyperion, haven't been able to reproduce

#### What is expected?
hyperion outputs to my chosen WLED controller

#### What is actually happening?
output is set to WLED controller A, but is actually outputting to WLED controller B. Test LED runs on the proper controller and LED count is also recognized correctly, however output is still on the wrong controller. Restarted and switched outputs multiple times, ended up working eventually (not sure what solved it)

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.13) (GitHub-dfd9438/5dc696b-1653218333)
- Build time:        May 22 2022 13:22:26
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/homebridge/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Pop!_OS 21.04
- Architecture:      x86_64
- CPU Model:         AMD Turion(tm) 64 X2 Mobile Technology TL-58
- CPU Type:          104
- Kernel:            linux (5.13.0-7614-generic (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.5
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

**Comment by Lord-Grey** [comment]
Would you mind sharing your configuration and logs? 
System->logs, Copy to Clipboard

**Comment by theTobster500** [comment]
Hyperion System Summary Report (My Hyperion Config), Reported instance: unknown

< ----- System information -------------------- >
Hyperion Server:
- Build:             (HEAD detached at 2.0.13) (GitHub-dfd9438/5dc696b-1653218333)
- Build time:        May 22 2022 13:22:26
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/homebridge/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Pop!_OS 21.04
- Architecture:      x86_64
- CPU Model:         AMD Turion(tm) 64 X2 Mobile Technology TL-58
- CPU Type:          104
- Kernel:            linux (5.13.0-7614-generic (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.5
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

< ----- Configured Instances ------------------ >
0: First LED Hardware instance Running: true

< ----- This instance's priorities ------------ >
110:  VISIBLE! (FLATBUFSERVER) Owner: undefined
240:           (V4L) Owner: undefined
250:           (GRABBER) Owner: undefined
priorities_autoselect: true

< ----- This instance components' status ------->
ALL - true
SMOOTHING - false
BLACKBORDER - true
FORWARDER - false
BOBLIGHTSERVER - false
GRABBER - true
V4L - true
LEDDEVICE - true

< ----- This instance's configuration --------- >
{"backgroundEffect":{"color":[0,255,255],"effect":"Warm mood blobs","enable":false,"type":"color"},"blackborderdetector":{"blurRemoveCnt":1,"borderFrameCnt":50,"enable":true,"maxInconsistentCnt":10,"mode":"default","threshold":5,"unknownFrameCnt":600},"boblightServer":{"enable":false,"port":19333,"priority":128},"color":{"channelAdjustment":[{"backlightColored":false,"backlightThreshold":0,"blue":[5,0,255],"brightness":100,"brightnessCompensation":0,"cyan":[50,255,255],"gammaBlue":2.2,"gammaGreen":2.5,"gammaRed":2.3,"green":[60,255,0],"id":"Color Corrected","leds":"*","magenta":[255,0,200],"red":[255,5,0],"white":[255,225,245],"yellow":[255,200,0]}],"imageToLedMappingType":"multicolor_mean"},"device":{"autoStart":true,"brightness":255,"colorOrder":"rgb","enableAttempts":12,"enableAttemptsInterval":15,"hardwareLedCount":100,"host":"wled-ambilight._wled._tcp.local","hostList":"wled-ambilight._wled._tcp.local","latchTime":0,"overwriteBrightness":true,"overwriteSync":true,"restoreOriginalState":true,"streamProtocol":"DDP","type":"wled"},"effects":{"disable":[""],"paths":["$ROOT/custom-effects"]},"flatbufServer":{"enable":true,"port":19400,"timeout":5},"foregroundEffect":{"color":[0,0,255],"duration_ms":3000,"effect":"Blue KR","enable":true,"type":"effect"},"forwarder":{"enable":false},"framegrabber":{"available_devices":"DX","cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"device":"dx","device_inputs":"0","enable":false,"fps":40,"framerates":"40","height":1080,"input":0,"pixelDecimation":7,"resolutions":"0","width":1920},"general":{"configVersion":"2.0.13","name":"My Hyperion Config","previousVersion":"2.0.13","showOptHelp":true,"watchedVersionBranch":"Stable"},"grabberV4L2":{"available_devices":"HD Webcam C615","blueSignalThreshold":0,"cecDetection":false,"cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"device":"HD Webcam C615","device_inputs":"0","enable":false,"encoding":"yuyv","flip":"NO_CHANGE","fps":30,"fpsSoftwareDecimation":0,"framerates":"30","greenSignalThreshold":100,"hardware_brightness":128,"hardware_contrast":32,"hardware_hue":0,"hardware_saturation":32,"height":480,"input":0,"noSignalCounterThreshold":200,"redSignalThreshold":0,"resolutions":"6","sDHOffsetMax":0.46,"sDHOffsetMin":0.4,"sDVOffsetMax":0.9,"sDVOffsetMin":0.1,"signalDetection":false,"sizeDecimation":8,"standard":"NONE","width":640},"instCapture":{"systemEnable":true,"systemGrabberDevice":"QT","systemPriority":250,"v4lEnable":true,"v4lGrabberDevice":"HD Webcam C615","v4lPriority":240},"jsonServer":{"port":19444},"ledConfig":{"classic":{"bottom":31,"edgegap":0,"glength":0,"gpos":0,"hdepth":7,"left":19,"overlap":1,"pblh":0,"pblv":100,"pbrh":100,"pbrv":100,"position":71,"ptlh":0,"ptlv":0,"ptrh":100,"ptrv":0,"reverse":true,"right":19,"top":31,"vdepth":5},"ledBlacklist":[],"matrix":{"cabling":"snake","ledshoriz":1,"ledsvert":1,"start":"top-left"}},"leds":[{"hmax":0.3648,"hmin":0.3126,"vmax":1,"vmin":0.93},{"hmax":0.3971,"hmin":0.3448,"vmax":1,"vmin":0.93},{"hmax":0.4294,"hmin":0.3771,"vmax":1,"vmin":0.93},{"hmax":0.4616,"hmin":0.4094,"vmax":1,"vmin":0.93},{"hmax":0.4939,"hmin":0.4416,"vmax":1,"vmin":0.93},{"hmax":0.5261,"hmin":0.4739,"vmax":1,"vmin":0.93},{"hmax":0.5584,"hmin":0.5061,"vmax":1,"vmin":0.93},{"hmax":0.5906,"hmin":0.5384,"vmax":1,"vmin":0.93},{"hmax":0.6229,"hmin":0.5706,"vmax":1,"vmin":0.93},{"hmax":0.6552,"hmin":0.6029,"vmax":1,"vmin":0.93},{"hmax":0.6874,"hmin":0.6352,"vmax":1,"vmin":0.93},{"hmax":0.7197,"hmin":0.6674,"vmax":1,"vmin":0.93},{"hmax":0.7519,"hmin":0.6997,"vmax":1,"vmin":0.93},{"hmax":0.7842,"hmin":0.7319,"vmax":1,"vmin":0.93},{"hmax":0.8165,"hmin":0.7642,"vmax":1,"vmin":0.93},{"hmax":0.8487,"hmin":0.7965,"vmax":1,"vmin":0.93},{"hmax":0.881,"hmin":0.8287,"vmax":1,"vmin":0.93},{"hmax":0.9132,"hmin":0.861,"vmax":1,"vmin":0.93},{"hmax":0.9455,"hmin":0.8932,"vmax":1,"vmin":0.93},{"hmax":0.9777,"hmin":0.9255,"vmax":1,"vmin":0.93},{"hmax":1,"hmin":0.9577,"vmax":1,"vmin":0.93},{"hmax":1,"hmin":0.95,"vmax":1,"vmin":0.9374},{"hmax":1,"hmin":0.95,"vmax":0.9574,"vmin":0.8847},{"hmax":1,"hmin":0.95,"vmax":0.9047,"vmin":0.8321},{"hmax":1,"hmin":0.95,"vmax":0.8521,"vmin":0.7795},{"hmax":1,"hmin":0.95,"vmax":0.7995,"vmin":0.7268},{"hmax":1,"hmin":0.95,"vmax":0.7468,"vmin":0.6742},{"hmax":1,"hmin":0.95,"vmax":0.6942,"vmin":0.6216},{"hmax":1,"hmin":0.95,"vmax":0.6416,"vmin":0.5689},{"hmax":1,"hmin":0.95,"vmax":0.5889,"vmin":0.5163},{"hmax":1,"hmin":0.95,"vmax":0.5363,"vmin":0.4637},{"hmax":1,"hmin":0.95,"vmax":0.4837,"vmin":0.4111},{"hmax":1,"hmin":0.95,"vmax":0.4311,"vmin":0.3584},{"hmax":1,"hmin":0.95,"vmax":0.3784,"vmin":0.3058},{"hmax":1,"hmin":0.95,"vmax":0.3258,"vmin":0.2532},{"hmax":1,"hmin":0.95,"vmax":0.2732,"vmin":0.2005},{"hmax":1,"hmin":0.95,"vmax":0.2205,"vmin":0.1479},{"hmax":1,"hmin":0.95,"vmax":0.1679,"vmin":0.0953},{"hmax":1,"hmin":0.95,"vmax":0.1153,"vmin":0.0426},{"hmax":1,"hmin":0.95,"vmax":0.0626,"vmin":0},{"hmax":1,"hmin":0.9577,"vmax":0.07,"vmin":0},{"hmax":0.9777,"hmin":0.9255,"vmax":0.07,"vmin":0},{"hmax":0.9455,"hmin":0.8932,"vmax":0.07,"vmin":0},{"hmax":0.9132,"hmin":0.861,"vmax":0.07,"vmin":0},{"hmax":0.881,"hmin":0.8287,"vmax":0.07,"vmin":0},{"hmax":0.8487,"hmin":0.7965,"vmax":0.07,"vmin":0},{"hmax":0.8165,"hmin":0.7642,"vmax":0.07,"vmin":0},{"hmax":0.7842,"hmin":0.7319,"vmax":0.07,"vmin":0},{"hmax":0.7519,"hmin":0.6997,"vmax":0.07,"vmin":0},{"hmax":0.7197,"hmin":0.6674,"vmax":0.07,"vmin":0},{"hmax":0.6874,"hmin":0.6352,"vmax":0.07,"vmin":0},{"hmax":0.6552,"hmin":0.6029,"vmax":0.07,"vmin":0},{"hmax":0.6229,"hmin":0.5706,"vmax":0.07,"vmin":0},{"hmax":0.5906,"hmin":0.5384,"vmax":0.07,"vmin":0},{"hmax":0.5584,"hmin":0.5061,"vmax":0.07,"vmin":0},{"hmax":0.5261,"hmin":0.4739,"vmax":0.07,"vmin":0},{"hmax":0.4939,"hmin":0.4416,"vmax":0.07,"vmin":0},{"hmax":0.4616,"hmin":0.4094,"vmax":0.07,"vmin":0},{"hmax":0.4294,"hmin":0.3771,"vmax":0.07,"vmin":0},{"hmax":0.3971,"hmin":0.3448,"vmax":0.07,"vmin":0},{"hmax":0.3648,"hmin":0.3126,"vmax":0.07,"vmin":0},{"hmax":0.3326,"hmin":0.2803,"vmax":0.07,"vmin":0},{"hmax":0.3003,"hmin":0.2481,"vmax":0.07,"vmin":0},{"hmax":0.2681,"hmin":0.2158,"vmax":0.07,"vmin":0},{"hmax":0.2358,"hmin":0.1835,"vmax":0.07,"vmin":0},{"hmax":0.2035,"hmin":0.1513,"vmax":0.07,"vmin":0},{"hmax":0.1713,"hmin":0.119,"vmax":0.07,"vmin":0},{"hmax":0.139,"hmin":0.0868,"vmax":0.07,"vmin":0},{"hmax":0.1068,"hmin":0.0545,"vmax":0.07,"vmin":0},{"hmax":0.0745,"hmin":0.0223,"vmax":0.07,"vmin":0},{"hmax":0.0423,"hmin":0,"vmax":0.07,"vmin":0},{"hmax":0.05,"hmin":0,"vmax":0.0626,"vmin":0},{"hmax":0.05,"hmin":0,"vmax":0.1153,"vmin":0.0426},{"hmax":0.05,"hmin":0,"vmax":0.1679,"vmin":0.0953},{"hmax":0.05,"hmin":0,"vmax":0.2205,"vmin":0.1479},{"hmax":0.05,"hmin":0,"vmax":0.2732,"vmin":0.2005},{"hmax":0.05,"hmin":0,"vmax":0.3258,"vmin":0.2532},{"hmax":0.05,"hmin":0,"vmax":0.3784,"vmin":0.3058},{"hmax":0.05,"hmin":0,"vmax":0.4311,"vmin":0.3584},{"hmax":0.05,"hmin":0,"vmax":0.4837,"vmin":0.4111},{"hmax":0.05,"hmin":0,"vmax":0.5363,"vmin":0.4637},{"hmax":0.05,"hmin":0,"vmax":0.5889,"vmin":0.5163},{"hmax":0.05,"hmin":0,"vmax":0.6416,"vmin":0.5689},{"hmax":0.05,"hmin":0,"vmax":0.6942,"vmin":0.6216},{"hmax":0.05,"hmin":0,"vmax":0.7468,"vmin":0.6742},{"hmax":0.05,"hmin":0,"vmax":0.7995,"vmin":0.7268},{"hmax":0.05,"hmin":0,"vmax":0.8521,"vmin":0.7795},{"hmax":0.05,"hmin":0,"vmax":0.9047,"vmin":0.8321},{"hmax":0.05,"hmin":0,"vmax":0.9574,"vmin":0.8847},{"hmax":0.05,"hmin":0,"vmax":1,"vmin":0.9374},{"hmax":0.0423,"hmin":0,"vmax":1,"vmin":0.93},{"hmax":0.0745,"hmin":0.0223,"vmax":1,"vmin":0.93},{"hmax":0.1068,"hmin":0.0545,"vmax":1,"vmin":0.93},{"hmax":0.139,"hmin":0.0868,"vmax":1,"vmin":0.93},{"hmax":0.1713,"hmin":0.119,"vmax":1,"vmin":0.93},{"hmax":0.2035,"hmin":0.1513,"vmax":1,"vmin":0.93},{"hmax":0.2358,"hmin":0.1835,"vmax":1,"vmin":0.93},{"hmax":0.2681,"hmin":0.2158,"vmax":1,"vmin":0.93},{"hmax":0.3003,"hmin":0.2481,"vmax":1,"vmin":0.93},{"hmax":0.3326,"hmin":0.2803,"vmax":1,"vmin":0.93}],"logger":{"level":"debug"},"network":{"apiAuth":true,"internetAccessAPI":false,"ipWhitelist":[],"localAdminAuth":true,"localApiAuth":true,"restirctedInternetAccessAPI":false},"protoServer":{"enable":true,"port":19445,"timeout":5},"smoothing":{"enable":false},"webConfig":{"crtPath":"","document_root":"","keyPassPhrase":"","keyPath":"","port":8090,"sslPort":8092}}

< ----- Current Log --------------------------- >
2022-07-25T20:36:45.805Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:215:sendClose()) Send close to ::ffff:192.168.0.165: 1000 
2022-07-25T20:36:47.135Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.0.165
2022-07-25T20:36:47.428Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:129:handleInstanceSwitch()) Client '::ffff:192.168.0.165' switch to Hyperion instance 0
2022-07-25T20:36:47.777Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:1184:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.0.165



I use hyperion screen capture as a source, have two WLED controllers on the same network with a different amount of LEDs on each, only one of which i want to use hyperion with

**Comment by Lord-Grey** [comment]
Sorry, I forgot...
Would you mind switching to the 2nd instance and share the config too, please?

**Comment by theTobster500** [comment]
sorry I haven't responded sooner.
i haven't configured it with the second WLED controller, since the amount of lights is different when I choose it as an output it asks if i want to reconfigure the light layout which I would like to avoid unless necessary. do you still need the config if I haven't set it up?

**Comment by Lord-Grey** [comment]
Maybe I misunderstood you.
From the description, I assumed that you run two WLED controller manger my Hyperion.
As that would require two Hyperion instances, I asked for the config of the 2nd instance.
If I got you right, you run WLED A with Hyperion and WLED B standalone.
Have you checked that both WLEDs announce themselves with different mDNS names. You need to check in WLED or an mDNS Discovery App…

**Comment by theTobster500** [comment]
I see, yeah I could've clarified better, I only have one hyperion instance and run WLED B standalone. they do both have different mDNS names. the IPs are dynamic and they have switched that one takes the old one of the other in the past, which is why I use mDNS to connect to them.
I don't think it was an issue related to the IPs switching though since I could use "identify" and the right one would blink and other services like homebridge haven't had any mix-ups since I've switched to mDNS

**Comment by Lord-Grey** [comment]
Thanks for confirming.
I suggest closing the issue for now.
We can reopen, if other users face the same issue.

**Comment by theTobster500** [comment]
sounds good, thank you for your time
