### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by joe23rep** [hyperion-project/hyperion.ng#1498]
## Bug report
cant install the latest version via AUR package. manual installation also ends in compiling errors

#### Steps to reproduce
just try to install newest version on an arch based distro. tried it on 2 different systems and its both times not working

#### What is expected?
that the installation works

#### What is actually happening?
 get this error message

cc1plus: all warnings being treated as errors make[2]: *** [dependencies/external/flatbuffers/CMakeFiles/flatc.dir/build.make:174: dependencies/external/flatbuffers/CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:983: dependencies/external/flatbuffers/CMakeFiles/flatc.dir/all] Error 2 make: *** [Makefile:156: all] Error 2 ==> ERROR: A failure occurred in build(). Aborting...

**Comment by jypma** [comment]
@joe23rep  GCC 12.1 trips on `-Wstrict`, issuing a bogus compiler warning (upstream [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104336)). 

Could be fixed by not enabling `-Wstrict` on GCC 12.
