### ISSUE TITLE
kodi checker use regex to read json

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#15]
Needs to be refactored, @Paulchen-Panther pointed me to this, maybe he is interested to refactor this.

**Comment by redPanther** [comment]
perhas we can use new qt json parser in this document as a test for migration the more complex parts?

**Comment by brindosch** [comment]
Hm, another question.
If we start and stop the grabbers later during runtime, make it sense to remove the kodicheck part out of all grabbers and just start and stop the grabber with this function?

My biggest problem may be that i have no idea how big the delay is from start grabber to start grabbing. Currently the switch is faster than the video you start (or pause/play) :)

**Comment by redPanther** [comment]
kodicheck triggers grabber start/stop - this won't change
additional every grabber can have idle detection that suspends the grabber. v4l2 does this already

start/stop during runtime is also needed, if we start with an unconfigured (no) grabber and then enable a grabber in the webinterface - or we want to change configuration of a grabber during runtime (without a restart)

**Comment by brindosch** [comment]
But it triggers inside the grabber code, if you trigger the grabber external it is a "bigger" initialize phase?
This was my concern.

**Comment by redPanther** [comment]
you mean when using hyperion-dispmanx instead of grabber in hyperiond?

start/stop grabber deosn't mean that we launch/kill the app regarding it's status. We will send a stop signal that stops sending, but it didn't kill the grabber. The grabber (e.g. hyperion-dispmanx) is running all the time.

**Comment by brindosch** [comment]
yes
if we implement it this way yes
