### ISSUE TITLE
Logo should say "Lighting" not "Lightning"

### ISSUE THREAD

**Issue by mooreye** [hyperion-project/hyperion.ng#1505]
- [x] I confirm that this is an issue rather than a question.

## Bug report
"Lightning" is a word that means a bolt of light during a thunderstorm. The logo should say "Lighting" (no 'n').

#### Steps to reproduce
N/A

#### What is expected?
I expected to see correct vocab in logo

#### What is actually happening?
Logo vocab is not correct

#### System

N/A

**Comment by mkcologne** [comment]
This is as old as this Tool is. 
We will take care.
Cheers - M.
