### ISSUE TITLE
Screen Capture issue

### ISSUE THREAD

**Issue by n4tur3502** [hyperion-project/hyperion.ng#1507]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
When I select either x11 or xcb my leds flicker when sitting idle.  When I switch over to usb capture the issue disappears. This is running on the latest stable LibreElec x86_64.  When I change the refresh rate on x11 or xcb it seems to cause random flickering.  

I have a log here https://pastebin.com/xnqtYtRX

#### System
Hyperion Server:
- Build:             (HEAD detached at 5dc696b8) (GitHub-dfd94381/5dc696b8-1653218333)
- Build time:        May 22 2022 11:40:56
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         expert
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /storage/hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      LibreELEC (official): 10.0.2
- Architecture:      x86_64
- CPU Model:         AMD Ryzen 5 3600 6-Core Processor
- CPU Type:          113
- Kernel:            linux (5.10.76 (WS: 64))
- Root/Admin:        true
- Qt Version:        5.7.1
- Python Version:    3.5.3
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
@n4tur3502 Most likely, the flickering is caused of the hardware setup.
I suggest you check with the community in the [Hyperion Forum](https://hyperion-project.org/forum/).

Questions will be, if you power the LED-Strip from both ends and have a common ground....
Might be although worth setting a very light color via a Color Effect and see, if flickering occurs too.
