### ISSUE TITLE
Raspberry PI4 - update from 2.0.12 to 2.0.13 ->qt.qpa.xcb: could not connect to display :0.0 

### ISSUE THREAD

**Issue by denimjeans** [hyperion-project/hyperion.ng#1518]
- [x] I confirm that this is an issue rather than a question.

## Bug report
after upgrading to 2.0.13 hyperiond does not start anymore, I receive:
`pi4p[0][~/devel]# hyperiond 
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstal   ling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Abgebrochen`
downgrading to 2.0.12 and it works. Back to 2.0.13, still same issue. Why is it trying to open a display ? I am using it only as daemon. 

#### Steps to reproduce
uname -a
`Linux pi4p 5.10.82-v7l+ #1493 SMP Wed Dec 1 11:37:31 GMT 2021 armv7l GNU/Linux`
apt install hyperiond

#### What is expected?
after 
`hyperiond`
it should work, but it doesn't
#### What is actually happening?

after upgrading to 2.0.13 I receive:
`pi4p[0][~/devel]# hyperiond 
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstal   ling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Abgebrochen
`

#### System

It does not start, so I cant provide it

**Comment by denimjeans** [comment]
Thanks for your reply. I am using latest debian Bullseye. Everything is fine with 2.0.12. But not for the 2.0.13 + nightly built 2.0.14. 
how do enforce to start as service? Good idea. Assuming this would resolve the issue as there is no UI required.

**Comment by Lord-Grey** [comment]
If you start via commandline 
`hyperiond —service`

if this does not work do hyperiond -h to check the exact wording (I am traveling right now)

**Comment by denimjeans** [comment]
> If you start via commandline `hyperiond —service`

Cool, That worked, thanks. So I need to do an alias then. 
-h does give the same error back. It seems that hayperiod expects a display by default. Anywhere we can setup to start without a GUI. Beside the alias option?
What switches are possible with hyperiond?

**Comment by Lord-Grey** [comment]
Hi @denimjeans 
Sorry, for only coming back after a while...

I did install a fresh [Raspberry Pi OS](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit) and Hyperion 2.0.14 via the APT repository and it works.

![Bildschirmfoto von 2022-11-30 17 00 23@2x](https://user-images.githubusercontent.com/48840279/204847337-6b8132ed-2448-407d-ba22-03ead8b48c3a.png)

Maybe you installed a package that is not fit for purpose for bullseye.

I would suggest the following.

1. Uninstall Hyperion completely
2. Install Hyperion from the official APT repository as described [here](https://apt.hyperion-project.org/)

Hopefully, it will work correctly then.
If not, we would need to identify what is the difference between your environment and mine....

**Comment by denimjeans** [comment]
@Lord-Grey, thanks. I'd assume it has then something to do with the enviroment variables. As reinstalling does not fix it. 
I can live with that alias solution no problem, just wanted to make you aware of this issue in case of others having the same problem

**Comment by denimjeans** [comment]
just for the protocol, issue still presits
```
pi4p[1][/mnt/devel/hyperion2015]# /usr/bin/hyperiond --version
QXcbConnection: Could not connect to display :0.0
Abgebrochen
pi4p[1][/mnt/devel/hyperion2015]# /usr/bin/hyperiond --version --service
Hyperion Ambilight Deamon
        Version   : 2.0.15 ((HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483))
        Build Time: Feb 19 2023 16:02:36
```

**Comment by Lord-Grey** [comment]
I am just wondering, do you run Hyperion on a rpi OS installation with desktop or without (light)?
In case with desktop, the standard one or another?

**Comment by denimjeans** [comment]
I dont use the desktop version. So lets call it light then :-). So your assumption is correct. 
if you quit the desktop and run on terminal only, you should be able to reproduce the issue
