### ISSUE TITLE
Install on Ubuntu 22.10 (kinetic) fails, missing release file

### ISSUE THREAD

**Issue by fightforlife** [hyperion-project/hyperion.ng#1531]
- [x] I confirm that this is an issue rather than a question.

## Bug report

This is more of a tracking ticket.
When following the official installation guide and installing hyperion via apt repo, there is no release file for Ubuntu 22.10 (kinetic).
https://docs.hyperion-project.org/en/user/Installation.html

#### Steps to reproduce
install Ubuntu 22.10 (kinetic)
follow the installation instructions: https://docs.hyperion-project.org/en/user/Installation.html

#### What is expected?
Hyperion should have a valid Release file for ubuntu 22.10 kinetic and install correctly.

#### What is actually happening?
Hyperion cannot be isntalled, because release file is missing.
If downgrading the releasefile to jammy there are unmet dependencies:

```
The following packages have unmet dependencies:
 hyperion : Depends: libpython3.9 but it is not installable
            Depends: libmbedtls12 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

#### System

Standard Ubuntu 22.10 x64 trying to install Hyperion 2.0.13

**Comment by fightforlife** [comment]
Fo anyone else finding this. It seems it is already available in nightly:
https://apt.hyperion-project.org/#nightly

**Comment by Lord-Grey** [comment]
@fightforlife Looks like we should do a release that kinetic gets also officially available.
For now, please make use of the nighly builds.

**Comment by Lord-Grey** [comment]
A new release 2.0.14 was provided yesterday including apt files for kinetic.
