### ISSUE TITLE
Cannot connect to Philips Hue Bridge 

### ISSUE THREAD

**Issue by killkrt** [hyperion-project/hyperion.ng#1541]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Cannot bind my Philips Hue bridge

#### Steps to reproduce
1. Select Led Instance > Led Output > Led Controller
2. Set Controller type to "philipshue"
3. Click on "Philips Hue Entertainment Wizard"
4. Enter the bridge IP address (same network of Hyperion server)

#### What is expected?
No bridge will be discovered even if providing the correct address.

#### What is actually happening?
Hue bridge should be found.
Also tried to create a new client, pushing the link button when is requested, but with no luck.

Log is providing this error: 
```
LEDDEVICE         : <ERROR> Invalid port [0] for host: (192.168.1.***)! - Port must be in range [0 - 65535]
hyperiond[9]: Invalid port [0] for host: (192.168.1.***)! - Port must be in range [0 - 65535]
hyperiond[9]: Invalid port [0] for host: (192.168.1.***)! - Port must be in range [0 - 65535]
```

Inside docker container that is running Hyperion I can _wget_ the index.html form that IP address and I can confirm that it is reachable and it is my HUE bridge.

#### System

Docker container running Hyperion v2.0.14

**Comment by Lord-Grey** [comment]
Set the Port = 80 on the LED-Configuration page.
If you do not see the port, change to Expert settings.

Please note that for Hue-Entertainment API additional ports need to be opened in docker.
See [here ](https://github.com/psychowood/hyperion.ng-docker) for reference.
