### ISSUE TITLE
Cololight Strip is not being detected correctly

### ISSUE THREAD

**Issue by scttrgd** [hyperion-project/hyperion.ng#1550]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When I attempt to add a new Cololight Strip, Hyperion returns _Failed to get the device's properties. Please check the configuration items._ and fails to allow the device to be added

#### Steps to reproduce
Both adding the device using the mDNS based service and by adding the IP address directly. 

#### What is expected?
Add device to hyperion

#### What is actually happening?
The device does not get added and in the logs the following is shown: 
`2022-12-30T14:39:49.890Z [LEDDEVICE] (DEBUG) (MdnsBrowser.cpp:180:resolveAddress()) Resolved mDNS hostname [MyHost.local.] to address [192.168.1.95]`
`2022-12-30T14:39:49.890Z [LEDDEVICE] (INFO) Resolved hostname (ColoLight-CEDA48._hap._tcp.local) to IP-address (192.168.1.95)`
`2022-12-30T14:39:49.890Z [LEDDEVICE] (INFO) Stream UDP data to 192.168.1.95 port: 8900`
`2022-12-30T14:39:50.117Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:563:setLedCount()) LedCount set to 0`
`2022-12-30T14:39:50.117Z [LEDDEVICE] (ERROR) Number of LEDs cannot be resolved`

If I _inspect element_ and remove the _disabled_ from the identify button, the device does flash many colours and then switches off. 

The only thing that I can think that might be happening is that this device is being misrecognised as a cololight plus rather than a cololight strip device as the DNS entry in my router sees it as CololightPlus-XXXXX (I'm absolutely not a C++ dev so I'm absolutely clutching at straws) 

I'm using a 5v 3A power supply and am able to control the device using both the app and with HomeKit. 
I've tried this with both the Hyperbian and with an install on an LXC container with the same results. 

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.14) (LordGrey-c9a1c88/b109703-1669566414)
- Build time:        Nov 27 2022 18:59:24
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.14
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         expert
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      HyperBian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 3 (v7l)
- CPU Type:          Raspberry Pi 4 Model B Rev 1.2
- CPU Revision:      c03112
- CPU Hardware:      BCM2711
- Kernel:            linux (5.15.76-v7l+ (WS: 32))
- Root/Admin:        true
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
I had problems with an older Strip too.
Have you installed the latest Cololight App on your mobile?
Have you installed the latest Firmware to the device?
Have you configured the "Device distance" (under device Settings) to the correct LED-Number?

**Comment by scttrgd** [comment]
It was the Device distance! I had no idea that setting meant number of LEDs! I've now got an issue where only 20 seem to be controlled and the other 40 are just full power (I believe this might actually be a fault with the unit) 
Thank you so much for the guidance!
