### ISSUE TITLE
Problème HyperBian wifi image problem not working on Raspberry PI4

### ISSUE THREAD

**Issue by JYCrois** [hyperion-project/hyperion.ng#1563]
- [x] #1564

## Bug report

Problème HyperBian wifi image problem not working on Raspberry PI4 model B from 2018
test made on 2 raspberry PI4 model B of 2018

#### Steps to reproduce

test with the latest version of November 2022

#### What is expected?

verification under SSH, wifi configuration well taken into account thanks to the wpa_supplicant.conf file

#### What is actually happening?

Wifi does not work, Hyperion is seen on the network as soon as I connect it to ethernet

**Comment by Lord-Grey** [comment]
I suggest you verify the WiFi configuration on the OS level.
This is not an Hyperion related issue.

**Comment by JYCrois** [comment]
no indeed hyperion is not in question, the problem comes from the Hyperbian ISO image which does not contain the wifi drivers for the RPI4, I installed the ISO image official version of Raspbian 64 bits then I installed hyperion and wifi works

⁣Télécharger BlueMail pour Android ​

Le 5 févr. 2023, 15:21, à 15:21, LordGrey ***@***.***> a écrit:

**Comment by Lord-Grey** [comment]
The HyperBian image is an http://archive.raspberrypi.org/debian bullseye/main armhf image with Hyperion installed via apt on top.

Maybe you could outline which package is missing for rpi4 Wifi looking at the latest build run:
https://github.com/hyperion-project/HyperBian/actions/runs/4060512392/jobs/6989675855
Then we can add it.
