### ISSUE TITLE
LED Matrix Vertical Cabling Direction not working

### ISSUE THREAD

**Issue by liquidbliss** [hyperion-project/hyperion.ng#1566]
- [x] I confirm that this is an issue rather than a question.

## Bug report
In the release notes of hyperion 2.0.13 a feature for vertical cabling direction should have been added:

> LED Layout Matrix: Support vertical cabling direction (#1420)

However, this feature is not available in LED-Layout Tab.
Versions checked 2.0.13 and 2.0.14

#### Steps to reproduce
Select "LED Instanced" --> "LED Layout" --> "Matrix Layout (LED Wall)"

#### What is expected?
Expected a way to select cabling direction

#### What is actually happening?
The "old" interface is shown, where it's not possible to select cabling direction

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.14) (LordGrey-c9a1c88/b109703-1669566414)
- Build time:        Nov 27 2022 18:20:23
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.14
- UI Lang:           en (BrowserLang: de-DE)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Raspbian GNU/Linux 10 (buster)
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 4 (v7l)
- CPU Type:          Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:      a22082
- CPU Hardware:      BCM2835
- Kernel:            linux (4.19.97-v7+ (WS: 32))
- Root/Admin:        true
- Qt Version:        5.7.1
- Python Version:    3.5.3
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
Hi @liquidbliss Thanks for highlighting.
You very well spotted at problem that the "direction" was removed erroneously via one [commit ](https://github.com/hyperion-project/hyperion.ng/pull/1421/commits/32caeb6a29256a5974b052ad996b254e82e3bab3#) from the UI page.
I will add it again.

**Comment by Lord-Grey** [comment]
I added the fix to the following PR https://github.com/hyperion-project/hyperion.ng/pull/1556 in case you would like to test it.
