### ISSUE TITLE
Gifs upload by Remote control => Colors/Effects not moving (are static)

### ISSUE THREAD

**Issue by kamilk91** [hyperion-project/hyperion.ng#1568]
- [x] I confirm that this is an issue rather than a question.

How to upload gif to make it moving?

#### Steps to reproduce
1. Login to your hyperion panel
2. Go to Remote control => Colors/Effects
3. Upload gif
4. Check your leds

#### What is expected?

Gif is moving, leds are changing their states

#### What is actually happening?

Gif is not moving i can see only first frame. 

#### System

```

yperion Server:
- Build:             (HEAD detached at 2.0.14) (LordGrey-c9a1c88/b109703-1669566414)
- Build time:        Nov 27 2022 18:59:24
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.14
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Raspbian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv6-compatible processor rev 7 (v6l)
- CPU Type:          Raspberry Pi Zero W Rev 1.1
- CPU Revision:      9000c1
- CPU Hardware:      BCM2835
- Kernel:            linux (5.15.32+ (WS: 32))
- Root/Admin:        true
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64)


```

**Comment by Lord-Grey** [comment]
Would you mind to share the Gif which is not working, please?

**Comment by kamilk91** [comment]
@Lord-Grey sure thing, i uploaded it to my gdrive

https://drive.google.com/drive/folders/1DKtQuzgK9PtVKhyWE7jaEcsSHvz-2FsM?usp=sharing

**Comment by Lord-Grey** [comment]
"Picture" on the remote control will only show one picture not executing an animation.
If you would like to have the animated version of the image, create an "GIF's" Effect via the Effects Configurator.
Then you can select your custom effect and you have the animated GIF running via the LEDs.

![image](https://user-images.githubusercontent.com/48840279/219943959-a06be814-015b-430c-b302-085e227497a5.png)

![image](https://user-images.githubusercontent.com/48840279/219943995-02981c55-6631-4ffc-8b38-980423a02f01.png)
