### ISSUE TITLE
debian packages have dependency libpython3.9, but when running it expects 3.10

### ISSUE THREAD

**Issue by hg42** [hyperion-project/hyperion.ng#1579]
- [x] I confirm that this is an issue rather than a question.

## Bug report

when I install
2.0.15 or
2.0.16-beta.1+nightly20230222a393f62
on debian from the hyperion apt repository,

it pulls the dependency **libpython3.9**,
but the executable expects **libpython3.10**

If I install libpython3.10, everything works like expected.

Note, system python version is 3.11.
The error will not show up on systems, where python 3.10 is installed.

#### Steps to reproduce

install the debian packages on debian testing (or any other system where **python 3.10 is _not_ installed**)

#### What is expected?

the dependency should be libpython3.10

#### What is actually happening?

libpython3.10 is missing (unless I install it manually)

#### System

Hyperion Server:
- Build:              ()
- Build time:        Feb 22 2023 00:22:53
- Git Remote:        
- Version:           2.0.16-beta.1+nightly20230222a393f62
- UI Lang:           auto (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/harald/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Debian GNU/Linux bookworm/sid
- Architecture:      x86_64
- CPU Model:         AMD Ryzen 5 PRO 4650G with Radeon Graphics
- CPU Type:          96
- Kernel:            linux (6.1.11-1-liquorix-amd64 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.7
- Python Version:    3.10.9
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0

**Comment by Paulchen-Panther** [comment]
Thank you very much for your effort to create an issue. I can confirm the error in any case.
If you would do us a favor and create a PR. The affected location is here:
https://github.com/hyperion-project/hyperion.ng/blob/a393f6211c90c7ef26c4d296a9de1d8ba9d9e074/.github/workflows/apt/amd64.json#L62

Greetings Paulchen

**Comment by hg42** [comment]
Ok, I can change the version in that file.

Though I think, it would be better, if the version in that file would autmatically follow the linked version.
But I'm not familiar with the project, nor am I able to compile it.

As far as I can see, it would compile an executable linked to python 3.11 on my system (which calls itself bookworm, but as I said it's a mix, mostly testing + parts of unstable, ubuntu versions etc.).
So, the created package would not be correct for my system (installing what is in the amd64.json file, but linking what is on my system), though it would work, because the default python version is already there.

I also checked the other variants in that file (`bionic`...`bookworm`) installing them and using `readelf -d` on the executable.
The other entries are ok.
Note: I didn't test `stretch`, because I didn't have the necessary sources and it would create too many conflicts etc.

**Comment by hg42** [comment]
interesting...
if I create a debian package with docker-compile.sh (which is the only way it works for me), it contains it's own libpython and it's not included in the dependencies of the package.
So, I still cannot test the real release this way.

create_all_releases.sh sounds suitable, but
compiling without docker complains about ALSA (maybe because I have pipewire?).
