### ISSUE TITLE
Kodi checker initial state bug

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#158]
If you have a video playing and then start Hyperion it doesn't "grab video" I just get the background effect.

**Comment by brindosch** [comment]
Is this new  since rework? I think kodi push no information? What shows the log?

**Comment by penfold42** [comment]
Dont known- latest git pull

I'm not near the pi, but there were 3 log entries on startup with the kodi data in it.

Stop movie, back to menu, start movie and it worked fine

**Comment by brindosch** [comment]
I think stop and start a movie should be enough. I bet Hyperion don't get the appropriate status on startup. I will test this.

**Comment by penfold42** [comment]
It wasn't menu mode - it was the background effect.

Grab menu, screensaver, audio etc... Are all on

**Comment by penfold42** [comment]
I told a lie - grab pause is false.

I'm 99% sure the movie wasn't paused tho.

I can't retest now - I can take a look in a day or so

**Comment by penfold42** [comment]
Thanks !

**Comment by Paulchen-Panther** [comment]
Thank you.
