### ISSUE TITLE
Audio Capture enabled after reboot automatically

### ISSUE THREAD

**Issue by Nikpesu** [hyperion-project/hyperion.ng#1581]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Audio Capture enabled after reboot/sign out/lock on windows automatically

#### Steps to reproduce
reboot/sign out/lock in windows

#### What is expected?
Just continue in mode that is desired/was present before

#### What is actually happening?
Audio Capture enabled and vu meter effect is applied

#### System
Win11 build 22621.1265 (latest)

Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 14:48:39
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         expert
- Avail Screen Cap.: qt,dx
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       C:/Users/nikpe/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Windows 10 Version 2009
- Architecture:      x86_64
- Kernel:            winnt (10.0.22621 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.11.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

**Comment by 9000000** [comment]
this is a very serious bug please fix it

**Comment by Lord-Grey** [comment]
@Nikpesu How are you disabling the audio grabber?
Via the Remote-Control, Dashboard or via the Capturing Hardware screen?

Note: Disabling via the Remote Control or Dashboard is always temporarily. That state will not be restored after a reboot.

Maybe you can do some screenshot outlining what you do and where you see the failure, please?
Thank you!

**Comment by Nikpesu** [comment]
@Lord-Grey could you compile for windows? Thanks in advance

**Comment by Lord-Grey** [comment]
> @Lord-Grey could you compile for windows? Thanks in advance

It is already available as part of the PR build.
See here https://github.com/hyperion-project/hyperion.ng/actions/runs/4746896023

**Comment by Nikpesu** [comment]
oh, i didn't realise. Thanks!

**Comment by Paulchen-Panther** [comment]
@Nikpesu  have you tested the fix?

**Comment by Nikpesu** [comment]
yes, and it works.
