### ISSUE TITLE
Lock/unlock hander- session bus is not connected

### ISSUE THREAD

**Issue by tricyphona** [hyperion-project/hyperion.ng#1587]
- [x] I confirm that this is an issue rather than a question.

## Bug report

After installing hyperion on a raspberry pi 4, during start up I get an error:
Mar 13 12:22:49 raspberrypi systemd[1]: Started Hyperion ambient light systemd service  for user root.
Mar 13 12:22:50 raspberrypi hyperiond[4466]: 2023-03-13T12:22:50.230 |__| DAEMON            : <ERROR> Lock/unlock handler- Session bus is not connected
Mar 13 12:22:50 raspberrypi hyperiond[4466]: Lock/unlock handler- Session bus is not connected

I use controller type: ws281x, and the LED's do not respond. 

#### Steps to reproduce

LEDs signal are connected on GPIO pin 18
LEDs ground to GPIO 0V & power supply
LEDs 12V is connected to powersupply +12V

Installing hyperion as described in https://docs.hyperion-project.org/en/user/Installation.html#raspberry-pi (either as extra program within raspberry pi, or as hyperbian). 
In another guide, extra steps were described to:
systemctl disable --now hyperion@user.service
systemctl enable --now hyperion@root.service

The 4 options have been tried: 
rpi + hyperion without extra steps
rpi + hyperion with extra steps
hyperbian without extra steps
hyperbian with extra steps
#### What is expected?

The leds to light up. 

#### What is actually happening?

The following error is showing as soon as hyperion starts. And no led light up. 
Mar 13 12:22:49 raspberrypi systemd[1]: Started Hyperion ambient light systemd service  for user root.
Mar 13 12:22:50 raspberrypi hyperiond[4466]: 2023-03-13T12:22:50.230 |__| DAEMON            : <ERROR> Lock/unlock handler- Session bus is not connected
Mar 13 12:22:50 raspberrypi hyperiond[4466]: Lock/unlock handler- Session bus is not connected

See also the pastebin: https://pastebin.com/zQDbYYX6

**Comment by Paulchen-Panther** [comment]
https://hyperion-project.org/forum/index.php?thread/13225-error-lock-unlock-handler-session-bus-is-not-connected/

**Comment by tricyphona** [comment]
Thanks for your reply!
Found this link aswell last few days ago:
https://github.com/hyperion-project/hyperion.ng/issues/641 --> https://github.com/jgarff/rpi_ws281x
The audio of rpi keeps locking /var/lock/asound.state.lock
blacklist snd_bcm2835, in config.txt:
