### ISSUE TITLE
Cannot stream USB Video to multiple segments

### ISSUE THREAD

**Issue by demuxer86** [hyperion-project/hyperion.ng#1588]
- [x] I confirm that this is an issue rather than a question.

## Bug report

SK6812b 600led strip, ESP32, Raspberry Pi 4,  Hyperion version 2.0.15, WLED 0.14.0-b1, I setup two segments in WLED and Hyperion.   Segments work fine, but Hyperion will not stream USB Video to both segments.   If I switch one segment off, the other works fine, and same if the other way around.   

#### Steps to reproduce

Started from scratch a few times! 

#### What is expected?

Doing an Ambilight setup,  I want to use qty 2 rows of led's on the back of my TV to make it brighter.    WLED has no trouble creating segments to make a 600 led strip into two 300's, and I can make them do the same effects, but Hyperion can't stream the USB video to both. 

#### What is actually happening?

I believe there is a bug in Hyperion that isn't letting both segments see the USB video data at the same time.  

#### System

I am not at my setup right now, sorry.

**Comment by Lord-Grey** [comment]
WLED supports to have Hyperion streaming to one WLED segment or to all LEDs.
If you want to stream to all LEDs ignoring WLED's segment definition, you need to disable " "Realtime - Use main segment only" in WLED's Sync Interfaces setup screen".

If you enable " "Realtime - Use main segment only" in WLED's Sync Interfaces setup screen, you can stream to one selected segment.

I suggest you check your WLED configuration.
