### ISSUE TITLE
update to last version

### ISSUE THREAD

**Issue by Diegoloex** [hyperion-project/hyperion.ng#1590]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I can't hit the update button in the web interface, it won't let me.

I have searched for information about it, but I am very clumsy and I can't find anything

#### Steps to reproduce

hit the refresh button in the web interface

#### What is expected?

Update to a latest version of hyperion

#### What is actually happening?

no refreh to V2.0.15

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.13) (GitHub-dfd9438/5dc696b-1653218333)
- Build time:        May 22 2022 12:55:01
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           es (BrowserLang: es-ES)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      HyperBian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv6-compatible processor rev 7 (v6l)
- CPU Type:          Raspberry Pi Zero W Rev 1.1
- CPU Revision:      9000c1
- CPU Hardware:      BCM2835
- Kernel:            linux (5.15.61+ (WS: 32))
- Root/Admin:        true
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 OPR/96.0.0.0

**Comment by Paulchen-Panther** [comment]
The update page clearly states: "At the moment the respective install button is disabled. Development is still ongoing here."
Let me refer you here: https://apt.hyperion-project.org/
