### ISSUE TITLE
Allow changes to the first created instance, or let us completely delete it if we have others set up.

### ISSUE THREAD

**Issue by cr0sis** [hyperion-project/hyperion.ng#1592]
## Feature request

Allow changes to the first created instance, or let us completely delete it if we have others set up.

I had to reinstall WLED on a blank D1 mini and point my first instance at that, then never turn that d1 on.

I wasn't happy with the led's behind my monitor, added better colour strips and more led's and the first instance kept re-initialising itself (while tied to the same IP of the new working instance). It wouldn't let me change the led's of the first instance which was all I really needed to do to accommodate the changes. I would have been fine either pointing it to an IP that it could never resolve or if I could remove the instance entirely, or if changes I made to disable the instance remained disabled between sessions.

**Comment by Paulchen-Panther** [comment]
I advise you to delete the Hyperion database and start over. You can find the database in your home directory under ".hyperion/db".
