### ISSUE TITLE
Unable take Web Access from Different LAN Subnet 

### ISSUE THREAD

**Issue by avamit2002** [hyperion-project/hyperion.ng#1593]
#### What problem does this feature solve?
After solving this , I would be able to access Hyperion through the WEB from different Subnet.

#### What does the proposed API look like?
N/a
#### How should this be implemented in your opinion?
The Different Subnet Should be whitelisted in the Hyperion main config file. I am unable to Locate this file in raspberry pi OS in which I installed the Hyperion through script.

#### Are you willing to work on this yourself?
I could do, if get some suggestion.

**Comment by Paulchen-Panther** [comment]
https://serverfault.com/a/760518/1011708

**Comment by avamit2002** [comment]
I already tried that way by allowing the Source IP subnet into  iptables. It didn't work. I'm able to take ssh and http/https are also accessible if I telnet the ports from different subnet. When trying to load the url from browser it is started to loading and stuck with loading state, when I debugged in chrome it is stuck on application layer.  css and js contents are not being loaded.

I would like to bring up one more point, that there is Firewall/UTM is placed between source and destination, however I checked all by enabling/allowing everything on Firewall side. Still no luck.

Note:  If accessing from the same subnet in which Hyperion server located, there is no issue with anything all looks good. The issue is only from different subnet.

I would appreciate if you could help me out.

**Comment by tpmodding** [comment]
we never did some iptable stuff nor limitations in accessing the webui... dont know where to look at...you also do not provide any information about your setup...so kinda hard to help
