### ISSUE TITLE
Multi-Lightpack Support

### ISSUE THREAD

**Issue by ChaosCoder** [hyperion-project/hyperion.ng#1594]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I see that [Multi-Lightpack](https://docs.hyperion-project.org/de/user/leddevices/usb/multilightpack) should be supported, but I can not select it in the dropdown for the LED-hardware. Selecting "lightpack" only lights up one of my two lightpacks.

#### Steps to reproduce
Go to LED-hardware in the main menu
Use the dropdown to select "multi-lightpack"

#### What is expected?
There is an option with "multi-lightpack" and choosing it works.

#### What is actually happening?
There is no option with "multi-lightpack"

#### System

Hyperion Server:
- Build:              ()
- Build time:        Feb 19 2023 16:07:33
- Git Remote:        
- Version:           2.0.15
- UI Lang:           de (BrowserLang: de-DE)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Raspbian GNU/Linux 10 (buster)
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 4 (v7l)
- CPU Type:          Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:      a02082
- CPU Hardware:      BCM2835
- Kernel:            linux (5.15.84-v7+ (WS: 32))
- Root/Admin:        true
- Qt Version:        5.11.3
- Python Version:    3.7.3
- Browser:           Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

**Comment by Paulchen-Panther** [comment]
I think they forgot to remove the Device from the [Schema](https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/hyperion/schema/schema-device.json#L77).
According to [this PR](https://github.com/hyperion-project/hyperion.ng/pull/1049), the device was removed with the [2.0.0-alpha.9 release](https://github.com/hyperion-project/hyperion.ng/releases/tag/2.0.0-alpha.9) and replaced with the multi-instance option.
All further backgrounds can only be answered by @Lord-Grey .

**Comment by Lord-Grey** [comment]
The multi-light pack was removed in favour that there is multi-instance support now.
Suggest you create a 2nd instance in Hypeeion and configure your 2nd lightpack.
