### ISSUE TITLE
Hyperion 2.0.15 not starting with libfreetype 2.13

### ISSUE THREAD

**Issue by xBelladonna** [hyperion-project/hyperion.ng#1597]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion 2.0.15 does not start on Arch Linux due to incompatibility with newer libfreetype 2.13. See #1359 for a similar issue on Fedora. Hyperion 2.0.15 is currently working on Debian bookworm with libfreetype 2.12.

#### Steps to reproduce
1. Download and extract Hyperion-2.0.15-Linux-x86_64.tar.gz
2. Run hyperiond

#### What is expected?
hyperiond will start normally and appear in the system tray.

#### What is actually happening?
hyperiond exits with the following error:
`hyperiond: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language`

If the library version from Debian 12 (bookworm) is copied to `/usr/lib` and symlinked to `libfreetype.so.6`, Hyperion then launches without issue. I have tested this with the current Debian library `/usr/lib/x86_64-linux-gnu/libfreetype.so.6.18.3`. Arch's version appears to be `libfreetype.so.6.19.0`.

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 14:41:05
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           en (BrowserLang: en-AU)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/bella/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Arch Linux
- Architecture:      x86_64
- CPU Model:         AMD Ryzen 7 3700X 8-Core Processor
- CPU Type:          113
- Kernel:            linux (6.2.10-arch1-1 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.7.1
- Python Version:    3.5.3
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by xBelladonna** [comment]
I have updated the system information in this issue. I was able to get hyperiond to launch by copying the working libfreetype from Debian 12 to my Arch installation and symlinking it to `libfreetype.so.6`. This is not a setup I have left permanently on my system, this was just for testing. I am willing to do any testing, building, investigation that I am capable of to get this fixed. Please let me know if recreating the test setup with the older libfreetype and doing some more work would be helpful.

**Comment by Lord-Grey** [comment]
Would you mind checking with the new releases 2.0.16?
For Fedora, we now provide dedicated dnf installation files see [here](https://releases.hyperion-project.org/)

**Comment by xBelladonna** [comment]
I (unfortunately) run Arch Linux as I'm all about getting the latest bugs first, so I packaged it using the tarball release as the source and installed it as a normal Arch user would (I think). I can confirm it all works! libfreetype 2.13.2-1 seems to work fine with it and the workaround is no longer required. Thank you so much!!
