### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Graffetti** [hyperion-project/hyperion.ng#1599]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
i intsalled hyperion and became the error lock/unlock session bus not connectet

#### What is expected?
a fix that i can use hyperion

#### What is actually happening?

i cant use it because the error

#### System
   https://pastebin.com/uHDy8ADc

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/issues/1587
