### ISSUE TITLE
zeroconf: move to own setting

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#16]
if we work anyway on everything ...

```
zeroconf
{
enable : true,
~~mDNSDescr : "aname",~~
~~mDNSService : "aServiceName"~~
},
```
I have a general question regarding zeroconf, if people configure another mDNSService (name?) an App could no longer identifiy it as Hyperion port?

Your example lead to this if i am right?
root@Penfold42MediaPlayer:~# avahi-browse -r _hyperiond_json._tcp

This identifier should be hardcoded - always the same.
And i am not sure if we should keep the option mDNDsecr, if we provide this optional in general i need to add it to the JSON checker, @Paulchen-Panther finished the json write to write a config. but it is based at the information of the json checker.
So the problem - the value will be the same on all platforms as long the user don´t change it  (or we code a detection to input this) (which will be usually 99%)

I would prefer to stick always with the hostname of the current device.

**Comment by redPanther** [comment]
why make a config for zeroconf(!) - there should be no configuration. I think we can set meaningful defaults. I see no reason why user should change this values

**Comment by brindosch** [comment]
Good ;)

But you could configure it?
https://github.com/hyperion-project/hyperion.ng/blob/master/src/hyperiond/hyperiond.cpp#L246-L247

**Comment by redPanther** [comment]
Of course. We can think about removing the ability to configure it

**Comment by penfold42** [comment]
are there any best practices for the service type, description or TXT records?

**Comment by brindosch** [comment]
@redPanther 
hm, okay, no disable option ;) (i thought that you as advanced user may appreciate that for *insertAreason*)
But this is also a reason why i want different access levels for the webinterface. Hide options you don´t need (majority of users) and the other just switch to "expert" and have fun :D

@penfold42 
are there applications you may have a look at?

**Comment by penfold42** [comment]
#22 makes this go away!
zerconf's config options have been moved to /dev/null
