### ISSUE TITLE
Installation problem with Debian Bookworm (current stable); libpython version mismatch

### ISSUE THREAD

**Issue by Psirus** [hyperion-project/hyperion.ng#1612]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Trying to install hyperion via apt as outlined in [the docs](https://docs.hyperion-project.org/en/user/Installation.html#install) fails with a libpython version mismatch.

#### Steps to reproduce

As per instructions, running on Debian Bookworm:

    wget -qO- https://apt.hyperion-project.org/hyperion.pub.key | sudo gpg --dearmor -o /usr/share/keyrings/hyperion.pub.gpg
    echo "deb [signed-by=/usr/share/keyrings/hyperion.pub.gpg] https://apt.hyperion-project.org/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hyperion.list
    sudo apt-get update && sudo apt-get install hyperion

#### What is expected?

Installation of Hyperion without errors.

#### What is actually happening?

~~~
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hyperion : Depends: libpython3.10 but it is not installable
            Depends: libmbedtls12 but it is not installable
E: Unable to correct problems, you have held broken packages.
~~~

#### System

No Hyperion yet. But as I say, Debian Bookworm.

**Comment by Paulchen-Panther** [comment]
Thanks for the bug report. Could you tell me your system?

**Comment by Psirus** [comment]
Not sure what you need to know. Desktop, MSI MS-7982 Mainboard, 16GB RAM, Intel i5 6500, Intel onboard GPU, 250GB SSD, 2TB HDD, Gnome 43.4.
