### ISSUE TITLE
Web server misspelling

### ISSUE THREAD

**Issue by specie77** [hyperion-project/hyperion.ng#1618]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion Web Configuration page. Explanations at the bottom of the screen. HTTPS Port says: “Port oft the HTTPS-Webserver” change “oft” to “of”.

#### Steps to reproduce
Load the page

#### What is expected?
Correct spelling 

#### What is actually happening?
Incorrect spelling (not being sarcastic, just trying to help)

#### System

v2.0.15

**Comment by Lord-Grey** [comment]
@specie77 Thanks for reporting the misspelled description.
Unfortunately, even the smallest mistakes are sometimes overlooked...

The error will be fixed within PR #1617

![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/599b9662-df56-44c1-be2f-0ca95aed2ee5)
