### ISSUE TITLE
(ERROR) Lock/unlock handler- Session bus is not connected

### ISSUE THREAD

**Issue by specie77** [hyperion-project/hyperion.ng#1622]
- [x] I confirm that this is an issue rather than a question.

## Bug report
WS218x LEDs work as intended, but only after using the updateHyperionUser.sh script (outside of bug report https://github.com/hyperion-project/hyperion.ng/issues/1620)

However, when Hyperion boots, the webUI shows an error in the log.

#### Steps to reproduce
Reboot, review webUI log.

#### What is expected?
Unsure?  Is this expected, should I ignore it?

#### What is actually happening?
Log error:
2023-07-17T17:51:00.231Z [DAEMON] (ERROR) Lock/unlock handler- Session bus is not connected

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 16:07:11
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           en (BrowserLang: en-US)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      HyperBian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv6-compatible processor rev 7 (v6l)
- CPU Type:          Raspberry Pi Zero W Rev 1.1
- CPU Revision:      9000c1
- CPU Hardware:      BCM2835
- Kernel:            linux (5.15.84+ (WS: 32))
- Root/Admin:        true
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
Thank for the reporting the issue on the misleading error messages in case hyperion is not able to support the suspend/lock feature.
This problem had already been fixed by #1605 .
