### ISSUE TITLE
gpg key for apt.hyperion-project.org expired

### ISSUE THREAD

**Issue by maschbaer** [hyperion-project/hyperion.ng#1627]
- [x] I confirm that this is an issue rather than a question.

## Bug report

when I try to run apt-get update, I get the following error:

`Hit:1 http://deb.debian.org/debian bullseye InRelease
Get:2 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:5 https://apt.hyperion-project.org bullseye InRelease
Hit:6 https://download.docker.com/linux/debian bullseye InRelease
Err:5 https://apt.hyperion-project.org bullseye InRelease
  The following signatures were invalid: EXPKEYSIG 0E6710C4A760E210 Hyperion Project <admin@hyperion-project.org>
Fetched 44.1 kB in 3s (14.9 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.hyperion-project.org bullseye InRelease: The following signatures were invalid: EXPKEYSIG 0E6710C4A760E210 Hyperion Project <admin@hyperion-project.org>
W: Failed to fetch https://apt.hyperion-project.org/dists/bullseye/InRelease  The following signatures were invalid: EXPKEYSIG 0E6710C4A760E210 Hyperion Project <admin@hyperion-project.org>
W: Some index files failed to download. They have been ignored, or old ones used instead. `
#### Steps to reproduce
Sudo apt-get update

#### What is expected?
No errors when apt-get update is run

#### What is actually happening?
The above error massage wrt key expired

#### System

`Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 16:07:11
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           de (BrowserLang: de-DE)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/pi/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Raspbian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 4 (v7l)
- CPU Type:          Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:      a020d3
- CPU Hardware:      BCM2835
- Kernel:            linux (6.1.19-v7+ (WS: 32))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like `

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/issues/1607#issuecomment-1572006214

**Comment by maschbaer** [comment]
Thanks! Works fine!

Please update the installation page
[https://apt.hyperion-project.org](url)

Jan
