### ISSUE TITLE
Audio Capture settings are ignored

### ISSUE THREAD

**Issue by pattyland** [hyperion-project/hyperion.ng#1630]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I finally got around to buying new hardware to test the new Audio Capture from version 2.0.15, but it looks like all of the settings except "Activate" are ignored.

#### Steps to reproduce
Activate Audio Capture and set e.g. Safe Color to Blue

#### What is expected?
Blue Light

#### What is actually happening?
The default settings are used, so in the case of "Safe Color" green. Saving the color works fine and is still correct after reloading etc.

#### System

Hyperion Server:
- Build:              ()
- Build time:        May 19 2023 17:58:09
- Git Remote:        
- Version:           2.0.15
- UI Lang:           en (BrowserLang: de-DE)
- UI Access:         default
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/pi/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Raspbian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 4 (v7l)
- CPU Type:          Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:      a02082
- CPU Hardware:      BCM2835
- Kernel:            linux (6.1.21-v7+ (WS: 32))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
Thank you for reporting the bug. I already found the issue and will correct it soon.
While testing, it seems there are other issues too.I need to have a closer look...
