### ISSUE TITLE
Setting a static color ignores blacklisted leds

### ISSUE THREAD

**Issue by RomRider** [hyperion-project/hyperion.ng#1634]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I created 2 LED Hardware (with the same LED controller).
One of them is using a full layout, the second one uses only some of the leds on the strip using the blacklist function.

When assigning a static color to the second LED hardware, the full strip is set to the color ignoring the blacklisted LEDs

#### Steps to reproduce

1. Create a LED Hardware
2. Blacklist some leds on the layout
3. Assign a static color
4. The full strip is now on (bypassing the blacklisted leds)

It doesn't apply to effects, only to plain colors.

#### What is expected?

Setting a plain color on a LED Hardware with a LED layout having blacklisted leds should only light up the non blacklisted leds.

#### What is actually happening?

blacklisted leds are ignored when using a static color

#### System

```
Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 15:13:33
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           auto (BrowserLang: fr-FR)
- UI Access:         expert
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /storage/hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      LibreELEC (official): 9.2.4
- Architecture:      arm
- CPU Model:         ARMv7 Processor rev 4 (v7l)
- CPU Type:          Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:      a02082
- CPU Hardware:      BCM2835
- Kernel:            linux (4.19.127 (WS: 32))
- Root/Admin:        true
- Qt Version:        5.7.1
- Python Version:    3.5.3
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safa
```

**Comment by Lord-Grey** [comment]
@RomRider Thanks for reporting this issue.
I fixed the problem via PR #1635
