### ISSUE TITLE
No 'RPi PWM' option?

### ISSUE THREAD

**Issue by FaboThePlayer** [hyperion-project/hyperion.ng#1636]
- [] I confirm that this is an issue rather than a question.

## Bug report
First I want to mention that server is running on a VM, LED's are not connected, just want to test the software before doing something on actual raspberry pi. I changed user to root. I find it odd that ws281s doesn't appear. First I thought that it will show up when I'll connect the LED's and use Hyperbian instead of debian in vm, but then the other shouldn't appear (RPi GPIO, SPI), right? Or is it exclusive to the actual raspberry Pi, that's why it doesn't appear?

![image](https://github.com/hyperion-project/hyperion.ng/assets/111151942/a6b40352-0b7c-4ba3-ad37-adcbe4cbf646)

#### Steps to reproduce
Run Hyperion as a root user.

#### What is expected?
An option to choose ws281x in RPi PWM column.

#### What is actually happening?
There is no column named RPi PWM.

#### System

Clean Debian 11 in virtual machine for now, planning to move to Hyperbian on raspberry pi zero w.

**Comment by Lord-Grey** [comment]
PWM will only be included for builds done for RPI, see the [build configuration](https://github.com/hyperion-project/hyperion.ng/blob/a5bb7e905ba153140c6563e88937e121ae3a88a9/CMakeLists.txt#L180).

In addition, if you run HyperHDR (as per screenshot) you should raise issues there and not with Hyperion.NG.

**Comment by FaboThePlayer** [comment]
Screenshot is from HyperHDR however I was trying this on the clean Hyperion-NG, and just had HyperHDR running at the moment of making screenshot. Anyways thank you so much for the answer.
