### ISSUE TITLE
Hyperion on Raspberry Pi5?

### ISSUE THREAD

**Issue by chromoxdor** [hyperion-project/hyperion.ng#1656]
Just tried to install hyperion on the RPi5 (libreelec) and it doesn´t want to run.
Can anybody confirm, that it is not yet supported or am i doing something wrong?

**Comment by tpmodding** [comment]
Hey, the devs dont have a rpi5 yet, we are waiting for it to be available to order

**Comment by chromoxdor** [comment]
Ohh, i see.. and i thought i am late with my new raspberry pi 🙂

**Comment by Paulchen-Panther** [comment]
@chromoxdor 
https://apt.hyperion-project.org/
