### ISSUE TITLE
Add an option to configure mDNS advertise address manually

### ISSUE THREAD

**Issue by meibensteiner** [hyperion-project/hyperion.ng#1659]
## Feature request

I have Hyperion running in a separate VLAN with an mDNS Relay. Unfortunately this means there is NAT being done between server and client and the server address announced with mDNS is not correct.
It would be great to have an option in the UI to set a "advertise address" so I can manually fix that, like it is possible in Home Assistant. https://www.home-assistant.io/integrations/homekit/#advertise_ip

#### What problem does this feature solve?

mDNS between networks needs manual intervention and a an override would make it possible to fix that.

#### What does the proposed API look like?

No idea, sorry.

#### How should this be implemented in your opinion?

mDNS annnouncement service would need to accept configuration from the web interface.

#### Are you willing to work on this yourself?

No. Not familiar with C++ unfortunately.

**Comment by Lord-Grey** [comment]
Hi
If I got it right, the Hyperion server should send a configured client network address while responding to mDNS requests that your relayed from client to server network?

As I am not too familiar with the described scenario, may I ask you to outline how you would use the translated IP in the client network, please?

**Comment by meibensteiner** [comment]
> If I got it right, the Hyperion server should send a configured client network address while responding to mDNS requests that your relayed from client to server network?

Yes, I think you got it right.
My Hyperion instance and my phone are in separate networks, with a Reverse Proxy in between. This works fine if I just use the DNS record, which resolves to the reverse proxy.

But I also have an mDNS proxy, which forwards mDNS from the server to the client network for automatic discovery. But since Hyperion sends out the IP native to its network, my client always gets the hyperion IP and not the reverse proxy domain name.

Which is why a single textbox to overwrite the URL the Hyperion server is sending would be very valuable for me. It could be in the "Web Services" or the "Web configuration" section.

**Comment by Lord-Grey** [comment]
Sorry, I do not get which device makes use of Hyperion‘s mDNS service advertised ?
Are you using the mDNS service name in the Mobile‘s  Browser?
Why can‘t you go with the DNS which works already?

**Comment by Lord-Grey** [comment]
Closing as no feedback provided…
