### ISSUE TITLE
Home screen widgets randomly unresponsive

### ISSUE THREAD

**Issue by Luiszd2305** [hyperion-project/hyperion.ng#1660]
Yes

- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
It happens randomly.

#### What is expected?
The home screen widgets should work all the time.

#### What is actually happening?
Home screen widgets are randomly unresponsive sometimes when getting back to the home screen. 

#### System
 I didn't find any System info there.

**Comment by Lord-Grey** [comment]
Would you mind providing a screenshot? 
I do not follow which homescreen and widgets you are referring to.
