### ISSUE TITLE
Hyperion APT repo is broken/docs have the wrong URL

### ISSUE THREAD

**Issue by andrew-kennedy** [hyperion-project/hyperion.ng#1666]
- [x] I confirm that this is an issue rather than a question.

## Bug report
There appears to be an issue with the installation instructions on the main hyperion website, I run into errors when I add the repository and install as described.

#### Steps to reproduce
Go through the apt repo setup as normal, proceed to install step:
```
sudo apt-get update && sudo apt-get install hyperion
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:5 https://apt.hyperion-project.org bookworm InRelease [1,838 B]
Fetched 1,838 B in 1s (1,287 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.hyperion-project.org bookworm InRelease' doesn't support architecture 'arm64'
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://apt.hyperion-project.org bookworm InRelease' doesn't support architecture 'armhf'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package hyperion
```

EDIT: The fix: I confirmed that the issue is the given URL on every set of hyperion docs is incorrect. If you dive into the source code for Hyperbian, you see the actual APT url is `https://apt.releases.hyperion-project.org`, not `https://apt.hyperion-project.org`. This is the cause of the repo apparently not supporting any valid architecture.

#### What is expected?
I expected hyperion to install normally.

#### What is actually happening?
Hyperion fails to install as the repo claims it doesn't support `arm64` or `armhf`.

#### System

```
> uname -a
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
```

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by Lord-Grey** [comment]
The repository in the documentation is the official current one. Unfortunately, at the time of the latest release there had been no Bookworm arm build environment available which is why you get the error.

We are in the process of reworking the apt repositoryand  this is why you already see the other url.
With the new repo Bookworm and Trixie will be a available for arm64 and armhf.

**Comment by Lord-Grey** [comment]
The repository and[ installation instruction](https://releases.hyperion-project.org/)s are now up to date.
