### ISSUE TITLE
Hyperion won't install on Debian Bookworm

### ISSUE THREAD

**Issue by Streammet** [hyperion-project/hyperion.ng#1668]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion does not install

#### Steps to reproduce
run the latest Debian 12

#### What is expected?
Hyperion to run

#### What is actually happening?
I get an error message after I run "sudo apt-get update && sudo apt-get install hyperion"

"
The following packages have unmet dependencies:
 hyperion : Depends: libpython3.10 but it is not installable
            Depends: libmbedtls12 but it is not installable
E: Unable to correct problems, you have held broken packages.
"

**Comment by Streammet** [comment]
My specs are:
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-13-amd64 
CPU: Intel N100 (4) @ 3.400GHz 
GPU: Intel Alder Lake-N [UHD Graphics]

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/issues/1666#issuecomment-1848444814

**Comment by Streammet** [comment]
@Paulchen-Panther but I dont use arm I use amd64.

**Comment by Lord-Grey** [comment]
The given background is applicable for all Bookworm packages incl. amd64.
Amd64 will be covered via the new repository,too.
