### ISSUE TITLE
Problem with Raspberry PI 5

### ISSUE THREAD

**Issue by lorenzobigazzi0** [hyperion-project/hyperion.ng#1670]
- [x] I confirm that this is an issue rather than a question.

## Bug report
OS not runing on raspberry PI 5 4gb model

#### Steps to reproduce
Flash the SD card with the OS, it will not boot

#### What is expected?
OS boot

#### What is actually happening?
Nothing

**Comment by Paulchen-Panther** [comment]
Are we talking about HyperBian? If so, the problem will be solved with the next release.
