### ISSUE TITLE
Windows --service option doesn't work

### ISSUE THREAD

**Issue by VuYeK** [hyperion-project/hyperion.ng#1671]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When I try to start Hyperion on Windows in service only mode it automatically closes after 2sec.
![Log](https://github.com/hyperion-project/hyperion.ng/assets/11438364/251f3d40-880f-4307-adf3-d65a010e05e6)

#### Steps to reproduce
```hyperiond.exe --service -c -d```

#### What is expected?
Hyperion working as hidden process without tray icon.

#### What is actually happening?
Application crashes because of 

> QWidget: Cannot create a QWidget without QApplication

#### System
Windows 11 23H2
```
Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 14:48:39
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           pl (BrowserLang: pl-PL)
- UI Access:         default
- Avail Screen Cap.: qt,dx
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       C:/Users/XXX/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Windows 10 Version 2009
- Architecture:      x86_64
- Kernel:            winnt (10.0.22631 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.11.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
```

**Comment by Paulchen-Panther** [comment]
The --service argument is currently only available for Linux. Obviously the operating system specific section to exclude this for Windows is missing.
You can have Hyperion written to the autostart during installation or via the SysTray icon entry.

**Comment by Lord-Grey** [comment]
@VuYeK The issue has been fixed...

Would you mind testing, if the fix works for you?
You can download a test version in the latest PR Build
https://github.com/hyperion-project/hyperion.ng/actions/runs/7349642378?pr=1672

@bobstardelux It would be great, if you could test the PR too, 
Checking that Remote Desktop work well, if "Listen to lock events" is disabled.
See https://github.com/hyperion-project/hyperion.ng/pull/1653 how to disable the Lock events.

**Comment by VuYeK** [comment]
Hello @Lord-Grey, thanks for fix - it is working perfect! :D

**Comment by Lord-Grey** [comment]
@VuYeK Thanks for testing. Much apprechaited!
