### ISSUE TITLE
Color calibration via Kodi doesn't work

### ISSUE THREAD

**Issue by kuba-orlik** [hyperion-project/hyperion.ng#1674]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. Run Hyperion
2. Start the color calibration wizard
3. Enter the IP address of the Kodi instance

#### What is expected?

It should connect and start the wizard

#### What is actually happening?

A "test success - time to proceed!" message is displayed in the Kodi interface, but Hyperion says "Kodi not found, proceed without Kodi support (please check, if remote control by other systems is activated)."

#### System
Hyperion Server:
- Build:             master (Hyperion-Bot-5ec7849a/2aa0d01d-1702152598)
- Build time:        Dec 27 2023 17:26:32
- Git Remote:        /var/cache/private/yay/hyperion.ng-git/hyperion.ng
- Version:           2.0.16-beta.1
- UI Lang:           en (BrowserLang: pl)
- UI Access:         expert
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Arch Linux
- Architecture:      x86_64
- CPU Model:         11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
- CPU Type:          140
- Kernel:            linux (6.6.8-arch1-1 (WS: 64))
- Root/Admin:        true
- Qt Version:        6.6.1
- Python Version:    3.11.6
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0

**Comment by Lord-Grey** [comment]
Which Kodi Version have you tested with?
Have you ensured that „remote control by other systems is activated)" in Kodi?

**Comment by kuba-orlik** [comment]
I've tested this with `Kodi Media Center 20.2 (20.2.0)`. I've triple-checked that "remote control by other systems" is activated in Kodi

**Comment by Lord-Grey** [comment]
Hi 

can you check, if there are any difference in your configuration scree to the one below?

![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/12621de7-fabb-45e2-a32d-6c53365483fa)

I just tested with LibreElec 11 and CoreElec 20 and both worked....

**Comment by Lord-Grey** [comment]
Closing as no feedback

**Comment by kuba-orlik** [comment]
Apologies for the delay. Yes, I can confirm the settings look like what you've shown:

![IMG_20240116_174832](https://github.com/hyperion-project/hyperion.ng/assets/2697916/bc59bac3-032c-426a-957a-5d53590b9af6)


https://github.com/hyperion-project/hyperion.ng/assets/2697916/7106c1f6-fb6a-4b24-b2a6-b142b16e2936

**Comment by kuba-orlik** [comment]
Ok, here are the results:

![image](https://github.com/hyperion-project/hyperion.ng/assets/2697916/94a7ff6c-8bc2-4c15-8a94-3780d5d9520d)


```json
{"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"Colour calibration wizard","message":"Test success - time to proceed!","image":"info","displaytime":5000},"id":"1"}
```

```json
{"id":"1","jsonrpc":"2.0","result":"OK"}
```

```
Connection closed: 1006
```

The JS console shows a warning:

```
The connection to ws://192.168.1.90:9090/jsonrpc/websocket was interrupted while the page was loading. [wizard.js:235:14](http://192.168.1.90:8090/js/wizard.js)
```

The line mentioned in the warning is 

```js
var ws = new WebSocket(kodiUrl);
```

**Comment by kuba-orlik** [comment]
It seems that the `cb` callback is sometimes called twice in the `sendToKodi` function - first with success, and then with error. It seems that closing the websocket triggers the `.onerror` handler. I think in this case it'll be useful to only call `cb` once. I'll draft a PR

**Comment by Lord-Grey** [comment]
Hi @kuba-orlik
I reworked the Kodi Wizzard that a websocket is maintained during one Kalibration session.
Would you mind testing PR #1718, if it works for you?

PS: In case you would like to test the PR without building yourself, you can test the re-build artifacts following the
[Testing Pull Requests documentation](https://docs.hyperion-project.org/en/user/advanced/Testing.html#pull-requests).

**Comment by kuba-orlik** [comment]
Sorry I didn't manage to test it in time - thank you for addressing the issue! <3
