### ISSUE TITLE
Can't update to 2.0.16 on Raspberry Pi 3B

### ISSUE THREAD

**Issue by camilloaddis** [hyperion-project/hyperion.ng#1684]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The system doesn't update to v2.0.16

#### Steps to reproduce
1. ssh into the pi
2. update apt-get via sudo apt-get update
3. update hyperion via sudo apt-get install hyperion

#### What is expected?
The system should update to the newest version (2.0.16)

#### What is actually happening?
The output is hyperion is already the newest version (2.0.15~bullseye) and the system doesn't update.

#### System

Hyperion Server:

Build: ()
Build time: May 19 2023 17:58:09
Git Remote:
Version: 2.0.15
UI Lang: it (BrowserLang: it-IT)
UI Access: expert
Avail Screen Cap.: dispmanx,framebuffer,qt
Avail Video Cap.: v4l2
Avail Audio Cap.: audio
Avail Services: boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
Config path: /home/pi/.hyperion
Database: read/write
Hyperion Server OS:

Distribution: Raspbian GNU/Linux 11 (bullseye)
Architecture: arm
CPU Model: ARMv7 Processor rev 4 (v7l)
CPU Type: Raspberry Pi 3 Model B Rev 1.2
CPU Revision: a02082
CPU Hardware: BCM2835
Kernel: linux (6.1.21-v7+ (WS: 32))
Root/Admin: false
Qt Version: 5.15.2
Python Version: 3.9.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by modem7** [comment]
Getting the same in an LXC container on Jammy. 

For now, I've grabbed the latest release and installed manually from the local file.

**Comment by Paulchen-Panther** [comment]
Please be patient a little longer. The redirection to the new repo will be made up for later. You can of course simply switch to the new repo at any time.
https://releases.hyperion-project.org

**Comment by Lord-Grey** [comment]
Redirection is in place, now.

You can do the version upgrade via
`sudo apt-get update --allow-releaseinfo-change`
`sudo apt upgrade`

Alternatively, use the commands @Paulchen-Panther suggested or 
use the new easy-install script:

Remove current version
`curl -sSL https://releases.hyperion-project.org/install | bash -s -- -remove`
Install latest version
`curl -sSL https://releases.hyperion-project.org/install | bash`

**Comment by camilloaddis** [comment]
Thanks, worked flawlessly!
