### ISSUE TITLE
Easy install fails on rpi zero

### ISSUE THREAD

**Issue by Vader699** [hyperion-project/hyperion.ng#1685]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When running the command
```
wget -qO- https://apt.hyperion-project.org/hyperion.pub.key | sudo gpg --dearmor -o /usr/share/keyrings/hyperion.pub.gpg
```
it returns gpg: no valid OpenPGP data found.

I ran just 
```
wget -O- https://apt.hyperion-project.org/hyperion.pub.key 
--2024-01-21 03:29:48--  https://apt.hyperion-project.org/hyperion.pub.key
Resolving apt.hyperion-project.org (apt.hyperion-project.org)... 188.68.47.21, 2a03:4000:30:d387::15:5027
Connecting to apt.hyperion-project.org (apt.hyperion-project.org)|188.68.47.21|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://apt.releases.hyperion-project.org/hyperion.pub.key [following]
--2024-01-21 03:29:49--  https://apt.releases.hyperion-project.org/hyperion.pub.key
Resolving apt.releases.hyperion-project.org (apt.releases.hyperion-project.org)... 188.68.47.21, 2a03:4000:30:d387::15:5027
Connecting to apt.releases.hyperion-project.org (apt.releases.hyperion-project.org)|188.68.47.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-21 03:29:50 ERROR 404: Not Found.
```

I tried this on multiple different machines and had a friend run it on a different network and he got the same.  

#### Steps to reproduce
See above

#### What is expected?
To get the gpg key for the repository

#### What is actually happening?
Key is returning 404.

**Comment by Vader699** [comment]
Must have been a temporary issue. It has started working for me now.

**Comment by Lord-Grey** [comment]
Sorry for the inconvenience.
We moved to a new repository URL and the redirection was missing. It should work now.

Nevertheless, I would recommend you install Hyperion via the new repository and not use the legacy URL.
Just follow the updated [instructions](https://releases.hyperion-project.org/).

**Comment by Vader699** [comment]
Thank you for your response.  I am trying to install on a PI zero v1 the install script errored saying it couldn't install on armv6 that wasn't supported.  I also tried Hyperbian but Hyperion wouldn't start.  So trying different ways.  Thank you for your work.

**Comment by Lord-Grey** [comment]
As the install script is new there might be still teething problems...
Could you run 
`curl -sSL https://releases.hyperion-project.org/install | bash -s -- -v`
and share the output, please?

**Comment by Vader699** [comment]
INFO : Identified distribution "raspbian"
DEBUG: Current architecture: armv6l
ERROR: Only armel, armhf, arm64, amd64 architecture(s) are supported for raspbian. You are running on armv6l

**Comment by Lord-Grey** [comment]
I found an issue in the script...

Could you run
curl -sSL https://releases.hyperion-project.org/install | bash -s -- -v
again and share the output, please?

**Comment by Vader699** [comment]
```
INFO : Identified distribution "raspbian"
DEBUG: Current architecture: armv6l
ERROR: Only armel, armhf, arm64, amd64 architecture(s) are supported for raspbian. You are running on armv6l
```

Same output.  Guessing we are still waiting on the armv6 builds to finish.

**Comment by Lord-Grey** [comment]
Unfortunately, there is still a problem with the script.
I will have a look into it.

could you execute in the meantime
`curl -sSL https://releases.hyperion-project.org/install | bash -x -s -- -v`

Than I see how a rpi zero react (as I do not have one at hand).
Thank you!

**Comment by Vader699** [comment]
Will do but it won't till I get home from work.  I tried again a few hours ago and got the same results as before.

**Comment by Lord-Grey** [comment]
@Vader699 You can retry the script. We fixed it.

**Comment by Vader699** [comment]
Just tried 
``` curl -sSL https://releases.hyperion-project.org/install | bash -x -s -- -v ```
And it worked just fine.  Everything appears to have been installed correctly and is running now.
