### ISSUE TITLE
Matrix Layout (LED Wall) Advanced Settings Custom Corner Definition/Location to create Ambient Expansion Displays

### ISSUE THREAD

**Issue by W2APS** [hyperion-project/hyperion.ng#1696]
#### What problem does this feature solve?
Using a Matrix Layout (LED Wall) that does not cover/display the entire captured video source.
Partially connected to https://github.com/hyperion-project/hyperion.ng/issues/1144

#### What does the proposed API look like?
It's a frontend-only change.

#### How should this be implemented in your opinion?
Much like the the Advanced Settings available for Classic Layout (LED Frame) LED Output instances where the position of each corner can be set relative to the captured video source, I would like this ability to be available for Matrix Layout (LED Wall) LED Output instances.
My use situation is as follows.  Based around a home cinema/theater system with a large direct view (QLED/OLED) display 77" diagonal or front projection system. I am looking to have LED displays either side of the main screen (either on the same front wall or side walls) and on the ceiling.  These would match the height (if on the side) or width (if above/ceiling) of the main screen and then extend 0.5m+ outwards.  They only need to display 5-10% of the corresponding side of the captured video source and stretch it across the matrix to expand the display into and around the room.

I can achieve the result I need for a single Matrix Layout Instance by using the Crop tools on the Capture setup page.  For example cropping 90-95% Left or 90-95% Right.  However as this affects the Capture source for all instances it is limited to one use.

Such commercial level systems can be seen here:
https://www.lightwalls.co.uk/led-video/
https://arled-cinema.de/en/movie-core-2/

#### Are you willing to work on this yourself?
I have no useful coding ability but am able to beta test.

**Comment by Lord-Grey** [comment]
Hi

is this what you are looking for?
Samples for illustration:

![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/7faed0c7-6618-4913-a604-8ebef11a3a58)

![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/0c4b7fc6-ee4d-47d0-a337-bba6e4b6e386)

![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/89088a04-b3d8-4afd-9abe-da931d294721)

**Comment by W2APS** [comment]
Yes! That looks spot on!
