### ISSUE TITLE
Not working in fedora

### ISSUE THREAD

**Issue by arnavnayak** [hyperion-project/hyperion.ng#1704]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
after installing we see the icon 
on clicking on the icon of hyperion it doesnt open in fedora systems

#### What is expected?
after isntallation , after clicking on the icon expecting it should open the application

#### What is actually happening?
rather than opening the application on click of the hyperion icon in fedora it does not open

#### System

![image](https://github.com/hyperion-project/hyperion.ng/assets/20569794/628b5360-337d-45d8-b17a-3463133a6c29)

**Comment by Paulchen-Panther** [comment]
Can you start hyperion from the console?
`hyperiond -d`

**Comment by Paulchen-Panther** [comment]
Closed because no feedback
