### ISSUE TITLE
postinstall needs smarter config.txt updating

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#1708]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I'm not sure the postinstall should be blindly updating config.txt
```
--- Hyperion ambient light postinstall ---
---> Raspberry Pi found, but SPI is not set, we write "dtparam=spi=on" to /boot/
config.txt
```
In my case with osmc, the check and change should be done in config.txt

#### Steps to reproduce
apt install or upgrade hyperion.ng from the repository

#### What is expected?
I already have dtparam=spi=on enabled in config-user.txt, dont add it to config.txt

perhaps change the detection logic to check for /dev/spidev and if present skip adding it (to the wrong file)

#### What is actually happening?
see above :)

#### System

PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="February 2024"
VERSION_ID="2024.02-1"

 hyperion 2.0.16~bullseye

**Comment by Lord-Grey** [comment]
@penfold42 Thank you for the feedback.
We are going to remove the update frontage package installation and have the documentation elaborated.

btw. Does OSCM provide the raspi-config command?
Would following command work:
`sudo raspi-config nonint do_spi 1`

**Comment by penfold42** [comment]
nope! they've replaced it with a message :)

```
penfold@loungepi:~$ raspi-config

It looks like you're familiar with Raspbian, or following a Raspbian tutorial.

OSMC is a media center operating system, and as such, we do things a little differently.

You should find all the options to configure your Raspberry Pi under My OSMC. If anything is
missing or you have any questions, let us know at https://discourse.osmc.tv

```

**Comment by Lord-Grey** [comment]
SPI Documentation was updated too

https://docs.hyperion-project.org/en/user/leddevices/#spi-prerequisites-controller-type-group-rpi-spi
