### ISSUE TITLE
German translation error in web GUI Capturing Hardware -> "Software frame skipping"

### ISSUE THREAD

**Issue by bwenner** [hyperion-project/hyperion.ng#1721]
[X] I confirm that this is an issue rather than a question.

## Bug report
The describing text "To save resources every n'th frame will be processed only. For ex. if grabber is set to 30fps with this option set to 5 the final result will be around 6fps" was translated incorrectly.

It says: "Jeder n-te Frame wird übersprungen um Ressourcen zu sparen. Beispiel: Ein Wert von 5 resultiert bei einem Aufnahmegerät mit 30fps in einer neuen Framerate von 6 fps."

#### Steps to reproduce
Open web GUI http://w.x.y.z:8090/#conf_grabber, switch to german language, and scroll to description "Überspringen von Frames"

#### What is expected?
This translation would be correct:
"Jeder n-te Frame wird berücksichtigt um Ressourcen zu sparen. Beispiel: Ein Wert von 5 resultiert bei einem Aufnahmegerät mit 30fps in einer neuen Framerate von 6 fps."

The key word is "berücksichtigt/bearbeitet" (=processed) instead of "übersprungen* (=skipped)

#### What is actually happening?
Wrong text is displayed

#### System
Hyperion Server:
- Build:             (HEAD detached at a93d79b) (Paulchen-Panther-cb85d2d/a93d79b-1705568419)
- Build time:        Jan 28 2024 10:21:59
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.16
- UI Lang:           de (BrowserLang: de)
- UI Access:         expert
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /root/.hyperion
- Database:          read/write
- Mode:              Non-GUI

Hyperion Server OS:
- Distribution:      Debian GNU/Linux 12 (bookworm)
- Architecture:      arm64
- CPU Type:          Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:      a020d3
- Kernel:            linux (6.1.0-rpi8-rpi-v8 (WS: 64))
- Root/Admin:        true
- Qt Version:        6.4.2
- Python Version:    3.11.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
Thanks for sharing the translation error.

I fixed this as:
„Um Ressourcen zu sparen, wird nur jedes n-te Bild verarbeitet. Wenn z.B. der Grabber auf 30fps eingestellt ist und diese Option auf 5 gesetzt ist, wird das Endergebnis ca. 6fps sein.“

Note: via [POEditor](https://poeditor.com/join/project/Y4F6vHRFjA) everybody can provide or update translations online.
We will integrate latest translations provided from time to time into the builds.
