### ISSUE TITLE
Error while installing hyperion

### ISSUE THREAD

**Issue by paradox-sp** [hyperion-project/hyperion.ng#1732]
- [x] I confirm that this is an issue rather than a question.

## Bug report
![image](https://github.com/hyperion-project/hyperion.ng/assets/59829282/4af8a6c0-b314-405e-b75b-322aa2118815)

**Comment by Paulchen-Panther** [comment]
Without a few lines of text from where you installed Hyperion, into which target directory, which OS etc. no one will be able to help you.

**Comment by Thinner77** [comment]
Hi,

IMHO this is related to NSIS installer, see https://github.com/hyperion-project/hyperion.ng/blob/94850d890a152ce999289bb5b5ec3d44899abbd2/cmake/nsis/template/NSIS.template.in#L223

It has a length limit of 1024 chars. Your current Windows PATH environment variable is too long for the installer.
See https://github.com/SWI-Prolog/swipl-devel/issues/450
and https://github.com/PointCloudLibrary/pcl/issues/5001

Simple solution is to add it manually. As i don't use Windows i can't tell you what to add, maybe @Paulchen-Panther can help out.
wbr

**Comment by Lord-Grey** [comment]
Not a Hyperion issue
