### ISSUE TITLE
libturbojpeg is not installable

### ISSUE THREAD

**Issue by kylewhirl** [hyperion-project/hyperion.ng#1733]
- [x] I confirm that this is an issue rather than a question.

## Bug report
tried installing hyperion a few times now, and i always end up with the same error 
``` The following packages have unmet dependencies:
 hyperion : Depends: libturbojpeg but it is not installable
E: Unable to correct problems, you have held broken packages.
```

#### Steps to reproduce
Follow install steps for Hyperion on raspberry pi 64 bit lite os

#### What is expected?
Install of libturbojpeg package 

#### What is actually happening?
Cannot install libturbojpeg package because it doesn't exist, there exists a libturbojpeg0 package though

**Comment by Paulchen-Panther** [comment]
Can you tell us which hardware or OS you want to install Hyperion on? Greetings Paulchen

**Comment by Lord-Grey** [comment]
Closing as no feedback
