### ISSUE TITLE
QT-Grabber: Pixeldecimation ignored

### ISSUE THREAD

**Issue by Thinner77** [hyperion-project/hyperion.ng#1751]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Hi,

maybe i'm doing something wrong or missing some informations, but it looks like pixeldecimation is not working in QT grabber.
It's set to 1 in WebGUI but default of 8 is used.

![grafik](https://github.com/hyperion-project/hyperion.ng/assets/59623671/a84fe907-0956-47b6-a3a4-03ed8718dcc2)
![grafik](https://github.com/hyperion-project/hyperion.ng/assets/59623671/cf95d6b2-e2ed-4024-918f-56c8d7984df7)

#### Steps to reproduce

Windows 10, hyperion.ng build from current master branch, start hyperion-qt.exe, start hyperiond.exe, open WebUI, enable Screen Capture, set pixeldecication=1, save config, restart hyperion-qt.exe, restart hyperiond.exe.

**Comment by Lord-Grey** [comment]
Hi @Thinner77 

It might be that you are confusing the "internal" screen capture (grabber) and the standalone grabber.

The Screenshot with the UI configuration is the internal grabber.
Independently from that there is a standalone grabber with on own executable: hyperion-qt.exe
That you have started via the command line.

The standalone grabber grabs the screen and send it to hyperion (local or remove) via flatbuffers.
As flatbuffer input has a higher priority, Hyperion uses that source and does not the the grabbed screen from the internal grabber.

You have started the standalone grabber with no options which will have a pixel decimation of 8.
You can have pixel decimation, executing with the following arguments
`hyperion-qt.exe --size-decimator 1`

Just do a `hyperion-qt.exe --help` to see all options.

The standalone grabber is handy, if you would have a remote Hyperion server, but would like to grab the windows screen.
If you running on the same box, using the internal grabber is recommended.

You might have seen the new Windows DDA grabber, which brings more capture performance.

Hoping that clarifies....

**Comment by Thinner77** [comment]
Hi @Lord-Grey,

thank you for this detailed clarification. I tried the internal QT grabber yesterday, but then only had an orange image in the preview.
That's why I thought I had to start the external QT grabber. I just tried it again with the internal one, it works. Please excuse the circumstances. I only use Windows to test whether everything still compiles and runs when I make changes to the code. That's why I'm not very knowledgeable about it yet, but I'm learning.

wbr

**Comment by Paulchen-Panther** [comment]
> Hi @Lord-Grey,
> 
> thank you for this detailed clarification. I tried the internal QT grabber yesterday, but then only had an orange image in the preview. That's why I thought I had to start the external QT grabber. I just tried it again with the internal one, it works. Please excuse the circumstances. I only use Windows to test whether everything still compiles and runs when I make changes to the code. That's why I'm not very knowledgeable about it yet, but I'm learning.
> 
> wbr

The orange picture could still come from the external grabber (DroidCam).
