### ISSUE TITLE
USB grabber crashes after changing the TV sources multiple times

### ISSUE THREAD

**Issue by newkind** [hyperion-project/hyperion.ng#1759]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I have installed Hyperion.ng on a Orange Pi Zero 3 and its working very nicely, but I seem to have an issue with USB grabber. I'm using only USB grabber and every couple days when I switch the input sources from the devices connected to the grabber to ie. applications built into TV something crashes the grabber and the only way to get it back running is to reboot the whole device.

I have tried two different USB grabbers based on different chipset and form factor (one is based on MS2130).

What I can see in Hyperion.ng log is this:

```
< ----- Current Log --------------------------- >
2024-06-21T16:40:51.899Z [V4L2] (ERROR) Throws error nr: VIDIOC_DQBUF error code 19, No such device
2024-06-21T16:40:51.900Z [V4L2] (ERROR) VIDIOC_STREAMOFF  error code  19, No such device
2024-06-21T16:40:51.915Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'adalight' signals error: 'Error writing data to ttyACM0, Error: 6'
2024-06-21T16:40:51.963Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'adalight' signals error: 'Invalid serial device: ttyACM0 !'
```

Full log can be found here: https://pastebin.com/raw/GAD5xgSm

I tried checking `journalctl` when it happened but there's nothing there: https://pastebin.com/raw/Y2TYsJCB

Any help would be appreciated! 

EDIT: I have enabled the Debug log level in Hyperion for the next couple days and I'll update this issue when it crashes again and there will be hopefully more stuff in the log.

Thank you!

#### Steps to reproduce
Switching between multiple sources on my TV - from the ones that are being handled by the usb grabber to the built-in the TV (not covered by Hyperion) crashes the USB grabber.

#### What is expected?
Grabber doesn't crash

#### What is actually happening?
Grabber crashes and I need to reboot the whole device

**Comment by Lord-Grey** [comment]
Hi @newkind Looking at the log, it seems that all USB devices are disconnected by the operating system at the same time.
This is not an Hyperion issue. Hyperion just looses the access to those devices, because they are not available any longer.

I suggest you check, what might be causing this on the OS level.
Maybe a power issue?
