### ISSUE TITLE
Missing Python3 dependencies with Ubuntu 24.04

### ISSUE THREAD

**Issue by Merisal** [hyperion-project/hyperion.ng#1767]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After the installation was successful, following the instructions at https://releases.hyperion-project.org/ I tried to start Hyperion from Startmenu. After this didn't work I tried it via console without success.
The message says that there is a missing python3 dependency.
`hyperiond: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory`

Using the deb file from release page worked fine.

#### Steps to reproduce
Follow instructions at https://releases.hyperion-project.org/
Try to start Hyperion from Start menu or console 

#### What is expected?
Hyperion is running in background and lights are working properly

#### What is actually happening?
Nothing while using shortcut at start menu.
Getting an error with unmet python dependencies.

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.16) (Paulchen-Panther-cb85d2d/a93d79b-1705568419)
- Build time:        Jan 18 2024 09:11:31
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.16
- UI Lang:           de (BrowserLang: de-DE)
- UI Access:         default
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/merisal/.hyperion
- Database:          read/write
- Mode:              GUI

Hyperion Server OS:
- Distribution:      Ubuntu 24.04 LTS
- Architecture:      x86_64
- CPU Model:         AMD Ryzen 7 7700X 8-Core Processor
- CPU Type:          97
- Kernel:            linux (6.8.0-39-generic (WS: 64))
- Root/Admin:        false
- Qt Version:        5.11.3
- Python Version:    3.7.3
- Browser:           Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Can you tell me your current installed Python version?
Greetings Paulchen

**Comment by Merisal** [comment]
I made a fresh install of Kubuntu 24.04 two days ago and the version is
`python3 --version
Python 3.12.3
`

**Comment by Paulchen-Panther** [comment]
I have updated the Ubuntu 24.04 builds (amd64/arm64/armhf) on the APT server. Could you try to install it again?

**Comment by Merisal** [comment]
> ~I have updated the Ubuntu 24.04 builds (amd64/arm64/armhf) on the APT server. Could you try to install it again?~ edit: I just saw that the creation of the Debian packages contains a dependency (qt5/6) error. I will look into this again tomorrow. I'll get back to you.

Thanks. Didn't read your update to your post and ran into the same qt error :smile:

**Comment by Paulchen-Panther** [comment]
The problem should now be solved.

**Comment by Merisal** [comment]
Installation works now, thanks.
