### ISSUE TITLE
Links to documentation (Install, config etc) broken on GitHub page.

### ISSUE THREAD

**Issue by austwhite** [hyperion-project/hyperion.ng#1772]
Not related to Hyperion NG itself

The links to Install, Config etc in the Readme on the GitHub page all give 404 error
- [x] I confirm that this is an issue rather than a question.
Not an issue with the application, just with documentation links
   I have a need to reinstall HyperionNG after several years of use (SD Card failure) and I found I could not get to the links for instructions.

**Comment by Paulchen-Panther** [comment]
But the documentation button works. :)
Unfortunately we missed to adapt the README when we revised the documentation. Sorry.
Maybe you can create a PR for us? ;)

Here are the links:

- [Installation](https://docs.hyperion-project.org/user/GettingStarted.html)
- [Configuration](https://docs.hyperion-project.org/user/Configuration.html)
- [Effect development](https://docs.hyperion-project.org/effects/Effects.html)
- [JSON API](https://docs.hyperion-project.org/json/JSON.html)

Thank you very much.
Greetings Paulchen

**Comment by Lord-Grey** [comment]
Fixed by #1779 and #1780
