### ISSUE TITLE
No service running on Raspberry pi zero

### ISSUE THREAD

**Issue by Toasterme** [hyperion-project/hyperion.ng#1784]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When i install using the script on raspberry pi zero W,  there is no service created, no hyperion.config.json created and no directory /etc/hyperion

#### Steps to reproduce
https://releases.hyperion-project.org/
curl -sSL https://releases.hyperion-project.org/install | bash

#### What is expected?
Have the service running and port listening

#### What is actually happening?
 ls -al /etc/hyperion/
ls: cannot access '/etc/hyperion/': No such file or directory

sudo systemctl status hyperion
Unit hyperion.service could not be found.

$ ls -al  /usr/share/hyperion/
total 44
drwxr-xr-x   7 root root  4096 Aug 18 15:50 .
drwxr-xr-x 118 root root  4096 Aug 18 13:19 ..
drwxr-xr-x   2 root root  4096 Aug 18 15:50 bin
drwxr-xr-x   2 root root  4096 Aug 18 15:50 effects
drwxr-xr-x   6 root root 20480 Aug 18 15:50 lib
drwxr-xr-x   2 root root  4096 Aug 18 15:50 scripts
drwxr-xr-x   2 root root  4096 Aug 18 15:50 service

$ ls /etc/systemd/system
bluetooth.target.wants                      dbus-org.freedesktop.timesync1.service  halt.target.wants            sockets.target.wants
dbus-fi.w1.wpa_supplicant1.service          default.target                          multi-user.target.wants      sshd.service
dbus-org.bluez.service                      dev-serial1.device.wants                network-online.target.wants  sysinit.target.wants
dbus-org.freedesktop.Avahi.service          getty.target.wants                      poweroff.target.wants        timers.target.wants
dbus-org.freedesktop.ModemManager1.service  getty@tty1.service.d                    reboot.target.wants
dbus-org.freedesktop.nm-dispatcher.service  graphical.target.wants                  remote-fs.target.wants

Here's the complete installating log : 
https://pastebin.com/8kNQRwGB

One last thing i did fix is the :
Raspberry Pi found, but SPI is not set, we write "dtparam=spi=on" to /boot/config.txt
But it is no longer /boot/config.txt that file change to /boot/firmware/config.txt

**Comment by Paulchen-Panther** [comment]
> You can start Hyperion from your menu now

**Comment by Toasterme** [comment]
> > You can start Hyperion from your menu now

I’m using raspberry is lite , so no GUI

**Comment by Toasterme** [comment]
Thank you, installed the service like you documented.  I still don't understand why it did install a lot of package regarding X11 library , qt, gtk.  I did connect with MobaXterm using defaut config so maybe it pretend to use as a source for X11 ?  Because it does create an X11 server by default, maybe that is why... Have a good day.
