### ISSUE TITLE
[GA] Release cycle and nightly builds

### ISSUE THREAD

**Issue by storm1er** [hyperion-project/hyperion.ng#1788]
## Feature request

- As a non-tech user I would like to know when the next release will be
- As a non-tech user I would like to test PR builds easily

#### What problem does this feature solve?

A big feature (to me) has been released (home assistant connectivity, any light of the house, yay) and there is no way to test it unless I wait for the next release (Unable to know when it will be) or I build the project myself, which not everyone can do.

#### What does the proposed API look like?

Not related

#### How should this be implemented in your opinion?

- As a user I would like to know when the next release will be:
  - Write the release cycle of the project in the readme or in a doc page

- As a user I would like to test PR builds
  - Github action downloads link are hard to find, maybe add a bot to add those links to PR's comments (with expiry if there is any)?

#### Are you willing to work on this yourself?

No: I don't know the release cycle (is it automated btw?) and I'm using gitlab CI/CD, so I'll be slow to update github's actions/workflow files

**Comment by Paulchen-Panther** [comment]
Nightly builds can be obtained from the repository page. 
https://releases.hyperion-project.org

You can recognize PR build on the Actions page.

![image](https://github.com/user-attachments/assets/54ab5780-686b-4289-a9e9-cce792f4270a)

**Comment by Lord-Grey** [comment]
Just in addition...

To test a dedicated PR follow the documentation:
https://docs.hyperion-project.org/user/advanced/Testing.html#pull-requests


> As a user I would like to know when the next release will be:
> Write the release cycle of the project in the readme or in a doc page

Given that we are a small team doing development voluntarily, there is no fixed release cycle.
Whenever there is a consistent state that we think is beneficial for a wider community and is reasonable spending the effort doing a release, we do so.
it is likely we still do a release this year, but no ETA yet.
