### ISSUE TITLE
wrong resolution discovered by hyperion

### ISSUE THREAD

**Issue by expresik** [hyperion-project/hyperion.ng#1791]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion shows wrong resolution for grabbers other than framebuffer - it means X11 and XCB
It worked correctly through years, including updates os Libreelec and hyperion and now -failed.
Today, after I've observed issue, I updated libreelec to 12.0.0.1 and Hyperion - to 2.0.16 - no effect.
Some screenshots here.
This what I can see (and its not expected)
![Image](https://github.com/user-attachments/assets/a1e08651-7320-40be-9142-44844d9c0ebd)

This is effect seen on hyperion side.
![Image](https://github.com/user-attachments/assets/dc09c9a2-3ea9-4f34-aaf8-0216d6817138)

In real world only part of my leds work, the most pf them is located next to black areas of display, so - they do nothing. However I can watch my videos on entire screen.

#### Steps to reproduce

Just try to set correct resolution for my device - it is fixed on wrong values.

#### What is expected?

Hyperion should read correct values of resolution and/or should let me set it manually.
The correct values are 1360x768

#### What is actually happening?

This is stable situation - but still wrong.
I've tried to:
- export settings,
- change width/height values for framegrabber to correct ones
- import settings back
- restart hyperion and reboot OS 
No effect, however when I exported settings once again, I can see there correct, expected values. Hyperion GUI still shows 3280x1080 and work with it.

#### System

Hyperion 2.0.16 (same on 2.0.15)
OS: Libreelec: 12.0.1 (same on 12.0.0)
Kernel: Linux 6.6.46
Hardware: Dell Wyse 5060 with Radeon R5E and two Displayports. Due to Dell websites it does not support 3280x1080 resolution or double 1640x1080 [https://www.dell.com/support/manuals/pl-pl/wyse-5040/thinos_8.5_ag/configuring-the-general-display-settings?guid=guid-e6986f35-28c2-459b-89f2-b75bf66891dd&lang=en-us](https://www.dell.com/support/manuals/pl-pl/wyse-5040/thinos_8.5_ag/configuring-the-general-display-settings?guid=guid-e6986f35-28c2-459b-89f2-b75bf66891dd&lang=en-us)

**Comment by Lord-Grey** [comment]
What LibreElec variant did you install?
Capturing via X11 normally requires **Legacy** Generic PC (for older PCs and NVIDIA GPUs).

Framegrabber is not a capture option any longer, since LibreElec changed their window manger with Matrix (v 10)

**Comment by expresik** [comment]
This is Legacy Generic variant - it was the only way to have hyperion running. I've installed version 11 more than year ago and it worked well till now, also through online updates.

**Comment by Lord-Grey** [comment]
This the following something that could be relevant for you?

https://forum.libreelec.tv/thread/28485-how-to-automatically-change-resolution-after-switching-tvs/

As it kicked in when switching versions and Hyperion is using data presented from the OS, I would assume it is related to LibreElec.
If you cannot resolve, I would suggest you check with the LibreElec forum.

**Comment by expresik** [comment]
Issue didn't start after update. I tried to update LE and Hyperion when observed the issue, with hope that it will solve problem. Issue started just like that with unknown reason.
But: there is no issue between LE and TV. It shows the same all the time (1360x768) and works perfectly with TV. The only part of system which fails is hyperion.
Of course I can ask on LE forum, but - is there a way to force resolution on hyperion side?

**Comment by expresik** [comment]
I've  found it!
The issue is outside of hyperion, kodi and libreelec. It's closer to hardware, some kind of hung up.

I completely forgot about one thing: few month ago I've connected HDMI wireless transmitter (with converter of course) to the second DisplayPort. From time to time I use FullHD projector with it.
So starting from this July I had:
- DP1 with 1360x768 TV
- DP2 with 1920x1080 transmitter

This worked great till now and without any reason - failed. With completely no action performed, including any connections or turning projector on/off.
I've checked:
# xrandr
Screen 0: minimum 320 x 200, **current 3280 x 1080**, maximum 16384 x 16384
DisplayPort-0 connected **primary** **1360x768+0+0** (normal left inverted right x axis y axis) 1600mm x 900mm
   1360x768      60.02*+
[...]
DisplayPort-1 connected **1920x1080+1360+0** (normal left inverted right x axis y axis) 708mm x 398mm
   1920x1080     60.00*+  50.00    59.94    30.00    24.00    29.97    23.98  
[...]

Looks like Screen 0 changed its primary display.
Now just disconnected transmitter and connected back and looks that DP-1 does not determine final resolution. I can see: 

Screen 0: minimum 320 x 200, current **1360 x 768**, maximum 16384 x 16384
DisplayPort-0 connected **primary** **1360x768+0+0** (normal left inverted right x axis y axis) 1600mm x 900mm
   1360x768      60.02*+
[...]DisplayPort-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +  50.00    59.94    30.00    24.00    29.97    23.98  
   1920x1080i    50.00  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1360x768      60.02  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94 

None is marked by star "*".

Probably I could fix my issue using command:
xrandr --output DisplayPort-0 --primary
I'll check it next time...

**Comment by Lord-Grey** [comment]
Great that you identified the root cause of the issue!
