### ISSUE TITLE
WLED matrix layout of 64x64 is not saved

### ISSUE THREAD

**Issue by dosipod** [hyperion-project/hyperion.ng#1804]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I have smaller setups of 16x16 , 32x16 that seems to be working fine with Hyperion  . WLED  has expanded the supported number of leds as well as the led panels types , with hub75 being added , I am testing with a small 64x64 panel that works perfectly fine when used with internal effects as well as ddp streaming from xlights . WLED at that moment can work with around 128x128 

#### Steps to reproduce
Setup 64x64 matrix in Hyperion 

#### What is expected?
64x64 matrix layout to be saved 

#### What is actually happening?
error below and when streaming the output is only on half of the 64x64 and mirrored 
![Image](https://github.com/user-attachments/assets/18b2cc30-719c-4111-9a72-c2367c42d413)

**Comment by Lord-Grey** [comment]
@dosipod I removed the constraint of 50 LEDs per Matrix row and column.

Please note that a hight number of LEDs to be mapped might result in performance issues, as well as multiple UDP network packages to be transferred to WLED for one overall update.

To test PR #1805 please follow the guidance here: https://docs.hyperion-project.org/user/advanced/Testing.html#linux
Happy to get feedback on how a huge number of LEDs impact performance etc.

Thank you!

**Comment by dosipod** [comment]
Sure you would get feedback  as our aim is not to use the final result in practice  but rather testing as part of the development work for both WLED and other open source apps . I will be posting on the PR for the result and I hope the size limit is highlighted as we aim push that  so 64x64 is just a start and  performance issues does not matter as this is considered wip  and nothing is free of bugs .And please take your time with that but if a quick response is received to our questions then you would also received quick feedback while I so much aim to avoid false positive reporting .

Install works fine but  I am not able to run macOS_x64  nor macOS_x64_qt6  due to below error ( my tests are on old intel based  mac mini ) 
![Image](https://github.com/user-attachments/assets/16b40ed7-04c0-48a6-8873-afc016cbe289)

**Comment by Paulchen-Panther** [comment]
@dosipod 
I have updated the Runner image from GitHub to macOS 13. Now the image should also run under x64 (hopefully 😃).

[#1805](https://github.com/hyperion-project/hyperion.ng/actions/runs/12035993071)

**Comment by dosipod** [comment]
@Paulchen-Panther  Install seems fine as before .No popup error like before but  still  fails to run now with different error ( tested both q5 and q6) 
![Image](https://github.com/user-attachments/assets/2098363b-3ce7-40a3-a254-91a6fb611688)

I hope that is not a silly missing lib from my system as this is a test machine and any workaround even if dirty is okay to test

**Comment by Paulchen-Panther** [comment]
@dosipod  Could you please test again?

[#1805](https://github.com/hyperion-project/hyperion.ng/actions/runs/12097157689)

**Comment by dosipod** [comment]
@Paulchen-Panther There is no update for our old machine to   macOS 13   so this may technically work but I have no way to verify , maybe we could wait to see if apple would release an update or be a hero for the poor man 
![Image](https://github.com/user-attachments/assets/0f0e6375-8827-426d-8efe-ce07cd03f498)

**Comment by Paulchen-Panther** [comment]
Does the QT error message exist for both (Qt5/6) versions of Hyperion?

**Comment by dosipod** [comment]
@Paulchen-Panther  Seems  macOS_x64  build run correctly on macOS 12.7.6 and Hyperon is up and running  , I am yet to test with the 64x64 panel but will do so shortly and update the PR with result .Thank you for the quick response
