### ISSUE TITLE
The screen lock event don't work

### ISSUE THREAD

**Issue by Benvalue27** [hyperion-project/hyperion.ng#1810]
- [x] I confirm that this is an issue rather than a question.

## Bug report

The screen lock event don't work on my computer

#### What is expected?

That the leds turn off when the screen locked. 

#### What is actually happening?

I install the latest version of Hyperion 2.0.16 and with the all the options on operating system event checked, the leds stay on when the screen is locked. 

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.16) (Paulchen-Panther-cb85d2d/a93d79b-1705568419)
- Build time:        Jan 18 2024 09:18:44
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.16
- UI Lang:           fr (BrowserLang: fr-FR)
- UI Access:         expert
- Avail Screen Cap.: qt,dx
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       C:/Users/value/.hyperion
- Database:          read/write
- Mode:              GUI

Hyperion Server OS:
- Distribution:      Windows 10 Version 2009
- Architecture:      x86_64
- Kernel:            winnt (10.0.22631 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.12.1
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0

**Comment by Lord-Grey** [comment]
Do you lock the screen that you need to enter a password again or do you run a screensaver, i.e. the screen goes black after a while?
The later is not support.

**Comment by Benvalue27** [comment]
I use a screensaver, so it's not supported.  But I tried with a real lock screen, that need a password again, and it doesn't work either.

**Comment by Lord-Grey** [comment]
Would you mind sharing a debug log which’s includes a real lock (and wait some seconds) and authentication with password, please!

**Comment by Lord-Grey** [comment]
Any Logs to share?
I tried on Windows 11 with the latest Code and it worked without any problems.

**Comment by Benvalue27** [comment]
So sorry, I worked on a physic solution with a physical switch. So I didn't try again.
I will retry tomorrow and try to send the logs, but I'm not sure how to find them.

**Comment by Lord-Grey** [comment]
1. Go toSystem -  Log
2. Enable Debug logging

Restart Hyperion
Lock Screen

3. Copy log output and sahre it


![Image](https://github.com/user-attachments/assets/c977699c-c750-4c7b-8744-91dacad16d2e)

**Comment by Benvalue27** [comment]
Sorry again, with Christmas holiday I didn't have access to my computer.

It works now, I can't explain why because nothing changed, but it works. 
It even works with sleep mode, when my screen goes black in sleep mode the LEDs turn off. 

I don't know if you still need the logs. 
If you don't, you can close the issue.

**Comment by Lord-Grey** [comment]
@Benvalue27 Thanks for coming back. Good tho hear it is working now.
In case there will be further issues, please come back with additional log input.
