### ISSUE TITLE
Home Assistant Lights live preview on layout don't seem to work

### ISSUE THREAD

**Issue by ChrisOboe** [hyperion-project/hyperion.ng#1813]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Home Assistant lights don't work properly. I am able to configure the home assistant lights. When i press the identify button the light turns on. 
~~Besides that it doesn't seem to update with the screen content.~~ Updating just startet to work. 

When i setup the layout and i enable live preview i get the following error message: "TypeError: event.response.result is undefined". 
I'm using the xcb screen grabber.
The global live preview in the top bar works fine. 
This only happens with home assistant lights.My wled lights work just fine. 

#### Steps to reproduce
Configure the xcb screen grabber 
Configure a home assistant light
Try to enable live preview in layout setup. 

#### What is expected?
1. That live preview works just like on e.g. wled lights
~~2. This is the main thing: that the led changes colors based on the screen content.~~

#### What is actually happening?
1. I get a error message as soon as i enable live preview on home-assistant lights layout configuration
~~2. The lights never update based on screen content. ~~

#### System
Hyperion Server:
- Build:              ()
- Build time:        Jan  1 1980 00:00:00
- Git Remote:        
- Version:           2.0.17-beta.2
- UI Lang:           de (BrowserLang: de)
- UI Access:         expert
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config database:   /home/gamer/.hyperion/db/hyperion.db
- Database:          read/write
- Mode:              GUI

Hyperion Server OS:
- Distribution:      NixOS 25.05 (Warbler)
- Architecture:      x86_64
- CPU Model:         AMD Ryzen 7 5800X3D 8-Core Processor
- CPU Type:          33
- Kernel:            linux (6.11.10-xanmod1 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.15
- Python Version:    3.12.7
- Browser:           Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0

I'm using a hyperion-ng build from this commit: 179ee316d029288cb1cc22a6ecc488fcaadd76e1
Since i'm building on a nixos system, some data like e.g. the build time gets stripped for reproducibility reaons. (I'm not sure what Build or Git Remote should contain normally).

**Comment by Lord-Grey** [comment]
Hi

I assume the UI pulls a JS set which is different from the build one.

Suggest  you update the "Document Root" pointing to the ".../asserts/webconfig directory where you did the build (see screenshot).

Then refresh the page and see, if it is working.

![Image](https://github.com/user-attachments/assets/4b0eeef4-e7dd-4b15-a2cc-cc09f047bcf9)

**Comment by Lord-Grey** [comment]
@ChrisOboe Thanks for reporting. I will have a look.

**Comment by Lord-Grey** [comment]
@ChrisOboe Fixed by #1814
