### ISSUE TITLE
Dynamic led count ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#194]
I don't know for fact that this will bite us, but i suspect some led devices store the numLeds at startup.

Do we need to make this truly dynamic or will we just destroy and instantiate the device if it changes ?

**Comment by redPanther** [comment]
to make it easy, reset ledcount in setConfig method. then it shouldn't harm ....

**Comment by redPanther** [comment]
I looked through all devices. When we reconfigure a device without destroying it, we have to call setConfig. Then all stored "numLeds" are set to current valid led count - so no problem here, issue can be closed

**Comment by penfold42** [comment]
Should we clean up the led drivers to do the config in their set config ?

It looks like the do it in ::write where they have easy access to the ledValues (and therefore their size)

Is there a clean way to access this from other methods ?

**Comment by redPanther** [comment]
doing in write is no problem, because it adapts dynamicly, when size of ledValues changes. Problem is some special led count value (e.g. in atmoorb) that value is not directly coresponding to amount of configured leds. But that access to those values are all in setconfig.

**Comment by penfold42** [comment]
Ideally I'd like to move some of the frame init stuff out of write and into setConfig.

It seems more logical to do it there and then we wouldn't have to check for array resizing on every write.

Do you think we can pass a ledcount, the led array or a reference to the Hyperion object into setConfig ?

**Comment by redPanther** [comment]
@penfold42 can we close this? LedDevices are in good shape now. changing of led count via webui forces a restart, so we don't need to be to dynamic

**Comment by penfold42** [comment]
yep
