### ISSUE TITLE
JSON RPC: current effect and current color

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#201]
@Paulchen-Panther 
Since the "initialEffect" array they show always(!) the value of "background-effect". Yes, this is a design problem now. How should we proceed?
Is it possible to blacklist priority (2147483646)? (As it is usually the same).

This means it would just show a color or effect that is set from a user and no longer from background-effect

**Comment by Paulchen-Panther** [comment]
Ja es ist möglich die niedrigste Priorität zu blocken.
hab auch noch mal den Vordergrundeffekt getestet. Die Dauer die in der config steht wird nicht mit berücksichtigt. Ist aber nur ein Schreibfehler.

**Comment by brindosch** [comment]
Nein, nur diese :/
Wenn man initialeffect nicht nutzt, würde er ja die nächste nehmen die kommt.
Wobei ich mir nicht sicher bin, ob man das je abschalten muss. Denn wer nie die grabber abschaltet, wird das nie sehen.

**Comment by Paulchen-Panther** [comment]
Der background effekt hat immer die niedrigste Prio. Wir im auch so zugewiesen. Schau dir mal meinen PR an.

**Comment by redPanther** [comment]
Der 'off effekt' hat die niedrigste prio. Der bg effekt hat lowest prio - 1.

Der wert der lowest prio ist die größte int zahl. Im priomuxer und in der hyperiond.cpp kann man das nachlesen.

Der wert läst sixh via priomuxer ermitteln.

**Comment by Paulchen-Panther** [comment]
Lag ich doch genau richtig mit "PriorityMuxer::LOWEST_PRIORITY -1"
Hab ich auch aus der hyperiond.cpp.

**Comment by redPanther** [comment]
Über json api kann man das schön in der serverinfo unter priorities sehen.

**Comment by Paulchen-Panther** [comment]
Da steht das auch noch drin

**Comment by Paulchen-Panther** [comment]
Close?
