### ISSUE TITLE
Enable/Disable components during runtime - Issues

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#204]
- [x] Blackborder
- [x] Smoothing
- [x] Kodicheck
- [x] v4l2
- [x] Grabber
- [x] boblight
- [x] udplistener
- [x] forwarder

More not tested yet

Feel free to use this PR for easy testing:
https://github.com/hyperion-project/hyperion.ng/pull/203

**Comment by redPanther** [comment]
and the last 3 services? any testers? ( @tpmodding  ) for boblight and udp listerns you can use nmap or other network port spy tool to see if hyperion opens the ports or not ...

**Comment by tpmodding** [comment]
i can test boblight and forwarder

**Comment by redPanther** [comment]
.. that would be great :-)

@penfold, can you test if udplistener vsn be enabled/disabled through hyperion-remote and/or webui?

**Comment by penfold42** [comment]
It seems really buggy via web interface

most times i get "Error while parsing json: illegal value at Line: 0, Column: 2" (or some other line/column reference).
The one time it did save without error, it did rewrite the config file, but the change didnt take effect until i restarted it.

Also noticed this:
[HYPERIOND JSONCLIENTCONNECTION] <ERROR> Someone is sending very big messages over several frames... it's not supported yet

**Comment by penfold42** [comment]
./hyperion-remote  --disable UDPLISTENER
./hyperion-remote  --enable UDPLISTENER

both seem to work fine

**Comment by redPanther** [comment]
@tpmodding any news from boblight and forwarder? I would like to close this issue

**Comment by tpmodding** [comment]
total vergessen, ich tests heute, ich geb dann feedback

**Comment by brindosch** [comment]
> ich tests heute, ich geb dann feedback
:)

**Comment by tpmodding** [comment]
jap bin dabei, hab probleme mit boblight... forwarder funzt zwar aber boblight macht mucken...bin aber nicht sicher obs an hyperion oder am boblight liegt der daten verschickt bzw nicht verschickt,
auf android geräten mit kodi bekomme ich kein boblight installiert, der will abhängigkeiten aber spuckt dabei fehler aus (kodi auf fire tv stick). muss jetzt mal nen neues libre installieren, bin noch auf einer alpha

**Comment by tpmodding** [comment]
@redPanther i updated everything today again and now my leds dont light up... if iy use hyperion it works, hyperion.ng workds nothing anymore?

**Comment by brindosch** [comment]
You could check with my "trans" branch. that worked before and hasn't the latest commits of redPanther. In case this is the reason.

**Comment by redPanther** [comment]
@tpmodding can you give some more details ... (config, leds, os, system)

You can get debug output with 
hyperiond --debug my.congif.json

BTW it works for me with adalight and fadecandy. Other drivers I can't test atm

**Comment by tpmodding** [comment]
@redPanther 
ähm lpd8806, raspbian on rpi3, config ->
http://pastebin.com/pFcx7aeQ

its only with hyperion.ng, hyperion starts and everything works fine

**Comment by penfold42** [comment]
I dont have a device to test, but this looked wrong...

**Comment by tpmodding** [comment]
i will try, why was it changed?

**Comment by penfold42** [comment]
an error i suspect when someone was cleaning up and refactoring the led devices

**Comment by redPanther** [comment]
I merged it with a small fix for the fix ....

**Comment by tpmodding** [comment]
will try it tomorrow, hope it works :)

**Comment by tpmodding** [comment]
1. i have alot of warnings? no errors, just warnings
http://pastebin.com/W1D3qD23
2. now it works! :)
but why i get no more information on command line? do i have to set a option for this?

pi@raspberrypi:~/hyperion.ng/build/bin $ ./hyperiond export.config.json 
^Cpi@raspberrypi:~/hyperion.ng/build/bin $ ./hyperiond export.config.json 
^Cpi@raspberrypi:~/hyperion.ng/build/bin $

**Comment by penfold42** [comment]
1) I just ignore the cmake policy crap!

2) yay! 
If you add --debug you get more output?
Hyperion.ng is a lot quieter by default

**Comment by tpmodding** [comment]
ok that explains it, yes i know the debug option, that works well :)

just have to test know the boblight part

**Comment by redPanther** [comment]
@tpmodding how is it going?

**Comment by tpmodding** [comment]
forwarder works, but i have no boblight to test

**Comment by redPanther** [comment]
I've tested boblight, ... it works :-)

**Comment by brindosch** [comment]
I am sorry, i found a tiny glitch. If you set framegrabber in config to false, it is never shown at the components control.

**Comment by redPanther** [comment]
solved, can be reclosed .. hopefully

**Comment by brindosch** [comment]
Can't test due to this strange segfault, it crashes even if i just change the enable to false (after export).

**Comment by brindosch** [comment]
Up and running
