### ISSUE TITLE
JSON RPC/Hyperion: Enable/Disable components during runtime

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#21]
Hyperion
- [ ] smoothing (activate bypass as it is already used if enable false?)
- [ ] blackborder
- [x] kodicheck
- [ ] forwarder
- [x] udplistener
- [x] boblight server
- [ ] grabbers (this should be handled though a platform depedent selection. To keep the command easy/platform independent)

JSON RPC
- [ ] smoothing
- [ ] blackborder
- [x] kodicheck
- [ ] forwarder
- [ ] udplistener
- [ ] boblight server
- [ ] grabbers

**Comment by brindosch** [comment]
<InsertYourCrazyReactionHere>
So close to cose! :D
Very good, can't wait for testing :)

**Comment by redPanther** [comment]
I can tell you, it's amazing.
A side effect ... I had to make big grabber refactoring ... that's why it take longer as expected. Last thing the bb detection is also tricky, because it is hidden in templates and factory ...

**Comment by brindosch** [comment]
bb was easier as I thought, because of my prior grabber refactoring all needed code was just there. Only a few additions were necessary.
