### ISSUE TITLE
Ws2812spi and sk6812rgbw have wrong default rate

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#216]
It needs to be something like 2857143

I'll fix it and reevaluate that figure

**Comment by penfold42** [comment]
@redPanther can we use the new json scheme files to apply defaults values for led devices ?

**Comment by brindosch** [comment]
on configuration base? yes, you could see this already at the webinterface.

**Comment by penfold42** [comment]
no, I don't mean the web interface - I mean the Json config parsing that happens on the led devices.
Now that we've refactored the devices, the SPI default speed is specified in providersspi.cpp
This is fine for most drivers that use it but not fine for ws2812spi and sk6812spi as they have very specific speed requirements

**Comment by redPanther** [comment]
Future plan is that defaults not hardcoded in cpp. All defaults taken automaticly from json schema.

Currently you have to overwrite setconfig and get desired json value. Then call setconfig from base class for getting the other values.
