### ISSUE TITLE
cleanup: remove smoothing from colors array

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#23]
Smoothing should be a own component like blackborder, kodicheck, ...
This is more a small todo note in general :)

**Comment by redPanther** [comment]
... the config part is boring - how about a rewrite and integrated smoothing in  priomuxer - then we have half the way to idle detection, but this a complex task and this shouldn't be done in a hurry

**Comment by brindosch** [comment]
and cause of this i just waited for some suggestions :D
