### ISSUE TITLE
startup effect logging needs cleanup

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#24]
sample output:
[HYPERIOND MAIN] <INFO> Hyperion started and initialised
INFO: Boot sequence 'Rainbow swirl fast' EFFECTENGINE INFO: run effect Rainbow swirl fast on channel 0
BLACKBORDER INFO: threshold set to 0.1 (26)
BLACKBORDER INFO: mode:default
started
[HYPERIOND MAIN] <INFO> Kodi checker created and started

Suggest just removing the cout statements around src/hyperiond/hyperiond.cpp:143:

**Comment by brindosch** [comment]
another question, is it necessary that the blackborder info spams always his setting? This is something you could log one time at startup.

**Comment by redPanther** [comment]
We should use new logger there and output those messages as Debug.

**Comment by redPanther** [comment]
A todo replace all cout with new logger

**Comment by redPanther** [comment]
the effect engine prints out every time a message, when an effect is set. This message is definitly a "Debug" message

**Comment by redPanther** [comment]
can closed because this is a subset of #25
