### ISSUE TITLE
migrate logging to new framework

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#25]
Lots to be done here - if someone new to hyperion wants to contribute, this is a tedious but worthy task!

There are 178 std::cout calls in the code as show here:
/hyperion.ng# find src libsrc -type f -exec grep -n std::cout /dev/null {} \; | wc -l
178

**Comment by brindosch** [comment]
no problem, i just need a code pattern /howto that could be used from me and for docu that devs could understand it.
regarding include, loglevel variants and how i call them

**Comment by redPanther** [comment]
please also take printf, std::cerr and qDebug() in account ;-)

**Comment by redPanther** [comment]
info for current head of master regarding new logger:
you can add commandline options for loglevel:
view debug messages:
```
hyperiond --debug
```
(more see help)

**Comment by redPanther** [comment]
Call for help! I wrote some doc about logging in the wiki:
https://hyperion-project.org/wiki/Logging

Would be great if somebody can migrate logging. We don't need migrating logging at once - component by component is absolutly ok. Ifquestions ... I will assist

**Comment by brindosch** [comment]
Good idea, i will have a look. For sure i could do that boring part :)

**Comment by redPanther** [comment]
Starting with the blackborder files are nice to practice

**Comment by penfold42** [comment]
What about banning commits of files that don't use the new logging framework ?

**Comment by brindosch** [comment]
Not sure what you mean in specific. Remove all code which has no logger implemented? This break Hyperion?

**Comment by redPanther** [comment]
Dont accept pr's when new logger oisnt used

**Comment by brindosch** [comment]
Of course.

**Comment by brindosch** [comment]
I have a question regarding the GetInstanceOf. This result in? another logoutput? a phrase like "EffectEngine" before the message itself?

**Comment by penfold42** [comment]
a new logging object if it doesnt exist.

If it does, you get a handle to the existing logging object

**Comment by brindosch** [comment]
This results in: you no longer see which part of Hyperion has thrown this error? If the message itself contain no "identifier"

**Comment by penfold42** [comment]
Sorry, I missed part 2 of your question.

The name of the logging object IS printed

**Comment by redPanther** [comment]
try to explain:

first get a logger:
`log = logger::getinstance("effects")`

this will create a logging object with logging scope "effects", if not exists, otherwise it returns existing object.

on log messages:
Info(log, "my msg")

a specific (named) logger is neccessary. This will print out the desired message and the logging scope. More than that, the logger knows exactly the position in source code (function, file and line number) where the message occurs.
Debug messages will print this information too, while info-error don't print those extra infos. This is because normal user would e a bit confused. with those info.

**Comment by redPanther** [comment]
the "solid" principles for good code:
https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)
https://de.wikipedia.org/wiki/Prinzipien_objektorientierten_Designs#SOLID-Prinzipien

**Comment by redPanther** [comment]
just for statistic:
search for outputs to convert to new logging:
`find src libsrc -type f -exec egrep -n "std::cout|qDebug|qWarning|std::cerr" /dev/null {} \; | wc -l`

result: 138-1 (logger.cpp has a cout, but this is neccessary ...)

getting the files:
`find src libsrc -type f -exec egrep -n "std::cout|qDebug|qWarning|std::cerr" /dev/null {} \; | cut -d: -f1 | sort | uniq`

result:
```
libsrc/blackborder/BlackBorderDetector.cpp
libsrc/blackborder/BlackBorderProcessor.cpp
libsrc/boblightserver/BoblightClientConnection.cpp
libsrc/bonjour/bonjourserviceregister.cpp
libsrc/effectengine/EffectEngine.cpp
libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp
libsrc/grabber/framebuffer/FramebufferFrameGrabber.cpp
libsrc/grabber/osx/OsxFrameGrabber.cpp
libsrc/grabber/v4l2/V4L2Grabber.cpp
libsrc/grabber/x11/X11Grabber.cpp
libsrc/hyperion/Hyperion.cpp
libsrc/hyperion/LinearColorSmoothing.cpp
libsrc/jsonserver/JsonClientConnection.cpp
libsrc/jsonserver/JsonServer.cpp
libsrc/leddevice/LedDeviceLightpack.cpp
libsrc/leddevice/LedDeviceLightpack-hidapi.cpp
libsrc/leddevice/LedHIDDevice.cpp
libsrc/protoserver/ProtoConnection.cpp
libsrc/protoserver/ProtoServer.cpp
libsrc/webconfig/CgiHandler.cpp
libsrc/webconfig/QtHttpClientWrapper.cpp
libsrc/webconfig/StaticFileServing.cpp
src/hyperion-aml/hyperion-aml.cpp
src/hyperion-dispmanx/hyperion-dispmanx.cpp
src/hyperiond/main.cpp
src/hyperion-framebuffer/hyperion-framebuffer.cpp
src/hyperion-osx/hyperion-osx.cpp
src/hyperion-remote/hyperion-remote.cpp
src/hyperion-remote/JsonConnection.cpp
src/hyperion-v4l2/hyperion-v4l2.cpp
src/hyperion-x11/hyperion-x11.cpp
```

**Comment by brindosch** [comment]
checking led devices:
false positive:
LedDeviceLightpack.cpp (just 2 std:cout commented out)
LedDeviceLightpack-hidapi.cpp (just 2 std:cout commented out)
LedHIDDevice.cpp (commented out printf and std:cout)

positive in brackets:
LedDevicePiBlaster.cpp (there are some printf but the majority is done)

positive:
LedDeviceWS2812b.cpp (printf, fatal and so on)

**Comment by penfold42** [comment]
piblaster is fine - those printfs are how hyperion writes to the piblaster daemon

**Comment by brindosch** [comment]
@redPanther 
if i am right you removed the "hyperion ambient light" notice and the version including the build number from the log, for sure this was not your initial intention :)

And the BB detection needs a "moved" logging or i just rename it to debug level. 
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/16731692/bf313cac-4779-11e6-93f7-068ced848c77.PNG)

I migrated Proto and Json, but needs a review and help for 2 lines.

**Comment by redPanther** [comment]
> removed the "hyperion ambient light" notice

it's there:
https://github.com/hyperion-project/hyperion.ng/blob/master/src/hyperiond/main.cpp#L106

message has to be moved to logger .... but I will make a more general way to get hyperion version

**Comment by brindosch** [comment]
That's debug, and main.cpp is never used for the "log", but as you said needs some adjustment.
I move bb to debug, as long this notice is so annoying :)

**Comment by redPanther** [comment]
>  main.cpp is never used for the "log"

what you mean? there is the "MAIN" logger defined. There are log messages, e.g.:
https://github.com/hyperion-project/hyperion.ng/blob/master/src/hyperiond/main.cpp#L93

I moved the version output to --version ... if we have a good fucntion for the version number, the hyperion class will make a info message for version number.

in normal circumstances we should keep terminal output as clean as possible, just the errors and warnings (--debug and --verbose are for bug hunt / development)

**Comment by brindosch** [comment]
> in normal circumstances we should keep terminal output as clean as possible

yes, : if someone uploads "a log" eg from webinterface it does not contain a version, this is no problem if we handle this like the following

workaround with a paste name (eh hyperion version gathered via JSON RPC).
http://pastebin.com/api

Hm, okay if everyone using the logupload we know always what we have here.
:)

**Comment by redPanther** [comment]
as i said, if we have a good func for version number, this info is printed to log. I didn't migrate it, because such a func didn't exists atm.

later on we can make a log upload from webinterface to pastebin as you suggest

**Comment by brindosch** [comment]
pastebin (or another paste service)? yes, i want to stop the log postong without quote tags at the forum :)

**Comment by brindosch** [comment]
something wiped your list? :o

**Comment by redPanther** [comment]
Are we ready here? Lost the overview ...

**Comment by brindosch** [comment]
hyperion-remote.cpp are std::cerr for output and ws2812b some printf

**Comment by penfold42** [comment]
From memory Hyperion remote was ok - they were printing to the console as they should

**Comment by redPanther** [comment]
I took a look ... mission is done. we can close the issue

**Comment by brindosch** [comment]
Yay :)
