### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#254]
I tested on my pi1. Current head needs about 25% cpu. I'm not compiled any grabber in, disabled all components and not compiled in the webserver, only mood bloobs are active.  And still such a high cpu usage.
Prior version has about 6%. This version is some selfcompiled stuff from june. It's already qt5 ...
I use tcp communication with localhost, that means qserialport cant be the problem.

Call to everybody: can you test current version on rpi?
Disabling webserver: just comment out the line where webserver is instanciated (new) in hyperiond/main.cpp

Messurment I did with top ... not the accurate testing tool, but in this case it's just fine.

A slightly higher usage than 6% is ok and understandable, but +20% is to much.

Have a nice day :-)

Ps: forgot to say, I compiled Release and striped the bins afterwards ....

**Comment by penfold42** [comment]
I've noticed this before - I'll repeat the test.

I would disable all grabbers
Disable web
Use file led device
Disable smoothing 
Set colour to black

**Comment by redPanther** [comment]
Just a notice, on my desktop (older amd  4 core)  usage is about 2% with all stuff enabled and grabbing full hd

**Comment by redPanther** [comment]
Any news here? Test on other systems are also appreciated.

**Comment by penfold42** [comment]
on a pi3 (not a pi1)
startup - 10.9% CPU
select a colour - 6.6%
run knight rider - 5%
UDP listener (effect) - 100% *laughs*

**Comment by redPanther** [comment]
That looks ok. Hmmm do we have a special pi1 issue? Or are my messurments faulty?

**Comment by penfold42** [comment]
Cmake is running now on my pi1 ...

**Comment by redPanther** [comment]
.... and what are the test results?

**Comment by penfold42** [comment]
Ran out of memory during compile

Tried swap over nfs - it hung

Got busy on other stuff

**Comment by tpmodding** [comment]
which system do you use on your pi @redPanther ?

**Comment by redPanther** [comment]
arch linux

**Comment by tpmodding** [comment]
if paulchens new PR is merged, i will compile and retest it on raspian and elec

**Comment by redPanther** [comment]
Let's go! :-)

**Comment by tpmodding** [comment]
raspbian everything up2date rpi3
without hyperiond
0,2-0,3%
with hyperiond
1,4-2,0% but most time on 1,8%...

:)

**Comment by redPanther** [comment]
thx for testing - this is in acceptable parameters. The pi1 make me sorry ... test on that old piece of hardware is apreciated

**Comment by tpmodding** [comment]
maybe its now besser cause we moved to QT?...

**Comment by redPanther** [comment]
hyperion is a qt project from beginning. Latest changes have no influence on permanentlöy running hyperion. The qtjson stuff is in hyperion boot phase.
Yours and penfolds pi3 test are quite close, so your test I a hint, that we have no probs on newer systems.

**Comment by tpmodding** [comment]
hab kein plan von software :S any other tests to do?

**Comment by tpmodding** [comment]
can close this? or should we wait?

**Comment by Paulchen-Panther** [comment]
Hab hier noch einen Pi Zero rumliegen. Soll ich darauf auch mal Hyperion kompilieren und laufen lassen? Der Zero basiert ja auch auf dem Pi 1 ( glaube ich zu mindestens).

**Comment by tpmodding** [comment]
www.serhan.in/hyperion.ng.zip kannst du direkt testen :) aber der zero hat 1000mhz, der 1er nur 700mhz wenn ich mich nicht irre..

**Comment by Paulchen-Panther** [comment]
Coole Sache. Dann probier ich das auch mal am Wochenende aus. Danke.

**Comment by redPanther** [comment]
tested with current master on my pi 1 ... performance problem is gone ...

**Comment by T-IOOO** [comment]
Sorry for opening up an old thread. I am running my Hyperion configuration with a Rpi zero w and I have issue with CPU staying constantly on 100%. I think the grabber might the problem but I am not entirely sure

lsusb gives me this... 
534d:0021

Is there anyone else having same issue? Is there a fix?

**Comment by ghostface** [comment]
Running pi zero as well having similiar problems:

- hyperion ng compiled from latest head 
- no grabbers enabled
- no blackbar detection or smoothing enabled
- hardware is lpd8806
- armarchlinux
- compiled from latest head

and I am getting 35% at idle, been using the old hyperion (non ng) before and it was way less than that, not sure what is causing this.

**Comment by T-IOOO** [comment]
I had a digital-analog-digital solution as a grabber back then. Changed to an hdmi-usb grabber and it improved the cpu and the image/color quality. The response is also way better! I had about a second delay which was very annoying. So try different grabbers, hope it helps!

**Comment by ghostface** [comment]
Ok i figured out what the reason for this is on my setup.

The 30% cpu load is consumed by an effects thread, disabling the boot animation fixed my problem.
I am not sure why this is happening, it appears like the boot effect (rainbow swirl fast, duration 3000) is getting stuck for some reason, might be my setup tho.

I went back testing from alpha5 to alpha8 and master head from yesterday and it was the same symptom everywhere - even deleted my /etc/hyperion folder and started with a fresh config.
