### ISSUE TITLE
Suggestion: InitialEffect

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#272]
Webui:
We can't keep the array for color [R,G,B] and the move to array for effects ["Rainbow swirl fast"] is now also a problem. (The point that our config == our UI is a big breaker and we are more or less forced to bring them together.
Percentage values are another example. We could "append" *100 = % as hint or you move from float to integer) (Which looks less ugly)

Idea:
Move color to HEX and place it as a string.
Remove the array for effects - a string only again

result:
No problem for validation as it is always a string
No longer arrays which adds at the ui more than one value

issues remain:
Implement bootstrap color picker (i found no handling inside jsoneditor for format:colors option?! Needs to be added)
The OR bridge between colorpicker and effectslist with the same(!) json value.

**Comment by penfold42** [comment]
So and initial effect called #FF0000 would be parsed as a colour rather than effect name ?
If so, yep, agree.

I never did understand why it was moved to an array.

**Comment by brindosch** [comment]
Good point, searching for # add the beginning should be enough? ( it unlikely that someone use a # - at least i hope so.)
It is still a possible fail. More rocket: split them and add a dropdown. At least this is (very) easy to handle with the webui. Also if i think about how to handle the load-your-value-in-form.
Depending on selected option, you could .hide color or effects (out of the box i think)

foreground: color
foregroundeffect : YourEffect
foregroundcolor :  YourColor

The reason was the validation. A string and a array for the same value. There was never a OR expected :)

**Comment by redPanther** [comment]
in code we need rgb values and it  is easier when we have an array of rgb values instead of an hex string.

Anyway we will change that. i already thought about that

foreground: color
foregroundeffect : YourEffect
foregroundcolor : YourColor

the foreground effect should be an auto generated enum, so in ui you simply select your effect instead of writing text.

i will see what I can do, task is not so big ...

**Comment by brindosch** [comment]
Rethink
The effectengine also runs with [RGB]. maybe it's better to find a proper way to include bootstrapcolorpicker and avoid the editor array function, you could anyway request the color schema you want from it. (HEX, RGB, RGBA(gradient!)) much more flexibel.

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion.ng/pull/358
