### ISSUE TITLE
Color calibration discuss

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#276]
As we slowly reaching a interesting step:
There are 3 types of use cases - we should catch them all
- Use just framegrabber or other "digital" sources (digital calibration)
- Use framegrabber and v4l2 (digital calibration that is applied to _all_ and a second calibration that is used for v4l2)
- Use just v4l2 (calibration for v4l2 only?!)

Additional question:
Effects and Colors - Should they skip the color modifications entirely? Does it harm someone with strange colors for effects/colors if they are not processed? (If i see people having 50,255,50 to get a white color?!)

Additional task:
merge 2 arrays in 1. Adjust transform and channeladjustments separably is crazy to use.
As code == gui i suggest a new sorting that follows the configuration flow and not the code flow.
See HyperCon: https://hyperion-project.org/wiki/HyperConProcessTab-Colors-EN

And on top:
Splitting smoothing between colors/effects and all other stuff (own setting - i think my smoothing is too high for effects, but good for pictures)

HSL vs HSV
Could you use HSL to lower the overall brightness without getting very weird colors (compared with HSV)?

**Comment by redPanther** [comment]
for effects/color "transform" is not usefull, but "adjustment" is needed. Some leddevices (fadecandy/adalight), can do same operation in hardware, so for that devices the settings not necessary - other devices e.g. all stripes directly driven on rpi gpio need this settings.

I think first task is to merge color settings in one settings block. Then we will see whats next.

**Comment by penfold42** [comment]
Is like to see separated settings
1) grabber settings to correct shitty grabbers
2) led device settings to correct wacky leds

**Comment by redPanther** [comment]
when I think about, should we stick "channeladjustments" to leddevice and "transform" to grabber.

When doing calibration set "channeladjustments" with solid colors/effects.
Then start grabbing and optimze result with "transformation".

Did I miss something? We can do this already. 
Just set:
```
"channelAdjustment_v4l_only" : false,
"transform_v4l_only" : true,
```
what we don't have is a "transform" for screen grabber (x11,dispmanx,..) 

perhaps we should:
- remove `"channelAdjustment_v4l_only" : false,` this should be active for all
- replace transform_v4l_only with (e.g.) "transform_target" with following possible values (enums) `all`, `v4l`, `screen capture`
- possibility to have "transform" block 2 times, so you can have different settings for v4l and screen capture

**Comment by brindosch** [comment]
So current state:
I think v4l2_only will be dropped and replaced by a priorities assignment.
Maybe as a string, so if you set it to "*" it will be applied to all priorities

If you now create a second entry and you set it to 250 for example it will be just applied to prio 250

It is necessary to build this segfault save, which means a incomplete *led index* assignment shouldn't kill it too! (it should assign than the default values instead)

@redPanther

**Comment by redPanther** [comment]
... I'm working already on it

**Comment by redPanther** [comment]
we should assign a color adjustment to component not to prio.
