### ISSUE TITLE
Osmc kodichecker issues 

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#278]
I did a quick test with osmc kodi 17 today.

I can't seem to get it to grab anything but video.

The logs look like it's correctly recognising it, but nothing on the leds.

I'll get more scientific with better logs later in the week, but has anyone else tried 17 ?

**Comment by brindosch** [comment]
Sad news, could you try hyperion-dipmanx to capture screenshots? If they are black we have a problem ;)

**Comment by penfold42** [comment]
My osmc kodi 16 is behaving the same way 8-(

The external dispmanx grabber works fine - as does the internal grabber for movies.
Disabling kodi checker works fine too.

Will have to dig deeper over the weekend

**Comment by penfold42** [comment]
I've renamed this issue from "Osmc kodi 17 issues?". It's basically broken in general for both kodi 16+17.

I suspect its a dispmanx grabber/kodichecker issue.

Works OK:
GRABBINGMODE_VIDEO
GRABBINGMODE_PAUSE

NOT Working:
GRABBINGMODE_AUDIO
GRABBINGMODE_PHOTO
GRABBINGMODE_MENU
GRABBINGMODE_SCREENSAVER

a --debug log shows it correctly determining the state from kodi:
```
[HYPERIOND KODI] <INFO> switching to PAUSE mode
[HYPERIOND Core] <INFO> Register new input source named 'Dispmanx' for priority channel '780'
[HYPERIOND KODI] <INFO> switching to VIDEO mode
[HYPERIOND Core] <INFO> Register new input source named 'Dispmanx' for priority channel '780'
[HYPERIOND KODI] <INFO> switching to AUDIO mode
[HYPERIOND Core] <INFO> Register new input source named 'Dispmanx' for priority channel '780'
[HYPERIOND KODI] <INFO> switching to MENU mode
[HYPERIOND Core] <INFO> Register new input source named 'Dispmanx' for priority channel '780'
[HYPERIOND KODI] <INFO> switching to SCREENSAVER mode
[HYPERIOND Core] <INFO> Register new input source named 'Dispmanx' for priority channel '780'
[HYPERIOND KODI] <INFO> switching to PHOTO mode
[HYPERIOND Core] <INFO> Register new input source named 'Dispmanx' for priority channel '780'
```

I tried to untangle the grabber and kodichecker code but am getting quickly lost...
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/hyperion/GrabberWrapper.cpp:99 might be a hint - whats this "pause" and "play" ?

**Comment by Paulchen-Panther** [comment]
Könntest du mal folgende Zeile löschen, neu kompilieren und danach noch mal testen?
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/grabber/dispmanx/DispmanxWrapper.cpp#L58

**Comment by penfold42** [comment]
I tried this and it made no difference.

BUT! commenting out line 51 did work:
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/grabber/dispmanx/DispmanxWrapper.cpp#L51

maybe something is broken with those flags

**Comment by penfold42** [comment]
@redPanther ?

**Comment by tpmodding** [comment]
they wanted to change something for grabbers:

 • Rework of rendercapture which is used by boblight or ambilight implementations
https://kodi.tv/kodi-v17-krypton-alpha-2/

**Comment by Paulchen-Panther** [comment]
This is done!
https://github.com/hyperion-project/hyperion.kodi/pull/18

**Comment by brindosch** [comment]
@penfold42 
Does @Paulchen-Panther fix work (too)?
remove this line: https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/grabber/dispmanx/DispmanxWrapper.cpp#L58

Wonder that your fix (penfold) kill something?
I have no issues with Kodi 16. Bu didn't tested 17.
Further test @tpmodding ?

**Comment by tpmodding** [comment]
only on osmc?

**Comment by penfold42** [comment]
I've only tested on osmc 16 with October update on a pi3 and osmc 17 beta on a pi3.

Removing line 58 didn't work.
Removing line 51 DOES work.

Why are those vc_mode flags needed ?
Why is capturing video and pause any different to capturing audio on a Pi?

**Comment by brindosch** [comment]
No idea about this flag - but there should be no difference? Maybe it was necessary at the beginning of Hyperion. An old "workaround" or such.
@tpmodding osmc and librelec would be good (Just to be sure) with kodi 16 and 17

**Comment by tpmodding** [comment]
will test them

**Comment by tpmodding** [comment]
LibreELEC:~/.config # /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json
/storage/hyperion/bin/hyperiond: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory

where can i find this? or create it for *elec systems?

**Comment by redPanther** [comment]
I think you should link against python2. How you compile it?

**Comment by tpmodding** [comment]
changed nothing, was it only this one?
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/effectengine/CMakeLists.txt#L4

**Comment by tpmodding** [comment]
so wie ich es sehe brauchen wir es nur für die effectengine, ist es schlimm wenn wir es fix auf 2.7 halten? dann ist es immer überall kompitabel

**Comment by redPanther** [comment]
ich würd das als cmake option machen ... Ich nutze das z.b. auf meinem system mit py3
Default wäre py2.
Ging es mit dem `find_package(PythonLibs 2.7 REQUIRED)` ?

**Comment by brindosch** [comment]
Das Thema hatten wir ja schon einmal. Travis linkt auch zu py3, obwohl py2 default ist. Hoffe das required hilft.

**Comment by redPanther** [comment]
bin mir da nich ganz so sicher ob das hilft ... muss mir das nochmal separat anschauen

**Comment by tpmodding** [comment]
früher hats immer geklappt...ich teste das eben mal schnell

**Comment by tpmodding** [comment]
hm, ne klappt irgendwie nicht... wie bekommen wirs ans laufen nu? reichts wenn wir die libpython3.4m.so.1.0: datei haben? & wo bekomm ichs? :)

**Comment by tpmodding** [comment]
habs kopiert jetzt:
LibreELEC:~/hyperion/bin # ./hyperiond.sh --version
/storage/hyperion/bin/hyperiond: error while loading shared libraries: libQt5Gui.so.5: cannot open shared object file: No such file or directory

...bin mal gespannt was wir alles noch brauchen... so wirds kompliziert

**Comment by brindosch** [comment]
Da es kein package für ro gibt... Ich meine aber tociek ist gescheitert. Nutz einfach osmc und gut ist :)
Da könntest du sogar direkt kompilieren anstatt 2 Systeme zu nutzen :)

**Comment by tpmodding** [comment]
ja bringt uns ja nichts wenn später hyperion.ng auf keinem elec system läuft?

**Comment by tpmodding** [comment]
hab alles kopiert...aber jetzt bin ich am ende

LibreELEC:~/hyperion/bin # ./hyperiond.sh --version
Hyperion Ambilight Deamon (661)
	Version   : 2.0.0 (master (redPanther-dc18ac3/9804a9b-1481025274))
	Build Time: Dec  7 2016 20:57:54
LibreELEC:~/hyperion/bin # ./hyperiond.sh --help
Usage: /storage/hyperion/bin/hyperiond [options] config.file
Hyperion Daemon

Options:
  -h, --help                         Displays this help.
  --version                          Show version information
  -p, --parent <parent>              pid of parent hyperiond
  -s, --silent                       do not print any outputs
  -v, --verbose                      Increase verbosity
  -d, --debug                        Show debug messages
  --export-config <export-config>    export default config to file
  --export-effects <export-effects>  export effects to given path

Arguments:
  config-files                       Configuration file
LibreELEC:~/hyperion/bin # ./hyperiond.sh --export-config test.config.json
LibreELEC:~/hyperion/bin # ./hyperiond.sh test.config.json 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted (core dumped)
LibreELEC:~/hyperion/bin # 

@redPanther  ?

**Comment by brindosch** [comment]
elec Systeme kommen später(wenn du mich frägst). Bevor man jetzt immer wieder anfängt da hinterher zu fixen. Das ganze ist ein einziger Flickenteppich. Wir haben noch genug anderen Kram :)

**Comment by tpmodding** [comment]
bin ich mit einverstanden. teste morgen dann mal das osmc :D

**Comment by brindosch** [comment]
RC3...
Still the same issues? I will test later these days

**Comment by redPanther** [comment]
> ould not find platform independent libraries
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to [:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

as the error message said, python can not find the modules. Setting PYTHONHOME to location where the modules located, should be enough. On my linux system it is /usr/lib/python2.7 for py2.7
(there should be e.g. a folder 'encodings'  )

**Comment by brindosch** [comment]
So, @penfold42 
tested with osmc kodi 17 rc3, i have seen no issue. Well, i noticed that dispmanx is black, when you display a picture - this is very very bad, as we need pictures for calibration...

**Comment by penfold42** [comment]
And does commmenting out the flags on line 51 fix it for you ?

**Comment by brindosch** [comment]
yes. this works for me too. https://github.com/brindosch/hyperion.ngBeta/commit/1355ea2f3843e6df5212c9e523085e2f9a4b4864
Did you tested kodi 16 with no flags?

**Comment by penfold42** [comment]
I did test it in december and that change was needed.

I just checked my current build and it is working WITHOUT this change...

WTF??

My kodi16 is osmc on an rpi3 with december update.

whats yours?

**Comment by penfold42** [comment]
im an idiot..... I had the kodichecker disabled in my current config...

It is still broken without that change in kodi 16

**Comment by brindosch** [comment]
Well osmc kodi 16 works for me with and without flags. I assume it has something to do with your software setup. (or is it just a fresh osmc?)

Anyway, i added this change now: https://github.com/hyperion-project/hyperion.ng/commit/c85b2de13dfcd70b4335fac42d1f078b0968ed8b . I have still no clue why these flags have been added just for kodi (even in the past - it makes no sense?!)

If someone have problems now, please report them in this issue. It is possible that support for kodi v15 and smaller is broken in a very strange way.

/closed

**Comment by redPanther** [comment]
We should delete kodi* funcs in dispmanxwrapper. They are obsolete now.

**Comment by brindosch** [comment]
Yes, i wanted to wait for your confirmed feedback :) (and maybe others around there @tpmodding )

**Comment by penfold42** [comment]
Agree - although a common combination, kodi and dispmanx should have no relationship to each other

**Comment by redPanther** [comment]
I've made a pr, so when it's ok, just merge it
