### ISSUE TITLE
undefined reference to `sd_listen_fds' and undefined reference to `sd_is_socket'

### ISSUE THREAD

**Issue by Kiina** [hyperion-project/hyperion.ng#279]
So I'm trying to compile for Amlogic S905 and everything seems fine until the end:

```
[  1%] Built target hidapi-libusb
[  3%] Built target tinkerforge
[ 10%] Built target hyperion-utils
[ 11%] Built target blackborder
[ 35%] Built target leddevice
[ 45%] Built target hyperion
[ 50%] Built target commandline
[ 54%] Built target jsonserver
[ 60%] Built target protoserver
[ 62%] Built target bonjour
[ 65%] Built target boblightserver
[ 67%] Built target udplistener
[ 69%] Built target kodivideochecker
[ 73%] Built target effectengine
[ 75%] Built target amlogic-grabber
[ 77%] Built target framebuffer-grabber
[ 80%] Built target v4l2-grabber
[ 91%] Built target webconfig
[ 91%] Linking CXX executable ../../bin/hyperiond
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1dcc): undefined reference to `sd_listen_fds'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1e10): undefined reference to `sd_is_socket'
collect2: error: ld returned 1 exit status
src/hyperiond/CMakeFiles/hyperiond.dir/build.make:145: recipe for target 'bin/hyperiond' failed
make[2]: *** [bin/hyperiond] Error 1
CMakeFiles/Makefile2:1322: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

My cmake output:

```
cmake -DPLATFORM=amlogic64 -DCMAKE_INSTALL_PREFIX=/usr ..
-- ENABLE_AMLOGIC = ON
-- ENABLE_DISPMANX = OFF
-- ENABLE_FB = ON
-- ENABLE_OSX = OFF
-- ENABLE_SPIDEV   = ON
-- ENABLE_TINKERFORGE = ON
-- ENABLE_V4L2 = ON
-- ENABLE_WS2812BPWM = OFF
-- ENABLE_WS281XPWM = OFF
-- ENABLE_X11 = OFF
-- ENABLE_TESTS = OFF
-- ENABLE_PROFILER = OFF
-- Current Version: master (redPanther-d3dc530/fab0c20-1477345973)
-- Found Qt Version: 5.5.1
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/aarch64-linux-gnu/libusb-1.0.so
-- Using protobuf compiler: /usr/bin/protoc
CMake Warning at doc/CMakeLists.txt:31 (message):
  Doxygen not found, unable to generate documenation!


-- Configuring done
-- Generating done
-- Build files have been written to: /root/hyperion/build
```

For some reason I have to define the Plattform manually else I will get:

```
PLATFORM is not defined and could not be evaluated.  Set
  -DPLATFORM=<rpi|pri-pwm|amlogic|amlogic64|x86>
```

probably because my cpu info looks like this:

```
processor       : 0
BogoMIPS        : 2.00
Features        : fp asimd crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 2.00
Features        : fp asimd crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 2.00
Features        : fp asimd crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 2.00
Features        : fp asimd crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : ODROID-C2
Revision        : 020c
```

which isn't a huge problem as long as the build would work

**Comment by sebastianwachter** [comment]
having the same problems

**Comment by redPanther** [comment]
the platform thing:
I can only recognize what I know .... I dont have an odroid c2 ... But I will add it for detection

the link problem:
your dbus lib needs linking against systemd libs. This point is harder, because I can't link on every system to systemd (-lsystemd-daemon to be exact) because It is not neccessary and wanted everywhere.
We have two options here: the easy, but not good one - make an option so everybody can activate linking on systemd
or the harder one, but the best - detect if systemd linkage is neccessary for link against libdbus-1

I will look into it ...

**Comment by redPanther** [comment]
just for testing,
can you modify src/hyperiond/CMakeLists.txt
add a line with "systemd-daemon" after "bonjour"

```
  webconfig
  bonjour
  systemd-daemon
)                                                                                                                                                            
```

**Comment by Kiina** [comment]
```
/usr/bin/ld: cannot find -lsystemd-daemon
collect2: error: ld returned 1 exit status
src/hyperiond/CMakeFiles/hyperiond.dir/build.make:145: recipe for target 'bin/hyperiond' failed
make[2]: *** [bin/hyperiond] Error 1
CMakeFiles/Makefile2:1322: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by penfold42** [comment]
Is there a systemd dev package available ?

**Comment by Kiina** [comment]
libsystemd-dev seems like the only one. Installed it but no difference.

Here are all systemd related packages, but they don't sound like much help:
```
apt-cache search systemd
golang-github-coreos-go-systemd-dev - Go client bindings for systemd socket activation, journal and dbus
init - System-V-like init utilities - metapackage
init-system-helpers - helper tools for all init systems
libcib-dev - cluster resource manager CIB library development
libcib4 - cluster resource manager CIB library
libcrmcluster-dev - cluster resource manager cluster library development
libcrmcluster4 - cluster resource manager cluster library
libcrmcommon-dev - cluster resource manager common library development
libcrmcommon3 - cluster resource manager common library
libcrmservice-dev - cluster resource manager service library development
libcrmservice3 - cluster resource manager service library
liblrmd-dev - cluster resource manager LRMD library development
liblrmd1 - cluster resource manager LRMD library
libpam-systemd - system and service manager - PAM module
libpe-rules2 - cluster resource manager Policy Engine rules library
libpe-status10 - cluster resource manager Policy Engine status library
libpengine-dev - cluster resource manager Policy Engine library development
libpengine10 - cluster resource manager Policy Engine library
libstonithd-dev - cluster resource manager STONITH daemon library development
libstonithd2 - cluster resource manager STONITH daemon library
libsystemd-dev - systemd utility library - development files
libsystemd0 - systemd utility library
libtransitioner2 - cluster resource manager transitioner library
pacemaker - cluster resource manager
pacemaker-cli-utils - cluster resource manager command line utilities
pacemaker-common - cluster resource manager common files
pacemaker-doc - cluster resource manager HTML documentation
pacemaker-resource-agents - cluster resource manager general resource agents
python-oslo.service - library for running OpenStack services - Python 2.x
python-oslo.service-doc - library for running OpenStack services - doc
python3-systemd - Python 3 bindings for systemd
systemd - system and service manager
systemd-dbg - system and service manager (debug symbols)
systemd-shim - shim for systemd
systemd-sysv - system and service manager - SysV links
upstart-sysv - event-based init daemon - SysV links
click-systemd - Click hook for systemd unit
ctop - Command line / text based Linux Containers monitoring tool
dbus-user-session - simple interprocess messaging system (systemd --user integration)
dh-systemd - debhelper add-on to handle systemd unit files
duck - checks URLs in debian/control and debian/upstream files
fail2ban - ban hosts that cause multiple authentication errors
fleet - distributed init system using systemd and etcd
gnome-logs - viewer for the systemd journal.
golang-coreos-log-dev - simple logging library for Go
kde-config-systemd - KDE control center module for Systemd
libnss-mymachines - nss module to resolve hostnames for local container instances
libnss-resolve - nss module to resolve names via systemd-resolved
light-locker - simple screen locker for lightDM display manager
nagios-plugins-contrib - Plugins for nagios compatible monitoring systems
needrestart - check which daemons need to be restarted after library upgrades
openstack-pkg-tools - Tools and scripts for building Openstack packages in Debian
pacemaker-remote - cluster resource manager proxy daemon for remote nodes
pipexec - create a directed graph of processes and pipes
python-dbusmock - mock D-Bus objects for tests (Python 2)
python-systemd - Python 2 bindings for systemd
python3-dbusmock - mock D-Bus objects for tests (Python 3)
python3-oslo.service - library for running OpenStack services - Python 3.x
systemd-container - systemd container/nspawn tools
systemd-coredump - tools for storing and retrieving coredumps
systemd-cron - systemd units to provide cron daemon & anacron functionality
systemd-docker - wrapper for "docker run" to handle systemd quirks
systemd-gui - transitional package for systemd-ui
systemd-journal-remote - tools for sending and receiving remote journal logs
systemd-ui - graphical frontend for systemd
uwsgi-core - fast, self-healing application container server (core)
```

**Comment by redPanther** [comment]
... we link against the library that implements `sd_listen_fds'. I couldn't test this ATM.
So I can only guess. According to man page https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html perhaps you have to link against "systemd". Add this in the  src/hyperiond/CMakeLists.txt

**Comment by Kiina** [comment]
Tried linking systemd still same errors. (linking libystemd etc doesn't work either)

**Comment by redPanther** [comment]
ok, can't help, because I can't try it out. It is 100% a missing lib. We need somebody with a odroidc2 / aml s905  system.
Which OS did you running?

I greped for sd_listen_fds in on my (x86) archlinux. The symbols are in libsystemd.so
So I'm absolutly sure we have to link against "systemd" (no 'lib' infront!).

My libdbus-1.so (that pulls the dependency to systemd) has following linkage:
```
        linux-vdso.so.1 (0x00007fff2ddce000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8c66904000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f8c6687c000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f8c664dc000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x0000557a5dde1000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f8c662c4000)
        libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f8c660bc000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f8c65eb4000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f8c65bac000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f8c65984000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f8c6576c000)
        libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f8c6545c000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f8c65244000)
```
as you see it links against systemd itselfs, so no need to link against systemd in programm that uses libdbus-1.so.

can you post the output of `ldd /usr/lib/libdbus-1.so`?

**Comment by Kiina** [comment]
My libdbus-1.so is located in /usr/lib/aarch64-linux-gnu/libdbus-1.so. Running ubuntu 16.04.1 with kernel 3.14.79-91 aarch64

```
ldd /usr/lib/aarch64-linux-gnu/libdbus-1.so
        linux-vdso.so.1 =>  (0x0000007fa2a5e000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007fa29c4000)
        libsystemd.so.0 => /lib/aarch64-linux-gnu/libsystemd.so.0 (0x0000007fa2942000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007fa27fa000)
        /lib/ld-linux-aarch64.so.1 (0x0000005575ef1000)
        libselinux.so.1 => /lib/aarch64-linux-gnu/libselinux.so.1 (0x0000007fa27cd000)
        librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007fa27b6000)
        liblzma.so.5 => /lib/aarch64-linux-gnu/liblzma.so.5 (0x0000007fa2788000)
        libgcrypt.so.20 => /lib/aarch64-linux-gnu/libgcrypt.so.20 (0x0000007fa26ef000)
        libpcre.so.3 => /lib/aarch64-linux-gnu/libpcre.so.3 (0x0000007fa267e000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007fa266a000)
        libgpg-error.so.0 => /lib/aarch64-linux-gnu/libgpg-error.so.0 (0x0000007fa2649000)
```

**Comment by redPanther** [comment]
Odroid c2 platform detection should work with latest github code. But this doesnt resolve the linker issue.

Can somebody with a odroid test if platform detection works?

**Comment by Kiina** [comment]
```
CMake Error at CMakeLists.txt:53 (message):
  PLATFORM is not defined and could not be evaluated.  Set
  -DPLATFORM=<rpi|amlogic|amlogic64|x86|x86-dev|osx|osx-dev>


-- Configuring incomplete, errors occurred!
See also "/root/hyperion.ng/build/CMakeFiles/CMakeOutput.log".
```

**Comment by redPanther** [comment]
move comment to correct issue:

**Comment by redPanther** [comment]
@oberstmueller your problem is more general and has nothing to do with pr #394 that's why I moved it here. As you can see it's a more general thing we have to solve, that's why I write in english so more audience can listen to it and hopefully find the right library we have to link to.

So now it is not a odrod-c2 (aka 64bit linux on amlogic platform) issue anymore. Which operationg system you use on your pi3? can you output the result of `uname -a`

**Comment by oberstmueller** [comment]
Sorry, before pr 394 i had no issue so i thougt it caused the Problem.

uname -a

Linux raspberrypi-Stube 4.4.48-v7+ #962 SMP Fri Feb 10 16:25:08 GMT 2017 armv7l GNU/Linux

**Comment by redPanther** [comment]
which distribution? rasbian, archlinux, ...?

**Comment by oberstmueller** [comment]
Raspbian

**Comment by redPanther** [comment]
I teste with ubuntu 16.10 on x86. No issue there. Also it compiles on osx. I guess its an issue with newer linux for arm. My pi2 is nt working atm, so I cant investigate.
Problem should be very easy to resolve, but without a system to reproduce its impossible. Can somebody help to find the lib we miss to link

**Comment by brindosch** [comment]
No issues with Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l.
Wonder when this has been introduced exatly. Specific kernel version? or a sepcific pr for systemd.

**Comment by oberstmueller** [comment]
I have downgraded the Pi to 4.4.13-v7. Same issue.

**Comment by Kiina** [comment]
If it worked before #394, have you tried to checkout the commit before and build?

**Comment by oberstmueller** [comment]
@Kiina
I don't know how to build from an old commit.

**Comment by redPanther** [comment]
view log: (last 5 log entries)
`git log -n5`
find commit hash you want. (e.g. 170ad4f5db0fa470686f3e893fc874c11f67145e for (including) pr #389)

goto specific revision:
`git checkout <commit hash>`
e.g.
`git checkout 170ad4f5db0fa470686f3e893fc874c11f67145e`

make yout tests.

discard your changes:
`git checkout master`

**Comment by redPanther** [comment]
just a guess:
in change libsrc/bonjour/CMakeLists.txt
```
if (USE_SHARED_AVAHI_LIBS)
	target_link_libraries(bonjour
		dns_sd
		avahi-client
		avahi-common
		avahi-core
		dbus-1
		systemd
		)
elseif (DEFAULT_USE_AVAHI_LIBS)
	target_link_libraries(bonjour
		libdns_sd.a
		libavahi-client.a
		libavahi-common.a
		libavahi-core.a
		libdbus-1.a
		libsystemd.a
		)
endif()
```
(systemd is added there)

**Comment by Kiina** [comment]
```
/usr/bin/ld: cannot find -lsystemd
collect2: error: ld returned 1 exit status
src/hyperiond/CMakeFiles/hyperiond.dir/build.make:227: recipe for target 'bin/hyperiond' failed
make[2]: *** [bin/hyperiond] Error 1
CMakeFiles/Makefile2:1322: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
Makefile:149: recipe for target 'all' failed

```

**Comment by redPanther** [comment]
@kiina your libsystemd.so is located in /lib/aarch64-linux-gnu/ (see the prior post from your). Perhaps the lib search path (LD_LIBRARY_PATH) didn't point to that folder. my libsystemd.so is in /usr/lib/
can you try to execute before `make`
`export LD_LIBRARY_PATH=/lib/aarch64-linux-gnu/`

other possibility:
add:
`LINK_DIRECTORIES(/lib/aarch64-linux-gnu/)`
in the first line of src/hyperiond/CMakeLists.txt

**Comment by oberstmueller** [comment]
On older commits its the same issue.

**Comment by Kiina** [comment]
@redPanther 
so I tried both methods with `/lib/aarch64-linux-gnu/` and `/usr/lib/aarch64-linux-gnu/`
as:
```
# readlink -f /usr/lib/aarch64-linux-gnu/libsystemd.so
/lib/aarch64-linux-gnu/libsystemd.so.0.14.0
```

but same issue. Maybe @oberstmueller should test because he probably doesn't have any linker issues with systemd

**Comment by redPanther** [comment]
could we ran into this: https://lists.freedesktop.org/archives/systemd-devel/2012-January/004132.html issue?

**Comment by Kiina** [comment]
It should build against the shared version from what I have seen

2017. 2. 14. 20:00에 "redPanther" <notifications@github.com>님이 작성:

**Comment by redPanther** [comment]
thats what we already trying here ... but dont know how this lib on your system is named. On my system it's simply libsystemd.so (ubuntu 14.04, 16.10 and latest archlinux all x86_64) I looked into the lib with `nm` and saw that sd_listen_fds is implemented there.

**Comment by Kiina** [comment]
Yeah it is also implemented in my libsystemd.so that I mentioned earlier

2017. 2. 14. 20:17에 "redPanther" <notifications@github.com>님이 작성:

**Comment by redPanther** [comment]
... then the big question is, why your libsystemd is not found. did you have any clue? `LINK_DIRECTORIES(/lib/aarch64-linux-gnu/)` should say the compiler where to look ...

just an experiment: can you copy libsystemd.so to /usr/lib ?

**Comment by Kiina** [comment]
Oh so I said "It should build against the shared version" but seems like it doesn't. DEFAULT_USE_SHARED_AVAHI_LIBS is only set to ON on x86. Raspberrypi 3 is 64 bit iirc so thats why it builds fine on the pi2 but not on the c2 and the pi3. 

@oberstmueller can you try to add `SET ( DEFAULT_USE_SHARED_AVAHI_LIBS  ON )` to your CMakeLists.txt under elseif ( "${PLATFORM}" STREQUAL "rpi" ) and report?

**Comment by redPanther** [comment]
then do:
`cmake -DDEFAULT_USE_SHARED_AVAHI_LIBS=ON ..` before make ...

**Comment by oberstmueller** [comment]
@Kiina same issue.

[100%] Linking CXX executable ../../bin/hyperiond
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1b58): undefined reference to `sd_listen_fds'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1b98): undefined reference to `sd_is_socket'
collect2: error: ld returned 1 exit status
src/hyperiond/CMakeFiles/hyperiond.dir/build.make:231: recipe for target 'bin/hyperiond' failed
make[2]: *** [bin/hyperiond] Error 1
CMakeFiles/Makefile2:1573: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by redPanther** [comment]
oh, I mean 
`cmake -DUSE_SHARED_AVAHI_LIBS=ON`
this should make same thing as your PR. I will cleanup the cmake stuff regarding avahi libs ... I will set the default to shared in general and make static an exception

**Comment by redPanther** [comment]
@oberstmueller can you try with latest github sources?

**Comment by oberstmueller** [comment]
@redPanther latest github sources?

**Comment by redPanther** [comment]
I updated hyperion so you have to update or xheckout again.

Do a 
git pull 
to get latest

**Comment by oberstmueller** [comment]
I'll try it when I'm home.

**Comment by oberstmueller** [comment]
Thank you @redPanther, no error anymore.
