### ISSUE TITLE
Priorities enhancement

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#28]
Move all default priorities to a single default-priorities.h

Enhance Json priority list with the name of which components have set that priority

Log a warning of priorities collide so it's more obvious why it's flickering as they fight to the death

**Comment by brindosch** [comment]
> Enhance Json priority list with the name of which components have set that priority

of couse, tihs list is currently near to useless. Just if you really know what is going on you understand it.

every device that set a priority should send a identifier? Kodi grabber addon for example "HyperionKodiAddon" or so. Or if a smartphone app is used "HyperionAndroidApp"

**Comment by penfold42** [comment]
ideally, yep

I've uploaded a list of every file under src and libsrc that has the word priority and a 3 digit number in it
[priority-grep.txt](https://github.com/hyperion-project/hyperion.ng/files/323467/priority-grep.txt)

**Comment by redPanther** [comment]
I wish a defaults.h with all defaults not only the priorities.

problem with prios is, there is no one fits all solution. It always depends on what you want to achieve.
Now udpListener(700) is more important as boblight(900) - why?
It is ok when 2 inputs had same prio, as long as they don't send at the same time.
When working with multiple remotes (phone app, web) then a not wisely setted app prio can have funny effects.

**Comment by brindosch** [comment]
usually people would not change these priorities as long they don´t need it. So it is in our hands to set the right values for most common cases.

**Comment by redPanther** [comment]
> Enhance Json priority list with the name of which components have set that priority

then every setcolor/setImage has to be extended. Perhaps with an id that qualifies the sender.
The sender id can be stored in InputInfo struct of prioMuxer. 
before setcolor/setimage can be used, the component has to be register it's id to hyperion class. Then we can store a human readable string, that we can show in json list

**Comment by redPanther** [comment]
> Move all default priorities to a single default-priorities.h

instead of this we can add default values in json schema file.
... this is easier to maintain and get an overview over the values.
Exception for now are the leddevices. There we need some other extension for schema definition and checking. More thoughts on this later.

**Comment by redPanther** [comment]
from the 3 things mentioned in issue, last 2 things already implemented, The first things we do via json schema files. Sadly we can't get the default values in code, but we will get this work to ...

I would say, main objectives of this issues are full filled. I suggest a close.
(we can make a nue issue "set defaults form json schema" ... )

**Comment by penfold42** [comment]
Happy to close.
The objective has been met for item 1 - I don't really care where they are as long as it's consistent and not scattered across a dozen .cpp files !
