### ISSUE TITLE
Adalight fastled arduino file mod

### ISSUE THREAD

**Issue by iLLiac4** [hyperion-project/hyperion.ng#284]
Do someone knows how to implement this part of the code into this ino file.
The file that needs to be modified:
[https://github.com/hyperion-project/hyperion.ng/blob/master/assets/firmware/arduino/adalight/adalight.ino]

With the logic from this file [https://github.com/iLLiac4/Adalight_Hyperion/blob/master/Adalight_WS2801_Mini_Pro_32u4.ino] that uses SPI.h logic which turns off the lights if no data is received for some time.

`      // If no data received for an extended time, turn off all LEDs.
      if((t - lastByteTime) > serialTimeout) {
        for(c=0; c<32767; c++) {
          for(SPDR=0; !(SPSR & _BV(SPIF)); );
        }
        delay(1); // One millisecond pause = latch
        lastByteTime = t; // Reset counter
      }`

**Comment by iLLiac4** [comment]
Ok i did it so you can use it and test it.
https://github.com/iLLiac4/Adalight_Hyperion/commits/master/experimental.ino

**Comment by redPanther** [comment]
I did some changes to our version inspired by your file:
https://github.com/redPanther/hyperion.ng/blob/bugfixes/assets/firmware/arduino/adalight/adalight.ino

I'm preparing a pr, if you want to test the sketch ...

**Comment by iLLiac4** [comment]
I have tested it and it seems to work.

 

There is also one ino file in my repo that can use adalight protocol and ordinary rgb led stripe. I have named it poors man ambilight because it will cost no more than 10usd. It is meant for arduino. https://github.com/iLLiac4/Adalight_Hyperion/blob/master/Adalight_RGB.ino

The wirinig can be the same as http://www.forum-raspberrypi.de/Thread-hyperion-tutorial-ambilight-mit-standard-led-strips but this one is not for RPI but for Arduino.

 

http://www.forum-raspberrypi.de/attachment.php?thumbnail=5870

**Comment by iLLiac4** [comment]
Also yesterday i have found premade wifi controller http://www.banggood.com/ARILUX-AL-LC01-Super-Mini-LED-WIFI-Smart-RGB-Controller-For-RGB-LED-Strip-Light-DC-9-12V-p-1058603.html?p=VD18093452842013112L  (it has to be from 5v-28v) that is based on esp2866. I am planning to mod it to accept ordinary stripes rgb and also ws2801 or. Apa102.

Yesterday the rgb support was added into https://github.com/SciLor/ESP8266_Hyperion_LED-Controller/tree/develop and have tested it and it works.

**Comment by redPanther** [comment]
I will add analog output to arduino sketch. Thx for inspiration

**Comment by redPanther** [comment]
I added analog output ... I tested with a simple rgb led, but adding a bigger led installation would work too ;-)

looks quite nice

**Comment by iLLiac4** [comment]
Looks good. One ino for all devices. The only thing is that user interaction is also needed  after 
/**************************************
   A D A L I G H T   C O D E
   no user changes needed
 **************************************/
 to set leds type, so it can be a little distracting for some users.

Maybe also you can adopt my file https://github.com/iLLiac4/Adalight_Hyperion/blob/master/Ambilight.fzz to visualize the wiring. If you want i can modify the schema to reflect your changes and add rgb stripe.

**Comment by redPanther** [comment]
I know ... some cleanup is needed and I'm not ready yet. 
I want to add another mode to get the  analog rgb values. Currently we have average over all leds. This is nice, but I think this is not suitable for every situation.

 I will add a new mode that takes rgb from last led.
Then in hyperion you can configure standard ambilight led strip with lots of leds and then add one led at the end that takes the image area for analog stripe.

On arduino the num_leds-1 send to fastled for you adressable stripe and the last led value goes to analog.

Cool thing about this is that you can drive 2 stripes (analog and digital) with one hyperion instance and one arduino.

Another thing I'm thinking of is to support a analog white channel. Then you can connect a ttl controlled 230V dimmer to control e.g. your old fashion bulb lamp.

**Comment by penfold42** [comment]
Have you guys looked at the piblaster support I reworked a few months back ?
PWM straight from a Pi with up to about 20 channels that can each be fed r, g, b or w from a Hyperion led

**Comment by redPanther** [comment]
Yes I see, but piblaster is not available on my x86 system ;-)

**Comment by redPanther** [comment]
@iLLiac4 can we close this issue?
