### ISSUE TITLE
Update Hypercon to work with hyperion.ng

### ISSUE THREAD

**Issue by rudelm** [hyperion-project/hyperion.ng#291]
Hi,

it seems that the current Hypercon from your project page generates incompatible json files with hyperion-ng on a mac. I always see these error with a fresh configuration made in Hypercon:

`hyperiond hyperion.config.json
[root].bootsequence: no schema definition
[root].endOfJson: no schema definition
[root].xbmcVideoChecker: no schema definition
[root].color.smoothing: no schema definition
[root].color.temperature: no schema definition
[root].forwarder: missing member
[HYPERIOND MAIN] <ERROR> Hyperion Daemon aborted:
  ERROR: Json validation failed
[HYPERIOND MAIN] <ERROR> Hyperion aborted:
  Hyperion::getInstance used without call of Hyperion::initInstance before`

Is there maybe a newer version of Hypercon available? Otherwise the documentation needs to be improved as I didn't found a thing regargind the LED configuration, especially their positioning.

An older working config from Hypercon with the old hyperion produced the same error.

**Comment by penfold42** [comment]
This is expected and unlikely to be fixed.

Hypercon should be irrelevant as Hyperion.ng has a web based config tool

**Comment by brindosch** [comment]
Greetings,
as penfold42 stated: HyperCon won't get any update. And as long .ng is alpha/incomplete there will be no documentation available.
I had the hope to complete ng until the end 2016. But we are "understaffed" so the process is slow.

FYI The led positions are shown("explained") here
![ledschema](https://cloud.githubusercontent.com/assets/15967679/20411830/8888be54-ad23-11e6-87fa-43a60ee43dff.jpg)

**Comment by rudelm** [comment]
Thanks! I wasn't aware there's a web based configuration tool. Are there any instructions on how to use and configure that web interface? I didn't found a clue on github nor the forums but would be glad to document it once I know how it is used.

**Comment by tpmodding** [comment]
<ip>:8099

**Comment by redPanther** [comment]
The webinterface is not ready yet. You can do several things with it, but it is not complete. E.g. led layout config is not ready. You can generate led layout with hypercon and than take leds section from old config to new config manualy.

**Comment by rudelm** [comment]
thanks for the fast response! The web interface is already looking good 👍 Good to know that I can take over the led layout from hypercon. I think this can be closed now.

**Comment by redPanther** [comment]
Btw start hyperion with 
hyperiond --debug /your/config.here
Then you will see all intresting output.

Also hyperiond --help for all commandline options.
