### ISSUE TITLE
Add "enable" option to all components

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#3]
All components should be able to be enabled/disabled with a option, to keep the .json clean (no comment out or removal of options to disable it)

- [x] Smoothing
- [x] All Grabbers
- [x] V4L2 (v4l2 could be used at the same time with the other grabbers - so this section will be there anyway)
- [x] blackborder 
- [x] kodicheck
- [x] boblight
- [x] proto json forward
- [x] UDP listener (server)

**Comment by redPanther** [comment]
All (mentioned) objects should be created on startup.
They should have a start stop method. 'enable' calls start if enable true.
With this approach we can dis/enable all components at runtime

**Comment by brindosch** [comment]
Hm, so we should use this to stop the grabbers? Code duplica.
We need a class which select and set the current grabber  anyway before startup the components, maybe a small info log output which platform  was detected

**Comment by redPanther** [comment]
Platform is the wrong term here. Capturing device is better. This is not neccessarily bound to a specific platform

**Comment by penfold42** [comment]
Add zeroconf and UDP listener to the list ?

**Comment by brindosch** [comment]
Yes, i added this already to the code pattern. I will add it here too

**Comment by redPanther** [comment]
did we need 'enable' for InitialEffect? This is not an own component like the other. From view of web-config we could provide a enabled/disable, but from a technical point it makes less sense to have it in the config file. (and the config file is more or less for 'pro' people, like firefox settings dialog vs. about:config)

**Comment by brindosch** [comment]
We could handle that :)
