### ISSUE TITLE
use qt5 json

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#31]
Now we use qt5. Qt5 brings native support for json parsing - use this instead of our external lib jsoncpp

http://doc.qt.io/qt-5/json.html
http://stackoverflow.com/questions/15893040/how-to-create-read-write-json-files-in-qt5

**Comment by brindosch** [comment]
@Paulchen-Panther 
:)
Not sure if he already use this for the next PR.

**Comment by redPanther** [comment]
Switching to qt-json is a big thing. Lots of files and cmake code are involved. Then our minimum qt version is qt 5.7.

**Comment by brindosch** [comment]
qt 5.7? this is a little bit too high for the moment. Even if you installed - like me - a fresh ubuntu 16.04 it is too old.
https://packages.debian.org/de/sid/qt5-default
https://launchpad.net/ubuntu/xenial/+package/qt5-default

**Comment by redPanther** [comment]
I understand something wrong .. I have to go to bed. We have to look since when it is available

**Comment by brindosch** [comment]
good night :)

**Comment by brindosch** [comment]
if i follow the this link and click at the bottom on the classes they say since QT5.0
So we could use it
@Paulchen-Panther

**Comment by Paulchen-Panther** [comment]
please read this: https://www.reddit.com/r/cpp/comments/2380pg/benchmarked_performance_of_c_json_libraries/

**Comment by brindosch** [comment]
So we should stick with jbson cause jsoncpp is horrible slow?

./jsoncpp-parser-testrunner data/medium-dict.json
[+] Finished successfully with an average of: 121035 us
mem: 44,224 K

./qjsondocument-parser-testrunner data/medium-dict.json
[+] Finished successfully with an average of: 82839 us
mem: 37,996 K

./jbson-parser-testrunner data/medium-dict.json
[+] Finished successfully with an average of: 64800 us
mem: 24,708 K

**Comment by Paulchen-Panther** [comment]
QJsonDocument couldn't handle the large test very well

**Comment by Paulchen-Panther** [comment]
we need to test it

**Comment by redPanther** [comment]
is our config a large testfile? our json stuff is not time critical - so speed doesn't matter

**Comment by Paulchen-Panther** [comment]
ok

**Comment by Paulchen-Panther** [comment]
we use it

**Comment by brindosch** [comment]
windows hyperion we are coming anyway :P

**Comment by brindosch** [comment]
We may need a list for all json code areas to remove everything from jsoncpp

**Comment by penfold42** [comment]
What's wrong with jsoncpp ?
It seems like a large change for little benefit

**Comment by brindosch** [comment]
// Uh, this is not done yet :)
@Paulchen-Panther 
if you are bored :)

**Comment by Paulchen-Panther** [comment]
Nein. Dachte eigentlich redPanther wollte das zu Ende führen? Wenn nicht mach ich das noch nebenbei. Hab gerade viel Arbeit um die Ohren, sorry.
