### ISSUE TITLE
Auto correction for json validation

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#319]
Hyperion should: delete single keys out of .json that are not available in schema instead of quit.
Add new keys, if there are new keys in schema but not in json.

**Comment by Paulchen-Panther** [comment]
Darf ich das übernehmen? ;-)

**Comment by brindosch** [comment]
Gerne :)
Ich hab festgestellt, dass der editor mit setValue "neue" keys wieder löscht. die zuvor nicht in der .json waren. Da muss man leider ansetzen, wenn man Hyperion mal updaten will.

**Comment by Paulchen-Panther** [comment]
Reden wir da gerade von der config oder den Effekten?

**Comment by brindosch** [comment]
Beim leddevice und framegrabber muss man aber aufpassen, sonst löscht der da Felder. Ich denke die könnte man auch aussparen. Da diese sich nach dem ganzen Umbau kaum noch eine Änderung erfahren werden.

Von der hyperion.config.schema
Wegen den Effekten muss ich mal schauen, wir hatten ja gestern das Thema Feld-Abhängigkeiten mit eventuell gewollt unvollständigen Datensätzen.

**Comment by brindosch** [comment]
Oh noch einen kleinen bugfix, bevor Effekte geschrieben werden, sollte man dringend überprüfen, ob ein Name angegeben wurde. Es ist nämlich möglich Effekte ohne Namen zu speichern. Den kann man aber nicht mehr löschen. (Sollte jemand drittes da auch eine ui für basteln)

**Comment by Paulchen-Panther** [comment]
Danke. Das werde ich mit berücksichtigen.

**Comment by Paulchen-Panther** [comment]
Nach [Zeile 489](https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/jsonserver/JsonClientConnection.cpp#L489) das hier einfügen:

`if (message["name"].toString().trimmed().isEmpty())`
`{`
`	sendErrorReply("Can't save new effect. Effect name is empty", command, tan);`
`	return;`
`}`

**Comment by brindosch** [comment]
Im offenen PR, danke :)

**Comment by brindosch** [comment]
@Paulchen-Panther 
Wie schauts aus?

**Comment by Paulchen-Panther** [comment]
close?

**Comment by brindosch** [comment]
Yup!
Es geht wieder voran ;)
