### ISSUE TITLE
Move to qt5-serialport

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#32]
We should replace our 3th party serial port library with serial port implemention from qt.
This shouldn't be hard, because serial port is used only in leddevices and they have a parent class with serial stuff.

Why?
- delete code in hyperion, deleted code is good code :-)
- better platform independent
- qt serialport is better tested
- we can use signal/slot from qt to be more event driven

**Comment by redPanther** [comment]
Serialport migration is nearly done. 

Can somebody tell me which sketch is the best for arduino + hyperion + ws2812?

**Comment by brindosch** [comment]
One way: our forum, tut section, ricks post. There is a sketch which usually works

**Comment by redPanther** [comment]
thx it worked, but I would suggest to set baudrate to 115200 as default. The current default was to slow for me and didn't work.

**Comment by brindosch** [comment]
We need a thread for the usage and where are the limits. People should share their informations :)
