### ISSUE TITLE
Send grabber screenshot to WebUI

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#320]
It would be great if we can display the screenshot of the grabber in LED Configuration just like in HyperCon. So can we transfer the screenshot as base64-Data? Maybe not via websocket because of data size. Maybe with http. 

Can someone tag this as an enhancement please. I can't. ;-)

**Comment by brindosch** [comment]
Before you take Screenshots you should apply user specific settings (to be HC a replacement)

**Comment by penfold42** [comment]
I love this idea.

:8099/grabber/snapshot.jpg

**Comment by redPanther** [comment]
impleneted!
screenshot is send via websockets as base64 jpeg. http based sending is not so easy atm ... 
close?

**Comment by brindosch** [comment]
This question points to a solution for live-screenshoting v4l2 during runtime (eg change crop values and look again at the result))

**Comment by b1rdhous3** [comment]
And I think we have the right solution. So yes I think we can close.
