### ISSUE TITLE
Effect override JSON file but use inbuilt .py ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#322]
Should this work ?

It seems I need to provide the python file myself if I use my own json file

**Comment by penfold42** [comment]
It does work if you specify the python script with a leading : 
If you wanted an aqua snake .json file to use the inbuild snake.py it would look like this:

```
{
        "name" : "Snake Aqua",
        "script" : ":snake.py",
        "args" :
        {
                "rotation-time" : 10.0,
                "color" : [0, 255, 255],
                "percentage" : 25
        }
}
```

**Comment by brindosch** [comment]
This is the way it works? The configurator just supports inbuild pys for now.
You can't switch between internal and external python file currently.

// you got it. Ah, you don't like the configurator :)

**Comment by penfold42** [comment]
My IDE consists of screen running on my Pi 
Screen 1 - vi
Screen 2 - make -j2
Screen 3 - build/bin/hyperiond --debug

What do you think I think of the configurator !

Jokes aside, Where does the condigurator store its effect configs when I hit save ?

**Comment by brindosch** [comment]
Your effect path
For deployment we specific "../custom-effects" to store them.

**Comment by brindosch** [comment]
A bonus to use the configurator instead of editing yourself is a live preview before you save and a auto reload of the effect list. Well implemented

**Comment by penfold42** [comment]
it is cool - I was using the live preview to fiddle with my candle stuff

I've found a bug tho - it writes to the first effect path - i have multiple and it was failing

**Comment by brindosch** [comment]
Maybe we should limit writing to the first path (which is usally the custom-effects path (later))
