### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by tociek** [hyperion-project/hyperion.ng#325]
Hi,

I tried to compile newest version, but I'm getting the following error:
make[2]: *** No rule to make target '../assets/webconfig/lang/de.json', needed by 'libsrc/webconfig/qrc_WebConfig.cpp'.  Stop.
CMakeFiles/Makefile2:1297: recipe for target 'libsrc/webconfig/CMakeFiles/webconfig.dir/all' failed
make[1]: *** [libsrc/webconfig/CMakeFiles/webconfig.dir/all] Error 2

Any help would be highly appreciated :)

**Comment by penfold42** [comment]
I had this - I can't remember if rerunning cmake  fixed it or blowing the build for away fixed it

**Comment by redPanther** [comment]
cd build
rm *.qrc

**Comment by tociek** [comment]
that worked
thanks!
