### ISSUE TITLE
Online help in web interface 

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#326]
We should add some !

Should it local or links to an online wiki ?

I prefer the linking online approach as it means we can update it much more quickly.

Can we use the localisation tags as keys for these links ? If we're diligent with them we could have in context help at a form level, a field level, effect options and so forth.

**Comment by redPanther** [comment]
Vote for online wiki!

**Comment by brindosch** [comment]
I would prefer a hybrid. We have so much space, what shall we do with it :)
I thought about placing on the right side of each editor a quick explanation for all options. (maybe hideable or collapsable). 
People are lazy, there is enough space, and the chance that a sentence for an options needs immediately an edit is near zero AND! Its always in sync with your version. (This syncing thing was also a problem with hypercon)

I hate Wiki edits, i would strip it down to generic stuff (exception developer docu, which needs always edits and don't fit at the webui).

Where no space is left or if advanced topics are available (for example an explanation how the led hscan vscan works and led devices) we could refer to a wiki.

I did the entire HyperCon docu EN/DE and i fear what is coming. Cause the workload to keep every single line in sync is just annoying

**Comment by penfold42** [comment]
Can we do hybrid based on a wiki ?

Scripts to dump some of the content locally and either build in to the binary or serve up as static HTML from the web server.

**Comment by redPanther** [comment]
we should install the html/jpegs for online help to share/hyperion/doc. The webui can route into that folder and dispaly help. When doc gets biger in size we can split the package into "hyperion" and "hyperion-doc" if we want

**Comment by brindosch** [comment]
Static htmls for option explanations is also not so smart, again you need to duplicate them in different languages. And let the people translate html files is not that nice which is also very error sensitive (html)

Static html pages don't need to be included, thats more a job of a wiki software to generate them (sphinx for example) and work with external links.

I thought a little bit again about my idea of single options explanations.
To prevent duplicated text (eg option titles!) It's maybe smarter to reuse them on the right side. Well it bloats the translation files slighty as you need a sentence for each option, but i think its much smarter this way. 
Creation could be a loop through the schemas or editor gathered informations which scales automatically up and down. Just a new key for i18n needs to be added for the text (sentence) part

**Comment by redPanther** [comment]
the current implemented solution is quite good. I  think this is the way we should go. Additionally we should have tutorials/wiki on our website for more detailed things (e.g. hardware setup)

can we close this issue?

**Comment by brindosch** [comment]
Thank you,
 i wanna include wiki hints that are displayed in settings container at the bottom. led devices and eff configurator are special and i am not sure if i implement this in another way. For example effects could be sorted into: led matrix only, classic leds and led matrix or classic leds only to give proper advices.

We'll see, if everything is done we create a new wiki, the current solution will be dropped.
A big thing is to find a good wiki software. There are a lot out there, but if it comes to multi lingual support i see just one solution currently...

**Comment by brindosch** [comment]
So i think the current state is good for basics. When everything is done we just need to talk which wiki software we should use from possible from huge systems like mediawiki down to simple markdown in a own github repo.
There are a lot of solutions, ideas are appreciated.

/closed
