### ISSUE TITLE
Udplistener bonjour advertises tcp port 0 when disabled

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#327]
Probably not cool.

Should I move the bonjour stuff from Hyperion and into the udplistener so it can control its own advertisements ?

**Comment by redPanther** [comment]
I think so. Every component that can be disabled should manage it's bonjour stuff. Perhaps when component disabled, advertisment can be stoped?

**Comment by brindosch** [comment]
UdpListener is currently not available. Will close for the moment
