### ISSUE TITLE
Move led device name to be a global instance name?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#328]
This should really be an attribute of the Hyperiond instance and not the led device.

Thoughts ?

**Comment by redPanther** [comment]
I thought this from my first hyperion experience ... I prefer we make a new section "general" and move the name (rename it to hyperionID?) into it. We could also move the leg level into that section ... Later on we can add something like "update notification" and "update notification mail" to send a mail, when a new version is out. ....

**Comment by brindosch** [comment]
> leg level into that section

I think we should keep the loglevel where it belongs to :)
Email notifications are a good idea.

**Comment by redPanther** [comment]
close?
