### ISSUE TITLE
Remove widget dependency

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#33]
Nothing should need it ?

It's big and it forces othe install dependencies with break OSMC without fixing it's library path

I've started trying to do it without knowing what I really doing

**Comment by penfold42** [comment]
Can you guys check out what ive done?
https://github.com/penfold42/hyperion.ng/tree/remove_widgets

# before
 ldd build/bin/hyperiond | wc -l
40
ldd build/bin/hyperiond | grep -i qt
        libQt5Network.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5 (0x76dd9000)
        libQt5Widgets.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5 (0x76713000)
        libQt5Gui.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5 (0x7641e000)
        libQt5Core.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5 (0x7608c000)

# after 
ldd build-nowidget/bin/hyperiond | wc -l
33
ldd build-nowidget/bin/hyperiond | grep -i qt
        libQt5Gui.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5 (0x76ca3000)
        libQt5Network.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5 (0x76b6f000)
        libQt5Core.so.5 => /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5 (0x767dd000)

**Comment by penfold42** [comment]
And less memory used too:
# before
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
25039 root      20   0  120600  16716  13544 S   2.3  2.2   0:00.49 hyperiond
# after
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
25076 root      20   0  114896  13768  10944 S   1.3  1.8   0:00.41 hyperiond

**Comment by brindosch** [comment]
Sounds good, and if you ask me. We don need it regarding to this
http://doc.qt.io/qt-5/qtwidgets-index.html

**Comment by redPanther** [comment]
looks good here - waiting for a PR :-)

**Comment by brindosch** [comment]
Use we qtGui for image processing?
http://doc.qt.io/qt-5/qtgui-index.html

**Comment by brindosch** [comment]
ignore the last message, for sure we do. low level api to access the system

**Comment by redPanther** [comment]
search for qimage ... lots of findings in the code ... answer: yes

**Comment by brindosch** [comment]
thinking > writing :)

**Comment by Paulchen-Panther** [comment]
Was ist mit den testfiles? Die könnte man doch auch zusammen fassen. Oder entfernen. Oder ...

**Comment by brindosch** [comment]
we talk about the test dir?
https://github.com/hyperion-project/hyperion.ng/tree/master/test

**Comment by brindosch** [comment]
so i tested now your branch. It works so far.
Sadly libqt5gui5 still needs deps of 86MB :)
But we save some memory! Which is good.

**Comment by redPanther** [comment]
I just make the move to qt5-serialport. we will need 100k more ....

**Comment by brindosch** [comment]
Why, why you destroy my dreams! :)

**Comment by redPanther** [comment]
dreams ... good idea :-)

**Comment by brindosch** [comment]
100k? You joke
-> libqt5serialport5
4113kB!

**Comment by penfold42** [comment]
I wonder if a move to a static binary would help ?

We clearly need bits of qimage, but we don't care for the distributions dependencies

**Comment by brindosch** [comment]
If you have a look at openelec deps it should work. We provide no more.
But i am not sure how we could prevent the install of all this deps.
https://sourceforge.net/projects/hyperion-project/files/release/hyperion.deps.openelec-rpi.tar.gz/download

**Comment by redPanther** [comment]
@brindosch 
why you qt libs are so big? are they debug libs? unstripped?
Here is a list of my 64bit x86 libs:
sorted by size, sizes are in kb. My qtgui have only 4.4Mb !!! not 86Mb as yours
```
24      ./libQt5Concurrent.so.5.2.1
108     ./libQt5SerialPort.so.5.2.1
116     ./libQt5QuickTest.so.5.2.1
164     ./libQt5Test.so.5.2.1
212     ./libQt5Positioning.so.5.2.1
236     ./libQt5Sensors.so.5.2.1
240     ./libQt5Xml.so.5.2.1
252     ./libQt5Sql.so.5.2.1
264     ./libQt5WebKitWidgets.so.5.2.1
308     ./libQt5Svg.so.5.2.1
400     ./libQt5OpenGL.so.5.2.1
404     ./libQt5PrintSupport.so.5.2.1
508     ./libQt5DBus.so.5.2.1
572     ./libQt5Help.so.5.2.1
588     ./libQt5QuickParticles.so.5.2.1
1096    ./libQt5CLucene.so.5.2.1
1296    ./libQt5Network.so.5.2.1
2420    ./libQt5Script.so.5.2.1
2500    ./libQt5DesignerComponents.so.5.2.1
3548    ./libQt5Declarative.so.5.2.1
3624    ./libQt5Quick.so.5.2.1
4116    ./libQt5Qml.so.5.2.1
4404    ./libQt5Gui.so.5.2.1
4756    ./libQt5Core.so.5.2.1
5104    ./libQt5Designer.so.5.2.1
6308    ./libQt5Widgets.so.5.2.1
34044   ./libQt5WebKit.so.5.2.1

```

**Comment by penfold42** [comment]
Remember there at the dependency on the libs themselves at a binary level and then there's also the distributions package dependencies which will usually include stuff we don't specifically need

**Comment by brindosch** [comment]
Sorry, yes @penfold42 
the gui package installs 86MB, so approx 95% libs we don´t need (?)

Is there a way to prevent this and just install what we really need?

**Comment by Paulchen-Panther** [comment]
Compiliert doch qt5 selber. Da gibt es bestimmt genug was deaktiviert werden kann.

**Comment by redPanther** [comment]
For distros with packagemanager, we should take deps from there. Deps delivery we should only do on openelec. Libreelec people dont want our bins, they handle it.

We can think about create static bins for openelec, but we dont save any bytes with that method.

**Comment by penfold42** [comment]
We should, but there's a lot of bloat that comes along for the ride.

Is the working memory much different for a shared vs dynamic exe ?

**Comment by brindosch** [comment]
so, widgets was removed. for the moment we live with the bloat. I would remooned to avoid "qt-defaults" cause it really installs everything like docs, sql and so on
