### ISSUE TITLE
Windows 10 linux subsystem limits

### ISSUE THREAD

**Issue by XfableX** [hyperion-project/hyperion.ng#330]
I have recently compiled Hyperion off of windows 10 using the Linux subsystem.
So far I know it works over wireless LED devices, the web interface works and the app works but have yet to find what does not. So far I have found that the Subsystem cannot see USB ports which will be a limitation.
Can more people try and discuss their findings with the subsystem?

**Comment by tpmodding** [comment]
awesome. did not know that its possible! windows system should work with com-port connections and an arduino?

**Comment by redPanther** [comment]
We use qt, it should be possible with some modifications regarding #include to compile with visual studio. But the big question, who wants to make the support job.

**Comment by XfableX** [comment]
Unfortunately I haven't really used visual studio at all but I can give it a try.

**Comment by redPanther** [comment]
I will close this issue ... we know now the it basicly works. Windows is currently not our development focus. More discussions to that topic can be  done at https://hyperion-project.org/
