### ISSUE TITLE
Reserve a Prio-Range for WebUI

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#331]
I've set my v4l2-grabber to prio 1 and wasn't able to set colors or effects from webui because they all use prio 1.

So just a thought: Shall we reserve a range of prios for our internal stuff?

**Comment by redPanther** [comment]
We schould limit settings to higher 1 and lower max int -2. But only in webui. If somebody does this willingly with a editor in config file ....
 we can't prevent that people doing stupid things.
Perhaps setting min/max in grabber schema do the job. Then also manual config edit is catched

**Comment by tpmodding** [comment]
the idea with the webui limit is good! we can not decide which priority have to use others :)

**Comment by brindosch** [comment]
Don't mess around with priority!
That's it https://github.com/brindosch/hyperion.ngBeta/commit/306400536920c2b7af720d296e792ec936838c15
