### ISSUE TITLE
Problems with Lightberry APA102 and the new Device merge

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#332]
As some people of you already know I have problems with my Lightberry Setup and hyperion.ng. On hyperion everything is fine. 

The problem is: 
At 3/4 of the in hyperion.ng defined LEDs one LED will flicker red and the led after that is purple. After that everything is black. 
Firstly I searched at the Lightberry Sketch without success. Then I noticed when I turned off the new "lightberry mode" which came with PR303 all LEDs are turning on again. (Not right color and more than defined but they turn on atleast)

So I checked out PR302 with the old adalightapa102 device before the merge, compiled it and everything works fine again like in hyperion (without .ng)

So I think there is a problem in the merge (PR303) in the part for "lightberry mode".
#303

**Comment by redPanther** [comment]
I'm on it. It's a merge problem.  Did you use this sketch?
 https://github.com/hyperion-project/hyperion.ng/blob/master/assets/firmware/arduino/adalightapa102/LightberryHDUSBAPA1021.1.ino

**Comment by b1rdhous3** [comment]
Nice, thank you!

At the moment I only tested with the newest from http://update.lightberry.eu
I can test the other as well.

Here is a diff between those:
https://www.diffnow.com/?report=6t87g

Can you say which should be used?

**Comment by redPanther** [comment]
stupid thing ... adalight device was never in lightberry mode, because config parameter was evaluated after init.
shoud be fixed now

**Comment by b1rdhous3** [comment]
It is working. :)

Thank you so much for the very fast fix!
