### ISSUE TITLE
HSL luminancegain is buggy

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#338]
I have a large xmas led display with 600+ LEDs and I need to reduce the overall brightness.
With hsv  "valueGain"    : 0.1000 it worked great and continues to work great with #336 

With hsl "luminanceGain"    : 0.1000, it doesnt work well 8-(

If you set colours at the higher end of the brightness range - greater than about f8f8f8 it starts getting the resulting colour data wrong. 
1st column is requested colour, 2nd is the resulting led data sent:
```
ffffff	191919	perfectly fine
fffffe	323200	blue gone, red + green are double
fffeff	320032	same issue
feffff	003232	same issue
fefeff	000032	red and green missing
	
fefefe	191919	fine
fefefd	212110	blue is half gone, red and green to high.
```

am i missing something about the HSL colour space here?

**Comment by redPanther** [comment]
It looks like precision/rounding problems

**Comment by redPanther** [comment]
BTW luminanceGain 0.1 ??? My lights are nearly off. First value that is ok is 0.4.

**Comment by redPanther** [comment]
can anybody try my branch:
https://github.com/redPanther/hyperion.ng/tree/hsltest

I've took conversion methods from:
https://www.programmingalgorithms.com/algorithm/hsl-to-rgb?lang=C
https://www.programmingalgorithms.com/algorithm/rgb-to-hsl?lang=C

perhaps that helps ;-)

**Comment by penfold42** [comment]
Will try it today

0.1 is fine if you have a 750 led Xmas display and don't want to blind passing drivers !

**Comment by redPanther** [comment]
> blind passing drivers 

ok, I guess the strobe effect is also not perfect for passing drivers :-)

**Comment by penfold42** [comment]
I think I could dazzle planes at 3000 ft

**Comment by redPanther** [comment]
or santa when he's comes by. ok now i understand the sense of extensive xmas lights. so long, gn8

**Comment by penfold42** [comment]
At a quick look it is still broken.

Im wondering whether hsl scaling will ever work - it's quite possible the different co-ordinate systems need infinite precision at the top and bottom of the HSL shape.

**Comment by redPanther** [comment]
I changed the precision from float  to double. Can you try again?

If this not working we can made lookup tables for the top and bottom values ....

**Comment by redPanther** [comment]
Instead of  a threshold we can convert to hsv when threshold is reached. Transformation is easy ...
http://codeitdown.com/hsl-hsb-hsv-color/
At the ond of the page

**Comment by redPanther** [comment]
Just another idea: when hsl transform is called we can convert it to hsv and do hsvtransform. The we get the natural lightness curve we want and perhaps we dont have precision problems

**Comment by redPanther** [comment]
while digging into this topic I realized that hsv transform in our code is mainly integer based. Perhaps that explains that this is more stable than hsl. In theory it should be possible to transform the hsl to integer based math. 
So now we have several options to go further and hopefully some solution will solve this nasty thing.
Perhaps it is good to make a test version with all options implemented and you can switch between algorithms with hyperion-remote. Then it is better possible to compare and figure out whats the best

**Comment by redPanther** [comment]
@penfold42 can you test if thresholdHigh has the effect you want from luminanceGain?

BTW branch mentioned is my test branch. My branch for pr is
https://github.com/redPanther/hyperion.ng/tree/adjustmentMerge
You can also try this, but there are more config changes (look default config) and colortransform is removed.

**Comment by redPanther** [comment]
@penfold42 I think this is solved. the new "brightness" option with values from 0.5 and below should lower your brightness correctly
