### ISSUE TITLE
Relative effect path don't work with systemd

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#347]
I have seen this issue long before. Now i investigated some more.

If systemd starts hyperiond, realtive effect path don't contains new created effects. Hyperion itself talks about success.

If i copy the systemd ExecStart command and let it run from commandline it works.
If i start hyperiond directly without /usr/bin symlink it works also.

User is always 'pi' on a raspbian jessie (also for systemd)
Wonder if someone could confirm this.

**Comment by redPanther** [comment]
can you post your systemd service file?

**Comment by redPanther** [comment]
this
`WorkingDirectory=/path/to/hyperion`
must be set, otherwise it can't be working

**Comment by brindosch** [comment]
Ha! Added for later
https://github.com/hyperion-project/hyperion.ng/commit/81e06ef6a07f9fba2fe9ba81b56f123a796da953
Thank you!
