### ISSUE TITLE
Enhance priorities info

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#349]
- Remove "ActiveEffect" and "ActiveColor"
 - Add this information to a priority, when it is a effect or color
 - For a better overview add a "who set it" identifier (App, WebUI, System (for capture devices) which needs to be added to your request (eg color, effect and proto sources)

An example
```
origin : AndroidApp
type : color
value : color values, duration
priority : 200
ip: 192.168.0.20

origin : Webinterface
type : effect
value : effect name, effect values, duration
priority : 250
ip: 192.168.0.22

origin : System
type : dispmanx
priority : 800

origin : HyperionScreenCap
type : proto
priority : 900
ip : 192.168.0.20
```

 - 'value' is just used for effects and colors with additional inormations that has been shown in activeEffect, activeColor
 - Duration is moved to 'value' due to the point a capture has no duration.
 - 'origin' is a identifier which is delivered from a request or 'system' if it is nothing external. requests with a missing identifier are rejected
 -  'type' replaces the content of the current origin, if it's a effect, the field contains 'effect' and the same for color with the values.

So leave some feedback :)
With this change it's perfect :)
@redPanther @Paulchen-Panther

**Comment by penfold42** [comment]
Source ip address ?

**Comment by brindosch** [comment]
Possible, but i think it's not that handy if you could already place a name instead (to remember). If you use the android app on a tablet and smartphone you could confirgure the origin name to your needs.

Or you need a ip for something different than identify for yourself?

**Comment by penfold42** [comment]
Mostly for troubleshooting user problems on the forums. 

Things are going to get more complicated with home automation - nest, amazon echo, homegrown perl/python scripts etc...

**Comment by brindosch** [comment]
update example
@redPanther what do you think? If this is done, it's perfect for(almost)ever? Maybe after the color area is finished :)

**Comment by redPanther** [comment]
Yes, after color and webui saving
