### ISSUE TITLE
Expose json interface via python ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#352]
Is this a good idea ?

I want to disable smoothing from some effects and this approach might have some other useful applications

**Comment by brindosch** [comment]
Interesting idea,
i already thought how to get rid of smoothing in a good way. For some effects it's useful, others not so great (strobe for example). [Sometimes it could be slower or faster - but just for _this_ effect.]

**Comment by penfold42** [comment]
If no one can think of another use for the json interface, we could add a smoothing option to the effects schema

**Comment by redPanther** [comment]
Set smoothing on/off from within an effect is no prob, we just have to add a function to access hyperion setComponentState.
Changing smooth args is more work, because the args currently not changable on runtime.
I suggest to add on/off and dont care about the args yet'

**Comment by redPanther** [comment]
smoothing is exposed to effects now. I wouldn't expose everything to effects. If some specific command is needed we can add it. (=> new issue)
I think we can close this issue.

**Comment by brindosch** [comment]
Yes and if you push your idea to the next lvl @penfold42 you end with a "Plugin Python Engine". Which might be interesting :)
But this should be developed splitted from the effect engine anyway (looking to kodi C python api for missing inspiration :))

**Comment by penfold42** [comment]
Agreed but it might be better to simply write a python (and other languages) library to make external python scripts easier rather than extend the hyperion core python
