### ISSUE TITLE
toggle on/off multiple devices

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion.ng#353]
Hey guys, with the new webUI we can now do more things simpler...

can we add something that we can detect different instances by the config names and toggle them on/off or create scenes...
example:
scene 1:
ledLeft TV ledRight
scene 2:
         only TV

**Comment by brindosch** [comment]
> detect different instances

First, you need this. https://github.com/hyperion-project/hyperion.ng/issues/55
> by the config names

The issues is now, you can't search for zeroconf information from your browser. @penfold42 do we need a population list via json rpc for webui to switch between?

**Comment by redPanther** [comment]
Hyperion should search via zeroconf for other instances and populate it via json

**Comment by redPanther** [comment]
@penfold42 can you implement (or give hints) a function that searches for other hyperions via zeroconf. 
Then we can use this to expose infos via json api

**Comment by penfold42** [comment]
I probably won't have time for a while, but here is what influenced the existing advertise stuff:
https://doc.qt.io/archives/qq/qq23-bonjour.html#examplefortuneserverandclient

**Comment by brindosch** [comment]
>time for a while

As time goes by
Looking forward for information sharing :)

Webserver config write is a huge issues for multi instances now. As you need a webserver for each instance and you need to assign them to the right json port!

**Comment by redPanther** [comment]
I integrated bonjour browser and resolver:
https://github.com/redPanther/hyperion.ng/tree/bonjour
I bit difficult is that especially the resolver works async. Our json client is sync. Perhaps we have to make a async json call like:
1. webui query bonjour
2. webui gets "ok" for valid request
3. later on webui gets incomming json call for the requested list of hyperion services.

This methode is similar to our live streams for led/video preview

**Comment by brindosch** [comment]
Closed
As of: https://github.com/hyperion-project/hyperion.ng/pull/578
