### ISSUE TITLE
Limit priority range, priority recommendations

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#360]
Strict:
I suggest to limit the priority range from 0-997 (3 digits are enough and don't eat much space)
Where 0 is reserverd for foreground effect
Where 1 is reserved for webui

json rpc should check against this range, before apply it. For the webui blocking we could filter against "origin" :webui (when it's implemented :))

background-effect could be moved to 998
off to 999
Clear-all. Apply it for 1-997? As we could keep the background effect running.

Recommendations
Remotes 2-99 (50 as default, they could overwrite each other)
Capture devices (100-997)

**Comment by penfold42** [comment]
I don't think we should force anything.

Sensible defaults with good documentation explaining the convention should suffice.

I need to be able to override the webui - alexa Pi needs to be able to override pretty much everything for a few seconds

**Comment by brindosch** [comment]
> I need to be able to override the webui
Well, okay. But 0 is forbidden :) (many custom scripts use 0, and i don't want that a application block the webui
The reason for a max priority of 997 are table layouts if you list all priorities and than a 2147483646 plops up. Could be a issue on applications due to low space and it looks overstated :)

**Comment by redPanther** [comment]
we can limit the datatype of priority. currently it is int32 or int64 depending if we have 64 or 32 bit. We can change it to in16, than max prio is 32767

**Comment by brindosch** [comment]
This is also something i thought first, but a even lower number with 3 digits would look quite good in an overview but it needs more code.
It's a start :)

yes, it's just eye candy - nothing fundamental

**Comment by brindosch** [comment]
Okay, another crazy idea, to keep it simple.
uint8? It would be definitely enough, its just a matter of habit.

allocation:
platform capt. 250
usb capt. 240
boblight,udplistener 200
proto services 100-199
remote services 2-99
webui 1
foreground effect 0

Any concerns? I think it's better manageable (viewing)
And now don't argument you need more priorities than this!! ;D

**Comment by redPanther** [comment]
looks good, but max is 255 not 256

**Comment by brindosch** [comment]
of course! Edited
I will prepare the schemas.
It is not possible to change just one or some value/s to unit_8 right?

**Comment by redPanther** [comment]
to get the of prio in range, change prioritymuxer.h:
`	const static int LOWEST_PRIORITY = std::numeric_limits<uint8_t>::max();`
if your changes complete, I can change the datastypes in the whole code
