### ISSUE TITLE
RPi3 - restart from the webUI fails...

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#369]
This is logged to stout:
```
* failed to open vchiq instance
```
I ran it under strace:
```
root@loungepi:/home/penfold/github/hyperion.ng/build# grep vchiq /tmp/strc
open("/opt/vc/lib/libvchiq_arm.so", O_RDONLY|O_CLOEXEC) = 3
open("/dev/vchiq", O_RDWR|O_LARGEFILE)  = 30
open("/opt/vc/lib/libvchiq_arm.so", O_RDONLY|O_CLOEXEC) = 3
open("/dev/vchiq", O_RDWR|O_LARGEFILE)  = -1 ENOMEM (Cannot allocate memory)
write(1, "* failed to open vchiq instance\n", 32) = 32
```

are we missing a close() somewhere?

**Comment by brindosch** [comment]
I could recreate the `* failed to open vchiq instance` message much easier. start hyperiond via command line and request a restart :)

**Comment by redPanther** [comment]
currently grabber is not destroyed/closed at webui restart.

**Comment by redPanther** [comment]
Should be resolved

**Comment by penfold42** [comment]
I think is back - is it just me?

**Comment by redPanther** [comment]
there are no changes at relevant code for that issue - if the issue is still there, then it was never solved.

**Comment by Lyr3x** [comment]
its happening to me very time i restart with a fresh install...
