### ISSUE TITLE
webUI should remember led layout parameters

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#370]
Maybe we store these in the config file just for the benefit of the webUI?

If I want to repeatedly reconfigure the leds, maybe changing the the gap or depth settings I need to repeatedly enter all of the settings

**Comment by brindosch** [comment]
i implemented a browser based persist. I thought also placing it in config as the gui is than always in sync with your layout. 
Downside is the bloat and you need to upgrade the config - if - you remove or add a option.

@redPanther

**Comment by brindosch** [comment]
the browser based persist should work now..
