### ISSUE TITLE
V4L2 cleanup on restart?

### ISSUE THREAD

**Issue by Paulchen-Panther** [hyperion-project/hyperion.ng#373]
Kann es sein, das die V4L2 Devices nicht richtig abgemeldet werden im System?
Ich kann nämlich meinen V4L2 Grabber (hab den erst seit heute) nach einem neustart von Hyperion nicht mehr benutzen. @redPanther kannst du da mal schauen?
Im Code von Hyperion wird ja vor jedem neustart die function freeObjects aufgerufen. Dort ist aber nichts mit V4L2 zu finden.
Hier die Logausgabe vom start und restart: [pastebin](http://pastebin.com/whS74uxf)

Danke red. :-)

**Comment by brindosch** [comment]
Hey Paulchen!
Mal ne andere Frage, wie kommts denn dazu?
```
[HYPERIOND MAIN] <INFO> set screen capture device to 'framebuffer'
[HYPERIOND MAIN] <ERROR> The framebuffer grabber can not be instantiated, because it has been left out from the build
[HYPERIOND ComponentRegister] <INFO> Framegrabber: off
[HYPERIOND MAIN] <WARNING> No grabber can be instantiated, because all grabbers have been left out from the build
```

Hast du die mit Absicht rausgelassen oder ist das ein bug?

**Comment by Paulchen-Panther** [comment]
Kein Bug. Keine Sorge. Hab alles rausgenommen außer V4L2. Der Pi Zero soll lediglich die HDMI Quelle bedienen. Und damit das ganze ein klein wenig schneller compiliert hab ich die anderen raus genommen.

**Comment by redPanther** [comment]
Meinst du mit restart via webui oder mit systemd/strg+c auf konsole?

Bei restart via webui kann es sein das die destruktoren nicht korrekt durchlaufen werden. Werd mir das dietage anschauen

**Comment by Paulchen-Panther** [comment]
Ich meine die restart Methode per WebUI

**Comment by redPanther** [comment]
Ich werd da mal einen aktiven aufruf zum schließen von grabber und leds einbauen

**Comment by Paulchen-Panther** [comment]
Das wäre super. Vielen dank. Kann ich dir irgendwie helfen?

**Comment by redPanther** [comment]
was ich so auf die stelle rausbekommen hab, ist das der grabber beim restart via ui nicht freigegeben wird (die led hw hingegen schon). Leider hat das hyperion object kein zugriff auf das grabber object. Deshalb geht das nich mal eben so ... ich mach da mal was ...

**Comment by redPanther** [comment]
dup of #369
