### ISSUE TITLE
iOS Hyperion app needs updating for Hyperion.ng

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#379]
@ChaosCoder

We're getting close to feature complete with Hyperion.ng and the app will need some small changes:
Priority 0 is banned
Colour tuning model is all changed

**Comment by brindosch** [comment]
No at all...

**Comment by brindosch** [comment]
We have even no docu, now it's -not- integration time...
We came back to use when it's really time..

**Comment by ChaosCoder** [comment]
Yeah, would be nice to have a summary on all the changes that are required (like what is replaced by what, etc.). I will integrate the needed changes ASAP as I know what changed. What version number will hyperion.ng have, as in how can I detect I'm communicating with the new version?
