### ISSUE TITLE
Last two leds keeps brighted up. 

### ISSUE THREAD

**Issue by IIIdefconIII** [hyperion-project/hyperion.ng#388]
As of the latest version of yesterday the last two lights keeps lighting up. even after an --clearall statement. I went 1 version back and there is no problem there. Just wanted to report it

WS2801 with arduino nano

**Comment by redPanther** [comment]
we need some info:
- config
- which sketch for arduino
- amount of your real leds

**Comment by IIIdefconIII** [comment]
http://pastebin.com/t8C9smAG
(could upload it in zip somehow)

sketch = Adalight_FastLED_WS2801_Arduino_Nano

amount of real leds,

(left, 25 top, 40, right 21) could be  that the current config file is otherwise, but id checked this by updating the led count in webconfig before and it was still on

**Comment by redPanther** [comment]
pastebin is ok ... did you try our adalight sketch? 
https://github.com/hyperion-project/hyperion.ng/blob/master/assets/firmware/arduino/adalight/adalight.ino (you can lower the max leds if you havn't enough memory)

**Comment by IIIdefconIII** [comment]
no i didnt, i will try that, need to image the htpc box first and ill report back

**Comment by IIIdefconIII** [comment]
currently i use
  // Define Data Pin
  #define DATA_PIN 11
  #define CLOCK_PIN 13
  // Baudrate, higher rate allows faster refresh rate and more LEDs (defined in /etc/boblight.conf)
  #define serialRate 500000

the one youre propsing is
//#define LED_PINS 6, 13  // 4 wire leds

should i rewire stuff?

**Comment by penfold42** [comment]
You can leave the wiring - just change the pins in the code.

Also try 115200 - you could be getting bigger overruns so is a quick check

**Comment by IIIdefconIII** [comment]
it was indeed the led count that wasnt correct in the arduino sketch, i tought the higer baudrate the better? you can close this , ill still keep it open for youre anser :) TY!

**Comment by IIIdefconIII** [comment]
Your adalight.ino works also good now with 115200 but why is lower better?

**Comment by IIIdefconIII** [comment]
the new adalight.ino does work but i get random colours in movies also the boot effect which is normally red, is blue this time, have to go back untill this this is fixed :) further everything works fine

**Comment by brindosch** [comment]
> red, is blue this time

byte order switched?

**Comment by IIIdefconIII** [comment]
sorry red = green instead of blue, what section of the sketch should i change?

**Comment by redPanther** [comment]
Set colororder on the sketch and in hyperion to rgb.

**Comment by IIIdefconIII** [comment]
TY, at the moment you adeed this if found it xD its ok now, mm seems like this is better/nicer then the other ino file, could you simple explain in 1 rule about that baudrate? than this can be closed

**Comment by IIIdefconIII** [comment]
my reported issue before wasn't a real issue.

#388

On recommendation i changed to a other adalight.ino.

Now the problem is back, this time its pink.

Previously I changed the led count to from 124 to 85 and it worked (the last 2 leds went off)
With the new adalight.ino i changed define max leds to 85. But the last 2 leds are pink.
