### ISSUE TITLE
Min Brightness is not setting the leds to black

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#391]
I have an strange issue here. 
The last version I used on a daily base was the state of PR #340. Yesterday I updated to the newest PR.

Now when my screen is black the LEDs won't turn off (even the live video LED preview shows black for all leds). The LEDs are white with a lesser brightness. When I adjust the channel for black in this state over the webui the LEDs are switching to that new color. minBrightness is 0.
If I set black with the remote in WebUI the leds turn off. 
It confuses me because it worked without a problem at least to PR #340. 

So I use adalight in the lightberry mode. I am using the default lightberry sketch on the arduino inside the lightberry USB connector
This are my configs.
For PR 340 (Working): http://pastebin.com/n7QhMj9b
Newest (Not Working): http://pastebin.com/FpXz0JXT

**Comment by redPanther** [comment]
problem was I need a rgbsum>0 to avoid dividing by zero. I changed the logic a bit and now it should be fixed.
BTW when you remove comments in:
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/utils/RgbTransform.cpp#L91
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/utils/RgbTransform.cpp#L113
then you see incomming and outgoing colors. In this case incomming was 0,0,0 and outgoing 1,1,1 ... now it should be as black as the night (when backlight is off)
