### ISSUE TITLE
last 2 leds stays pink

### ISSUE THREAD

**Issue by IIIdefconIII** [hyperion-project/hyperion.ng#393]
my reported issue before wasn't a real issue.

https://github.com/hyperion-project/hyperion.ng/issues/388

On recommendation i changed to a other adalight.ino.

Now the problem is back, this time its pink.

Previously I changed the led count to from 124 to 85 and it worked (the last 2 leds went off) 
With the new adalight.ino i changed define max leds to 85. But the last 2 leds are pink.

**Comment by redPanther** [comment]
dont change max leds, unless you have to less memory. 
Would be great if you don't make such noise here, this is a bug tracker not chat room.
