### ISSUE TITLE
Collapse multiple 1 wire SPI drivers into 1 ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#396]
Should I collapse the different 1 wire spi drivers into a single device type with options for led type ?

Right now we have ws2812 and sk6812 which are 95% the same.
I'm adding sk6822 support and it's also basically the same.

Can we have multiple schema files reference a common underlying device driver ?
That would be cleaner as the web GUI would look like different strip types but the magic happens in cop with different strip parameters in a .h file.

**Comment by redPanther** [comment]
You can make a one wire spi provider that is derivated from spi provider. Then you can move most of the code into new provider.

**Comment by penfold42** [comment]
Can we have multiple schema files reference a common underlying device driver ?

I haven't looked at how they relate to each other yet...

**Comment by redPanther** [comment]
should be working like this:

take the schema files:
schema-sk6812spi.json
schema-ws2812spi.json

ws2812spi are the name of the class in lower case.
In factory class this name is connected to a device class through the REGISTER macro.
when those schema files above should point to same class, then
add new macro:
`#define REGISTER2(deviceName,className) LedDevice::addToDeviceMap(QString(#deviceName).toLower().toStdString(), LedDevice##className::construct);`
(perhaps you find a better general name then REGISTER2)

then add the devices:
```
REGISTER2(Ws2812SPI,OneWireSPI);
REGISTER2(Sk6812SPI,OneWireSPI);
```
in LedDeviceOneWireSPI you can read "type" from json config to get the info which led type is currently set

**Comment by tpmodding** [comment]
@Lord-Grey deine Meinung?

**Comment by Lord-Grey** [comment]
@tpmodding I put it to the backlog and need to think about it.

**Comment by Lord-Grey** [comment]
Close it for now.
