### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#4]
- [x] refactor UDP as seperate listener and remove it from the bootsequence and effect list

UDP should be a listener (clean) implemented like boblight
```
	"udpServer" : 
	{
		"enable" : false,		
		"port" : XXXXX,
		"priority" : 900
	},
```

**Comment by penfold42** [comment]
I'll do a native listener

**Comment by penfold42** [comment]
I've started.... https://github.com/penfold42/hyperion.ng/tree/udp_listener

I've literally cloned the boblight server and done one hell of a search and replace.
In fact, here's roughly what i did in case its helpful for someone else...

cp -a boblightserver/ udplistener/
mv BoblightClientConnection.cpp	UDPClientConnection.cpp
mv BoblightServer.cpp	UDPListener.cpp

mv BoblightClientConnection.h	UDPClientConnection.h
mv BoblightServer.h UDPListener.h


%s/BoblightServer/UDPListener/g
%s/BoblightClientConnection/UDPClientConnection/g
%s/boblightserver/udplistener/g
%s/BoblightClientConnection.cpp/UDPClientConnection.cpp/g
%s/BoblightClientConnection.h/UDPClientConnection.h/g
%s/BoblightServer/UDPListener/g
%s/boblightServer/udpListener/g
%s/boblightserver/udplistener/g
%s/BOBLIGHT/UDPLISTENER/g

**Comment by brindosch** [comment]
Great! If it works just remove the code from the effectengine (?) :)

**Comment by redPanther** [comment]
there wasn't any code regarding udp in effect engine. just a additional python script

**Comment by penfold42** [comment]
Correct - a hastily cobbled together Python script that I thought was worth sharing (and deleting shortly!)

**Comment by penfold42** [comment]
#48 
I think we can close this issue now?

**Comment by brindosch** [comment]
y
