### ISSUE TITLE
JSON RPC/Hyperion: Hyperion version number #2

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#41]
We currently output the full version/id string via JSON, but this is not really a version check, cause an app don´t need a github commit number and you need to sort this out during processing. Also this string just reflects the branch name, which lead to issues.

So we should provide a "hardcoded" version string which just outputs a app friendly formatted value to detect the real feature level of Hyperion. We should give the developers the possibility to react with another ui for example or just to show this easier.

**Comment by redPanther** [comment]
already prepared, this is needed for packagin (deb/rpm) too.
see https://github.com/hyperion-project/hyperion.ng/blob/master/cmake/packages.cmake
but need a bit tuning and then uses those cmake vars as defines ....
here on musescro you can see how they made it:
https://github.com/musescore/MuseScore/blob/master/CMakeLists.txt#L158

**Comment by penfold42** [comment]
What we really need is a manually configured Json protocol version.

Major.minor x.yyy

Bump the major version of its not backward compatible.

**Comment by brindosch** [comment]
Is there ususally always a check on apps which blocks apps on access? Currently there is no check possible so all old apps will still work?

**Comment by brindosch** [comment]
@penfold42 
could be closed or is there another solution available?

**Comment by penfold42** [comment]
Yep
