### ISSUE TITLE
JSON Interface is incompatible with Hyperion Remote Control App

### ISSUE THREAD

**Issue by KartoffelToby** [hyperion-project/hyperion.ng#416]
Any changes in the JSON remote syntax?

**Comment by brindosch** [comment]
Are you talking about the Android App?
Yes, broken entirely. There won't be control applications until we reach beta. 
Please consider this is pre alpha staged software, so the api will change here and there until we freeze it (beta). For the moment you could use the webinterface and hyperion-remote
