### ISSUE TITLE
Adjustments bugs

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#422]
For your next session @redPanther 
- Gamma of 0.0 results in white (raise min to 0.01?)
- maxBrightness of 0.0 results in 1.0 brightness (independet of minBright) (raise min to 0.01?). I vote for integer values anyway :)

**Comment by redPanther** [comment]
gamma 0 -> white is not a bug, its just what gamma does. But yes we should limit the range. Mostly gamma < 1 makes no sense in our case. will set the min to 0.1

here the gamma crve for gamma: 0-1 and 2
![gamma_curve](https://cloud.githubusercontent.com/assets/6893049/24251096/4c2c36c0-0fd9-11e7-8a9d-193e17880d39.png)
