### ISSUE TITLE
Web interface should provide power cable size recommendation

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#426]
http://www.nooutage.com/vdrop.htm

It would be great to incorporate this page via a link or use their JavaScript to recommend the required wire size based on some assumptions and the number of leds configured

**Comment by brindosch** [comment]
I think this is already too late (build-> install). We could keep the ampere for lazy people. I am working on a power supply calculator, your suggestion could be part of it. (Makes more sense to me)

**Comment by Lord-Grey** [comment]
Closing for now. Can be reopened on further demand.
