### ISSUE TITLE
Not all Hue recognized

### ISSUE THREAD

**Issue by Gamer106** [hyperion-project/hyperion.ng#429]
I've gotten Hyperion setup, and the WebUI breaks generally anytime I try to save/restart (Raspbian Jessie Pi3), and when it does restart it'll enter a failed state either due to not recognizing the devices, or not enough bulbs (easily fixable by editing the number in Index). Is there something I need to do so that more of the lights are discovered or recognized? I have 6 total. 3 Bulbs, 1 Bloom, 1 Go, and 1 Lightstrip. Only the Bloom, Go, and one bulb are recognized/working.

BEFORE YOU OPEN A NEW ISSUE!

Search at our wiki: wiki.hyperion-project.org
Our FAQ: https://hyperion-project.org/wiki/FAQ-Frequently-Asked-Questions
And have a look at our forum: forum.hyperion-project.org
If you need help please open a new thread their!

WE PROVIDE NO SUPPORT AT GITHUB!
All misleading issues will be closed without a announcement!

**Comment by b1rdhous3** [comment]
I can confirm this. After the newest PR's my hyperion starts for about 10 seconds and closes then. 
I think there is something broken with hue atm.

**Comment by Gamer106** [comment]
Ah, understood. That's what's happening when it eventually does work. They'll do the intro, then I can't calibrate the colors because they stop :(

**Comment by brindosch** [comment]
Please provide feedback at PR472, unrecognized ids are now properly logged.
