### ISSUE TITLE
Move all header files to include?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#43]
should we? theres 60 .h files in include and 60 .h files across src/ and libsrc/

find src/ libsrc/ -name \*.h | cut -d / -f 1-2 | sort | uniq -c
      1 libsrc/boblightserver
      1 libsrc/effectengine
      4 libsrc/hyperion
      1 libsrc/jsonserver
     31 libsrc/leddevice
      1 libsrc/protoserver
      7 libsrc/webconfig
      1 src/hyperion-aml
      1 src/hyperiond
      1 src/hyperion-dispmanx
      1 src/hyperion-framebuffer
      1 src/hyperion-osx
      5 src/hyperion-remote
      3 src/hyperion-v4l2
      1 src/hyperion-x11

**Comment by Paulchen-Panther** [comment]
No

**Comment by penfold42** [comment]
what should go in include/ and what should be next to the cpp files?

**Comment by redPanther** [comment]
Please dont move the h files. Its perfect as it is. In include are the exported headers. Near the cpp files are the privat headers

**Comment by penfold42** [comment]
got it
