### ISSUE TITLE
ubuntu 17.04 leds nog lighting up

### ISSUE THREAD

**Issue by IIIdefconIII** [hyperion-project/hyperion.ng#434]
installation and all went fin but the leds wont light up

**Comment by penfold42** [comment]
Any errors logged to the console if you start hyperiond with --debug ?

**Comment by brindosch** [comment]
Please don't provide so much information. We are overhelmed by the log, config and hardware setup.

**Comment by brindosch** [comment]
I assume it's done

**Comment by marrobHD** [comment]
My APA102 wont get on on Raspi 3B+. Is the wirering scheme the same as the normal hyperion?
