### ISSUE TITLE
Document (and warn) about maximum led counts for each device

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#436]
We should do it !

Where is the best place ? Webui ? Log files ? Wiki ?
All of the above ?

Some limits are imposed by the protocol, 

some are imposed by kernel defaults (like spi max transfer size )

Some are based on the arduino ram / sketch used

**Comment by brindosch** [comment]
Hm,
log -> possible but just if the led count is to high
Wiki -> should be the primary place to go.

Could you add the limits/hints? Feel free to add more :+1: 
https://docs.hyperion-project.org/en/user/led-hardware/intro

You got a mail!

**Comment by brindosch** [comment]
//push
Did you noticed the mail?

**Comment by Lord-Grey** [comment]
Closing for now. Can reopen on further demand.
