### ISSUE TITLE
Effects smoothing+

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#447]
I want to bring back a point which isn't properly solved. Effects and smoothing. I see the follwing issues:
- Some effects require it (candle, mood blobs) and others should use it too, instead running on device latchtime border. Well, it is smooth, but the cpu usage of hyperiond is on a Pi2 at around 40%, for the swirl which is very high.
- Using the global smoothing for control about this is weird. The values might be too high and what happens if you run 2 effects which wants to enable and disable it? Check against the active one again?

From a code view it might be better to implement a own smoothing for the effect engine which could be build more dynamically for better control from effects.

https://github.com/hyperion-project/hyperion.ng/issues/352
@penfold42

**Comment by penfold42** [comment]
Personally I'd rather add smoothing settings to the effect schema and enhance the existing smoothing to be dynamic rather than just off/on

**Comment by redPanther** [comment]
I have a nice idea. I'm on it ... stay tuned

**Comment by redPanther** [comment]
issue solved?

**Comment by brindosch** [comment]
I think so. Thank you
Will later on tune everything.
