### ISSUE TITLE
Add 3D mode switching to API

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#454]
Simple as that, while protobuf already has such a function, the json-rpc lacks of it

- No words fix: Retuns _always_ 2D as string is case sensitive. https://github.com/hyperion-project/hyperion.ng/blob/master/include/utils/VideoMode.h#L15 Therefore broken since 2014
- Add to API and make sure all grabber wrappers listens for it (hyperion class emiter pipe?)

**Comment by redPanther** [comment]
you mean something like that?
https://github.com/redPanther/hyperion.ng/tree/vid3d

**Comment by brindosch** [comment]
Like that, i just wanted to track it :)
Thank you, that's cool. It's also a tiny addition for plugins like kodichecker after it's gone from the core.
This is also a reason why i want to merge the different interfaces into a protocol independet interface, it makes everything just easier, one interface, one route instead creationg cross connections everywhere

Hint: You don't need the slot to signal bidge in hyperiond. You can also connect signal(JsonProc) with signal(hyperiond)

**Comment by brindosch** [comment]
Forget what i said, you added it as signal but don't call it as usual function
