### ISSUE TITLE
Philips Hue

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#466]
Philips Hue is unstable in it's current state. Following a list of notes
- Check if bridge ip is reachable, verify that user has access. Try again after 10 seconds if failed
- Adapt update speed to the configured light count (maybe with speed selection slow/normal/fast)
- In case the bridge goes offline, step back to point 1
- Remove QEventloops, use async feedback. (thread freezer)
- switchOffOnBlack broken(?) verification required
- led count vs light id - untested

@ntim @bimsarck 
You are invited (also to test my webui assistant :))

**Comment by seblagaffe** [comment]
Hy,
The webui is great. But on restart, after boot effect (which work) hyperiond crash 
`[hyperiond EFFECTENGINE] <INFO> effect finished
[hyperiond Core] <INFO> Unregister input source named 'Rainbow swirl fast' from priority register
[hyperiond LedDevice] <DEBUG> <LedDevicePhilipsHue.cpp:152:post()> Post http://192.168.0.11/api/PDfs6Ld0l0QxUaVTF6C2tzWoy9nivFMzmg0IcVUP/lights/1/state: {"on":false}
[hyperiond LedDevice] <DEBUG> <LedDevicePhilipsHue.cpp:152:post()> Post http://192.168.0.11/api/PDfs6Ld0l0QxUaVTF6C2tzWoy9nivFMzmg0IcVUP/lights/2/state: {"bri":56,"on":true,"xy":[0.33700000000000002,0.33160000000000001]}
[hyperiond LedDevice] <DEBUG> <LedDevicePhilipsHue.cpp:152:post()> Post http://192.168.0.11/api/PDfs6Ld0l0QxUaVTF6C2tzWoy9nivFMzmg0IcVUP/lights/3/state: {"bri":118,"on":true,"xy":[0.159,0.27160000000000001]}
[hyperiond LedDevice] <DEBUG> <LedDevicePhilipsHue.cpp:152:post()> Post http://192.168.0.11/api/PDfs6Ld0l0QxUaVTF6C2tzWoy9nivFMzmg0IcVUP/lights/1/state: { "xy": [0.0000, 0.0000], "bri": 1 }
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)
`

**Comment by cmuckel** [comment]
Do you have a solution for the broken switchOffOnBlack? I noticed the problem yesterday

**Comment by fir3drag0n** [comment]
Is there a way to set up a different update speed when I already have a second instance (apa102 leds)?
