### ISSUE TITLE
artnet inupt module

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#467]
We already support an "udplistener" to use hyperion as "bulb" from other sources. "udplistener" is something custom. Would be nice to support professional/more standardized network input.

At first I think of using artnet. Then hyperion can be used from profesional light mixing console or software. (Also opensource software "QLC" can be used to create shows via artnet, so we can use it to test artnet input.)

**Comment by brindosch** [comment]
artnet, pretty cool.
So fast forward!

**Comment by brindosch** [comment]
Oh, maybe add a optional field to remap your leds. Ususally you have a matrix in these kind of software. But to use it with a TV layout you need to pick the leds from the borders and assign them to your leds.
