### ISSUE TITLE
AMLOGICGRABBER x265 Playback problem

### ISSUE THREAD

**Issue by alorbach** [hyperion-project/hyperion.ng#470]
Hi,

I am testing latest commit of hyperion.ng with LibreElec on Odroid C2 device. 
I got a plugin for libreelec with hyperion.ng working properly with the commit https://github.com/hyperion-project/hyperion.ng/commit/81f5f512577a97f4c9f01aa4a55fe63d64cfd065

It appears that hyperion.ng has the same problem grabbing x265 content as hyperion. I don't see any hints if something is going wrong when running with --debug.

With x264 content, LEDs are working properly. With x265 content, LED't turn purple and stay.

**Comment by nrosier** [comment]
This was also discussed on the OSMC board (for the Vero4K). Following solves it:

echo 1 > /sys/module/amvdec_h265/parameters/double_write_mode

Put it in /etc/rc.local or equivalent if this fixes it for you.

**Comment by penfold42** [comment]
Is it safe to forcible enable this when Hyperion startup ? 

Is there any downside to having this on ?

If it's not safe to unilaterally do this inside Hyperion, I guess we could at least warn in the logs

**Comment by redPanther** [comment]
This was also my thouht. We can just add it to grabber init - at least a warning. On my c2 I have this set too + all other stuff recommended in the net (kernel cfg/patch)

**Comment by alorbach** [comment]
This worked indeed! I will add this into my libreelec image somehow, properly using rc.local. 
Does this also fix the random video stutter issue with amlgrabber?

**Comment by alorbach** [comment]
Spoke to soon, setting double_write_mode fixes hyperion but HEVC decoding performance is bad on real 4k videos now. Stuttering and more. Is there any documentation on the kernel values in  /sys/module/amvdec_h265/parameters/?

**Comment by alex240188** [comment]
It would be nice to find some documentation on this.
Using echo 3 gave me working h265 Hyperion without effecting playback but this doesn't seem to work with Hyperion.ng

**Comment by alex240188** [comment]
Echo 2 messes up on screen video so would be interesting to see what the options are actually doing

**Comment by redPanther** [comment]
Hmm I'm not certain if there is a real solution. Some theory about that: video app (kodi) streams encoded video to decoder hardware. This decodes and streams data directly to gpu/video out without involving the cpu (dma).
Problem is that it is not possible to access decoded video. Double buffering means that every frame is duplicated. In this is mostly the cpu involved so the advantage of dma is lost.
Perhaps there is a fancy feature in this soc to solve the double buffer problem.

**Comment by newkind** [comment]
> It would be nice to find some documentation on this.
Using echo 3 gave me working h265 Hyperion without effecting playback but this doesn't seem to work with Hyperion.ng

Currently I'm running echo 3 on my S912 device running CoreElec and so far seems good. I'll be testing it some more.

**Comment by tpmodding** [comment]
I will close this, if the problem occures, just reopen it.
