### ISSUE TITLE
WebUI Bugs

### ISSUE THREAD

**Issue by Paulchen-Panther** [hyperion-project/hyperion.ng#473]
- Beim importieren einer neuen Config  wird nicht auf den eingetragenen port gewechselt. (WebUI nicht erreichbar)
- Beim ändern des WebUI Ports wird nicht auf den eingetragenen port gewechselt. (WebUI nicht erreichbar)
- Protokollmeldungen werden (außer Debug) nicht angezeigt. (Keine Protokoll Einträge vorhanden)
- Die Forwarder Ports lassen sich auf belegte Ports setzen. (WebUI nicht erreichbar)
- Anzahl der LEDs lässt sich auf 0 abspeichern. (Hyperion Crash) ("ASSERT: \"endLed < _ledAdjustments.size()\" in file /libsrc/hyperion/MultiColorAdjustment.cpp, line 29")

**Comment by redPanther** [comment]
Danke fürs durchtesten!

**Comment by brindosch** [comment]
Danke, ein paar davon sind definitiv regressions. Dabei wollte ich mich doch python zuwenden nächste Woche :sob: 

Aber mehr davon!

**Comment by brindosch** [comment]
Ich glaub das kann man zu machen?

**Comment by Paulchen-Panther** [comment]
Nicht ganz. Aber Ja.

**Comment by brindosch** [comment]
Der Port-Forwarder sitzt mit den Instanzen jetzt etwas zwischen den Stühlen. Kann man behalten für komplexe multi-device-room setups. Der Nutzen ist aber wohl heute geringer als früher :)
Weiß aber spontan nicht was du im PR bezüglich dessen gerade anpasst.

**Comment by Paulchen-Panther** [comment]
Was wir bräuchten wäre ein Dev der mal den oben aufgelisteten Fehler beseitig , bzgl.webui Port Wechsel.

**Comment by brindosch** [comment]
De Zaunpfahl reicht jedenfalls um ihn Quer durch Deutschland zu sehen ;)
Stimme dir zu.

**Comment by brindosch** [comment]
Damits erledigt ist: https://github.com/hyperion-project/hyperion.ng/commit/7e324bb1d3d1cb038ee37670631486bcf6698bde

Ich hab meinen Fork irgendwie nicht geschafft zu syncen. Bin wohl aus der Übung. Jemand hat mir wieder Rechte gegeben. Zukünftig wieder PR's, allein wegen CI

**Comment by Paulchen-Panther** [comment]
Yeahhh. @brindosch is back. :smile:
