### ISSUE TITLE
[Testers wanted] Hyperion-Control for Kodi

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#474]
Hello everyone, i am pleased to provide you the first testing version of a new Kodi Addon for Hyperion.
**This addon will replace the KodiCheck at Hyperion!**

Current functions:
- Enable or disable a Hyperion component of your choice based on the conditions you already know from KodiChecker
- Enable 2D/3D switch (has a little bug due to missing python apis / race condition with json rpc)
- Enable Hyperion on startup / disable on shutdown
- Settings reload during runtime
- Hyperion Server detection (SSDP)
- Kodi 17/18

Flaws:
- http! No detection of hyperion restarts, move to websocket or raw tcp socket.

Please install with "install from zip file"
Don't forget to leave some feedback
[script.service.hyperion-control-1.0.0.zip](https://github.com/hyperion-project/hyperion.ng/files/3412180/script.service.hyperion-control-1.0.0.zip)

**Comment by redPanther** [comment]
perhaps use that:
https://pypi.python.org/pypi/websocket-client/

**Comment by brindosch** [comment]
I already tried that to implement, but failed. I got no reponse/handshake, exception. No clue what i am doing wrong here. But this is my first python "app" so i have no experience which may result in simple issues. Maybe it's a lifetime issues. You can have a look at connect_ws.py which was a test.

Anyway, a huge issues are loops that freezes everything, esp the send/recv. They need to quit when kodi requests it, so that the script can properly exit / perform exit tasks.

Some things i forgot to mention
- i forgot pictures mode!
- kodi supports a reload of settings during runtime, this is full implemented, but kodi returns always old values, no clue why, need to ask kodi pros. (That worked earlier in development )

**Comment by redPanther** [comment]
Will test it asap.
On our forum I had posted pycode for raw connection. I fon't know where exectly, but perhaps you find the code

**Comment by brindosch** [comment]
Hello again,
updated first post with new zip (v0.0.2).
Changes
 - Code cleanup
 - startup wizard (sadly it's not that what i intended for, because of a issue with setSetting(). Maybe find the issue)
 - fixed read settings during runtime

@redPanther 
I didn't found your post, can you remember at least in which area you posted it or topic it was related to?
the whole socket stuff is not as easy as i thought if you want it as clean as possible with async send/read, non blocking. Like a QTcpSocket :)

**Comment by brindosch** [comment]
### Update - V0.0.3
-Can be installed on Kodi 18

**Comment by nrosier** [comment]
I'm unable to get the same behaviour as with Kodi + hyperion "classic"

Setup:
amlgrabber priority 100
boblight server priority 110
v4l-grabber priority 120

with hyperion "classic" if nothing is playing on Kodi it will give priority to the boblight server or the v4l-grabber. since the switch to hyperion.ng the amlgrabber keeps having the highest priority so boblight and v4l-grabber are never used.
tried to fix this with this addon which should replace the old kodichecker but the behaviour is still the same. only amlgrabber is active.
how can I fix this?

**Comment by nrosier** [comment]
Got a step closer. Turned out I had to restart Kodi for the addon to activate. But still having trouble getting the v4l-grabber to activate. It works when I give it a higher priority than the platform grabber.

**Comment by brindosch** [comment]
Hello @nrosier 
thank you for your feedback, actually you can just control one component. Which means you need to decide if you want to control the platform capture or usb. V4l can automatically disable and enable itself based on signal (There is a bug which prevents auto enable).
Probably i will add a second component tab (by the risk of more user confusion)

brindosch

**Comment by nrosier** [comment]
Hello @brindosch 

I've fixed it by "hacking" this: https://github.com/Hwulex/hyperion-config-switch
In stead of switching config based on my AVR's input,  I just use a hyperion-remote command to disable/enable the required component. Or disabled the LED's when the AVR is powered off.

**Comment by 007hacky007** [comment]
Thank you for this addon! Seems to work perfectly for my setup:
hyperion-ng with grabber and forwarder to second hyperion-ng instance running in VM with access to arduino nano. 

Works as expected: enable lights on playback and when starting kodi and disable them when kodi is off or on screensaver.

**Comment by newkind** [comment]
I just tested this addon and I noticed two issues.

1) With enabled "Hyperion during Pause", when you play the video - you won't get the led light until you pause the video at least once during the playback

2) When you have enabled the video play detection - Live TV from ie. TVHeadend doesn't trigger Hyperion

**Comment by zenji101** [comment]
Thanks for the addon; 
Running an Odriod C2, Coreelec, Hyperion.ng addon service.
Like @newkind I have the issue where LED lights don't work until paused, then resumed. But I only have Video play detection enabled .....
Would the workaround listed work for me too?

**Comment by zenji101** [comment]
never mind - I gave it a shot and so now it works!! Yey!
Thanks  @newkind and of course @brindosch 

Regards
Z.

**Comment by tbrasser** [comment]
Nice, got this working (including LiveTV 'fix'), only thing I did was put the playingaudiocheck before the playing(video), so the distinction between them would still be made.

**Comment by AndyMel** [comment]
Hi, is possible to run this script on LE 9 kodi 18 on s812 analogic ?

**Comment by AndyMel** [comment]
amlogic wanted to say

**Comment by Cyriltra** [comment]
Hi, thank you for this addon, definitively very useful with hyperion-ng
How the target component setting works actually ?
I can select either:
- platform capture
- Hyperion
- Boblight server
- UDP Listener
- Forwarder
- Blackborder detection
- Smoothing
- Led hardware
- USB capture

I just want the leds to be turned on when I play a movie. Otherwise they need to be off.
So i've selected platform capture, should I select Hyperion instead ? what is the difference ?

**Comment by Cyriltra** [comment]
Hello,
version 0.0.3 was not working for me as the selected component would be disabled but the LEDs were still ON but not refreshed....
So i've modified this addon to instead set LEDs brightness to 0 when I want them OFF and to whatever level i want  (0 to 100) whenever I need them to be ON.
My version: 
[script.service.hyperion-control.0.0.4.zip](https://github.com/hyperion-project/hyperion.ng/files/3181234/script.service.hyperion-control.0.0.4.zip)

**Comment by UniCizin** [comment]
Hey, 
i tried it with the newest version of Hyperion.ng but it doesnt work.
i tried to deactivate USB Capture while Kodi plays a Video, but Hyperion debugger shows me only this message
`[hyperiond JSONCLIENTCONNECTION] (ERROR) Failed to parse json data from JsonRpc@::ffff:192.168.0.33: Error: illegal value at Line: 0, Column: 1 `
`[hyperiond JSONCLIENTCONNECTION] (ERROR) Failed to parse json data from JsonRpc@::ffff:192.168.0.33: Error: illegal value at Line: 1, Column: 0`

the IP is the Kodi Box.
I used the JSON-RPC-Port  of Hyperion.ng (19444)


i used version 0.0.3 and 0.0.4 (but i liked 0.0.3. more because of the ability to choose the components)

**Comment by brindosch** [comment]
Hello, @UniCizin, you need to use the webserver port. The Addon uses HTTP
@newkind Thank you for your investigation. LiveTV was untested on my side.
@Cyriltra The different options allow you to be more specific how Hyperion reacts. When you disable Hyperion the background effect/color is also gone. When you disable the platform capture the background effect/color is still running.
You have a choice for your setup/liking how Hyperion should react on Kodi's state changes.

At all i noticed a higher "fail" rate with Kodi 18 escpecially with youtube. Without further log observing i suspect Kodi doesn't trigger as correct as before the state changes.

SelfNote: Further tests and update to reflect the current hyperion.ng state.
Thank you at all!

**Comment by brindosch** [comment]
Hello everyone,
The issues are fixed now
New: Hyperion Server detection (if you are using a recent version of hyperion.ng)
New: Debug option to observe Kodis reactions on your own through notifications
New: Support for Token Authorization (Not in .ng yet)

I consider this a V1.0.0. It's planned to push this Addon to the official Kodi repo once hyperion.ng goes live (for years now, hehe)

Have fun!

If you have specific feature ideas, just leave a message

**Comment by UniCizin** [comment]
works like a charm now.. thank you 
(only the server detection did not work, but my values were saved from prev. version)

**Comment by b1rdhous3** [comment]
Do you Plan to push this code to github or am i blind?

**Comment by brindosch** [comment]
The detection runs just with the first setup. But you can trigger it at the config menu (execution tab) again if required.
Missing is a tracking for ip/port, as the Hyperion server has a unique id it's possible to redetect and compare at the background on every startup.

Yes there is no repository. It was a small side project. A repository is required for kodi repository push anyway now :)

**Comment by brindosch** [comment]
Sooo, moved to an own repository. Please use the github release section.
https://github.com/hyperion-project/hyperion.control/releases

This issue will be closed
