### ISSUE TITLE
Add secam video type to v4l

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#478]
We have pal and ntsc option in the v4l grabber but we need to think of the French !

**Comment by brindosch** [comment]
Should be very easy to solve. For Hyperion 1 it's a hugher task, because HyperCon needs also a update.
http://elixir.free-electrons.com/linux/latest/source/include/uapi/linux/videodev2.h#L1167

**Comment by brindosch** [comment]
Added: https://github.com/hyperion-project/hyperion.ng/commit/59ec7673733be229f60297ee8ab97821ce0b20e0
