### ISSUE TITLE
Webinterface und read-only Raspbian

### ISSUE THREAD

**Issue by Andirs55** [hyperion-project/hyperion.ng#481]
Hallo ich habe mein Raspbian auf Read-only gestellt um die SD Karte zu schützen, da er wenn der TV ausgeht über eine Schaltsteckdose zusammen mit den LEDs vom Strom getrennt wird. Wenn man nun das Webinterface öffnen möchte kommt folgende Fehlermeldung:

Fehler beim Schreibzugriff!
Hyperion hat keinen Schreibzugriff auf die aktuell geladene Konfiguration. Bitte korrigiere die Dateizugriffsrechte um fortzufahren.

Es wäre sinnvoll eine Art "Read-Only" Webinterface zu haben um das Hyperion weiter steuern (Farben, Effekte, etc.) zu können.

**Comment by brindosch** [comment]
Hallo @Andirs55 ,
ich befürchte ein read-only Ansatz für die "Hyperion Daten" lässt sich nicht länger sinnvoll umsetzen. Ich spreche bewusst nicht nur von der Konfiguration, Hyperion wird modularer und somit ein "schreiben" unumgänglich.
Das restliche System kann weiterhin auf read-only laufen, das sollte keine Probleme machen.

Eine frisch kompilierte Version aus diesem repo schreibt ohne weiteres zutun in das aktuelle Nutzerverzeichnis (home), was bei dir vmtl /home/pi ist

**Comment by brindosch** [comment]
Danke!
