### ISSUE TITLE
Debian 9 - compile errros/warnings

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion.ng#485]
the compile.sh dont work as expected....it aborts

After this operation, 67.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
pi@raspberrypi:~ $ 

more output: 
https://pastebin.com/BzZZyi8N

and compiling has some errors/warnings:

first waning:
```
[ 10%] Building C object dependencies/build/tinkerforge/CMakeFiles/tinkerforge.dir/bricklet_led_strip.c.o
[ 11%] Building C object dependencies/build/tinkerforge/CMakeFiles/tinkerforge.dir/ip_connection.c.o
In file included from /usr/include/errno.h:28:0,
                 from /home/pi/hyperion/dependencies/build/tinkerforge/ip_connection.c:13:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
[ 12%] Building CXX object dependencies/build/hidapi/CMakeFiles/hidapi-libusb.dir/hidapi-libusb_automoc.cpp.o
```
second error/warning?
https://pastebin.com/rRReDWuG

complete output from console:
https://pastebin.com/NwPt09a4

edit: and after starting, the webui doesnt start?
edit2: oh no...new port -.-

**Comment by brindosch** [comment]
Someone needs to patch these deprecations :)

**Comment by brindosch** [comment]
Es wäre spannend zu wissen, ob man die geforderten Änderungen auch mit Ubuntu 14.04 anwenden kann (4.4)

**Comment by tpmodding** [comment]
soll ich mal Ubuntu 16.04.3 LTS in ner vmware packen und testen? oder willste straight 14.04?

**Comment by brindosch** [comment]
Nein, ich meine ob die alten Versionen noch gehen nachdem das gefixt ist, sonst muss man den alten code und den neuen code  gleichzeitig behalten
