### ISSUE TITLE
H264 Playback/Sync issues with AML-grabber

### ISSUE THREAD

**Issue by nrosier** [hyperion-project/hyperion.ng#488]
Configuration:

Vero 4K with OSMC, Debian 9.2, Kodi 17.6 (also on previous versions).
Hyperion: latest "classic" version and latest NG version.
Audio DTS/AC3 in passthrough mode or AAC as PCM
h264 encoded files

Issue: after some time playback seems to "slow down" while audio continues at normal speed. When I skip back 10s the video/audio re-syncs and playback continues as normal (for some time).

Issue does not occur when aml-grabber is disabled.

**Comment by redPanther** [comment]
when aml capturing is used (kernel side) hw acceleration is off, we cant fo anything from user space (hyperion). amlogic must implement a stable hw accelerated capturing api...

this is not a hyperion issue, it is the aml platform itself.

**Comment by nrosier** [comment]
thanks. will also report this back to the OSMC forum.

**Comment by nrosier** [comment]
can this be documented with the aml-grabber. I know at least of 1 other user who has the same issue. I can bypass this as I also have a v4L-grabber. In it's current state the aml-grabber is not very usefull.

**Comment by andrcuns** [comment]
Yep, I'm experiencing issue with sync occasionally as well.
