### ISSUE TITLE
Zeroconf advertises the wrong UDP listener ip if it's multicast address

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#49]
Need to look into how to explicitly advertise an ip address

**Comment by penfold42** [comment]
This looks close
http://stackoverflow.com/questions/8153979/dns-sd-how-to-manually-register-a-remote-service

**Comment by penfold42** [comment]
#53 now listens to all ip addresses in addition to the multicast address.
Not really a fix for this, but at least the advertised service also works.

**Comment by brindosch** [comment]
One question. the multicast address is always the same if you follow the "guideline"?

**Comment by penfold42** [comment]
It's whatever you specify in the config file

**Comment by brindosch** [comment]
UdpListener is currently not available. Will close for the moment
