### ISSUE TITLE
Connection to KODI 18 broken

### ISSUE THREAD

**Issue by gismo2004** [hyperion-project/hyperion.ng#490]
According to  [xbmc github](https://github.com/xbmc/xbmc/pull/12281) and [forum](https://forum.kodi.tv/showthread.php?tid=324598) Kodi does not allow "WriteAccess" via "GET" methode anymore.

Thus using JSONP will not work, because it is using GET for all requests. [link:](https://stackoverflow.com/a/16416877)

unsing JSON leads to problems with ["Access-Control-Allow-Origin"](https://stackoverflow.com/a/46955558) when directly accessing the API. As far as i understand, using a proxy is the only way to handle this (as written in the last link). 

Unfortunately im not skilled enough to create such thing. 

if i can help somehow, please let me know.

cheers

**Comment by brindosch** [comment]
According to the PR this is fixed?
Closed until someone says something different :)
