### ISSUE TITLE
Replace protobuf with flatbuffers

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#494]
Flatbuffers replaces protobuf (because of overhead and major upgrade required to be future proof again). Controlling (clear/clearll/setEffect/...) shouldn't be handled at the interface (at least for the moment) it's meant to be used for sending a lot of data more efficient compared to plaintext json (webserver/websocket)

Connection: Clients needs to keep the connection open to register once with meta data, followed by the real data. A connection abort of the tcp socket means register again

Register message:
Hyperion.ng makes more use of meta data, so it's probably better to send them just once on new connection. (This is also the new internal pattern to reduce data passing and to make it more readable)
- **origin** User friendly name of the sender
- **priority** Priority to use, the priority will last for the current socket connection to assign the send data to this priority

Data fields proposal (send to push data):
-  **type** (int) Type of data to support different formats. As Hyperion is probably faster to "decode" data to the Hyperion format compared to a client. (Example RGB, RGBA, jpeg/png as base64, ...)
- **data** The data will be processed according to type
- **width** (optional) Depends on type, the current data type in protobuf requires it while other types in future may not
- **height** (optional) Depends on type, the current data type in protobuf requires it while other types in future may not

Dropped fields compared to protobuf:
- **timeout** There is no reason why the client should provide a timeout. This should be handled by Hyperion/ user settings for the flatbuffer receiver. Allows more control as not sending clients can be disconnected automatically after a specific period along with their priority registration.
- All control fields.

@MartB
Please leave a comment, probably i've overseen something. If you have questions just ask.

issue: https://github.com/hyperion-project/hyperion.ng/issues/455

**Comment by brindosch** [comment]
I noticed that the protoserver is a mess.
Is it ok when i implement a new server(tcp) class where you just need to add the flatbuffer parsing?

**Comment by MartB** [comment]
The ideas above sound okay to me but i guess some stuff will pop up while implementing it.

As for the rewrite, i originally wanted to get rid of qt completely for the protoserver and use native c++ with multithreading (tcp / udp).
So yeah i will let you rewrite it and then add my stuff on top.

**Comment by brindosch** [comment]
Great, for sure there are some things to tune.

The problem with qt is, it's actually everywhere and migration at this stage of development (this repository) would be hefty. Writing this server now in plain c++ is probably not the best step as long we have qt as cross platform handler (I have a windows 'port' in mind for the future)

Another proposal was to recreate Hyperion written in Rust. Which would be a complete fresh start.

Conclusion:
In the end it's up to the commitment of the contributor where this project moves to. My target is to finish it and to provide later also a windows version. As fast as possible, as Hyperion 1 with HyperCon is unmaintend so it's just a matter of time when people go crazy because of broken binarys. Should be noted that i am primarly the only Hyperion dev now for a longer period

I will implement the server at my much more progressed branch here, as the Hyperion class will be run threaded soon along with multi instance spawning: https://github.com/brindosch/hyperion.ngBeta/tree/rework
I will implement server as requested with threading too. (And probably migrate others too, but step by step)

Thank you for your already amazing commitment!

**Comment by MartB** [comment]
Hyperion in Rust sounds like a great idea.
I wont say no to a challenge to get me to learn some Rust haha.

I didnt expect that yet another project exists. (beta)
I will take a look at it and play around with some implementations of flatbuffers while you finish up that proto server.

No need to thank me just yet.
You pulled off this  greatproject, if theres anyone to thank its you and all the past contributors!

**Comment by MartB** [comment]
I did some early tests and it works perfectly fine with the current implementation.
I did not test the protoclient stuff tho and i didnt implement everything.

Waiting for the tcpserver changes and then we can tackle this together.

If anyone wants to test i have buildable sources in the following repos:
https://github.com/MartB/hyperion-flatbuffers-kodi
https://github.com/MartB/hyperion.ng

**Comment by MartB** [comment]
Actually i think i misread the first part.
Do you really want to drop all the commands besides image data sending ?

Flatbuffers is much faster than json and is much better suited for this then invoking yet another web api with additional protocol / serialization overhead. Its not a performance critical part but it adds another layer of complexity to something thats supposed to be simple.

**Comment by brindosch** [comment]
Thank you for you example code, i hope i get something up and running soon.

> I didnt expect that yet another project exists. (beta)

It's not really a beta, its more unstable than the current master here.

> Do you really want to drop all the commands besides image data sending 

Yes, the json api is currently well implemented (websocket/HTTP/raw TcpSocket) and documented (not public). At my rework branch there is a more critical point, the split between global scope and instance scope which i working toward.
I won't implement it at this stage until everything is finished

**Comment by MartB** [comment]
So that leaves us with 2 connections for lets say the kodi addon then ?
I dont know how i feel about this, afterall having a central more lowlevel api like the one provided by the proto server has many benefits for doing image sending + control together over one connection.

I will let you finish your stuff and play around with the source a bit, maybe i find more issues.
Just give me a heads up whenever you need something / you are done.

**Comment by brindosch** [comment]
And go :)

> proto server has many benefits for doing image sending + control together over one connection

For sure, the problem is to implement it accurately. This can be all done, but i want to avoid the reimplementation until the json interface has been finished in the scope of features i implemented at my fork. But you can start with it whenever you want.

> When we connect we send a register that much is understood but what happens
when the implementations want to signal a pause aka im not sending any data right now you can deregister me and what is supposed to happen when they want to send data again ? (all this with still having the socket open)

A priority can be set to inactive, which hides (is not qualified to be visible) the priority from selection and stops timeout calculation. So the register information is never lost (while writing this i remember there is no clear protection on user request at api).

During the past week i had a deeper look on threading, as i am fairly new to it. Also in the scope of easy qt there are some basic you need to know which i stumbled upon.
Plugins has been fixed first and run properly threaded including their callbacks from Hyperion. This was the last deal breaker on that part.

I've implemented the FlatbufferServer threaded. The sockets aren't threaded yet, well the demand isn't high for this. Please note that QT is a event driven framework which means blocking operations are discouraged as you usually have a event to listen for. Which is probably one of the reasons why Hyperion still runs in a single thread(!) and performs "well enough, with space for threading :)"

I've tested your implementation, i used the kodi plugin from your link, but all i get is "unhandledImplentation", the switch() statement in handleMessage() server side seems broken(?)

I would be happy if we can remove proto soon. Especially i want to ask you for this task. You wrote that the flatbuf_xy.fbs file structure isn't so flatbuffers'ish, feel free to break in pieces and prepare a better structure for image sending as written in first post AND everything that follows in future. 

At the mean time i can work more on threading, especially the multi Hyperion instancing will exercise me for some days (for sure). If this is done i can connect the global Flatbuffer with instance based sharing with queued inter-thread communication.

**Comment by MartB** [comment]
>I've tested your implementation, i used the kodi plugin from your link, but all i get is "unhandledImplentation", the switch() statement in handleMessage() server side seems broken(?)

You probably used the new kodi plugin with the outdated server code, i implemented a newer more "flatbuffer like" version in my latest commits.

https://github.com/MartB/hyperion-flatbuffers-kodi/commit/37c5574d563669a3e521089228104d6a011816df
and
https://github.com/MartB/hyperion.ng/commit/30a9bb027f6d8f4c86012a0c2ef7c339826fb92d

Its straigthforward to port, but i can do it aswell if you want.

I agree threading shouldnt be a dealbreaker in this case.

**Comment by brindosch** [comment]
Thank you for your snippets. I've tested a bit with hyperion-x11 and i noticed a heavy memory leak with hyperion-x11 (up to 1gb from ususally 1mb) and at hyperiond when the flatbuffers are in use. It results within a minute into a bad_alloc.

I pushed my current dev stuff into rework. Be aware of the commit changelog.

**Comment by MartB** [comment]
Do you have some forwarding nodes assigned ?
I had a similar issue with a forwarder and it ended in an endless loop.

Even if its not related to forwarders i would guess that some component is looping.
I will check that out later.

**Comment by brindosch** [comment]
Ah perfect, solved. Last time i used valgrind it just crashed away with a "this should never happen" message

Will move forward.

**Comment by brindosch** [comment]
So this can be closed, we have both for backwards comp :)
