### ISSUE TITLE
Hyperiond is horribly insecure

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#5]
It runs as root

No authentication on its network services

No source IP restrictions on its network services

When we support reconfiguration via a browser you could overwrite any file on the OS

**Comment by brindosch** [comment]
yes, security is also something we talked about and needs to be improved. Write down all ideas and suggestions for more security here.

There is at least one issue i have seen if hyperion runs with lower rights: no access to usb devices (arduino). Could we build a workaround or something?

**Comment by penfold42** [comment]
udev rules to allow non-root access to the USB device.

Probably ditto for /dev/SPI

**Comment by penfold42** [comment]
http://askubuntu.com/questions/15570/configure-udev-to-change-permissions-on-usb-hid-device

**Comment by brindosch** [comment]
hm so new install processing for service files: on all systems we should create a new user which get access to the hyperion bins and config location at /etc/hyperion to modifiy files.

We need to test the udev things to get in best case a working solution for all platforms

**Comment by penfold42** [comment]
Yep - also another good reason to move to using OS native packages.

It's ok to make install or install.sh scrips to drop obvious binaries and config file on the box, but when you start doing core OS things like udev rules it's a nightmare for users to untangle.

**Comment by redPanther** [comment]
Native packages:
We have packs for debian based distros. Rpm is prepared, but the post install is missing yet. Somebody done a arch aur script for old hyperion. 
With cpack we can generate osx dmg packages too, but nothing done yet.

What distros/os should we support?
Best thing would be if we are so famous that distro packagers create their own hyperion package and care about integration. Should we do some advertising?

I will look into the arch script and make it suitable for h.ng


And I will add ip restrictions to servers.

**Comment by redPanther** [comment]
I can add simple address restrictions. 
I would make a black/whitelist where you can list your addresses

```
"protoserver"
 {
   "port" : 19445,
   "restriction mode" : "allow",      // or "deny" or "none"
   "hosts" : [ "192.168.178.10",  "192.168.178.20",  "192.168.178.30"]
}
```

Is this ok for now? any hints?
The implemention is quit simple. Just add the parsing and check if client that request a connection is in the list.

**Comment by penfold42** [comment]
http://doc.qt.io/qt-5/qhostaddress.html#isInSubnet-1

Is our friend - if we get a naked IP address we can match on that. If we get an ip+mask bits we can use in subnet.
So, 10.0.0.3, 192.168.0.0/16 should both be acceptable

Do you think we should so a validate ip class ?
Feed it the config config string and the desired ip
Address and have it return true/false ?

For performance, a cache would be good (UDP packets coming on quickly)

**Comment by brindosch** [comment]
I like the subnet /16 idea which is whitelisted by default. If someone tries to connect from "outside" it is not accepted.
security is always something in between bothering and benefit :)

**Comment by redPanther** [comment]
this is exactly what I want. I will use it as validator.
Then we can write:
```
"protoserver"
 {
   "port" : 19445,
   "restriction mode" : "allow",      // or "deny" or "none"
   "hosts" : [ "192.168.178.0/16",  "192.168.240.30"]
}
```
As cache we can take a simple std::map with <string:bool> and define a cache size. If cache size is reached, first x values are popped out

**Comment by NicoHood** [comment]
I also noticed that a) hyperion service is running as root and b) it is not even required. If hyperion runs as separate user with no home directory, wouldn't this isolate hyperion good enough? If someone tries to control my leds... I dont care. However if he can control hyperion and thereby my whole system as root, I am not so happy anymore.

Tell me what you think. I  will modify the Archlinux package then and add a new hyperion user for the service unit.

**Comment by penfold42** [comment]
It’s not as simple as that:
- Some led drivers require direct IO on the Pi which needs root.
- Some will need spi access (permissions can fix this)
- the screen grabbers probably need root too

**Comment by brindosch** [comment]
As of today
[x] It runs as root (systemd tuned)
[x] No authentication on its network services (https://github.com/hyperion-project/hyperion.ng/pull/578) 
[x] No source IP restrictions on its network services (https://github.com/hyperion-project/hyperion.ng/pull/578)

I think this can be closed. Improvements are always possible with further details. Currently a limited administration access with a password is not implemented. Everything else is acceptable
