### ISSUE TITLE
Hyperion Integration to Hue Bridge

### ISSUE THREAD

**Issue by Reborn2** [hyperion-project/hyperion.ng#501]
Hello

It would be nice if the Light ability from Hyperion, can be used from The Hue app and grouped together with Hue Lamps in scenes. If it can linked to a Huebridge. 

(Benefits Alexa, Siri and Busch Free@Home integration)

**Comment by mawi13** [comment]
You can use home assistant for this task, i use it this way.

**Comment by penfold42** [comment]
Homebridge works too

**Comment by Teryon** [comment]
@penfold42 which plugin do you use in homebridge ?
How do you make Hyperion device appears in Hue ?
