### ISSUE TITLE
Cannot Compile -  undefined reference to symbol 'dlsym@@GLIBC_2.4'

### ISSUE THREAD

**Issue by washcroft** [hyperion-project/hyperion.ng#502]
I'm getting a few errors at the end of the compilation on an RPi:

Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

```
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(dynload_shlib.o): undefined reference to symbol 'dlsym@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/hyperion-remote/CMakeFiles/hyperion-remote.dir/build.make:169: recipe for target 'bin/hyperion-remote' failed
make[2]: *** [bin/hyperion-remote] Error 1
CMakeFiles/Makefile2:2296: recipe for target 'src/hyperion-remote/CMakeFiles/hyperion-remote.dir/all' failed
make[1]: *** [src/hyperion-remote/CMakeFiles/hyperion-remote.dir/all] Error 2
```

Initial searches seem to indicate the dl library hasn't been included, but adding that to CMake library list for the several binaries this error is given for doesn't resolve it.

**Comment by washcroft** [comment]
Fixed by adding **-ldl -lutil** to the compile command line for each binary

**Comment by Nahasapeemapetilon** [comment]
hi, i use "cmake" and "make" to compile on bananas, where can i add this linker flags?
