### ISSUE TITLE
Need trapezoid mapping for grabbers

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#504]
Webcam capture is a viable Option.

We need a way to map the 4 corners  of the screen to transpose the capture image.

Abusing the led co-ordinate system is not ideal as it will break some effects.
This really is an input thing

**Comment by penfold42** [comment]
Thinking more about this, the webUI could auto calibrate.

Display an image in a distinctive colour with each corner lit up in turn and find the co-ordinates

**Comment by penfold42** [comment]
Possibly - it might be near enough.
My concern is due to the smaller colour depth of most webcams but it might be close enough

**Comment by AalianKhan** [comment]
Is there any update on this?

**Comment by tpmodding** [comment]
https://github.com/hyperion-project/hyperion.ng/pull/791
