### ISSUE TITLE
Ps3 Eye als Grabber

### ISSUE THREAD

**Issue by JulianMined** [hyperion-project/hyperion.ng#510]
In der Classic Version lässt sie die Kamera problemlos als Grabber benutzen.
In dieser Version bekomme ich folgende Meldung.

hyperiond V4L2:auto] <INFO> available V4L2 devices:
        /dev/video0     gspca main driver
hyperiond V4L2:auto] <INFO> search for usable video devices
[hyperiond V4L2:auto] <INFO> test v4l device: /dev/video0
[hyperiond V4L2:auto] <INFO> no usable device found

**Comment by tpmodding** [comment]
@Paulchen-Panther sollte das mit deinem einem fix nicht schon funktionieren?

**Comment by tpmodding** [comment]
@Paulchen-Panther ?

**Comment by Paulchen-Panther** [comment]
Ich glaube dieser Issue hat sich erledigt. Kann geschlossen werden.
