### ISSUE TITLE
SK6812 Issue. strange colors and missing led

### ISSUE THREAD

**Issue by SaulGoodman1337** [hyperion-project/hyperion.ng#526]
Hi,
I desperately need your help. That really makes me desperate right now.

I removed my old WS28xx from my TV to replace it with nice SK6812 RGBW. 
I connected the SK6812 to GPIO 18.

First of all the colors don't seem to be right. See photo.
And LED's are missing. I have 224 LED's in the setup and 55 of the LED's are not addressed.

Can anyone help me here?

Video:
https://youtu.be/KmLhOLSSFE0
Screenshots:
https://abload.de/img/dsc006904rcgv.jpg (Colors are not correct)
https://abload.de/img/screenshot2018-12-29ayqevh.png (Hyperion.ng configuration)

**Comment by penfold42** [comment]
My guess is it’s sending RGB data and not RGBW data.

Did you build from source ?

**Comment by danielpondruff** [comment]
Yep. Fresh build from source. Any Idea how to fix this?

**Comment by penfold42** [comment]
Nope !

Run from command line with debugging and see what it thinks the led device config is - from memory it’s logged on startup.

Also show us the device section of the config file

**Comment by danielpondruff** [comment]
hyperiond -d:

> root@raspberrypi:/home/pi/hyperionng/hyperion/build/bin# ./hyperiond -d
[hyperiond MAIN] <INFO> Selected configuration file: /root/.hyperion/config/hyperion_main.json
[hyperiond LOGGER] <WARNING> Logger settings overridden by command line argument
[hyperiond ChannelAdjust_BLACK] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ChannelAdjust_WHITE] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,255,255
[hyperiond ChannelAdjust_RED] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,0,0
[hyperiond ChannelAdjust_GREEN] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,255,0
[hyperiond ChannelAdjust_BLUE] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,255
[hyperiond ChannelAdjust_CYAN] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,255,255
[hyperiond ChannelAdjust_MAGENTA] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,0,255
[hyperiond ChannelAdjust_YELLOW] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,255,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond Core] <INFO> ColorAdjustment 'default' => [0; 221]
[hyperiond Core] <DEBUG> <Hyperion.cpp:315:getLedLayoutGridSize()> led layout grid: 72x43
[hyperiond ComponentRegister] <INFO> Json/Proto forwarder: off
[hyperiond LedDevice] <DEBUG> <LedDeviceWS281x.cpp:25:init()> whiteAlgorithm : white_off
[hyperiond LedDevice] <INFO> LedDevice 'ws281x' configured.
[hyperiond Core] <INFO> Creating linear smoothing
[hyperiond Smoothing] <INFO> smoothing cfg 0: interval: 4517888 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 1: pause
[hyperiond ComponentRegister] <INFO> Smoothing: activated
[hyperiond ComponentRegister] <INFO> LED device: activated
[hyperiond Smoothing] <INFO> smoothing cfg 2: interval: 30458128 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 3: interval: 30473870 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 4: interval: 30478750 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 5: interval: 30479706 ms, settlingTime: 50 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 6: interval: 30478990 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 7: interval: 30498322 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 8: interval: 30500318 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 9: interval: 30500566 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 10: interval: 30503034 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 11: interval: 30502902 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 12: interval: 30481130 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 13: interval: 30505810 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 14: interval: 30505806 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 15: interval: 30482086 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 16: interval: 30484762 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 17: interval: 30505838 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 18: interval: 30481258 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 19: interval: 30488250 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 20: interval: 30487502 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 21: interval: 30488802 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 22: interval: 30490718 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 23: interval: 30491486 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 24: interval: 30490182 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 25: interval: 30494474 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 26: interval: 30496394 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 27: interval: 30493786 ms, settlingTime: 50 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 28: interval: 30493190 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 29: interval: 30569798 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 30: interval: 30568470 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 31: interval: 30467586 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 32: interval: 30575474 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 33: interval: 30576326 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 34: interval: 30576062 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 35: interval: 30576110 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 36: interval: 30467326 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond Smoothing] <INFO> smoothing cfg 37: interval: 30578742 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond EFFECTENGINE] <INFO> 35 effects loaded from directory :/effects/
[hyperiond EFFECTENGINE] <INFO> 19 effect schemas loaded from directory :/effects/schema/
[hyperiond EFFECTENGINE] <INFO> 0 effects loaded from directory /root/.hyperion/custom-effects
[hyperiond EFFECTENGINE] <DEBUG> <EffectEngine.cpp:43:EffectEngine()> Initializing Python interpreter
[hyperiond Core] <DEBUG> <Hyperion.cpp:447:Hyperion()> configured leds: 222 hw leds: 222
[hyperiond ChannelAdjust_BLACK] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,0
[hyperiond ChannelAdjust_RED] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,0,0
[hyperiond ChannelAdjust_GREEN] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,255,0
[hyperiond ChannelAdjust_BLUE] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,0,255
[hyperiond ChannelAdjust_CYAN] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 0,255,255
[hyperiond ChannelAdjust_MAGENTA] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,0,255
[hyperiond ChannelAdjust_YELLOW] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,255,0
[hyperiond ChannelAdjust_WHITE] <DEBUG> <RgbChannelAdjustment.cpp:24:resetInitialized()> initialize mapping with 255,255,255
[hyperiond MAIN] <INFO> Hyperion initialized
[hyperiond MAIN] <INFO> Json server created and started on port 19444
QObject::connect: No such slot ProtoServer::setVideoMode(VideoMode)
[hyperiond MAIN] <INFO> Proto server created and started on port 19445
[hyperiond MAIN] <DEBUG> <hyperiond.cpp:301:startNetworkServices()> Boblight server created
[hyperiond ComponentRegister] <INFO> Boblight server: off
[hyperiond Core] <INFO> Register new input source named 'UDPLISTENER' for priority channel '200'
[hyperiond MAIN] <DEBUG> <hyperiond.cpp:320:startNetworkServices()> UDP listener created
[hyperiond ComponentRegister] <INFO> UDP listener: off
[hyperiond MAIN] <DEBUG> <hyperiond.cpp:343:startNetworkServices()> UDP LIstener mDNS responder started
[hyperiond MAIN] <DEBUG> <hyperiond.cpp:350:startNetworkServices()> Json mDNS responder started
[hyperiond MAIN] <DEBUG> <hyperiond.cpp:356:startNetworkServices()> Proto mDNS responder started
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.050000 (13)
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[hyperiond BLACKBORDER] <DEBUG> <ImageProcessor.cpp:62:setLedMappingType()> set led mapping to type 0
[hyperiond ComponentRegister] <INFO> Blackborder detector: activated
[hyperiond V4L2:/dev/video0] <DEBUG> <Grabber.cpp:33:setVideoMode()> setvideomode 0
[hyperiond V4L2:/dev/video0] <INFO> Signal threshold set to: {12, 12, 12}
[hyperiond V4L2:/dev/video0] <INFO> Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
[hyperiond MAIN] <DEBUG> <hyperiond.cpp:564:createGrabberV4L2()> V4L2 grabber created
[hyperiond V4L2:/dev/video0] <INFO> configured v4l device: /dev/video0
[hyperiond V4L2:/dev/video0] <DEBUG> <V4L2Grabber.cpp:543:init_device()> width=720 height=576
[hyperiond V4L2:/dev/video0] <DEBUG> <V4L2Grabber.cpp:557:init_device()> Pixel format=YUYV
[hyperiond V4L2:/dev/video0] <INFO> Started
[hyperiond Core] <INFO> Register new input source named 'V4L2:/dev/video0' for priority channel '240'
[hyperiond MAIN] <INFO> V4L2 grabber started
[hyperiond ComponentRegister] <INFO> V4L capture device: activated
[hyperiond MAIN] <INFO> set screen capture device to 'dispmanx'
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.050000 (13)
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[hyperiond BLACKBORDER] <DEBUG> <ImageProcessor.cpp:62:setLedMappingType()> set led mapping to type 0
[hyperiond ComponentRegister] <INFO> Blackborder detector: activated
[hyperiond DISPMANXGRABBER] <DEBUG> <Grabber.cpp:33:setVideoMode()> setvideomode 0
[hyperiond DISPMANXGRABBER] <INFO> Display opened with resolution: 640x480
[hyperiond Core] <INFO> Register new input source named 'Dispmanx' for priority channel '250'
[hyperiond MAIN] <INFO> DISPMANX frame grabber created and started
[hyperiond Core] <INFO> Unregister input source named 'Dispmanx' from priority register
[hyperiond Dispmanx] <INFO> grabber change state to disabled
[hyperiond ComponentRegister] <INFO> Framegrabber: off
[hyperiond MAIN] <INFO> Hyperion started
[hyperiond EFFECTENGINE] <INFO> run effect Rainbow swirl fast on channel 0
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.050000 (13)
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[hyperiond BLACKBORDER] <DEBUG> <ImageProcessor.cpp:62:setLedMappingType()> set led mapping to type 0
[hyperiond Core] <INFO> Register new input source named 'Rainbow swirl fast' for priority channel '0'
[hyperiond MAIN] <INFO> Inital foreground effect 'Rainbow swirl fast' started
[hyperiond EFFECTENGINE] <INFO> run effect Snake on channel 254
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.050000 (13)
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[hyperiond BLACKBORDER] <DEBUG> <ImageProcessor.cpp:62:setLedMappingType()> set led mapping to type 0
[hyperiond Core] <INFO> Register new input source named 'Snake' for priority channel '254'
[hyperiond MAIN] <INFO> Inital background effect 'Snake' started
[hyperiond WEBSERVER] <DEBUG> <WebConfig.cpp:38:WebConfig()> WebUI initialized, document root: :/webconfig
[hyperiond WEBSERVER] <INFO> started on port 8090 name 'Hyperion WebConfig'
[hyperiond WEBSERVER] <DEBUG> <StaticFileServing.cpp:61:onServerStarted()> Web Config mDNS responder started
[hyperiond Smoothing] <INFO> set smoothing cfg: 25, interval: 0 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond V4L2:/dev/video0] <INFO> Stopped
[hyperiond Core] <DEBUG> <Hyperion.cpp:536:bonjourRecordResolved()> found hyperion session: raspberrypi.local.:8090
[hyperiond Smoothing] <INFO> set smoothing cfg: 30, interval: 0 ms, settlingTime: 40 ms, updateDelay: 0 frames
[hyperiond EFFECTENGINE] <INFO> effect finished
[hyperiond Core] <INFO> Unregister input source named 'Rainbow swirl fast' from priority register
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.050000 (13)
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:26:BlackBorderProcessor()> mode: default
[hyperiond BLACKBORDER] <DEBUG> <ImageProcessor.cpp:62:setLedMappingType()> set led mapping to type 0
[hyperiond WEBSOCKET] <DEBUG> <WebSocketClient.cpp:29:WebSocketClient()> New connection from ::ffff:10.20.31.6

/root/.hyperion/config/hyperion_main.json

> "device": {
        "colorOrder": "brg",
        "dma": 5,
        "gpio": 18,
        "invert": false,
        "latchTime": 1,
        "leds": 224,
        "rewriteTime": 5000,
        "rgbw": true,
        "type": "ws281x",
        "whiteAlgorithm": "sub_min_warm_adjust"
    },

**Comment by danielpondruff** [comment]
hmm the log said :

> whiteAlgorithm : white_off

and 

> [hyperiond Core] Hyperion.cpp:447:Hyperion() configured leds: 222 hw leds: 222

that's not what i defined in the config oO

**Comment by penfold42** [comment]
Even with that it should still work.

My guess is that it’s not setting the strip type to sk6812 in https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/leddevice/dev_rpi_pwm/LedDeviceWS281x.cpp

Maybe add some debugging

**Comment by danielpondruff** [comment]
its working! you're right. StripType is not set to sk6812. i have changed line 43 to 
`	_led_string.channel[_channel].strip_type = SK6812_STRIP_GRBW;
`
compile it, running and voila.... Colors ! it seems thats your config parse for rgbw is not working...

**Comment by penfold42** [comment]
Not my code anymore ...!
I wrote the original rgbw support but it’s been refactored since then.

It also looks like the warm algorithm was never implemented. White off and subtract min that I wrote should work but might suffer the same fate as rgbw right now...

**Comment by penfold42** [comment]
deviceConfig["rgbw"].toInt()

Maybe toBool would be better here - presuming there is a toBool

**Comment by penfold42** [comment]
Oh dear...
In the code:
QString whiteAlgorithm = deviceConfig["white_algorithm"].toString("white_off");

In the schema:
“whiteAlgorithm": {
	"type": "string",

**Comment by danielpondruff** [comment]
Log spam:
[hyperiond RGBtoRGBW] <ERROR> white algorithm 'sub_min_warm_adjust' is not implemented yet.

**Comment by danielpondruff** [comment]
Is here a Hope that you can reimplement this Feature ? 

Yep. White off and subract minimum are working correct.and yes, If i use White off, i have the same behavior like my hardcoded rgbw before.


I would like to thank you very much for your Help !

**Comment by penfold42** [comment]
Yep, done

Also in my fixes branch

**Comment by danielpondruff** [comment]
Works the way it's supposed to. Thanks a lot for that ! 
Is there a possibility somewhere to donate a few beers ? 🍺

**Comment by RickDB** [comment]
Good to hear 👍 , looks resolved so closing.
