### ISSUE TITLE
UDPListener - what to do with short packets ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#54]
If 10 LEDs are configured and we get a packet with only 3 LEDs of data should we set the other 7 to black ?

Right now, it uses whatever was in the buffer from the last packet with black the default at startup.

Choices:
Leave it as it is
Set the remainder to black
Ignore the packet
Ignore and send an error packet back to the client

**Comment by brindosch** [comment]
Hm, what might be the most common usage?
I would set it to black?

**Comment by penfold42** [comment]
I'll set it to black.
I might add a stricter check option that drops packets that are the wrong size and log it (occasionally with a count)
