### ISSUE TITLE
failing to compile on rpi0

### ISSUE THREAD

**Issue by cr0wm4n** [hyperion-project/hyperion.ng#540]
I get the below error when compiling on a rpi0 with OSMC
Any fix available for it ?

[ 79%] Building CXX object libsrc/webserver/CMakeFiles/webserver.dir/webserver_automoc.cpp.o
[ 80%] Building CXX object libsrc/webserver/CMakeFiles/webserver.dir/webserver_automoc.dir/qrc_WebConfig_NXBAIHQSQM5QBD.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
libsrc/webserver/CMakeFiles/webserver.dir/build.make:326: recipe for target 'libsrc/webserver/CMakeFiles/webserver.dir/webserver_automoc.dir/qrc_WebConfig_NXBAIHQSQM5QBD.cpp.o' failed
make[2]: *** [libsrc/webserver/CMakeFiles/webserver.dir/webserver_automoc.dir/qrc_WebConfig_NXBAIHQSQM5QBD.cpp.o] Error 4
CMakeFiles/Makefile2:2169: recipe for target 'libsrc/webserver/CMakeFiles/webserver.dir/all' failed
make[1]: *** [libsrc/webserver/CMakeFiles/webserver.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Paulchen-Panther** [comment]
If this is the case, you are running out of memory. So run perhaps make -j 2 instead. This will mean fewer parallel jobs and will mean the compilation will take longer but hopefully will not exhaust your system memory.

**Comment by cr0wm4n** [comment]
i have tried already with  -j 1
it still results in the same error on a pi zero :(

is there anything else i can do to resolve it ?

**Comment by tpmodding** [comment]
i will try it on my pi zero after work (or after champions league game :-P )

**Comment by cr0wm4n** [comment]
Thankyou :)

**Comment by brindosch** [comment]
As already said, no memory. That's very sad.

Time to start the pre-release tagging and ci uploads for ready to use packages @Paulchen-Panther during the next weeks? :+1:
