### ISSUE TITLE
Philipshue with switchOffOnBlack=true does not turn off the lights. (Potential Fix)

### ISSUE THREAD

**Issue by bennealon** [hyperion-project/hyperion.ng#545]
With reference to this closed issue: [https://github.com/hyperion-project/hyperion.ng/issues/466](https://github.com/hyperion-project/hyperion.ng/issues/466)

And this bug: [https://hyperion-project.org/threads/hyperion-ng-switchoffonblack-not-working.3112/#post-14170](https://hyperion-project.org/threads/hyperion-ng-switchoffonblack-not-working.3112/#post-14170)

`switchOffOnBlack=true` with a Philips Hue configuration does not turn the lights off appropriately. Comparing the logic to that in Hyperion, it appears the lights are being turned off, then immediately the colour is being set again, which is likely turning the bulbs back on.

LedDevicePhilipsHue.cpp (existing code)

```
if (switchOffOnBlack && xy.bri == 0)
{
	light.setOn(false);
}
else
{
	light.setOn(true);
}
// Write color if color has been changed.
light.setTransitionTime(transitionTime);
light.setColor(xy, brightnessFactor);
```

LedDevicePhilipsHue.cpp (proposal)

```
if (switchOffOnBlack && xy.bri == 0)
{
	light.setOn(false);
}
else
{
	light.setOn(true);

        // Write color if color has been changed.
        light.setTransitionTime(transitionTime);
        light.setColor(xy, brightnessFactor);
}
```

However i'm not sure on the implication of not setting `this->transitionTime = transitionTime;` and `this->color = color;` each frame when the light is off - which are found within the light methods.

The above change would ensure the request JSON being sent to each light aligns with how it is in the current generation of Hyperion where this logic works as expected.

**Comment by RickDB** [comment]
@Paulchen-Panther could you check if we can add this fix?

**Comment by Paulchen-Panther** [comment]
I will look today, after work
