### ISSUE TITLE
LED Hardware needs config change before it works

### ISSUE THREAD

**Issue by UniCizin** [hyperion-project/hyperion.ng#547]
Hello,

i have Hyperion.ng up and running with arduino since a month or two.
the only issue still bothering me is that if i start all the devices (raspberry, led power supply etc), the leds stay black.

hyperion.ng is running, in the webconfig i see that there is a picture in the grabber and the arduino does the initial rgb flash 2 or 3 times, but then nothing happens.

I have to change and then reset a parameter in "LED Hardware"-Section to get it working. (set the connection delay f.e.)

any ideas?

**Comment by RickDB** [comment]
Try setting the connection delay setting (start with 5000ms) as it might be that during inital startup with the Arduino it needs a bit more time.
Had the same problem with Hyperion non-ng and that solved it here, using this adalight sketch:

https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/assets/firmware/arduino/adalight/adalight.ino

If you still have the problem just let us know and will check it further.

**Comment by UniCizin** [comment]
it's wierd. 
i have the delay at 9000 ms.. Sometimes it works like a charm, sometimes i have to change one of the parameters.
I dont know wich sketch i used in arduino, but i will try the one mentioned by you just to make sure.

**Comment by UniCizin** [comment]
can be closed.
works like a charm with the sketch mentioned above.

((i also extended the startup effect to a duration of 7500 ms to get it shown))
