### ISSUE TITLE
What's left for a beta/stable version?

### ISSUE THREAD

**Issue by rogerlz** [hyperion-project/hyperion.ng#548]
Hey, 

I would like to offer some help with hyperion.ng to bring it at least to a beta version and release some binary packages so the users don't have to compile it.

I'm not a full-time c++ developer, but I'm sure I can help fix some bugs and/or test things.

I've seen some forum posts with checklists and ToDos, but all seems very old (2016,2017) and I don't know what has been implemented or not.

Do we have an accurate checklist? Should I open new issues for packaging release and work on them? 

What about bi-monthly (I know everyone is busy) release tag so we can have a proper changelog?

Thx

**Comment by b1rdhous3** [comment]
Hi, 

help is always very welcome. 
From my perspective ng would be ready Dir Beta. 

We have one big thing to do:

We have to define and implement automatic Build and deploy process. I think you already saw the process with Travis. We need to complete this. 
Would be great if you can contribute there. 

Thanks!

**Comment by rogerlz** [comment]
Cool. I'll be happy to take a look on that.

**Comment by pattyland** [comment]
Is there anything still blocking? I saw the working Azure Pipelines which look very promising!
