### ISSUE TITLE
Hyperion forwarder

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#55]
The forwarder is one of the greatest extensions of Hyperion. So maybe @redPanther wants to push the usage "comfort in general to come faster in touch and to keep the documentation and "how to setting it up" lines low.
My ideas are the following.

The main instance of Hyperion starts more instances if you set it at a .json file here:

```
    "forwarder" : 
    {
        "json" : ["127.0.0.1:19446"],
        "proto" : ["127.0.0.1:19447"],
                "instance" : SecondConfig.json,ThirdConfig.json
    },
```

On top of this, a auto assignment of ports might be useful too. Why mess around yourself with ports if Hyperion just need to count +2 to the current base value?

A issue might be that we still have the JSON and PROTO port cat at the .json
A option could be to remove the option to configure it (bad, but count the people who change their ports)
or all following hyperion instances need to ignore the setting for JSON and PROTO port at the .json.

/discuss
This post is not to hurry up things, just to keep track of what could be done :)

**Comment by redPanther** [comment]
... this is more an enhancement/new feature then refactoring. "refactoring" means (simplified) - make it better without changing the behaviour

**Comment by brindosch** [comment]
:P

**Comment by penfold42** [comment]
Or maybe a magic port number of 0 to automatically get one ?

**Comment by redPanther** [comment]
Not from 0  -I dont want zo interfere with system services.
I'm thinking about doing port assingment during install phase. This is not so dificult as doing this on normal runtime

**Comment by redPanther** [comment]
What about the possibility to write instead of ip:port a config file for localhost. Then hyperion gets the port (ip is localhost) for forwarding and starts the instance.

then there is a bit less to configure. We also could check for port collisions, e.g. both had boblight on and on the same port ....

**Comment by brindosch** [comment]
you mean something like
```
		"json" : ["nodemcu.left.json:19446"],
		"proto" : ["nodemcu.left.json:19447"]
```
Sounds good! Better to handle indeed.

**Comment by redPanther** [comment]
yes, but without port. only remote hosts need ip:port
```
        "json" : ["nodemcu.left.json,192.168.178.99:19445"],
        "proto" : ["nodemcu.left.json,192.168.178.99:"]

```

**Comment by brindosch** [comment]
an this information could be extracted to start also a child process? The issue we run into is definitely that we have no root access, so no access to service files to add additional configs to start.
:)

**Comment by redPanther** [comment]
> an this information could be extracted to start also a child process?

yep, we get the port from the config itself

**Comment by brindosch** [comment]
I consider this closed,  forwarder need to be configured by hand afterwards, but spawning is now under easy access.
