### ISSUE TITLE
Error when pulling hyperionorg/hyperion-ci

### ISSUE THREAD

**Issue by funnym0nk3y** [hyperion-project/hyperion.ng#553]
When running the command for compilation in a docker container pulling the image `hyperionorg/hyperion-ci` of dockerhub fails. Error message is `Error response from daemon: manifest for hyperionorg/hyperion-ci:latest not found`

There is a similar case described in the forum, but without a solution. [http://wiki.hyperion-project.org/threads/installing-hyperion-ng.3491/page-2#post-14337](url)

**Comment by Paulchen-Panther** [comment]
It is a typo in this [File on this Line](https://github.com/hyperion-project/hyperion.ng/blob/b1b2079f972330c757b50f4c6615e810df4e3e10/bin/scripts/docker-compile.sh#L97)

Please change to hyperion-project/hyperion-ci

**Comment by funnym0nk3y** [comment]
This is one of my first interactions with a open source project. Should I clone this project, change it and make a pull request?

**Comment by Paulchen-Panther** [comment]
Fork -> Change -> Pull Request
