### ISSUE TITLE
ESP32 + APA102 + wifi = flickering?

### ISSUE THREAD

**Issue by deex2** [hyperion-project/hyperion.ng#557]
Hi,

I am currently building a setup with an ESP32 + APA102 + RPI0 w + Pi Camera. I am using also the code from here: https://github.com/SciLor/Hyperion_LED-Controller
The problem is that the leds are not stable at all. I am using the last version of the code that I have compiled on the RPI0.
At the beginning, I was thinking that it was a hardware problem, so I did multiple tests. At the end, it looks like a software problem.
Here some tests I did: if I turn the RPI0 + Hyperion, the ESP32 is showing a default color:
Here a video:
https://drive.google.com/file/d/1whaHCECnqdubt3Pj-SG7R2H-W-0Eexab/view?usp=sharing

As we can see here, leds are stable. Some this is not a hardware problem, or a esp32 problem.

If I turn on Hyperion.ng, the ESP32 is connected, and I ask Hyperion.ng to show an effect (flag for example). Here a video:
https://drive.google.com/file/d/1rcyTIvgrRD7z7GbB43no97DIXo5S4Ior/view?usp=sharing

As we can see, this is not stable at all, this is flickering. So I guess there is a problem with Hyperion.ng?
Any idea of why?

Thank you.

**Comment by tpmodding** [comment]
sounds more like an issue with the data signal, do you have a level shiffter?
