### ISSUE TITLE
Travis and Docker

### ISSUE THREAD

**Issue by Paulchen-Panther** [hyperion-project/hyperion.ng#560]
@RickDB 
Did you notice that the Travis CI check is aborted due to exceeding the maximum time limit?
Oddly, Travis goes through all platforms in my fork. I saw that Travis treated the Docker image differently under my fork than in the official master. Would it be possible to create an official repository ([docker-ci](https://github.com/hyperion-project/docker-ci)) for the Docker files? At the moment this runs over my account. ([docker-ci](https://github.com/Paulchen-Panther/docker-ci))

______________________________________________________________________

_**Official Repository:**_
![hyperion-project](https://user-images.githubusercontent.com/16664240/57983593-1df5cb80-7a54-11e9-88fb-a166cbf8e563.png)

![docker-hyperion-project](https://user-images.githubusercontent.com/16664240/57983569-b6d81700-7a53-11e9-9d01-2aeeb635150e.png)

![terminated](https://user-images.githubusercontent.com/16664240/57983614-6ad9a200-7a54-11e9-9612-5839ef0f655d.png)

______________________________________________________________________

_**My Fork:**_
![paulchen-panther](https://user-images.githubusercontent.com/16664240/57983609-5695a500-7a54-11e9-8d3e-166b8d911d5e.png)

![docker-paulchen-panther](https://user-images.githubusercontent.com/16664240/57983573-c192ac00-7a53-11e9-872e-f21626147296.png)

**Comment by RickDB** [comment]
Noticed as well and usually it corrects itself, will fix it today :)

**Comment by RickDB** [comment]
Travis is retrying with cleared caches so that usually sorts it out

New docker repo created as well:

https://github.com/hyperion-project/hyperion.docker-ci

**Comment by RickDB** [comment]
Hmm failed to build again for certain platforms:

https://travis-ci.org/hyperion-project/hyperion.ng/builds/534635873

It used to work fine and always check Travis before merging so new commit causing it is unlikely, do we need to adjust something on Travis's end?

**Comment by Paulchen-Panther** [comment]
I think it lacks a permit. can you look into your e-mail? I have made a request. ![](https://i.imgur.com/AE8Nshe.png)

**Comment by Paulchen-Panther** [comment]
More information: https://docs.docker.com/docker-hub/builds/link-source/#grant-access-to-a-github-organization

**Comment by RickDB** [comment]
Lists it as approved, can try to revoke and re-add if it's still pending.


![Capture](https://user-images.githubusercontent.com/347084/58034435-e146d480-7b26-11e9-8113-9b50f10eb2d8.PNG)

**Comment by Paulchen-Panther** [comment]
Thank you. do you have a docker account? I would like to invite you. :+1:

**Comment by Paulchen-Panther** [comment]
![](https://i.imgur.com/lD5avLn.png)

**Comment by Paulchen-Panther** [comment]
![](https://i.imgur.com/cIcjjrs.png)

**Comment by Paulchen-Panther** [comment]
I'll do some tests this weekend. I always work so long during the week. Nevertheless, many thanks for your help

**Comment by RickDB** [comment]
Will create a docker account and pm you the details later :)

Thanks again for you work on this 👍
