### ISSUE TITLE
WebCam issue (Priority/inactive)

### ISSUE THREAD

**Issue by UniCizin** [hyperion-project/hyperion.ng#561]
Hey, i tried to get hyperion.ng running with a webcam pointing at my tv.

at first it worked well, but after some time i cant seem to get it back running again
the attached log always repeats a message.
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:231:setInputImage()) Priority 100 is now inactive
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:231:setInputImage()) Priority 100 is now active
[log.txt](https://github.com/hyperion-project/hyperion.ng/files/3195536/log.txt)

**Comment by Paulchen-Panther** [comment]
how did you compile hyperion.ng?

**Comment by UniCizin** [comment]
I followed the tutorial in the Wiki.

**Comment by Paulchen-Panther** [comment]
with docker or the usual way?

**Comment by UniCizin** [comment]
The usual way.

**Comment by Paulchen-Panther** [comment]
OK. I have already fixed some mistakes in my fork. May be that this error is also resolved. You could try the following.
Replace line 297 in PriorityMuxer.cpp with [this line](https://github.com/Paulchen-Panther/hyperion.ng/blob/V4L2/libsrc/hyperion/PriorityMuxer.cpp#L297)

**Comment by UniCizin** [comment]
and then just recompile or is it necessary to clean up files or something?

**Comment by Paulchen-Panther** [comment]
Cleanup ist not necessary.  Just compile

**Comment by UniCizin** [comment]
This works well. Thank you
