### ISSUE TITLE
Hyperion.Ng

### ISSUE THREAD

**Issue by Moimemeici** [hyperion-project/hyperion.ng#565]
Hello, 
sorry for my english, but Thank you for this Work
and i'am going use Docker but i have this problem, sorry for disturb.

# docker run --tty --interactive hyperionproject/hyperion-ci:amd64
Command not found:

best regard

**Comment by RickDB** [comment]
Hi,

Gonna ping @Paulchen-Panther as he knows more about the docker images :)

**Comment by Paulchen-Panther** [comment]
@Moimemeici Which hardware and which os?

**Comment by Moimemeici** [comment]
I have Debian 9.0 with docker last version.
I'm not using usb capture.

**Comment by Paulchen-Panther** [comment]
Could you please post the console output "sudo systemctl status docker"?

**Comment by Paulchen-Panther** [comment]
I will close this here due to missing feedbacks. For further questions, just reopen the issue.
