### ISSUE TITLE
webserver port fallback

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#57]
QtHttpServer error : "The bound address is already in use"

For more comfort, i would prefer port 80, in case port 80 is already in use by another application, could we use 8099 as fallback before we quit the server?

Why? Why not :)
People use Hyperion primarily on a Pi with a mediacenter distribution. So port 80 might be applicable for 99% of users

**Comment by penfold42** [comment]
OSMC kodi defaults to port 80

**Comment by brindosch** [comment]
Yours? My osmc kodi points to 8080, like on all other default installs.

**Comment by penfold42** [comment]
https://discourse.osmc.tv/t/osmc-nfsroot-web-server-cant-bind-port-80/17262

**Comment by brindosch** [comment]
Currently my Hyperion runs on port 80. So this is for new  installs? Than they changed it.

If i think about it, it may be better we use our own port.
Would be great to open the Webinterface after the new  installer was successful.

I plan currently a small wizard which replace the hypercon  installation (when  we are ready for a drop)

**Comment by penfold42** [comment]
Maybe zeroconf can help here to find it
