### ISSUE TITLE
Support for libpython >= 3.5

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#570]
Hi

doing an x86x64 hyperion.ng build on Ubuntu 18.10 works fine with python 3.6 installed.
Unfortunately, installing the .deb package on 18.10 or 19.04 via apt fails due to a dependency to libphython3.5.

```
sudo apt-get install --dry-run ./Hyperion-2.0.0-Linux-x86.deb
...
The following packages have unmet dependencies.
 **hyperion-x86 : Depends: libpython3.5 but it is not installable**
E: Unable to correct problems, you have held broken packages
```

Is there a way to support libpython3.5 and 3.6 in parallel?

Many thanks in advance
Lord-Grey

**Comment by Paulchen-Panther** [comment]
Can you try the `|` vertical bar (pipe) symbols separator [on this line](https://github.com/hyperion-project/hyperion.ng/blob/master/cmake/packages.cmake#L46)?

`SET ( CPACK_DEBIAN_PACKAGE_DEPENDS "libqt5core5a (>= 5.5.0), libqt5network5 (>= 5.5.0), libqt5gui5 (>= 5.5.0), libqt5serialport5 (>= 5.5.0), libqt5sql5 (>= 5.5.0), libqt5sql5-sqlite (>= 5.5.0), libavahi-core7 (>= 0.6.31), libavahi-compat-libdnssd1 (>= 0.6.31), libusb-1.0-0,` **libpython3.4 | libpython3.5 | libpython3.6**`, libc6" )`

**Comment by Lord-Grey** [comment]
Adding libpython3.5 | libpython3.6 | libpython3.7 did the trick to be able to install the deb package.
I can do a PR for this.

Unfortunately, when I execute hyperiond on Ubuntu 19.04,  which is on Python 3.7.3, I get the following error:
`hyperiond: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
`
hyperiond and the deb-package was build on Ubuntu 18.10 with Python 3.6.

Does it mean that the executable needs to be build differently or is there a missing dependency?
Thank you!

**Comment by brindosch** [comment]
Hello,
Hyperion links always to one specific python version during compilation. So you said you build with 3.6 so you need always 3.6. The required version in .deb dependency should always match with the system Hyperion in compiled on. In our case it's based on travis/azure machines

But @Paulchen-Panther is currently organizing the auto publishing of new test version when available. So you no longer need to mess around on your own for testing.

**Comment by Lord-Grey** [comment]
But how would this solve the problem of getting Hyperion.ng running on multiple Ubuntu versions having different python3 subversions each?
e.g. if the azure machine links python3.5, it will not run/install on ubuntu 18 (python3.6) nor ubuntu 19 (python 3.7) with the current way of doing things... or do I miss something?

**Comment by Paulchen-Panther** [comment]
> or do I miss something?

Yes. We can build for multiple versions of Ubuntu if requested

**Comment by Lord-Grey** [comment]
Thank you!
