### ISSUE TITLE
Unable to run install via Docker on PI 0 W

### ISSUE THREAD

**Issue by Joeboyc2** [hyperion-project/hyperion.ng#577]
Hey @Paulchen-Panther,

I'm trying to install the latest release via the docker command on a Raspberry pi 0 W running Docker version 18.06.2-ce, build 6d37f41 (im having to run this version as its the only one that is know to run correctly on by PI) but i get the following error:
```
---> Startup docker...
standard_init_linux.go:190: exec user process caused "exec format error"
---> Hyperion compilation failed! Abort

```
Here the whole output from the console:
```
pi@Hyperion:~ $ wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -t armv6hf
---> Initilize with BUILD_TARGET=armv6hf, BUILD_TYPE=Release, BUILD_PACKAGES=true
---> Downloading Hyperion source code from https://github.com/hyperion-project/hyperion.ng.git
Submodule 'dependencies/external/flatbuffers' (https://github.com/google/flatbuffers) registered for path 'dependencies/external/flatbuffers'
Submodule 'dependencies/external/protobuf' (https://github.com/hyperion-project/protobuf.git) registered for path 'dependencies/external/protobuf'
Submodule 'dependencies/external/rpi_ws281x' (https://github.com/hyperion-project/rpi_ws281x.git) registered for path 'dependencies/external/rpi_ws281x'
Cloning into '/home/pi/hyperion.ng/dependencies/external/flatbuffers'...
Cloning into '/home/pi/hyperion.ng/dependencies/external/protobuf'...
Cloning into '/home/pi/hyperion.ng/dependencies/external/rpi_ws281x'...
Submodule path 'dependencies/external/flatbuffers': checked out '0eb7b3beb037748bf5b469e4df9db862c4833e35'
Submodule path 'dependencies/external/protobuf': checked out 'adce8a99fdab90f290d659b6b3bf2d09b721e24a'
Submodule path 'dependencies/external/rpi_ws281x': checked out '6c5ade93d1af78cd19e60ee5ecc34adfd111b186'
---> Startup docker...
standard_init_linux.go:190: exec user process caused "exec format error"
---> Hyperion compilation failed! Abort

```
seems its the docker run command that is failing :(

**Comment by Paulchen-Panther** [comment]
Hello @Joeboyc2 
Sorry for the missing documentation. The docker build script runs only on the X86_64 architecture. cross compile makes no sense on a rpi.

**Comment by Joeboyc2** [comment]
Oh.... so does the raspi zero section need removing from the compile how to
section?

**Comment by Paulchen-Panther** [comment]
Not really. You can use the docker build script to create the binaries on an x64_86 platform.

**Comment by Joeboyc2** [comment]
Ah so I could build the binary for my zero w on my pi 3 and move it over to
run?

I assume it was an install that ran in a docker container... please correct
me if I have completely for this wrong lol

**Comment by Paulchen-Panther** [comment]
> Ah so I could build the binary for my zero w on my pi 3 and move it over to run?

No. Only on x64_86 platform. RPI is ARM platform.
What I could do is create a docker image for the ARM platform. Then you could create the image for the rpi zero on your RPI3

**Comment by Joeboyc2** [comment]
Ah I completely get it now, so I can build it on my windows machine and
then run it on the zero!

**Comment by Paulchen-Panther** [comment]
yes. :+1:

**Comment by Paulchen-Panther** [comment]
New Docker tag 'rpi-raspbian' is created. So you can start compiling hyperion inside docker from your rpi.
Command:
`wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -t rpi-raspbian`

**Comment by Joeboyc2** [comment]
Legend! i was more than happy to run it on my windows machine, but, if i can run it directly that's even better, i'll try it now :)

**Comment by Paulchen-Panther** [comment]
If you receive an error like "Failed to parse version.json string properly. Expect X.Y.Z." please wait until tomorrow and try again. I'm looking for a fix

**Comment by Joeboyc2** [comment]
ah, Snap, got an error :(

`pi@Hyperion:~ $ wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -t rpi-raspbian
---> Initilize with BUILD_TARGET=rpi-raspbian, BUILD_TYPE=Release, BUILD_PACKAGES=true
---> Downloading Hyperion source code from https://github.com/hyperion-project/hyperion.ng.git
Submodule 'dependencies/external/flatbuffers' (https://github.com/google/flatbuffers) registered for path 'dependencies/external/flatbuffers'
Submodule 'dependencies/external/protobuf' (https://github.com/hyperion-project/protobuf.git) registered for path 'dependencies/external/protobuf'
Submodule 'dependencies/external/rpi_ws281x' (https://github.com/hyperion-project/rpi_ws281x.git) registered for path 'dependencies/external/rpi_ws281x'
Cloning into '/home/pi/hyperion.ng/dependencies/external/flatbuffers'...
Cloning into '/home/pi/hyperion.ng/dependencies/external/protobuf'...
Cloning into '/home/pi/hyperion.ng/dependencies/external/rpi_ws281x'...
Submodule path 'dependencies/external/flatbuffers': checked out '0eb7b3beb037748bf5b469e4df9db862c4833e35'
Submodule path 'dependencies/external/protobuf': checked out 'adce8a99fdab90f290d659b6b3bf2d09b721e24a'
Submodule path 'dependencies/external/rpi_ws281x': checked out '6c5ade93d1af78cd19e60ee5ecc34adfd111b186'
---> Startup docker...
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:35 (message):
  Failed to parse version.json string properly.  Expect X.Y.Z.


-- Configuring incomplete, errors occurred!
See also "/hyperion.ng/build/CMakeFiles/CMakeOutput.log".
---> Hyperion compilation failed! Abort
`
This is running it directly on the Zero, do you thin it would be any different if i run it on my 3 or 4?

**Comment by Joeboyc2** [comment]
ah, just seen your post, no worries, thank you for your help on this :)

**Comment by Paulchen-Panther** [comment]
I would be ready! :grin:

**Comment by Joeboyc2** [comment]
managed to build it now @Paulchen-Panther :)
But i'm stuck trying to get it to load lol, i have found many hyperiond files but when i try to run them it fails with scheme errors,

i am however able to get it to run if i simply type hyperiond, im not sure what the differences are or if that is even the right version that is running - Could be an old install, although i have deleted my previous folders

**Comment by b1rdhous3** [comment]
So if you run ./hyperiond without any arguments hyperion will create a new file called "hyperion_main.json" in ~/.hyperion/config. 
I suggest you start with this fresh config again. 

We have autocorrection in hyperionng for configs but since I don't know from which version you are coming this can maybe fail. 
Hope this helps

**Comment by Joeboyc2** [comment]
so i don't have anything related to hyperion in my "/usr/bin" dir :(
I was running one of @Paulchen-Panther 's releases he had in his repository (no longer there however) im not sure where that installs to.

while writing this i actually managed to find where it was executing from :-) "/usr/local/bin/hyperiond" & "/usr/local/share/hyperion/bin/hyperion"
removing these folders now prevents hyperiond from running 👍 

I'll clean up my folders (removing /home/pi/.hyperion & /.hyperion and try the docker compile again so see what i get this time

**Comment by Paulchen-Panther** [comment]
> I was running one of @Paulchen-Panther 's releases he had in his repository (**no longer there however**) im not sure where that installs to.

It is integrated in the official repo. You do not need my branch.

**Comment by b1rdhous3** [comment]
Ok, good. Pls report back then :)

**Comment by Joeboyc2** [comment]
Yeh I'm happy to use the official repo now was just stating that as that
was the version I was running 👍

So pleased this new version is getting so much support now, happy to test
the new features and help where I can to get it to a proper release 😁

**Comment by Joeboyc2** [comment]
So the compile has finished (I took my boys out swimming (but also the pi zero is ssslllooowwwww lol))

I now have a 'deploy' folder and a 'hyperion.ng' folder in '/home/pi'

What are next steps....?

**Comment by b1rdhous3** [comment]
What do you find in this folders? There should be some binarys. 
I personally don't use the docker compiling method so I can't exactly say where the bins are located now.

**Comment by Paulchen-Panther** [comment]
In the 'deploy' folder your are finding installable packages and compressed tar.gz achives with the binarys. The hyperion.ng folder is used to compile hyperion in docker.

**Comment by Joeboyc2** [comment]
i managed to have a play around last night and got it all running via the deploy folder using the hyperiond binary there.
I didn't want to play around with the other files as i wasn't sure what each did.
I've created a service file based on the hyperion.systemd file in 'hyperion.ng/bin/service' pointing it to the hyperiond binary in '/home/pi/deploy' and that is working fine so i'll probably just run it like that for the moment.

Thanks for all you help guys, i guess we can close this issue off cant we?

**Comment by Paulchen-Panther** [comment]
> @Paulchen-Panther can i remove the hyperion.ng folder now the binary's have been built? or is it a good idea to keep it around? will it make the next compiles any quicker?

Yes, you can remove the folder.
No, the dockerscript cleans the folder before building the next release

**Comment by Joeboyc2** [comment]
Ok great stuff, I'll clean up a bit and wait for the next realise cheers
guys 👍
