### ISSUE TITLE
LEDs left on after effects run

### ISSUE THREAD

**Issue by Joeboyc2** [hyperion-project/hyperion.ng#583]
Hi all,
Having an issue with effects not clearing the LEDs when they finish or source is closed, the most obvious way this is affecting my setup is after the startup effects runs (rainbow swirl) the LEDs are left on, nice as it might be, they used to turn off on the older version I was using.

For reference this is the version I am running currently:

`pi@Hyperion:~/deploy $ ./hyperiond --version
Hyperion Ambilight Deamon (13983)
        Version   : 1.0.0 (master (Paulchen-Panther-48bf005/bea8345-1562747080) Git Remote: https://github.com/hyperion-project/hyperion.ng.git)
        Build Time: Jul 13 2019 12:27:03`

**Comment by Joeboyc2** [comment]
The only way I can clear the LEDs is to apply another colour or turn them on then off again using my home assistant switch (which just send the clear command I think)

**Comment by Paulchen-Panther** [comment]
Which LED device is affected?

> pi@Hyperion:~/deploy $ ./hyperiond --version Hyperion Ambilight Deamon (13983) Version : 1.0.0 (master (Paulchen-Panther-48bf005/bea8345-1562747080) Git Remote: https://github.com/hyperion-project/hyperion.ng.git) Build Time: Jul 13 2019 12:27:03

Is this version running correctly?

**Comment by Joeboyc2** [comment]
I'm running apa102s and other than the minor effects issue all seems to be working fine, I don't use a grabber but I am feeding in data via the android screen grabber app and that works fine too

**Comment by Paulchen-Panther** [comment]
Thanks for your feedback. I'll take a look at that later.

**Comment by Joeboyc2** [comment]
Happy to grab logs or run some tests to help out if needed

**Comment by b1rdhous3** [comment]
Just compiled the current master with Docker on x64 for my raspberry pi zero w running raspbian. I also use apa102 (with lightberry mode). 
I can confirm this bug. 

If you configure your system without any capture like instance capture or usb capture and no background effect the boot up effect stays where it is and the leds wont turn off. 
Log:
```
./hyperiond test -d
[hyperiond DAEMON] <DEBUG> <PythonInit.cpp:20:PythonInit()> Initializing Python interpreter
[hyperiond SettingsManager] <INFO> Selected configuration file: /home/pi/.hyperion/config/test.json
[hyperiond SettingsManager] <DEBUG> <SettingsManager.cpp:129:SettingsManager()> Settings database initialized
[hyperiond EFFECTFILES] <INFO> 36 effects loaded from directory :/effects/
[hyperiond EFFECTFILES] <INFO> 19 effect schemas loaded from directory :/effects/schema/
[hyperiond EFFECTFILES] <INFO> 4 effects loaded from directory /home/pi/.hyperion/custom-effects
[hyperiond SettingsManager] <INFO> Selected configuration file: /home/pi/.hyperion/config/test.json
[hyperiond SettingsManager] <DEBUG> <SettingsManager.cpp:73:SettingsManager()> Settings database initialized
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:65:handleSettingsUpdate()> Set mode to: default
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:67:componentStateChanged()> Blackborder detector: enabled
[hyperiond FLATBUFCONNECTION] <INFO> Connecting to Hyperion: 127.0.0.1:19401
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:67:componentStateChanged()> LED device: enabled
[hyperiond LEDDEVICE] <DEBUG> <LedDeviceAdalight.cpp:37:init()> Adalight driver with activated LightBerry APA102 mode
[hyperiond LEDDEVICE] <DEBUG> <LedDeviceAdalight.cpp:53:init()> Adalight header for 26 leds: Ada 0x00 0x1a 0x4f
[hyperiond LEDDEVICE] <INFO> LedDevice 'adalight' configured.
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:67:componentStateChanged()> Smoothing: enabled
[hyperiond EFFECTENGINE] <INFO> run effect Rainbow swirl fast on channel 0
[hyperiond LEDDEVICE] <INFO> Opening UART: /dev/ttyACM0
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:153:registerInput()> Register new input 'System/EFFECT' with priority 0 as inactive
[hyperiond HYPERION] <INFO> Initial foreground effect 'Rainbow swirl fast' started
[hyperiond BOBLIGHT] <DEBUG> <BoblightServer.cpp:24:BoblightServer()> Instance created
[hyperiond DAEMON] <INFO> Hyperion initialized
[hyperiond DAEMON] <INFO> set screen capture device to 'dispmanx'
[hyperiond DISPMANXGRABBER] <DEBUG> <Grabber.cpp:33:setVideoMode()> Set videomode to 0
[hyperiond LEDDEVICE] <DEBUG> <ProviderRs232.cpp:182:tryOpen()> Setting baud rate to 1000000
[hyperiond LEDDEVICE] <DEBUG> <ProviderRs232.cpp:198:tryOpen()> Device blocked for 1500 ms
[hyperiond DISPMANXGRABBER] <INFO> Display opened with resolution: 720x480
[hyperiond DISPMANXGRABBER] <DEBUG> <Grabber.cpp:82:setWidthHeight()> Set new width: 80, height: 45 for capture
[hyperiond DAEMON] <INFO> DISPMANX frame grabber created
[hyperiond V4L2:auto] <DEBUG> <Grabber.cpp:33:setVideoMode()> Set videomode to 0
[hyperiond V4L2:auto] <INFO> Signal threshold set to: {12, 12, 12}
[hyperiond V4L2:auto] <INFO> Signal detection is now disabled
[hyperiond V4L2:auto] <INFO> Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
[hyperiond DAEMON] <DEBUG> <hyperiond.cpp:413:handleSettingsUpdate()> V4L2 grabber created
[hyperiond JSONSERVER] <DEBUG> <JsonServer.cpp:23:JsonServer()> Created instance
[hyperiond JSONSERVER] <INFO> Started on port 19444
[hyperiond PROTOSERVER] <INFO> Started on port 19445
[hyperiond FLATBUFSERVER] <INFO> Started on port 19400
[hyperiond WEBSERVER] <DEBUG> <WebServer.cpp:96:handleSettingsUpdate()> Set document root to: :/webconfig
[hyperiond WEBSERVER] <INFO> Started on port 8090 name 'Hyperion Webserver'
[hyperiond LEDDEVICE] <DEBUG> <LedDeviceAdalight.cpp:80:receivedData()> >>received 4 bytes data
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:231:setInputImage()> Priority 0 is now active
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:330:setCurrentTime()> Set visible priority to 0
[hyperiond LEDDEVICE] <DEBUG> <ProviderRs232.cpp:216:writeBytes()> 35 frames dropped
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:290:setCurrentTime()> Timeout clear for priority 0
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:330:setCurrentTime()> Set visible priority to 255
[hyperiond EFFECTENGINE] <INFO> effect finished
[hyperiond WEBSOCKET] <DEBUG> <WebSocketClient.cpp:32:WebSocketClient()> New connection from ::ffff:192.168.178.21
[hyperiond WEBSOCKET] <DEBUG> <WebSocketClient.cpp:197:sendClose()> send close: 1000
[hyperiond WEBSOCKET] <DEBUG> <WebSocketClient.cpp:32:WebSocketClient()> New connection from ::ffff:192.168.178.21
```


My productive running build is working correctly and the leds turn off after startup effect. I also don't use any capute device there. Currently I only using windows grabber but this grabber does not send data always, so sometime there is no grabber active at my build. Especially after boot. 

I currently use this version productive. So I think somewhere in the meantime it broke.  

Build BugFixes2 (Paulchen-Panther-a406fef1/2ae692de-1550520990) Git Remote: https://github.com/hyperion-project/hyperion.ng.git

Build date | Feb 21 2019 23:10:08

**Comment by Paulchen-Panther** [comment]
@b1rdhous3 Ich kann eure Situation nicht nachvollziehen. Mein Fadecandy device schaltet nach dem booteffekt korrekt ab. Auch das test ausgabegerät file zählt alles korrekt auf (boot effekt und black signal).
Am WE könnte ich in der Wohnstube mein Adalight ausprobieren.

**Comment by b1rdhous3** [comment]
@Paulchen-Panther dann scheint es irgendwie am LEDDevice zu liegen oder so. Der Effekt bleibt auf jeden Fall stehen. In der Prioritätenliste ist nach dem Spielen des Effekts nichts. Die ist komplett leer. Trotzdem bleiben die Farben bestehen. 
Im verlinkten Gist findest du die Consolenausgabe und die aktuelle Config welche ich zum Test verwendet habe. (Da kannst du auch sehen, dass ich keine Grabber an habe und keinen Hintergrundeffekt)
Ich hab das gerade erstellt. Also auch nochmal frisch verifiziert. 

https://gist.github.com/b1rdhous3/1ce98dea8a85ab1b27b2e791e46aeedc

@Joeboyc2 Sorry for talking German. It is much easier to clarify it this way.

**Comment by Joeboyc2** [comment]
Haha no worries @b1rdhous3 I know a little German but I can always use google translate to follow along, you guys know much more about this than I do so just loop me back in if you need me to test anything 😁

**Comment by brindosch** [comment]
I think that is a led device specific bug. Never ever had a problem with the apa102 for example.

**Comment by b1rdhous3** [comment]
This occours in apa102. With a Build from february everything is Fine. So it have to be some change in between.

**Comment by brindosch** [comment]
Oh, okay. So i should probably test it again :)

**Comment by Paulchen-Panther** [comment]
Ich muss zugeben, ich habe nur meinen PR getestet. Könntet ihr den vielleicht Mal testen? Wenn das Problem nicht mehr besteht brauchen wir auch nicht weiter suchen. 

@Joeboyc2 Can you maybe test my PR? If the problem no longer exists we do not need to search further.

**Comment by Joeboyc2** [comment]
Happy to test @Paulchen-Panther, where can I find your pr code?

**Comment by Paulchen-Panther** [comment]
#578

**Comment by Joeboyc2** [comment]
I'll take a look this evening and then get back to you 👍

**Comment by brindosch** [comment]
OT: If someone is super bored, here is something for testing with Kodi :)
https://github.com/hyperion-project/hyperion.ng/issues/474

**Comment by Joeboyc2** [comment]
Hey @Paulchen-Panther, i've finally got around to re-compiling, i wasnt sure how to do it directly from your PR so i compiled it based on your fork of this repo.

Here is the version i am running now:
`pi@Hyperion:/ $ /home/pi/deploy/hyperiond --version
Hyperion Ambilight Deamon (5505)
        Version   : 1.0.0 (master (GitHub-3cef94e/77299ba-1563551059) Git Remote: https://github.com/Paulchen-Panther/hyperion.ng.git)
        Build Time: Jul 28 2019 13:22:38`

Unfortunately i still have the same issue on this latest version, did i do something wrong, or it is best to compile from the PR, and if so, how would i go about doing that?

**Comment by Paulchen-Panther** [comment]
@Joeboyc2 

> `pi@Hyperion:/ $ /home/pi/deploy/hyperiond --version Hyperion Ambilight Deamon (5505) Version : 1.0.0 (master (GitHub-3cef94e/77299ba-1563551059) Git Remote: https://github.com/Paulchen-Panther/hyperion.ng.git) Build Time: Jul 28 2019 13:22:38`

my PR branch is 'api_auth' not 'master'.
Replace in the 'docker-compile.sh':

The [line 5](https://github.com/Paulchen-Panther/hyperion.ng/blob/api_auth/bin/scripts/docker-compile.sh#L5) with this:
`GIT_REPO_URL="https://github.com/Paulchen-Panther/hyperion.ng.git"`

The [line 85](https://github.com/Paulchen-Panther/hyperion.ng/blob/api_auth/bin/scripts/docker-compile.sh#L85) with this:
`git clone --recursive --single-branch --branch api_auth --depth 1 -q $GIT_REPO_URL $SCRIPT_PATH/hyperion.ng || { echo "---> Failed to download Hyperion source code! Abort"; exit 1; }`

and run the script again.

**Comment by Joeboyc2** [comment]
thanks for getting back to me so fast, silly mistake on my side :( re-compiling now, back to you in a little bit (its slow on the Pi Zero) will be faster next time as i can run on a pi 4 :)

**Comment by Joeboyc2** [comment]
Hey @Paulchen-Panther , Finally finished Compiling :(
Anyway, after resetting up the config ( i assume this is due to the config file going away and its now using the database) its all now working fine :) no more stuck effects.

I did have one issue however, but like i said its now working fine

When configuring my LED layout:
![image](https://user-images.githubusercontent.com/8202030/62012854-5bc54d80-b183-11e9-9568-903d28b27757.png)
hyperion stopped, i looked in the console and i had this error 
`pi@Hyperion:~/deploy $ ./hyperiond
[hyperiond DISPMANXGRABBER] <ERROR> Failed to open display! Probably no permissions to access the capture interface
**
GLib:ERROR:/build/glib2.0-F5w919/glib2.0-2.50.3/./glib/gmain.c:3158:g_main_dispatch: assertion failed: (source)
Segmentation fault
`
Restarting Hyperion worked and the led config had been saved so its not a massive issue

**Comment by brindosch** [comment]
Thank you for your feedback,
so you saved your layout and it crashed? Can you repeat this crash case?
I wonder because dispmanx has nothing to do with the led configuration.
What happens when you change the settings for platform capture (pixels for example). Does it crash too?

**Comment by Joeboyc2** [comment]
yeh, basically, however subsequent saves work just fine, it was only the first time i saved it.
That displaymax error was the first thing that came up before i even loaded the web interface, the error i got from saving is the part after the **
Changing the pixels values on the platform capture and saving working just fine (i don't use platform capture however) but it has turned the lights on so  i know it is still running

**Comment by brindosch** [comment]
Hello @Joeboyc2 
Can you please test our current master? A bunch of new stuff is now available with many fixes :)
You can delete/rename your `.hyperion` folder in your home directory for a complete reset.
Would be interesting how it goes now!

Thank you

**Comment by Joeboyc2** [comment]
ok cool, i'll give it a go now, gives me the chance to use my other pi to compile, should be much quicker then using my zero :P

**Comment by Joeboyc2** [comment]
@brindosch, i have compiled and am running the latest version, it didn;t however ask me to re-configure anything even after i renamed the .hyperion folder

**Comment by brindosch** [comment]
No settings reset? Everything still there? Did you probably run as another user or root? Hyperion uses a
 folder. there is no way around :)
Anyway, any issues or errors present?

**Comment by Joeboyc2** [comment]
Ah looks like it was running as root , deleted the folders now and its
reset so I'll try to set it up again and see what happens 👍

**Comment by brindosch** [comment]
A good point! I've added a log msg for the user data folder. So you see what's going on. https://github.com/hyperion-project/hyperion.ng/pull/602

**Comment by Joeboyc2** [comment]
Setup just fine this time, no default when setting the leds layout and the
leds are not left on after an effect so I think all my issues are solved!

Great work guys 👍

**Comment by brindosch** [comment]
Sounds good!
Thank you
