### ISSUE TITLE
hyperion crashes after executing hue wizard

### ISSUE THREAD

**Issue by isarvalley** [hyperion-project/hyperion.ng#585]
Hi,

I try to configure hyperion ng to work with my hue light bulbs. But as soon as the hue wizard is closed hyperion crashes.  I installed hyperion on a raspberry pi 3 with raspbian buster.

This is the error I get, after the hue wizard is closed:

[hyperiond DISPMANXGRABBER] <ERROR> Snapshot failed: -1
[hyperiond DISPMANXGRABBER] <ERROR> Snapshot failed: -1
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x719023d4), parent's thread is QThread(0x6bd1f8f0), current thread is QThread(0xfab4e8)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x719023d4), parent's thread is QThread(0x6bd1f8f0), current thread is QThread(0xfab4e8)
Segmentation fault

When I start hyperion again I get this error:

pi@hyperion:~/hyperion.ng/build/bin $ ./hyperiond
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called recursively
terminate called recursively
terminate called recursively

May be someone can point out what I am doing wrong.

Best Regards,

Johannes

**Comment by b1rdhous3** [comment]
Which build version do you use? What is your build date?
Please consult "About Hyperion" on WebUI for this.

**Comment by bosco688** [comment]
Hey,

i have exactly the same problem with hue.

Compiled hyperion today from master.

Version | 1.0.0
-- | --
Build | master (GitHub-3cef94e/77299ba-1563551059) Git Remote: https://github.com/hyperion-project/hyperion.ng.git
Build date | Jul 30 2019 14:05:44

My hue:

Bridge BSB002, software version 1933087030
3x Play bar LCT024, software version 1.46.13_r26312

Some ideas?

Thanks

**Comment by bosco688** [comment]
Got it.

Its the smoothing parameter "enable". If the value is set to "false" (which is the default when using the wizard) hyperion crashes.

**Comment by Paulchen-Panther** [comment]
> Got it.
> 
> Its the smoothing parameter "enable". If the value is set to "false" (which is the default when using the wizard) hyperion crashes.

I have already fixed this error in my [PR](https://github.com/hyperion-project/hyperion.ng/pull/578) (hopefully). Once the smoothing was turned off, [the LED device was turned off](https://github.com/hyperion-project/hyperion.ng/pull/578/files#diff-92b4fc9c56b95f8aace44667f1af50deL183). That's why the wizard did not work anymore.

**Comment by bosco688** [comment]
Merci :)

Dann warte ich oder probiere diesen Stand mal aus.

PS - auch wenn offtopic... verwendet Hyperion die Rest API oder Entertainment API von Hue?

**Comment by Paulchen-Panther** [comment]
You are welcome to try my PR.

At the moment, Hyperion still uses the REST API. @SJunkies is currently working on the Entertainment API. His branch is at https://github.com/SJunkies/hyperion.ng/tree/entertainment-api-2019

**Comment by bosco688** [comment]
Tried @SJunkies hue entertainment implementation. It works great so far :)

I will try your PR later this week. I am looking forward to the new instance feature you built. This is exactly what i need for my LED strip and my hue.

Now the two features just have to be merged  xD

**Comment by b1rdhous3** [comment]
Can be closed
