### ISSUE TITLE
Cross compilation help

### ISSUE THREAD

**Issue by DarkAnakin** [hyperion-project/hyperion.ng#586]
Hi
Can someone  explain me this error output

>AutoMoc subprocess error
>------------------------
>The moc process failed to compile
  "/tmp/hyperion.ng/include/blackborder/BlackBorderProcessor.h"
into
  "/tmp/hyperion.ng/build-rpi/libsrc/blackborder/blackborder_autogen/BPOSSKDTX4/moc_BlackBorderProcessor.cpp".

>Command
>-------
>/mnt/DevData/Cross-Compilation/Qt5.7.1/5.7/gcc_64/bin/moc -I/tmp/hyperion.ng/build-rpi/libsrc/blackborder/blackborder_autogen/include -I/tmp/hyperion.ng/build-rpi -I/tmp/hyperion.ng/dependencies/include -I/tmp/hyperion.ng/include -I/tmp/hyperion.ng/dependencies/external/flatbuffers/include -I/mnt/DevData/Cross-Compilation/raspberryPI/rootfs/usr/include/arm-linux-gnueabihf/qt5 -I/mnt/DevData/Cross-Compilation/raspberryPI/rootfs/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/mnt/DevData/Cross-Compilation/raspberryPI/rootfs/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/mnt/DevData/Cross-Compilation/raspberryPI/rootfs/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/mnt/DevData/Cross-Compilation/raspberryPI/rootfs/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/mnt/DevData/Cross-Compilation/raspberryPI/rootfs/usr/include/arm-linux-gnueabihf/qt5/QtGui -DPLATFORM_RPI -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SERIALPORT_LIB --include /tmp/hyperion.ng/build-rpi/libsrc/blackborder/blackborder_autogen/moc_predefs.h -o /tmp/hyperion.ng/build-rpi/libsrc/blackborder/blackborder_autogen/BPOSSKDTX4/moc_BlackBorderProcessor.cpp /tmp/hyperion.ng/include/blackborder/BlackBorderProcessor.h

>Output
>------
>Unknown option 'include'.

I can make the command execute without error with replacing _--include /tmp/_ by _-I/tmp/_  but I can't found what file inject the --include option.

Thanks

**Comment by b1rdhous3** [comment]
Please try the docker compilation for cross compile. This should be much easier.

**Comment by DarkAnakin** [comment]
Thanks.
I tried it but i got standard_init_linux.go:211: exec user process caused "exec format error". I am on ubuntu 19.04 x64.

**Comment by Paulchen-Panther** [comment]
What command did you use?

**Comment by DarkAnakin** [comment]
Thanks to make me like an idiot ;)
I have tried the native arm compilation command on x86 machine, of course it will not compile.

thanks again
