### ISSUE TITLE
QSQLITE driver broken on CoreELEC (ARM)

### ISSUE THREAD

**Issue by Portisch** [hyperion-project/hyperion.ng#603]
https://github.com/hyperion-project/hyperion.ng/commit/c62ea87ab7ad7afc08e6703eefac0e171a7f7ea6

This commit break the hyperiond on Amlogic CoreELEC:

```
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
[hyperiond DB] <ERROR> Driver not loaded Driver not loaded
[hyperiond MAIN] <ERROR> Hyperion Daemon aborted:
  Failed to open database connection!
```

What is missing on CoreELEC system?

**Comment by Paulchen-Panther** [comment]
The sqlite driver

**Comment by brindosch** [comment]
I think you need the sqlite plugin from qt. `libqt5sql5-sqlite`
It will be loaded on runtime from qt and is therefore not in the usual link list. We might need to add some code in case qt can't locate it.

**Comment by hissingshark** [comment]
Hi, just passing through whilst looking into another issue.

FYI - I encountered the same issue this morning but adding `libqt5sql5-sqlite` to my Vero4k installer dependencies fixed it.

**Comment by Portisch** [comment]
https://github.com/hyperion-project/hyperion.ng/pull/645
