### ISSUE TITLE
Setting some effects after each other gets Hyperion.NG stuck

### ISSUE THREAD

**Issue by ChaosCoder** [hyperion-project/hyperion.ng#604]
I use the web interface and the hyperion-remote cmdline tool. 

(1) After switching between different effects, the LEDs get stuck on some frame of the effect. 

Additionally (2), setting an effect (any) via web interface or hyperion-remote or setting an image via hyperion-remote and then setting a color with the same priority leaves the LEDs stuck on the effect or image without actually setting the LEDs to the new color.

## How to reproduce (1)

Using the web interface or the hyperion-remote cmd tool, set the effect "Atomic Swirl" and then "Candle" and do that repeatedly (no clear inbetween, all with the same priority), eventually, the LEDs will stop animating and are stuck. You can also verify this by using the LED Visualization tool of the Webinterface.

## How to reproduce (2)

Using the web interface or the hyperion-remote cmd tool:
Set an effect OR an image
Set a color
LEDs will still show the effect (one frame of it, not changing).

## Workaround

Workaround for getting the LEDs to change again: It always resolves if I clear the priority channel. Sometimes (1) resolves by setting a different effect (but will be stuck again when switching back to the one before).

**Comment by Paulchen-Panther** [comment]
Whitch LED Device you are using?

**Comment by ChaosCoder** [comment]
The debug file output.

**Comment by Paulchen-Panther** [comment]
Welches System?

p.s. lass dir doch nicht alles aus der Nase ziehen.

**Comment by ChaosCoder** [comment]
Ich selber benutze macOS 10.14.6 zum Testen. Hyperion.NG ist auf dem `9d84cdea0cec8a12b351b57c693eef10ac4030fe` Stand. Ein Bekannter hat ebenfalls diese Probleme auf einem nicht-macOS-System - welches System genau, weiß ich nicht, hat mir aber gereicht, um erstmal das exakte System als Fehlerquelle unwahrscheinlich zu machen. Wenn du mehr Informationen brauchst, sag Bescheid.

Zu deinem P.S.:
Ich versuche hier nur zu helfen. Ein solcher Spruch wie "Lass dir doch nicht alles aus der Nase ziehen." fördert nicht gerade, dass Leute darauf Lust haben... Wenn solche Informationen relevant sind, warum baust du nicht eine Erinnerung in das ISSUE Template ein? Oder weist in deinem ersten Kommentar nicht darauf hin, dass du mehr als nur wissen willst, welches LED Gerät ich benutze. Trotzdem entschuldige ich mich, nicht gleich alles mitgeschickt zu haben.

Zusätzlich weiß ich nicht, ob es dir wichtig ist, den Open-Issue-Zähler klein zu halten, aber #605 verhält sich als Problem sehr anders, als dieses Problem hier. Aber das ist ja deine Entscheidung.

**Comment by Paulchen-Panther** [comment]
> Ich selber benutze macOS 10.14.6 zum Testen. Hyperion.NG ist auf dem `9d84cdea0cec8a12b351b57c693eef10ac4030fe` Stand. Ein Bekannter hat ebenfalls diese Probleme auf einem nicht-macOS-System - welches System genau, weiß ich nicht, hat mir aber gereicht, um erstmal das exakte System als Fehlerquelle unwahrscheinlich zu machen. Wenn du mehr Informationen brauchst, sag Bescheid.

Danke für deine ausführliche Beschreibung.

> Wenn solche Informationen relevant sind, warum baust du nicht eine Erinnerung in das ISSUE Template ein?

Das sollte ich evtl. tun oder gleich den Issue Bereich schließen. Abgesehen davon, hast du gelesen was im Template steht. WE PROVIDE NO SUPPORT AT GITHUB!

Warum hast du dich im Forum nicht angemeldet und deine Probleme geschildert. Wenn du dich auf den Schlips getreten fühlst tut es mir leid.

> Zusätzlich weiß ich nicht, ob es dir wichtig ist, den Open-Issue-Zähler klein zu halten, aber #605 verhält sich als Problem sehr anders, als dieses Problem hier. Aber das ist ja deine Entscheidung.

Ich sehe da keine großen Unterschied als Dev. Deshalb habe ich ja auch geschrieben kombiniere den Fehler mit diesem hier. Und ja, man muss nicht bei jeder kleinigkeit einen neuen Issue eröffnen. Das macht die Sache nicht übersichtlicher.

**Comment by Paulchen-Panther** [comment]
Du hast geschrieben du benutzt den Debug output. Hast du dir die Dateiausgabe mal angeschaut oder reagiert das WebUI nur nicht.

**Comment by ChaosCoder** [comment]
> Das sollte ich evtl. tun oder gleich den Issue Bereich schließen.
Kann ich dann nur empfehlen 👍🏻

Ich als Dev sehe da Unterschiede, das eine (2) ist 100% reproduzierbar, das andere (1) tritt nur manchmal auf. Ich habe die beiden Issues jetzt hier kombiniert, keine Ahnung, warum du #605 jetzt wieder geöffnet hast, nachdem du nochmal darauf hingewiesen hast, dass ich die Fehler hier kombinieren soll. Aber du regelst das bestimmt.

Ich habe mir die Dateiausgabe angeschaut und es werden im Fall (1) nachdem der andere Effekt aktiviert wird, nur noch die gleichen Farbwerte gesetzt (immer und immer wieder). In der Ausgabe sieht man, dass Effekt "Atomic swirl" am Anfang läuft, dann setze ich mit `hyperion-remote -e "Candle" -p 1` (gleiche Priorität wie der vorherige Effekt) den neuen Effekt. Danach werden immer die gleichen Farbwerte wiederholt.

```
[{49,49,0}{10,10,0}{0,0,0}{0,0,0}{29,29,0}{108,108,0}{126,126,0}{113,113,0}{92,92,0}{29,29,0}{0,0,0}{0,0,0}{0,0,0}{6,6,0}{43,43,0}{104,104,0}{117,117,0}{32,32,0}{0,0,0}{0,0,0}{0,0,0}{0,0,0}{38,38,0}{106,106,0}{121,121,0}{75,75,0}]
[{44,44,0}{7,7,0}{0,0,0}{0,0,0}{34,34,0}{111,111,0}{126,126,0}{110,110,0}{89,89,0}{24,24,0}{0,0,0}{0,0,0}{0,0,0}{9,9,0}{49,49,0}{107,107,0}{115,115,0}{29,29,0}{0,0,0}{0,0,0}{0,0,0}{0,0,0}{42,42,0}{109,109,0}{120,120,0}{71,71,0}]
[{40,40,0}{5,5,0}{0,0,0}{0,0,0}{38,38,0}{114,114,0}{125,125,0}{107,107,0}{84,84,0}{20,20,0}{0,0,0}{0,0,0}{0,0,0}{12,12,0}{53,53,0}{111,111,0}{113,113,0}{25,25,0}{0,0,0}{0,0,0}{0,0,0}{0,0,0}{47,47,0}{112,112,0}{118,118,0}{66,66,0}]
[{35,35,0}{3,3,0}{0,0,0}{0,0,0}{43,43,0}{116,116,0}{125,125,0}{103,103,0}{80,80,0}{16,16,0}{0,0,0}{0,0,0}{1,1,0}{15,15,0}{58,58,0}{113,113,0}{111,111,0}{21,21,0}{0,0,0}{0,0,0}{0,0,0}{1,1,0}{51,51,0}{115,115,0}{116,116,0}{62,62,0}]
[]
[{32,32,0}{1,1,0}{0,0,0}{0,0,0}{47,47,0}{118,118,0}{124,124,0}{100,100,0}{75,75,0}{14,14,0}{0,0,0}{0,0,0}{3,3,0}{19,19,0}{62,62,0}{116,116,0}{108,108,0}{18,18,0}{0,0,0}{0,0,0}{0,0,0}{3,3,0}{56,56,0}{117,117,0}{113,113,0}{57,57,0}]
[]
// HIER HAB ICH DEN NEUEN EFFEKT "CANDLE" GESETZT XXXXXXXXX //
[]
[{32,32,0}{1,1,0}{0,0,0}{0,0,0}{47,47,0}{118,118,0}{124,124,0}{100,100,0}{75,75,0}{14,14,0}{0,0,0}{0,0,0}{3,3,0}{19,19,0}{62,62,0}{116,116,0}{108,108,0}{18,18,0}{0,0,0}{0,0,0}{0,0,0}{3,3,0}{56,56,0}{117,117,0}{113,113,0}{57,57,0}]
[{32,32,0}{1,1,0}{0,0,0}{0,0,0}{47,47,0}{118,118,0}{124,124,0}{100,100,0}{75,75,0}{14,14,0}{0,0,0}{0,0,0}{3,3,0}{19,19,0}{62,62,0}{116,116,0}{108,108,0}{18,18,0}{0,0,0}{0,0,0}{0,0,0}{3,3,0}{56,56,0}{117,117,0}{113,113,0}{57,57,0}]
[{32,32,0}{1,1,0}{0,0,0}{0,0,0}{47,47,0}{118,118,0}{124,124,0}{100,100,0}{75,75,0}{14,14,0}{0,0,0}{0,0,0}{3,3,0}{19,19,0}{62,62,0}{116,116,0}{108,108,0}{18,18,0}{0,0,0}{0,0,0}{0,0,0}{3,3,0}{56,56,0}{117,117,0}{113,113,0}{57,57,0}]
[]
[{32,32,0}{1,1,0}{0,0,0}{0,0,0}{47,47,0}{118,118,0}{124,124,0}{100,100,0}{75,75,0}{14,14,0}{0,0,0}{0,0,0}{3,3,0}{19,19,0}{62,62,0}{116,116,0}{108,108,0}{18,18,0}{0,0,0}{0,0,0}{0,0,0}{3,3,0}{56,56,0}{117,117,0}{113,113,0}{57,57,0}]
...
```

Das zeigt dann auch das Webinterface an (die LED Visualisation), das Webinterface geht sonst noch ganz normal.

Für das Problem (2) wird nachdem der Effekt gesetzt wurde und man die Farbe setzt nur noch einmal die gleichen RGB Werte gesetzt (laut File) und dann passiert nichts mehr in der Ausgabe.

**Comment by Paulchen-Panther** [comment]
Könntest du bitte den PR #607 testen? Danke
