### ISSUE TITLE
Setting color after setting effect or image does not work

### ISSUE THREAD

**Issue by ChaosCoder** [hyperion-project/hyperion.ng#605]
Setting an effect (any) via web interface or hyperion-remote or setting an image via hyperion-remote and then setting a color with the same priority leaves the LEDs stuck on the effect or image without actually setting the LEDs to the new color.

## How to reproduce

1. Set an effect OR an image
2. Set a color

LEDs will still show the effect (one frame of it, not changing).

## Resolve

Clearing the priority channel fixes the problem.

**Comment by Paulchen-Panther** [comment]
Whitch LED Device you are using?

**Comment by ChaosCoder** [comment]
The debug file output.

**Comment by Paulchen-Panther** [comment]
Please combine this with #604

**Comment by Paulchen-Panther** [comment]
Lass mich raten! Du benutzt den Debug output?

**Comment by ChaosCoder** [comment]
Warum raten, schrieb ich doch: https://github.com/hyperion-project/hyperion.ng/issues/605#issuecomment-522106646

Habe jetzt alles wie du gewünscht hast in #604 dokumentiert.
