### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by UniCizin** [hyperion-project/hyperion.ng#618]
Hello guys,

yesterday, i updated my running hyperio.ng to the newest version but unfortunately, it does not start anymore.
i get a lot of error messages like these

`root@Hyperion:/usr/local/share/hyperion/bin# hyperiond test.config.json
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].general.watchedVersionBranch: missing member
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].grabberV4L2: additional properties attribute is only valid for objects
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].grabberV4L2: properties attribute is only valid for objects
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].grabberV4L2: object expected
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].leds[0].hscan: no schema definition
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].leds[0].index: no schema definition
[hyperiond SettingsManager] <ERROR> Schema Syntax Error: [root].leds[0].vscan: no schema definition
`

(this was a test call, the json file does not exist, but the result is the same with no file as argument)

**Comment by b1rdhous3** [comment]
See this: https://github.com/hyperion-project/hyperion.ng/pull/614
you have to rebuild your Config. The config is now also stored in a db. Located at ~/.hyperion/db

**Comment by UniCizin** [comment]
ah yes.. thank you. everything works fine now.

Best would be if you guys make changes like this more visible. I was not able to follow the changes the last few weeks and was not aware of this.

**Comment by Paulchen-Panther** [comment]
You have to keep in mind that hyperion.ng is not yet officially released. Thus, everything is still in the development stage and therefore no information obligation to anyone.
