### ISSUE TITLE
Some issues/suggestions in hyperion.ng

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion.ng#619]
i found some issues/problems:

1. ~~webui detects my system language(german) but shows in the language settings english(default)~~
2. ~~if i change my LED controller type in "LED Hardware" it is active (i can see the leds changing) but if click on dashboard the old controller is listed, and when i click back to LED Hardware, the old controller is selected ( i think only an webUI problem?)~~
3. ~~if i change the RGB order for my leds (LPD8806 or ws281x) it does not changes the order...~~
4. as some users reported in the forum already...it is not possible to controll different instances with different json ports? ... i run a test system with lpd8806 on spi ports and ws281x on gpio 18... i wanted to controll both led-system at the same time...but not possible? or did i miss something?
5. is there an option to add the brightness of the leds to "LED Hardware" tab?
6. a save button next to the generate led configuration (at LED layout tab) i have first to create and then save the config...i never controll the generated output...so i can save it direct
7. ~~stopping activ instance crashes hyperion/webui?~~

**Comment by b1rdhous3** [comment]
Thanks!

I can quickly confirm point 2 and 3 since I encountered them in the last days. The values are saved, but you have to restart hyperion to get it working (this is new).
Also the same applys for changing the LED layout (e.g. amount of leds). @tpmodding could you confirm this?

**Comment by tpmodding** [comment]
nope...it saves mine...
master (brindosch-cb9cec3b/24495bbc-1566680010) Git Remote: https://github.com/hyperion-project/hyperion.ng.git
added 6. to first post

**Comment by brindosch** [comment]
Short notes

> webui detects my system language(german) but shows in the language settings english(default)

Browser and version? I noticed some weird behaviour with the internal lang detection (with chrome) of the lib we use. And there was no real update to this. I should probably replace that with own parsing code. Funny that it worked for years now.

> 2

Good catch, the ledDevice is selected based on the serverinfo.ledDevice.active, which "never" updates.
S: Remove active device prop and extract from config as everything else. With permission @Paulchen-Panther 

> 3

Found a possible issue/solution: https://github.com/hyperion-project/hyperion.ng/pull/621

> 4  it is not possible to controll different instances with different json ports?

Controlling different instances isn't a matter of ports, as all server ports (not boblight) are now shared across instances. We already had someone who noted that while using hyperion-remote [Quick fix PR #596](https://github.com/hyperion-project/hyperion.ng/pull/596). An internal "sharing" option is currently missing. I had an idea for it but never completed the code. 

> 5 brightness in ledconfig

As temporary adjustment or saved adjustment? Possible is both. How about the colors page? (Why duplicate it in ledconfig) 

> 6 a save button next to the generate led configuration

I think there were buttons if you use default "settings lvl view".

Thanks for your report(s)

**Comment by brindosch** [comment]
Test round requested :)
All issues should be resolved

**Comment by brindosch** [comment]
@b1rdhous3 @tpmodding 
 :)

**Comment by tpmodding** [comment]
Sorry habs nicht geschafft zeitlich, werds gegen testen :)

**Comment by tpmodding** [comment]
ich hab jetzt des öfteren "Speicherzugriffsfehler" die kamen nicht :(
log ab compile
https://pastebin.com/3DVQw5gU

2 ist fixed
3 ist fixed

neuer "bug" gefunden...

wenn man auf der zweiten instanz ist und stoppt diese dann auf dem dashboard dann schiess ichs ab...reagiert zwar anfangs, zeigt ober aber noch die zweite instanz an...aber kann nicht zur ersten wechseln oder irgendwas anderes...wenn ich dann mit strg+c in der konsole hyperion beende und neu starte bekomme ich einen fehler das die instanz deaktiv ist, oben steht immer noch "
Selected instance: Sub_ws2812b"....@b1rdhous3 kannst du das reproduzieren?

**Comment by brindosch** [comment]
Hast du das led Layout regeneriert? Das müsste dem log nach futsch sein.
Für den Speicherzugriff einmal gdb nutzen: Hier gehts zur Anleitung: https://docs.hyperion-project.org/en/user/support#segmentation_faults

> wenn man auf der zweiten instanz ist und stoppt diese dann auf dem dashboard dann schiess ichs ab
Inwiefern Abschuss? Crash? "Falsche UI"? Die WebUI sollte eigentlich bei einem "instance-update" automatisch wieder die serverinfo ziehen, wenn die aktuell ausgewählte Instanz stirbt. Ich weiß nicht, ob das aus meinem rework branch auch übernommen wurde. Muss mal schauen.

Anmerkung: Wir haben noch einige Speicherzugriffsfehler. Diese treten aber idr nicht nachvollziehbar immer auf. Dauert noch etwas, bis wir alles haben. Ggf mal Daten sammeln: https://github.com/hyperion-project/hyperion.ng/issues/609

**Comment by b1rdhous3** [comment]
> Inwiefern Abschuss? Crash? "Falsche UI"? Die WebUI sollte eigentlich bei einem "instance-update" automatisch wieder die serverinfo ziehen, wenn die aktuell ausgewählte Instanz stirbt. Ich weiß nicht, ob das aus meinem rework branch auch übernommen wurde. Muss mal schauen.

Das ist mein "Bock" und kommt hierher https://github.com/hyperion-project/hyperion.ng/pull/608. :)

Ich Speicher ja im Storage die aktuelle Instanz, damit diese nach F5 wieder da ist. Wenn wir nun eine Instanz beenden, wird die Instanz nicht aus dem Storage gelöscht und die UI versucht beim Neuladen weiterhin die Instanz aufzurufen. Bekommt dann eine Fehlermeldung zurück. Wechseln in die Hauptinstanz geht auch nicht mehr, da ja der Button ausgeblendet ist. 
@tpmodding 
![image](https://user-images.githubusercontent.com/5278602/64061869-5fb01980-cbe0-11e9-9155-d44c7ca9f7b4.png)
Lösche mal den ausgewählten Wert, dann sollte es wieder gehen. Ich kümmere mich um nen Fix.

**Comment by b1rdhous3** [comment]
@tpmodding testest du Punkt 7 noch einmal? :)

**Comment by tpmodding** [comment]
yes, genau so! klappt eins a

**Comment by b1rdhous3** [comment]
> zu 5. ok ich revidiere das mit dem LED Hardware-tab, ich meinte die helligkeit allgemein bezogen, soll heissen: ich hab jetzt 5 instanzen...und ich möchte ALLE einfach auf 20% helligkeit dimmen... momentan müsste ich in alle instanzen einzel rein und dort unter remote controll alle instanzen runter stellen...könnten wir irgendwie einen "allgemeinen" slider einfügen um alle instanzen gleichzeitig zu senken...

Das wäre vll allgemein n Punkt? Vielleicht möchte man an alle Instanzen die gleiche Farbe oder den gleichen Effekt oder so schicken. Evtl. sollten wir da über einen "global" Schalter nachdenken...

**Comment by brindosch** [comment]
Wie bereits erwähnt. Es fehlt ein internes verteilen der Befehle. Die Idee steht, der Code nicht.

**Comment by brindosch** [comment]
Hab den save button dauerhaft sichtbar gemacht. Weil das jetzt aber ggf zu Verwirrung führt, ist der "Generieren" button gestrichen. On-Update pushes zum ace-editor sollten auch kein Problem darstellen

EN: All "issues" resolved. Point 4/5 is a missing feature which is on my TODO list.

**Comment by brindosch** [comment]
@tpmodding 
Wie kannst du 5 Instanzen nutzen, ich hab momentan relativ starke memory leaks mit default config. Sind 2-10mb/s
Es reicht bereits eine zweite Instanz zu starten/stoppen. Je öfter ich das mache je schlimmer wird es.

Habt ihr kein Problem?
ping @Paulchen-Panther

**Comment by tpmodding** [comment]
ich hab ehrlich gesagt garnicht drauf geachtet wie die auslastung ist...

wie kann ichs gegen prüfen?

**Comment by brindosch** [comment]
Ein Tool um die Auslastung des Arbeitsspeichers zu sehen. hyperiond dreht dann völlig durch (1gb bis zum crash hatte ich schon) Wenn du keine Desktop hast, kannst du für Linux [top](https://wiki.ubuntuusers.de/top/) verwenden

**Comment by tpmodding** [comment]
<img width="814" alt="instanzen erstellt und gestartet" src="https://user-images.githubusercontent.com/17259976/65373490-86f98400-dc7e-11e9-9f86-83aee66218b1.png">
instanzen erstellt und gestartet

<img width="717" alt="Bildschirmfoto 2019-09-21 um 14 43 46" src="https://user-images.githubusercontent.com/17259976/65373477-67625b80-dc7e-11e9-91e2-90fde5df69b2.png">
eingestellt habe ich nur die led hardware mit den passenden layouts, und danach den police solid effekt gestartet....

**Comment by brindosch** [comment]
Läuft platform capture? Damit leakt es tierisch rum bei mir.

**Comment by tpmodding** [comment]
jaein...nur die shell...habs nicht im desktop modus...

ich könnte mir vorstellen, da die weiterleitung nicht aktiv ist..er mit jeder instanz jedes mal neu den desktop aufnimmt?

**Comment by brindosch** [comment]
Genau genommen müsste der platform capture und v4l immer laufen. Die Instanzen hängen sich in den stream rein und kopieren vom main thread die Daten in den hyperion thread. Also es gibt immer nur ein capture interfac das wirklich captured

**Comment by tpmodding** [comment]
ok dann wirds nicht daran liegen...trotzdessen ist ne cpu last von ca 80% ja auch nicht das wahre...

**Comment by brindosch** [comment]
@Paulchen-Panther 
TODO: platform capture und v4l müssen jeweils erkennen wieviele Hyperion instanzen dran hängen und wenn niemand da ist abschalten. Ist mir gerade wieder eingefallen... wollte ich auch noch machen. Es wird ja nie langweilig :)

**Comment by brindosch** [comment]
Kannst du mal in den instanzen platform capture aktivieren? Die müssten dann ja auf schwarz schalten (bzw in der ui). Würde mich interessieren, ob es da durchdreht, wenn du die instanz dann einfach mal startest/stopps

**Comment by tpmodding** [comment]
ne alles soweit in ordnung...last geht runter wenn alle aus sind, wieder hoch wenn alle an sind...also nix ausergewöhnliches

<img width="647" alt="Bildschirmfoto 2019-09-21 um 15 01 07" src="https://user-images.githubusercontent.com/17259976/65373664-aa253300-dc80-11e9-8649-8366c80e3396.png">

**Comment by Paulchen-Panther** [comment]
> @Paulchen-Panther
> TODO: platform capture und v4l müssen jeweils erkennen wieviele Hyperion instanzen dran hängen und wenn niemand da ist abschalten. Ist mir gerade wieder eingefallen... wollte ich auch noch machen. Es wird ja nie langweilig :)

Ich schaue mal nach wenn mein System aufgesetzt ist.

**Comment by brindosch** [comment]
Dann liegt es wahrscheinlich an meiner Desktop Hardware. Muss wegen Windows 7 jetzt sowieso upgraden.

- Ryzen 5 2600  120€
- 32GB RAM  130€
- Mainboard 60€

310€ -> Deal?
Mit 16GB RAM ist etwas knapp mit der Hyperion VM.

Vielleicht sollte ich das als Ansporn nehmen. Hyperion nach Windows "portieren", dann spar ich mir die VM und 65€.

:)

**Comment by tpmodding** [comment]
Ohje..lieber rpi4 :D

**Comment by brindosch** [comment]
So als surf desktop dürfte der Pi4 tatsächlich eine kleine brauchbare Lösung sein. Preis/Leistung ist natürlich besser. Aber darauf kann man vmtl kein Siedler daddeln. Für deine 5 Hyperion Instanzen sicher auch ganz cool :)
Mir hat der Pi3 als Mediacenter immer noch etwas zu wenig Power (Nutze trotzdem 2 davon als Mediacenter mit Emby als backend) und mit Netflix geht nicht einmal 720p. Bin gespannt was mit dem Pi4 so geht.

**Comment by Thunderbolt1** [comment]
Hi ich habe ein seit dem Umstieg vom alten auf das NG das problem, da alle Farben super dargestellt werden, aber bei dunklen Szenen die LED einfach alle leicht wabernd weiterleuchten statt auszugehen.
das Problem tritt bei PI3 & Pi4 auf ich finde keinen Menüpunkt im WEBIF bzw habe alle Punkte durchgetetstet.
Hat jemand von euch den entscheidenden Tipp für mich.
Hab den alten Logilink Grabber mit den 2801 LEDS von AliExpress
![81dL+LDDxsL _AC_SL1500_](https://user-images.githubusercontent.com/60275085/73104600-05995300-3ef7-11ea-92e6-5f8be6bf3848.jpg)
