### ISSUE TITLE
Some Image Processing fields missing

### ISSUE THREAD

**Issue by heathbar** [hyperion-project/hyperion.ng#622]
The following fields from the old HyperCon app are missing in the new web configuration.

![image](https://user-images.githubusercontent.com/598154/64140934-e1b06600-cdcb-11e9-94e0-70abbdb112dc.png)

**Comment by TechnoHoschi** [comment]
this would be great

"saturationGain" = HDR Workaround? ;)

**Comment by Lord-Grey** [comment]
Provided by #1477
Gap on Temperature is covered by #658, therefore closing this issue.
