### ISSUE TITLE
Leds blinking on Kodi playback paused (OSMC / Vero4K+)

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [hyperion-project/hyperion.ng#626]
Hi everybody,

when pausing video playback within Kodi the LEDs and HUEs keep toggleing on and off (about every 3-5 seconds).

There is nothing in the log (using -v verbose output). Is there any setting that might cause this?
Is anybody else seeing this?

best regards
Anthrax

**Comment by d3str0y3r** [comment]
I think, I have almost the same problem like you on my raspberry 3B with DietPi (6.26).
When adjusting the volume or pausing while video playback in kodi, the screen as well as the lights are going on and off. Classic hyperion, which I used before, works without any problems.


Logs:
Okt 19 19:12:31 RPi hyperiond[1607]: [hyperiond V4L2:/dev/video0] <INFO> Signal lost
Okt 19 19:12:31 RPi hyperiond[1607]: [hyperiond V4L2:/dev/video0] <INFO> Signal detected
Okt 19 19:12:36 RPi hyperiond[1607]: [hyperiond V4L2:/dev/video0] <INFO> Signal lost
Okt 19 19:12:38 RPi hyperiond[1607]: [hyperiond V4L2:/dev/video0] <INFO> Signal detected
Okt 19 19:12:44 RPi hyperiond[1607]: [hyperiond V4L2:/dev/video0] <INFO> Signal lost

**Comment by AnthraxLeprosyPi** [comment]
Might the grabber fail to read from stream/framebuffer because its not changing anymore or seams ended? And then retrys and fails again in a loop until the video is unpaused and therefore the stream is continued?

As you may gathered from my humble trying above - it's been a long long time since I coded myself ;-)

Anyways best regards,
Anthrax

PS: this thing is AWESOME an continues to improve... looking forward for the .ng final.

**Comment by tpmodding** [comment]
I will close this, if the problem occures, just reopen it.

**Comment by jangrewe** [comment]
@tpmodding I have the same issue with a new Vero 4K+ and the alpha.9 release (built from source).
I am using the AMLogic grabber.
When i pause playback in Kodi (and only then), my lights switch on an off in a ~10s interval (5s on, 5s off).
Under Remote Control -> Source Selection, i can see the "System: Platform Capture: (AmLogic)" source disappear and reappear (5s gone, 5s showing).
The slider under the "Component Control" stays enabled, same for the status on the dashboard.
