### ISSUE TITLE
Building Hyperion NG - differents results following HowTO

### ISSUE THREAD

**Issue by URBANsUNITED** [hyperion-project/hyperion.ng#627]
Hi!

It looks like that the building HowTO follows different sources.
[https://github.com/hyperion-project/hyperion.ng/blob/master/CompileHowto.md](url)

I am using an external USB Grabber 1b71:3002 Fushicai USBTV007 Video Grabber [EasyCAP]
and that delievered while first testing a coloured live stream.
I tried the docker building method and got a b/w live stream.
Command:
wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -t armv7hf

After searching I found this thread
[https://hyperion-project.org/threads/hyperion-ng-auf-raspberry-4-raspbian-buster-usb-grabber.3689/](url)
And this fix
[https://github.com/hyperion-project/hyperion.ng/pull/606](url)

I rebuild a new version by this command:
wget -qO- https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/bin/compile.sh | sh

And got a coloured live stream again.

So, I believe the Compiling manual follows different sources as the fix for the b/w ext. grabber is merged in the latest sources.

Possible?

Thanks

URBANsUNITED

**Comment by Paulchen-Panther** [comment]
On which operating system did you run the finished binaries from the docker? Which hardware did you use?

**Comment by URBANsUNITED** [comment]
Hi!

My Docker System is Debian 9.11 on AMD Opteron 3280 CPU
The compilation on the rpi was on Buster 10.1

**Comment by tpmodding** [comment]
https://github.com/hyperion-project/hyperion.ng/releases
