### ISSUE TITLE
RPi4: Missing support for 2 displays

### ISSUE THREAD

**Issue by nicedevil007** [hyperion-project/hyperion.ng#628]
Hey guys,

I installed hyperion.ng on my Raspberry Pi successfully now.
The only thing not working is the grabber :/

I get this error on starting Hyperiond:

`[hyperiond DISPMANXGRABBER] <ERROR> Failed to open display! Probably no permissions to access the capture interface`

EDIT brindosch: changed title
- Rpi4 support for 2 displays is missing (selection)

**Comment by Paulchen-Panther** [comment]
Which RPi?
Which OS?
Which way did you install or compile hyperion.ng?

Have you ever tried the following:
https://github.com/hyperion-project/hyperion.ng/issues/584#issuecomment-512787426

Greetings, Paulchen

**Comment by nicedevil007** [comment]
I was using hypriotOS and did test that what your link told me.

I was able to get the LEDs on with the error now but only white and black :/

After 3 days of testing around I switched back to the old hyperion that is working as intended.
Will give hyperion.ng a next try after newer release :)

**Comment by Paulchen-Panther** [comment]
Switch to the Framebuffer grabber and it is working.
Proof:
![webUI](https://user-images.githubusercontent.com/16664240/65822749-931aae00-e249-11e9-8b7c-f29159c4dfd5.png)
![console](https://user-images.githubusercontent.com/16664240/65822750-9746cb80-e249-11e9-9718-19ec12319df8.png)

**Comment by brindosch** [comment]
Do we have a false positive detection here? The assert should trigger? Second: It's not possble that hyperion works and hyperion.ng not.
@Paulchen-Panther 

hyperion
```
	bcm_host_init();

	{
		// Check if the display can be opened and display the current resolution
		// Open the connection to the display
		_vc_display = vc_dispmanx_display_open(0);
		assert(_vc_display > 0);
```

hyperion.ng
```
	bcm_host_init();
	_vc_display = vc_dispmanx_display_open(0);
	assert(_vc_display > 0);

	DISPMANX_MODEINFO_T vc_info;
	int result = vc_dispmanx_display_get_info(_vc_display, &vc_info);

	vc_dispmanx_display_close(_vc_display);

	if(result != 0)
	{
		Error(_log, "Failed to open display! Probably no permissions to access the capture interface");
```

**Comment by brindosch** [comment]
@nicedevil007 
Are we talking about a Raspberry Pi 4? A second display would explain that

**Comment by nicedevil007** [comment]
@brindosch 
yep that was/is raspbbery pi 4 with one HDMI cable connected my AVR.

I got it to work with the error message showing up. Just forgot that dtparm SPI thing...
Hyperion.ng is working then but only with colour white/black (like this 
https://github.com/hyperion-project/hyperion.ng/issues/600).

I figured out to get it to work correctly when I first install hyperion (the old one with hypercron), than install a suitable config file and than install hyperion.ng.

The error message stays the same but it will work with color.

**Comment by Paulchen-Panther** [comment]
> I got it to work with the error message showing up. Just forgot that dtparm SPI thing...
> Hyperion.ng is working then but only with colour white/black (like this
> #600).

Du hast dein Problem schon im Forum gepostet. Gibst uns aber keine weiteren Details darüber, welchen weg du benutzt hast hyperion.ng zu installieren. Mein Vorletzter Post beinhaltete mehrere Fragen (zu sehen an den Fragezeichen) die du bis jetzt nicht beantwortet hast.
Erwartest du wirklich das ich dir alles aus der Nase ziehe?
Von meiner Seite her ist dieser Issue für mich geschlossen.

**Comment by nicedevil007** [comment]
Sry das ich jetzt gerade net auf deine "Frage" eingehe von weiter oben. Hatte vorhin nur gesehen, dass irgendwer in dem Fall "brindosch" auf mein bereits von mir geclosetes Issue gepostet hatte und ich ihm Feedback gegeben habe.

Versteh mich net falsch, ich bin auch eher "Tüftler" und probiere lieber zu lange an etwas bevor ichs aufgebe... 

Würde dir ja auch ganz gern nen Feedback zu deinen "Fragen/Frage" von oben geben nur versteh ichs gerade net so ganz was ich damit anfangen soll... bin halt eigentlich the "only USB grabber User". Was der Framebuffer intern macht ist mir grundsätzlich wurscht, das HDMI is nur zum debuggen angeschlossen falls ich doch net Headless weiterkomme?

**Comment by Paulchen-Panther** [comment]
Wenn du nur der

> "only USB grabber User"

bist, warum erstellst du dann ein Issue zum internen grabber?

**Comment by nicedevil007** [comment]
Weil da [hyperiond DISPMANXGRABBER] steht und ich beim GRABBER davon ausging, dass der USB Grabber damit gemeint ist? Sry das ich auch nur, wie so viele andere einfach nen Guide befolgen und das tolle Programm net in und auswendig kennen. 

Da es hier nur noch um Fehler/Schuldzuweisung geht, close ich das jetzt und werd net weiter mehr drauf eingehen. Sehr schade, dacht immer man kann konstruktiv den Entwicklern auf Github helfen und wird net gleich rund gemacht nur weil man anscheinend nen LOG falsch interpretiert.

**Comment by brindosch** [comment]
@Paulchen-Panther 
Ist durchaus etwas ruppig unterwegs. Grundsätzlich macht ja der Ton die Musik.

Ferner könnte man ein verbessertes issue template einsetzen (Wobei klar werden muss, dass "Leds black" kein Fall für die Issues ist)
Das Problem ist legitim und rührt daher, dass von "uns" noch keiner den RPi 4 besitzt und das mit den 2 HDMI Anschlüssen durchgespielt hat. Was da sonst noch an Problemen kommt ist ebenfalls offen.

**Comment by Lord-Grey** [comment]
@nicedevil007 Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment]
Closing, as no feedback provided. Can be reopened, if needed.
