### ISSUE TITLE
Python error while compiling

### ISSUE THREAD

**Issue by fishredleung** [hyperion-project/hyperion.ng#632]
Hi guys, 
when I was compiling using my rpi4 buster, the following error occurred:

./Python/dynload_shlib.c:83: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:127: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:102: error: undefined reference to 'dlerror'
./Modules/posixmodule.c:5924: error: undefined reference to 'openpty'
./Modules/posixmodule.c:6018: error: undefined reference to 'forkpty'
collect2: error: ld returned 1 exit status
make[2]: *** [src/hyperion-framebuffer/CMakeFiles/hyperion-framebuffer.dir/build.make:156: bin/hyperion-framebuffer] Error 1
make[1]: *** [CMakeFiles/Makefile2:3385: src/hyperion-framebuffer/CMakeFiles/hyperion-framebuffer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object src/hyperion-remote/CMakeFiles/hyperion-remote.dir/hyperion-remote_autogen/mocs_compilation.cpp.o
[ 98%] Building CXX object src/hyperion-v4l2/CMakeFiles/hyperion-v4l2.dir/hyperion-v4l2_autogen/mocs_compilation.cpp.o
./Python/dynload_shlib.c:83: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:127: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:102: error: undefined reference to 'dlerror'
./Modules/posixmodule.c:5924: error: undefined reference to 'openpty'
./Modules/posixmodule.c:6018: error: undefined reference to 'forkpty'
collect2: error: ld returned 1 exit status
make[2]: *** [src/hyperion-dispmanx/CMakeFiles/hyperion-dispmanx.dir/build.make:157: bin/hyperion-dispmanx] Error 1
make[1]: *** [CMakeFiles/Makefile2:3287: src/hyperion-dispmanx/CMakeFiles/hyperion-dispmanx.dir/all] Error 2
[ 98%] Linking CXX executable ../../bin/hyperion-remote
./Python/dynload_shlib.c:83: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:127: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:102: error: undefined reference to 'dlerror'
./Modules/posixmodule.c:5924: error: undefined reference to 'openpty'
./Modules/posixmodule.c:6018: error: undefined reference to 'forkpty'
collect2: error: ld returned 1 exit status
make[2]: *** [src/hyperion-remote/CMakeFiles/hyperion-remote.dir/build.make:153: bin/hyperion-remote] Error 1
make[1]: *** [CMakeFiles/Makefile2:3093: src/hyperion-remote/CMakeFiles/hyperion-remote.dir/all] Error 2
[ 98%] Linking CXX executable ../../bin/hyperion-v4l2
./Python/dynload_shlib.c:83: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:127: error: undefined reference to 'dlsym'
./Python/dynload_shlib.c:96: error: undefined reference to 'dlopen'
./Python/dynload_shlib.c:102: error: undefined reference to 'dlerror'
./Modules/posixmodule.c:5924: error: undefined reference to 'openpty'
./Modules/posixmodule.c:6018: error: undefined reference to 'forkpty'
collect2: error: ld returned 1 exit status
make[2]: *** [src/hyperion-v4l2/CMakeFiles/hyperion-v4l2.dir/build.make:155: bin/hyperion-v4l2] Error 1
make[1]: *** [CMakeFiles/Makefile2:3189: src/hyperion-v4l2/CMakeFiles/hyperion-v4l2.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

how can I solve it ?

**Comment by Paulchen-Panther** [comment]
Which OS on Buster basis do you use?

**Comment by fishredleung** [comment]
Sorry I’m a completely noob, just tried it again and didn’t work.
I have been successfully complied it with  docker, but how can I start the Hyperion server after that?

**Comment by brindosch** [comment]
You can follow the [Release page](https://github.com/hyperion-project/hyperion.ng/releases) for latest updates now.
