### ISSUE TITLE
Travis build with SPI ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#65]
Can we get travis to build with SPI ?

I just tested both ubuntu and centos x86 systems with:
cmake -DPLATFORM=x86 -DENABLE_SPIDEV=ON -DCMAKE_BUILD_TYPE=Release ..

and they build fine

**Comment by brindosch** [comment]
I updated my fork with a new travis ci instructions following their doc.
@redPanther 
The TEST fails if i saw that right.
https://travis-ci.org/brindosch/hyperion.ngBeta/jobs/140806832

OSX:
I need help for OSX builds to check current necessary deps to install @tpmodding 
Is the cmake command right?

**Comment by penfold42** [comment]
looks like an issue with the "test" stuff we have.
I get a failed build with cmake -DENABLE_TESTS=ON too but for different reasons that ill fix

**Comment by brindosch** [comment]
weird, can´t test further. travis.ci has some problems currently.
