### ISSUE TITLE
Forwarding via flat-buffers not working.

### ISSUE THREAD

**Issue by hissingshark** [hyperion-project/hyperion.ng#652]
I have NG built from a recent commit #4c0c102 (10/11/2019) on a Vero4K (OSMC) and an RPi3 (RaspbianLite)

Platform capture works on both devices and can be seen in the webGUI live preview.

On the Vero4K I have "forwarder" activated, with the "JSON target" and "flatbuffer target" set to the IP address of the RPi3 and the default ports.
Debug output is:
[hyperiond JSONSERVER] <INFO> Started on port 19444
[hyperiond FLATBUFCONNECTION] <INFO> Connecting to Hyperion: 192.168.1.250:19401
[hyperiond NETFORWARDER] <INFO> Forward now to json targets '192.168.1.250:19446'
[hyperiond NETFORWARDER] <INFO> Forward now to flatbuffer targets '192.168.1.250:19401'​

On the RPi3 I have "Flatbuffers Server" and "Protocol Buffers Server" activated, set to the same ports as above.
Debug output is:
[hyperiond JSONSERVER] <INFO> Started on port 19444
[hyperiond FLATBUFSERVER] <INFO> Started on port 19401
[hyperiond PROTOSERVER] <INFO> Started on port 19446​

So how should I see the Vero4K forwarded onto the RPi3?
I assumed there would be an option in the RPI3 "remote control" to select the Vero4K as a source, but I only have the usual:
System Platform Capture: (Dispmanx)
System Effect: Warm mood blobs​

It is unclear if this is a bug or operator error.
Is there something else I should be doing?

Many Thanks,

**Comment by gismo2004** [comment]
@hissingshark your ports for json and proto are somehow wrong... (json target should be 19444 for you) 

Anyway, I have the same problem. The only way to make the flatbuffer forwarder work, is to change the port on sender side to something "wrong" and save settings. Then back to correct port and save. This enables the forwarding and also lights up the leds.
Disable (save) enable (save) the forwarding switches it off and requires the above steps to enable it again. 

Both instances are running latest (today) source

Could this be a config issue?

**Comment by hissingshark** [comment]
@gismo2004 thanks for your feedback.
I've tried setting Flatbuffer Target 1 to 192.168.1.250:19400 but no change.
Unfortunately I've not been able to reproduce your fix of wrong/right settings.  Or at least I think so.

When you have it working do you see something under Source Selection in the Remote Control, so that you can select the forwarded data?

**Comment by gismo2004** [comment]
@hissingshark sorry for late response... you know: Christmastime == Busytime :-)

however: yes i see something in SourceSelection of the "server instance". I hope i'll have some time to check this in the next two weeks.

The json forwarder is working as far as i have seen. Is this working for you? (try to load an effect on client and start it...)

**Comment by gismo2004** [comment]
@hissingshark one thing i have found out: for making it work for me, I need to switch to a "wrong" port for at least 5s, after that switching back to the correct one, enables the forwarding for me...

**Comment by gismo2004** [comment]
@hissingshark i have at least something that works now... I'm sure that my "workaround" is not what @Paulchen-Panther want will use, but for me it is working :-D

I also don't understand how componentStateChanged() should get triggered as its source is never COMP_FORWARDER but i have absolutely no clue how all this stuff "should" work *g* so i hope paulchen will help to fix it.
check my patch and apply it. 
[test.zip](https://github.com/hyperion-project/hyperion.ng/files/4027181/test.zip)

**Comment by hissingshark** [comment]
I'll take a look at that, thank you.
Still not clear about the settings I need, but if I start from scratch this patch should at least rule out that quirky part.

**Comment by hissingshark** [comment]
@gismo2004 
I added your patch, cleared out both configs and started again.
I had it working very briefly, but then it stopped again.  Likely my fiddling with the config to narrow down exactly what was required - but there's proof it CAN work on this combination of platforms.
Thank you.

**Comment by hissingshark** [comment]
This still isn't working for me.  I've rebuilt from master on both devices.
@gismo2004 can you confirm this has fixed it for you?  And if so could you share your settings for each device so I can see how they align?  I'm finding the labelling of the settings somewhat confusing to be honest.

**Comment by gismo2004** [comment]
@hissingshark i still need my patch (first part) to be able to switch the forwarder off and on via kodi addon! (i don't want to have the lights on when in menu...)

That's my setup:

![client](https://user-images.githubusercontent.com/2325636/76147939-b15ec280-60a1-11ea-8dc3-7fb8d4ac5a2a.png)
![server](https://user-images.githubusercontent.com/2325636/76147944-b4f24980-60a1-11ea-95a2-f355b389660e.png)
