### ISSUE TITLE
Building on Odroid N2 falis with BCM_LIBRARIES, BCM_INCLUDE_DIR failed.

### ISSUE THREAD

**Issue by SzymonZy** [hyperion-project/hyperion.ng#653]
Hello

I'm following compile faq on Odroid N2 running RetroArena. Configure complains about missing Broadcom libraries (BCM_INCLUDE_DIR, BCM_LIBRARIES). 
(cmake -DENABLE_AMLOGIC=ON -DCMAKE_BUILD_TYPE=Release ..)
What is the proper switch to use AML grabber during compilation and disable Broadcom?

**Comment by jMasterkingswag** [comment]
Hi, just set "-DPLATFORM=amlogic64" instead of "-DENABLE_AMLOGIC=ON" the CMakeLists.txt tries to automatically look up the platform you're compiling on. If you're f.e. crosscompiling on some other device running arm, the script just assumes you are on a raspbi

**Comment by tpmodding** [comment]
thanks @jMasterkingswag 
will close this
if this didnt help, please reopen it
