### ISSUE TITLE
Turning on and off all the time

### ISSUE THREAD

**Issue by trendol** [hyperion-project/hyperion.ng#655]
Hi there!

I got a weird behaviour with my Hyperion-setup. It is a Lightberry-setup with v4l2 grabber. And for the last 2 months, it works perfectly with standalone effects (Rainbow swirls etc) but as soon as I'm turning on a movie with the grabber activate, it goes something like this: for the first 20-30 seconds, it works perfectly. Then the top and the bottom LEDs of the TV just goes blank. The side LEDs of the TV works for additional 5-6 seconds and then also goes blank. After 5-6 seconds again, it all turns on again and works for 20-30 seconds again .. and it just does that over and over.

I'm not sure really where to start debugging. Is it a power supply error, since the "local" effects seems to work perfectly? I did a screenshot from the grabber, and it seems to work aswell, except for these red lines everywhere. Is that normal? (see attached)

![screenshot](https://user-images.githubusercontent.com/3259430/70852559-07590b00-1ea3-11ea-9b62-eae766998614.png)

Anyone care helping a beginner of this? :( Can I debug this somehow?

**Comment by Toxminn** [comment]
i have the errors myself :(
did you find out anything?

**Comment by trendol** [comment]
> i have the errors myself :(
> did you find out anything?

Yeah so, I did change the black detection value to 0.5. After that everything seems pretty much better. It's still going on and off, but not as often, more after a couple of minutes or so. Very weird, but yeah that's what I did.

**Comment by tpmodding** [comment]
issues with usb grabbers are known, we are working on them
