### ISSUE TITLE
Proto forward to from hyperion.ng to hyperion (old gen) does not work

### ISSUE THREAD

**Issue by DrBlokmeister** [hyperion-project/hyperion.ng#657]
I made this issue after recommendation by @RickDB with a request to also tag @Paulchen-Panther .

Since I updated my Odroid C2 with CoreELEC to the latest version [CoreELEC 9.2.1](https://github.com/CoreELEC/CoreELEC/releases/tag/9.2.1) my protobuffer forward does not work anymore. Right now my setup is as follows:

- Odroid C2 runs Hyperion.ng on CoreELEC and plays the media (main instance)
- RPI2 runs LibreELEC and Hyperion (old gen) and is connected to ambilight LED strips (secondary instance)
- Odroid C2 forwards color details via protobuffer to RPI2

Since updating to latest version of CoreELEC, my hyperion setup does not work anymore. Before that, everything worked great on [CoreELEC 9.2.1](https://github.com/CoreELEC/CoreELEC/releases/tag/9.0.3). After update the logfile is flooded with these messages:

```
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply
[hyperiond FLATBUFCONNECTION] (ERROR) Unable to parse reply`
```

On the second instance, my log contains these errors:
```
JSONSERVER INFO: New connection
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
JSONSERVER INFO: Connection closed
[libprotobuf ERROR /home/sascha/hyperion/dependencies/external/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "proto.HyperionRequest" because it is missing required fields: command
```

The old version where everything worked is indicated as version 101 in the changelog:
```
101
- Add Platform script
100
- Initial Release @e438bc6
```
With this in the makefile:
```
PKG_NAME="hyperion.ng"
PKG_VERSION="74766fd62631a35d90872278b3bf9d88d4dfffdd"
PKG_SHA256="257d05290dc1bd86bc3f1b84e252af66a6a3876eda77fe3864a96f0ab87f1b9b"
PKG_REV="101"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/hyperion-project/hyperion.ng"
PKG_URL="https://github.com/hyperion-project/hyperion.ng/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain Python3 avahi libusb qt-everywhere protobuf flatbuffers:target"
PKG_SECTION="service"
PKG_SHORTDESC="Hyperion.NG: an AmbiLight controller"
PKG_LONGDESC="Hyperion.NG($PKG_VERSION) is an modern opensource AmbiLight implementation."
```

The new CoreELEC version 9.2.1 has the same changelog and makefile, but somehow this version doesn't work. Note that in 9.0.3 I used the hyperion.ng version included in the release without updating, and with 9.2.1 it didn't work before, or after updating to the latest version. The hyperion build that has the bug is version 2.0.0 with build date Nov 27th 2019 at 10:11:58.

I think the issue is with the dropped protobuffer support, which has not been brought back to the latest release included in CoreELEC.

**Comment by tpmodding** [comment]
Will close this, hyperion classic is discontinued...
