### ISSUE TITLE
Transform "Color Temperature" missing

### ISSUE THREAD

**Issue by FreshGer** [hyperion-project/hyperion.ng#658]
Hello,

First: i am loving this project.

One Thing i would like to mention anyway: In the former hyperion we were able to change the overall **color temperature**. This is needed to match the colors of the Stripe (standard is blue-ish) with that of the TV. Matching the "Whitelevel" only helps with real white, not with gray or others.  

Back then it was done like this: 
`std::vector<ColorRgb> ledColors = _raw2ledTemperature->applyCorrection(adjustedColors);`

`static MultiColorCorrection * createLedColorsTemperature(const unsigned ledCnt, const Json::Value & colorTemperatureConfig);`

From what i understand it would need to be placed in the **void MultiColorAdjustment::applyAdjustment(std::vector<ColorRgb>& ledColors)**? :)

Regards,
FreshGer

**Comment by d4kine** [comment]
Hm I'm really looking forward for this, because the colors are horrible with the WS2801 stripe.
