### ISSUE TITLE
How can I update Hyperion.ng

### ISSUE THREAD

**Issue by marrobHD** [hyperion-project/hyperion.ng#659]
How can I update Hyperion.ng to the newest version?

**Comment by Joeboyc2** [comment]
At the moment you need to rerun the original compile steps to recompile the
latest source code.

The guys are working on making the installer packages but I dont think they
are ready just yet

**Comment by Paulchen-Panther** [comment]
Which operating system and which hardware do you use?

**Comment by marrobHD** [comment]
Debian Buster and a Raspberry 3B+

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/blob/master/CompileHowto.md#native-compiling-on-raspberry-pi

**Comment by marrobHD** [comment]
I hadnt installed this way. I used this script. https://gist.github.com/marrobHD/176dbcade1927db26121d65a66fa0aef#file-compile-sh

**Comment by Paulchen-Panther** [comment]
I would just say run your script again!?!

**Comment by marrobHD** [comment]
Yes but that wont work: https://pastebin.com/9LJqJEpT It cancels at some time because many issues

**Comment by Paulchen-Panther** [comment]
It's best to try reducing the number of build threads
https://gist.github.com/marrobHD/176dbcade1927db26121d65a66fa0aef#file-compile-sh-L83

**Comment by marrobHD** [comment]
Oupps fixed it. Maybe the last time when I tested the script i runned it with the root user. I had to add sudo to some commands in the code. Thank you. Im a dummy xD
