### ISSUE TITLE
Wrong/low resolution with stk1160 grabber

### ISSUE THREAD

**Issue by greso** [hyperion-project/hyperion.ng#661]
Using a stk1160 grabber on a raspberry pi 3 with raspbian the grabber is set to a wrong (very low) resolution resulting in a washed out image (the resolution set is 36x32). 

After some trial and error I figured that the correct resolution is overwritten by the following code block:
https://github.com/hyperion-project/hyperion.ng/blob/fe728b15434d9f960eca899efb1dfebd7b9c319d/libsrc/grabber/v4l2/V4L2Grabber.cpp#L625-L629

Deleting this block the results in a correct resultion of720x480.

The issue is also described by others in this forum thread:
https://hyperion-project.org/threads/ng-hyperion-v4l2-capture-resolution-issue.3684/page-2

If you need more information or have any additional questions please let me know.

Thank you for this wonderful software!

**Comment by andrewpros** [comment]
For now u can set hard coded width and height values specific to that grabber in config grabberV4L2 section.

**Comment by greso** [comment]
It seems like this doesn't work. Width and height is also not documented in the commented config file: https://github.com/hyperion-project/hyperion.ng/blob/fe728b15434d9f960eca899efb1dfebd7b9c319d/config/hyperion.config.json.commented#L102

Even if this does work I think this should be more obvious that this needs to be done (at least something about it should be printed in the log).

**Comment by andrewpros** [comment]
Did u check it or not? The code shows it is reading this value if it is set and not 0, so u can set the value up front if there are some issues.
The snippet of the code you linked shows that it is only executed if the detected values are 0, so, maybe that stk1160 grabber is reporting wrong values or 0 and that could be why its is not working they way it should.

Not sure why the width/height is missing now, maybe i had some old code, sorry cant help more.

**Comment by tpmodding** [comment]
should be fixed with #766
