### ISSUE TITLE
V4L2Grabber: problem with device video input selection

### ISSUE THREAD

**Issue by Thinner77** [hyperion-project/hyperion.ng#662]
Hi,

i've noticed a problem using my USB-grabber (Bus 001 Device 005: ID 1b71:3002 Fushicai USBTV007 Video Grabber [EasyCAP]) connected to Raspberry Pi3B. If there is no other capture device connected grabber is created at /dev/video0 and all is working fine. But if i connect a Raspberry Pi camera grabber is created at /dev/video1 (cam at /dev/video0) and i only get a black picture using ./hyperion-v4l2 -d /dev/video1 -v PAL -s 1 --screenshot

After some debugging i'm sure there is something wrong in V4L2Grabber.cpp, function V4L2Grabber::setDeviceVideoStandard setting the video input for the device.

Currently video input is derived from last char of devicename, resulting in 0 for /dev/video0 and 1 for /dev/video1:

QChar input = device.at(device.size() - 1);
_input = input.isNumber() ? input.digitValue() : -1;

But devices may have multiple video inputs, my grabber has one for composite video (used by me) and one for s-video input:

v4l2-ctl -d /dev/video1 --list-inputs
ioctl: VIDIOC_ENUMINPUT
	Input       : 0
	Name        : Composite
	Type        : 0x00000002 (Camera)
	Audioset    : 0x00000000
	Tuner       : 0x00000000
	Standard    : 0x0000000000FFF9FF (PAL-B/B1/G/H/I/D/D1/K/M/60 NTSC-M/M-JP/443/M-KR SECAM-B/D/G/H/K/K1/L/Lc)
	Status      : 0x00000000 (ok)
	Capabilities: 0x00000004 (SDTV standards)
	Input       : 1
	Name        : S-Video
	Type        : 0x00000002 (Camera)
	Audioset    : 0x00000000
	Tuner       : 0x00000000
	Standard    : 0x0000000000FFF9FF (PAL-B/B1/G/H/I/D/D1/K/M/60 NTSC-M/M-JP/443/M-KR SECAM-B/D/G/H/K/K1/L/Lc)
	Status      : 0x00000000 (ok)
	Capabilities: 0x00000004 (SDTV standards)`

So, if grabber is created at /dev/video1, input 1 is selected (s-video), but i would like to use input 0 (composite).

I can fix that for my installation setting _input to 0, but maybe there is a chance to get a config option for selecting devices video input?

Thanks for your time and your great work.

wbr

**Comment by tpmodding** [comment]
should be fixed with #766
