### ISSUE TITLE
Missing python 3.5 libraries

### ISSUE THREAD

**Issue by jonwilliams84** [hyperion-project/hyperion.ng#664]
Follow a build, I try to run hyperion and get

./hyperion-x11: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

Have tried installing libpython3.6-dev but still no dice.

Any ideas?

**Comment by Paulchen-Panther** [comment]
We are missing few details.
Which OS?
How did you compile?
How did you install or start it?

**Comment by jonwilliams84** [comment]
Sorry...
OS = Ubuntu 18.04
Compiled using the docker-compile.sh for X64 
started using ./hyperion-x11 or ./hyperiond from deploy directory

**Comment by Paulchen-Panther** [comment]
There seems to be room for improvement on the X64_86 platform (docker native compile).
The best way to compile it under platform x64_86 is [the usual way](https://github.com/hyperion-project/hyperion.ng/blob/master/CompileHowto.md#the-usual-way).

**Comment by jonwilliams84** [comment]
Cheers, have sorted by compiling manually within a Dockerfile and can now start hyperiond within a container

**Comment by Paulchen-Panther** [comment]
If you want to support us, you can share your Docker container for Hyperion with us. At https://github.com/hyperion-project/hyperion.docker-ci
:wink:

**Comment by jonwilliams84** [comment]
You can grab my image from Dockerhub: sirfragalot/hyperion.ng:0.1.0

It can be run it with:
`docker run -d -v ./hyperion.config.json:/etc/hyperion:ro --name="Hyperion" --network host sirfragalot/hyperion.ng:0.1.0`
(obviously change the path of the config to suit)

...give it a whirl - I am unable to test at the moment because I am away from my LEDs!!!

**Comment by Paulchen-Panther** [comment]
I'll test it tomorrow. Thank you for your effort, time and work.

**Comment by jonwilliams84** [comment]
no worries...been a long time fan of hyperion, but just redone my LEDs; built on an ESP8266 running WLED and wanted to test the udpraw with Android Grabber from the TV.  Will test out tonight hopefully.

**Comment by jonwilliams84** [comment]
Just got home and tested my image - working fine...however, the bind mount for the config appears to be wrong.  What's the default path for config in hyperion-ng?

**Comment by Paulchen-Panther** [comment]
There is no more config. You can specify a path. Everything is stored in a database.
Example: hyperiond --userdata /path/to/
If the database does not exist in the path, it will be created

**Comment by Paulchen-Panther** [comment]
Configured via WebUI http://localhost:8090

**Comment by jonwilliams84** [comment]
Ah...does it write its config to a file anywhere - like the old hyperion? e.g. /etc/hyperion/hyperion.config.json?  That way I could bind the file as a volume / config with the container.

If I config via the WebUI - on save the container restarts and resets...here is the debug log:

`[hyperiond QTGRABBER] <ERROR> Previous line repeats 1 times
[hyperiond EFFECTENGINE] <INFO> run effect Rainbow swirl fast on channel 0
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:153:registerInput()> Register new input 'System/EFFECT' with priority 0 as inactive
[hyperiond EFFECTENGINE] <INFO> run effect Warm mood blobs on channel 254
[hyperiond WEBSOCKET] <DEBUG> <JsonAPI.cpp:1123:handleLoggingCommand()> log streaming deactivated for client  ::ffff:10.255.0.2`

**Comment by jonwilliams84** [comment]
Ok...sorry didn't read your comment regarding --userdata.

Image now fixed and re-upped to the hub. Working like a charm now!

Launch with:
`docker run -d -v /path/on/host:/etc/hyperion --name="Hyperion" --network host sirfragalot/hyperion.ng:0.1.0`

This will save the to the path in the volume bind mount, so ensure you have the correct perms, etc.

**Comment by jonwilliams84** [comment]
link to hub:
https://hub.docker.com/r/sirfragalot/hyperion.ng

**Comment by Paulchen-Panther** [comment]
First Alpha Releases are available [here](https://github.com/hyperion-project/hyperion.ng/releases).

**Comment by fightforlife** [comment]
Just a noob question:

Would it be possible to use the x11 grabber while running hyperion in a docker container?

**Comment by Paulchen-Panther** [comment]
@fightforlife No
