### ISSUE TITLE
Spam on Forum - Support

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion.ng#665]
Post your Forum Account Name and I will activate it!

**Comment by eyk107** [comment]
eyk107

**Comment by xenon1337** [comment]
xenon

Just registered today with my Google+ account (mellmann at gmail dot com).
Could you please activate my account? Thanks!

**Comment by tpmodding** [comment]
Done

**Comment by xenon1337** [comment]
Google+ login is no longer possible:

Fehler 400: redirect_uri_mismatch
The JavaScript origin in the request, https://www.hyperion-project.org, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/886535280339-g2p74q2der7dij9867mqq2p8u5tlj8er.apps.googleusercontent.com?project=886535280339 to update the authorized JavaScript origins.

**Comment by rassaei** [comment]
@tpmodding could you please activate my account on the forum? Username is obscuritas

**Comment by tpmodding** [comment]
@rassaei done
