### ISSUE TITLE
Respect user defined v4l2-ctl video capture format [VIDIOC_G_FMT]

### ISSUE THREAD

**Issue by MichaelAnders** [hyperion-project/hyperion.ng#666]
I own a CA FLINT 4KP USB FullHD HDMI grabber attached to an odroid XU4 (Pi doesn't work) via USB3.

I've not been able to get hyperion-v4l2 working with this device properly when I want to forward the flatbuffer to another hyperion instance running on a Pi v2 which drives the LEDs, it would always crash shortly after it's started:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to parse message
Aborted

To see what is being used I did this:
hyperion-v4l2 -d /dev/video2 -s 1 --screenshot
Signal detection informations

dimension after decimation: 1920 x 1080

So hyperion is reading the maximum resolution available (see bottom for a list of all resolutions), and that's just too much to handle it seems.

My solution to make it work:
1)
hack "libsrc/grabber/v4l2/V4L2Grabber.cpp" and rebuild:
  // set the settings
max_width=720; // hack: force height/width
max_height=480; // hack: force height/width

2)
v4l2-ctl -d /dev/video2 --set-fmt-video=width=720,height=480,pixelformat='YUYV' -p 30

3)
hyperion-v4l2 -d /dev/video2 -a 192.168.100.250:19400 -s 3

And the video is transmitted and show in "Live video" on the Pi.

Without this hack, I would have to use a much higher "-s" to shrink the video even more, but that leaves my odroid XU4 using 4 of it's 8 cores at 100% (so ~50% in total) - and the fan gets very loud then...
 
With this hack, the CPU utilization is ~ 12% in total and spread across 6 cores, the fan remains quiet.

It would be nice if there was a parameter so that I could just define the VIDIOC_G_FMT via v4l2-ctl and hyperion would use that information instead of going to the maximum resolution available.

Here is what the device supports:
v4l2-ctl --list-formats-ext --verbose -d /dev/video2
VIDIOC_QUERYCAP: ok
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
		Size: Discrete 720x480
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2
		Size: Discrete 720x480
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)

**Comment by Mernst1** [comment]
Same Problem for me to, hyperion is using full HD resolution from the grabber which causing to much CPU power for the pi3.
Would be great to have a opportunity  to select the possible resolutions.

**Comment by T-IOOO** [comment]
I am running hyperion.ng with following hardware
Rpi0 W
Leds: APA102
Grabber: EasyCap (534d:0021)

Everything works great except the pi's CPU is constantly 100%.
When I disable the grabber the CPU drops to 3-4%.

I know that the Grabber I have is not a recommended one but it actually works.
Is there a fix for this? please let me know!

**Comment by tpmodding** [comment]
should be fixed with #766
