### ISSUE TITLE
Disable/Enable LedDevices automatically depending on Grabber signal availability

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#667]
Hi
on the back of the following forum post [disable-udp-activity-when-there-is-no-signal](https://forum.hyperion-project.org/threads/disable-udp-activity-when-there-is-no-signal.10409/#post-24249), please find below two User Stories to be discussed for the backlog.

**User Stories**
1. As a Hyperion.NG user, I want to have the LedDevice output disabled when there is no Grabber signal for a given period of time, so that no additional update events/network traffic is generated to update LedDevices.

2. As a Hyperion.NG user, I want to have the LedDevice output enabled automatically when the Grabber provides changing input , so that LedDevices reflect the streamed input.

**Comment by Lord-Grey** [comment]
Given that PR #654 takes care that network traffic is suppressed when a LedDevice is disabled,
the main gap is to identify that a grabber is idle or continues feeding data.
The case of these scenarios, the LedDevice would be disabled/enabled.

For the solution implementation, I would see the following options:

1. A user could configure the color, a grabber sends in idle mode.
If the same color is send over a period of time or for a number of snapshots (e.g. 6 times in 30 seconds) the LedDevices are disabled. In case a different color is send, LedDevices are enabled again.

2. Hyperion recognizes that the same picture (identified via a fingerprint) is send for a number of snapshots (e.g. 6 times in 30 seconds) and then the LedDevices are disabled. In case a different fingerprint is send, LedDevices are enabled again (and fingerprints ares only tested e.g. every 5 seconds to minimize load).

3. The grabber identifies the idle state itself and "signals" hyperion to disable/enable the LedDevices.

Option 3 would of course be preferred, but I do not know, if there are Grabber out there with such a feature. Next best option I would see is two, as it is not limited to idle colors and grabbers, but would allow to identify other idle scenarios, e.g. a not changing Kodi menu screen for a given period.

Any opinions, further ideas/options come to mind?

**Comment by tpmodding** [comment]
the idea is good, but i think this is only posible on non-analog usb grabbers..(boblight an framegrabber should work with this) the analog usb grabbers have "too much flicker" as discussed here
https://hyperion-project.org/threads/die-grenzen-eines-analogen-grabbers-und-die-digitale-l%C3%B6sung.4438/

your thoughts?

**Comment by Lord-Grey** [comment]
That answer I feared for analogue grabbers...
Nevertheless, we may then only provide that feature for digital ones unless the is a better idea to solve for this scenario in a efficient way.

Option 3, do you you know, if digital grabbers can „throw“ idle state?

**Comment by brindosch** [comment]
Sounds interesting.
For specific actions i think a trigger -> actor system is required. A bunch of triggers and actors that can be combined.
`on_screencapture_active -> leddevice_disable`
`on_time(18:00) -> set_effect(effectname)`

**Comment by Lord-Grey** [comment]
Great driving the idea even further....
Seems we need to strive even integrating with IFTTT. :)

To have effects as a pure actor we need to disentangle it from LinearColorSmoothing ( which is anyway on my list).

The LedDevice part should be already ready functionality. Via the UI Button this works with #654, just needs to be wrapped as an actor.

**Comment by Lord-Grey** [comment]
Following triggers/actors come into mind, please add as required.

**Triggers**
- Grabber signal unavailable/available/idle
- Data and/or Time of Day
- External Event via API ( or script/command line)

**Actions**
- Disable/Enable Hyperion.NG
- Start/Stop Instance
- Switch off/on LedDevice (all or per instance)
- Run an Effect  (all or per instance)
- Set a Color (for a given time, all or per instance))

**Comment by Araforn** [comment]
Thanks Lord Grey for starting this discussion as a continuation from the Hyperion forum.

I have since developed a workaround in my NodeMCU sketch where I disable/enable Hyperion based on an MQTT command.

This solves the problem where I no longer have hyperion taking control of my ambilight ina power off/no signal scenario.

However it does not and could not solve the problem where hyperion will continue to UDP stream to the device for 90% of its life (we don't watch too much TV! :)) 

Ultimately I now just want to disable hyperion entirely when I don't use it. I believe this can be done by API Call in Hyperion NG but I cannot find documentation/endpoints to do this.

Could you advise what is required to disable hyperion via the API?..

Thabks for your help.
