### ISSUE TITLE
Led Matrix Layout page does not consider last layout saved

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#669]
The Led Matrix Layout page does not consider last layout saved

Test Case:

1. Configure File-Device with 9 Leds
2. Define 3x3 Matrix Layout and save
https://snipboard.io/HqeEg6.jpg
3. Restart hyperion.ng
4. Open Led Matrix layout page

-> The matrix configuration shows the default values  10x10, Snake, Top Left
and not the ones previously saved.
https://snipboard.io/C18gqx.jpg

-> The Preview is correct

**Comment by brindosch** [comment]
Mentoring/Notes
- Server: ledConfig entries should be prefixed with `ma_` and `cl_` to match their full id representation. The `ma_` fields are missing. A db migration should be used to prevent loss of data
- webconfig: include the prefix in the loop for save/restore.

**Comment by Lord-Grey** [comment]
@brindosch Prima, so lernt man auch immer wieder neue Bereiche kennen...
Wo finde ich den Code für eine DB Migration?

Anstatt eines Prefixes, habe ich eine Classic und Matrix Gruppe gebildet.
Hier kämpfe ich gerade noch mit JS...

**Comment by brindosch** [comment]
Mit Gruppe geht auch. Der Vorschlag war ein minimal-edit-Ansatz.
Es gibt keine Migration.

**Comment by Lord-Grey** [comment]
> * A db migration should be used to prevent loss of data

Wenn es aktuell keine DB Migration gibt, wie soll ich dann den obigen Hinweis verstehen?

Oder soll der JS Code auch die alte Struktur lesen können und die neue abspeichern.
So in etwas wie ein Green/Blue Deployment?

**Comment by brindosch** [comment]
> Wenn es aktuell keine DB Migration gibt, wie soll ich dann den obigen Hinweis verstehen?

Das man sich etwas überlegen muss.

> Oder soll der JS Code auch die alte Struktur lesen können und die neue abspeichern.

Wäre auch eine Idee, man könnte das komplette config object undefiniert lassen (schema) und beliebig beschreiben.

Ein Mechanismus zur Migration bleibt aber nötig

**Comment by Lord-Grey** [comment]
@brindosch Ich habe den Code soweit, dass er funktioniert.
Auch eine Routine habe ich geschrieben, die das alte Schema in das neue Umsetzt.

Allerdings wird nach dem Starten im Browser ein Mix von alt und neu in die Datenbank geschrieben:
```
{
    "bottom": 2,
    "classic": {
    },
    "edgegap": 0,
    "glength": 0,
    "gpos": 0,
    "hdepth": 8,
    "left": 3,
    "matrix": {
    },
    "overlap": 0,
    "position": 0,
    "reverse": false,
    "right": 4,
    "top": 1,
    "vdepth": 5
}

```
und Warnings ausgegeben

```
[hyperiond SettingsManager] <WARNING> Config Fix: [root].classic: Removed property: classic
[hyperiond SettingsManager] <WARNING> Config Fix: [root].matrix: Removed property: matrix
```

Wenn ich speichere sieht die Datenbank wie erwartet aus.
```

{
    "classic": {
        "bottom": 2,
        "edgegap": 0,
        "glength": 0,
        "gpos": 0,
        "hdepth": 8,
        "left": 3,
        "overlap": 0,
        "position": 0,
        "reverse": false,
        "right": 4,
        "top": 1,
        "vdepth": 5
    },
    "matrix": {
        "cabling": "snake",
        "ledshoriz": 5,
        "ledsvert": 5,
        "start": "top-left"
    }
}
```

Die Warnungen kommen aber immer noch.

Nach einem Neustart kommen keine Warnungen mehr auch beim Speichern mehr.

Es sieht so aus, als würde hyperion das Schema/die Daten beim Einlesen als gültige Referenz nehmen.
Was mache ich falsch?

**Comment by brindosch** [comment]
Supi
Der settingsManager wird die Daten immer an das schema angleichen. Es kann sein, dass da evtl ein Fehler drin ist.
Vielleicht einen PR erstellen, dann kann man es direkt einsehen und editieren.
