### ISSUE TITLE
Turning smoothing off has no effect (still enabled)

### ISSUE THREAD

**Issue by TheAndi** [hyperion-project/hyperion.ng#671]
When I disable smoothing using the components control, it has no effect and smoothing is still enabled.
It also has no effect when I disable smoothing in the global smoothing settings. I can even change the smoothing time (while it's turned off) and see the difference.

Running on my RPi 1 B+ (running Raspbian Buster Lite).

**Comment by Lord-Grey** [comment]
@TheAndi Hi, I did some updates on Smoothing/LedDevices lately (see #654).
Disabling/Enabling of Smoothing and/or LedDevices should work now.

As the PR has not been merged with the master-branch yet, you may want to give it a try using the code from my [respository](https://github.com/Lord-Grey/hyperion.ng).
Your testing support would be great in getting near-time feedback.
Thanks in advance!

**Comment by Lord-Grey** [comment]
@TheAndi PR654 was just merged with the master.

**Comment by TheAndi** [comment]
Thanks!
I'll give it a try and let you know ;)

**Comment by TheAndi** [comment]
I got the new version up and running, but as soon as I switch to the LED device to ws281x Hyperion crashes:

```
[hyperiond WEBSOCKET] <DEBUG> <WebSocketClient.cpp:30:WebSocketClient()> New connection from ::ffff:192.168.178.40
[hyperiond WEBSOCKET] <DEBUG> <JsonAPI.cpp:107:handleInstanceSwitch()> Client '::ffff:192.168.178.40' switch to Hyperion instance 0
[hyperiond LedDeviceWrapper] <INFO> LedDevice 'ws2812spi' closed
[hyperiond LEDDEVICE] <INFO> LedDevice 'ws281x' found.
[hyperiond LEDDEVICE] <DEBUG> <LedDevice.cpp:68:setEnable()> Device '' was not ready! Trying to re-open.
[hyperiond LEDDEVICE] <DEBUG> Previous line repeats 200 times
[hyperiond LEDDEVICE] <DEBUG> Previous line repeats 200 times
...repeats for many lines...
Segmentation fault
```

Let me know if and how I can provide more info/log or if I should try something different.

Thanks in advance

**Comment by Lord-Grey** [comment]
Let me have a look. I will come back to you.

**Comment by Lord-Grey** [comment]
@TheAndi The failing ws281x LED device is addressed by issue #676.

**Comment by Lord-Grey** [comment]
@TheAndi Have you had the chance to test, if turning smoothing off has now an effect on the output (after #654 and #676, #679 are now part of the master)?
If not, may I ask you to outline the specific test steps, please?

**Comment by T-IOOO** [comment]
I am running Hyperion 2.0.0-alpha.2 and I can confirm that smoothing ON/OFF is working!

**Comment by TheAndi** [comment]
Sorry for the late response, I'm a bit busy at the moment.
But I can confirm that the smoothing toggle works for me too (running 2.0.0-alpha.1)

Will give the alpha.3 a try soon :)
