### ISSUE TITLE
Components control: Button design missleading

### ISSUE THREAD

**Issue by TheAndi** [hyperion-project/hyperion.ng#677]
Nothing that important, but I just want to point it out:

When looking at the components control panel, it is used as status indicator and as toggle button. And in my opinion the current design is very confusing. When I click on a red button with a stop symbol on it, I expect something to stop. But the button just shows that it is already stopped and enables it instead. 

If status and toggle should be in one entity I would recommend something like a switch:
![grafik](https://user-images.githubusercontent.com/33332336/74543158-29bfe100-4f45-11ea-9285-da60d85d6b5d.png)

Or just status indicators (like on the dashboard) with a separate corresponding switch

**Comment by b1rdhous3** [comment]
I will evaluate this. 

Any other opinions on this topic?

**Comment by Lord-Grey** [comment]
@b1rdhous3 I agree. Toggle buttons will be more intuitive.

2. This this beyond toggle buttons, but while you are going to update the Remote Control panel we may think about to have sliders to control output delay or smoothing time-windows interactively. This would also improve the user experience from click and save way to just manipulating a slider...

**Comment by b1rdhous3** [comment]
You are right the remote panel can get some more improvements than this. We can take a look in it. But for the start I think the slider would be a good start. Espacially for the options which don't need or take other values like smoothing or so on.

**Comment by Lord-Grey** [comment]
I completely agree! MVP change is Toggle buttons.
I just wanted not losing the idea :)
