### ISSUE TITLE
Smoothing "Activate" Checkbox does not sync when enabled/disabled elsewhere

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#680]
The Smoothing "Activate" checkbox on the Image Processing screen does not reflect a status change, if Smoothing is disabled/enabled via the Components control button.
The Components status overview reflect the change correctly.

**Test Case:**
1. Verify that Smoothing is off (either Components status overview or Debug-Log)
2. Enable Image Processing -> Smoothing "Activate" checkbox
3. Save
4. Components control - >Disable Smoothing
5. Verify that Smoothing is off (either Components status overview or Debug-Log)
6. Refresh Image Processing Screen
-> Smoothing Activate is still checked -> NOK

**Comment by zerobabble** [comment]
Experiencing the same issue with latest commit.
- Configuration ==> Image Processing ==> Smoothing /checkbox checked. 
- Hyperion restart ==> smoothing disabled, smoothing checkbox still checked.
- Remote Control ==> Components Control ==> Start smoothing.
- RPi3/apa102

**Comment by brindosch** [comment]
> The Smoothing "Activate" checkbox on the Image Processing screen does not reflect a status change, if Smoothing is disabled/enabled via the Components control button.

That's intended.  The checkbox shows if the ~setting~ is enabled (persistent). Component control is a runtime change and can be freely used but it never persists a restart.

> Configuration ==> Image Processing ==> Smoothing /checkbox checked.
Hyperion restart ==> smoothing disabled, smoothing checkbox still checked.

That's a bug, the smoothing should reflect on startup the settings state
