### ISSUE TITLE
CI: Deprecate or fix travis

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#683]
Travis mac builds are broken, as we have now Github Actions and Azure should we still maintain travis?

**Comment by tpmodding** [comment]
why use externa tools if we can use github tools? is there a added value for travis?

**Comment by brindosch** [comment]
Travis was the first service. That's it.

**Comment by Paulchen-Panther** [comment]
> is there a added value for travis?

Not in a long time. [The time limit prevents us from running the arm docker container to the end](https://github.com/hyperion-project/hyperion.ng/blob/master/.travis.yml#L34-L56).

**Comment by brindosch** [comment]
Oh, you are right. /rm
