### ISSUE TITLE
Trouble with installing on RPi4

### ISSUE THREAD

**Issue by previajoemal** [hyperion-project/hyperion.ng#691]
Hi,

First of all, I have limited knowledge of Linux.

I have tried to install hyperion.ng now on latest Raspian (Buster Rev. 2020-02-13) on a RPi4 (4GB RAM) and ended up in the same scenario all the time.

What I can read it's something wrong with  SSL & CMake.

I have run the commands:

- sudo apt-get update
- sudo apt-get install git cmake build-essential qtbase5-dev libqt5serialport5-dev libusb-1.0-0-dev python3-dev libxrender-dev libavahi-core-dev libavahi-compat-libdnssd-dev libjpeg-dev libqt5sql5-sqlite
-  sudo apt-get install libraspberrypi-dev
-  wget -qO- https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/bin/compile.sh | sh

At 100% it's as follow:

```
> [100%] Linking CXX executable ../../bin/hyperiond
> -- CMake Version: 3.13.4
> CMake Deprecation Warning at CMakeLists.txt:18 (CMAKE_POLICY):
>   The OLD behavior for policy CMP0026 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- PLATFORM is not defined, evaluated platform: rpi
> -- PLATFORM: rpi
> -- ENABLE_AMLOGIC = OFF
> -- ENABLE_DISPMANX = ON
> -- ENABLE_FB = ON
> -- ENABLE_OSX = OFF
> -- ENABLE_SPIDEV   = ON
> -- ENABLE_TINKERFORGE = ON
> -- ENABLE_V4L2 = ON
> -- ENABLE_WS281XPWM = ON
> -- ENABLE_USB_HID = ON
> -- ENABLE_X11 = OFF
> -- ENABLE_QT = ON
> -- ENABLE_TESTS = OFF
> -- ENABLE_PROFILER = OFF
> -- validate json files
>    checked files: 78 success: 78 errors: 0
> -- validate json effect files
>    checked effect files: 38 success: 38 errors: 0
> -- validate json file
> -- Current Version: 2.0.0-alpha.1
> --  - Build: master (GitHub-00502890/2e15ef7c-1581970640) Git Remote: https://github.com/hyperion-project/hyperion.ng.git
> -- Linker: GNU gold
> -- Found Qt Version: 5.11.3
> -- Found libusb-1.0:
> --  - Includes: /usr/include/libusb-1.0
> --  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
> -- Using JPEG library: /usr/lib/arm-linux-gnueabihf/libjpeg.so
> -- Using flatbuffers compiler: /home/pi/hyperion/build/bin/flatc
> CMake Deprecation Warning at dependencies/external/protobuf/src/CMakeLists.txt:329 (cmake_policy):
>   The OLD behavior for policy CMP0026 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- Using protobuf compiler: /home/pi/hyperion/build/bin/protoc
> -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found suitable version "3.7.3", minimum required is "3.5")
> -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found suitable version "3.7.3", minimum required is "3.4")
> CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
>   OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake-3.13/Modules/FindOpenSSL.cmake:412 (find_package_handle_standard_args)
>   src/hyperiond/CMakeLists.txt:49 (find_package)
>   src/hyperiond/CMakeLists.txt:260 (InstallDependencies)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/hyperion/build/CMakeFiles/CMakeOutput.log".
> See also "/home/pi/hyperion/build/CMakeFiles/CMakeError.log".
> make[2]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/build.make:191: bin/hyperiond] Error 1
> make[2]: *** Deleting file 'bin/hyperiond'
> make[1]: *** [CMakeFiles/Makefile2:2991: src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> 
```
Any help is appreciated.

**Comment by Paulchen-Panther** [comment]
sudo apt-get install libssl-dev

**Comment by previajoemal** [comment]
Hi,

Thanks for your answer.

Seems like the error disappeared but I can't get the web GUI on RPi Ip on 8090 or 8091.

Any Idea?

**Comment by Paulchen-Panther** [comment]
How do you run hyperion? Did you install it or took the binaries out of the build folder?
Output log from 'hyperiond - d'!

**Comment by previajoemal** [comment]
> How do you run hyperion? Did you install it or took the binaries out of the build folder?
> Output log from 'hyperiond - d'!

My misstake, I thought it was autostarted but it wasn't.
All works fine now but how do I make it autostart on boot?

The hyperiond in located in /usr/local/share/hyperion/bin

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion.ng/tree/master/bin/service

**Comment by previajoemal** [comment]
Thanks,

But like I said my knowledge of Linux is limited.

I have tried to copy hyperion.systemd  to /etc/systemd/system/ and renamed it to hyperion.service

Without changing it i get the error:
`Feb 19 22:01:10 raspberrypi systemd[1]: /etc/systemd/system/hyperion.service:7: Invalid user/group nam`

When I change the user to Pi I can start it but the webserver doesn't start.

**Comment by b1rdhous3** [comment]
If you want you can use one of our fresh Releases :)
It will install an service right away. 

`
wget https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.2/Hyperion-2.0.0-alpha.2-Linux-armv7hf-rpi.deb
sudo dpkg -i Hyperion-2.0.0-alpha.2-Linux-armv7hf-rpi.deb
`

If using user pi your service will be "hyperiond@pi."

**Comment by fir3drag0n** [comment]
I just updated to alpha 3, but now I have to first disable and enable hyperion by the web interface in order to start the grabbing.

What can I do to start after booting immediately?

**Comment by fir3drag0n** [comment]
I think it is the same problem as here described https://github.com/hyperion-project/hyperion.ng/issues/710

**Comment by brindosch** [comment]
Is resolved
