### ISSUE TITLE
CI - Artifacts for faster testing

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#700]
## Feature request

CI should upload final artifacts on PR's.
- The version number of these builds in `version` file should be modified to reflect the origin. For example `2.0.0-alpha.1-PR#676-ci-COMMIT` or `2.0.0-alpha.1-CI-COMMIT`
- This is probably not a feature for us devs, as we can build and run very quickly. But as a user you will appreciate it.

This can be?
- [Azure](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops). I see just "internal" usage snippets, is this available for browser download?
- [Gitub Actions](https://github.com/marketplace/actions/upload-artifact)

#### What problem does this feature solve?

Fast access to PR builds

#### Are you willing to work on this yourself?

**Comment by b1rdhous3** [comment]
They will not published to releases page? Because they should not. 
Where can a user get the package? With the azure link?

**Comment by Paulchen-Panther** [comment]
> They will not published to releases page? Because they should not.

Vollkommen richtig.

> Where can a user get the package? With the azure link?

Ich habe mich für GitHub Actions entschieden.
Ist unter der GitHub Actions Zusammenfassung des jeweiligen PRs enthalten.
Screens:
https://prnt.sc/r6jewe
https://prnt.sc/r6jfas

**Comment by Paulchen-Panther** [comment]
@brindosch 

> * The version number of these builds in `version` file should be modified to reflect the origin. For example `2.0.0-alpha.1-PR#676-ci-COMMIT` or `2.0.0-alpha.1-CI-COMMIT`

Ich werde noch versuchen den jeweiligen Commit da irgenwie mit einzubauen. In den Dateinamen ist schlecht. Da spinnt CPack rum wenn der Dateiname zu lang wird.
Hast du andere Vorschläge?

**Comment by b1rdhous3** [comment]
Wir sollten vorsichtig sein jeden PR direkt zu Kompilieren, oder? 
Wir haben ja noch nicht geprüft was da eingebaut wurde. Und nachher lädt das jmd runter

**Comment by Paulchen-Panther** [comment]
> Wir sollten vorsichtig sein jeden PR direkt zu Kompilieren, oder?

Ist ja zum Glück noch in der WIP Phase. :smiley: 

> Wir haben ja noch nicht geprüft was da eingebaut wurde. Und nachher lädt das jmd runter

Man sollte schon selber wissen was man tut. Wer jeden Mist downloaded, dem ist sowieso nicht mehr zu helfen.

**Comment by b1rdhous3** [comment]
Stimmt schon, dennoch fühlt man sich ja ein bisschen verantwortlich ;) 

Gibt ja leider genug Beispiele wo sowas ausgenutzt wurde

**Comment by Paulchen-Panther** [comment]
> Stimmt schon, dennoch fühlt man sich ja ein bisschen verantwortlich ;)
> 
> Gibt ja leider genug Beispiele wo sowas ausgenutzt wurde

Ich denke, [das hier](https://github.com/marketplace/actions/pull-request-comment-trigger) ist ein ganz heißer Kandidat.

**Comment by b1rdhous3** [comment]
Wenn man da festlegen kann wer dieses trigger Wort nutzen darf, perfekt!

**Comment by Paulchen-Panther** [comment]
> Wenn man da festlegen kann wer dieses trigger Wort nutzen darf, perfekt!

Scheint nicht so zu sein. [Quelle](https://github.com/Khan/pull-request-comment-trigger/blob/master/action.yml)

**Comment by Paulchen-Panther** [comment]
Was ich vergessen habe zu erwähnen. Die Dauer der Artifact Verfügbarkeit ist auf einen Tag beschränkt. Dafür sollte [dieses cron Script](https://github.com/hyperion-project/hyperion.ng/pull/702/files#diff-9c8a8027f6d68479d7974a98fde32203) sorgen.

**Comment by brindosch** [comment]
Super :)
Spricht etwas gegen das maximale Vorhalten von 90 Tagen seitens GH?

**Comment by Paulchen-Panther** [comment]
> Super :)
> Spricht etwas gegen das maximale Vorhalten von 90 Tagen seitens GH?

Nein. Die Dauer macht mir keine Sorgen. Nur die maximale Größe von 55GB

**Comment by brindosch** [comment]
Dann gehen wir vielleicht auf 14 Tage?

**Comment by brindosch** [comment]
> Da spinnt CPack rum wenn der Dateiname zu lang wird.

Dann muss man wohl mit weniger auskommen. Die Markierung so ist schon ganz gut.

**Comment by Paulchen-Panther** [comment]
> > Da spinnt CPack rum wenn der Dateiname zu lang wird.
> 
> Dann muss man wohl mit weniger auskommen. Die Markierung so ist schon ganz gut.

Wenn du uns im About Fenster eine separates Feld hinterlegst, kann ich auch den PR Link und den commit des PRs per env variable an das build Script übergeben.

**Comment by Paulchen-Panther** [comment]
Ich werde mal den PR mergen und dann sehen wir wie sich das ganze gestaltet.

**Comment by brindosch** [comment]
Ja mal sehen und ggf weiter anpassen. >1GB pro push ist schon eine Hausnummer.

**Comment by Paulchen-Panther** [comment]
Wir können auch nur die deb Pakete zum testen bereit stellen.

**Comment by brindosch** [comment]
Ja schwierig. Vielleicht nur eine "portable" Version (tar.gz)? Entpacken, ausführen, testen, feedback, löschen. Welcher flow ist sinnvoll und universell genug? Zumal die artifacts eigentlich kein daily driver sein sollten.

Also nach meiner Überlegung eine `*.tar.gz` pro Ziel. Wären dann so ~450MB anstatt 1,2GB?

Ggf mehr Input erwünscht. @hyperion-project/hyperion

**Comment by Paulchen-Panther** [comment]
> Ja schwierig. Vielleicht nur eine "portable" Version (tar.gz)? Entpacken, ausführen, testen, feedback, löschen. Welcher flow ist sinnvoll und universell genug? Zumal die artifacts eigentlich kein daily driver sein sollten.

Klingt Sinnvoll. Ist schon mal weniger als die Hälfte.
Commit kommt gleich.

**Comment by Paulchen-Panther** [comment]
Wo wir noch Platz einsparen könnten ist das kontrollierte Kopieren von Python in die Pakete. Bis jetzt wird das ganze Python Verzeichnis kopiert. Ist das überhaupt notwendig?

**Comment by brindosch** [comment]
Ich schätze das ist die ganze std lib für Python dann? Weiß aber nicht wo man da sinnvoll Grenzen ziehen kann. Für die Effekte benötigt man 99% vermutlich nicht. `import time` ist wohl das am Meisten genutzte. Sollte man aber mal ein Addon interface aufmachen, dann wird man wieder mehr zur Verfügung stellen wollen oder alles.

**Comment by tpmodding** [comment]
sind das alles sachen wo man sagen kann "hey ihr MÜSST das vorher installieren"
