### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by jonwilliams84** [hyperion-project/hyperion.ng#701]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I get this when trying to build the latest release within a Dockerfile.

` -- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
 CMake Deprecation Warning at dependencies/external/protobuf/src/CMakeLists.txt:329 (cmake_policy):
   The OLD behavior for policy CMP0026 will be removed from a future version
   of CMake.
   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.
 -- Using protobuf compiler: /source/hyperion/build/bin/protoc
 -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.5") 
 -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.4") 
 CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
   OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")
 Call Stack (most recent call first):
   /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
   /usr/share/cmake-3.10/Modules/FindOpenSSL.cmake:390 (find_package_handle_standard_args)
   src/hyperiond/CMakeLists.txt:68 (find_package)
   src/hyperiond/CMakeLists.txt:260 (InstallDependencies)
 -- Configuring incomplete, errors occurred!
 See also "/source/hyperion/build/CMakeFiles/CMakeOutput.log".
 See also "/source/hyperion/build/CMakeFiles/CMakeError.log".
 make[2]: *** [bin/hyperiond] Error 1
 make[2]: *** Deleting file 'bin/hyperiond'
 src/hyperiond/CMakeFiles/hyperiond.dir/build.make:232: recipe for target 'bin/hyperiond' failed
 CMakeFiles/Makefile2:2902: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed
 make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
 make: *** [all] Error 2
 Makefile:151: recipe for target 'all' failed
`

#### Steps to reproduce

Compilation of latest version

#### What is expected?

Compilation successful

#### What is actually happening?
Compile fails with above error.

#### System

Ubuntu 18.04 - Docker build. x86/amd64.

**Comment by Paulchen-Panther** [comment]
I can't confirm this issue.
Compiled under Ubuntu 18.04:
https://gist.github.com/Paulchen-Panther/283e4d0abf23ed6b7366ecf5b8ad244b

**Comment by hissingshark** [comment]
This is happening for me on an RPi Zero W running Raspbian Lite and also on the Vero4K running OSMC/Debian.

---
Vero4K:
> [100%] Linking CXX executable ../../bin/hyperiond                                                                                                                            
> -- CMake Version: 3.7.2                                                                                                                                                      
> -- PLATFORM: amlogic                                                                                                                                                         
> -- ENABLE_AMLOGIC = ON                                                                                                                                                       
> -- ENABLE_DISPMANX = OFF                                                                                                                                                     
> -- ENABLE_FB = ON                                                                                                                                                            
> -- ENABLE_OSX = OFF                                                                                                                                                          
> -- ENABLE_SPIDEV   = OFF                                                                                                                                                     
> -- ENABLE_TINKERFORGE = OFF                                                                                                                                                  
> -- ENABLE_V4L2 = OFF                                                                                                                                                         
> -- ENABLE_WS281XPWM = OFF                                                                                                                                                    
> -- ENABLE_USB_HID = OFF                                                                                                                                                      
> -- ENABLE_X11 = OFF                                                                                                                                                          
> -- ENABLE_QT = OFF                                                                                                                                                           
> -- ENABLE_TESTS = OFF                                                                                                                                                        
> -- ENABLE_PROFILER = OFF                                                                                                                                                     
> -- validate json files                                                                                                                                                       
>    checked files: 78 success: 78 errors: 0                                                                                                                                   
> -- validate json effect files                                                                                                                                                
>    checked effect files: 38 success: 38 errors: 0                                                                                                                            
> -- validate json file                                                                                                                                                        
> -- Current Version: 2.0.0-alpha.3                                                                                                                                            
> --  - Build: master (Hyperion-Bot-51f7481d/cc840ab5-1583090356)                                                                                                              
> -- Linker: Default system linker                                                                                                                                             
> -- Found Qt Version: 5.7.1                                                                                                                                                   
> -- Found libusb-1.0:                                                                                                                                                         
> --  - Includes: /usr/include/libusb-1.0                                                                                                                                      
> --  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so                                                                                                                  
> -- Using flatbuffers compiler: /home/osmc/hyperion-vero4k/source/build/bin/flatc                                                                                             
> -- Using protobuf compiler: /home/osmc/hyperion-vero4k/source/build/bin/protoc                                                                                               
> -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.5m.so (found suitable version "3.5.3", minimum required is "3.5")                                               
> -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.5m.so (found suitable version "3.5.3", minimum required is "3.4")                                               
> CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):  
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES                                                                                                               
>   OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")                                                                                                                
> Call Stack (most recent call first):                                                                                                                                         
>   /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)                                                                              
>   /usr/share/cmake-3.7/Modules/FindOpenSSL.cmake:385 (find_package_handle_standard_args)                                                                                     
>   src/hyperiond/CMakeLists.txt:68 (find_package)                                                                                                                             
>   src/hyperiond/CMakeLists.txt:262 (InstallDependencies)                                                                                                                     
>                                                                                                                                                                              
>                                                                                                                                                                              
> -- Configuring incomplete, errors occurred!                                                                                                                                  
> See also "/home/osmc/hyperion-vero4k/source/build/CMakeFiles/CMakeOutput.log".                                                                                               
> See also "/home/osmc/hyperion-vero4k/source/build/CMakeFiles/CMakeError.log".                                                                                                
> src/hyperiond/CMakeFiles/hyperiond.dir/build.make:224: recipe for target 'bin/hyperiond' failed                                                                              
> make[2]: *** [bin/hyperiond] Error 1                                                                                                                                         
> make[2]: *** Deleting file 'bin/hyperiond'                                                                                                                                   
> CMakeFiles/Makefile2:2687: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed                                                                             
> make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2                                                                                                            
> Makefile:149: recipe for target 'all' failed                                                                                                                                 
> make: *** [all] Error 2  

---
RPi Zero W:

> [ 95%] Automatic MOC for target hyperiond
> [ 95%] Built target hyperiond_autogen                                
> [ 95%] Linking CXX executable ../../bin/hyperiond                          
> -- CMake Version: 3.13.4                                                  
> CMake Deprecation Warning at CMakeLists.txt:18 (CMAKE_POLICY):
>   The OLD behavior for policy CMP0026 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all                                                                                                       
>   policies are deprecated and that a policy should be set to OLD only under                                                                                                 
>   specific short-term circumstances.  Projects should be ported to the NEW                                                                                                  
>   behavior and not rely on setting a policy to OLD.                        
> 
> -- PLATFORM is not defined, evaluated platform: rpi
> -- PLATFORM: rpi                                                                                                                                                            
> -- ENABLE_AMLOGIC = OFF                                                                                                                                                     
> -- ENABLE_DISPMANX = ON                         
> -- ENABLE_FB = ON                                       
> -- ENABLE_OSX = OFF
> -- ENABLE_SPIDEV   = ON
> -- ENABLE_TINKERFORGE = ON                 
> -- ENABLE_V4L2 = ON                                           
> -- ENABLE_WS281XPWM = ON                                     
> -- ENABLE_USB_HID = ON                                                                                                                                                      
> -- ENABLE_X11 = OFF                       
> -- ENABLE_QT = ON  
> -- ENABLE_TESTS = OFF
> -- ENABLE_PROFILER = OFF
> -- validate json files
>    checked files: 78 success: 78 errors: 0
> -- validate json effect files
>    checked effect files: 38 success: 38 errors: 0
> -- validate json file
> -- Current Version: 2.0.0-alpha.3
> --  - Build: master (Hyperion-Bot-51f7481d/cc840ab5-1583090356)
> -- Linker: GNU gold
> -- Found Qt Version: 5.11.3
> -- Found libusb-1.0:
> --  - Includes: /usr/include/libusb-1.0
> --  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
> -- Using JPEG library: /usr/lib/arm-linux-gnueabihf/libjpeg.so
> -- Using flatbuffers compiler: /home/pi/hyperion/build/bin/flatc
> CMake Deprecation Warning at dependencies/external/protobuf/src/CMakeLists.txt:329 (cmake_policy):                                                                          
>   The OLD behavior for policy CMP0026 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> -- Using protobuf compiler: /home/pi/hyperion/build/bin/protoc
> -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found suitable version "3.7.3", minimum required is "3.5")                                              
> -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found suitable version "3.7.3", minimum required is "3.4")                                              
> CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):                                                                             
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
>   OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)                                                                            
>   /usr/share/cmake-3.13/Modules/FindOpenSSL.cmake:412 (find_package_handle_standard_args)                                                                                   
>   src/hyperiond/CMakeLists.txt:68 (find_package)
>   src/hyperiond/CMakeLists.txt:262 (InstallDependencies)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/hyperion/build/CMakeFiles/CMakeOutput.log".
> See also "/home/pi/hyperion/build/CMakeFiles/CMakeError.log".
> make[2]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/build.make:191: bin/hyperiond] Error 1                                                                                 
> make[2]: *** Deleting file 'bin/hyperiond'
> make[1]: *** [CMakeFiles/Makefile2:2991: src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2                                                                                
> make: *** [Makefile:152: all] Error 2

---
In both cases I find it odd that `cmake` is invoked again at the end of the process?
Both also reference OpenSSL, but `cmake` didn't complain about it when configuring prior to the build.
The build dependencies haven't changed in your guide either.

**Comment by Paulchen-Panther** [comment]
Unfortunately I do not have a Vero4k but could you explain your detailed steps on the rpi zero w to me?

**Comment by hissingshark** [comment]
Needs `libssl-dev` installing.
I've submitted a PR to add this to the manual build instructions.
I went to fix the docker build scripts but see that it was already fixed there.
