### ISSUE TITLE
To much white shown

### ISSUE THREAD

**Issue by gijsje** [hyperion-project/hyperion.ng#705]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?
I have WS2801 behing the tv and they sort of work with the latest beta version.
The issue i have that they show a lot of white light when the immage actualy is black.
They do not really turn of when thay should turn off.
The also saturates the  colors show with a lot of white in them

i did try al lot of settings but maybe i have not found the correct setting yet or maybe there is an issue with sending the info to the led.
If i look at the image video preview in the software there is not that much white in the led shown in the pic.

Here is a pic of the action screen with the white
http://gijsje.net/div/hyperion-1.jpg

Here is a pic of the software screen capture
http://gijsje.net/div/hyperion-2.png
#### System
RPI 3B+

**Comment by tpmodding** [comment]
do you have blackborder active?

**Comment by ssirkakriss** [comment]
I think you can adjust what your seeing with the gamma settings under Image processing.
![hypergama](https://user-images.githubusercontent.com/32778627/75121259-3f798880-5660-11ea-978a-b6b5313188b5.PNG)

Hope its of help.

**Comment by T-IOOO** [comment]
It sounds more like the Backlight threshold is >0
Try setting it to 0 and see what happens. I have APA102 and my issue is that the lights stays on even when I shut the TV and receiver off.

**Comment by gijsje** [comment]
Thanks for the tips i wil have a look later today

**Comment by gijsje** [comment]
I have now changed the gamma of all channels to 2 and now it is much better.
Thanks
