### ISSUE TITLE
Ws2812b

### ISSUE THREAD

**Issue by oriasp** [hyperion-project/hyperion.ng#714]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The ws2812b pwm led config doesnt work, hyperion ng gives sometimes an error out.

#### Steps to reproduce
Select ws2812x on the led hardware list, the leds will not shine.

#### What is expected?
That the leds work like in the spi mode. Spi has much issues with rasoberry because it doesnt have an RTC.

#### What is actually happening?
Nothing, sometimes an error.

**Comment by Lord-Grey** [comment]
> The ws2812b pwm led config doesnt work, hyperion ng gives sometimes an error out.

Would you mind to share the log including the error output with us, please?
Best would be you enable Debug logging to have additional information next to the error(s).

In addition, it would be helpful, if you share the version and platform details you experience the failures on.
Thank you!

**Comment by FPille** [comment]
Refer to this post: https://github.com/hyperion-project/hyperion.ng/issues/641#issuecomment-582572394

**Comment by Lord-Grey** [comment]
The post refers to two issues, the first on library, the second on Device not ready.
The later was fixed.
Rather then pointing to the other post, it would be helpful if you can be more specific.
Otherwise it will be challenging to provide some help....

**Comment by FPille** [comment]
The link refers to this post/comment. 
> Running hyperiond as root (via sudo) should solve the problem with the ws281x library.

That might fix this issue as well...

**Comment by oriasp** [comment]
I always start the hyperiond with a script as root. (sudo) And on raspbian lite, buster. 
And thanks to you all, i really appreciate your works. With the newest build, forwarding works better.

Because i use my Raspberry only for ambilight, i have settled the CPU frequency down to 250 and use now the ws281xspi library. With throttling the speed, the well known issue with the ws2812b flickering stopped. 
I use the build Hyperion ng 2.0.0-alpha.3.
I close this issue, because the spi-driver works properly.
