### ISSUE TITLE
Pi Blaster not working

### ISSUE THREAD

**Issue by JulianMined** [hyperion-project/hyperion.ng#715]
I can use Pi-Blaster with terminal but not with Hyperion.

[hyperiond LEDDEVICE] <INFO> Connected to device(/dev/pi-blaster)
[hyperiond LEDDEVICE] <ERROR> Device disabled, device 'piblaster' signals error: 'Device (/dev/pi-blaster) is already open.'
[hyperiond LEDDEVICE] <ERROR> Device 'piblaster' cannot be enabled, as it is not ready!

**Comment by Lord-Grey** [comment]
@JulianMined Do you have another hyperion instance still running?

Alternatively, which platform are you running on and would you be able to compile, if I provide you with a modified version?

**Comment by JulianMined** [comment]
I tried to run it in a second instance on Raspbian Buster.
The first instance uses ws2812spi.

**Comment by Lord-Grey** [comment]
Does it work, if you only run one instance with Pi-Blaster?

**Comment by JulianMined** [comment]
@Lord-Grey No, that's also not working

**Comment by Lord-Grey** [comment]
@JulianMined Could you check, if PR #855 addresses your issue?

**Comment by Lord-Grey** [comment]
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment]
Closing, as no feedback provided. Can be reopened, if needed.
