### ISSUE TITLE
SSDP Discovery does work reliably

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#726]
- [x] I confirm that this is an issue rather than a question.

## Bug report

SSDP Discovery does work reliably.
Devices are not consistently identified.

#### Steps to reproduce

Configure a Nanoleaf of PhilipsHue (requires #712) device without hostname/IP-address

#### What is expected?

A device is consistently identified.

#### What is actually happening?

Only in very limited cases device is identified, esp. if ST is broad (e.g. ssdp:all).

**Comment by Lord-Grey** [comment]
Reason is that waitForReadyRead is only called ones which result in the fact that additional ssdp responses are not considered.

I am already working on a fix, but would like also to add additional features,
which e.g. would be required for a Philips Hue and YeeLight support.

**Comment by brindosch** [comment]
As said we need a searchString for data of `LOCATION`. Currently it's designed to search for a unique `ST`. Details may vary based on the targets. Extracted data may help

So here is a Hue bridge for ref
```
<root>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.0.177:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (192.168.0.177)</friendlyName>
<manufacturer>Signify</manufacturer>
<manufacturerURL>http://www.meethue.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2015</modelName>
<modelNumber>BSB002</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>xxxxxxxxx</serialNumber>
<UDN>uuid:xxxxxxxxx</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>
```

**Comment by Lord-Grey** [comment]
@brindosch Thanks for sharing.
Indeed, additional features are required incl. lookups in other fields, plus, e.g. Yeelight requires a different port and has propriarity reponse elements.
Let me do the mandatory fix to not loose ssdp reponses and then I will take care about more flexibility...
