### ISSUE TITLE
LibreELEC install?

### ISSUE THREAD

**Issue by iLLiac4** [hyperion-project/hyperion.ng#730]
Hi is it possible to create a package under releases that can be installed to librelec?
TNX

**Comment by Teryon** [comment]
Hi,
Yes, how can we install this on LibreElec x86-64 ?
Thx.

**Comment by Paulchen-Panther** [comment]
@iLLiac4 & @Teryon 
[Automatic install script](https://hyperion-project.org/threads/howto-hyperion-ng-libreelec.10463/) for RPi (1,2,3,4) for LibreELEC.

Other Platforms as RPi:
- Download [tar.gz](https://github.com/hyperion-project/hyperion.ng/releases) with eg. "wget" or "curl" and unpack to /storage.
example:
`curl -# -L --get https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.3/Hyperion-2.0.0-alpha.3-Linux-amd64-x11.tar.gz | tar --strip-components=1 -C /storage share/hyperion -xz`
- run /storage/hyperion/bin/hyperiond

**Comment by Paulchen-Panther** [comment]
To start Hyperion on startup. Create a service file manual.
example: from the "automatic install script"

**Comment by iLLiac4** [comment]
Hi. Have tried but it is still missing some libs

 # /storage/hyperion/bin/hyperiond
/storage/hyperion/bin/hyperiond: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory

**Comment by Paulchen-Panther** [comment]
then please open a new bug issue. Thank you. closed.
