### ISSUE TITLE
Not completly diasbled with wled

### ISSUE THREAD

**Issue by gijsje** [hyperion-project/hyperion.ng#731]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I am running the lastest beta version 2.0.0-alpha.3
I have wled on a D1 mini with firmeware WLED_0.9.1_ESP8266_ws2801.bin
Hyperion is on a Pi3 
LED config UDPE131

#### What is actually happening?
If hyperion is enabled it work good and the led change by the screen input.
If i disable hyperion i would expect that i can controll the led again with wled.
This works but the leds turn of in a sequence of about 2,5 seconds.
So they turn of and turn on again i can change the color or effect within wled.

If stop hyperion completly or turn of the pi the leds are working ok without the blinking effect.

So i think there is still data comming for hyperion making my leds turn on and off.

Is there something i can check?
It is not a power issue as it are only 10 leds with a big power supply

**Comment by brindosch** [comment]
I suppose this is the led device rewrite, which is active when the led device is disabled. Can you set the access lvl at the webui to expert and change the refresh time of the led device to 0?

**Comment by Teryon** [comment]
Setting refresh time from 2500ms to 0 fix the bliking effect.
But I have to manually disable LED DEVICE, to get WLED control back, without disabling this, hyperion keeps control of it.

**Comment by brindosch** [comment]
`2.0.0-alpha.6`. All network related led devices should no longer refresh. However, there is no feature that disables the device "out of the wilde". So you need to disable Hyperion or just the led device if you want to switch control.

We might add "something" to disable the led device in different scenarios in future versions.
