### ISSUE TITLE
Failed to open device

### ISSUE THREAD

**Issue by sawo69** [hyperion-project/hyperion.ng#733]
Hi,

I installed hyperion on a RPi 3b

```
sudo apt-get update
sudo apt-get install git cmake build-essential qtbase5-dev libqt5serialport5-dev libusb-1.0-0-dev python3-dev libxrender-dev libavahi-core-dev libavahi-compat-libdnssd-dev libjpeg-dev libqt5sql5-sqlite libssl-dev
wget -qO- https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/bin/compile.sh | sh 
```

start hyperion with ./hyperiond

Configured apa102 in the web interface

I get the following error

[hyperiond LEDDEVICE] <ERROR> Device disabled, device 'apa102' signals error: 'Failed to open device (/dev/spidev0.0). Error message: No such file or directory'

[This](https://tof.cx/image/qQjqri) is my setup

**Comment by tpmodding** [comment]
is spi active?

**Comment by sawo69** [comment]
What is a spi and how do I check that?

**Comment by tpmodding** [comment]
https://bit.ly/3979Jfp

**Comment by tpmodding** [comment]
please use google, this is not an issue

you can also look at our forum https://hyperion-project.org/

**Comment by sawo69** [comment]
Thanks, indeed the SPI was not enabled.

Nothing working jet but I got rid of the error message.
