### ISSUE TITLE
LibreELEC x86 x64 installation

### ISSUE THREAD

**Issue by iLLiac4** [hyperion-project/hyperion.ng#735]
I have tried to install hyperion.ng to LibreELEC x86 build 18.6.
The steps were:
Download tar.gz with eg. "wget" or "curl" and unpack to /storage.
example:
curl -# -L --get https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.3/Hyperion-2.0.0-alpha.3-Linux-amd64-x11.tar.gz | tar --strip-components=1 -C /storage share/hyperion -xz
run /storage/hyperion/bin/hyperiond

After running hyperiond the error about missing library:
/storage/hyperion/bin/hyperiond: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory

**Comment by Paulchen-Panther** [comment]
I'm going to look at this today

**Comment by iLLiac4** [comment]
TNX will test it and update this topic if it will work.
https://forum.kodi.tv/showthread.php?tid=338046

**Comment by Paulchen-Panther** [comment]
When the workflow from[ this PR](https://github.com/hyperion-project/hyperion.ng/pull/736) is complete, you will find compiled artifacts to test [here](https://github.com/hyperion-project/hyperion.ng/actions/runs/60824439).

**Comment by iLLiac4** [comment]
I have tested it. The installation now works. Now i will need to figure out which grabber to use since I am using adalight controller but it seems that none of the platform capture/type works and x11 freezes. I there any type like it was on old version hyperion-project/hyperion.kodi where we had to use this one to be able to capture?

**Comment by Paulchen-Panther** [comment]
I tried the Hyperion package on LibreELEC on another x86 system yesterday. It went smoothly there. Could you try a fresh system?
We would also be interested in the hyperion log output.

**Comment by iLLiac4** [comment]
Which grabber have you used? Is also any additional addon needed? Tnx

**Comment by Paulchen-Panther** [comment]
I used the X11 grabber. But you can try the QT Grabber. I didn't use an add-on.

**Comment by iLLiac4** [comment]
Ok did a clean boot and the same problem effects do work but no grabbing.
This is the log for QT grabber https://pastebin.com/Sd3cUVau

**Comment by Paulchen-Panther** [comment]
I actually meant the X11 log and not the QT grabber. That was just a suggestion. But it doesn't matter.
Please tell us more about your system. If possible, mainboard type, CPU etc.

**Comment by iLLiac4** [comment]
If i select x11 it goes into bootloop.
Media center is asrock j5005-itx https://www.asrock.com/mb/Intel/J5005-ITX/index.asp
with 8gb ram. For ambilight I use arduino with adalight code from my repo https://github.com/iLLiac4/Adalight_Hyperion and it has worked on older version.
