### ISSUE TITLE
LED Device can't be disabled

### ISSUE THREAD

**Issue by TheAndi** [hyperion-project/hyperion.ng#742]
Today I upgraded to alpha3 and noticed that after pressing the green "stop" button in the remote section it comes back green (running) again and the "disable" gets reverted right after that.
The log confirms that (see first two lines)

I also tried shutting down the whole instance and this leads to even more unpredictable behavior:
![grafik](https://user-images.githubusercontent.com/33332336/77599908-a364ca80-6f06-11ea-80e2-b9de8060bebe.png)
The LED device state gets altered many times (not consistent). Once it kept changing forever.

This instance uses the WS281x PWM device.
On my other instance using UDPRAW this does not occur

**Comment by Lord-Grey** [comment]
@TheAndi That is a known issue and addressed by #728

**Comment by brindosch** [comment]
Now available in 2.0.0-alpha.4
