### ISSUE TITLE
Swirl Effect does not work for certain setups / manually set hyperion.imageHeight()

### ISSUE THREAD

**Issue by TheAndi** [hyperion-project/hyperion.ng#743]
Recently I built a setup with just top and bottom LEDs and noticed that every effect using the swirl.py does not show up well. Rainbow looks like this:
![grafik](https://user-images.githubusercontent.com/33332336/77600680-e627a200-6f08-11ea-94d7-e61b6a9219cb.png)

As I don't have any side LEDs, the hyperion.imageHeight() probably is very small leading to this distortion. Is there any way to adjust the LED config (already tried a lot) to make it work anyway?

I think a good way to deal with such setups would be to give the user a way to enter the (in this case) vertical height manually.

Probably more effects using the hyperion.imageHeight() are affected.

(Running alpha3)

Would be great if there is a possibility to make it work!

**Comment by brindosch** [comment]
Wow, this looks amazing in slow motion for sure! Will look into it.

**Comment by brindosch** [comment]
I modified the width/height calculation to at least 50% pixel of each other. This keeps all colors visible (nearly). Is that sufficient?
![relaxed grid](https://user-images.githubusercontent.com/15967679/77708281-f6eb1d00-6fc7-11ea-89dc-563a11b21c10.gif)

**Comment by TheAndi** [comment]
Uhh, looks a lot better. Will this fix be in the next release?

Thanks a lot!

For the future an advanced setting for the height/width (of nonexistent pixels) could also be nice.
