### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion.ng#744]
## Feature request
A toggle to have a Dark-Mode would be nice

#### What problem does this feature solve?
My crying eyes at night
#### What does the proposed API look like?
none
#### How should this be implemented in your opinion?
With a toggle 
#### Are you willing to work on this yourself?
Nooo maybe @b1rdhous3 or @brindosch

**Comment by b1rdhous3** [comment]
Hatte ich mir schonmal angeschaut. Ist glaube aktuell mit der Struktur nicht ganz so einfach umgesetzt, aber dennoch möglich!

**Comment by tpmodding** [comment]
@b1rdhous3 schau mal ins forum, du hast ne nachricht :-P

**Comment by brindosch** [comment]
Vielleicht kann man ein vorbereitetes bootstrap3 verwenden für diesen Zeck und den Rest dann per Hand justieren. Wenn es sowas gibt.

**Comment by b1rdhous3** [comment]
Nach meinen Recherchen bietet bootstrap3 dafür schon einige Funktionen um es einfacher zu machen. 
Dann haben wir vor dem Dark Mode aber noch ein anderes Projekt ;)

**Comment by brindosch** [comment]
Der Nebel ist heute wieder sehr dicht.

**Comment by b1rdhous3** [comment]
Ich nehms zurück. Bootstrap 3 mit 4 verwechselt...

**Comment by brindosch** [comment]
Du kannst auch den bootstrap 3 zu 4 upgrade guide anschauen, ob man mit search & replace migrieren kann

**Comment by b1rdhous3** [comment]
Ich glaube das ist durch unsere bootstraps "addons" wohl eher ein größerer Aufwand, oder?

**Comment by brindosch** [comment]
Jsoneditor ist ganz gut strukturiert, die themes sind separiert. Colorpicker weiß ich nicht und die notifications kann man auch einfach komplett ersetzen, wenn nötig.

**Comment by b1rdhous3** [comment]
Soll der Dark Mode im Server eingestellt werden? Also für alle Geräte/Clients dann gleich?

Ich würde eher zu einem Cookie auf dem Client tendieren.
