### ISSUE TITLE
Only one JSON port for all Hyperion instances?

### ISSUE THREAD

**Issue by TheAndi** [hyperion-project/hyperion.ng#747]
I don't know if this is a bug or intentional.

I know the doc says it's only one port for all instances, but why?

How can I control my two instances remotely (with e.g. the app) if there is no separate port?
And how can the first instance be forwarded to the second one, when they use the same port?

Additionally, despite is saying it's one port for all instances, it saves two separate JSON ports.
When I set a port in instance 2, hit save, change to instance 1, it still shows its previous port.
Regarding the log, it always uses the port saved last.

**Comment by Danos0100** [comment]
At the moment, it is kinda both. The feature for forwarding between multiple instances run by the same Hyperion daemon is not yet implemented. Once you kill the daemon and restart it, you will see that all instances have the same port numbers again - these reflect your last change to the port numbers of any instance.

It would be very cool to see this feature coming soon by ‘simply’ converting the port settings to local instead of global settings. (I have no clue if this is an easy task though). Especially if you are using SJunkie’s Hue Entertainment implementation together with lights attached to your raspi.

This could probably be worked around by starting the Hyperion daemon twice with multiple users. However, the system throws off an error about hyperiond already running. Would any developer like to instruct us on how to run two instances of the daemon itself (with two different config db  files)?

**Comment by Danos0100** [comment]
What I also found out:

– The JSON server on port 19444 (default) is **only running for the first instance**, you can‘t control any other distance on this port (despite the WebUI stating that this is the JSON RPC Control for **all instances**

– the Boblight server is an exception to this global rule: You cannot set independent ports, but if I enter port 19333 for the first instance, the second one will use 19334 (console output: `[hyperiond BOBLIGHT] <WARNING> Port '19333' is already in use, will increment
[hyperiond BOBLIGHT] <WARNING> The requested Port '19333' was already in use, will use Port '19334' instead`). This message won‘t pop up for any other network services. And I‘ve verified that I can‘t control my second instance on JSON 19445.

– connecting to JSON using the Hyperion remote app on android only works if the app is already running and configured to the correct IP adress and port when you are starting the daemon. If you try to establish this connection later, it will throw this error: `QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is HyperionIManager(0x183e268) `

**Comment by Paulchen-Panther** [comment]
> – connecting to JSON using the Hyperion remote app on android only works if the app is already running and configured to the correct IP adress and port when you are starting the daemon. If you try to establish this connection later, it will throw this error: `QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is HyperionIManager(0x183e268)`

@brindosch 
Have you ever had the opportunity to look at what that is?

**Comment by TheAndi** [comment]
@Danos0100 Yes, that's exactly my problem. I have a second instance and no way of controlling it (other than WebUI). Neither forwarding nor hyperion remote app work because of this issue.
Would be great if this could be fixed/implemented soon.

**Comment by Cosmicbase** [comment]
Habe ebenfalls das Problem wenn ich Befehle über Ha-Bridge ausführe oder per Hyperion App crasht Hyperion. Musste leider von Alpha4 auf Alpha3 zurück das es wieder geht. Leider ist aber in Alpha4 das V4L2 width/height/fps nicht implementiert.

Bitte um Hilfe.

**Comment by Danos0100** [comment]
> Habe ebenfalls das Problem wenn ich Befehle über Ha-Bridge ausführe oder per Hyperion App crasht Hyperion. Hier tritt ein Fehler auf über Port 19444. Musste leider von Alpha4 auf Alpha3 zurück das es wieder geht. Leider ist aber in Alpha4 das V4L2 width/height/fps nicht implementiert.
> 
> Bitte um Hilfe.

Das gehört wahrscheinlich eher unter #751. Port 19444 ist standardmäßig JSON.

**Comment by Cosmicbase** [comment]
Danke für die Info.

**Comment by otbe** [comment]
Just to clarify this a little bit: right now there's no way to remote control all hyperion(ng) instances?
Background: I want to enable/disable all LEDDEVICEs via OpenHab binding. I guess thats what the forwarding would accomplish.

**Comment by Danos0100** [comment]
Right. Neither does the software apply JSON commands to all instances nor does it create additional JSON ports to control every instance on its own nor does forwarding work correctly.

**Comment by otbe** [comment]
Thanks for calrifaction. Until there's a proper solution Im gonna use a little script.

<details>
 <summary>Example script</summary>

```typescript
import * as WebSocket from 'ws';

const ws = new WebSocket('ws://ambilight:8090');

enum State {
  ON = 1,
  OFF = 0,
}

const instances = [0, 1];
const state = State.OFF;

ws.on('error', (e) => console.log(e));
ws.on('message', (e) => console.log(e));
ws.on('open', () => {
  for (const instance of instances) {
    ws.send(
      JSON.stringify({
        command: 'instance',
        tan: 2,
        subcommand: 'switchTo',
        instance,
      })
    );

    ws.send(
      JSON.stringify({
        command: 'componentstate',
        tan: 2,
        componentstate: { component: 'LEDDEVICE', state: !!state },
      })
    );
  }

  ws.close();
});

```
</details>

**Comment by brindosch** [comment]
> When I set a port in instance 2, hit save, change to instance 1, it still shows its previous port.

This is likely a visual bug. If you reload the page it should be correct

> How can I control my two instances remotely (with e.g. the app) if there is no separate port?

There is some inconsistency how the api can be used, and the default behaviour is _unexpected_ in some way. The script of @otbe shows that exactly. We currently have no _apps_ (source code) for Android/iOS. While everyone believes we have :)

**Comment by TheAndi** [comment]
> We currently have no apps (source code) for Android/iOS. While everyone believes we have :)

I think there are no necessary changes for the apps to make anyway, as they still function fine with hyperion.ng (tested with the android app and most of the hyperion.ng-alphas).
A separate JSON Port for each instance would make the app work for all instances and should also allow forwarding.

**Comment by tpmodding** [comment]
https://github.com/hyperion-project/hyperion.ng/issues/809

will close this
