### ISSUE TITLE
Alpha.4 - usbtv007 wrong video format?

### ISSUE THREAD

**Issue by T-IOOO** [hyperion-project/hyperion.ng#749]
Running alpha.4. Grabber only shows b/w colors, I am unable to set video standard (nothing happens)

I recently bought the nsendato HDMI-USB and it was working flawlessly with alpha.3

**Comment by Paulchen-Panther** [comment]
OS? Hardware? etc. p.p.

**Comment by T-IOOO** [comment]
Rasbian Buster Lite on Rpi0 W,
Fushicai usbtv007

**Comment by Paulchen-Panther** [comment]
Compiled by yourself?

**Comment by T-IOOO** [comment]
yes!

**Comment by Paulchen-Panther** [comment]
will test it as soon as possible

**Comment by Paulchen-Panther** [comment]
One more question. How did you compile?

**Comment by T-IOOO** [comment]
I usually remove ”hyperion” folder first. Then I do it the ”manual” way, not the automatic method. Since I am a beginner I would appreciate an update tutorial for hyperion.

**Comment by Paulchen-Panther** [comment]
Could you please try the automatically created release on GitHub?

**Comment by HyperFann** [comment]
Same thing for me, alpha 4 armv6 on rpi1 installed flawlessly from you .deb.

Alpha 3 had colors and alpha 4 black&white
My USB grabber is a direct usb2hdmi

**Comment by hennors** [comment]
Raspberry Pi 3 Model B Rev 1.2
Syntek Semiconductor Co., Ltd STK1160 Video Capture Device
Hyperion-2.0.0-alpha.4-Linux-armv7hf-rpi + self compile
same issue

**Comment by Paulchen-Panther** [comment]
Mit meinem HDMI to USB Converter habe ich keine Probleme.
https://prnt.sc/roheyo

**Comment by pierrebuet** [comment]
I have the same issue here, using an HDMI to USB Grabber (usbtv007). If I stop the instance, set the standard for the controller (v4l2-ctl --set-standard 0x000000ff) and restart the instance, I have color.
@Paulchen-Panther : Welche HDMI to USB Converter benutzt Du bitte?

**Comment by T-IOOO** [comment]
I just tested your suggestion (set standard) and I got the color back.
But hyperion seems very ”heavy” and after a while stops working.

**Comment by Paulchen-Panther** [comment]
Fix is online at PR #753 

> But hyperion seems very ”heavy” and after a while stops working.

What does the Hyperion console log say?

**Comment by T-IOOO** [comment]
I reverted back to alpha.3 earlier today and now i updated to alpha.4 again and color is

I used the wget command to download the
