### ISSUE TITLE
Alpha 4 Crashes with Deadlock

### ISSUE THREAD

**Issue by flexage** [hyperion-project/hyperion.ng#751]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After upgrading Alpha 3 to Alpha 4, Hyperion starts and then crashes due to a deadlock after a few seconds.

The startup animation plays, and then I get a few seconds of the led strips lighting up with the selected source, then Hyperion freezes.

I get this in the log:

```
Mar 29 04:16:56 raspberrypi systemd[1]: Started Hyperion ambient light systemd service  for user pi.
Mar 29 04:17:23 raspberrypi hyperiond[698]: QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is HyperionIManager(0xeeb238)
```

#### Steps to reproduce

- Upgraded from Hyperion NG Alpha 3 to Alpha 4
- Started Hyperion
- CRASH!

#### What is expected?

Hyperion to stay running.

#### What is actually happening?

Hyperion is crashing with the above error log.

#### System

Managed to grab the system info in the few seconds before Hyperion crashes.

Hyperion Server: 
- Build:       (HEAD detached at 731b517b) (brindosch-80f7da4d/731b517b-1585347672)
- Build time:  Mar 28 2020 12:26:41
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.4
- UI Lang:     auto (BrowserLang: en-GB)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by Danos0100** [comment]
A side note from #747 (which doesn‘t have to do that much with the actual problem 747 I guess):

connecting to JSON using the Hyperion remote app on android only works if the app is already running and configured to the correct IP adress and port when you are starting the daemon. If you try to establish this connection later, it will throw this error: `QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is HyperionIManager(0x183e268)`

The Hex error code appears to be random, it changes each time I replicate the error.

**Comment by Cosmicbase** [comment]
@brindosch Hast du ein Plan wann ein PR kommt?
Thx

**Comment by brindosch** [comment]
I hope tomorrow.

**Comment by Cosmicbase** [comment]
> I hope tomorrow.

Wow I think then should solve the problem with port 19444 and I can finally adjust the resolution of my digital grabber with the newer PR. I need the Port 19444 for HA Bridge also. 
I'm very happy for a quick Solution. :-)

**Comment by dws199** [comment]
I have the same issues with this version too, I'm not able to connect from HA and am also see the deadlock error.  Looking forward to the fix as it's a great application :-)

**Comment by deisi** [comment]
One up

**Comment by Cosmicbase** [comment]
> I hope tomorrow.

Sorry für die Aufdringlichkeit...
Gibts ein Zeitplan wann der Fix kommt?
Danke dir und Hut ab für deine (eure) Arbeit!

**Comment by tpmodding** [comment]
2 down, we all know that there is a bug...
everyone also all knows that the devs are coding in there free time
everyone also knows that there is eastern a the weather is good
so everyone should wait...

fix will come when everything is fixed and the devs choose to release a new version....there a few more things they want to add and merge in a new version....

please be patient everyone...!

**Comment by Paulchen-Panther** [comment]
should be fixed with [alpha 5](https://github.com/hyperion-project/hyperion.ng/releases/tag/2.0.0-alpha.5)

**Comment by flexage** [comment]
Alpha 5 worked for me! Thanks, excellent work!
