### ISSUE TITLE
USB Capture only in Black and white

### ISSUE THREAD

**Issue by DanielL99** [hyperion-project/hyperion.ng#754]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion shows and processes a black and white picture from my Fushicai USBTV007
But after running `mplayer tv:// -tv device=/dev/video0` it shows and processes a normal colored Image

#### Steps to reproduce
Run an USB Capture in Hyperion with a Fushicai USBTV007 on a RasPi 3 with Raspbian Buster Lite

#### What is expected?
Processing of a colored Image
![After](https://user-images.githubusercontent.com/17531095/77849626-67af5680-71cd-11ea-9ca3-901452698825.png)

#### What is actually happening?
Processing of a black and white Image
![Before](https://user-images.githubusercontent.com/17531095/77849629-6c740a80-71cd-11ea-9157-89e57af144eb.png)

#### System

Hyperion Server: 
- Build:       master (GitHub-f1b8023/20a5e5d-1585321722)
- Build time:  Mar 27 2020 16:02:47
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.3
- UI Lang:     en (BrowserLang: en)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Fix is online at PR #753

**Comment by DanielL99** [comment]
Okay, thanks

**Comment by mazafra1** [comment]
> Fix is online at PR #753

Can this fix be tested?

**Comment by Paulchen-Panther** [comment]
Yes. Finished artifacts can be tested at:
https://github.com/hyperion-project/hyperion.ng/actions/runs/67531542
(When all platforms have compiled)

**Comment by Paulchen-Panther** [comment]
@mazafra1 
If you test it, could you give feedback?

**Comment by DanielL99** [comment]
> @mazafra1
> If you test it, could you give feedback?

Do I copy it into /usr?

**Comment by Paulchen-Panther** [comment]
1. unzip the artifact
2. extract the tar.gz
3. run "hyperiond -d" from extracted share/hyperion/bin

**Comment by DanielL99** [comment]
It works fine
Thank you @Paulchen-Panther

**Comment by mazafra1** [comment]
> @mazafra1
> If you test it, could you give feedback?

No changes on my side, but, please be aware, this is a brand new video grabber (UTV007) so I don't know if it's ever worked correctly. Actually is getting b&w screenshots with both Hyperion and Hyperion.ng.

I'm connecting it directly to RPi4 without an active usb hub, could it be a power problem? Any other checks I may need to do?

Thanks.

**Comment by Thinner77** [comment]
@mazafra1
Maybe your grabber is configured to output NTSC video standard by default.
Post output of:
v4l2-ctl -d /dev/video0 --all --verbose
v4l2-ctl -d /dev/video0 --list-standards --verbose
v4l2-ctl -d /dev/video0 --set-standard=pal --verbose
wbr

**Comment by mazafra1** [comment]
Thanks for your time @Thinner77 

```
v4l2-ctl -d /dev/video0 --all --verbose
VIDIOC_QUERYCAP: ok
Driver Info:
        Driver name      : usbtv
        Card type        : usbtv
        Bus info         : usb-0000:01:00.0-1.3
        Driver version   : 4.19.97
        Capabilities     : 0x85200001
                Video Capture
                Read/Write
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x05200001
                Video Capture
                Read/Write
                Streaming
                Extended Pix Format
Priority: 2
Video input : 0 (Composite: ok)
Video Standard = 0x000000ff
        PAL-B/B1/G/H/I/D/D1/K
Format Video Capture:
        Width/Height      : 720/576
        Pixel Format      : 'YUYV' (YUYV 4:2:2)
        Field             : Interlaced
        Bytes per Line    : 1440
        Size Image        : 829440
        Colorspace        : SMPTE 170M
        Transfer Function : Default (maps to Rec. 709)
        YCbCr/HSV Encoding: Default (maps to ITU-R 601)
        Quantization      : Default (maps to Limited Range)
        Flags             : 
Streaming Parameters Video Capture:
        Frames per second: 25.000 (25/1)
        Read buffers     : 2

User Controls
                     brightness 0x00980900 (int)    : min=0 max=1023 step=1 default=448 value=448 flags=slider
                       contrast 0x00980901 (int)    : min=0 max=1023 step=1 default=464 value=464 flags=slider
                     saturation 0x00980902 (int)    : min=0 max=1023 step=1 default=512 value=512 flags=slider
                            hue 0x00980903 (int)    : min=-3583 max=3583 step=1 default=0 value=0 flags=slider
                      sharpness 0x0098091b (int)    : min=0 max=255 step=1 default=96 value=96 flags=slider
```

```
v4l2-ctl -d /dev/video0 --list-standards --verbose
VIDIOC_QUERYCAP: ok
ioctl: VIDIOC_ENUMSTD
        Index       : 0
        ID          : 0x000000000000B000
        Name        : NTSC
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 1
        ID          : 0x0000000000001000
        Name        : NTSC-M
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 2
        ID          : 0x0000000000002000
        Name        : NTSC-M-JP
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 3
        ID          : 0x0000000000008000
        Name        : NTSC-M-KR
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 4
        ID          : 0x0000000000004000
        Name        : NTSC-443
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 5
        ID          : 0x00000000000000FF
        Name        : PAL
        Frame period: 1/25
        Frame lines : 625

        Index       : 6
        ID          : 0x0000000000000007
        Name        : PAL-BG
        Frame period: 1/25
        Frame lines : 625

        Index       : 7
        ID          : 0x0000000000000008
        Name        : PAL-H
        Frame period: 1/25
        Frame lines : 625

        Index       : 8
        ID          : 0x0000000000000010
        Name        : PAL-I
        Frame period: 1/25
        Frame lines : 625

        Index       : 9
        ID          : 0x00000000000000E0
        Name        : PAL-DK
        Frame period: 1/25
        Frame lines : 625

        Index       : 10
        ID          : 0x0000000000000100
        Name        : PAL-M
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 11
        ID          : 0x0000000000000800
        Name        : PAL-60
        Frame period: 1001/30000
        Frame lines : 525

        Index       : 12
        ID          : 0x0000000000FF0000
        Name        : SECAM
        Frame period: 1/25
        Frame lines : 625

        Index       : 13
        ID          : 0x0000000000010000
        Name        : SECAM-B
        Frame period: 1/25
        Frame lines : 625

        Index       : 14
        ID          : 0x0000000000040000
        Name        : SECAM-G
        Frame period: 1/25
        Frame lines : 625

        Index       : 15
        ID          : 0x0000000000080000
        Name        : SECAM-H
        Frame period: 1/25
        Frame lines : 625

        Index       : 16
        ID          : 0x0000000000320000
        Name        : SECAM-DK
        Frame period: 1/25
        Frame lines : 625

        Index       : 17
        ID          : 0x0000000000400000
        Name        : SECAM-L
        Frame period: 1/25
        Frame lines : 625

        Index       : 18
        ID          : 0x0000000000800000
        Name        : SECAM-Lc
        Frame period: 1/25
        Frame lines : 625
```

```
v4l2-ctl -d /dev/video0 --set-standard=pal --verbose
VIDIOC_QUERYCAP: ok
VIDIOC_S_STD: ok
Standard set to 000000ff
```

**Comment by Thinner77** [comment]
@mazafra1
OK, thanks, looks good, PAL was/is set. For hyperion.ng go to WebUI, Configuration, Capture Hardware and try setting video standard to no-change/auto or select PAL, try both.
wbr

**Comment by mazafra1** [comment]
> @mazafra1
> OK, thanks, looks good, PAL was/is set. For hyperion.ng go to WebUI, Configuration, Capture Hardware and try setting video standard to no-change/auto or select PAL, try both.
> wbr

Thanks. About that I do need to start hyperiond and open what URL (http://<rpi_ip>:8090 doesn't work for me)?

Besides, in to make the daemon work, do I need to store hyperion.config.json somewhere?

Sorry for such obvious questions, first contact with hyperion here.

**Comment by Thinner77** [comment]
You can use the LED Visualization; little TV symbol on upper right corner in WebUI to test your settings.
wbr

**Comment by mazafra1** [comment]
Do you think this is good enough? Now it's more coloured than before, indeed.

<img width="552" alt="Screenshot 2020-04-01 at 15 58 07" src="https://user-images.githubusercontent.com/31898896/78145859-b3fad080-7431-11ea-87e1-b9976d5a6cd3.png">

**Comment by Thinner77** [comment]
Weird, it still looks like NTSC. Have you tried selecting NTSC in WebUI?
Which TV standard (SECAM, PAL, NTSC ) is used in Spain?
wbr

**Comment by mazafra1** [comment]
> Weird, it still looks like NTSC. Have you tried selecting NTSC in WebUI?
> Which TV standard (SECAM, PAL, NTSC ) is used in Spain?
> wbr

In Spain, actually almost whole EU, PAL is the standard.

I did your test and tried PAL, NTSC and SECAM, and I got still bad results.

I tried also to set the physical switch on the HDMI2AV converter to NTSC and v4l2 is not even able to grab a screenshot.

**Comment by Thinner77** [comment]
OK, thanks for your input.

To narrow down the problem please install package qv4l2 on RPi, it's a graphical V4L2 test utility.

Select composite input and tv standard NTSC, then use play button to open preview window. If you switch between PAL/NTSC on HDMI2AV adapter you should see wrong colors on PAL and good ones on NTSC. Then close window, select PAL and reopen preview window. If switch on adapter is set to PAL you should see good colors, if set to NTSC output should be black or freezed (see framecounter in lower left corner). This is how it behaves in my setup. And please use external power supply to HDMI2AV adapter if possible.

wbr

**Comment by mazafra1** [comment]
Wow!! This is just amazing.... If software and hardware are configured in NTSC, everything WORKS JUST FINE!!!

But if I configured everything to PAL or crossed, I got wrong image. How is this even possible?

Thanks for your time and support @Thinner77 
<img width="933" alt="Screenshot 2020-04-02 at 15 58 03" src="https://user-images.githubusercontent.com/31898896/78258467-98f49300-74fb-11ea-876f-dd0072454ac9.png">
<img width="721" alt="Screenshot 2020-04-02 at 15 56 29" src="https://user-images.githubusercontent.com/31898896/78258478-9bef8380-74fb-11ea-98e1-8e18868a7536.png">

**Comment by Thinner77** [comment]
Is this an acceptable solution for you?

If not you should check HDMI2AV adapter first, some are crap, see "Mini HDMI2AV converter DOA. Typical crap from china. FIXED" and "Another defective HDMI2AV adapter" on YT. Check if it really outputs PAL by connecting it to a TV with AV input. TV should tell you if PAL or NTSC is incoming, maybe by overlay or somewhere in settings menu, maybe you can force TV how to handle input. To check grabber feed in a signal from DVD player or something else with AV output or use scart2AV adapter. Be creative, good luck.

wbr

**Comment by mazafra1** [comment]
Maybe I was too quick to answer that it's working. Today it's not working anymore independently of the configuration I set. I tried 2 differents HDMI2AV adapters with identical results: black or almost black screen.

HDMI2AV adapter is usb-powered (it doesn't work without)and LEDs are not connected to RPi and powered by different DC source, but do you think this issue could be related to RPi [lack of enough] power??

Thanks again,

**Comment by Thinner77** [comment]
Hi, as this is no longer related to this bugfix, you should post your problem in the forum, i'm sure there are experienced users who can help. Thanks.
wbr

**Comment by joselcaguilar** [comment]
Hi, I'm testing from EU too just like @mazafra1 and using PAL format day after day.
I built from source for RPi armv7hf (commit 133399c6b6b5a4b01161755a32ec7610b3a12ca6) and it works as expected, however the problem described here, raised again with Alpha 0.0.4 release.

The workaround for me is set NTSC instead of PAL in Hyperion as well as HDMI2AV.

Thx to the Hyperion Team for check this and your great work for everyone!

**Comment by mazafra1** [comment]
@joselcaguilar Could you share your artifacts, please?

**Comment by joselcaguilar** [comment]
@mazafra1 I can't attach it because the bits are too big.

You can try to build it directly modifying docker-compile.sh:
`git clone --recursive --depth 6 -q $GIT_REPO_URL $SCRIPT_PATH/hyperion || { echo "---> Failed to download Hyperion source code! Abort"; exit 1; }
git checkout 133399c6b6b5a4b01161755a32ec7610b3a12ca6
`

**Comment by joselcaguilar** [comment]
The [artifact for RPi buster armv7hf](https://gofile.io/?c=xHXXfn) from commit 133399c6b6b5a4b01161755a32ec7610b3a12ca6 uploaded, hope it helps @mazafra1 

In my opinion something is wrong in 662872dafebc271a1d6dbff7dd850fea9c3c1527

**Comment by mazafra1** [comment]
Thanks a lot @joselcaguilar !!
Though I had to give up with my current video grabber (I have 2 new ones in delivery for next week) since I believe it's broken or it got misconfigured somehow. It's not working anymore even if it worked ONCE at the beginning thanks to @Thinner77 .

Guys, do you know of any possible way of resetting the device to its factory defaults?

**Comment by gijsje** [comment]
> Yes. Finished artifacts can be tested at:
> https://github.com/hyperion-project/hyperion.ng/actions/runs/67531542
> (When all platforms have compiled)

Will there be a alpha 5 release soon with this fix?

**Comment by joselcaguilar** [comment]
> Thanks a lot @joselcaguilar !!
> Though I had to give up with my current video grabber (I have 2 new ones in delivery for next week) since I believe it's broken or it got misconfigured somehow. It's not working anymore even if it worked ONCE at the beginning thanks to @Thinner77 .
> 
> Guys, do you know of any possible way of resetting the device to its factory defaults?
> 
> _Edited_: Jose, what's your output for `v4l2-ctl --list-formats-ext` ?

Using my own build from last commit 52e7f04e46206c693351fca7c52859e11b920585:
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture
        [0]: 'YUYV' (YUYV 4:2:2)

**Comment by Paulchen-Panther** [comment]
> Will there be a alpha 5 release soon with this fix?

Yes
