### ISSUE TITLE
make documention warningless

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.ng#76]
The doxygen doc generate lots of (approx.800) warnings. This should be fixed in the long run.

you can generate the doc with:
`make doc`
and you will find the doc in build/doc/html.

**Comment by brindosch** [comment]
Regarding warnings. As you see  at travis, cmake throws during configuration  a lot if errors that are no longer suppressed with wno dev

**Comment by redPanther** [comment]
difference is, doxygen warnings are more errors than warnings. They say where your source code has bad documentation.

cmake warnings in travis build: There is only one cmake warning on solved, therefore I've made a PR:  https://github.com/tvdzwan/protobuf/pull/1
but @tvdzwan are to busy. Can we clone the protobuffer and then we make a fix in our repo? 
The others has to be fixed by time.

travis build to show errors/warnings and not working tests :-) if all is everytime warningless and green, it's boring ;-)

**Comment by brindosch** [comment]
I will ask for a protobuffer move to hyperion-project. So we have better access

**Comment by redPanther** [comment]
:+1:

**Comment by brindosch** [comment]
protobuf is now in our scope :)

**Comment by redPanther** [comment]
I delay that ... I have it onto my todo list. But I clode this so we can focus on other things
