### ISSUE TITLE
Hyperion.NG 9.2.103 in CoreElec 9.2.2 Protocol Buffers Server does not work

### ISSUE THREAD

**Issue by bylderup** [hyperion-project/hyperion.ng#768]
New Version work fine with local grabbing.
But with Signal from Hyperion Android Grabber via Port 19445 no function anymore.

Had to go back to Hyperion.NG 9.2.101

**Comment by Rickexe** [comment]
Hi, 

I already had issues with hyperion.ng 103 on elec 9.2.1. The hyperion control addon is not working with it either.

**Comment by DrBlokmeister** [comment]
It's also not working for me anymore. How can I roll back the addon as a work-around?

**Comment by tpmodding** [comment]
Sorry but we dont provide the hyperion addon on coreelec, it is based on our code, but provided from the coreelec team...you can ask at there forum, may they can help you

or @Portisch can help us?

**Comment by Portisch** [comment]
Change the priority in the App to be between 100-199, then it's working again.

**Comment by heikomat** [comment]
Thank you @Portisch, that worked for me!
