### ISSUE TITLE
Hyperion and DiyHue Bridge

### ISSUE THREAD

**Issue by BTopbas** [hyperion-project/hyperion.ng#769]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I am using DiyHue Virtual Hue Bridge. I am successfully discovery this fake bridge with my iPhone hue apps, and Philips Ambilight TVs. But in Hyperion this bridge not found. I write bridge IP also nothing happening. 

Here is DiyHue Bridge: https://diyhue.org/

PS: I know the build is not original. But I first try the latest original build. Original build can't find a bridge. After that, I compile SJunkies build. So the same system and same happens.

PS2: Yes. I have Philips Ambilight Tv and I am still using ws2812b's strips in my Ambilight tv with android grabber. Maybe this is a most stupid thing but I love Hyperion more than Ambilight.

#### Steps to reproduce
Connect Hue Bridge.

#### What is expected?
Successfully discovery and connect to hue bridge.

#### What is actually happening?
Not discovery Hue Bridge.

#### System

Hyperion Server: 
- Build:       entertainment-api-2020 (SJunkies-e53b42d5/cc39649f-1586967374)
- Build time:  Apr 15 2020 21:41:55
- Git Remote:  https://github.com/SJunkies/hyperion.ng.git
- Version:     2.0.0-alpha.4
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.93+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537

**Comment by tpmodding** [comment]
Did you also tested this PR https://github.com/hyperion-project/hyperion.ng/pull/592 ?

**Comment by SJunkies** [comment]
@tpmodding 
the entertainment-api-2020 branch is currently the same as the entertainment-api-2019 branch.
I will look into this problem!

**Comment by BTopbas** [comment]
@SJunkies if you need any info or debug messages I am here. Today I am successfully connected hue bridge with Hyperion! But without a wizard. I added an IP address and username manually.
![hyperion](https://user-images.githubusercontent.com/6390054/79584846-9f783280-80d7-11ea-99a9-9376ec979efa.jpg)

I have used Hue essentials app for extract username. And copy username. After that connect is successfully. Wizard still no response.

![Screen Shot 2020-04-17 at 17 58 56](https://user-images.githubusercontent.com/6390054/79585014-dcdcc000-80d7-11ea-8cc1-13668704a9fc.png)

I used local IP because Hue emulator installed the same device with Hyperion. So now no problem. I can control lights with Hyperion. I edited config.json manually. Philips Hue Wizard is still not working.

**Comment by SJunkies** [comment]
@BTopbas 
thanks for your input!
the bridge discovery inside the wizard works currently only with [https://discovery.meethue.com](https://discovery.meethue.com) website. If no data is available over this URL, manually typed in bridge IP is needed.
Use Target-IP: 192.168.2.5 like on your devices screenshot and restart the wizard.
If the bridge is found, you can create a new user inside the wizard and configure your lights.
All updates within the Hue Bridge/Lights/Wizard etc. currently available inside the #592.
for this PR:
I will try to add bridge discovery through SSDP later...
To use the entertainment API, an entertainment group is required, which must first be created with one of the Hue apps.

**Comment by SJunkies** [comment]
are you sure, that your username is correct?
Do you get response from API, when u open the url inside a browser:
http://BRIDGEIP/api/USERNAME/

I think the existing usernames cannot be accessed in readable format through the REST API...

**Comment by Lord-Grey** [comment]
@SJunkies The Username is OK.
It is the wizard.js that has problems. If you use the previous version the wizard works. With the latest version, one cannot proceed beyond the assistant's intro screen.

If you look at the console output you will find:

```
ReferenceError: ev is not definedwizard.js:784:13
    beginWizardHue http://localhost:8090/js/wizard.js:784
    startWizardPhilipsHue http://localhost:8090/js/wizard.js:602
    jQuery 2
```

Hoping that ring-fences the issue.

**Comment by Lord-Grey** [comment]
@SJunkies In addition, the configuration item "Log all Hue commands" is only available, if  Entertainment API is selected. It should be available for classic API, too. Pleasae remove that dependency in the definition file.

**Comment by SJunkies** [comment]
> @SJunkies The Username is OK.
> It is the wizard.js that has problems. If you use the previous version the wizard works. With the latest version, one cannot proceed beyond the assistant's intro screen.
> 
> If you look at the console output you will find:
> 
> ```
> ReferenceError: ev is not definedwizard.js:784:13
>     beginWizardHue http://localhost:8090/js/wizard.js:784
>     startWizardPhilipsHue http://localhost:8090/js/wizard.js:602
>     jQuery 2
> ```
> 
> Hoping that ring-fences the issue.

Thanks for this!
my editor wasn't case sensitive, while i did the last changes with  search / replace 🤦 
Fix coming soon. Sorry for that :/

**Comment by BTopbas** [comment]
> are you sure, that your username is correct?
> Do you get response from API, when u open the url inside a browser:
> http://BRIDGEIP/api/USERNAME/
> 
> I think the existing usernames cannot be accessed in readable format through the REST API...but maybe i’m wrong!?

Yes I get response. Here is output.

`{"lights":{"1":{"capabilities":{"certified":true,"control":{"colorgamut":[[0.704,0.296],[0.2151,0.7106],[0.138,0.08]],"colorgamuttype":"A","maxlumen":200,"mindimlevel":10000},"streaming":{"proxy":false,"renderer":true}},"manufacturername":"Philips","modelid":"LST002","name":"Hue WS2812 strip 1","state":{"alert":"none","bri":35,"colormode":"xy","ct":200,"effect":"none","hue":62536,"mode":"homeautomation","on":false,"reachable":false,"sat":254,"transitiontime":1,"xy":[0.6716,0.2986]},"swversion":"5.127.1.26581","type":"Color light","uniqueid":"00:17:88:01:00:6b:0d:99-0b","productname":"Hue lightstrip plus","config":{"archetype":"huelightstrip","function":"mixed","direction":"omnidirectional","startup":{"mode":"safety","configured":false}}}},"groups":{"1":{"action":{"on":false,"bri":35,"ct":200,"hue":62536,"sat":254,"xy":[0.6716,0.2986]},"class":"Living room","lights":["1"],"name":"ArtFunSex","state":{"any_on":false,"all_on":false},"type":"Room","sensors":[]}},"config":{"Hue Essentials key":"e79aa50e7f5e11eab069d076580a5c5f","Remote API enabled":false,"UTC":"2020-04-18T15:09:16","apiversion":"1.35.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"D07658FFFE0A5C5F","datastoreversion":"70","dhcp":true,"factorynew":false,"gateway":"192.168.2.1","internetservices":{"internet":"connected","remoteaccess":"connected","swupdate":"connected","time":"connected"},"ipaddress":"192.168.2.5","linkbutton":false,"localtime":"2020-04-18T15:09:16","mac":"d0:76:58:0a:5c:5f","modelid":"BSB002","name":"Philips hue","netmask":"255.255.255.0","portalconnection":"connected","portalservices":true,"portalstate":{"communication":"disconnected","incoming":false,"outgoing":true,"signedon":true},"proxyaddress":"none","proxyport":0,"replacesbridgeid":null,"starterkitid":"","swupdate":{"checkforupdate":false,"devicetypes":{"bridge":false,"lights":[],"sensors":[]},"notify":true,"text":"","updatestate":0,"url":""},"swupdate2":{"autoinstall":{"on":true}},"swversion":"1937113020","timezone":"Europe/Bucharest","whitelist":{"6eb521447f6011eabe57d076580a5c5f":{"create date":"2020-04-15T21:31:13","last use date":"2020-04-17T22:51:03","name":"Hue 3#Batuhan’s iPhone"},"hueessde7f6011eabc2ad076580a5c5f":{"create date":"2020-04-15T21:33:18","last use date":"2020-04-18T15:09:16","name":"Hue Essentials#iPhone"},"web-ui-7589":{"create date":"2020-04-15T21:20:25","last use date":"2020-04-16T07:54:36","name":"WebGui User"}},"zigbeechannel":25},"scenes":{"1":{"appdata":{"data":"eSRpL_r01_d01","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Relax","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"10":{"appdata":{"data":"GBHmN_r01_d17","version":1},"group":"1","lastupdated":"2020-04-17T16:14:15","locked":false,"name":"Arctic aurora","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"11":{"appdata":{"data":"T2XBZ_r01_d18","version":1},"group":"1","lastupdated":"2020-04-17T16:14:15","locked":false,"name":"Spring blossom","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"2":{"appdata":{"data":"pdYu4_r01_d02","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Read","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"3":{"appdata":{"data":"aXyQZ_r01_d03","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Concentrate","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"4":{"appdata":{"data":"4Atfe_r01_d04","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Energize","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"5":{"appdata":{"data":"5Isqm_r01_d05","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Bright","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"6":{"appdata":{"data":"llvRj_r01_d06","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Dimmed","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"7":{"appdata":{"data":"wBiA6_r01_d07","version":1},"group":"1","lastupdated":"2020-04-17T16:14:14","locked":false,"name":"Nightlight","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"8":{"appdata":{"data":"yCrKo_r01_d15","version":1},"group":"1","lastupdated":"2020-04-17T16:14:15","locked":false,"name":"Savanna sunset","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]},"9":{"appdata":{"data":"wtJrd_r01_d16","version":1},"group":"1","lastupdated":"2020-04-17T16:14:15","locked":false,"name":"Tropical twilight","owner":"6eb521447f6011eabe57d076580a5c5f","picture":"","recycle":false,"type":"GroupScene","version":2,"lights":["1"]}},"schedules":{},"rules":{},"sensors":{"1":{"config":{"configured":false,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"daylight":null,"lastupdated":"none"},"swversion":"1.0","type":"Daylight"}},"resourcelinks":{}}`

**Comment by Lord-Grey** [comment]
@BTopbas @SJunkies already fixed the issue. You may want to try his latest code base.

**Comment by SJunkies** [comment]
@BTopbas 

> @SJunkies Yes I get response. Here is output.

thanks for testing!

I could setup the DIYHue with Docker and found the current problem inside the wizard.
The DIYHue bridge, don't behave like a original Philips Hue bridge!
The REST API call: http://BRIDGEIP/api/ don't work and result in a 404, but thats the base to identify a Hue bridge with the wizard, because the original bridge return a json information over that URL.

@all
I'm currently trying some workarounds, but for security reasons, it would be best if someone else could insert a hyperion command with "sendToHyperion" over the API to execute an SSPD search with SSDPDiscover Class and return the results to the frontend.
This would also be the best way to remove internet dependencies from the https://discovery.meethue.com URL to work on offline networks as well.

**Comment by Lord-Grey** [comment]
@SJunkies I have the same need for the Yeelight ssdp discovery. Plus some additional tweaks as Yeelight has some proprietary stuff. I will have a Look when I have the lights basics working.

**Comment by Lord-Grey** [comment]
@sjunkies I manged to get the diyHue bridge running and via a RESTClient I managed also to get a username and clientkey.
Then I created and Entertainment Group with one light and activated streaming.

The I started hyperion with the right parameters, but the device goes into error "Bridge response is not Valid'".

If I look at the bridge's response. It is a valid Success message.
Looks like there is an issue, if the stream is active, you try to disable it...

Please find the log details below:

```
hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:358:log()> Entertainment Group found     : [4] 
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:358:log()> Lights in Group               : 1
[hyperiond LEDDEVICE] <INFO> Entertainment Group [4] "" with 1 Lights found
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:358:log()> Light-IDs configured          : 1
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:358:log()> Light-IDs                     : 1
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:744:PhilipsHueLight()> Recognized model id LCT001 of light ID 1 as gamut B
[hyperiond LEDDEVICE] <INFO> Light ID 1 ("Hue Lamp 1", LED index "0") created
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Streamer Debug            : yes
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL DebugLevel                : [4] Verbose
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Servername                : Hue
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Host                      : 192.168.2.152
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Port                      : 2100
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> PSK                           : 321c0c2ebfa7361e55491095b2f5f9db
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> PSK-Identity                  : 2bd7034a81ab11eab438000c29d8d52d
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Transport Type            : DTLS
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Seed Custom               : dtls_client
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Retry Left                : 5
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Read Timeout              : 0
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Handshake Timeout min     : 400
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Handshake Timeout max     : 1000
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Handshake attempts        : 5
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:91:init()> Successfully parsed 192.168.2.152 as an ip address.
[hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:122:init()> UDP SSL using 192.168.2.152:2100
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:563:getJson()> GET: [http://192.168.2.152:80/api/2bd7034a81ab11eab438000c29d8d52d/groups/4]
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> LED device: enabled
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:613:handleReply()> Reply.httpStatusCode [200]
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:630:handleReply()> Reply: [{"action":{"bri":221,"ct":0,"hue":10105,"on":false,"sat":254,"xy":[0.4356,0.4967]},"class":"TV","lights":["1"],"locations":{"1":[0,0.7,0]},"state":{"all_on":false,"any_on":false},"stream":{"active":true,"owner":"2bd7034a81ab11eab438000c29d8d52d","proxymode":"auto","proxynode":"/bridge"},"type":"Entertainment"}]
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:1144:initStream()> Group: "" [4] is in use, try to stop stream
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:587:putJson()> PUT: [http://192.168.2.152:80/api/2bd7034a81ab11eab438000c29d8d52d/groups/4] [{"stream":{"active":false}}]
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:613:handleReply()> Reply.httpStatusCode [200]
[hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:630:handleReply()> Reply: [[{"success":{"/groups/4/stream":{"active":false}}}]]
[hyperiond LEDDEVICE] <ERROR> Device disabled, device 'philipshue' signals error: 'set stream to false: Bridge response is not Valid'
[hyperiond LEDDEVICE] <ERROR> Group: "" [4] couldn't stop by user: "2bd7034a81ab11eab438000c29d8d52d" - Entertainment API not usable[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> LED device: disabled




```

If I set the entertainment group to {"stream":{"active":false}} before starting, the same error occurs:

> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Streamer Debug            : yes
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL DebugLevel                : [4] Verbose
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Servername                : Hue
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Host                      : 192.168.2.152
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Port                      : 2100
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> PSK                           : 321c0c2ebfa7361e55491095b2f5f9db
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> PSK-Identity                  : 2bd7034a81ab11eab438000c29d8d52d
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Transport Type            : DTLS
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Seed Custom               : dtls_client
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Retry Left                : 5
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Read Timeout              : 0
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Handshake Timeout min     : 400
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Handshake Timeout max     : 1000
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:183:configLog()> SSL Handshake attempts        : 5
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:91:init()> Successfully parsed 192.168.2.152 as an ip address.
> [hyperiond LEDDEVICE] <DEBUG> <ProviderUdpSSL.cpp:122:init()> UDP SSL using 192.168.2.152:2100
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:563:getJson()> GET: [http://192.168.2.152:80/api/2bd7034a81ab11eab438000c29d8d52d/groups/4]
> [hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> LED device: enabled
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:613:handleReply()> Reply.httpStatusCode [200]
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:630:handleReply()> Reply: [{"action":{"bri":221,"ct":0,"hue":10105,"on":false,"sat":254,"xy":[0.4356,0.4967]},"class":"TV","lights":["1"],"locations":{"1":[0,0.7,0]},"state":{"all_on":false,"any_on":false},"stream":{"active":false,"owner":null,"proxymode":"auto","proxynode":"/bridge"},"type":"Entertainment"}]
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:1195:startStream()> Start entertainment stream
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:587:putJson()> PUT: [http://192.168.2.152:80/api/2bd7034a81ab11eab438000c29d8d52d/groups/4] [{"stream":{"active":true}}]
> [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 0 is now active
> [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 0
> [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:198:setInput()> Priority 254 is now active
> [hyperiond X11] <DEBUG> <GrabberWrapper.cpp:49:start()> Grabber start()
> [hyperiond HYPERION] <INFO> Hyperion instance 'First LED Hardware instance' has been started
> [hyperiond X11GRABBER] <INFO> Update of screen resolution: [0x0]  to [3280x1200]
> [hyperiond X11GRABBER] <INFO> Using XRender for grabbing
> [hyperiond X11GRABBER] <INFO> Update output image resolution: [0x0]  to [410x150]
> [hyperiond X11GRABBER] <INFO> Capture interface is now enabled
> [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 250 is now active
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:613:handleReply()> Reply.httpStatusCode [200]
> [hyperiond LEDDEVICE] <DEBUG> <LedDevicePhilipsHue.cpp:630:handleReply()> Reply: [[{"success":{"/groups/4/stream":{"active":true}}}]]
> [hyperiond LEDDEVICE] <ERROR> Device disabled, device 'philipshue' signals error: 'set stream to true: Bridge response is not Valid'
> [hyperiond LEDDEVICE] <ERROR> Philips Hue Entertaiment API could not initialisized!
>

**Comment by Lord-Grey** [comment]
@SJunkies Currently, if one configures the bridge manually via IP(e.g. for diyHue), plus having a valid username configured, the wizard does not continue. This is due to the fact that the username  configured is not passed to the brigde checking.

The following changes passes the configured username and one can use the wizard.
That also works with diyHue and manual IP-Config.
Please have a look, if the suggested changes are not in conflict with other logic. I have not tested it in all combinations....

  //check if ip is empty/reachable/search for bridge
  if(eV("output") == "")
  {
    getHueIPs();
  }
  else
  {
    var ip = eV("output");
    $('#ip').val(ip);
    hueIPs.push({internalipaddress : ip});
    checkHueBridge(checkBridgeResult, **$('#user').val())**;
  }

  $('#retry_bridge').off().on('click', function(){
    hueIPs.push({internalipaddress : $('#ip').val()});
    hueIPsinc = 0;
    checkHueBridge(checkBridgeResult, **$('#user').val()**);
  });

**Comment by BTopbas** [comment]
> @SJunkies Currently, if one configures the bridge manually via IP(e.g. for diyHue), plus having a valid username configured, the wizard does not continue. This is due to the fact that the username configured is not passed to the brigde checking.
> 
> The following changes passes the configured username and one can use the wizard.
> That also works with diyHue and manual IP-Config.
> Please have a look, if the suggested changes are not in conflict with other logic. I have not tested it in all combinations....
> 
> //check if ip is empty/reachable/search for bridge
> if(eV("output") == "")
> {
> getHueIPs();
> }
> else
> {
> var ip = eV("output");
> $('#ip').val(ip);
> hueIPs.push({internalipaddress : ip});
> checkHueBridge(checkBridgeResult, **$('#user').val())**;
> }
> 
> $('#retry_bridge').off().on('click', function(){
> hueIPs.push({internalipaddress : $('#ip').val()});
> hueIPsinc = 0;
> checkHueBridge(checkBridgeResult, **$('#user').val()**);
> });

I compiled with these changes. And so far so good! Wizard is working!

**Comment by SJunkies** [comment]
fyi: I changed the Philips Hue wizard to recognize non-original bridges!
Unfortunately it is not yet an SSDP solution, so the IP must still be entered manually, but I have changed the check to the IP/api/config URL so that it works at all ;)
It should also work for other bridge alternatives...but myself have not tested any other than the DIYHue ....

The username (+ clientkey) for non-original bridges, can now also be created using the wizard.

**Comment by SJunkies** [comment]
@BTopbas 
Did everything work now and the issue can be closed or are there any other problems with the current version?

**Comment by BTopbas** [comment]
@SJunkies Yep. Everything works! Thanks for your hard work and effort! I am closing the issue.

**Comment by SJunkies** [comment]
Thank you!!!
