### ISSUE TITLE
Pre compiled releases aren't working

### ISSUE THREAD

**Issue by Rickexe** [hyperion-project/hyperion.ng#773]
Hey,

I am using a amlogic Coreelec box and I want to install hyperion on it as a service. I have tried installing it with this command: curl -# -L --get https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.5/Hyperion-2.0.0-alpha.5-Linux-aarch64-amlogic.tar.gz | tar --strip-components=1 -C /storage share/hyperion -xz

But it's not installing the latest version of hyperion.ng even though it is in the title. 
Can anyone explain me why it's not working? 

Thanks in advance

**Comment by Paulchen-Panther** [comment]
This is not the coreelec forum.
