### ISSUE TITLE
Pre compiled releases aren't latest version

### ISSUE THREAD

**Issue by Rickexe** [hyperion-project/hyperion.ng#774]
Hey,

The pre compiled releases aren't the latest version of hyperion.ng. In the title it says 2.0.0 alpha 5 but when you install it on let's say coreelec or raspbian it just says 2.0.0. I used this command to extract it. 
curl -# -L --get https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.5/Hyperion-2.0.0-alpha.5-Linux-aarch64-amlogic.tar.gz | tar --strip-components=1 -C /storage share/hyperion -xz

**Comment by tpmodding** [comment]
they are

look at http://ip:8090/#about

**Comment by Rickexe** [comment]
They are not. I can send you a screenshot of the web ui. 
lol.... where else would I look.

**Comment by tpmodding** [comment]
yes please, could you also paste the System info (Github Issue) information on the about page, may there is a problem

**Comment by Rickexe** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/48714886/79641943-e713c280-819a-11ea-88d6-e0587c8240cb.png) see, I just extracted the release tar.gz again just to be sure and it still says 2.0.0

**Comment by Rickexe** [comment]
When I compile it myself on debian laptop it does say 2.0.0 alpha 5 
![image](https://user-images.githubusercontent.com/48714886/79641968-1cb8ab80-819b-11ea-9fcf-3ebe5de471f8.png)

**Comment by Rickexe** [comment]
On the about page there is nothing to see with the one from the pre compiled release 
![image](https://user-images.githubusercontent.com/48714886/79642029-6d300900-819b-11ea-9293-bfaa5fe8c437.png)

With the manually compiled one there is
![image](https://user-images.githubusercontent.com/48714886/79642040-7f11ac00-819b-11ea-9207-dfc04a196193.png)

**Comment by tpmodding** [comment]
i tested it with the osx, you have the archlinux one right? then there is maybe the problem in the archlinux version

<img width="969" alt="Bildschirmfoto 2020-04-18 um 17 42 20" src="https://user-images.githubusercontent.com/17259976/79642121-0fe88780-819c-11ea-831b-1137bad9fad2.png">

**Comment by tpmodding** [comment]
btw you used the version vom sjunkie, not from the offical repo?

**Comment by Paulchen-Panther** [comment]
Please post a console log output from your amlogic device with the extracted hyperion version

**Comment by Rickexe** [comment]
I see. That is my second instance which controls hue lights but that's not the problem. Just console log from hyperion ui?

**Comment by Paulchen-Panther** [comment]
No. console

**Comment by Paulchen-Panther** [comment]
if you have unpacked the version, you have to start it too. Packing alone is not enough

**Comment by Rickexe** [comment]
![image](https://user-images.githubusercontent.com/48714886/79642232-98672800-819c-11ea-95dc-8714aa5c9b61.png)

**Comment by Paulchen-Panther** [comment]
please start with `./hyperiond`

**Comment by Rickexe** [comment]
![image](https://user-images.githubusercontent.com/48714886/79642266-d1070180-819c-11ea-972b-3983028b1245.png)
I get this error when I do that

**Comment by Rickexe** [comment]
maybe a limitation in coreelec?

**Comment by Paulchen-Panther** [comment]
`ls` please

**Comment by Rickexe** [comment]
![image](https://user-images.githubusercontent.com/48714886/79642286-f8f66500-819c-11ea-9052-5714251d2599.png)

**Comment by Rickexe** [comment]
Thanks for helping me btw

**Comment by Paulchen-Panther** [comment]
the please `hyperiond -d` and output

**Comment by Rickexe** [comment]
[hyperiond DAEMON] (DEBUG) (PythonInit.cpp:20:PythonInit()) Initializing Python interpreter
 [hyperiond SettingsManager] (INFO) Selected configuration file: /storage/.hyperion/config/hyperion_main.json
 [hyperiond SettingsManager] (DEBUG) (SettingsManager.cpp:129:SettingsManager()) Settings database initialized
 [hyperiond EFFECTFILES] (INFO) 36 effects loaded from directory :/effects/
 [hyperiond EFFECTFILES] (INFO) 19 effect schemas loaded from directory :/effects/schema/
 [hyperiond EFFECTFILES] (INFO) 0 effects loaded from directory /storage/.hyperion/custom-effects
 [hyperiond SettingsManager] (INFO) Selected configuration file: /storage/.hyperion/config/hyperion_main.json
 [hyperiond SettingsManager] (DEBUG) (SettingsManager.cpp:73:SettingsManager()) Settings database initialized
 [hyperiond BLACKBORDER] (DEBUG) (BlackBorderProcessor.cpp:65:handleSettingsUpdate()) Set mode to: default
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:67:componentStateChanged()) Blackborder detector: enabled
 [hyperiond FLATBUFCONNECTION] (INFO) Connecting to Hyperion: 127.0.0.1:19401
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:67:componentStateChanged()) LED device: enabled
 [hyperiond LEDDEVICE] (INFO) LedDevice 'file' configured.
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:67:componentStateChanged()) Smoothing: enabled
 [hyperiond EFFECTENGINE] (INFO) run effect Rainbow swirl fast on channel 0
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:153:registerInput()) Register new input 'System/EFFECT' with priority 0 as inactive
 [hyperiond HYPERION] (INFO) Inital foreground effect 'Rainbow swirl fast' started
 [hyperiond EFFECTENGINE] (INFO) run effect Warm mood blobs on channel 254
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:153:registerInput()) Register new input 'System/EFFECT' with priority 254 as inactive
 [hyperiond HYPERION] (INFO) Inital background effect 'Warm mood blobs' started
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:153:registerInput()) Register new input 'System/GRABBER' with priority 250 as inactive
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:67:componentStateChanged()) Framegrabber: enabled
 [hyperiond BOBLIGHT] (DEBUG) (BoblightServer.cpp:24:BoblightServer()) Instance created
 [hyperiond DAEMON] (INFO) Hyperion initialized
 [hyperiond DAEMON] (INFO) set screen capture device to 'amlogic'
 [hyperiond AMLOGICGRABBER] (DEBUG) (Grabber.cpp:33:setVideoMode()) Set videomode to 0
 [hyperiond FRAMEBUFFERGRABBER] (DEBUG) (Grabber.cpp:33:setVideoMode()) Set videomode to 0
 [hyperiond FRAMEBUFFERGRABBER] (INFO) Display opened with resolution: 1920x1080@32bit
 [hyperiond AMLOGICGRABBER] (DEBUG) (AmlogicGrabber.cpp:31:AmlogicGrabber()) constructed(160 x 160), grabber device: /dev/amvideocap0
 [hyperiond DAEMON] (INFO) AMLOGIC grabber created
 [hyperiond JSONSERVER] (DEBUG) (JsonServer.cpp:23:JsonServer()) Created instance
 [hyperiond JSONSERVER] (INFO) Started on port 19500
 [hyperiond FLATBUFSERVER] (INFO) Started on port 19600
 [hyperiond AMLOGICGRABBER] (INFO) FB mode
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:231:setInputImage()) Priority 250 is now active
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:330:setCurrentTime()) Set visible priority to 0
 [hyperiond PROTOSERVER] (INFO) Started on port 19446
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:96:handleSettingsUpdate()) Set document root to: :/webconfig
 [hyperiond WEBSERVER] (INFO) Started on port 8090 name 'Hyperion Webserver'
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:231:setInputImage()) Priority 0 is now active
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:192:setInput()) Priority 254 is now active
 [hyperiond WEBSOCKET] (DEBUG) (WebSocketClient.cpp:32:WebSocketClient()) New connection from ::ffff:192.168.178.33
 [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:916:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.178.33


This is what I get

**Comment by tpmodding** [comment]
do you know what you do? and are you 100% sure that you start the downloaded files and not the ones on your system?

**Comment by Paulchen-Panther** [comment]
rename the hyperiond to hyperiond_old and start hyperiond. You will see that this version does not start at all.

```
mv hyperiond hyperiond_old
hyperiond
```

**Comment by Paulchen-Panther** [comment]
The version you start all the time is from the official CoreELEC repo.

**Comment by Rickexe** [comment]
How is that possible. The command I ran creates that directory.

**Comment by tpmodding** [comment]
dont know, but i think that is not related to our release...so will close it
if you need help, go to our forum please.

**Comment by Rickexe** [comment]
I do have the addon installed yes but it's on a different port first of all and in the .kodi folder so I don't understand how that would be possible

**Comment by Rickexe** [comment]
I can't post on forums for some reason

**Comment by tpmodding** [comment]
your forum name?

**Comment by Rickexe** [comment]
Oh wait I can.

**Comment by Rickexe** [comment]
Did you remove it from the releases page?
