### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by baerni** [hyperion-project/hyperion.ng#776]
#### What problem does this feature solve?
Easy and quick use on raspberry and hass.io

#### What does the proposed API look like?
I don't know
#### How should this be implemented in your opinion?
Container on hub.docker.com

#### Are you willing to work on this yourself?
unfortunately not, but I will be happy to test

Do you plan to make a container at hub.docker.com? It would be a nice option and quick to use thanks to portainer.

**Comment by tpmodding** [comment]
**You used the search?**

unfortunately no

https://github.com/hyperion-project/hyperion.ng/issues/764
