### ISSUE TITLE
Hyperion.NG Behind Nginx Reverse Proxy Websocket Failure

### ISSUE THREAD

**Issue by dcplaya** [hyperion-project/hyperion.ng#781]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion.NG doesn't work behind a reverse proxy. Specfically an NGINX reverse proxy. Hyperion NG is running inside a docker and works with no issues. I want to put the web GUI behind a reverse proxy for security.  

#### Steps to reproduce
Install Hyperion.NG 2.0 Alpha 5.

#### What is expected?
Webpage should load as normal.

#### What is actually happening?
Webpage is blank. Console of the Chrome window is
```
hyperion.js:80 WebSocket connection to 'wss://hyperion.TLDN.com:80/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

#### System

The relevant NGINX config is
```
        location / {
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_pass https://127.0.0.1:8092/;
        }
```

**Comment by tpmodding** [comment]
this is not a hyperion issue...we have no docker support for now
i will close it, but try to help you

WebSocket connection to 'wss://hyperion.TLDN.com:80/' failed: Error in connection establishment

so you need the websocket part also my friend

i would just try something like

https://pastebin.com/15nGa1FZ

line 27 and 28 are optional...

**Comment by dcplaya** [comment]
I never claimed it was a Docker issue, I just stated I have it running in a Docker in case it helped troubleshooting.

Either way, thanks for the NGINX config. It did not work unfortunately. Only thing I didn't have was the websockify location but after adding that, I get the same issue.

I have used the exact same NGINX config for other services that use websockets and they seem to work fine.

I thought the issue was that the Hyperion webserver is forcing WSS connections to port 80 instead of 443 (hence the SSL error). Wasn't sure if it was accidentally hard coded or something.

Either way, like you state, this doesn't seem like a Hyperion issue. Thanks again for the help!

**Comment by tenitz** [comment]
@dcplaya Did you solve this issue? I tried the same thing with the same version, but I also get ERR_SSL_PROTOCOL_ERROR on trying to establish an wss connection. HTTP works just fine

**Comment by m33ts4k0z** [comment]
I tend to disagree that this is not a hyperion issue. It looks like the way that the port it selected in order to perform the websocket connection relies on javascript and since using a reverse proxy, the port will always by absent, the code will always try to look at port 80 no matter what. Here is the related code inside hyperion.js:

`window.jsonPort = (document.location.port == '') ? '80' : document.location.port;
 window.websocket = (document.location.protocol == "https:") ? new 
 WebSocket('wss://'+document.location.hostname+":"+window.jsonPort) : new 
 WebSocket('ws://'+document.location.hostname+":"+window.jsonPort);`

It will work if you redirect to the ssl port so it is always visible in the address bar but this also requires additional port forwards in the router.

**Comment by Lord-Grey** [comment]
@m33ts4k0z As it looks, you exactly know how to fix it. Therefore you just might want to suggest the changes required and everybody will benefit.
Thank you!

**Comment by m33ts4k0z** [comment]
@Lord-Grey This is a fix that would work:

```
--window.jsonPort = (document.location.port == '') ? '80' : document.location.port; 
window.websocket = (document.location.protocol == "https:") ? new WebSocket('wss://'+document.location.hostname+":443") : new WebSocket('ws://'+document.location.hostname+":80");
```
Basically remove the port selection and hard code the http and https ports.

**Comment by Lord-Grey** [comment]
Ok, but that would not cover the scenario, someone uses a port different to the default port.
Looks like the solution should be a mixture of both but doing more justice to ssl.
Your proposal is a quick fix ignoring other scenarios.

**Comment by m33ts4k0z** [comment]
I will continue to the open thread that I created. You are right aboutt he different scenarios so I came up with code that will cover everything. I will post on the open thread once I test the fix thoroughly.

**Comment by Lord-Grey** [comment]
Thank you!
