### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by pattyland** [hyperion-project/hyperion.ng#784]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I replaced my old self compiled version with Alpha 5 on a fresh installed Rasbian and try to import my backup. Hyperion restarts but nothing is imported.

#### Steps to reproduce
Click on Import and wait

#### What is expected?
Imported settings

#### What is actually happening?
nothing beside a restart

#### System

Hyperion Server: 
- Build:       (HEAD detached at e3587923) (Paulchen-Panther-2e83c587/e3587923-1587148622)
- Build time:  Apr 17 2020 19:15:25
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: de)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by brindosch** [comment]
"Merged" with issue: #804
