### ISSUE TITLE
HDMI drops with Pi3B+

### ISSUE THREAD

**Issue by wardwygaerts** [hyperion-project/hyperion.ng#793]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Sometimes when Hyperion is enabled and Platform grabber is on, my HDMI signal drops and come backs after a second. In some cases this happens only once, in other cases the HDMI signals keeps dropping.

#### Steps to reproduce
Enable Hyperion with platform grabber on.

#### What is expected?
no HDMI drops

#### What is actually happening?
Sometimes when Hyperion is enabled and Platform grabber is on, my HDMI signal drops and come backs after a second. In some cases this happens only once, in other cases the HDMI signals keeps dropping. When disabling Hyperion, the issue is solved. I'm now using a PI3B+, but had the same issues with a PI4 (4GB).
My Pi's are connected to an Onkyo receiver.

#### System
Hyperion Server: 
- Build:       (HEAD detached at e3587923) (Paulchen-Panther-2e83c587/e3587923-1587148622)
- Build time:  Apr 17 2020 19:15:25
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: en)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: LibreELEC (official): 9.2.1
- Arch:         arm
- Kernel:       linux (4.19.106 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**Comment by Paulchen-Panther** [comment]
We do not officially support LibreELEC. In this case, please contact the LibreELEC forum. So I'm going to close this issue
Thank you very much
