### ISSUE TITLE
[Feature Request] Airplay Support

### ISSUE THREAD

**Issue by bmwbry** [hyperion-project/hyperion.ng#795]
I believe airplay uses UDP (scrambled) to send audio during airplay. Since we can already use Airplay on Raspberry Pi’s, I presume we already know how to unscramble the UDP stream or at least have access to it.

Would there be a way to take this UDP stream and map it to output on Hyperion?

For instance you could have a regular airplay device playing music but select Hyperion as an additional synced output that would then display a visualizer based on the currently played song.

**Comment by tpmodding** [comment]
pls use the template, thanks
