### ISSUE TITLE
LED white flashes

### ISSUE THREAD

**Issue by mazafra1** [hyperion-project/hyperion.ng#797]
- [x] I confirm that this is an issue rather than a question.

## Bug report
All LEDs flash white randomly without input signal.

#### Steps to reproduce
Hyperion server enabled while input signal is off. My environment is RPI4 on raspbian buster. Apa102 LED strip is connected to RPI's SPI with level shifter and external power DC. RPI's and LED's ground line is common.

#### What is expected?
No LED switching on at all.

#### What is actually happening?
LED flashes white without input signal. Even when LED strip power is off. I'm guessing on some spi voltage peak. Disabling Hyperion instance from web dashboard stops flashes.

#### System

Hyperion Server: 
- Build:       (HEAD detached at e3587923) (Paulchen-Panther-2e83c587/e3587923-1587148622)
- Build time:  Apr 17 2020 19:15:25
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: en-GB)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm64
- Kernel:       linux (4.19.114-v8+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 
[Hyperion-2.0.0-alpha.5-Backup (My Hyperion Config) 2020.05.14.txt](https://github.com/hyperion-project/hyperion.ng/files/4627607/Hyperion-2.0.0-alpha.5-Backup.My.Hyperion.Config.2020.05.14.txt)

**Comment by brindosch** [comment]
> I'm guessing on some spi voltage peak

As supposed, Hyperion won't create white flashes. So there is nothing we can do here, sorry.

**Comment by 7h30n3** [comment]
@mazafra1 Could you solve the problem? I have the same issue with mit Raspberry Pi 3 and  WS2801 via SPI.
