### ISSUE TITLE
We need to migrate tpm2.net support to a new driver and kill the old UDP driver

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#80]
I'm half way they doing it but would love someone to test when done

**Comment by brindosch** [comment]
I had some time ago a OLA installation on my Pi as short matrix test with Jinx! on Windows to create the output, i may able to test it with this setup again.
@redPanther may also interested in this.

**Comment by redPanther** [comment]
I heared that windows software glediator also sends via tpm2net. I have no windows in my family, But I can try ola+qlc. I use qlc already for my DMX fixtures.

**Comment by redPanther** [comment]
@penfold42 whats the status of this topic?

**Comment by penfold42** [comment]
I got half way thru it and realized I need a tpm2.net receiver.  It's still on my list I'll let you know where I get ronin a few days

**Comment by penfold42** [comment]
#217
