### ISSUE TITLE
Signal recognition doesn‘t work properly

### ISSUE THREAD

**Issue by sascha777** [hyperion-project/hyperion.ng#800]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I use the black signal recognition to turn lights off instead of giving a constant blue. Therefore I adjusted the RGB values that worked for me. 
A few days later these values doesn‘t work anymore and the lights are blue again. After readjusting Settings the signal recognition runs fine again. Unfortunately this repeats every few days without a constant schema. 
Strange is that rising values from signal recognition to a higher value, saving it and setting it back to the old value does also help to get the signal recognition work again. 

#### Steps to reproduce
Set signal recognition
Use for some days 🙁 can‘t force it another way
set regonition value up, save, down, save

#### What is expected?
Having constant signal recognition values that black out the light when no signal is present

#### What is actually happening?
See bug report
Thank you so much for your amazing work! I really love Hyperion!

#### System

Hyperion Server: 
- Build:       master (GitHub-2cdb309e/94728608-1589306166)
- Build time:  May 15 2020 10:43:27
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: de)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/81.0.4044.124 Mobile/15E148 Safari/604.1

**Comment by brindosch** [comment]
This sounds strange, it should simply work.

**Comment by sascha777** [comment]
Just upgraded today to the latest master yesterday. Problem still occurs. 
Are there logs available to investigate further?
Am I the only one facing this issue?

**Comment by tpmodding** [comment]
Which input method do you use?

**Comment by sascha777** [comment]
USB with V4L2:auto

**Comment by sascha777** [comment]
It’s working again 🤔
Let’s keep this on hold and I will report back with further investigation.

**Comment by m-seker** [comment]
> This sounds strange, it should simply work.

This is what I say when i have no clue :D
