### ISSUE TITLE
LED freeze after start-effect finished

### ISSUE THREAD

**Issue by UniCizin** [hyperion-project/hyperion.ng#803]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After updating to newest version (build from git), my SK6812 freeze after start-effect finished.
They just stay the last color the effect showed and don't react at all.
The harware setup works flawless with a build from Sep 20 2019 18:48:54

#### Steps to reproduce
Update to newest version via git and build.
Setup the LED configuration via web frontend.
restart the Pi.

#### What is expected?
LEDs display the start effect and are "open" for new input

#### What is actually happening?
Start effect is shown, than the leds show the last color from this effect, nothing more.

#### System

Unfortunately to i went back to a backup (version mentioned above) to clarify it is not an hardware issue. But it was alhpa 5, compiled yesterday on a Pi 3.

**Comment by Lord-Grey** [comment]
Would you mind sharing a debug log, please.

**Comment by UniCizin** [comment]
yes, here you go..
i made a fresh install of alpha 5.. behaviour still the same.
[hyperion_debug.txt](https://github.com/hyperion-project/hyperion.ng/files/4672027/hyperion_debug.txt)

**Comment by Lord-Grey** [comment]
@UniCizin 

I am not the expert in terms of grabber, but the following log-line may indicate that there is a problem in that area:

` [hyperiond V4L2:/dev/video0] (INFO) Signal lost`

To test that the LedDevice work, you may run an effect or a color from the color-picker via the remote-control screen.

**Comment by UniCizin** [comment]
No, does not work as i mentioned before. The LEDs freeze completely . No
custom colors nor selected effects Rother.



LordGrey <notifications@github.com> schrieb am Sa., 23. Mai 2020, 17:55:

**Comment by Lord-Grey** [comment]
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by UniCizin** [comment]
I am sorry, i did Not close the issue. I Made a fresh Install a while ago
with a newer version then mine from the issue and everything works.
Thank you

LordGrey ***@***.***> schrieb am So., 18. Juli 2021, 19:00:

**Comment by Lord-Grey** [comment]
@UniCizin Thanks for coming back!
