### ISSUE TITLE
Configuration export/import for multiple instances

### ISSUE THREAD

**Issue by schmidtjr** [hyperion-project/hyperion.ng#804]
#### What problem does this feature solve?
(issue appears on 2.0.0-alpha.5 (HEAD detached at e3587923) (Paulchen-Panther-2e83c587/e3587923-1587148622))
If you have multiple instances defined, you need to export a configuration for each instance.
The name of the exported file does not contain a hint on the exported configuration.

#### What does the proposed API look like?
-
#### How should this be implemented in your opinion?
I see two options:
1. Make the documentation of configuration export more precise. It needs to state that it's only exporting the currently selected instance. The exported filename should contain the instance name.
2. Provide a complete configuration export, that contains all instances. (And of course an import function for a full configuration)
#### Are you willing to work on this yourself?
No

**Comment by brindosch** [comment]
This is a issue that was indeed introduced with the instance feature. Some adjustment are required to.

**Comment by Nico04** [comment]
Looking for this too :)

**Comment by tjenvy** [comment]
my raspberry pi software was not working right. I had exported configuration regularly with any changes.  I thought I would be fine. Never in my wildest dreams did I imagine that it was only exporting the current instance.  If you have multiple lights like I do one naturally thinks it exports all of them. I now have to re-setup all but my main TV lights.  This is a 4 year old thread seems like an important thing to have worked on in 4 years. Not that I am not thankful of all the work that has gone into this, but this is a pretty big deal.
