### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by lukasloetkolben** [hyperion-project/hyperion.ng#807]
Hi, i have the "Black and White" problem with my Videograbber.
I think you already fixed it, may i ask if you can create a new release.
I want to install it on my LibreElec.

thank you so much

**Comment by tpmodding** [comment]
hi,

new releases will be created when we think it is time for a new release...
if you need the newest build, you can compile it yourself...there is a howto on github, in the forum, on youtube etc....
thanks
