### ISSUE TITLE
Alpha5 MacOS dmg isnt working

### ISSUE THREAD

**Issue by MansM** [hyperion-project/hyperion.ng#808]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Alpha5 MacOS dmg isnt working

#### Steps to reproduce
download dmg file
open the dmg file
move hyperion file to Applications
open Hyperion

#### What is expected?
opening hyperion

#### What is actually happening?
double clicking in finder: 
You can’t open the application “Hyperion” because it may be damaged or incomplete.

on the command line:
open Hyperion.app/
The application cannot be opened because its executable is missing.

**Comment by tpmodding** [comment]
Yep, can confirm it...i always tested the tar.gz files only, those work 

Apple has changed his signing rules etc....

**Comment by brindosch** [comment]
In 2.0.0-alpha.6 the `.dmg` build has been discontinued due to the signing rules. Please use the `tar.gz`. 

However, this will just work if you have a development setup because of the libs @tpmodding? This should be probably fixed.

@Paulchen-Panther 
Did you tested the lib gathering on mac?

**Comment by NgKhanh** [comment]
Hello, where can I download .dmg file ?

**Comment by tpmodding** [comment]
https://github.com/hyperion-project/hyperion.ng/releases/tag/2.0.0-alpha.10
 there is currently only the Hyperion-2.0.0-alpha.10-macOS-x86_64.tar.gz file
