### ISSUE TITLE
API: Better intance control handling

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#809]
## Feature request

Current handling of the instance api isn't easy enough. When more than one instance should be controlled in the same way, or information should be gathered by instance it's getting complicated. So i propose

Add a new optional instance field to all requests or to specific requests
```json
{"command":"xxx", "subcommand": "xxx", "instance":0, "tan":1}
```
It's open to the implementation if this should be limited to the number or if a string is also accepted with the user defined name. (Or an array with selections)

If the instance field is omitted or set to `-1`
- Getter functions use the instance `0` (if applicable)
- Setter functions like effect/color will be pushed to all instances  (if applicable)

Further it might be possible to select more than one but less than all instances by providing a list of instances `[0,3,4]` (if applicable)

The last bit is how to "observe" the state of an instance, i think one instance for one connection is okay. More will increase load for the browser if not handled carefully. So no changes here.
 

#### What problem does this feature solve?
API usage when different instances should be selected
#### Are you willing to work on this yourself?
Yes

cc @Lord-Grey @Paulchen-Panther

**Comment by Paulchen-Panther** [comment]
@brindosch 
https://hyperiondevteam.slack.com/archives/C1Z0Z9KS9/p1597944834006700
