### ISSUE TITLE
Missing dependencies in cmake

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion.ng#81]
I try to get the AUR package ready for hyperion 2.x now.
I tried compiling the source but cmake does not throw an error for some missing deps. Those should be included to the cmake.

A pacman dep list would also be nice, I will work on that. If someone already develops on arch and has the deps ready, please let me know.

```
[ 97%] Linking CXX executable ../../bin/hyperiond
/usr/bin/ld: cannot find -ldns_sd
/usr/bin/ld: cannot find -lavahi-client
/usr/bin/ld: cannot find -lavahi-common
/usr/bin/ld: cannot find -lavahi-core
/usr/bin/ld: cannot find -ldbus-1
collect2: error: ld returned 1 exit status
make[2]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/build.make:150: bin/hyperiond] Error 1
make[1]: *** [CMakeFiles/Makefile2:1445: src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

I checked but the package `avahi` is installed. I am wondering what is missing.
```
[arch@arch hyperionpkg]$ find / -name avahi-client 2>/dev/null
/usr/include/avahi-client
```

**Comment by penfold42** [comment]
This seems similar to #40

What system/CPU are you building for and what was your cmake line ?

**Comment by NicoHood** [comment]
x64 (laptop) with the line `cmake -DENABLE_FB=ON -DCMAKE_BUILD_TYPE=Release ..`

**Comment by penfold42** [comment]
cmake -DPLATFORM=x86 -DCMAKE_BUILD_TYPE=Release ..

**Comment by redPanther** [comment]
for distros without static avahi libs use that:
cmake -DPLATFORM=x86 -DCMAKE_BUILD_TYPE=Release USE_SHARED_AVAHI_LIBS=ON ..

**Comment by redPanther** [comment]
this can be closed, issue was resolved before ...
