### ISSUE TITLE
Windows building error

### ISSUE THREAD

**Issue by Rickexe** [hyperion-project/hyperion.ng#811]
Hey, 

I need help with building for windows. I am getting this error on this command: cmake --build . --config Release -- -maxcpucount

![image](https://user-images.githubusercontent.com/48714886/83120696-aa0fe980-a0d1-11ea-8827-ae8dc4ad1953.png)

I used "cmake -DPLATFORM=windows -G "Visual Studio 16 2019" .." instead of "cmake -DPLATFORM=windows -G "Windows 16 2019" .." because the windows one didn't work for me. Don't know if this is the problem. 

BTW: It's probably not a bug but I don't know what to label it.

**Comment by brindosch** [comment]
Hello, i have seen that error sometimes. Needs investigation on our side.

> I used "cmake -DPLATFORM=windows -G "Visual Studio 16 2019" .." instead of "cmake -DPLATFORM=windows -G "Windows 16 2019" .."

A typo at the instructions. Is corrected.

To your service i've added the packages of windows to the latest release. But be aware of the windows issues list.

**Comment by Rickexe** [comment]
Thanks. I found the exe after I posted this thread. Is it necessary to add hyperion to path?

**Comment by brindosch** [comment]
No, you can use the desktop shortcut (if created) or the entry at the menu.

**Comment by Rickexe** [comment]
I am really struggling with the gamma with the hue entertainment api. When I increase the gamma to 2 it's flickering a lot and when gamma is 1 it's flickering less but the colors are not that good in my opinion. Do you know what the best gamma is for the hue entertainment api?

**Comment by Rickexe** [comment]
Also, do you know if the aarch64 packages can be installed on coreelec already?

**Comment by Paulchen-Panther** [comment]
> Also, do you know if the aarch64 packages can be installed on coreelec already?

No questions about CoreELEC please. This is the wrong place for that.

**Comment by Rickexe** [comment]
I know sorry. But coreelec forums are down XD.

**Comment by Paulchen-Panther** [comment]
The AARch64 builds are generic releases. CoreELEC uses other dependencies. So no

**Comment by Rickexe** [comment]
Ok Thank you.
