### ISSUE TITLE
Hdmi signal drop

### ISSUE THREAD

**Issue by Tobi-ctrl** [hyperion-project/hyperion.ng#814]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hdmi signal drops when playing 1080p content with enabled hyperion using internal grabber. 

#### Steps to reproduce
Enable hyperion and internal grabber. Play 1080p content. See error. 

#### System

Hyperion-ng alpha v2.0.0-alpha6

**Comment by Paulchen-Panther** [comment]
Please post complete system infos from WebUI.

> In the web interface of the Hyperion config go to System > About Hyperion and Paste the content of "System info (Github Issue)" here

**Comment by tpmodding** [comment]
thanks for ignoring our template,
