### ISSUE TITLE
Crashes when changing LED Layout

### ISSUE THREAD

**Issue by richard-kramer** [hyperion-project/hyperion.ng#815]
I installed the latest Release (alpha.6) on my Raspberry Pi 4.
When trying to change the LED Layout, Hyperion crashes.

I'm not entirely sure, what exactly causes the crash, but it always happens with the same layout options. I was able to reproduce with just 12W and 8H.

It crashes with the error message

```txt
[1]    14010 segmentation fault  /usr/bin/hyperiond
```

## System info:

```txt
Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:11:33
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     en (BrowserLang: de-DE)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
--
```

**Comment by tpmodding** [comment]
thanks for ignoring our template,

Please don't delete this template or we'll close your issue

You can try it with the template again
