### ISSUE TITLE
'grabber-v4l2.input' setting equivalent 

### ISSUE THREAD

**Issue by NKnusperer** [hyperion-project/hyperion.ng#817]
#### What problem does this feature solve?
Old `hyperion.config.json` has a setting `'grabber-v4l2.input` 
> V4L2 input to use [default=0]

This can be used to switch input if a capture devices has multiple video inputs, eg. HDMI and CVBS.
As far as I can tell there is no equivalent setting available in hyperion.ng.

#### How should this be implemented in your opinion?
Add a `Input` option to the `USB Capture` setting form.

#### Are you willing to work on this yourself?
I will try if you can guide me into the right direction

**Comment by Paulchen-Panther** [comment]
> Are you willing to work on this yourself?

???

**Comment by NKnusperer** [comment]
@Paulchen-Panther Yes if I know how.

**Comment by tpmodding** [comment]
in hyperion classic we had this option, and i can not remember that even one people used this option...do you need it?

**Comment by Paulchen-Panther** [comment]
Which device do you use?

**Comment by NKnusperer** [comment]
I have a old AmbiScreen Box which I would like to modernise.
Essentially it is just a Raspberry Pi 3 with a STK1160 which was somehow modded to support two inputs (0=CVBS / 1=HDMI).

https://ambiscreen.tv/

**Comment by Paulchen-Panther** [comment]
Ich werd mal schauen was sich da machen lässt.
