### ISSUE TITLE
LED Color incorrect after 1 meter (Red/Green Switches)

### ISSUE THREAD

**Issue by DutchmanNL** [hyperion-project/hyperion.ng#818]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Having ws2812b controlled by WLED (UDP) gives wrong color in 2 areas

The LED itself works fine, I use 144 p/m (462 in total).
I fuse the LED stripe every meter

#### Steps to reproduce
- used latest Hyperion alpha
- Video grabber 
- WLED ob ESP (Wemos)

#### What is expected?
Correct colours around the whole screen 

#### What is actually happening?
Wrong Color Schema (example half way Red is green and at the end red is blue)

![502DCA19-FEE6-43A2-9B03-8F0641708817](https://user-images.githubusercontent.com/7318445/83485177-cd0e1500-a4a6-11ea-98fd-ef72c3e3f488.jpeg)

When I just test the LEDS all is fine, rainbow effect also looks correct (not sure about the Color)

![B3AA1A1F-7CFB-4547-96FA-98EE86CD5F66](https://user-images.githubusercontent.com/7318445/83485230-e911b680-a4a6-11ea-92bf-01dcf3d04449.jpeg)

#### System
Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 20:36:52
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: nl)
- UI Access:   default
- Avail Capt:  v4l2,framebuffer,x11,qt

Hyperion Server OS: 
- Distribution: Ubuntu 18.04.4 LTS
- Arch:         x86_64
- Kernel:       linux (4.15.0-101-generic (WS: 64))
- Browser:      Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1

**Comment by tpmodding** [comment]
Can you please provide a video from the effect "knight rider"

**Comment by DutchmanNL** [comment]
> Can you please provide a video from the effect "knight rider"

sure here we go 


[IMG_0366.MOV.zip](https://github.com/hyperion-project/hyperion.ng/files/4716884/IMG_0366.MOV.zip)

As we see also here we get 3 different color types, I first thought it has something todo with the RBG stripe but as mentioned (and seen in the picture) controlling it normally is working (non hyperion) and the color switch is also not where the strifes are connected (so not related to bad soldering etc)

**Comment by tpmodding** [comment]
Ok, did you made your led layout right IN hyperion? doesnt look so....

**Comment by DutchmanNL** [comment]
> Ok, did you made your led layout right IN hyperion? doesnt look so....

can you tell me why ?

yes the layout is correct (one maybe 3 or 4 LEDS need to move to have an exact match)
The layout is correct set to RGB, the color at the top is correct but the other 2 not.

if I change that, the top LED stripe (with abut 10cm to the left corner, will have the wrong color.

wen I use the profile and separate my leds start from 170-340 and put green into the red color at least green is correct but would neet to do that for all 5 values and the 3rd part of the TV (and a second profile is not working)

**Comment by tpmodding** [comment]
did you set the right start led? did you use segments on wled? which protocol you choosed?

**Comment by DutchmanNL** [comment]
> did you set the right start led? did you use segments on wled? which protocol you choosed?

Start led is at the right and set to inverse (in direction of the LED stripe)

![Schermafbeelding 2020-06-02 om 16 13 27](https://user-images.githubusercontent.com/7318445/83530418-00bf5e00-a4ec-11ea-86cf-e7dd3083e35c.png)

I don't use any segments in WLED

![Schermafbeelding 2020-06-02 om 16 14 05](https://user-images.githubusercontent.com/7318445/83530526-20ef1d00-a4ec-11ea-8a1f-da49f4f97d2a.png)

Protocol used is UDP133 (other did not work at all)

![Schermafbeelding 2020-06-02 om 16 15 11](https://user-images.githubusercontent.com/7318445/83530624-3f551880-a4ec-11ea-8df6-d9dcbeadb42e.png)

**Comment by tpmodding** [comment]
can you try it with udpraw and with port 19446 please?

**Comment by DutchmanNL** [comment]
Switching to udpraw with port 19446 looks to fix the behavior, I will provide additional test and update the issue this evening.

If this is the solution, I will also add the section to the Hyperion NG wiki accordingly

**Comment by tpmodding** [comment]
I will close this, if the problem occures, just reopen it.
