### ISSUE TITLE
Web UI stops working / did not load at all

### ISSUE THREAD

**Issue by AxelMaassen** [hyperion-project/hyperion.ng#819]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Enable internal cam on raspberry pi 3stops web ui from working

#### Steps to reproduce
Enable / disable cam via raspi-config

#### What is expected?
no side effects, I need the cam to look at the TV

#### What is actually happening?
no more reaction of the webui, all buttons blocked

#### System

Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:09:46
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: HyperBian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Please fill the rest from the issue template. thanks

**Comment by Paulchen-Panther** [comment]
The error is caused by a newly added V4L2 driver (BCM2835 ISP).
Thanks for your report. I will deal with this problem.

**Comment by tihoangyeudau** [comment]
same issues with pi zero W
