### ISSUE TITLE
Saturation 

### ISSUE THREAD

**Issue by kehne92** [hyperion-project/hyperion.ng#822]
## Feature request

 can't ask on the forum 

#### What problem does this feature solve?
Hey, it would be very great if the old saturation setting could be implemented. I personally liked this setting and missed it 
#### How should this be implemented in your opinion?
Increase the color so light red is red 
#### Are you willing to work on this yourself?
No, I can't. Sorry :(

**Comment by AalianKhan** [comment]
I need this feature as I am using a USB Logitech camera. The webcam is capturing too much white thus making the led too white and flushing out the colour. With an option to adjust saturation this can eliminate my issue. 
Cameras are becoming more and more prominent in a solution to enable users to have Ambilight on whatever they are using so this feature is becoming a must.

**Comment by AalianKhan** [comment]
What red should look like
![IMG-20200722-WA0007](https://user-images.githubusercontent.com/39784853/88254239-a6888100-cc82-11ea-90c0-b188e03f16cd.jpg)
What red I get with webcam (too much white)
![IMG-20200722-WA0006](https://user-images.githubusercontent.com/39784853/88254269-c1f38c00-cc82-11ea-9765-a199f907a05f.jpg)
