### ISSUE TITLE
Forwader BUG - Client LEDS do not illuminate until web UI is accessed  

### ISSUE THREAD

**Issue by RKF-FKR** [hyperion-project/hyperion.ng#823]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Using Hyperion NG to forward Proto and JSON (or either).  LED's on the target screen do not become active until the WEB UI is accessed (or refreshed) After that, Hyperion works flawlessly.  

#### Steps to reproduce
Start Pi4 containing the V4L2 grabber and the forwarder port details. (eg  192.168.1.200)
Start Pi Zero W containing the client ports. (eg 192.168.1.300)
Wait for splash screen of client > OK
Wait for Hyperion to commence on client (192.168.1.300) > fail
Using Mac Safari - access 192.168.1.200:8090 - hit enter
Hyperion UI opens - lights illuminate on 192.168.1.300

#### What is expected?
Previous Hyperion forwarder and client Pi's boot up, then as soon as client connects with forwarder Hyperion LED's commence.

#### What is actually happening?
Strangely I need to open a web UI for the client lights to commence - happens whether I use LAN cable or Wifi for the Hyperion forwarder Pi

#### System

Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:11:33
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: en-au)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15

**Comment by Paulchen-Panther** [comment]
Which LEDs do you use on your Pi Zero W?

**Comment by RKF-FKR** [comment]
I have use AP102 (without problems on the old version).

**Comment by RKF-FKR** [comment]
@Paulchen-Panther - I can also report that the LEDs on server Pi - connected to Pi pins 19 and 23 (also APA102) will also remain on the boot colours until the UI is opened.  Once the UI web page is opened.  So that means forwarder and server LEDS seem to suffer the same symptoms.

**Comment by m-seker** [comment]
@RKF-FKR @direk Do you have the possibility to build hyperion with debug symbols ? If yes, running the hyperion in gdb and providing the stack trace (`ctrl + c, thread apply all bt`) before accesing WebUI would make a good start towards understanding the issue.

**Comment by RKF-FKR** [comment]
@m-seker I'd love to try your suggestion.  I am not at your level of expertise.  Happy to download and try a compiled version that contains your suggested changes though.

**Comment by mstuebner** [comment]
Same issue using W2812 led on GPIO18 of an PI3b+

**Comment by direk** [comment]
Sorry, I moved to RPi4 with adalight USB device to drive leds and alpha.8 version. The problem disappeared.

**Comment by RKF-FKR** [comment]
Indeed my problems have vanished with Alpha 8 as well using the classic wired configuration.

**Comment by tpmodding** [comment]
so this can be closed?

**Comment by RKF-FKR** [comment]
From my perspective, yes. But I noticed that @mstuebner is still using Alpha 6 and has the problem. 
Otherwise yes I believe with the current version it should be fine.

**Comment by mstuebner** [comment]
Moved to alpha 8 today and can confirm that this is gone
