### ISSUE TITLE
Hyperiond hangs on start if compiled with ENABLE_V4L2 on RP2

### ISSUE THREAD

**Issue by szlop** [hyperion-project/hyperion.ng#824]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Start hyperiond without any config on Raspberry Pi 2.

#### What is expected?
Normal startup.

#### What is actually happening?
Startup does not finish, the webserver is not starting. Instead, one CPU core goes to 100% load and hyperiond starts allocating memory, till the system gets unresponsive after about one minute. Hyperiond starts normally, if compiled with ENABLE_V4L2 = Off. 

[hyperiond-debug.txt](https://github.com/hyperion-project/hyperion.ng/files/4742406/hyperiond-debug.txt)

#### System

Hyperion Server: 
- Build:       master (GitHub-4d429a27/08de6b78-1590779969)
- Build time:  Jun  7 2020 16:43:50
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: de)
- UI Access:   expert
- Avail Capt:  dispmanx,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.44-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0 

The System info is copied from a build with ENABLE_V4L2 = Off. I am running Rasbian Buster without xserver. There is an Arduino connected via USB, which is meant to be used by the adalight driver. Since the webserver is not starting, I have not configured anything. I got identical results for the armv7 deb package from the Hyperion 2.0.0-alpha.6 release and commit 08de6b7.

**Comment by Paulchen-Panther** [comment]
Fixed in PR #820

**Comment by szlop** [comment]
Thanks a lot!

**Comment by szlop** [comment]
> Fixed in PR #820

Today I tested this commit, it fixes the issue for me.
