### ISSUE TITLE
Select Nanoleaf Canvas Panels for Ambilight

### ISSUE THREAD

**Issue by Lumumba76** [hyperion-project/hyperion.ng#827]
**## Feature request**
Selecting Canvas Squares which should give Ambilight
In the current version it is only possible to use Canvas 1-n (starting at the top left) for Ambilight.
I would like to be able to use Canvas 13-17 as an Ambilight. The rest should be black.

![Ambilight](https://user-images.githubusercontent.com/20858466/84000951-f545ba00-a965-11ea-878b-581c0e2965e9.png)

**#### What problem does this feature solve?**

**#### What does the proposed API look like?**

**#### How should this be implemented in your opinion?**

**#### Are you willing to work on this yourself?**
Of course i can support.

**Comment by Lord-Grey** [comment]
Hey @Lumumba76

I have done an initial start to allow a different panel sequencing, as well as to define a start panel greater zero.

![image](https://user-images.githubusercontent.com/48840279/84432921-cc574a80-ac2d-11ea-9bd9-72d164308f1c.png)

In case you can compile yourself you can have a look into my git-hub repository
https://github.com/Lord-Grey/hyperion.ng

Branch: Refeactor_LedDevices

Note: To see the configuration item you need to switch to settings-level "advanced"

**Comment by Lumumba76** [comment]
I will test as soon as the new Canvas arrive :-)
Thank u very much!
