### ISSUE TITLE
Forwarder Multiple instances not working

### ISSUE THREAD

**Issue by RaymondMouthaan** [hyperion-project/hyperion.ng#831]
- [x] I confirm that this is an issue rather than a question.

Hi guys,

Thanks for the great work on this amazing piece of software!

I am trying to setup a multiple hyperion instance configuration, but after a few days of trying I just can't figure it out. I've read this https://hyperion-project.org/threads/forwarder-on-coreelec-proto-hyperionrequest-missing-command.3585/ and followed the steps.

Your help is very much appreciated! 

## Bug report
Not sure whether it's a bug or I just missed something in my configuration.

#### Steps to reproduce
- Two Raspberry PI 3B, resp. **hyperion-1** and **hyperion-2**

#### hyperion-1 

- 2.0.0-alpha.6 installed 
- Forwarder **activated**
   - json target 1: **10.10.1.11:19444**
   - flatbuffer target 1: **10.10.1.11:19400**
- Platform Capture  **deactivated**
- USB Capture **activated**
- LED device **activated**
   - Controller Type: **adalight**

This instance controls a ws2813 ledstrip (271 leds) behind my TV perfectly fine, while playing a movie or using the hyperion app on my iPhone.

#### hyperion-2

- 2.0.0-alpha.6 installed 
- Forwarder **deactivated**
- Platform Capture  **deactivated**
- USB Capture **deactivated**
- LED device **activated**
   - Controller Type: **adalight**

- Json Server port: **19444** 
- Flatbuffers Server port: **19400**

This instance controls a ws2813 ledstrip (140 leds). __Using the hyperion app on my iPhone the effects and color wheel controls the ledstrip as expected__. 

#### What is expected?
That hyperion-1 forwards to json target and flatbuffer, while hyperion-2 receives this data and controls the secondary ledstrip. 

#### What is actually happening?
From the hyperion-1 logs is seems it connects to hyperion-2:

```
 [hyperiond FLATBUFCONNECTION] (INFO) Connecting to Hyperion: 10.10.1.11:19400
 [hyperiond NETFORWARDER] (INFO) Forward now to json targets '10.10.1.11:19444'
 [hyperiond NETFORWARDER] (INFO) Forward now to flatbuffer targets '10.10.1.11:19400'
``` 

However at hyperion-2 there is nothing to see in the logging related to the connection and the ledstrip isn't controlled as expected.

#### Hyperion-1

Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:11:33
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: en-gb)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

#### Hyperion-2
Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:11:33
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: en-gb)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

**Comment by szlop** [comment]
I've got a setup similar to this with adalight and forwarding to a Raspberry Pi and I experienced the same problems. Today I compiled #820 and my setup is working fine since.

**Comment by RaymondMouthaan** [comment]
> I've got a setup similar to this with adalight and forwarding to a Raspberry Pi and I experienced the same problems. Today I compiled #820 and my setup is working fine since.

Thanks for the tip! I'll try that branch as well 👍

**Comment by RaymondMouthaan** [comment]
@szlop , your right #820 fixes this issue as well, thanks! 👍🏽
