### ISSUE TITLE
Web Configuration responds with 404 - Requested file: index.html

### ISSUE THREAD

**Issue by heikobihr** [hyperion-project/hyperion.ng#834]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When opening web interface (http://localhost:8090), embedded webserver delivers a HTTP 404.
Browser shows `404 - Requested file: index.html`

#### Steps to reproduce
* Windows build on "Microsoft Visual Studio Community 2019" (commit id 5eb45e857fd12f96979d03e80e4dd1ee86a096c4)
* start hyperiond.exe
* open web interface in browser: http://localhost:8090

#### What is expected?
* Browser shows web interface

#### What is actually happening?
Browser shows `404 - Requested file: index.html`

#### System

After fixing the issue:

Hyperion Server: 
- Build:       master (GitHub-0dd4bbf9/5eb45e85-1592422704)
- Build time:  Jun 20 2020 11:06:44
- Git Remote:  git@github.com:heikobihr/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   default
- Avail Capt:  qt

Hyperion Server OS: 
- Distribution: Windows 10 Version 1903
- Arch:         x86_64
- Kernel:       winnt (10.0.18362 (WS: 64))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by Paulchen-Panther** [comment]
Please use Visual Studio Code and open the workspace file in the folder .vscode / hyperion.code-workspace.
This allows Hyperion to be compiled without problems on Windows. If there are any complications, set the environment variables "Qt5_DIR" and "CMAKE_PREFIX_PATH" manually.

**Comment by heikobihr** [comment]
A build in Visual Studio Code works for me, too. Thanks for pointing this out :-)

It looks like CMake gets some wrong paths from Microsoft Visual Studio Community 2019, causing invalid aliases to be generated to WebConfig.qrc.
