### ISSUE TITLE
hiperion.ng on ubuntu 20.04

### ISSUE THREAD

**Issue by xzxzard** [hyperion-project/hyperion.ng#838]
Hi guys.
Previously i used hyperion (arduino nano with APA102) on ubuntu 18.04 (amd64) and all worked fine.
After upgrade on ubuntu 20.04 and hiperion.ng - nothing works. I have tried a lot of sketches and options - same result. WebUI says that LED device is conected. 
Can anyone help me?

**Comment by Paulchen-Panther** [comment]
Not here.
This the right place -> https://www.hyperion-project.org/

**Comment by xzxzard** [comment]
> Not here.
> This the right place -> https://www.hyperion-project.org/

Thank you.
