### ISSUE TITLE
Web interface not accessible after activating Picam

### ISSUE THREAD

**Issue by PhilippH264** [hyperion-project/hyperion.ng#839]
- [x] I confirm that this is an issue rather than a question.

## Bug report

- Webinterface is not accessible as soon as the Picam-Interface is activated in raspi-config.
- The behaviour occurs in both Hyperbian-image and manual install via .deb-fille

#### Steps to reproduce

- hyperion.ng 2.0.0-alpha.6 on Raspberry Pi 3
- Picam connected to the Pi via flexcable
- activate Picam interface: 

1. Connect to pi via ssh
2. "sudo raspi-config"
3. "5 Interfacing Options - Configure connections to peripherals"
4. "P1 Camera - Enable/Disable connection to the Raspberry Pi Camera"
5. "Would you like the camera interface to be enabled?" -> Yes
6. "The camera interface is enabled" -> Ok
7. "Finish"
8. "Would you like to reboot now?" -> Yes

#### What is expected?

- Camera in hyperion.ng is accessible to use it as video source

#### What is actually happening?

- Web interface is not accessible after activating camera interface
- Camera is working properly (raspistill/raspivid works and produces pictures/videos)
- after deactivating the cam in config and rebooting the web interface shows up again

#### System

Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:09:46
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     de (BrowserLang: de-DE)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: HyperBian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by tihoangyeudau** [comment]
watching for this!

**Comment by phluther** [comment]
I can confirm that this is also an issue on the Raspberry Pi Zero W running HyperBian

**Comment by tihoangyeudau** [comment]
> I can confirm that this is also an issue on the Raspberry Pi Zero W running HyperBian. Hyperion Classic works fine with the Pi Camera.

with pi 3b+, there is same issue

**Comment by tihoangyeudau** [comment]
Is there Anyone help us fix this issue. My hyperion.ng on rpi does not find out picam

**Comment by vbier** [comment]
With the current version, the web interface still works after activating the pi camera using raspi-config. But I am not able to use the camera with hyperion.ng, regardless of the settings. The live preview does not show an image at all.

As a workaround, I have started raspivid on my PI with a full screen preview and use the DispmanX grabber to grab the preview instead of directly capturing from the camera. This works.

**Comment by Lord-Grey** [comment]
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by vbier** [comment]
I just installed alpha 10 and can confirm that my raspi camera is now working as usb capture device. Unfortunately there is no way to configure capturing in order to improve image quality. But the original problem is gone.

**Comment by Lord-Grey** [comment]
> there is no way to configure capturing

Did you check, if something is available when you switch to "Expert" Level?
