### ISSUE TITLE
Cross compile instructions are not accurate

### ISSUE THREAD

**Issue by tociek** [hyperion-project/hyperion.ng#84]
Hi,

I've been trying to compile hyperion-ng for RPi on my laptop (ubuntu 14.04). Unfortunately I got stuck at running create_all_releases.sh . I am getting the following error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BCM_INCLUDE_DIR
   used as include directory in directory /home/jacwk/hyperion1/libsrc/grabber/dispmanx
   used as include directory in directory /home/jacwk/hyperion1/src/hyperion-dispmanx
BCM_LIBRARIES
    linked by target "dispmanx-grabber" in directory /home/jacwk/hyperion1/libsrc/grabber/dispmanx

-- Configuring incomplete, errors occurred!
```

I do believe I followed all steps properly including qt5 installation.

Any help would be highly appreciated.
Jacek

**Comment by redPanther** [comment]
the headers for broadcom videochip are missing. Did you follow that instruction in crosscompilehowto:
mkdir -p "$RASCROSS_DIR/firmware"
```
git clone https://github.com/raspberrypi/firmware.git "$RASCROSS_DIR/firmware"
ln -s "$RASCROSS_DIR/firmware/hardfp/opt" "$ROOTFS_DIR/opt"
git clone git://github.com/raspberrypi/tools.git "$RASCROSS_DIR/tools"
```
cmake searches dispmanx headers in "$ROOTFS_DIR/opt"

**Comment by tociek** [comment]
I am quite confident that I did the steps you mentioned, but I will retry in the afternoon and report back.

**Comment by redPanther** [comment]
Verify if desired headers in opt folder. When cmake says xy didn't found. Xy isn't there or cmake search on wrong place.

**Comment by brindosch** [comment]
And the next error you will get is: libdnssd not found :)

**Comment by redPanther** [comment]
Then we need libdnssd.so somwhere in lib path. We have to copy the lib from raspi to /usr/lib

**Comment by brindosch** [comment]
need to check, i rsynced everything and the lib is available, but "not found".

**Comment by redPanther** [comment]
Take a look directly on file system, where this lib is,located. The lib must be somewhere on xour pi, otherwise you aren't sble to compile directly on your pi

**Comment by brindosch** [comment]
Yeah i know, it worked on the pi before, but not at the crosscompile.

**Comment by tociek** [comment]
How do you normally compile hyperion? On pi? I used to do that on pi, but cmake now complains that it lacks qt5 and I was not able to install qt5 via aptitude

**Comment by brindosch** [comment]
Qt5 is not available on  wheezy. You need backports access or jessie

**Comment by brindosch** [comment]
The documentation is laking, cause it is still in early development. This repo should rather be a private repo with dev access :)

You may get further configuration problems sooner or later, i suggest to ask not :)
one person ask -> no problem
more peoples ask -> weird issues answering :)

**Comment by tociek** [comment]
I just wanted to test one of the features you recently added (the one with 'leds' parameter in device section, that is not working globally, not only for apa102). If you want me to wait until it gets to the official release, then fine... I was just eager to see if it really works :)

**Comment by brindosch** [comment]
No problem, due to your workload you should prefer to compile on the pi, you could use another sd card. May be way faster :)

**Comment by tociek** [comment]
That was indeed way easier... but I ran into another problem :)

I wanted to test hyperion on OE and I an got error saying that QT libraries are missing... So i copied them from jessie, but one of them (libQt5SerialPort.so.5) does not exist in /usr/lib/arm-linux-gnueabihf

**Comment by redPanther** [comment]
perhaps lib is located somewhere else? e.g. /usr/lib?

**Comment by tociek** [comment]
That's where I got other qt libraries from, but the one mentioned before  was not there... 

I will check other folders (I assumed that all qt libs would be in single place)

**Comment by tociek** [comment]
Ok, apparently I was blind...

So... after copying several libs, hyperion finally started... and failed, because OE does not have python 3 installed:
```
0-89INFO: Creating linear smoothing
HYPERION (CS) INFO: Created linear-smoothing(interval_ms=50;settlingTime_ms=100;updateDelay=0
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted (core dumped)
```

**Comment by brindosch** [comment]
Did you installed python 3? As far as i know it still 2.7.X default. Use your OE a older version? We talked about this and we keep the python level in sync with kodi to prevent issues

**Comment by tociek** [comment]
I have the latest OE... I saw I have python 3 installed, but I don't know where is came from :) (maybe it's needed for different software). I will play around with it and in case I don't find solution, I will start with Jessie from scratch

**Comment by brindosch** [comment]
a minimal update, but there are still code issues that needs to be pointed out until this is working again.
As this is on the list for travis, i close it :)
