### ISSUE TITLE
Hyperiond won't initialize framegrabber if you enable v4l with no hardware

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#85]
Pi1 with framegrabber and v4lgrabber enabled
No grabbing hardware, no /dev/video
Start hyperiond

An error is logged, but the dispmanx grabber never gets initialized 

I'll look into it later if no one beats me to it

**Comment by brindosch** [comment]
I could confirm this :)

**Comment by redPanther** [comment]
solved ...
