### ISSUE TITLE
Windows autostart feature

### ISSUE THREAD

**Issue by Paulchen-Panther** [hyperion-project/hyperion.ng#851]
#### What problem does this feature solve?

Start Hyperion manually every time

#### What does the proposed API look like?

The installer (NSIS) should write a registry key for the current user or for all users

#### How should this be implemented in your opinion?

https://docs.microsoft.com/en-us/windows/win32/setupapi/run-and-runonce-registry-keys
https://nsis.sourceforge.io/Reference/WriteRegStr

#### Are you willing to work on this yourself?
Maybe 😄

**Comment by brindosch** [comment]
Cool idea, should this be a one time decision (install) or an option for Hyperion to enable/disable the entry whenever wanted?

**Comment by Paulchen-Panther** [comment]
Ideally the second variant

**Comment by brindosch** [comment]
Hm, regedit needs admin. There is another possible solution to use `%appdata%\Microsoft\Windows\Startmenü\Programme\Autostart` and place a link to hyperiond. But the path seems to be lang specific, at least on Win 7.

**Comment by brindosch** [comment]
Forget what i said, 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run' should be always accessible.

**Comment by Paulchen-Panther** [comment]
Or Manifest
https://docs.microsoft.com/en-us/previous-versions/bb756929(v=msdn.10)?redirectedfrom=MSDN#requested-execution-levels

**Comment by Paulchen-Panther** [comment]
The registry should be able to be described in Hyperion mode with the help of QSettings.
https://doc.qt.io/qt-5/qsettings.html

**Comment by brindosch** [comment]
For my second attempt there is another region independent path`C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

Upgrading the manifest to admin is probably a little heavy :)

At least we have now enough hints :)

**Comment by Paulchen-Panther** [comment]
UAC is really simple with Cmake.
https://prnt.sc/t80kce
https://prnt.sc/t80kxb
