### ISSUE TITLE
Few 'bugs' in latest Alpha 6

### ISSUE THREAD

**Issue by iLLiac4** [hyperion-project/hyperion.ng#854]
1. If you install Hyperion Control addon and has two instances (one is adalight and the other is in my example forwarder to esp2866 device) and you disable the option for menu colors in addon, the addon disables both System | Platform Capture: (X11) when you stop video, but when you select a video only System | Platform Capture: (X11) for primary is enabled and the other one is not.

2. Also it would be nice to have an option to zero the stream to adalight device (send black to shut it down). For example even if menu lights are disabled and you press stop in the middle of the video. Ta last colour is then send to device the whole time. If you disable the led device and reenable it then the colors are blanked.

**Comment by tpmodding** [comment]
please use the template and DONT IGNORE IT

thanks!

**Comment by Lord-Grey** [comment]
@iLLiac4 On 2, see #855, when disabling the device it should go black and no updates occur unless you configured a "Refresh time".
