### ISSUE TITLE
Picam can be not used in Hyperion.ng with both of pi zero W and Pi 3B+

### ISSUE THREAD

**Issue by tihoangyeudau** [hyperion-project/hyperion.ng#856]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Picam can be not used in Hyperion.ng with both of rpi zero W and Pi 3B+

#### What is expected?
rpi can detect and grabber via Picam module

#### What is actually happening?
rpi just detect module name "camera 0" then can not grabber it, there is not any chooses for it

#### System

Hyperion Server: 
- Build time:  Jun 29 2020 12:45:45
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: en-CA)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS:
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**Comment by Crazor** [comment]
So what's the solution here, since it was closed??
