### ISSUE TITLE
Provide App Window

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#857]
## Feature request

Is there a need for an app window for desktop users? Express your opinion :)
![webview](https://user-images.githubusercontent.com/15967679/86152025-e040ee80-baff-11ea-9933-2a6e8fdb63dc.PNG)

#### Are you willing to work on this yourself?
yes

**Comment by Paulchen-Panther** [comment]
Wenn es an das SysTray gebunden ist, sollte es IMHO keine Einwände geben.

**Comment by brindosch** [comment]
Es gibt leider einen blöden Nebeneffekt. Es benötigt einen Haufen Speicher (bundled Chromium). Bin daher etwas hin und her gerissen. Eigentlich ist es bloat, wenn man es nicht nutzt.

**Comment by emddummi** [comment]
Zu viel wenn man eh alles per webif macht...

**Comment by brindosch** [comment]
Windows 10 with MS Edge or better the [Chromium Edge](https://www.microsoft.com/en-us/edge) might be worth a try. If used through [webview](https://github.com/webview/webview).

Fun fact is that Qt support Android and iOS to use the system webview, but not the desktop platforms. Uuh "Hyperion on Android"
