### ISSUE TITLE
Service filename 

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion.ng#86]
The service is not a script. You should rather name it hyperiond.service. Or use if this gives problem with the init scripts use hyperiond.systemd.service.

In the install script I also suggest to name the service hyperiond and not just hyperion. This is a common practise and also the binary itself is also called hyperiond.

**Comment by penfold42** [comment]
Agree

**Comment by NicoHood** [comment]
I also suggest to:
* Remove all service files from the `make install` command
* Or place the correct service file into the correct directory

Having the services in an "useless" directory for other systems as well makes less sense to me.

**Comment by redPanther** [comment]
Naming ... ok, but not always filename and service name matches (like httpd versus apache2). The other files don't harm. If we don't wan't 'useless' service files hyperion shouldn't have any service files and the distribution package has to add this. 
But I think this is lowest prio, we have more serious stuff todo and installation process works so far.

**Comment by NicoHood** [comment]
Yes I suggest to remove them from `make install` but package them with `make deb` or whatever this command is.

In my PKGBUILD is use:
```
        make install
	install -Dm 644 "${srcdir}/hyperion/config/hyperion.config.json.default" "${pkgdir}/etc/hyperion/hyperion.config.json"
	install -Dm 644 "${srcdir}/hyperion/bin/service/hyperion.systemd.sh" "${pkgdir}/usr/lib/systemd/system/hyperiond.service"
	rm -rf "${pkgdir}/usr/share/hyperion/service"
```

Maybe you could add a label to some issues which are minor. I aggree that this is not important for now. But maybe it would still make sense to change it before the first release, as then no paths/names are broken in future versions.

**Comment by brindosch** [comment]
At least the install.sh reanme it during c/p and delete the service directory. I don't know why the name ending matters that much.
Now we have 2 systemd files. We need to rename them anyway during install. And to be honest, as redPanther already said. There is enough to do, is a service file name really a problem?

**Comment by NicoHood** [comment]
I know that this is minor, but a .sh is just wrong and confusing (the people in the archlinux irc pointed that out). We need to rename it anyways, true. But it would at least be less confusing as its no script.

Its low priority for sure. And I know you have other TODOs. I just noted this bug, no need to hurry.
I know that you'd be happy for more contributions, i know. But I currently dont have the time. But I try to file all bugs I find, dont missunderstand me just  because I file a lot of bugs. I might fix it though If i find the time or it bugs me too much.

**Comment by redPanther** [comment]
source files stay on current naming schema. The debian package (and the future install script for +elec) will rename the file into something appropriate. The service itself is renamed to hyperiond, like suggested
