### ISSUE TITLE
Serial device detection broken on Linux

### ISSUE THREAD

**Issue by oCanna** [hyperion-project/hyperion.ng#865]
- [x] I confirm that this is an issue rather than a question.

## Bug report

> [hyperiond LEDDEVICE] <INFO> LedDevice 'adalight' found.
> [hyperiond LEDDEVICE] <INFO> Opening UART: /dev/ttyACM0
> [hyperiond LEDDEVICE] <ERROR> Device disabled, device 'adalight' signals error: 'Invalid serial device name: [/dev/ttyACM0]!'
> [hyperiond LEDDEVICE] <ERROR> Device disabled, device 'adalight' signals error: 'Error opening device!'

The serial device detection was working prior this commit: e365a2839d327c9f6e3836e7f4c5e552522df425

#### Steps to reproduce
On a linux system, try to connect led hardware through a serial interface.

#### What is expected?
A working serial device detection.

#### What is actually happening?
ping @heikobihr 

#### System
Hyperion Server: 
- Build:       master (GitHub-922420bb/6cf9dfaa-1593464112)
- Build time:  Jul  5 2020 16:42:12
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: de)
- UI Access:   expert
- Avail Capt:  v4l2,framebuffer,x11,qt

Hyperion Server OS: 
- Distribution: Ubuntu 20.04 LTS
- Arch:         x86_64
- Kernel:       linux (5.4.0-40-generic (WS: 64))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by Lord-Grey** [comment]
Duplicate to #859, Fix is part of #855.
Immediate workaround is just using the portable without /dev/, i.e. ttyACM0 only.
