### ISSUE TITLE
Controlling Hyperion with TV remote

### ISSUE THREAD

**Issue by m-seker** [hyperion-project/hyperion.ng#878]
## Feature request

If all goes well with https://github.com/hyperion-project/hyperion.ng/pull/877/files , we can start benefiting more from CEC.

What about providing an API to get notified when there is a certain event on HDMI bus that I'm interested in ?
Eg : Users can listen for key press events of their remote and change colors/effects accordingly.

#### What problem does this feature solve?
Users can use their remote to control Hyperion

#### What does the proposed API look like?
Not clear, open to suggestion
#### How should this be implemented in your opinion?
Not clear, open to suggestion
#### Are you willing to work on this yourself?
Maybe

More to consider : What happens on a system with Kodi ? Kodi also uses CEC.

**Comment by tpmodding** [comment]
@m-seker can we close this?
