### ISSUE TITLE
Missing enable/disable setting in config

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion.ng#88]
You can disable some part of the config without commenting now which is great.

```
	"webConfig" :
	{
    	"enable" : true,
    	"document_root" : "/usr/share/hyperion/webconfig",
    	"port" : 8099
	},
```

However not all settings can be disabled and I want to disable more of them. Since commenting now should not be used anymore, I am not sure if simply adding "enable" would work. But even if so, the default config should has this setting, possibly set to true or false.

**Comment by penfold42** [comment]
I'm
In the middle of adding it to the forwarder config

**Comment by redPanther** [comment]
Webserver shouldn.t be disabled, because it is main configuration and user interface.

Please don't open issues for things we already have open issues.

**Comment by NicoHood** [comment]
Why? I personally do not need a webserver (which is vulnearable).

But this issue more focussed on the settings that do not have an "enable" section.
If its a duplicate mark it as so and reference the original issue.

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion.ng/issues/3
