### ISSUE TITLE
Raspberry pi 1 B crash on reboot after install [

### ISSUE THREAD

**Issue by Tom-Neverwinter** [hyperion-project/hyperion.ng#891]
latest release version confirmed.

"Please confirm you will submit an issue."
uh? that's why i'm here, right?  

- [x] I confirm that this is an issue rather than a question.

we get it, questions will be closed.

## Bug report
Raspberry pi 1 B crash on reboot after install

following this tutorial:
https://www.youtube.com/watch?v=urOEHzbV48A

using the official raspberry os install method:
https://www.raspberrypi.org/documentation/installation/installing-images/

and using "raspberrypi os other" "raspberry pi os lite 32bit"

#### Steps to reproduce
install raspberry pi os other lite 32bit

sudo apt-get update
sudo apt-get upgrade
cat /proc/cpuinfo [to find your arm architecture]
https://github.com/hyperion-project/hyperion.ng/releases
 
download hyperion:
wget https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.6/Hyperion-2.0.0-alpha.6-Linux-armv6l.deb

install hyperion
sudo dpkg -i Hyperion-2.0.0-alpha.6-Linux-armv6l.deb
before reboot open "ipaddress":8090  after reboot works perfectly

REBOOT

open "ipaddress":8090  after reboot FAILs to load

#### What is expected?
website loads properly.

#### What is actually happening?
hyperion website fails to load.

#### System

how about a cmd line version. Ironically my issue is literally getting to the web interface.... dont feel like re-installing again. 

Phil Harris:
Same issue here on a RPi 3 Model B ... Hyperion installs but no web interface on either port 8090 or 8091. About to try using the non-lite version of Pi OS (OK ... tried that and no web interface either) and then I'll give it a go on an RPi4...

**Comment by heytcass** [comment]
Same issue with RPi 4 1GB and RPi 3 B+.

**Comment by m-seker** [comment]
@Tom-Neverwinter  @heytcass  Can you run hyperion manually(hyperiond -d) and paste the output here ? Sounds like a major issue but we don't see it in master.

**Comment by heytcass** [comment]
`pi@hyperion:~ $ hyperiond -d
[hyperiond MAIN] <INFO> Set user data path to '/home/pi/.hyperion'
[hyperiond DAEMON] <DEBUG> <PythonInit.cpp:45:PythonInit()> Initializing Python interpreter
[hyperiond SettingsManager] <DEBUG> <SettingsManager.cpp:108:SettingsManager()> Settings database initialized
[hyperiond EFFECTFILES] <INFO> 39 effects loaded from directory :/effects/
[hyperiond EFFECTFILES] <INFO> 22 effect schemas loaded from directory :/effects/schema/
[hyperiond EFFECTFILES] <INFO> 0 effects loaded from directory /home/pi/.hyperion/custom-effects
[hyperiond SettingsManager] <DEBUG> <SettingsManager.cpp:108:SettingsManager()> Settings database initialized
[hyperiond BLACKBORDER] <DEBUG> <BlackBorderProcessor.cpp:65:handleSettingsUpdate()> Set mode to: default
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> Blackborder detector: enabled
[hyperiond DAEMON] <INFO> set screen capture device to 'dispmanx'
[hyperiond DISPMANXGRABBER] <DEBUG> <Grabber.cpp:34:setVideoMode()> Set videomode to 0
[hyperiond DISPMANXGRABBER] <INFO> Display opened with resolution: 4x1053347956
[hyperiond DISPMANXGRABBER] <DEBUG> <Grabber.cpp:83:setWidthHeight()> Set new width: 80, height: 45 for capture
[hyperiond DAEMON] <INFO> DISPMANX frame grabber created
[hyperiond V4L2:auto] <DEBUG> <Grabber.cpp:34:setVideoMode()> Set videomode to 0
[hyperiond LEDDEVICE] <INFO> LedDevice 'file' found.
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> Smoothing: enabled
[hyperiond FLATBUFCONNECTION] <INFO> Connecting to Hyperion: 127.0.0.1:19401
[hyperiond EFFECTENGINE] <INFO> Run effect "Rainbow swirl fast" on channel 0
[hyperiond EFFECTENGINE] <DEBUG> <EffectEngine.cpp:183:runEffectScript()> Start the effect: name [Rainbow swirl fast], smoothCfg [2]
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:158:registerInput()> Register new input 'System/EFFECT' with priority 0 as inactive
[hyperiond HYPERION] <INFO> Initial foreground effect 'Rainbow swirl fast' started
[hyperiond EFFECTENGINE] <INFO> Run effect "Warm mood blobs" on channel 254
[hyperiond EFFECTENGINE] <DEBUG> <EffectEngine.cpp:183:runEffectScript()> Start the effect: name [Warm mood blobs], smoothCfg [2]
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:158:registerInput()> Register new input 'System/EFFECT' with priority 254 as inactive
[hyperiond HYPERION] <INFO> Inital background effect 'Warm mood blobs' started
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:158:registerInput()> Register new input 'System/GRABBER' with priority 250 as inactive
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> Framegrabber: enabled
[hyperiond BOBLIGHT] <DEBUG> <BoblightServer.cpp:28:BoblightServer()> Instance created
[hyperiond ComponentRegister] <DEBUG> <ComponentRegister.cpp:36:setNewComponentState()> LED device: enabled
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:198:setInput()> Priority 254 is now active
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 0
[hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 0 is now active
Killed
`

"Killed" happened on its own with no input from me. Also made sure I tried loading frontend before it was killed, still nothing.

**Comment by m-seker** [comment]
@heytcass Thanks for the logs. Unfortunately right now they don't seem to tell anything. My suggestion would be waiting a bit until Alpha7 is released(pretty soon I assume) and to see if we can reproduce it. Even if it is not resolved with Alpha7, it will hopefully tell us more about the reason of the problem you experience.

PS: I also can provide a release from latest master if you are eager to try before release.

**Comment by Bassfiend** [comment]
Hi Guys,

OK so confirmed with both a Pi Model 3 B+ and a 2GB Pi 4 using PiOS Lite, PiOS Full and PiOS 64bit...

@m-seker - Are we the first people to have this issue or have you seen it from anywhere else? If it's just us then there must be something that we're doing that is different or causing the issue, no?

Cheers

Bassfiend / Phil Harris

**Comment by heytcass** [comment]
@Bassfiend Makes me wonder if there has been something updated recently that broke something since we're all running apt update and upgrade now.

**Comment by heytcass** [comment]
@m-seker I wouldn't mind giving the master build a go, maybe it can help clear something up before Alpha 7 comes out?

**Comment by m-seker** [comment]
@heytcass  Perfect. You can try the following :

https://wetransfer.com/downloads/ccbd91ea3628703225bb634d40362c9a20200722131828/69ba2e0b42783ce6b115cd405e0cb19e20200722131909/9cf55f

It should hopefully print more detailed logs. Size of the file is a bit on the bigger size(116MB) since it includes debug symbols. I may ask you to run hyperion with gdb unless we find something useful in the logs.

**Comment by m-seker** [comment]
Btw looking again, it doesn't look like a crash. We should probably have seen SIGABRT or SIGSEGV. Killed means someone is killing it, unless we are sending SIGKILL from within Hyperion, which is not the case.

**Comment by Bassfiend** [comment]
> @Bassfiend Makes me wonder if there has been something updated recently that broke something since we're all running apt update and upgrade now.

@heytcass - OK - I'll try it without an upgrade pass...

Hmmm ... installed clean OS but *DIDN'T* do the update pass and i get the web config page coming up so it seems to be linked to the latest Pi update.

**Comment by heytcass** [comment]
I was able to get the web interface to load with an apt update/upgrade pass, until I rebooted, and that killed the page. So the issue seems to be with the reboot.

**Comment by heytcass** [comment]
Ah ha! Seems to be a memory issue. This is on my RPi 4 1GB. Ran dmesg immediately after a reboot, on a fresh PiOS Lite image, where Hyperion is the only thing running.

```
pi@raspberrypi:~ $ dmesg | grep hyperion
[   70.224839] [    558]  1000   558   240328   173278  1761280    24379             0 hyperiond
[   70.224857] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=hyperiond,pid=558,uid=1000
[   70.224900] Out of memory: Killed process 558 (hyperiond) total-vm:961312kB, anon-rss:693112kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1720kB oom_score_adj:0
[   70.299315] oom_reaper: reaped process 558 (hyperiond), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[  123.297533] [    576]  1000   576   266728   203026  1982464    22495             0 hyperiond
[  123.297545] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=hyperiond,pid=576,uid=1000
[  123.297665] Out of memory: Killed process 576 (hyperiond) total-vm:1066912kB, anon-rss:812104kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1936kB oom_score_adj:0
[  123.435979] oom_reaper: reaped process 576 (hyperiond), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[  157.848691] [    587]  1000   587   227920   162093  1646592    22467             0 hyperiond
[  157.848715] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=hyperiond,pid=587,uid=1000
[  157.848801] Out of memory: Killed process 587 (hyperiond) total-vm:911680kB, anon-rss:648372kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1608kB oom_score_adj:0
[  157.984240] oom_reaper: reaped process 587 (hyperiond), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[  192.571557] hyperiond invoked oom-killer: gfp_mask=0x400dc2(GFP_KERNEL_ACCOUNT|__GFP_HIGHMEM|__GFP_ZERO), order=0, oom_score_adj=0
[  192.571567] CPU: 1 PID: 601 Comm: hyperiond Tainted: G         C        5.4.51-v7l+ #1326
[  192.572083] [    601]  1000   601   215281   149231  1540096    22047             0 hyperiond
[  192.572126] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=hyperiond,pid=601,uid=1000
[  192.572174] Out of memory: Killed process 601 (hyperiond) total-vm:861124kB, anon-rss:596672kB, file-rss:252kB, shmem-rss:0kB, UID:1000 pgtables:1504kB oom_score_adj:0
[  192.648442] oom_reaper: reaped process 601 (hyperiond), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
@Bassfiend Can you do the same on your 2GB model?

cc: @m-seker

**Comment by Bassfiend** [comment]
@heytcass - Will do ... just going to run the following through:

For each of 3B+, 4 2GB and 4 4GB....

1) Fresh "Lite" install
2) Install Hyperion
3) Reboot
4) Confirm web interface still exists
5) Update
6) Confirm web interface still exists
7) Reboot
8) Confirm web interface still exists

**Comment by m-seker** [comment]
I checked my Pi4 2GB, hyperion uses around 1.3Gb, so we figured the root cause, now time to figure out how we can decrease it.

**Comment by heytcass** [comment]
@m-seker Interesting. Especially because according to @Bassfiend 's comment [here](https://github.com/hyperion-project/hyperion.ng/issues/891#issuecomment-662417257) it didn't work on his 2Gb model. I am also very curious about how [Dr Zzs](https://github.com/snipercaine) ever got it working on his Pi 3 in the video linked in the original post.

Also a shame that I have a **big** Amazon delivery today with a splitter, LEDs, etc that I'm going to have to explain to my wife, without being able to use it as a justification immediately. 😂 Also would rather not burn my 8GB Pi just for running Hyperion. Hmmm...

**Comment by Bassfiend** [comment]
Odd that it runs fine, surviving reboots *UNTIL* you do an apt-get update / apt-get upgrade / reboot pass though...

I've checked this so far on my 3B+ and rebooting the Pi is fine *UNTIL* you do the update then on the next reboot it stops working!

If you've found the cause then is it worth me testing further?

@heytcass - I get no results from "dmesg | grep hyperion"...

**Comment by heytcass** [comment]
@Bassfiend Even after the reboot?

**Comment by Bassfiend** [comment]
@heytcass - I reckon there's something very recent slipped into the OS update which wasn't there a couple of days ago when he did the recording.

@heytcass - Yup - even after the reboot...

**Comment by Bassfiend** [comment]
Just rebooted 3B+ again before running update ...

pi@raspberrypi:~ $ dmesg | grep hyperion
[    3.453717] systemd[1]: Created slice system-hyperiond.slice.
pi@raspberrypi:~ $

**Comment by m-seker** [comment]
@heytcass No worries just stall your wife while we are investigating it :D

**Comment by Bassfiend** [comment]
@heytcass - I reckon that's @m-seker offering to buy dinner... ;-)

**Comment by Bassfiend** [comment]
Right - now the 2GB Pi4...

Fresh "Lite" install

wget https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.6/Hyperion-2.0.0-alpha.6-Linux-armv7l.deb

sudo dpkg -i Hyperion-2.0.0-alpha.6-Linux-armv7l.deb

Web interface up and running.

dmesg | grep hyperion

pi@raspberrypi:~ $ dmesg | grep hyperion
pi@raspberrypi:~ $

run sudo reboot

Web interface still working.

pi@raspberrypi:~ $ dmesg | grep hyperion
[ 3.453717] systemd[1]: Created slice system-hyperiond.slice.
pi@raspberrypi:~ $

run sudo apt-get update / sudo apt-get upgrade

Web interface still working

sudo reboot

No more web interface

login as: pi
pi@192.168.0.70's password:
Linux raspberrypi 5.4.51-v7l+ #1326 SMP Fri Jul 17 10:51:18 BST 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jul 22 16:27:07 2020 from 192.168.0.66

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ dmesg | grep hyperion
pi@raspberrypi:~ $ 

So on the Pi4 2GB I'm no longer seeing anything from hyperion with the dmesg | grep hyperion command...

**Comment by m-seker** [comment]
@Bassfiend can you try with the binary I uploaded above ?

**Comment by Bassfiend** [comment]
> @Bassfiend can you try with the binary I uploaded above ?

I'll try - I'm a Windows boy though so I haven't a bloody clue how to find anything in the filesystem of a Pi!

**Comment by Paulchen-Panther** [comment]
@Bassfiend In the last release there were problems with the V4L2 grabber. (new BCM2835 ISP Device) As a result, the WebUI was no longer accessible. But these have already been fixed.
More information here: https://github.com/hyperion-project/hyperion.ng/issues/819

**Comment by Bassfiend** [comment]
> @Bassfiend In the last release there were problems with the V4L2 grabber. (new BCM2835 ISP Device) As a result, the WebUI was no longer accessible. But these have already been fixed.
> More information here: #819

Erm - thanks - don't think this is anything to do with what we're seeing here though...

Phil

**Comment by Paulchen-Panther** [comment]
@Bassfiend 
Hyperion scans the system for cameras to make them available in the WebUI. In the last release there was no new BCM2835 ISP driver. The RPi upgrade only came afterwards. Hyperion was stuck in a loop, making the WebUI unreachable. Just test the @ m-seker build. thank you

**Comment by heytcass** [comment]
@m-seker @Paulchen-Panther @Bassfiend Working on flashing the new build now.

**Comment by Bassfiend** [comment]
> @Bassfiend
> Hyperion scans the system for cameras to make them available in the WebUI. In the last release there was no new BCM2835 ISP driver. The RPi upgrade only came afterwards. Hyperion was stuck in a loop, making the WebUI unreachable. Just test the @m-seker build. thank you

So when you say "last release" do you mean of Hyperion or of the PiOS update / upgrade package?

I'll try to use the file @m-seker linked to but I am not a Linux person I'm afraid so finding my way round the Linux filesystem is like bumbling around a maze in the dark - I have it copied to my root though and I'll try installing it in a minute as soon as I have finished confirming the same on a 4GB Pi4...

P

**Comment by Paulchen-Panther** [comment]
@Bassfiend No panic. The new Alpha 7 is not long in coming

**Comment by Bassfiend** [comment]
> @Bassfiend No panic. The new Alpha 7 is not long in coming

Thanks - I'll try to use the file if I can work it out ... be good to get it quashed before the next public upload. :-)

**Comment by m-seker** [comment]
> > @Bassfiend
> > Hyperion scans the system for cameras to make them available in the WebUI. In the last release there was no new BCM2835 ISP driver. The RPi upgrade only came afterwards. Hyperion was stuck in a loop, making the WebUI unreachable. Just test the @m-seker build. thank you
> 
> So when you say "last release" do you mean of Hyperion or of the PiOS update / upgrade package?
> 
> I'll try to use the file @m-seker linked to but I am not a Linux person I'm afraid so finding my way round the Linux filesystem is like bumbling around a maze in the dark - I have it copied to my root though and I'll try installing it in a minute as soon as I have finished confirming the same on a 4GB Pi4...
> 
> P

You don't need to install it. Just extract the archive and run the binary inside bin/

**Comment by heytcass** [comment]
`./hyperiond: error while loading shared libraries: libcec.so.4: cannot open shared object file: No such file or directory`

**Comment by Paulchen-Panther** [comment]
sudo apt-get install libcec-dev

**Comment by heytcass** [comment]
Ah. The "-dev" is what I was missing. Thanks.

**Comment by heytcass** [comment]
`./hyperiond: error while loading shared libraries: libGLdispatch.so.0: cannot open shared object file: No such file or directory`

Is it looking for an X server? Is the fact that I'm on PiOS Lite an issue?

**Comment by tpmodding** [comment]
Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51-v7+ (WS: 32))

have no issues.... will test with a 1b too

**Comment by Bassfiend** [comment]
I’d best leave it till the Alpha pops up as I don’t know enough command line Linux not to be a liability going forward ... meddle not in the affairs of dragons if thou art crunchy and taste good with ketchup. 😜

**Comment by heytcass** [comment]
Don't know why I didn't think of this until now, but here is the list of things getting upgraded with apt:
```

pi@hyperion:~ $ apt list --upgradable
Listing... Done
ca-certificates/stable 20200601~deb10u1 all [upgradable from: 20190110]
firmware-atheros/testing 1:20190114-1+rpt7 all [upgradable from: 1:20190114-1+rpt6]
firmware-brcm80211/testing 1:20190114-1+rpt7 all [upgradable from: 1:20190114-1+rpt6]
firmware-libertas/testing 1:20190114-1+rpt7 all [upgradable from: 1:20190114-1+rpt6]
firmware-misc-nonfree/testing 1:20190114-1+rpt7 all [upgradable from: 1:20190114-1+rpt6]
firmware-realtek/testing 1:20190114-1+rpt7 all [upgradable from: 1:20190114-1+rpt6]
libgnutls30/stable 3.6.7-4+deb10u4 armhf [upgradable from: 3.6.7-4+deb10u3]
libraspberrypi-bin/testing 1.20200717-1 armhf [upgradable from: 1.20200512-2]
libraspberrypi-dev/testing 1.20200717-1 armhf [upgradable from: 1.20200512-2]
libraspberrypi-doc/testing 1.20200717-1 armhf [upgradable from: 1.20200512-2]
libraspberrypi0/testing 1.20200717-1 armhf [upgradable from: 1.20200512-2]
raspberrypi-bootloader/testing 1.20200717-1 armhf [upgradable from: 1.20200512-2]
raspberrypi-kernel/testing 1.20200717-1 armhf [upgradable from: 1.20200512-2]
raspi-config/testing 20200707 all [upgradable from: 20200515]
rpi-eeprom-images/testing 7.8-1 all [upgradable from: 7.0-1]
rpi-eeprom/testing 7.8-1 all [upgradable from: 7.0-1]
```
Anything suspicious in there?

**Comment by Paulchen-Panther** [comment]
@heytcass 
Please test this (armv6hf) artefact:  https://github.com/hyperion-project/hyperion.ng/actions/runs/177653687

**Comment by jaffacake** [comment]
Same issue here on a fresh raspbian install on a Pi 3 B+ seems to run out of memory in all instances for me 😢 I did an apt-get upgrade before installing hyperion too.

@Paulchen-Panther just tried the armv7 artifact from that build and it looks like it solved it for me, it's no longer crashing and can get into the web ui!

**Comment by Paulchen-Panther** [comment]
> 2020-07-22T20:33:49.388 hyperiond DAEMON       : <ERROR> The dispmanx framegrabber can not be instantiated, because it has been left out from the build

Are you sure you took an arm packet?

**Comment by jaffacake** [comment]
Yeah, I downloaded armv7hf.zip & unpacked to Hyperion-2.0.0-alpha.6-PR#894-Linux-armv7l

**Comment by Paulchen-Panther** [comment]
Ok. I'm just looking at what it is.

**Comment by jaffacake** [comment]
Hyperion mostly seems to be working, but it's the first time I've set it up & used it. Looks like my video 2 USB grabber is working & hyperion is picking up the video stream.

Only issue I've got is that the entertainment area is configured & apparently streaming but the lights are unresponsive 😢 Guessing it might be an unrelated issue but just an FYI

**Comment by jaffacake** [comment]
Oh actually ignore the entertainment issue, looks like they are working, just really dim.

**Comment by Paulchen-Panther** [comment]
Problem for deactivated DispmanX Grabber found. Fix is comming

**Comment by jaffacake** [comment]
Has this been resolved? I just saw an update on the latest release. Just wondering as I'm still running using the build you linked to & not a proper release.

**Comment by Paulchen-Panther** [comment]
> Has this been resolved?

Yes. Please use official alpha 7 release to test

**Comment by tpmodding** [comment]
@Paulchen-Panther schliessen?

**Comment by Paulchen-Panther** [comment]
> @Paulchen-Panther schliessen?

Ja
