### ISSUE TITLE
Hyperiond locate all memory 

### ISSUE THREAD

**Issue by bruesche** [hyperion-project/hyperion.ng#893]
Hi there,
After i updated to the latest packages from raspianbuster my Hyperion allocated all of the memory of my Raspberry pi. I stopped the service and everything is ok. But when I start my hyperiond the process catch all the memory. What can I do? On the same pi I ran deconz and so after hyperion started the server has no response because of running out of memory. 

Please help.

Thx 

P.s.: running latest version of HyperionNG Alpha 2.0.6

**Comment by tpmodding** [comment]
Alpha 7 is near, should fix some issues, could you wait till it is released and then recheck with it please?

Thank you!

**Comment by bruesche** [comment]
How long must I wait? A week is no problem...

**Comment by bruesche** [comment]
And how can I update then?

**Comment by bruesche** [comment]
The webinterface is not functional. Hyperiond is started but interface not reachable

**Comment by bruesche** [comment]
Started but process get all memory

**Comment by tpmodding** [comment]
This is no chat...

**Comment by tpmodding** [comment]
please fill out the issue template and dont ignore it!
