### ISSUE TITLE
random colors in each led.

### ISSUE THREAD

**Issue by juanesf** [hyperion-project/hyperion.ng#897]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I just compiled and installed Hyperion, nothing abnormal. but when I try to use hyperion app android the LEDs light up randomly except for the first one. It is worth mentioning that the effects and the usb capture work without problems.
Edit:
- Compiled from source

#### Steps to reproduce
- install hyperion-free from Google Play Store (https://play.google.com/store/apps/details?id=nl.hyperion.hyperionfree)
- add hyperion server ip address.
- test effects (work well)
- test static color (red, green, blue)

#### What is expected?
solid colors along the led tape
![Screenshot_20200722-224911_Hyperion Free](https://user-images.githubusercontent.com/19717636/88288377-b1aed180-ccc1-11ea-9cfe-d46fbdad246b.jpg)

#### What is actually happening?
random colors in each led.
![20200722_224808](https://user-images.githubusercontent.com/19717636/88288117-4e24a400-ccc1-11ea-838d-3492de80d3e7.jpg)
![20200722_224737](https://user-images.githubusercontent.com/19717636/88288201-6c8a9f80-ccc1-11ea-8614-bd1bc1c76bcf.jpg)

#### System
Hyperion Server: 
- Build:       master (GitHub-6179ec73/df0d411b-1595434539)
- Build time:  Jul 23 2020 02:17:17
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: es-419)
- UI Access:   default
- Avail Capt:  v4l2,framebuffer,x11,qt

Hyperion Server OS: 
- Distribution: Ubuntu 20.04 LTS
- Arch:         arm
- Kernel:       linux (5.7.7-sunxi (WS: 32))
- Browser:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML)

**Comment by tpmodding** [comment]
What happens if you use the hyperion webinterface to change colors or effects?
also i have seen you are using a nodemcu to controll...which software do you have on your nodemcu? AND you dont have a level shifter, nor a capacitor for the nodemcu...am i right? those are a lot of things which come together.... could you recheck everything...

**Comment by juanesf** [comment]
- when using the interface only the effects work well, the colors have the same problem in the application and web-ui.
Effects:
![Screenshot_20200723-093940_Chrome](https://user-images.githubusercontent.com/19717636/88294662-8a103700-ccca-11ea-85e6-0f49b38b7874.jpg)
![20200723_094003_1](https://user-images.githubusercontent.com/19717636/88294825-b461f480-ccca-11ea-87f3-331fb68daea6.gif)

Colors:
![Screenshot_20200723-094236_Chrome](https://user-images.githubusercontent.com/19717636/88294902-c2b01080-ccca-11ea-87d0-3a0937899f26.jpg)
![20200723_094313](https://user-images.githubusercontent.com/19717636/88294994-db202b00-ccca-11ea-88a0-2ed0ac1f0b89.jpg)



- the firmware on nodemcu is WLED (https://github.com/Aircoookie/WLED)

- I have a 5 volt source for led and nodemcu, working without problems for at least two years with the same type of configuration. (migrated from diyhue to wled)

- problem appeared after merge # 875 (https://github.com/hyperion-project/hyperion.ng/pull/875)

**Comment by tpmodding** [comment]
Ok, then i would ask you to wait till alpha7, in alpha 7 we have implemented wled as a own device

which led device settings did you use?

**Comment by juanesf** [comment]
I have used both instances, before raw udp. and now wled and rawudp with the same results.

**Comment by juanesf** [comment]
I want to try the installation before commit: https://github.com/hyperion-project/hyperion.ng/pull/875

**Comment by juanesf** [comment]
![Screenshot_20200724-093420_Chrome](https://user-images.githubusercontent.com/19717636/88396896-2a309380-cd91-11ea-908b-1398e7c8efd5.jpg)
![20200724_093442](https://user-images.githubusercontent.com/19717636/88396919-31f03800-cd91-11ea-8b18-00757abebadb.jpg)

Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 21:11:33
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: es-419)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Ubuntu 20.04.1 LTS
- Arch:         arm
- Kernel:       linux (5.7.7-sunxi (WS: 32))
- Browser:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML)

**Comment by m-idler** [comment]
Got the same issue with a fresh HyperBian setup. Effects work wonderful, solid colors lead to the same random led behaviour. Can i support anyhow?

**Comment by dvd77** [comment]
Same here... with alpha 6 everything is ok, in v7 its not.
Example : when RGB byte order is started ( solid color) random leds are turned on in different colors 

My hw setup : apa102 connected via wled, raspberrypi 0w

**Comment by tpmodding** [comment]
Hey, please dont get me wrong but "i doesnt work now" is something where i think "no infos, no config nothing...i can do nothing with those informations...just ignore it"
i think we have good developers which do awesome work and always try to fix problems as soon as posible, but to do this we need debug logs, and a loooot more information....so if you want to help us and if you want that we help you, please use our github issue template, give us more infos and more logs that so that we can all work together. Regards TP

**Comment by Lord-Grey** [comment]
@juanesf I confirm that is a bug in the setColor routine.

**Comment by Joeboyc2** [comment]
I've got the same issue too using apa102s.
I've also found that I can't turn the leds off atall so I've had to switch the led device option off in remote control when I switch the tv off

**Comment by RaymondMouthaan** [comment]
Saw same behaviour too using a ws2815b

**Comment by Joeboyc2** [comment]
Ive gone back to alpha 6 and all is working just fine

**Comment by jonwilliams84** [comment]
Same issue here with WLED or udpe131.

Effects work fine but solid colours results in random colours for each led.

On a side-note is there anyway that the colour I set directly in WLED can have a higher priority than that set in Hyperion? Or someway of syncing the two, so if I change the colour in WLED, the colour / effect is updated in Hyperion?

**Comment by tpmodding** [comment]
@jonwilliams84 nope, udp-incoming data > everyhting else, but this is more related to wled

**Comment by jonwilliams84** [comment]
I am thinking that maybe a 'sync' endpoint / listener on hyperion that maybe WLED could post changes to / current settings upon change...that way any colours set from WLED directly could be reflected in hyperion.  I understand that this would also require buy-in from the WLED project to add code to their app too.

**Comment by drew-holt** [comment]
#906 resolved this for me setting solid colors in the web-ui, hyperion android app, and home assistant. thanks!

**Comment by juanesf** [comment]
Same for me

**Comment by maltonic** [comment]
> #906 resolved this for me setting solid colors in the web-ui, hyperion android app, and home assistant. thanks!

Hi, i'm having the same problem with hyperbian, but i don't know exaclty how to solve this with #906 . Can you tell me what steps i need to do precisely? thank you
