### ISSUE TITLE
Windows Adalight USB not working

### ISSUE THREAD

**Issue by Rickexe** [hyperion-project/hyperion.ng#899]
Hello, 

This is not really a bug report it's more like a question but it gave me no other option. I am trying to control my usb led strip which I have previously used with linux based hyperion installs. In linux I used to set the device output option to /dev/ttyUSB0 and it worked. Now I am trying to make it work on a windows installation of hyperion but the same device output doesn't seem to work. In the logs it simply says it can't find the output device. 

I have tried running ubuntu of an external ssd with hyperion installed on it and it was working fine on that same machine I tried it on with windows. Neither ACM0 or USB0 work. 

Are these the only two device output options there are? Does anyone know how to get usb led devices to work on windows?

Thanks in advance

**Comment by tpmodding** [comment]
I would kindly ask you on the forum for support...

but on windows you have to use the COM ports...
