### ISSUE TITLE
Move component X to QT

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#9]
- [x] UDP (led) device
- [x] serial 
- [ ] JSON (in progress)
- [x] Command Line Parser

If there is more, just write it down

**Comment by redPanther** [comment]
you can check "serial"

**Comment by Paulchen-Panther** [comment]
Json

**Comment by Paulchen-Panther** [comment]
getoptplusplus

**Comment by redPanther** [comment]
@brindosch  I updated your initial post, I hope that was ok ...

**Comment by brindosch** [comment]
Thats great, thank you :)
