### ISSUE TITLE
make install always rebuilds the package

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion.ng#90]
I am not sure if this is a bug or an issue/feature of the cmake system in general. If you run `make install` It does not simply abort (if it was compiled before), it tries to compile again. Its super fast, but still not correct. This is minor though, but maybe the fix is triviial.

**Comment by redPanther** [comment]
Its s normal behaviour of automake since ages/forever. If you intrested how it works learn how cmake, make tools and our cmake scripts work. To much to describe here ...

**Comment by NicoHood** [comment]
Okay. If it cannot be further improved, I will close this. Thanks :)
