### ISSUE TITLE
Alpha7 bug report.

### ISSUE THREAD

**Issue by T-IOOO** [hyperion-project/hyperion.ng#901]
I just installed Alpha7. Backlight is no longer working. It looks more like a dimmed version of "mood blobs". Can someone confirm same issue?

**Comment by Paulchen-Panther** [comment]
please fill out the issue template and dont ignore it!

**Comment by T-IOOO** [comment]
Sorry, I was writing from my iphone and the "report bug template" crashes the github app

**Comment by tihoangyeudau** [comment]
i solved it: "should uncheck the cec detect"

**Comment by T-IOOO** [comment]
@tihoangyeudau It's not working for me
