### ISSUE TITLE
libX11.so.6 Hyperion 2.0.0-alpha.7 on LibreElec RPI 4

### ISSUE THREAD

**Issue by Xoofer** [hyperion-project/hyperion.ng#902]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I can't launch the alpha 7 on LibreElec on RPI4

I've an error at the launch : ` /storage/hyperion/bin/hyperiond: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`

#### Steps to reproduce

Install the alpha 7 on RPI4 on LibreElec

#### What is expected?

Launch of hyperiond

#### What is actually happening?

Crash on libX11.so.6 at the opening

**Comment by DutchTaurus** [comment]
I confirm same issue on RPi3 running LibreElec 9.2.3

**Comment by Paulchen-Panther** [comment]
Thanks for the feedback. The new CEC feature is causing problems. The pre-installed libCEC library in the Docker container refers to the X11 window system. Of course, this cannot be found on all ARM platforms. The bug will be fixed in the course of development. A temporary fix for the Alpha 7 packages will appear later today.

**Comment by tihoangyeudau** [comment]
This mean if i complie it in native rpi 3b+ instead of docker , i will not get this issue?

**Comment by Paulchen-Panther** [comment]
https://hyperion-project.org/threads/howto-hyperion-ng-libreelec-inoffiziell-unofficially.10463/page-3#post-26614

**Comment by tihoangyeudau** [comment]
Thank you

**Comment by Xoofer** [comment]
> 
> 
> https://hyperion-project.org/threads/howto-hyperion-ng-libreelec-inoffiziell-unofficially.10463/page-3#post-26614

Thank, it's working

**Comment by vzoltan** [comment]
I confirm same issue on RPi Zero W running LibreElec 9.2.3.


Kodi 18.7.1 (Linux Kernel 4.19.x)
LibreELEC-RPi.arm-9.2.3.img.gz
