### ISSUE TITLE
Apa107

### ISSUE THREAD

**Issue by azak1r** [hyperion-project/hyperion.ng#905]
Good day,

Not sure where to list this at so i made a blank issue. I recently got my hands on a couple of apa107 144/m strips. When i did some digging into these led's i found that they are the replacement for the apa102. 
Now when i connect them to the pi and power everything on only 101 led's light up one the strip. the rest is not working at all. 

I used the apa102 from the controller type dropdown in the webconfig.
Is there a way to get the entire strip to light up or is it something that i cannot fix myself and needs to be done on the software side?

running Hyperion alpha-6

**Comment by Paulchen-Panther** [comment]
please fill out the issue template and dont ignore it!
