### ISSUE TITLE
Have the Instance number as part of the logline

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#910]
## Feature request
As a Developer, I want to see the hyperion instance number / name as part of a logline (on the console, as well as on the UI)
so that I can correlate the individual log-outputs to an instance.

As a Developer, I want to be able to filter (e.g. grep) for a instance number / name and component easily
so that I can correlate the individual log-outputs to an instance and the given component.

**Comment by tpmodding** [comment]
Good idea!
