### ISSUE TITLE
Dispmanx on Hyperion 2.0.0-alpha.7 with LibreElec RPI 4 

### ISSUE THREAD

**Issue by Xoofer** [hyperion-project/hyperion.ng#913]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I've a blackscreen on the dispmanx on the alpha 7

I've the same problem on the standalone version of dispmanx

When I use the older version of the standalone dispmanx ( The alpha 6 ) it's work great in the alpha 7

Do you have any idea to fix that on non standalone version ?

#### Steps to reproduce

Select dispmanx on the internal frame grabber

#### What is expected?

Display kodi in the internal framegrabber

#### What is actually happening?

I've a blackscreen

#### System

Hyperion Server: 
- Build:       (HEAD detached at ffa2fd45) (Paulchen-Panther-69e9fa6d/ffa2fd45-1595517126)
- Build time:  Jul 24 2020 15:55:19
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: fr)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: LibreELEC (official): 9.2.1
- Arch:         arm
- Kernel:       linux (4.19.106 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by Paulchen-Panther** [comment]
> Do you have any idea to fix that on non standalone version ?

Yes, replace hyperiond with the armv7l artifact from PR #906

**Comment by Xoofer** [comment]
I replace the hyperiond, the problem is still present. After I tried to replace the entire files with the PR906 but it's always present.

Sometimes I've a glitched screen like this in the leds preview : 
![image](https://user-images.githubusercontent.com/68756211/88564901-207a8a80-d034-11ea-9ca2-c22402822b62.png)

**Comment by Paulchen-Panther** [comment]
Please stop the hyperion.ng service.
`systemctl stop hyperion.service`

Then please test the complete package. Just unpack somewhere and the execute the hyperiond in share/hyperion/bin.
Many thanks.

**Comment by Xoofer** [comment]
I've deleted my folder and replaced with package earlier but now to test I made a new folder and unpacked the package in the new folder ( And I have needed to delete the libz and libcec to launch hyperiond ).

The problem is the same I've sometime glitched screen, sometime blackscreen and now I had one good frame but only one frame ... ( The screen in leds preview is always freeze like the refresh does not work, it's strange, but it work with the DispmanX alpha 6 in standalone and usb grabber ).

The system info in Hyperion is : 

Hyperion Server: 
- Build:       (HEAD detached at pull/906/merge) (GitHub-b725aafc/4bd90962-1595722648)
- Build time:  Jul 26 2020 00:40:14
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.7-PR#906
- UI Lang:     auto (BrowserLang: fr)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: LibreELEC (official): 9.2.1
- Arch:         arm
- Kernel:       linux (4.19.106 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by Paulchen-Panther** [comment]
ok. will check

**Comment by Xoofer** [comment]
Ho god. I had just downloaded the wrong package ( build b725aafc instead of b94ad3db ).

I'm really sorry, it's working great with the last package

**Comment by tpmodding** [comment]
you are welcome
