### ISSUE TITLE
"set zlib back to system ignore list/revert pr #871" commit make raspberry pi cannot access to web ui IP

### ISSUE THREAD

**Issue by tihoangyeudau** [hyperion-project/hyperion.ng#920]
@Paulchen-Panther I confirm this commit make raspberry pi cannot access to web ui IP. i tested it many time and when i reverted it, the issue was solved. For linux, windows, macos, this commit works well

_Originally posted by @tihoangyeudau in https://github.com/hyperion-project/hyperion.ng/pull/904#issuecomment-666352703_

**Comment by tpmodding** [comment]
This is the last time I warn you, use the template. If you fool the next time, you will get a ban...

**Comment by tihoangyeudau** [comment]
sorry I forgot!
