### ISSUE TITLE
OffTopic!

### ISSUE THREAD

**Issue by mkcologne** [hyperion-project/hyperion.ng#922]
Guys!
Completely OffTopic, but I really appreciate, what u are doing here. 
The leap from hyperion to hyperion.ng ist outstanding and I'm really grateful, that u are giving this to the Community!
Cheers to all of you!
M.

**Comment by tpmodding** [comment]
Thank you!! i appreciate it, good to hear some praise!
But i will close this "issue" to have a overview with the isses

big thanks to all the devs!
@brindosch @Paulchen-Panther @Lord-Grey @SJunkies @m-seker and all contributers!
