### ISSUE TITLE
Reverse proxy with SSL not working with Hyperion.ng

### ISSUE THREAD

**Issue by m33ts4k0z** [hyperion-project/hyperion.ng#923]
Hello,

I saw a similar issue some months ago that it was immediately closed as a non-hyperion issue. Actually it is a hyperion issue and is really easy to fix. The problem lies in the hyperion.js file: 

`window.jsonPort = (document.location.port == '') ? '80' : document.location.port; 
window.websocket = (document.location.protocol == "https:") ? new WebSocket('wss://'+document.location.hostname+":"+window.jsonPort) : new WebSocket('ws://'+document.location.hostname+":"+window.jsonPort);`

When a proxy_pass is performed through a reverse proxy, the address bar doesnt have a port. that makes Hyperion WebSocket default to 80. So HTTP works. On the other hand, when SSL is used, Hyperion is again using port 80 since again the reverse proxy doesn't show a port on the address bar but that results in a protocol missmatch error. Since this file is baked into the binary, it is not easy to edit. However it would suffice if port 443 is used when https is detected.

**Comment by Lord-Grey** [comment]
@m33ts4k0z not sure what is the problem with binary...?
Update the following  file and do a Pull-Request:

https://github.com/hyperion-project/hyperion.ng/blob/c124e2136a47bfd488afdff54a2bf0d41da18e74/assets/webconfig/js/hyperion.js

**Comment by m33ts4k0z** [comment]
@Lord-Grey Sorry how can I update the file? I don't have access to do that. Do you mean download it locally, edit and compile?

**Comment by tpmodding** [comment]
Fork this repo to your account, make the changes, then you can submit a Pull request from your changed repo to our repo :-)

**Comment by m33ts4k0z** [comment]
I have now implemented and tested a fix that should cover all cases.

**Comment by m33ts4k0z** [comment]
After the fix is applied, you can use [this](https://pastebin.com/RTYa6qPA) configuration for Nginx reverse proxy. It includes auto SSL redirection and support for certbot certificate auto renewal if you use Let's Encrypt.

**Comment by tpmodding** [comment]
unraid ftw 👍
