### ISSUE TITLE
HDR tone mapping and FPS software limit feature... partially implemented.

### ISSUE THREAD

**Issue by awawa-dev** [hyperion-project/hyperion.ng#927]
[final_lut_fps_limit_2020_08_01_patch.diff.txt](https://github.com/hyperion-project/hyperion.ng/files/5011116/final_lut_fps_limit_2020_08_01_patch.diff.txt)
[lut_rgb.zip](https://github.com/hyperion-project/hyperion.ng/files/5011120/lut_rgb.zip)

#### What problem does this feature solve?
Using most of the video grabbers or matrix/scallers with HDR content causes color degradation (bleak colors).
We can't repair the hardware but we can somehow corrected it using 3D LUT HDR to SDR tone mapping.

HDR test file: "HDR10-Sony-Bravia-OLED demo" (before and after)
![03](https://user-images.githubusercontent.com/69086569/89152714-f2c9a000-d563-11ea-8f69-8f00098f868f.jpg)
![03-corrected](https://user-images.githubusercontent.com/69086569/89152730-f9f0ae00-d563-11ea-84d2-c59f227d8cb3.jpg)
![07](https://user-images.githubusercontent.com/69086569/89152740-fc530800-d563-11ea-90f5-9d0dfc4ab6df.jpg)
![07-corrected](https://user-images.githubusercontent.com/69086569/89152749-fe1ccb80-d563-11ea-991d-9c11a18d92f4.jpg)
![08](https://user-images.githubusercontent.com/69086569/89152754-ffe68f00-d563-11ea-9474-46809db4bb1d.jpg)
![08-corrected](https://user-images.githubusercontent.com/69086569/89152760-0117bc00-d564-11ea-8799-eef919400a9d.jpg)
![12](https://user-images.githubusercontent.com/69086569/89152765-0248e900-d564-11ea-958c-63aee2046461.jpg)
![12-corrected](https://user-images.githubusercontent.com/69086569/89152772-037a1600-d564-11ea-967b-36dd63086655.jpg)
![25](https://user-images.githubusercontent.com/69086569/89152778-04ab4300-d564-11ea-8c79-4d5382cafaad.jpg)
![25-corrected](https://user-images.githubusercontent.com/69086569/89152787-06750680-d564-11ea-81fe-dd76d7cc9588.jpg)
![28](https://user-images.githubusercontent.com/69086569/89152800-0b39ba80-d564-11ea-85a9-9b6abd0ebc4a.jpg)
![28-corrected](https://user-images.githubusercontent.com/69086569/89152808-0c6ae780-d564-11ea-942b-b61f86b23018.jpg)

![Clipboard01](https://user-images.githubusercontent.com/69086569/89173113-0a188580-d584-11ea-893c-9d8d9fc60510.jpg)

#### What does the proposed API look like?

I've prepared patch using solution from fast-hdr project. The attached RGB LUT file (lut_rgb.3d) must be present in the Hyperion configuration folder. There is also new settings that allows skipping frames to save resources.

#### Are you willing to work on this yourself?

Yes, it's already implemented.

**Comment by AalianKhan** [comment]
Is this related to this problem I am having? #822

**Comment by awawa-dev** [comment]
> Is this related to this problem I am having? #822

It's hard to say. I would need a screenshots from Hyperion www capture live preview to see if it can help. The translation used in that particular 3d lut matrix is for bt709 colorspace (used in modern 1080p/4k grabbers & cameras et, even though that they can't handle bt2020 correctly). Older analog devices could use different colorspace (for ex. I suppose that utv007 clones are using bt601 for pal/secam, my old clone doesn't handle bt2020/HDR signal at all).

**Comment by AalianKhan** [comment]
Hey @awawa-dev 
What screenshots do you need? My particular setup includes a wled instance with a raspberry Pi 3 and a Logitech C270. 
I'm not a programer as such but I am was just wondering if it is possible for Hyperion to auto correct the colors. For example a wizard comes up and you show a picture of red, then Hyperion knows the value should be red but it may not see red so it assigns the color of sees and sends red to the LEDs. Again I am not a programer so I am not sure.

**Comment by awawa-dev** [comment]
You can send me (on private) screenshots from this Hyperion preview section, but as I wrote before it means to solve bt2020 in bt709 issues and positive result will be a lucky shot:
![image](https://user-images.githubusercontent.com/69086569/89153453-2e189e80-d565-11ea-8f00-e6d8980d3103.png)
If anyone wants to test results you can send me your screens either. But please verify on 100% that the captured content is BT2020, I have attached in the first post how it will possible look (otherwise that test will say nothing).

**Comment by arifroni** [comment]
Hello, i have been looking for a solution for 4K hdr setup. I am thinking of buying a [HDFURY Dr.HDMI 4K](https://www.hdfury.com/product/dr-hdmi-4k/). this way i plan to use a constant sync for my AVR/shield. then i want to use a splitter (out1: 4K HDR (to TV) & out2: 1080p HDR to some grabber (any suggestion would be nice)). problem is with the HDR signal in the pi. 

then i came across to this thread and now i am asking would my setup will solve the HDR issue if i use the HDR>SDR LUT?
what is mjpeg capture device? any suggestion? amazon.de link would be nice.
