### ISSUE TITLE
Multiple Simultaneous Output/LED Hardware

### ISSUE THREAD

**Issue by jaffacake** [hyperion-project/hyperion.ng#931]
## Feature request
It'd be nice to be able to add multiple LED Hardware outputs & have them update simultaneously.

#### What problem does this feature solve?
Being able to use Hue Entertainment for Hue Plays alongside a traditional LED SPI or PWM. This would be useful to have LED strips driven behind the TV & ambient lighting up other parts of the room using Hue Entertainment.

#### What does the proposed API look like?
n/a

#### How should this be implemented in your opinion?
Update the LED Hardware section to allow multiple outputs (potentially restricted by the type, ie you can't run two SPI's at the same time)

#### Are you willing to work on this yourself?
No, sorry I don't know too much C++

**Comment by tpmodding** [comment]
you ever noticed the different instances you could use with different hardware?

**Comment by jaffacake** [comment]
Oh, I didn't notice that option 🤦  Maybe nesting the LED hardware into the same page/subpage of an instance would make it a bit more obvious. It doesn't seem very intuitive.

I'll just quietly close this....
