### ISSUE TITLE
DispmanX is broken on RPi4

### ISSUE THREAD

**Issue by m-seker** [hyperion-project/hyperion.ng#954]
- [x] I confirm that this is an issue rather than a question.

## Bug report

DispmanX is broken on RPi4. 

#### Steps to reproduce

Start hyperion on RPi4.

#### What is expected?

Hyperion should capture screen without breaking HDMI signal.

#### What is actually happening?

Hyperion can capture the screen without any problem. Logs are completely fine. However as soon as I start hyperion, the TV loses video signal.

I have to reboot the device to get the signal back. (Probably it can also be done without reboot but currently I don't know how)

#### System

Hyperion Server: 
- Build:       master (GitHub-4148e589/13205a9d-1596450699)
- Build time:  Aug  6 2020 00:53:21
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: tr-TR)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,xcb,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

**Comment by m-seker** [comment]
@Paulchen-Panther @tpmodding @Lord-Grey  should we default to X11 on RPi4 until this is fixed ?

**Comment by Paulchen-Panther** [comment]
It is about time that we tackled the V4L2/GBM implementation

**Comment by Paulchen-Panther** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=265883

**Comment by m-seker** [comment]
Disabling following line in ````/boot/config.txt```` fixes it :
````
#dtoverlay=vc4-fkms-v3d
````
https://www.raspberrypi.org/forums/viewtopic.php?t=266059

**Comment by jes1417** [comment]
> Disabling following line in `/boot/config.txt` fixes it :
> 
> ```
> #dtoverlay=vc4-fkms-v3d
> ```
> 
> https://www.raspberrypi.org/forums/viewtopic.php?t=266059
> 
> EDIT : Reboot required after changing.

I am running hyperion on a pi4 with retropie installed and I guess they use this setting, after commenting out the line and rebooting emulationstation failed to start.

I am getting pretty bad screen tearing while watching video content on the device through kodi and the plex add-on

**Comment by TheEsch** [comment]
Hello, after altering the config.txt now kodi shows following error:
ERROR: Unable to create GUI. Exiting

what can i do now?

System: 
-Raspberry 4 4GB
-Hyperion alpha8
-adalight

**Comment by m-seker** [comment]
@TheEsch Yes, it makes KODI unusable. PI4 is basically not supported yet.

**Comment by barbiermathieu91** [comment]
Hello,
I still have the same problem on a fresh raspberry OS et the Alpha 9.0.

Raspberry 4 2gb

Thank you for the amazing work

**Comment by Chaphasilor** [comment]
> should we default to X11 on RPi4 until this is fixed ?

@m-seker can we manually switch to using X11 as a workaround? it seems like `hyperion-x11` isn't installed by default though...

**Comment by Lord-Grey** [comment]
> @m-seker can we manually switch to using X11 as a workaround? it seems like `hyperion-x11` isn't installed by default though...

What OS are you running?

**Comment by Chaphasilor** [comment]
> > @m-seker can we manually switch to using X11 as a workaround? it seems like `hyperion-x11` isn't installed by default though...
> 
> What OS are you running?

Beta release of OSMC, based on Debian 10 (Buster) :)

**Comment by Lord-Grey** [comment]
Closed as duplicate to #983

**Comment by antoniocifu** [comment]
In my case (rpi4 + retropie + kodi) Everything was working fine until I deleted the lines of `/boot/config.txt`
```
hdmi_group=1
hdmi_mode=16
```
DispmanX stopped working and now that I have disconnected them again it has worked again
(These lines do not make Kodi go down to 1080, only at startup until it detects my HDMI and returns to 4K resolution)
