### ISSUE TITLE
Implement multithreading for the v4l2 grabber (aka poor performance for MJPEG grabbers)

### ISSUE THREAD

**Issue by awawa-dev** [hyperion-project/hyperion.ng#962]
## Feature request
One of the great feature on Hyperion-NG is MJPEG device support. This was one of the reason why I've migrated from the old version. Unfortunately even after implementing using of turbo-jpg that performance is poor: for 800x600 it's 7-8FPS for Rpi3+ (bottom hardware limit for grabber driver is 30FPS) and 100% CPU usage that causes delay in processing of the frames: the problem that appears on the forum from time to time. I suspect the result for Rpi4 is better by about 1-2 FPS if it scales to single thread performance. The reason is single thread processing and the jpeg frame decoding is taking it's toll: turbo-jpeg is very fast but we are limited by the single thread usage and hardware limit.

I've tried several approaches to make it parallel but only classic approach worked in the tests for me: make process_image as static method, pass all the parameters from the object as copies and run it on separated thread.

test A: frame emit replaced with debug output on the current version of image processor => 7-8FPS

[<img src="https://user-images.githubusercontent.com/69086569/89976429-b6372c00-dc68-11ea-9596-e3b64bb66bd5.jpg"  width="400"/>](https://user-images.githubusercontent.com/69086569/89976429-b6372c00-dc68-11ea-9596-e3b64bb66bd5.jpg)
[<img src="https://user-images.githubusercontent.com/69086569/89976434-b8998600-dc68-11ea-9d95-b4445105f069.jpg"  width="400"/>](https://user-images.githubusercontent.com/69086569/89976434-b8998600-dc68-11ea-9d95-b4445105f069.jpg)

test B: static version of the process_image running on a separated thread. Frame emit replaced with debug output, don't know if the logger is thread safe so std::cout came in handy. The frame is being copied to the new buffer before execution to avoid thread locking/access issues:

[<img src="https://user-images.githubusercontent.com/69086569/89976634-3a89af00-dc69-11ea-8c95-0df450d78406.jpg"  width="400"/>](https://user-images.githubusercontent.com/69086569/89976634-3a89af00-dc69-11ea-8c95-0df450d78406.jpg)
[<img src="https://user-images.githubusercontent.com/69086569/89976636-3c537280-dc69-11ea-9e16-3646975f7639.jpg"  width="400"/>](https://user-images.githubusercontent.com/69086569/89976636-3c537280-dc69-11ea-9e16-3646975f7639.jpg)

So it's seems that even Rpi3 is capable of processing 30FPS if it uses all available cores.

Main questions:
1) do we really need it? how it will work on other devices? New separate path only for jpeg frame&turbojpg library&multithread processing? the is some memory overhead for making a copy of the frame to the new buffer (relatively small cost for jpg encoding only)
2) how to emit new signal from the std:thread and safely return the result? google says to use QThread and worker (I'm not familiar with qt at all). The frame passed with emit is released on the end?

**Comment by awawa-dev** [comment]
OK, as un update & to answer some my own questions & present some results: I've implemented it.
Rewrite completely using QThread instead of std::threads and using signals/slots for communication. 

Thread's queue count is idealThreadCount. 
If new frame incomes and there is no free thread slot to process it will be skipped immediately (as on the screenshot) to make resources for a fresh one.
There's about 140ms constant delay - that the limit of Rpi's core to process single mjpeg frame and we can do nothing about it besides somehow manage to rewrite turbo-jpg as multi threaded library  ;)
Because as I wrote in the first post emit was disabled so now as I enable there is additional cost of processing the frame by Hyperion.
So no more 30FPS at 800x600 on Rpi3+ but 25FPS ;)
![cpu4](https://user-images.githubusercontent.com/69086569/90169206-96098900-dd9e-11ea-85e7-a281c51e76a9.jpg)

For now it's only on my forked branch "multithreading". I don't want to commit git pull now for some reasons.

1) Dont know if it's important feature or is it ideal solution and there is some thread-related risks. I'm a case of person with that mjpeg device and rpi that can't handle on manufacture settings and I have wrote it to use it on my own primary.

2) I think there is a need of refactoring v4l2grabber and there are some things in the git pull already...future git merge & tests would be a great pain on this stage.
MJPEG processing path is already splitted on the main branch: it's processed in the grabber only and other formats are using ImageResampler class for copying/cropping/resizing et. 
That's not a complaint because I think I it was done for performance tuning. But if would merge this patch that could start look really ugly. I tried some refactor on my own but it's not finish.

3) tested on x32 (VBox with camera) and armv7 (Rpi3+ with grabbers). Seems stable and for mjpeg v4l2 grabber performance increased greatly. No tread related issues or memory leaking so far (need more tests).
In test there was no sign of race hazard that could case out of sync frames: a condition could be added to avoid that theoretically scenario as frame index is passed to worked and forwarded later.

4) Could be easy extended for other color encoding but...point no 1 & 2 :)

5) And thread are threads. Things can go nasty in some unplanned scenarios on some setups & hardware.

Anyway you've got some results from that experiment to think about it ;)

**Comment by m-seker** [comment]
I would like to contribute optimizing this but I don't have much fre time anymore.

- What about hardware decoding? It should be possible with VideoCore. There are some examples with OpenMAX available but I'm on mobile now.

- What about SIMD? Is turbojpeg using NEON capabilities?

140ms for decoding a 800x600 jpeg sound a LOT.

**Comment by awawa-dev** [comment]
Thanks for a hint about videocore. I'll check it. 
I've used default turbo jpg configuration from Hyperion.

140ms could be predicted: that's ~time needed for current Hyperion release to process new frame on a single core. And that why we have 7-8FPS for MJPEG. 
For old generation mobile i7 on VBox the delay is ~65ms.

**Comment by Paulchen-Panther** [comment]
https://github.com/rlamarche/camera-toolbox/blob/master/app/gpu/omximagedecoder.cpp

**Comment by awawa-dev** [comment]
I narrowed down the problem, I've met it before but after implemented MT it's back with second strike
![crop](https://user-images.githubusercontent.com/69086569/90296807-e3642400-de8c-11ea-8681-f141e49b187c.jpg)
I think that's the main reason that cause that 140ms delay and maybe should be benchmarked. Replaced with memcpy the delay is reduced to 16ms and ~60ms using LUT transformation. That's a huge difference on live, that delay is even more important for me than FPS. But memcpy breaks the live preview: as I understand the data is shared between grabber and WWW using QSharedDataPointer. I cant fix it and I dont know any method to simply copy QImage to customized Image (beside point by point) but if I have to choose I choose that small delay then live preview because it's not the feature for every day use.

**Comment by awawa-dev** [comment]
Ok, I benchmarked that construct on much stronger i7:
![image](https://user-images.githubusercontent.com/69086569/90422658-77b3ce00-e0bb-11ea-95fc-ca379c439ed2.png)
![slow_curent](https://user-images.githubusercontent.com/69086569/90422677-7d111880-e0bb-11ea-95d9-7b836f7c4908.png)

vs memcpy:
![slow_mem](https://user-images.githubusercontent.com/69086569/90422693-8306f980-e0bb-11ea-8a1c-1fa9b8cfc123.png)

Memcpy is 10x faster on i7. Rpi doesnt have any chances with that code and higher resolution (or screen dimension cause memory aligjment problem in ImageData).

Is the any particular reason to use custom class ImageData in Image that can cause many problem with memory alignments on runtime? I saw some usage of memcpy/memmove in project and is it really safe? So that usage should be removed at all or I think image should be implemented differently. Image duplicate almost every aspect of QImage.

**Comment by m-seker** [comment]
@awawa-dev ImageData is an example of PIMPL. It saves a bunch of unneeded copies with this line : https://github.com/hyperion-project/hyperion.ng/blob/master/include/utils/Image.h#L42

If there is an alignment problem, it should be fixed with aligned_alloc inside ImageData.

BTW, I really lost track where your work is going. If memcpy works, then it means source and the destination are in the same format(RGB888), which means you can just get rid of the for loop and use memcpy. If that creates another set of problems, that means there other bugs which we need to fix.

And what do you mean with **stable** scanline ? What does stable mean here ?

**Comment by awawa-dev** [comment]
@m-seker Multithreading is finished and working perfectly. That not the case - I tested on program main thread as current version does.
Currently I'm fighting with that memcopy problem:
1) memcpy QImage - > Image that is emitted and it's WORKS :) Almost perfect BUT:
2) when we run Live view on the portal it's crashes for some resolution and screen decimation
3) or it produces such results and (dont know if it's related to 2):
decimation = 3
![error1](https://user-images.githubusercontent.com/69086569/90425566-3f62be80-e0c0-11ea-89af-bdd43075c9dc.png)
decimation = 1
![error2](https://user-images.githubusercontent.com/69086569/90425597-4ab5ea00-e0c0-11ea-9065-dee74bbfa896.png)
source (from grabber) and destination (to emit) screen match size (resize take cares of that and also I check it).

**Comment by awawa-dev** [comment]
> @awawa-dev ImageData is an example of PIMPL. It saves a bunch of unneeded copies with this line : https://github.com/hyperion-project/hyperion.ng/blob/master/include/utils/Image.h#L42

And how to use it with Qimage that is use all around in grabber? I ask because every example I found simply copies pixel by pixel from QIme to Image.

**Comment by m-seker** [comment]
I don't think it's an alignment problem. malloc(or new) is guaranteed to be aligned, see the following :
https://www.gnu.org/software/libc/manual/html_node/Aligned-Memory-Blocks.html

Stricter alignment should only be needed in case of SIMD.

The first preview of video shows that there is a mismatch between source and destination formats (I don't know which objects) and memcpy can't do the job. Probably you are trying to memcpy from an 32 bit image to a 24bit image. 

You need to make sure that the the source image (QImage in your case) should be in RGB888 [format](https://doc.qt.io/qt-5/qimage.html#format) if you want to copy it to Image<ColorRgb> with memcpy.

**Comment by m-seker** [comment]
Pixel by pixel copy is the worst possible solution but if the source and destination images are in different format, then there is no other way (except SIMD).

**Comment by awawa-dev** [comment]
@m-seker I can assure you that the format is RGB. 
The only setting that's changed is sizedecimation (I didnt introduced it, it causes both frames to resize)
**It happen's on the same instance run: no need to recompile program.**
In any case effect shouldn't by that drastic.
Decimation 3=> broken, set it back to 1 and it works.
And as can be seen on the first picture: colors are broken OK, but the lines width doesnt match each other.

I really double check everything and the last suspect is the aligment of that array of object in ImageData that causes memcpy to failed in some scenarios. If it's by design then OK, but we should use memcpy in any case of use of that object (but this also broke Rpi performance as in this case)

**Comment by Paulchen-Panther** [comment]
The problem of image distortion has been known for a long time (before m-seker rewrote the image class). It seems to be a bug in the QT implementation. In the past memcpy was also used for the QT grabber.

**Comment by awawa-dev** [comment]
@Paulchen-Panther thanks for explanation, but I'm not sure that the problem is in QT or QImage. I can memcpy to QImage to buffer and save it from the grabber to proof or overthrow it but it will change anything?

**Comment by Paulchen-Panther** [comment]
When I wrote the MJPEG implementation, I wasn't primarily concerned with speed. We can also move away from QImage and convert the data from TurboJPEG or libJPEG into the RGB888 format in some other way. Since QImage allows you to reduce or crop the image at the same time, this was the easiest way for me. I always have an open ear for suggestions for improvement.

**Comment by awawa-dev** [comment]
@Paulchen-Panther you've implemented it very well, I couldn't improve the speed on single thread :) 
Anyway turbojpg works on the buffer, it's bits() from QImage now. It's works well and if we would use byte[] array it doesn't make any difference but I can try. But at some moment we must transfer the data from buffer to custom Image and we cant do it fast because memcpy (using memptr from Image) will failed in some scenarios I think. As it happens now.

**Comment by awawa-dev** [comment]
@Paulchen-Panther , @m-seke only FYI: I've fixed point 2 from the list related to crashes on Rpi when the live feed in on.

JSonApi:setImage doesn't have any self-defense mechanism when it's forced to process 800x600 at almost 60FPS. Poor grabber performance on slower hardware can mask it.
On screen just temporally solution for my fork.
![image](https://user-images.githubusercontent.com/69086569/90443997-6976a980-e0dd-11ea-9640-cd60f1bb9093.png)
