### ISSUE TITLE
Random patterns when setting a solid color

### ISSUE THREAD

**Issue by max-te** [hyperion-project/hyperion.ng#963]
- [x] I confirm that this is an issue rather than a question.

## Bug report
When setting a solid color the LEDs are instead set to a - seemingly random - pattern.
The LED visualization in the web interface reflects this:

![2020-08-12_19:13:40](https://user-images.githubusercontent.com/870074/90045933-04334a80-dcd0-11ea-83cc-7f20f0895772.png)

Platform capture and effects both work as expected.
This worked fine on the version of hyperion.ng I had installed previously, though I'm not sure which version that was.

The pattern is not deterministic, but changes every time I re-set the color.

#### Steps to reproduce
Set a solid color in the remote control panel.
Open the LED visualization.

#### What is expected?
All LEDs have the color set above.

#### What is actually happening?
The LEDs have various different colors.

#### System

Hyperion Server: 
- Build:       
- Build time:  Aug  1 2020 02:16:44
- Git Remote:  
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  v4l2,framebuffer,amlogic,qt

Hyperion Server OS: 
- Distribution: CoreELEC (official): 9.2.3
- Arch:         arm64
- Kernel:       linux (3.14.29 (WS: 32))
- Browser:      Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0

**Comment by Paulchen-Panther** [comment]
> * Distribution: CoreELEC (official): 9.2.3

Wrong point of contact.
You are right here ->https://discourse.coreelec.org/

The bug has already been fixed -> https://github.com/hyperion-project/hyperion.ng/issues/897

**Comment by max-te** [comment]
Thanks! Sorry for the bother.
