### ISSUE TITLE
Hyperion as Server Service only

### ISSUE THREAD

**Issue by struthio** [hyperion-project/hyperion.ng#971]
#### What problem does this feature solve?
I currently use Hyperion is setup similar to this
Grabber(Host1) grabs screen and pushes it over network to hyperion(Host2).
In this setup on Host2 I do not need any of grabbers compiled in Hyperion (but disabing all grabbers in HyperionConfig.h.in cases compile to fail).

Also in such setup maybe it would be possible to drop most of lib requirements for compiling hyperion as 'server only'?

#### What does the proposed API look like?
There is no new API introduced to Hyperion. Just to be able to compile 'server only' hyperion.

**Comment by m-seker** [comment]
This is not a feature but a bug, it should compile without any grabber.
