### ISSUE TITLE
Adalight output device on Windows

### ISSUE THREAD

**Issue by Rickexe** [hyperion-project/hyperion.ng#975]
Hi, 

I have asked this question before. 

On the windows version of hyperion.ng what do you have to set the output device to in order for usb led devices like adalight to work. I have tried so many things with tty and comm ports but it's just not recognizing it. 

Last time you said I should ask on the forums but I can't post on the forums for some reason. Also, you are the developers so who better to ask than you. 

Thanks in advance

**Comment by tpmodding** [comment]
i will close this, cause you ignored the templates...
please open a new issues WITH THE TEMPLATE, provide some infos, what you did and what happend, and provide a log
thanks

**Comment by Rickexe** [comment]
omg you are so rude. you are never helping anyone on this github wtf. can no one tell me what to set as output device? oh well, fuck this project. hyperion is slow anyway.

**Comment by Rickexe** [comment]
going back to huestacean lol way better

**Comment by tpmodding** [comment]
Your welcome honey

**Comment by Rickexe** [comment]
least helpful developers. not helping their users. good luck. retard.

**Comment by tpmodding** [comment]
Thank you

**Comment by Lord-Grey** [comment]
@Rickexe 

> I have tried so many things

You might want to share what you tried, which debug output (logs) you have seen and what what environment you have tried running with.
The template tries guiding you providing the information we seem to be relevant getting in a position better addressing your question. Please bear in mind that not everybody has every device on our end and devices too often have some specific challenges, plus Windows is a quite new development.

So putting yourself in our shoes might help in understanding that the more information one share the higher the opportunity is getting things clarified and resolved (plus following some netiquette makes in general things running more smoothly).
