### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [hyperion-project/hyperion.ng#980]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [LedDeviceMultiLightpack](https://github.com/hyperion-project/hyperion.ng/blob/7389068a6631c1ae3c174d12c50874944f759bc0/libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.cpp#L30 "Destructor for LedDeviceMultiLightpack")
- [ProviderRestApi](https://github.com/hyperion-project/hyperion.ng/blob/c00d8e62fb5a57f57a142fcd51ad5822c8bef544/libsrc/leddevice/dev_net/ProviderRestApi.cpp#L40 "Destructor for ProviderRestApi")

**Comment by m-seker** [comment]
@elfring Hey thanks for contribution.

I did some cleaning already but will check again If I miss some of them:

https://github.com/hyperion-project/hyperion.ng/pull/958/files

**Comment by Paulchen-Panther** [comment]
Done in PR #1036 .
