### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [hyperion-project/hyperion.ng#981]
Would you like to [wrap any pointer data members](https://github.com/hyperion-project/hyperion.ng/blob/c00d8e62fb5a57f57a142fcd51ad5822c8bef544/src/hyperiond/hyperiond.cpp#L63 "Update candidate: HyperionDaemon class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by m-seker** [comment]
@elfring Thanks. This is already in my TODO list. We indeed need to convert some of the raw pointers to smart ones and some of them to references.

**Comment by elfring** [comment]
Thanks for your source code improvements.
