### ISSUE TITLE
HTTP JSON Control Instance not working

### ISSUE THREAD

**Issue by jonaspaulo** [hyperion-project/hyperion.ng#986]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Perform the JSON HTTP Call like:
https://ibb.co/4RSRrr7
<a href="https://ibb.co/4RSRrr7"><img src="https://i.ibb.co/9H4H55N/stopinstance.jpg" alt="stopinstance" border="0"></a><br /><a target='_blank' href='https://geojsonlint.com/'>json object validator</a><br />

#### What is expected?
Being able to turn OFF/ON the LED Instance via HTTP JSON

#### What is actually happening?
Nothing on the logs on the stopInstance command

On the startInstance command I can see that the command reaches the server. If I have the LED Instance already on I get (as I should):
```
Aug 31 18:32:49 raspberrypi hyperiond[1944]: 2020-08-31T18:32:49.606 hyperiond HTTPJSONRPC  : <DEBUG> JsonAPI.cpp:107:handleInstanceSwitch() | Client '::ffff:X.X.X.X' switch to Hyperion instance 0
Aug 31 18:32:49 raspberrypi hyperiond[1944]: 2020-08-31T18:32:49.654 hyperiond HYPERION     : <DEBUG> HyperionIManager.cpp:109:startInstance() | Can't start Hyperion instance index '0' with name 'First LED Hardware instance' it's already running or queued for start
```
If the LED Instance is already off it doesn't do anything

#### System

Hyperion Server: 
- Build:       (HEAD detached at ffa2fd45) (Paulchen-Panther-69e9fa6d/ffa2fd45-1595517126)
- Build time:  Jul 24 2020 15:49:41
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

**Comment by Paulchen-Panther** [comment]
Wenn es sich nicht in der WebUI unter Instanzenverwaltung an oder ausschalten lässt, wird das mittels Json-API auch nicht funktionieren. Erst Kopf anstrengen dann Issue erstellen. Meine Fresse.

**Comment by jonaspaulo** [comment]
Sorry I don't understand. It cannot be switched off in the WEB UI?

I can switch it off here:


<a href="https://imgbb.com/"><img src="https://i.ibb.co/VxRywwm/aa.png" alt="aa" border="0"></a><br /><a target='_blank' href='https://geojsonlint.com/'>geojson online map</a><br />


I thought this API Call did the same or not?

Thanks and sorry to bother you :)

**Comment by jonaspaulo** [comment]
Sorry I don't understand. It cannot be switched off in the WEB UI?

I can switch it off here:


<a href="https://imgbb.com/"><img src="https://i.ibb.co/VxRywwm/aa.png" alt="aa" border="0"></a><br /><a target='_blank' href='https://geojsonlint.com/'>geojson online map</a><br />


I thought this API Call did the same or not?

Thanks and sorry to bother you :)

**Comment by jonaspaulo** [comment]
Sorry I don't understand. It cannot be switched off in the WEB UI?

I can switch it off here:


<a href="https://imgbb.com/"><img src="https://i.ibb.co/VxRywwm/aa.png" alt="aa" border="0"></a><br /><a target='_blank' href='https://geojsonlint.com/'>geojson online map</a><br />


I thought this API Call did the same or not?

Thanks and sorry to bother you :)

**Comment by jonaspaulo** [comment]
Sorry I don't understand. It cannot be switched off in the WEB UI?

I can switch it off here:


<a href="https://imgbb.com/"><img src="https://i.ibb.co/VxRywwm/aa.png" alt="aa" border="0"></a><br /><a target='_blank' href='https://geojsonlint.com/'>geojson online map</a><br />


I thought this API Call did the same or not?

Thanks and sorry to bother you :)

**Comment by jonaspaulo** [comment]
Sorry I don't understand. It cannot be switched off in the WEB UI?

I can switch it off here:


<a href="https://imgbb.com/"><img src="https://i.ibb.co/VxRywwm/aa.png" alt="aa" border="0"></a><br /><a target='_blank' href='https://geojsonlint.com/'>geojson online map</a><br />


I thought this API Call did the same or not?

Thanks and sorry to bother you :)

**Comment by Paulchen-Panther** [comment]
> I thought this API Call did the same or not?

Nein. Damit wird die Instanz nur Pausiert aber nicht abgeschaltet. Abschalten ist hier drin:
![image](https://user-images.githubusercontent.com/16664240/91752540-c76bbc80-ebc6-11ea-9576-26264b1ef383.png)

**Comment by Paulchen-Panther** [comment]
Stop vs Disable.

**Comment by jonaspaulo** [comment]
Ok. Thanks for clearing it up. Is there any other call then to do the Disable action? Either via REST or through hyperion CLI or other?
Thanks

**Comment by Paulchen-Panther** [comment]
Yes.
https://docs.hyperion-project.org/en/json/Control.html#control-components
https://docs.hyperion-project.org/en/json/Control.html#components-ids-explained

Component: ALL
