### ISSUE TITLE
Changing effect at a given priority should issue a priorities update (I think)

### ISSUE THREAD

**Issue by dermotduffy** [hyperion-project/hyperion.ng#992]
Hyperion 2.0.0-alpha.7

- [x] I confirm that this is an issue rather than a question.

## Bug report

If an effect is visible at a given priority, setting a new effect at the same priority should issue a priorities update (or at least I am surprised it does not).

#### Steps to reproduce

   1. Subscribe to Hyperion priority updates (in one terminal)
```
$ echo '{"command":"serverinfo", "subscribe":["priorities-update"] }' | nc hyperion 19444
```

   2. Set an effect via the API (in a different terminal).
```
echo '{"origin": "Home Assistant", "priority": 128, "effect": {"name": "Candle"}, "command": "effect"}' | nc hyperion 19444
{"command":"effect","success":true,"tan":0}
```

   3. Set a different effect via the API (in the same terminal).
```
$ echo '{"origin": "Home Assistant", "priority": 128, "effect": {"name": "Light Clock"}, "command": "effect"}' | nc hyperion 19444
{"command":"effect","success":true,"tan":0}
```

#### What is expected?

Since the effect has changed at that given priority, I would expect a priorities-update to appear in the subscribed terminal.

#### What is actually happening?

No priority subscription update will be observed in the first terminal.

(If you issue a clear in between, the priority updates are as expected)

#### System

Hyperion Server: 
- Build:       master (GitHub-f719f0b/838092e-1597257777)
- Build time:  Aug 19 2020 04:01:56
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51+ (WS: 32))
- Browser:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/53

**Comment by Paulchen-Panther** [comment]
Why should a 'priorities update' be sent if the priority does not change?
An 'effects-update' will be sent if this is registered.

**Comment by dermotduffy** [comment]
Aren't effects-update for the possible [effects list](https://docs.hyperion-project.org/en/json/Subscribe.html#effects-updates), rather than an active effect? (which is in priorities-update).

What I describe does work for setting a different color at the same priority, but not for a different effect at the same priority.

**Comment by Paulchen-Panther** [comment]
I'll take a closer look at that.

**Comment by Paulchen-Panther** [comment]
@dermotduffy 
Can you please test my PR #1036 ?

**Comment by dermotduffy** [comment]
@Paulchen-Panther This does not appear to be fixed, or behaving as expected, when I used the same test case as in my original report.

Starting from a Hyperion instance with no effect running. Upon executing the first effect call (Step #2 above) I receive this:

```
{"command":"priorities-update","data":{"priorities":[{"active":false,"componentId":"EFFECT","origin":"Home Assistant@IP","owner":"Candle","priority":128,"visible":false},{"active":false,"componentId":"V4L","origin":"System","priority":240,"visible":false}],"priorities_autoselect":true}}
{"command":"priorities-update","data":{"priorities":[{"active":true,"componentId":"EFFECT","origin":"Home Assistant@IP","owner":"Candle","priority":128,"visible":true},{"active":false,"componentId":"V4L","origin":"System","priority":240,"visible":false}],"priorities_autoselect":true}}
```

I think I should have received 1 callback here, rather than 2, showing the effect being active.

When I send the second effect call (Step #3 above) I receive nothing at all, and would have respected to receive 1 additional call (that shows the new effect priority).

**Comment by Paulchen-Panther** [comment]
A little change. Could you test the PR again?
Here is a proof: 
![record_000001](https://user-images.githubusercontent.com/16664240/95566345-b9108c00-0a21-11eb-8b29-f93aafaf426b.gif)

**Comment by dermotduffy** [comment]
@Paulchen-Panther OK, this was a bit confusing. This issue _does_ appears to be resolved, but something different has changed that caused confusion:

   * The effect names have changed case (used to be "Light Clock", now "Light clock") and so (as per my reproduction steps) things were not working as anticipated until I figured out the effect names were different. I don't know if this is intentional or not?
   * Setting an effect that does not exist returns success, and it should not:

```
$ echo '{"origin": "Home Assistant", "priority": 128, "effect": {"name": "This is not a real effect"}, "command": "effect"}' | nc hyperion 19444
{"command":"effect","success":true,"tan":0}
```

So this issue might resolved, but there are 1 or maybe 2 others hidden in here.

**Comment by Paulchen-Panther** [comment]
> * The effect names have changed case (used to be "Light Clock", now "Light clock") and so (as per my reproduction steps) things were not working as anticipated until I figured out the effect names were different. I don't know if this is intentional or not?

According to Git history, there was no change in the name of the effect.
https://github.com/hyperion-project/hyperion.ng/commits/master/effects/light-clock.json

> * Setting an effect that does not exist returns success, and it should not:

I'll have a look at myself. Thanks for the feedback. 👍

**Comment by dermotduffy** [comment]
Thanks @Paulchen-Panther
