### ISSUE TITLE
Extreme delay between picture on TV and on LEDs

### ISSUE THREAD

**Issue by PaulNBerlin** [hyperion-project/hyperion.ng#994]
Hi, I am quite new to hyperion. I got it working on my pi zero. It works smooth with my ws2812b leds connected to a nodemcu with wled. 

Running videos from the pi itself (eg. retropi) is working flawlessly. 

But running picutures from external sources like my receicer/playstayed resulted in extrem delay between picture and led lights (1-2 seconds).
I am using the following grabber which might already cause the issue (but I dont know): https://de.aliexpress.com/item/4001061243548.html?spm=a2g0x.search0302.3.207.684c77527YNJQg&ws_ab_test=searchweb0_0,searchweb201602_0,searchweb201603_0,ppcSwitch_0&algo_pvid=181c3825-501c-4bd5-b134-3075fcab9429&algo_expid=181c3825-501c-4bd5-b134-3075fcab9429-28  

I already tried a lot of changes in the config without success. 

Is there anybody who can help?

Edit: User manual of the grabbers says: 
Computer HW config reqs: 
CPU: PC i5-3400 or above; NB i7-3537U 2.0GHZ or above
Graphics card: PC NVIDIA GT630 or above; NC NVIDIA GT735M or above
Run memory: 4G RAM

**Comment by PaulNBerlin** [comment]
@Paulchen-Panther may I ask why you close my issue without any comment?

**Comment by m-seker** [comment]
> @Paulchen-Panther may I ask why you close my issue without any comment?

Follow the issue template please.
