### ISSUE TITLE
Zeroconf does not work

### ISSUE THREAD

**Issue by dermotduffy** [hyperion-project/hyperion.ng#995]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Zeroconf does not work as [advertised](https://docs.hyperion-project.org/en/api/Detect.html#zeroconf) (pun intended).

#### Steps to reproduce

Run `avahi-browse` on the local network, or on the machine hosting Hyperion:

```
(~) $ avahi-browse -r _hyperiond-http._tcp
```

... or ...

```
(~) $ avahi-browse -a | grep -i hyperion
```

#### What is expected?

Some form of output (as per diagram shown on [zeroconf instructions](https://docs.hyperion-project.org/en/api/Detect.html#zeroconf)).

#### What is actually happening?

No output.

#### System

```
Hyperion Server: 
- Build:       master (GitHub-f719f0b/838092e-1597257777)
- Build time:  Aug 19 2020 04:01:56
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51+ (WS: 32))
- Browser:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 
```

**Comment by m-seker** [comment]
Thanks !

**Comment by dermotduffy** [comment]
@m-seker Thanks!

I took the liberty of doing a build from head with this fix applied, but it does not appear to have fixed the problem, were you able to verify the fix on your end?

**Comment by m-seker** [comment]
> @m-seker Thanks!
> 
> I took the liberty of doing a build from head with this fix applied, but it does not appear to have fixed the problem, were you able to verify the fix on your end?

Interesting.

````
┌─[murse@Arch64] - [~/projects/hyperion.ng/build] - [Mon Sep 07, 23:37]
└─[$]> avahi-browse -a
+ docker0 IPv4 Arch64:8092                                   _hyperiond-http._tcp local
+ docker0 IPv4 Arch64:8090                                   _hyperiond-http._tcp local
+ enp0s3 IPv6 Arch64:8092                                   _hyperiond-http._tcp local
+ enp0s3 IPv6 Arch64:8090                                   _hyperiond-http._tcp local
+ enp0s3 IPv4 Arch64:8092                                   _hyperiond-http._tcp local
+ enp0s3 IPv4 Arch64:8090                                   _hyperiond-http._tcp local
+     lo IPv4 Arch64:8092                                   _hyperiond-http._tcp local
+     lo IPv4 Arch64:8090                                   _hyperiond-http._tcp local
````

Can you make sure -DENABLE_AVAHI=ON while configuring with cmake ?

**Comment by dermotduffy** [comment]
```
-- ENABLE_AVAHI = ON
```

... in the build output. However, might be an issue with how I'm building ... investigating.

**Comment by dermotduffy** [comment]
Yes, it was a build problem. Got it to work!

However, I note that only `_hyperiond-http._tcp` works, but `_hyperiond-flatbuf._tcp` and `_hyperiond-json._tcp` still do not (it's the latter I'm looking for in my usecase).

**Comment by m-seker** [comment]
> Yes, it was a build problem. Got it to work!
> 
> However, I note that only `_hyperiond-http._tcp` works, but `_hyperiond-flatbuf._tcp` and `_hyperiond-json._tcp` still do not (it's the latter I'm looking for in my usecase).

I'll have a look after work.

**Comment by m-seker** [comment]
@dermotduffy Can you give another try ?

**Comment by dermotduffy** [comment]
Looks good! Thank you!

```
+ eno1 IPv6 pi:8092                               _hyperiond-http._tcp local
+ eno1 IPv6 pi:8090                               _hyperiond-http._tcp local
+ eno1 IPv4 pi:8092                               _hyperiond-http._tcp local
+ eno1 IPv4 pi:8090                               _hyperiond-http._tcp local
+ eno1 IPv6 pi:19400                              _hyperiond-flatbuf._tcp local
+ eno1 IPv4 pi:19400                              _hyperiond-flatbuf._tcp local
+ eno1 IPv6 pi:19444                              _hyperiond-json._tcp local
+ eno1 IPv4 pi:19444                              _hyperiond-json._tcp local
```
